### ISSUE TITLE
Cant get it on mac

### ISSUE THREAD

**Issue by SimonJames89513** [bluemagic123/tModLoader#10]
I download the file than open and put terraria into the vanilla file but when i run the code it does nothing

**Comment by JavidPack** [comment]
We just released a mac version a few minutes ago: http://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/#Download

**Comment by SimonJames89513** [comment]
Wow thanks!

**Comment by SimonJames89513** [comment]
In the read me file it says "you must navigate this to terminal." I was just wondering what "this" was Thanks

**Comment by bluemagic123** [comment]
Resolved on the forums.
