### ISSUE TITLE
GlobalItem's Save() and Load() methods aren't working

### ISSUE THREAD

**Issue by CXUtk** [bluemagic123/tModLoader#102]
I have noticed that the method **Save(Item item)** and  **Load(Item item, TagCompound tag)** are not being called when I trying use them. I tried to use MessageBox to ensure whether they being called and the result is that they didn't.

**Comment by JavidPack** [comment]
Did you use the needs saving hook?

**Comment by CXUtk** [comment]
Well, then how about Loading hook?

**Comment by JavidPack** [comment]
If there is saved data the load hook should be called

**Comment by CXUtk** [comment]
Well, I haven't noticed that. Thanks for your help.
