### ISSUE TITLE
Materials in recipe group not displaying "Material" in game

### ISSUE THREAD

**Issue by Minesap** [bluemagic123/tModLoader#105]
As you can see in the screenshot Rainbow String is not displaying "Material" although it is able to be used in the crafting recipe for the Amethyst Yoyo (bottom left). I've already crafted the yoyo multiple times using all the strings that I inputted in the recipe group. This is mostly a visual bug but this makes it so you cannot put other strings like Black String to the Guide for help.

![5426006595b7389e26cc3446300368f0](https://cloud.githubusercontent.com/assets/25136652/21964688/673f8ed2-db16-11e6-9dca-f9913c43d367.png)

**Comment by JavidPack** [comment]
Fixed with https://github.com/bluemagic123/tModLoader/commit/7e330dab187bae9999ae3cb6a44a8c75516063e5
