### ISSUE TITLE
Mods for mac

### ISSUE THREAD

**Issue by Atlas19220** [bluemagic123/tModLoader#106]
I want to make a mod form my Terraria, i watched a tutorial video step-by-step and when i tried to build my mod it crashed. Can somebody help please?(using mac)

**Comment by NyxZoldrent** [comment]
I don't think this is the place for this kind of issue. You should post this on the forum page, or try to get help on discord.

**Comment by gorateron** [comment]
Okay first of all, when you need help with an error, **post the actual error and code**. We can't do anything if we don't see exception logs and code used.
