### ISSUE TITLE
OnRespawn hook

### ISSUE THREAD

**Issue by XVoltzX** [bluemagic123/tModLoader#107]
Weirdly enough, tModLoader lacks a hook that is called when a player respawns. It's not something major at all but I feel like it could be useful to others, if you don't have the time I could attempt opening up a pull request.

**Comment by XVoltzX** [comment]
That's interesting, I'm guessing it would be best if it were called from the local player's machine.

**Comment by gorateron** [comment]
I think it should be sent to all clients. What if a mod wants something to happen on a player respawn? Would it only work for the player respawning...?

**Comment by XVoltzX** [comment]
I don't know, I guess it's best to do what you guys think is better.
