### ISSUE TITLE
ModPlayer.Load (and likely other overrideable class's .Load methods) are called even when the player has no save data

### ISSUE THREAD

**Issue by hamstar0** [bluemagic123/tModLoader#108]
I advise against removing this behavior, but some indication of this to the code (other than checking individual missing TagCompound fields) might be nice.

**Comment by gorateron** [comment]
Why was this closed @hamstar0 ?

**Comment by hamstar0** [comment]
Again, don't recommend removing this behavior.  Simply using TagCompound.HasTag is able to work around it.

Now whatever that matter of ModPlayer.Initialize being called every frame on the client was about, on the other hand...

**Comment by JavidPack** [comment]
I just checked the source code and the debugger. ModPlayer.Load is NOT called on a particular player unless you have data saved for that player for that ModPlayer.

**Comment by hamstar0** [comment]
Hmm, I could've sworn my log file output .Load calls in the main menu for a newly created character.

**Comment by JavidPack** [comment]
Well yeah, because save is called when you create the newly created character. If you copy in a .plr or create the character while the mod is disabled, it won't call load because there is no data.

**Comment by hamstar0** [comment]
Here's a log file of creating 2 new characters (with no others characters also listed, and no other mods but the logger), deleting them, then creating one more: https://hastebin.com/janunewole.css

I'm confused.

**Comment by JavidPack** [comment]
ok, so what are you confused about then?  From what I can see it is as I explained

**Comment by hamstar0** [comment]
Sorry to edit before reply: ModPlayer.Load is called more times than I can account for with the number of players.
