### ISSUE TITLE
ModPlayer.GetWeaponKnockback not working for melee weapons

### ISSUE THREAD

**Issue by dtimTerraria** [bluemagic123/tModLoader#115]
The GetWeaponKnockback for melee weapons is only being called when the player hovers over the item and the only item that is adjusted is the clone that is used for displaying.  Any hits done with the weapon are not receiving the knockback change according to the numbers provided to ModifyHitNPC (and breakpoints don't get hit).

Items that produce a projectile work correctly.

ModItem.GetWeaponKnockback appears to be the same.

**Comment by JavidPack** [comment]
Can you provide a simple mod so we can test this.

**Comment by dtimTerraria** [comment]
This should be adding 10 knockback via GetWeaponKnockback in ModPlayer, ModItem, and GlobalItem
None of them work for melee weapons as far as I can tell.

[knockbackmod.zip](https://github.com/bluemagic123/tModLoader/files/737967/knockbackmod.zip)

If you load the VS project you'll need to change the references and build settings, etc because my tModLoader is in a different place than default.

**Comment by Jofairden** [comment]
You should most likely use [ModifyHitNPC](https://github.com/bluemagic123/tModLoader/wiki/ModItem#public-virtual-void-modifyhitnpcplayer-player-npc-target-ref-int-damage-ref-float-knockback-ref-bool-crit) and change the knockback there. Afaik GetWeaponKnockback is used for tooltips.

**Comment by dtimTerraria** [comment]
Then it shouldn't affect ranged and magic weapons.  Either way is fine but it's inconsistent right now.
