### ISSUE TITLE
Mods not loading in load order.

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#117]
Linux and windows load in different order.

This causes item ID mismatches.

**Comment by Shockah** [comment]
I didn't look into the code, but I suspect it may also load in different order on two Windows machines, depending on the circumstances - at least if the order is purely based on how the underlying IO returns the file list. I can imagine it returning in different order for, say, different file date metadata or different file systems.

**Comment by Jofairden** [comment]
Related commit: fde396f7511771f23f818999052a636cc9861bda
