### ISSUE TITLE
Significant lag when UI elements are drawn on the screen

### ISSUE THREAD

**Issue by rgon842** [bluemagic123/tModLoader#120]
I'm experiencing an issue where every time that a menu or other type of UI element is being drawn on the screen (such as the Item/NPC browsers from the Cheat Sheet mod) Terraria's FPS drops to 15-20 from 60 and the game becomes incredibly laggy. If I press F11 to hide the UI, the lag completely disappears (back to 60 FPS); pressing F11 again to turn the UI on sees the lag return.

For troubleshooting, I have uninstalled and reinstalled both Terraria, .NET Framework 4.5.2, and XNA 4.0, with no avail. The issue does not occur when playing unmodded Terraria (after uninstalling, deleting the My Documents/My Games/Terraria folder and reinstalling from Steam), it is only after installing tModLoader v 0.9.1 that the issue occurs. Running Terraria both in single player and multiplayer does not make a difference (I'm hosting the server on the same machine where Terraria is running).

I can confirm that the issue is specific to the desktop computer; I have installed both Terraria and tModLoader 0.9.1 on another PC (a laptop with lower specs than the desktop) and Terraria works with no issues. Below I've included the specs for both workstations:

Desktop Computer (the one experiencing the issue):
> Procesor: Intel Core i5-2500K (Sandy Bridge, 4 cores) @ 3.30 GHz 
> Memory: 16 GB RAM
> Hard Drive: 250 GB SSD
> Graphics: AMD Radeon HD6900 (2 GB)
> OS: Windows 7 Ultimate SP1 (64-bit)
> .NET Framework 4.5.2 x64 is installed on this machine

Laptop Computer (no issues occur on this machine):
> Processor: Intel Core i5-6200U (Skylake, 2 cores) @ 2.80 GHz
> Memory: 8 6B RAM
> Hard Drive: 450 GB SSD
> Graphics: Intel Integrated HD Graphics 520
> OS: Windows 10 Pro (64-bit)
> .NET Framework 4.6 is installed on this machine (built-in on Windows 10)

**Comment by JavidPack** [comment]
Can you list the mods you have enabled while experiencing the lag?

**Comment by rgon842** [comment]
Only the Cheat Sheet mod, to make sure that excessive memory usage from a lot of mods wasn't an issue.

Regardless, I was able to determine the source of the issue and address it, even though it took reformatting my primary hard drive and install a fresh copy of Windows 10 Pro 64 bit: 

There is an application from StarTech called USB Display Device (Trigger Family) that is used as a software driver to control a DVI-to-USB conversion dongle, which allows me to connect a second monitor to my desktop PC and extend my displays. It appears that this driver somehow mucks with how tModLoader draws menus and UIs, as the lag was gone after installing Windows 10, but returned after installing this driver. Uninstalling this driver and rebooting my machine afterwards got rid of the lag altogether; I was able to test this with multiple mods loaded, including very large ones suchas Thorium, Crystilium, Calamity, etc. Here's a link to the product page: [https://www.startech.com/AV/USB-Video-Adapters/USB-DVI-External-Multi-Monitor-Video-Adapter~USB2DVIE2#dnlds](url)

I will have to live with having to uninstall and reinstall this driver whenever I want to play Terraria, as not having that second monitor is a killer (as I also use this PC for work), but in the end a resolution was found for this issue. Please close this issue and consider it resolved.
