### ISSUE TITLE
Allow translation in mods

### ISSUE THREAD

**Issue by Kimi-Arthur** [bluemagic123/tModLoader#134]
Since Terraria will have full translation starting from 1.3.5, it will be great if tModLoader supports a similar pattern and make the switch of language the same way as the vanilla one.
Thanks!

**Comment by Jofairden** [comment]
I see as why jopo added the 'Far in Future' label. This will be quite a large undertaking and not to mention, this is actually already possible for mods, but with their own implementation.

**Comment by bluemagic123** [comment]
Resolved with the recent updates to 1.3.5 (from 57418dd6a3e7abbc472dc0403e5ef415f80124fe to 00240dafc313bf708947a7719ba7d7d1d55a4d7a)
