### ISSUE TITLE
Add documentation for useful vanilla classes and members

### ISSUE THREAD

**Issue by Kimi-Arthur** [bluemagic123/tModLoader#135]
Mod developers may need to use vanilla classes and members sometimes. It will be helpful if the new documentation can contain information for that, especially the patches tModLoader is adding.

**Comment by JavidPack** [comment]
Vanilla changes are enumerated here: https://github.com/bluemagic123/tModLoader/wiki/Vanilla-Class-Changes

Useful Vanilla methods: https://github.com/bluemagic123/tModLoader/wiki/Useful-Vanilla-Methods
