### ISSUE TITLE
Reloading mods

### ISSUE THREAD

**Issue by rayman89** [bluemagic123/tModLoader#136]
When reloading multiple mods at once if one of them fails all the mods will be re reloaded except that one this becomes bothersome when there is more than 1 mod that fails and you reload a lot of mods. Could you consider changing it so when this happens it continues reloading the next mod instead of starting all over again?

Also could you make it if you add or update 1 mod you don't need to reload all the enabled mods just the one you changed/added?

**Comment by JavidPack** [comment]
Not really, there are so many things that need to happen in a specific order that doing this is impossible.

**Comment by Chicken-Bones** [comment]
The problem is you have no idea how badly that mod failed. It might have failed in such a manner that will cause all mods after it to fail, even if they don't have problems themselves

**Comment by Bogdan-G** [comment]
skip mod in cycle list? remove unused data if no mod in list?
