### ISSUE TITLE
tmodloader crashes visual studio 2017 when using debugger

### ISSUE THREAD

**Issue by LyraelRayne** [bluemagic123/tModLoader#137]
I set up visual studio as per https://github.com/bluemagic123/tModLoader/wiki/Developing-with-Visual-Studio except using 2017 because I can't get a copy of 2015 anymore without an MSDN subscription.

Terraria loads, but when my mod is loaded VS crashes with an access violation.

Not sure if this is something you can fix or something MS would have to fix.  Also not sure what kind of information would help you with figuring it out, so let me know what you need.

tmodloader version is 0.9.1 and Terraria is 1.3.4.4

**Comment by JavidPack** [comment]
Other devs have tried with VS 2017, but so far we think it's a VS 2017 bug. It might be something we'll try again once VS 2017 Update 1 happens.

Also, Visual Studio 2015 Community seems to still be downloadable here: https://www.microsoft.com/en-us/download/details.aspx?id=48146

**Comment by LyraelRayne** [comment]
Ooh! Going to give that a crack now. Thanks.

**Comment by Chicken-Bones** [comment]
hello there, I'm roughly aware of the source of the bug, but haven't had time to pin it down. Reading and writing certain mod assemblies with Mono.Cecil causes VS to crash when the debugger is attached

**Comment by LyraelRayne** [comment]
OK I got it working with VS2015 thanks to your link. Much easier working when you can inspect variables! I'll leave it up to your discretion whether to leave this open for others' information or close it.

**Comment by Jofairden** [comment]
I feel tempted to try out VS 2017 now that it's out of RC, but the only issue is that it botches the 2015 install.. ;/

**Comment by LyraelRayne** [comment]
I installed 2015 after installing 2017 and they both seem to work (although I haven't used 2017 for anything since installing 2015)

**Comment by Jofairden** [comment]
I'll be installing 2017 on my work laptop because I have an SSD, will report results.

**Comment by Jofairden** [comment]
Woops, forgot we had this. Referenced here with explanation: #153
