### ISSUE TITLE
ExampleMod's reference to Terraria code is broken.

### ISSUE THREAD

**Issue by PJB3005** [bluemagic123/tModLoader#14]
Considering ExampleMod is in `/ExampleMod` (`/` being this repo), the reference should be `../src/tModLoader/Terraria.csproj`.

It isn't, it's `../../../../../../VideoGameHacking/Terraria/tModLoader/src/tModLoader/Terraria.csproj`.

It's obviosously for where @JavidPack put his folders (git blame), but it should really be more generic.

**Comment by itamargreen** [comment]
Where is it referenced?

**Comment by PJB3005** [comment]
[`ExampleMod/ExampleMod.csproj`](https://github.com/bluemagic123/tModLoader/blob/master/ExampleMod/ExampleMod.csproj#L150)

**Comment by bluemagic123** [comment]
To be honest I don't even know why ExampleMod has a csproj file. I personally never made one and never used it, since it's a small enough project for me to use a normal text editor.
