### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by Tyfyter** [bluemagic123/tModLoader#140]
the new documentation doesn't seem to have the most important parts of a mod api documentation page: methods that the modder can call, and methods the modder can create to be called on certain events

**Comment by JavidPack** [comment]
I'm not sure I follow. The documentation has information on all the hooks we've made. Everything vanilla related is easily inferred from the method signatures Visual Studio will autocomplete for you. There is also a section in the wiki about useful vanilla methods.

**Comment by Jofairden** [comment]
I'm not sure what you mean either, @Tyfyter, **[the new documentation](http://bluemagic123.github.io/tModLoader/html/annotated.html)** contains all methods a modder can call. You can use the search bar to find what you're looking for. Some documentation may still be missing at this point in time, but methods should still be there.
