### ISSUE TITLE
Build all will complain about references it doesn't need to

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#143]
Click Build all with a mod with references in your Mods folder and it'll be added to the list of mods to build. Example: Empty Mod Sources folder, Boss Checklist.tmod in Mods folder.

**Comment by Chicken-Bones** [comment]
I'll look into this

**Comment by Chicken-Bones** [comment]
Fixed 98ca71c140c933ea04c7eb92f3e104f0ac9d0bf1
