### ISSUE TITLE
v0.9.2.2 Should we dynamically add content in mods/sources/browser?

### ISSUE THREAD

**Issue by Jofairden** [bluemagic123/tModLoader#149]
To clarify:
Right now the user has to wait for the entire load to complete, e.g: download data, parse, handle items, add handled items to UIList. (all items show up at the same time) Maybe we should follow an order of: download data, parse, handle items -> (handle item, add handled item to UIList) The only benefit is that UI will feel more dynamic, and that's about it. It's a small change which is easily done. If we agree, the UILoader might need small changes as well (for example, a faint blue overlay is drawn over the entire UIList, with the UILoader above it, you see the list getting filled as items being handled instead of all at once, but input to the UIList is disabled until if fully loads.

**Comment by Chicken-Bones** [comment]
I'm not sold on this, unless the server returns the data in sort order

**Comment by Jofairden** [comment]
It also isn't really needed anymore, I saw jopo worked on the menu and it's
a lot faster.


Op 27 mrt. 2017 11:07 schreef "Chicken-Bones" <notifications@github.com>:
