### ISSUE TITLE
License

### ISSUE THREAD

**Issue by The-Beast** [bluemagic123/tModLoader#15]
Why don't you have a license? If you think that if you have no license means that you grant unlimited rights to distribute, modfy, etc. then you're wrong. That's why CC0 or The Unlicense were created. If that sounds offensive, than sorry, I didn't mean to be offensive.

**Comment by bluemagic123** [comment]
Truth be told, I've been too lazy to try to find the right license. But yeah, I probably should make this a top priority.

**Comment by The-Beast** [comment]
If you want some help, visit http://choosealicense.com/
