### ISSUE TITLE
tModLoader crashes loading mod in OSX when it contains a static class

### ISSUE THREAD

**Issue by LyraelRayne** [bluemagic123/tModLoader#150]
I had an extension method in my mod which was in a static class in the same CS file as my ModPlayer (see mod https://github.com/LyraelRayne/TerrariaCombatHotkeysMod/releases/tag/v1.0).

Everything loaded fine on Windows, but on OSX the game would crash before it gets to the main menu while loading the mod, regardless of if the mod was enabled or not.

I tried running in tmodloaderserver and got the attached crash log.

[crash.txt](https://github.com/bluemagic123/tModLoader/files/871986/crash.txt)

**Comment by LyraelRayne** [comment]
I was able to remove the extension method (it was just for debugging) and get my mod loading on OSX btw,  this is just a heads up that it doesn't work under those circumstances.

**Comment by Jofairden** [comment]
Hmm. Some kind of mono issue going on. Are you sure you have mono 4? I found a similar issue back in the day from tAPI: https://github.com/NyxStudios/TShock/issues/994

You could try this:
`sudo apt-get install libmono-system-servicemodel4.0a-cil`
Installing this might not help as it seemed specific to the issue I got it from, but it's worth a shot. This should get you the mono service model library for CLI 4.0

**Comment by JavidPack** [comment]
This is a known issue, we need to do a Mono.Cecil rewrite while building mods since something moved. Once chickenbones has ample free time he'll look into it.

**Comment by Jofairden** [comment]
Ah, didn't know it was the same issue, even though I thought about it. We'll have to wait until chicken bones has time.

**Comment by Chicken-Bones** [comment]
Fixed d445b9bd1163e6ac62e765d94a7da922882a88b8
