### ISSUE TITLE
Visual Studio 2017 debugger crashes on reading mods

### ISSUE THREAD

**Issue by Jofairden** [bluemagic123/tModLoader#153]
For reference. Old: #137

> It has todo with Mono.Cecil
> Just doing a simple read to Cecil and write back to binary crashes the debugger
> But only on some mods
> ExampleMod has been safe from the bug for me
> But CheatSheet has not

**Comment by Chicken-Bones** [comment]
Fixed (for client) [on my machine at least] with fadfa37f12ab20ca82ec6c3f9d70606143ca867b
