### ISSUE TITLE
[Suggestion] Delete Mod button in "mods"

### ISSUE THREAD

**Issue by rayman89** [bluemagic123/tModLoader#158]
Would be nice to be able to delete a mod you don't want anymore from the tmod's ui  either via "Mods" or mod Browser once you "installed" it.

**Comment by Jofairden** [comment]
Good idea.

**Comment by JavidPack** [comment]
Done in https://github.com/bluemagic123/tModLoader/commit/f9699a1a8a43e90c41dee7e32af03c7c6c76acb3
