### ISSUE TITLE
ItemInfo removed upon dropping items in multiplayer

### ISSUE THREAD

**Issue by gamrguy** [bluemagic123/tModLoader#160]
### Description

Dropping any item with ItemInfo removes said ItemInfo if in multiplayer.

### Steps to Reproduce

1. Enter multiplayer on any tModLoader server
2. Drop any item with ItemInfo onto the ground
3. Observe that the item has been wiped of all ItemInfo.

(Easiest to observe when using my mod, Item Customizer. Place a dye on an item and see that it is immediately removed upon being dropped in multiplayer, while the dye remains visible when dropped in singleplayer.)

### Expected behavior 

Item keeps its ItemInfo upon being dropped on the ground in multiplayer.

### Actual behavior

Item resets its ItemInfo upon being dropped on the ground in multiplayer.

### Reproduction frequency

100%.

### Versions

Since `tModLoader v0.9.2.1` at the least. Occurs in `tModLoader v0.9.2.3`.

### Mods

Not possible to replicate without mods. I use my mod, Item Customizer, to replicate the glitch as it is easy to tell when the ItemInfo gets wiped (custom name and shader are removed).

**Comment by bluemagic123** [comment]
Just to make sure, you've implemented the NetSend and NetReceive hooks in GlobalItem, right?

**Comment by Jofairden** [comment]
What blue said.. You need to manually sync ItemInfo using NetSend and NetReceive in GlobalItem or ModItem classes.

**Comment by Jofairden** [comment]
No further response, looks like this is resolved.
For future web-travelers (why are you using a time machine?!), here's an example:

```
		public override void NetSend(BinaryWriter writer)
		{

			writer.Write(Tier);
			writer.Write(DemonicEssence);
		}

		public override void NetRecieve(BinaryReader reader)
		{
			Tier = reader.ReadUInt32();
			DemonicEssence = reader.ReadUInt32();
		}
```
