### ISSUE TITLE
Error when installing cart run exe on windows

### ISSUE THREAD

**Issue by Tms157** [bluemagic123/tModLoader#161]
### Description

Not working just getting error when i try to run the exe after installing it 

### Steps to Reproduce

Install the mod loader

### Expected behavior 

tModloader to install and and work

### Actual behavior

Not working getting a error see below:
https://gyazo.com/83d7eb2d48911425aaaec061faad949c

### Reproduction frequency

100%

### Versions

Cart get to the menu

### Mods

None

### Additional Information

First time installing the mod today getting this problem is it because of the update today? running on windows. Im assuming you might already know but its seems every one has this problem (looking on your forum page)

**Comment by MaybeICanHelp** [comment]
This isn't a bug, it happens every time a new update for Terraria is released. In this case, 1.3.5. All you can do is wait for tModLoader to release a new version, then install it and it should work again.

**Comment by bluemagic123** [comment]
It doesn't happen every time a Terraria update is released, but this update is special.

**Comment by Krom2k** [comment]
I get the same message but by looking closely at the Terraria.exe created by the ModLoader, it is showing in the detailed properties version 1.3.4.4 but the original exe (steam) is 1.3.5.1. I did download the ModLoader v0.9.2.3 for v1.3.5. Could the wrong exe be packaged in the 0.9.2.3 download? Does it work for any body running Terraria v.1.3.5.1?

**Comment by JavidPack** [comment]
> This is simply a repackaging of tModLoader v0.9.2.3 with some additional compatibility files so it can continue to run for users who have had their Terraria updated to 1.3.5+ by Steam.
> 
> This does not contain the 1.3.5+ content, it contains the 1.3.4.4 content, but will actually load since 1.3.5 changed some files that prevented 0.9.2.3 from loading correctly.
> 
> Look for tModLoader 0.10 near the end of May.

**Comment by arcanis** [comment]
Small question:

> This does not contain the 1.3.5+ content, it contains the 1.3.4.4 content

Does it means it effectively ships with a Terraria rollback, so no traduction etc? Or is it only tModLoader features that will be affected (in this case, what exactly will break?)?

**Comment by arcanis** [comment]
Hm, apparently I lost my world. Probably should have backuped ...

**Comment by JavidPack** [comment]
If you were trying to load a 1.3.5 world, you'll have to wait for an update to open that world again in modded terraria.
