### ISSUE TITLE
ModPlayer.ConsumeAmmo is not 1:1 with ammo consumption for flamethrower weapons

### ISSUE THREAD

**Issue by hamstar0** [bluemagic123/tModLoader#162]
### Description

ModPlayer.ConsumeAmmo runs numerous times more than needed while firing flamethrower (I only noticed in particular at the end of a given firing stream).

### Steps to Reproduce

Fire flamethrower.

### Expected behavior 

1:1 hook triggers with ammo consumption (note: NO ammo saving armor/buffs/accessories used.)

### Actual behavior

Excess hook firings for several frames after a given stream.

### Reproduction frequency

Always.

### Versions

v0.9.2.3

### Mods

Durability, Cheat Sheet

**Comment by JavidPack** [comment]
Looking at the useTime and useAnimation of that item, it should be called about 6 times per shot. Is it not?

The hook is always called regardless of whether it has already been decided to not consume ammo, as is the case in the code for weapons that shoot the Flames projectile. 

This is consistent with other effects, such as ammo reducing buffs.

**Comment by hamstar0** [comment]
Then for consistency sake it probably should be called something slightly different, like CanConsumeAmmo.  Otherwise I'll think this is the go-to method for hooking _only_ instances of ammo use.

**Comment by Jofairden** [comment]
Jopo is right, the flamethrower has multiple uses in a single use animation. I did something like this to combat this
```
		public override bool ConsumeAmmo(Player player)
		{
			return
				!(player.itemAnimation < item.useAnimation - 2)
				&& Main.rand.NextFloat() <= 0.5f;
		}
```
