### ISSUE TITLE
Latest Update (10 mins ago) broke the mod loader again

### ISSUE THREAD

**Issue by Tms157** [bluemagic123/tModLoader#163]
### Description

After the last update (10 mins ago from this post) it broke the launcher again

### Steps to Reproduce

Just run the launcher 

### Reproduction frequency

100%

**Comment by uJelleh** [comment]
Yeah when I replace the files (terraria.exe, etc) the game version shows 3.4.4 on the main menu... please update soon! ^_^

**Comment by JavidPack** [comment]
Yep, just reinstall.

@uJelleh That's what it's suppose to do.
