### ISSUE TITLE
Multiple serializers of the same type

### ISSUE THREAD

**Issue by Itorius** [bluemagic123/tModLoader#164]
tML throws an error when 2+ serializers with the same type exist. I suggest checking if the serializer is already added in TagSerializer.AddSerializer method.

**Comment by Chicken-Bones** [comment]
Example use case? 
And what solution do you propose? Throw the error earlier with a more informative message/Take the first one and ignore the second/Display a warning
My initial concern is there's no way of knowing of two serializers are compatible, so more information about your situation would be good

**Comment by JavidPack** [comment]
Also, if a serializer is something a lot of mods/modders would find useful, we might be able to add it straight into tmodloader.

**Comment by Chicken-Bones** [comment]
Closing this due to lack of interest, can be reopened if discussion arises
