### ISSUE TITLE
Terraria.bin.osx not compatible with current version?

### ISSUE THREAD

**Issue by LuckyMidget** [bluemagic123/tModLoader#166]
### Description

whenever i try to open terraria with the exact step on readme.txt, it shows up Terraria.bin.osx is not compatible with current version of mac.

### Steps to Reproduce

1. i did everything that's in the guide
2. as it says to overwrite everything, i did that too
3. then opened it from steam

### Expected behavior 

I thought i would open just like other people's modded terraria

### Actual behavior

it didn't open and showed up with the issue as i said.

### Version
I did this in terraria 1.3.5

tModLoader v0.9.2.3

**Comment by JavidPack** [comment]
That download didn't work for people, guess they need to follow the other instructions for now. (The Steam console direct download thing mentioned elsewhere.)
