### ISSUE TITLE
Mod.PostAddRecipes hook

### ISSUE THREAD

**Issue by goldenapple3** [bluemagic123/tModLoader#167]
It would be useful to have a hook which runs after all the AddRecipes() hooks have been called. This could be used to edit other mods' recipes.

When using RecipeFinder/RecipeEditor normally in Mod.AddRecipes(), it only affects mods which are loaded before yours. That can be a problem in a lot of cases.

**Comment by bluemagic123** [comment]
I've actually been thinking about this recently. We'll try to get this in for the next update.

**Comment by goldenapple3** [comment]
Nice! Thank you.

**Comment by Jofairden** [comment]
Say we add this hook, what if a mod that loads after yours adds new recipes within this hook? What then? There is no call order priority in place..

**Comment by goldenapple3** [comment]
Well, most recipes would be added in AddRecipes(), so I think it'll be fine most of the time. At least, it will be better than it is now.
