### ISSUE TITLE
Query 3 Failure

### ISSUE THREAD

**Issue by DrEinsteinium** [bluemagic123/tModLoader#17]
While publishing an update Query3 failed:

"Replacing with new version!
File is valid....
Query3 failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's display name) and pressing the tWiki Search key (default L), can be changed in' at line 1"

Here is the string in my description.txt
"This mod was created to make it much easier and faster to search the official Terraria Wiki for information about the many items added in game.

You can use the search function by hovering over an item in your inventory or hovering over a monster (showing it's display name) and pressing the tWiki Search key (default L), can be changed in the Mod Controls menu. All links will be opened in your default web browser."

I'm assuming the query was too long? I changed it to this and it worked:
"You can search the Terraria Wiki by hovering over an item in your inventory or hovering over a monster in the world and pressing the tWiki keybinding (default L, can be changed in the Mod Controls menu). All links will be opened in your default web browser."

**Comment by JavidPack** [comment]
I think I fixed it, want to publish again with the original?
