### ISSUE TITLE
Linux server script is CRLF which breaks the shebang.

### ISSUE THREAD

**Issue by PJB3005** [bluemagic123/tModLoader#171]
```
steam@ubuntuServer:~/terraria_1.3.4.4$ ./tModLoaderServer
bash: ./tModLoaderServer: /bin/bash^M: bad interpreter: No such file or directory
```

Simple workaround is to run `dos2unix` over the file beforehand or to explicitly invoke bash over it, but it's still not ideal.

**Comment by JavidPack** [comment]
Should be fixed with https://github.com/bluemagic123/tModLoader/commit/dda96cf1410f6f4563904cdd434a49d5f38c4adc

**Comment by PJB3005** [comment]
I just downloaded the latest Linux download and the script is still CRLF formatted. Something's up.

**Comment by JavidPack** [comment]
We haven't released a new version since this fix, did you download the release or the repository?

**Comment by JavidPack** [comment]
Oh, I mean since we refixed this in a later commit.

**Comment by PJB3005** [comment]
Oh that's possible then.
