### ISSUE TITLE
System.EntryPointNotFoundException: Unable to find an entry point named "InitSafe" in DLL 'CSteamworks'. at Steamworks.NativeMethods.SteamAPI_InitSafe() at Steamworks.SteamAPI.Init() at Terraria.Social.Steam.CoreSocialModule.Initalize() at Terraria.Social.SocialAPI.Initialize(Nullable'1 mode) at Terraria.Program.LaunchGame(String[] args)

### ISSUE THREAD

**Issue by PixelWinter** [bluemagic123/tModLoader#172]
Ive clicked the button but people on the tmodloader discord channel said I downloaded outdated. I renamed normal terraria "terrariaOld" And it said that theres 2 folders of the same and that I could merge them (As known as content folder) And fonts and others. But some of the DLL folders said I could rename them to like "steam_api(2)". And I did that but I had no idea what to do with the folders like content. So I had no choice to try to merge them. But then it said this when I tryed to open tmodloader version of terraria:System.EntryPointNotFoundException: Unable to find an entry point named "InitSafe" in DLL 'CSteamworks'. at Steamworks.NativeMethods.SteamAPI_InitSafe() at Steamworks.SteamAPI.Init() at Terraria.Social.Steam.CoreSocialModule.Initalize() at Terraria.Social.SocialAPI.Initialize(Nullable'1 mode) at Terraria.Program.LaunchGame(String[] args)
And now only normal terraria works.

**Comment by bluemagic123** [comment]
The entire point of the special download was to provide files that replace the ones you already have. You're supposed to replace all the files, not rename anything.

**Comment by PixelWinter** [comment]
Oh well do I delete the ones that are the same?

**Comment by PixelWinter** [comment]
Nice! Thx blue! I've had this problem for a long time!

**Comment by PixelWinter** [comment]
Also BTW forget my first comment on you

**Comment by Jofairden** [comment]
You're welcome. 💯 👍

**Comment by PixelWinter** [comment]
Uh when I try to open it, it says something about the image TileCracks not found.
Any information?

**Comment by PixelWinter** [comment]
Or could I just download a tilecracks image

**Comment by Jofairden** [comment]
@PixelWinter it's pretty obvious you are using cracked Terraria, which tML will not work with. We've had similar reports before. We are not allowed to help people with cracked (modified) versions of Terraria (illegally obtained editions). You need to have a legitimate version obtained on a Steam or GoG (Gathering of Gamers) account.

**Comment by PixelWinter** [comment]
I do have it on steam. Ill prove it Search Pixel_Winter up on steam and look at the games

**Comment by Jofairden** [comment]
In that case I recommend you do the following:

1. Go to your Steam library and locate Terraria
2. Right click Terraria and hit 'Properties'
3. Go to the local files tab and click on Browse local files..
4. Delete the following files (if they exist)
- Terraria.exe
- TerrariaServer.exe
- tModLoaderServer.exe
- (folder) ModCompile
5. Go back to the local files tab in the properties window (within steam) and click Verify integrity of game files..
6. Once this completes, please verify Terraria runs when you launch the game
7. Try to reinstall tModloader and see if it works

If the above solution doesn't work, you should try to completely remove Terraria and reinstall the game, verify that it works, then try to reinstall tModLoader.

**Comment by JavidPack** [comment]
Note that the TileCracks error usually happens if you are trying to launch tModLaoder from somewhere other than the terraria install directory.

**Comment by PixelWinter** [comment]
So I verified the game. It does work. So now I need 1 little tiny answer. Ik this is dumb to ask but do I delete Tmodloaders files that are there then delete contents, steam_api, and CSteamworks? plus normal terraria?
Then paste  tmodloader files in? I am so sorry but its hard to think it out

**Comment by Jofairden** [comment]
If the files are verified you should not delete anything. You copy all the contents of the tModLoader installation directory to your Terraria directory, and you allow it to overwrite when it asks.

**Comment by PixelWinter** [comment]
So by overwrite you mean replace the files?

**Comment by Jofairden** [comment]
When copying files to the Terraria directory, click 'yes' or 'yes to all' when it asks to overwrite the files. Essentially it will then replace those files with the tModLoader files. If you ever wish to revert to vanilla you can still do this, no worries :)

**Comment by PixelWinter** [comment]
What about the DLL's? Skip, copy and replace, don't copy or copy but keep both files?

**Comment by Jofairden** [comment]
Not sure what you mean. Just follow my steps. If you have a clean Terraria install, simply copy the tModLoader files to the Terraria folder and overwrite when asked.

**Comment by PixelWinter** [comment]
The DLLS like steam_api

**Comment by PixelWinter** [comment]
Gives me the options Skip, copy and replace, don't copy or copy but keep both files when it finds 2 of the same dll
