### ISSUE TITLE
tModLoader not working

### ISSUE THREAD

**Issue by marxninja19** [bluemagic123/tModLoader#174]
Basically, im using the new one for 1.3.5 terraria and i put in all the files into my terraria folder, but when i open either of the terrarias, it opens normal terraria, not the tModLoader one.

**Comment by marxninja19** [comment]
<!--Basically, im using the new one for 1.3.5 terraria and i put in all the files into my terraria folder, but when i open either of the terrarias, it opens normal terraria, not the tModLoader one.

**Comment by bluemagic123** [comment]
That means you didn't install it properly.

**Comment by marxninja19** [comment]
oh! i have two terraria folders, i thought it was the one that has my players and worlds in it. YAY
