### ISSUE TITLE
Mono compilation error: "You must add a reference to assembly Microsoft.Xna.Framework"

### ISSUE THREAD

**Issue by Merser433** [bluemagic123/tModLoader#175]
Basically, whenever i try to add a new class that has anything that has something to do with XNA, for example, a Vector2 value initialization, tML throws stuff like:
> The type 'Microsoft.Xna.Framework.Vector2' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553'. May have something to do with DynamicSpriteFont

It only happens on Mono compilation, windows build compiles fine.

To reproduce:
1. Get ExampleMod
2. Make a Debug.cs file in it's source's root folder, and paste >[this](https://pastebin.com/kSncy0qK)< in it.
3. Try compiling the mod with TML.
4. IMPORTANT STEP: Get an error.

**Comment by Chicken-Bones** [comment]
Smaller test case https://pastebin.com/bNBqRxPH
Primary issue is the use of `DynamicSpriteFont` and the `SpriteBatch.Draw` extension method
I believe the wrong ReLogic dll is being used for osx compilation

**Comment by Chicken-Bones** [comment]
Fixed 9e57cac9162f21aea5d145370559f890e3efdf91
