### ISSUE TITLE
Request: Arrange mods in mods list

### ISSUE THREAD

**Issue by rayman89** [bluemagic123/tModLoader#177]
Would be nice to be able to sort mods in the mod list alphabetically, by enabled/disabled and by date (the last mods to be downloaded/updated).

**Comment by Chicken-Bones** [comment]
Seconded, also icons for info/delete/extract might be nice

**Comment by GaryAlfred** [comment]
Being able to order (enabled) mods for loading is relevant. Often code in one mod may step on code in another.

**Comment by Chicken-Bones** [comment]
Ah no, this order would not allow users to control loading. If you want one mod to load before or after another you must specify this in the build properties. Otherwise mods load in alphabetical order.

**Comment by JavidPack** [comment]
Implmented in 18ff849e99685265fed1dfc74e96c9c8c1478e05
