### ISSUE TITLE
Tmodloader Linux support 1.3.5

### ISSUE THREAD

**Issue by Xeddius** [bluemagic123/tModLoader#178]
Tmodloader lacks a 1.3.5 Linux version, the windows based files are incompatible.
I own the 1.3.5.3 GOG release of Terraria for Linux and would be more than willing to help in bringing a linux release if possible.

**Comment by Chicken-Bones** [comment]
Thankyou for your offer. We expect to release 1.3.5.3 tModLoader within a week (5th April)
