### ISSUE TITLE
Request: Mod loading options

### ISSUE THREAD

**Issue by rayman89** [bluemagic123/tModLoader#185]
Sometimes you just wanna check something and you open tmodloader terraria and you have to wait a lot if you have many mods installed so would it be possible to add an option to not load mods as soon as the exe is opened and do it after you select the single player/multiplayer (or you could put instead an item menu named "Play" that appears instead of single/multiplayer when this option is enabled and once you press it the mods load and then you can choose single player or multiplayer normally).

**Comment by JavidPack** [comment]
Already implemented in next version: hold shift. f9699a1a8a43e90c41dee7e32af03c7c6c76acb3
