### ISSUE TITLE
tModLoaderInstaller for 1.3.5 is not in the file I download.

### ISSUE THREAD

**Issue by TheGrimReaper149** [bluemagic123/tModLoader#186]
The Files I get
Content
ModCompile
CSteamworks.dll
README
start-tModLoaderServer
start-tModloaderServer-steam-friends
start-tModloaderServer-steam-private
steam_api.dll
Terraria
tModLoaderServer
The files I SHOULD get:
all of the above but without tModLoaderInstaller 
PLEASE I need some help with this.
I have downloaded it before for 1.3.4 then I got rid of it to play vanilla.

**Comment by Jofairden** [comment]
I'm not sure exactly what you mean here. The installer is an accessory thing and isn't required to actually 'install' tML in case you didn't know.. I advise you to read the [installation section of our README](https://github.com/bluemagic123/tModLoader#installation) to find out how to install if you didn't know already.

**Comment by TheGrimReaper149** [comment]
thanks I didnt see the installation guide I just assumed you needed to have the Install patch.
