### ISSUE TITLE
Mac crash on startup Terraria 1.3.5.2 with tModLoader v0.10

### ISSUE THREAD

**Issue by SerLizar** [bluemagic123/tModLoader#187]
### Description

After installing the latest release, using the installer .jar file, Terraria crashes during startup, resulting in the crashlog 
[Runtime Error.txt](https://github.com/bluemagic123/tModLoader/files/1054148/Runtime.Error.txt).

This is probably the result of it not having been built against FNA.dll

### Steps to Reproduce

0. All steps should be performed in a computer running MacOS
1. Download a fresh copy of Terraria v1.3.5.2 from Steam
2. Install tModLoader using the installer .jar file
3. Launch Terraria

### Expected behavior 

Terraria startups, reads mods and the main menu loads with the tModLoader related options available.

### Actual behavior

tModLoader is trying the use functions from the Microsoft.XNA.*.dll files instead of using the ones from FNA.dll

### Reproduction frequency

100%

### Versions

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`

Terraria v1.3.5.2
tModLoader v0.10

### Mods

None

### Additional Information

It should be the same problem the linux users are having, but I can't confirm it do to the fact that I'm not currently running linux.

**Comment by kasette** [comment]
> It should be the same problem the linux users are having, but I can't confirm it do to the fact that I'm not currently running linux.

can confirm that.
im on Debian testing; reproduction 100%

**Comment by SerLizar** [comment]
Fixed with v0.10.0.1
