### ISSUE TITLE
Mod Browser Mac displays update available screen while on the latest

### ISSUE THREAD

**Issue by SerLizar** [bluemagic123/tModLoader#190]
### Description

When opening the mod browser the following appears: 
![screen shot 2017-06-08 at 10 23 44 pm](https://user-images.githubusercontent.com/3751178/26959986-67703308-4c99-11e7-9bbd-23cd89ba7073.png)

### Steps to Reproduce

1. Install tModLoader v0.10.0.1 (latest version as of writhing) in Mac
2. Launch Terraria
3. Access the Mod Browser (Beta) option

### Expected behavior 

The mod browser opens up directly since the latest tModLoader version is installed.

### Actual behavior

A message mentioning an available update is displayed before being able to access the mod browser.

### Reproduction frequency

100% given you just launched Terraria, or click reload browser.

### Versions

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`
tModLoader v0.10.0.1
Terraria v1.3.5.2

### Mods

None, problem still stands while having mods installed.

### Additional Information

None that I can think of right now.

**Comment by JavidPack** [comment]
Typo on the server, fixed.
