### ISSUE TITLE
Mod Error Report 11/9/2021

### ISSUE THREAD

**Issue by Drago1490** [bluemagic123/tModLoader#1947]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Hello TML team.  I want to help out as much as I can, and I understand there isn't much I can do, so I figured why not stress test the game?  I really want to see this project succeed, so if I can find as many ways to break the mod loader as possible then that should help, right?  Anyway, I don't know how you guys operate, but I thought it would be best if I do a log of all the bugs that I find on my journey.  If you would like me to do it differently, feel free to reach out to me on discord.  My tag is SRD_Drago#2458.  Now on to the bugs.

1)  [in game]  When in the mod config page, open a config, clicking on the next page arrow does nothing.  If you click on it again, the game moves the camera off of the player and freezes the game.  

2)  [main menu]  The "Download Mods" page freezes and crashes the game after the images have loaded.  This happens on initial startup and after leaving a game session.  TML settings in the settings page of the main menu do not determine if this error persists.

3)  [in game]  Multiplayer seems to slow down the game, as well as significant rubberbanding for the host and increased entity reach.  This happens even with no mods enabled, but does not happen in vanilla with the exact same connection variables.

All of these issues have been repeatable 100% of the time and has occurred on multiple devices.

**Comment by JavidPack** [comment]
Many of these issues have been solved, if anything persists, please open a new issue for the specific issue
