### ISSUE TITLE
[1.4 Alpha] Playing with the sun while mods are loading, breaks the tModLoader logo/sprite

### ISSUE THREAD

**Issue by LCrew** [bluemagic123/tModLoader#1958]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Playing with the sun while mods are loading breaks the tModLoader logo/sprite, but fixes it when loading in the main menu.

![download](https://user-images.githubusercontent.com/7798036/141652425-8791fe4f-5740-4f44-ad95-655f584d2283.png)

### Steps to reproduce

1. Open tModLoader
2. Wait for mods to start loading (or any screen when something gets loaded in, that being - installing new mods, reloading them, initializing)
3. Start playing with the sun while that happens. (Terraria easter egg, when you can move sun by clicking on it)
4. Sprite breaks.

### Expected Behavior

Expected - Playing with the sun shouldn't break the tModLoader logo/sprite

### Actual Behavior

Actually happening - Playing with the sun breaks the tModLoader logo/sprite

### Reproduction frequency

Everytime.

**Comment by nullapple** [comment]
Apparently in the main.cs in Terraria there is a line that states the following:
`if (alreadyGrabbingSunOrMoon && !playOldTile) {
				playOldTile = true;
				MenuLoader.ActivateOldVanillaMenu();
			}`
Your issue is a year old and this 'bug' still happens to this day. However I don't know if this is an Easter egg instead, as I don't know why the development team would implement a chunk of code that does this.

**Comment by JavidPack** [comment]
I tested this today and could not get any issues. The code has been updated a little recently, maybe it fixed itself. If anyone has this issue feel free to reopen. Please post a video as well just in case I'm testing wrong.
