### ISSUE TITLE
Tmod tries to use xbox controller

### ISSUE THREAD

**Issue by Pepe3939** [bluemagic123/tModLoader#1967]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When tmod opens, it tries to use a controller which I dont have connected and doesnt let me interact with the menus.
I hope I explained the issue correctly, Im not fluent in english, sorry
![image](https://user-images.githubusercontent.com/81560057/141833294-8345bc21-732e-401f-a4cc-363e73af7fa4.png)

### Steps to reproduce

I just opened tmod

### Expected Behavior

It should let me interact using the mouse

### Actual Behavior

It tries to use xbox controls

### Reproduction frequency

it happens every time I open tmod

**Comment by Solxanich** [comment]
I've responded in Discord with the likely cause, as I believe I saw your post already about this. 

In case you don't see it in discord, this is caused by a fake controller named Monect. This comes from the #alpha-support channels pins:
"My game is launching in controller mode with no controllers!
Follow steps in https://community.monect.com/d/39-fuk-monect-hid-device to resolve "

**Comment by Zaflis** [comment]
I can confirm that disabling monect from device manager made tModLoader work with mouse again. Additionally if you press Win+R and type "joy.cpl", it will show you list of installed game controllers. It should be empty at normal.

Also 2 of the monect devices there didn't have "monect" in their name, i opened their properties 1 by 1 to see which ones are. The actual line that did have "monect" in it was not able to be disabled, but apparently that didn't matter.

Anyway this is a bug in tModLoader that we can't force mouse/keyboard mode regardless if there are game controllers installed. None of this is an issue in the main Terraria game.

**Comment by BassJoey** [comment]
Here's how you fix:
Documents\My Games\Terraria\tModLoader and right click config.json and open with Notepad

Change these 2 settings to the following:
  "InvisibleCursorForGamepad": false,
  "SettingBlockGamepadsEntirely": true,

Save and exit. Right click config.json and click properties. Check Read Only box. Play the game.
