### ISSUE TITLE
[1.4 Alpha] Modifying loot bag drops prevent them from being opened

### ISSUE THREAD

**Issue by Unknowneth** [bluemagic123/tModLoader#1971]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

I noticed this when I added a new item drop from a boss treasure bag and for some reason the bag won't open and the UI disappears for a few ticks. I thought this had something to do with my code but it also affects other mods. Opening treasure bags with the "clicker mod" causes this too since it also modifies treasure bag loot. Opening some bags will give you a new drop but the bag won't open and the vanilla loot will not spawn.

### Steps to reproduce

1. Try installing a mod that adds modified loot bag drops. for instance, the clicker class mod.
2. get a random treasure bag (any would do)
3. open it

### Expected Behavior

The bag would open normally and give you the normal loot alongside the modded loot

### Actual Behavior

the inventory flashes and no item will spawn. The bag won't open too.

### Reproduction frequency

90%. there are some occasions where the modded loot spawns but not the vanilla ones.

### Additional Information

Check out chippy's last clicker class video and go to the part where he opens the moonlord treasure bag. it shows this bug happening.

**Comment by SimoneG97** [comment]
This is a mod-related issue.
The clicker class mod hasn't got an update in 15 days, meanwhile tmodloader changed various things...
I'm not insightful enough, but if I have to guess, this issue is related to all "Right click to open" items and was cause by changes
like on Player.QuickSpawnItem (#1926).
