### ISSUE TITLE
When using The Constant seed, i dont see my cursor.

### ISSUE THREAD

**Issue by malanak2** [bluemagic123/tModLoader#1976]
In the new 1.4.3 tmodloader, i opened the dont starve seed, and I couldn't see my cursor. Searchedd and others see it. I used cheat sheet and ore excavator.

**Comment by JavidPack** [comment]
You didn't post client.log, how can we help?

My guess is you need to make sure steam downloads the latest update to both tmodlaoder and cheat sheet. I don't know if ore excavator is updated yet, but I know cheat sheet is.

**Comment by malanak2** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/7569105/client.log)
here

**Comment by malanak2** [comment]
Fixed, thanks

**Comment by malanak2** [comment]
Fixed, thanks
