### ISSUE TITLE
1.4 Alpha check Terraria version

### ISSUE THREAD

**Issue by SakoPolis** [bluemagic123/tModLoader#1979]
### Version

Latest public-1.4-alpha

### OS

Linux

### Platform

Steam

### Description

Currently the 1.4 alpha (and maybe the stable version) does not check for the Terraria version, and instead claims that game assets are missing. Attached is my crashlog for today, containing the crashes for Glow 310 missing, and after a few tries I made a fake Glow 310 file and it complained that Extra 244 was missing, I kept creating files and it kept discovering new missing ones until I updated to the latest vanilla terraria on steam which contained the missing game assets.
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/7574337/client-crashlog.txt)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7574344/client.log)
Here is the client log after I created around 15 fake buff files and then realized I was probably on the wrong version of the game.

### Steps to reproduce

Have old version of terraria. 
Install tmodloader.
Get in-descriptive error message.

### Expected Behavior

It should warn the user about the wrong version.

### Actual Behavior

It only notices missing asset files.

### Reproduction frequency

Any time when versions don't match.

### Additional Information

My temporary solution for users on reddit: [https://old.reddit.com/r/Terraria/comments/qxnlqw/tmodloader_14_issues/hlddgxo/](url)

**Comment by JavidPack** [comment]
I looked and steamworks doesn't seem to have any way of detecting the terraria buildid, so I'm guessing the only solution is to give the user a special message informing them to update terraria if the missing texture is detected to be Glow 310.  Or just do the check at startup. If anyone wants to attempt this lets talk in discord.

**Comment by SakoPolis** [comment]
You could give a warning to update the game/ verify the steam files if any asset is missing.
