### ISSUE TITLE
How do i assign a ammoID to an existing item

### ISSUE THREAD

**Issue by jaleck0** [bluemagic123/tModLoader#1980]
Hello im currently working on a mod in the current tModloader and i am trying to program a gun that shoots an item that already exists in the game. It seems that you can not just put any item in the item.useAmmo section. How do i for example make a gold bar a piece of consumeable ammo?

![image](https://user-images.githubusercontent.com/70542390/142729221-3c0456ef-ffda-4266-8231-811b5656f31b.png)

**Comment by Solxanich** [comment]
You won't really get any help with coding here -
The github issues is geared primarily to tmodloader development which isn't necessarily people who know the ins and outs of modding (let alone a place where those that do look).

Please reach out instead in the discord https://discord.gg/tmodloader 
And use one of the ``#Help-with-modding`` channels.

**Comment by jaleck0** [comment]
wasnt able to get help there but i will ask it again
