### ISSUE TITLE
Dresser Issues

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#1981]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

1) Dressers added by tModLoader cannot be opened using Smart Cursor, but they can open the Dresser UI.
2) Dressers added by tModLoader highlight incorrectly.

### Log File

![Screenshot_440_tModLoader](https://user-images.githubusercontent.com/33076411/142736943-9aad82e5-0479-4f3d-9f35-faf4844b3aa9.png)
Issue 2.

### Steps to reproduce

1. Open any Terraria world.
2. Place down a non-vanilla dresser.
3. Enable Smart Cursor.
4a. Hover the mouse above the dresser and right-click.
4b. Hover the mouse near the dresser.

### Expected Behavior

1) Right-clicking above a dresser with smart cursor enabled opens the chest that is part of the dresser, while right-clicking below will open the Dresser UI.
2) Hovering the mouse above or below a dresser will only highlight that half of the dresser.

### Actual Behavior

1) Right-clicking above the dresser does nothing, right-clicking below opens the Dresser UI as expected.
2) Hovering the mouse near a dresser highlights the entire dresser.

### Reproduction frequency

100%.

**Comment by JavidPack** [comment]
This has been fixed as part of https://github.com/tModLoader/tModLoader/pull/3210
