### ISSUE TITLE
Build Error With Brand New Tutorial Mod

### ISSUE THREAD

**Issue by Kewlchicken** [bluemagic123/tModLoader#1985]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### Description

![image](https://user-images.githubusercontent.com/94885085/142971133-393fd2b5-8c47-49c4-b56f-e558edec85a7.png)
So i decided i would try to get into modding a while back and i decided terraria would probably be the easiest an most fun for me and my skill level. I started following the steps on this tutorial and everything went just fine until hitting the "Build + Reload" button to load in the mod. seconds after it comes up with this message and i have no idea what it means or what to do about it. I looked it up and found 1 other person who had the same problem on reddit here: https://www.reddit.com/r/Terraria/comments/ppojuk/tmodloader_modding_error/
Unfortunately there was only one comment that linked to a method of installing the example mod. After doing so myself i found out i had the same problem as the other person with 57,302 errors. hoping someone can shed some light on this coz i have no clue whats happening lol. ¯\_(ツ)_/¯

Any help is appreciated. Thanks.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7585824/client.log)

### Steps to reproduce

1. Open Mod Sources
2. Create Mod
3. Click Build + Reload

### Expected Behavior

The mod loads itself

### Actual Behavior

an error log pops up

### Reproduction frequency

Every time.

### Additional Information

Using V1.3.5.3, TmodLoader0.11.8.5

**Comment by JavidPack** [comment]
Here is a copy and paste of the message we tell people in the discord chat who have this issue:

> If you have this particular error while building mods after installing Visual Studio that claims that simple things like Object or List don't exist, but you know that you have all the correct using statements, you might have run into this strange bug. We don't know why this bug occurs, but basically the Reference Assemblies folder has somehow been corrupted. To fix this, delete C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5 and then in the Visual Studio installer, click More->Repair. This process will take quite a while, and you will need to restart your computer to complete the process.

In addition, there has been some mention that installing VS 2022 instead of VS 2019 can also cause this issue, so it has been suggested to uninstall 2022 and install 2019, but I'm not positive.

**Comment by Kewlchicken** [comment]
thank you! uninstalling 2022 and installing 2019 worked perfectly!
