### ISSUE TITLE
Corrupt character selection

### ISSUE THREAD

**Issue by elillesaeter** [bluemagic123/tModLoader#1993]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

Character selection screen is not acting as expected. tModLoader keeps displaying unnamed, corrupt characters which are apparently saved to the cloud. If I turn off cloud storage for these characters and re-enter the character selection there are always at least two new cloud stored, unnamed characters. I have tested this on both macOS and Windows 10.

I managed to make a working, local character on macOS but managed to delete it by trying to delete one of the corrupt characters mentioned above. On Window 10, when trying to hit play on a newly created character it simply freezes and I have to force quit.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7597980/client.log)

### Steps to reproduce

1. Start tModLoader
2. Select "Single Player"
3. There are two unnamed characters, with the default looks, 100 health and 0 mana, with cloud saving on
4. Set cloud saving off, go back and select single player again. There are now four characters, the previous two, and always two new with cloud saving on.
5. Sometimes one of the characters display a long string of special characters and symbols.
6. Behaviour when trying to delete some of these characters is weird, and could delete other characters.

### Expected Behavior

There should be no corrupted characters and I should be able to create a new character and a new world and store them both online on steam and play normally.

### Actual Behavior

The character selection screen is corrupt.

### Reproduction frequency

Each time I run tModLoader

### Additional Information

I have tried on macOS, loading mods manually as the mod browser does not work on macOS, and got to play successfully. However I deleted my character trying to delete a corrupted character that was created automatically by tModLoader.

I have also tried in Windows 10 via boot camp on an intel MacBook pro, on a fresh steam install, and managed to reproduce the same issues regarding the corrupted characters, but not being able to play at all with a local character.

**Comment by direwolf420** [comment]
There currently exists an ongoing issue between TML and vanilla in Steam, in which Steam Cloud data would get randomly corrupted in memory, resulting in crashes and/or broken entries seen at player/world screens. It has existed for quite a long time, but became much more apparent since recently.
The issue can currently be avoided by either starting Steam in offline mode, or by manually moving data off of vanilla's cloud at the page linked below, and avoiding putting Worlds & Players onto the Steam Cloud in the meantime, both in vanilla and TML.

Link: https://store.steampowered.com/account/remotestorageapp/?appid=105600 (Requires logging into Steam.)

**Comment by fzrdi** [comment]
Hi i have the exact same problem, how would i go about "manually moving data off of vanilla's cloud at the page linked".

Im very stuck and i feel like i have tried everything.

**Comment by commetteri** [comment]
ive been using reinstalling as a fix for a long time, also when i started playing tmodloader it started corrupting alot, then i think it got into original terraria aswell

**Comment by JavidPack** [comment]
We're hoping steam has fixed this issue, we'll see if it is fixed once <https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3114798907236840432> goes live

**Comment by JavidPack** [comment]
Since I haven't seen any reports of this issue since Steam updated, I think this issue has been resolved, closing.
