### ISSUE TITLE
Huge Dupe Bug

### ISSUE THREAD

**Issue by Rahmiel** [bluemagic123/tModLoader#20]
Multiplayer in version 0.7.1.1

Chests allow duplication of items when using the loot all button. I'm pretty sure this is being caused by the server. The way it works is you put a bunch of separate stacks of items in a chest, hit loot all, you get all the items but when you close the chest and reopen it all but the first slot of items are in the chest AND in your inventory. This can be replicated numerous times with natural and player placed chests. Seems like a sync issue, server doesn't realize you pressed loot all or something. Not exactly sure.

**Comment by JavidPack** [comment]
Now fixed, thanks.
