### ISSUE TITLE
Can't rebind keys

### ISSUE THREAD

**Issue by BillyBobXXXII** [bluemagic123/tModLoader#2007]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

I was trying to rebind the keys for rage and adrenaline in Calamity but when I try it just changes the keybind to "None" and then "Unbound" when I try again. I can reset to default, but am unable to use custom keybinds for anything. I already tried uninstalling and reinstalling the game and deleting the conig.json and input profiles.json files.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7614988/client.log)

**Comment by direwolf420** [comment]
Consult the FAQ for fixing your issue: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#enabling-mods-freezes-the-gamesetting-controls-doesnt-work-properly

**Comment by Shawnyall** [comment]
Following the steps laid out in the FAQ didn't do anything, nor did running the game as Administrator. Have tried many solutions that have been stated online, but haven't found anything that works. This is still an issue.

As for myself, it is a fresh install of tModLoader, and I have no mods installed. Running the latest non-preview version.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
