### ISSUE TITLE
[1.4] Clicking "Publish" on a server-side mod causes TML to loop infinitely

### ISSUE THREAD

**Issue by xNarnia** [bluemagic123/tModLoader#2009]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Server-side mods can not be published on the Mod Browser. When you attempt to publish, the "loading mods" screen appears and loops infinitely. The process can not be cancelled and the game must be forcefully quit.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7629270/client.log)

### Steps to reproduce

1. Create a brand new ExampleMod from the Mod Sources screen
2. In the build.txt, create a new line with "side = Server"
3. Build + Reload the newly created mod on the Mod Sources screen
4. Click Publish on the Mod Sources screen

### Expected Behavior

When clicking on the Publish button, the Publish menu should show with fields to enter information into.
![](https://cdn.discordapp.com/attachments/698369130155212880/915369743186288691/Expected.gif)

### Actual Behavior

The screen changes to an infinite, looping, loading screen
![Actual](https://cdn.discordapp.com/attachments/534215632795729922/915360841312923679/CantPublish.gif)

### Reproduction frequency

This can be reproduced 100% of the time.

**Comment by Solxanich** [comment]
For future self:
At any rate, server side mod publishing.
Its possible to publish those mods from the command line. 
If memory serves, the syntax is something like 
``dotnet tmodloader.dll -server -steam -publish MyMod`` or something like that.

An actual fix for ingame will take some thought and design planning
