### ISSUE TITLE
[Linux] Mod browser not downloading mod after download button is hit and other issues

### ISSUE THREAD

**Issue by carlobagnoli** [bluemagic123/tModLoader#2010]
### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

2 bugs:
1.- On Steam, tModLoader takes 2~3 tries to open, just going to the tModLoader page in steam and clicking play crashes, yet, for some reason if you keep trying you will at some point get in.
2.- Can't install any mods, as soon as I hit the download button for a mod, the screen for download gets flashed for less than a second and goes back to the browser.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7629282/client.log)

### Steps to reproduce

First issue:
[Linux Manjaro]: Go to the tModLoader game page in Steam and click play until it runs, you'll see that the first few tries won't work, but it eventually gets there.

Second issue:
[Linux Manjaro]:
Go to the mod browser and click download for **any** mod

### Expected Behavior

First issue: Opens first try

Second issue: Downloads the mod

### Actual Behavior

First issue: Opens on second or third try

Second issue: Doesn't download the mod.

### Reproduction frequency

First issue: Most of the time it takes 2 times, sometimes 3, but never 1.

Second issue: 100%

### Additional Information

I use Manjaro (Linux).

**Comment by carlobagnoli** [comment]
For anyone that doesn't know how mod loading works, yet has the same issue, you could download the mods manually, via looking into the client.log and looking for the download link. Then just go to the mods folder copy and paste it.
At least for me, doing it manually is good enough.

**Comment by sorat0mo** [comment]
I encounter the same problem as well, Kubuntu 21.04

Logs is as follows: https://gist.github.com/sorat0mo/0f65e6a1f98b5e8093a04f68080663ef

Seems like handshaking and authentication erred.

**Comment by LumaLivy** [comment]
For others using linux, looking in client.log for the links was a good enough idea for me too. To get a filtered list of links all I do is attempt to download the mod from the browser first and then: (in a terminal @ `~/.local/share/Terraria/ModLoader/Logs`)

`cat client.log | grep tmod`

The link you just tried to download from should be printed at the very bottom, and any other `.tmod` file links you attempted in the mod browser will also get printed out.

Disclaimer, your log folder might be in a different spot on your computer, but I found mine by using the "open mods folder" button from the mods list in-game. Then I just navigated upwards to the logs directory and opened a terminal there.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
