### ISSUE TITLE
[1.3.5.3, Linux] tModLoader is not starting

### ISSUE THREAD

**Issue by uuigdevt47** [bluemagic123/tModLoader#2016]
### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

When i start `tModLoader.bin.x86_64` or `tModLoader.bin.x86` i get this error:

`AL lib: (EE) AddFileEntry: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"`
`AL lib: (EE) AddFileEntry: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr`

Arch Linux, OpenAL version 1.21.1-2
Steam version of the game.

**Comment by Psifour** [comment]
At a glance this sounds like a version mismatch between your system openal version and maybe a bundled library? You could try running openal-info for more information (preferably after setting the log level environment variable for openal).

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
