### ISSUE TITLE
the type or namespace name "World" does not exist in the namespace "Terraria" - help plz

### ISSUE THREAD

**Issue by hx3k11** [bluemagic123/tModLoader#2018]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

**Comment by Solxanich** [comment]
Please ask in the Discord.
https://discord.gg/tmodloader

The #alpha-help-with-modding channel is intended for that help, not here. This is targetted for tmodloader development, and you won't likely receive an answer here as such.
You may consult the migration guide. A link to that can be found in the mod sources menu ingame

**Comment by Mirsario** [comment]
Resolved in Discord.
