### ISSUE TITLE
I can not get in to the mod browser

### ISSUE THREAD

**Issue by EdgeDoesStuff** [bluemagic123/tModLoader#2019]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

when I am trying to open the mod browser it says Bad JSON 

[Bad JSON: <html><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><meta content="not-matched-by-esb" name="status" /><title>Error Page 404</title></head><body bgcolor="white"><div id="esberror"></div><table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="1024"><tbody><tr><td style="height: 100%;width: 100%;padding-top: 20px;border-bottom-width: 1px;border-bottom-style: dotted;border-bottom-color: #DDCCFE;padding-bottom: 10px;text-align: center;"><span style="font-family:Georgia,Times,serif;font-size:22px;line-height:140%;font-weight:normal;color:#666666;text-decoration:none;"><b>ERROR 404 Page Not Found</b></span></td></tr></tbody></table></body></html>
   at Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateFromJson(LocalMod[] installedMods, String json)]

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7651364/client.log)

### Steps to reproduce

opening the mod browser crash

### Expected Behavior

it opens

### Actual Behavior

is does not open

### Reproduction frequency

every single god damn time

**Comment by Solxanich** [comment]
Please ask in the Discord.
https://discord.gg/tmodloader

The #support channel is intended for help with user specific issues, not here. 
This is targetted for tmodloader development, and you won't likely receive an answer here as such.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
