### ISSUE TITLE
Switch the default label from master to 1.4

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#2021]
### Do you intend to personally contribute/program this feature?

No

### Description

It would be significantly more convenient for development to change our default label from being on master to being on 1.4

Advantages include the pulse analytics actually being accurate, and ensuring PR to 1.4, not master.
It also saves the hassle of having to change the target branch of the PR from master to 1.4 every time.

### What does this proposal attempt to solve or improve?

This should reduce the likelihood of PRs made against the wrong branch.

At this time, one can reasonably say 1.3 is not seeing any further development, and will only see updates as required for hashes for GoG.
This is kinda something we have to do at somepoint, and I'd recommend we do it over the December through January break so there are more folks having time to adjust.

**Comment by Chicken-Bones** [comment]
Done, master is also renamed to 1.3
