### ISSUE TITLE
AutoloadEquip(EquipType.HandsOn) is Bugged

### ISSUE THREAD

**Issue by isnir** [bluemagic123/tModLoader#2023]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Sprites will not show when [Autoload Equip(Equip Type.HandsOn)] is used.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7658134/client.log)

### Steps to reproduce

Create an Accessory with an visual sprite and use [AutoloadEquip(EquipType.HandsOn)]

### Expected Behavior

The Accessory visual shows on the player.

### Actual Behavior

No visual shows on the player.

### Reproduction frequency

100% of the time.

### Additional Information

The size of the visual does not seems to matter, it will always show nothing

Mod as example: [AutoLoadBug.zip](https://github.com/tModLoader/tModLoader/files/7658241/AutoLoadBug.zip)

**Comment by direwolf420** [comment]
Your `_HandsOn.png` is in the wrong format, it was changed in 1.4 to this layout:
![AncientClickingGlove_HandsOn](https://user-images.githubusercontent.com/15894498/144820322-0d1ee5ac-3b50-41b9-9ce8-2e6b8446b4d1.png)
