### ISSUE TITLE
(1.4) What happened ModContent.PrefixType<T>() ?

### ISSUE THREAD

**Issue by Unknowneth** [bluemagic123/tModLoader#2024]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When I try to use it, it gives me an error that goes like "the type name PrefixType<> does not exist in type 'ModContent'" 
 
I am basically trying to create a reforge with custom behavior

### Steps to reproduce

1. Try something like item.prefix == ModContent.PrefixType<Path.Goes.Here>() in something like a globalItem
2. Build/Compile the mod
3. Error occurs

### Expected Behavior

The mod should compile just fine and the prefix should be detected when using it

### Actual Behavior

The game gives me an error that the type doesn't exist

### Reproduction frequency

Always happens

**Comment by direwolf420** [comment]
Works for me. Provide your full .cs file where you use PrefixType, aswell as the full client log (found in ModLoader/Beta/Logs)

---------------------
![Screenshot_1](https://user-images.githubusercontent.com/15894498/144819867-be9483ee-115d-4d1b-bd31-06c1d45cef07.png)
![Screenshot_2](https://user-images.githubusercontent.com/15894498/144819870-fe6375a7-80fb-463c-b940-e109cfa6f14f.png)
