### ISSUE TITLE
Seems like the mod listing php was deleted from the javid site

### ISSUE THREAD

**Issue by IonDrako** [bluemagic123/tModLoader#2030]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

The mod browser wasn't working so I looked around the [javid.ddns](http://javid.ddns.net/tModLoader/) site and found the DirectModDownloadListing.php the modloader uses for it's mod browser wasn't there anymore (possibly deleted, there is a new account protected mods directory though). I assume it's for something intended but wanted to report it just in case it isn't.

**Comment by JavidPack** [comment]
That page isn't used for the mod browser, so your issue is elsewhere. I'd suggest asking in the discord to more quickly solve your issue, as github isn't suitable for real time support queries.

**Comment by IonDrako** [comment]
The browser is working again but it was my misunderstanding due to tmodloader itself. When the browser doesn't load it gives the option to click the window to open the/a site to see if that's working and said link is what I put here "_http://javid.ddns.net/tModLoader/DirectModDownloadListing.php_" obviously now this isn't what it uses but it is the place it tried to send me through the launcher.

That's probably another issue itself but I'll close this one at the least.
