### ISSUE TITLE
Weather Pain projectile gives error in chat

### ISSUE THREAD

**Issue by Lurrae** [bluemagic123/tModLoader#2033]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

With zero mods enabled (not even Cheat Sheet) the Weather Pain's projectile, shortly before despawning, leaves a message in chat stating that it `"cannot access a disposed object"` or something along those lines

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7682277/client.log)

### Steps to reproduce

1. Obtain the Weather Pain (either by defeating Deerclops or using a mod or an inventory editor)
2. Fire the weapon and follow its projectile (Witch's Broom mount works well for this purpose)
3. When the Weather Pain despawns, there may be a message in the chat, though as stated above, it doesn't happen every time

### Expected Behavior

The Weather Pain should not post error messages in chat when its projectile despawns, even as inconsistently as it does currently

### Actual Behavior

An error message is posted in chat, and the logs contain a full stack trace of the error

### Reproduction frequency

Not very commonly, though I have noticed that building and reloading any one of my mods, and then immediately disabling it and reloading again, does seem to make it far more likely for some reason (though which mod I reload doesn't seem to make a difference), so the error may have some relation to lingering mod data; I can't say for certain whether it's an issue with tModLoader or one of my mods not unloading properly, though

### Additional Information

I had my music disabled, and I noticed that when the error happened, the wind sound effects that the Weather Pain usually makes stopped just before it despawned, and very rarely, the projectile didn't actually despawn immediately after giving the error

**Comment by Chicken-Bones** [comment]
Seems a more general sound related bug. Relevant portion of stack trace
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SoundEffectInstance'.
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.set_Pan(Single value) in D:\a\tModLoader\tModLoader\FNA\src\Audio\SoundEffectInstance.cs:line 56
   at Terraria.Audio.ActiveSound.Update() in tModLoader\Terraria\Audio\ActiveSound.cs:line 80
   at Terraria.Audio.SoundPlayer.Update() in tModLoader\Terraria\Audio\SoundPlayer.cs:line 70
   at Terraria.Audio.SoundEngine.Update() in tModLoader\Terraria\Audio\SoundEngine.cs:line 47
   at Terraria.Main.UpdateAudio() in tModLoader\Terraria\Main.cs:line 8752
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12825
   ```

**Comment by JavidPack** [comment]
I've tried replicating on current 1.4.4-preview and could not replicate. I'm assuming this fixed itself due to other sound fixes since this report. Feel free to reopen if it happens again on the latest 1.4.4-preview.
