### ISSUE TITLE
[1.4] Carrot unobtainable except on Windows

### ISSUE THREAD

**Issue by EtherTyper** [bluemagic123/tModLoader#2034]
Terraria checks whether the player is using the Collector's Edition using the registry key `HKEY_CURRENT_USER\CurrentUser\software\terraria\Bunny`. While the registry is available in Mono on all platforms, in .NET Core it is only available on Windows. So, this feature works in vanilla Terraria on macOS, but does not work in tModLoader 1.4 alpha on macOS.

Not sure if this behavior is intentional, or whether it counts more as a bug report or feature request, so I decided not to use a template.

**Comment by Chicken-Bones** [comment]
Just letting you know that this will be quite difficult and the benefit is to a very limited number of users, so it's unlikely to ever be resolved. I'll leave it open as a known issue.

**Comment by Madmadness65** [comment]
Bringing this up again, except this time it's not functional on the public release of tML 1.4.3.6 on Windows now. However, it is still perfectly functional on the latest tML 1.3.5.3 release, as well as vanilla 1.4.3.6.

**Comment by YokujinKaze** [comment]
can confirm im not getting my carrot nor the bunny spawns when equipped on 2022.6.96.4 on windows

**Comment by Jacky10X** [comment]
it seems tML 1.4.4 has fixed the problem. But the tML 1.4.3 still has the issue. But tML 1.4.4 is still in development.
So I hope this glitch can get fixed on tML 1.4.3

**Comment by m1neral-rocks** [comment]
Would it be possible to add "IsLinux" and "IsMacOS" checks and depending on the result looking at the "~/.mono/registry/CurrentUser/software/terraria/values.xml" file and continuing with the normal function after that? I haven't looked at the decompiled code yet and I'm not really experienced with dotnet and c#'s quirks but if this sounds plausible I can at least try and see if it works.

**Comment by Chicken-Bones** [comment]
The carrot was never released on any platform other than windows. Allowing non collectors to get collector's edition items is outside the scope of tML.
