### ISSUE TITLE
Failed to load asset

### ISSUE THREAD

**Issue by Muramas** [bluemagic123/tModLoader#2037]
When I try to load the beta in steam, it attempts to locate the files in D:\a\tmodloader
When I turn off the beta the old tmodloader works fine.

I have looked though the registry and could not locate a value or data that would point there. 

![image](https://user-images.githubusercontent.com/2413847/145681694-aba168a5-f145-499c-aa43-7a599a968412.png)

**Comment by direwolf420** [comment]
Update Terraria to 1.4.3.2

**Comment by Muramas** [comment]
That fixed it.
