### ISSUE TITLE
Sort workshop by type

### ISSUE THREAD

**Issue by Muramas** [bluemagic123/tModLoader#2039]
### Do you intend to personally contribute/program this feature?

No

### Description

It would be nice to have the ability to see certain kind of mods such as big overhaul mods, quality of life. graphical etc. instead of a long list of all the mods.

### What does this proposal attempt to solve or improve?

Currently the mod list has a long list of every mod listed by update, it makes it pretty hard to tell what the mod does without reading the description / using it. This could make it easier to find certain types of mods or different game versions of mods.

### Which (other) solutions should be considered?
This would most likely be done using tags and then you can make these tags searchable / categorized. Though one issue with letting the developer choose which tags is that they might choose unrelated tags to get a wider audience. 
_No response_

**Comment by Solxanich** [comment]
Duplicates request #245 

If you agree this is a duplicate, please close the issue; if not a duplication, please elaborate why.
