### ISSUE TITLE
treasure bags/crates/christmas gifts not opening

### ISSUE THREAD

**Issue by SDarren12** [bluemagic123/tModLoader#2043]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When I try to open a treasure bag or a fishing crate the screen just blinks and does nothing 

### Steps to reproduce

get a fishing crate/treasure bag
try to open it

### Expected Behavior

get the corresponding loot

### Actual Behavior

nothing

### Reproduction frequency

always with the listed items that can be opened

**Comment by Solxanich** [comment]
This is caused by a Mod.
Magic Storage just updated in the last few hours, and was the most common mod to cause that, so try updating it.

If not, again its a mod problem, not a tmod problem. You can cycle through your mods to determine which one it is, and let the mod author know.
