### ISSUE TITLE
my tmodloader characters keep reseting

### ISSUE THREAD

**Issue by DeepBlue78** [bluemagic123/tModLoader#2046]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### Description

i am on tmodloader v0.11.8.5 (vanilla 1.3.5.3) and when i boot up any character as far as i can tell, its fine in game, nothing wrong, but then after i save and quit the next time i try to load it up i noticed that the playtime was set back to 0 and it was like a freshly made character, i can reopen it, and keep playing, the worlds are all fine, no change there, also it creates these "ghost characters" as i like to call them every time i open the character select page, no name, no mana, 100 hp, 0 playtime. and if i try to delete any of these characters, it deletes EVERY SINGLE ONE of my characters (the vanilla game is unnaffected) (dont worry i got them restored)

### Steps to reproduce

i dont know what happened it just happened like this

### Expected Behavior

characters should not change when not being played or changed in files

### Actual Behavior

characters are reseting to become brand-new characters

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
Since no log was posted, it is assumed this is a mod issue, closing.
