### ISSUE TITLE
[1.4] Rain doesnt fall in modded biomes

### ISSUE THREAD

**Issue by Hallam9K** [bluemagic123/tModLoader#2048]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

The texture for rain is invisible while in modded biomes, I assume its because of how different colored rain works in 1.4 (rain sprite below)
![RainOriginal](https://user-images.githubusercontent.com/32880148/146655398-8a4023fe-73a2-4f47-b49a-d32317a426b1.png)

### Steps to reproduce

1. Create a modded biome
2. Go in it while its raining

**Comment by Solxanich** [comment]
Fixed in #2195
