### ISSUE TITLE
[1.4] Water droplet gore from modded biomes appear as granite golem head gores

### ISSUE THREAD

**Issue by Hallam9K** [bluemagic123/tModLoader#2049]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Self-explanatory, custom water droplet gores ive made and set for the WaterStyle's GetDropletGore creates a vanilla gore instead of the modded one

[DropletStuff.zip](https://github.com/tModLoader/tModLoader/files/7776069/DropletStuff.zip)

### Reproduction frequency

Seems to be always, other people have encountered it too

**Comment by steviegt6** [comment]
Seems as though `GetDropletGore` was forgotten about.
