### ISSUE TITLE
Error CS0012

### ISSUE THREAD

**Issue by JonkerWonker** [bluemagic123/tModLoader#2056]
I'm trying to have TML "Build" my mod, but whenever I click "Build" it gives me the CS0012 error screen

**Comment by Solxanich** [comment]
Please seek help in the discord, not here.
https://discord.gg/tmodloader

The discord is for generic help requests.
The github is for well defined bugs in tmodloader.
99% of help requests here will go unanswered as the people involved on each are different, and a lack of details presented means there is nothing to work with here.
 
If you are unsure if it is a bug, ask in the discord first.
