### ISSUE TITLE
Provide a smooth transition for breaking changes throughout ongoing development

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2073]
# Goal
When we transition from out of 1.4 alpha and encourage modders and users to transition, API breaking changes will still come, but they need to come with a predictable preview, some way for modders to prepare for them, and a way to shield users who just want to keep their current playthrough safe.

# Proposal
### Github branches:
- `1.4-stable` - bugfixes only, updates once a month
- `1.4-preview` - breaking changes before the 20th of the month. Modders should develop here to use new features and prepare for the monthly update.
- `1.4-dev` - github development and testing. Will track preview before the 20th, and accumulate breaking changes after until the next month rollover.

### Versioning:
- Versioning will be `yyyy.mm.ff.pp` preview and stable will always have different `yyyy.mm` versions. The release cycle will be monthly, focused around transitioning this month's preview to stable.
- The tML `BuildInfo.BuildPurpose` will be set to dev/preview/release based on the branch. Only preview and stable will deploy to steam, and allow mod publishing.
- `1.4-dev` will not be versioned. Versions are identified by commit sha.
- Every commit to `1.4-preview` will increment the `.ff` version.
- Every commit to `1.4-stable` aside from the auto-merge action, will increment the `.pp` version.

### Mod publishing:
- A mod will publish to steam inside a subfolder matching the yyyy.mm version of the tML build.
- Only two different yyyy.mm folders can exist simultaneously.
- tML will load the newest version of the mod it can.

Effectively, because preview and stable will always have different yyyy.mm versions, this means that modders can publish and maintain two versions of their mods. Stable and preview. When tML stable version updates, players will automatically start loading the newer version of the mod which has been prepared, and modders can continue to develop next month's release against the new preview version.

### Github Actions and guidelines
- An action will be created, preview -> stable
    Prereqs: 
        - `1.4-preview` is tagged with `approved-for-stable`
        - `1.4-stable` is a parent of `1.4-preview` (allowing a fast-forward merge)
        - `1.4-preview` is tagged with a newer `yyyy.mm` version than `1.4-stable`
        - `1.4-preview` `yyyy.mm` version is < the current `yyyy.mm`
    
    Steps:
        - fast-forward `1.4-stable` to `1.4-preview`
        - set `1.4-preview` version to `yyyy.mm.0.0`
        - merge `1.4-dev` to `1.4-preview` (if this fails, the workflow won't abort)
        - run all steam deploy actions
        
    This action will be automatically run at midnight GMT on the 1st of each month. If it fails, a member of the tML team may re-run it, but due to the prereqs, each preview yyyy.mm version can only be merged to stable once.
    
- PRs will target `1.4-dev` by default. All PRs will be reviewed in some form before being accepted in to `1.4-dev`.
- Before midnight GMT on the 20th of the month, `1.4-preview` will automatically track `1.4-dev`, via fast-forward merges.
    After the 20th, commits to `1.4-preview` will be focused on non-breaking changes and stabilising the preview.
- As mentioned above, commits will increment the version numbers automatically.
- Bugfixes to `1.4-stable` will have to be merged back into `1.4-qa`/`1.4-preview` manually
   
### How modders find out about and react to breaking changes:
- Through a discord announcement channel, breaking change PRs must include porting instructions.
- Modders should test their mod on the preview after the 20th of each month, make any ports, and publish a new version if required. We hope the predictable release cycle and good communications from the tML team via discord can keep this a smooth process.
- **Bonus** Through a subscribe-able endpoint that can be used to trigger their own CI based on the results of our Action
  - How? Auto-rebuild and publish for each preview version? Needs more thought...

**Comment by Solxanich** [comment]
Design overview, from Discord:

How modders find out about breaking changes:
1) Through a discord announcement channel that gets written (ideally from Actions)
2) And Through a subscribe-able endpoint that can be used to trigger their own CI based on the results of our Action
3) It will be on the modder to stay informed & keep up outside of these two. We will be providing ample predictability to support them in this design.

These changes will NOT apply to time-sensitive hot fixes. Those will be accelerated in to release as soon as reasonably possible, with targeted testing in the form of Peer Review as needed. 
Time sensitive hot fixes will consist of a direct PR from the dev branch in to the stable release branch (and be cloned in to every other branch subsequently, ideally via Actions).

How Github will be changed:
1) 1.4 will be renamed as 1.4-qa. The branch where all non-time sensitive PRs will head to first.
2) a 1.4-preview branch will be created. Any PR targeting 1.4-qa will be cloned to here, assuming it meets the conditions to do so. Any PR targeting here directly will also be cloned in to 1.4-qa.
3) a 1.4-stable branch will be created. Only time-sensitive hot fixes may be PR'd to it. This is the 'Release' branch.

How the Workflow will go for Staging changes for Release:
1) 1st of the Month: 1.4-stable will be merged in to 1.4-preview & 1.4-qa via Actions to ensure all branches are consistent base. Likewise, 1.4-qa will be merged in to 1.4-preview.
2) PRs will be submitted to 1.4-qa. All PRs will be reviewed in some form before being accepted in to 1.4-qa. These PRs will be cloned in to 1.4-preview
3)  After the 20th of the month, PRs will stop being cloned from 1.4-qa in to 1.4-preview. This is the 'staging' window at which all changes are finalized and only targeted, time-sensitive bugfixes may be added to 1.4-preview via a PR to it directly. Modders should be able to trust that this is what they will see in release at the end of the month. PRs are submitted to 1.4-qa as normal for non-time sensitive changes  
4) End of the month/1st of the month at midnight -> 1.4-preview will be merged in to 1.4-stable IF it has the label "Deploy".
NOTE: preview can only be merged to stable via fast forward.
NOTE2: The Action that runs all of the 1st of the month tasks should be configured as a singular action with multiple steps for proper ordering.

Versioning: 
"the qa branch won't be versioned, it'll just be github commit shas
We can go with yyyy.mm.ff.pp versioning, where every change to preview implements ff, and every patch to release increments pp
stable will always be running last month's version, and preview will be this month's version"
All versioning should be auto-handled by github Actions.

How Steam & Modding will work for these branches:
1) A 'preview' folder will be added to the Workshop folder that will contain a version of the mod built against the preview branch. This preview version of the mod will be loaded if the player is on the preview branch, which will be determined by the release mod version being behind the current tml version.
2) When a mod is published on the stable branch, if its TML version is greater or equal to the TML version in the preview folder, the preview folder will be emptied. This would nominally happen around the 1st week of the month.
3) If a mod is published on the preview branch and the previous version of the mod that is in the preview folder is from the prior month, first the old preview file will be moved to be considered release, and then the new preview file for the new month will be added to the preview folder
4) Steam will consist of 3 branches - 1.4 (the release branch), 1.3 (1.3_Legacy Beta Option), Preview (1.4_Preview Beta Option)
5) Publishing on anything outside of those 3 branches will be blocked.
