### ISSUE TITLE
Add support for high dpi displays

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#2078]
### Description

Add support for high dpi displays.
Use https://wiki.libsdl.org/SDL_GetDisplayDPI & FNA high dpi variable: https://github.com/FNA-XNA/FNA/wiki/7:-FNA-Environment-Variables

### What does this proposal attempt to solve or improve?

Reports of blurriness on M1 and Windows

**Comment by Conofour** [comment]
This would be really awesome, most of us use 4k displays
