### ISSUE TITLE
[1.4 Alpha] No music at all

### ISSUE THREAD

**Issue by phruh** [bluemagic123/tModLoader#2088]
### Version
Latest public-1.4-alpha

### OS
Windows

### Platform
Steam

### Description
Music is at 100% volume, however there is no music at all, none on title screen, none in-game, none while music boxes are active.
![image_2022-01-11_062322](https://user-images.githubusercontent.com/88738597/148891788-1408d9b6-c42f-4e4b-a750-aadd152097d6.png)

### Expected behavior
Music would play at all times

### Actual behavior
Music doesn't play at all

### Reproduction frequency
Always

### Additional Information
*No response*

**Comment by theguywhoplaysterraria** [comment]
This is happening to me too

**Comment by Solxanich** [comment]
Temporarily fixed by rolling back to an older version. 
A formal fix is being worked on.
