### ISSUE TITLE
Crash when opening Settings menu during Lunar Events

### ISSUE THREAD

**Issue by flarn2006** [bluemagic123/tModLoader#2094]
### Version

Latest Official (v0.11.8.5)

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If I defeat the Lunatic Cultist and subsequently open the Settings menu, the game will crash with an error, even if no mods are loaded aside from tML itself.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7866560/client.log)

### Steps to reproduce

1. Defeat the Lunatic Cultist
2. Press Esc and click Settings.

### Expected Behavior

The Settings menu should appear.

### Actual Behavior

The menu does appear for a split second, then the game crashes with an error dialog.

### Reproduction frequency

Always.

### Additional Information

This is the same exact issue as #925. That issue additionally mentions searching Cheat Sheet for "pillar" causing the same crash, which is something I observed as well. I was going to comment on the issue with my log asking to reopen it, but then I saw a comment saying to make a new issue if it still happens, so that's what I'm doing now.

**Comment by Solxanich** [comment]
This probably would have been better to ask first in the Discord, as I believe this is a bug that is user side.

You'll want to try going to the file folder for Terraria (can get there through Local Files option in Steam), and delete everything in it.
Than reinstall Terraria. 

Basically, one of the pillars has an invalid file name for Unix, and if you've had Terraria pre-1.4, you can get a crash bug from the file failing to load.

**Comment by flarn2006** [comment]
Thank you; that helped me solve the problem. I had actually just done another test and narrowed it down to the Solar Pillar, and from there I was able to manually rename the offending file and avoid having to re-download everything. The file in question is `steamapps/common/Terraria/Content/Images/npc_517.xnb`. Renaming it to `NPC_517.xnb` fixed the issue.
