### ISSUE TITLE
Add a `Clone` method to Terraria.Recipe

### ISSUE THREAD

**Issue by Soaryn** [bluemagic123/tModLoader#2096]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Provide a new method in Terraria.Recipe named `Clone()` to provide a new instance of the same Recipe with all of the data copied to the new recipe. 

**Example:**
New item is introduced.
We want to loop over every recipe (added by mods or vanilla) and add a new recipe when a specific material is used.
This new recipe would be modified as such:
  - The specific material would be removed from the ingredients.
  - The new item we introduced would be added as an ingredient with a different stack size.
  - A new call back would be added to modify how the new item would be consumed

Key feature to note, is that the original recipe is still intact.
Something that needs to be addressed if this is added, is the ability to also remove callbacks, as `.Register` adds the Alchemy Callback which would break if registering a pure clone.

### What does this proposal attempt to solve or improve?

The intent is to allow new recipes to be added based on exact copies of other recipes. Say that you add a new item that has a special call back without modifying the original recipe. This item would work for similar recipes given a specific material.

Currently in order to create a copy of a new recipe, you can do so manually to some extent, but lack some critical information such as  `ConsumeItemHooks` or `OnCraftHooks` which would affect recipes such as Alchemy or other modded call backs.

### Which (other) solutions should be considered?

Opening up the call backs used in Recipe to not be internal. This, however, could open up new problems with mod compatibility, nor does it prevent other fields from being missed.

**Comment by Solxanich** [comment]
Closed per #2314 and confirmation from Dire
