### ISSUE TITLE
Bosses and NPCs

### ISSUE THREAD

**Issue by Rahmiel** [bluemagic123/tModLoader#21]
So originally I was noticing that NPCs weren't spawning and bosses don't _always_ spawn when using a boss calling item. This only applies to modded by the way. Anyways originally it was only happening with the Tremor mod, but now it has expanded to many other mods. Weird interactions with NPCs and Mobs. Not sure 100% if its the mods or tModLoader, my assumption is that it is a combination but mostly on the way the mod is using certain hooks for npcs, bosses, and mobs. Anyways I thought I would put this here just as an FYI. I really think tModLoader is amazing, you guys are creating a proper modding API for Terraria.

**Comment by bluemagic123** [comment]
Just to clarify, is this server-only or is it also in singleplayer?

**Comment by Rahmiel** [comment]
Definitely server side only. SP seems pretty much fleshed out, all of the major bugs right now are with MP. At least the gameplay affecting ones.
