### ISSUE TITLE
[alpha 1.4 bug]   

### ISSUE THREAD

**Issue by subaruchan** [bluemagic123/tModLoader#2102]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Not sure why this is happening but even when I have 0 mods enabled or even **installed**, all mobs for some reason have **6hp** this includes bosses too the only exception are NPCs and harmless mobs!!! I have re-installed TMod loader too to see if it fixed the problem... It didn't!!

**Comment by KIRILLAND78** [comment]
All mobs also deals 0 damage now.

**Comment by illethor** [comment]
Exact same thing for me. All enemies have 6 HP and they cannot hurt me. Only projectiles (such as arrows fired from a skeleton archer) are able to hurt me.

**Comment by steviegt6** [comment]
Could you send your logs? And is this recent (i.e. only started happening an hour or two ago)? This may be the result of a couple of very recent commits.

**Comment by subaruchan** [comment]
It's been patched in the very recent update no problems now👍👍👍

**Comment by Solxanich** [comment]
Was apparently a bug with last two updates, fixed in a recent commit. 9d644d48b36a9e3d41c0a56adcf1f70b1d6be57a
