### ISSUE TITLE
[1.4] Errors during workshop data loading cause crash

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2111]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If an exception occurs during refreshing/loading workshop information about mods (or resource packs too?), the code (that exists for vanilla resoure packs) tries to play a sound, but at this point the audio engine hasn't initialized yet, and a hard crash occurs:

![crash](https://user-images.githubusercontent.com/15894498/151063643-eb00126f-30e9-4669-9689-55f839fc1823.png)

Possible cause for such workshop exceptions: A corrupt `workshop.json`
Possible cause for the audio issue: Reordering of the sequence done for loading workshop content on tmls side

Possible solution: Look into the differences between vanilla sequence and tml sequence, especially in regards to audio initializing.

### Log File

Log: [Link](https://hst.sh/asadowamej.cs). The mod in question was [Dynamic Lights](https://steamcommunity.com/sharedfiles/filedetails/?id=2679594765) (error is from a few weeks ago, seems to be locally on the user side, as I haven't seen anyone reporting this on the workshop page, nor were there any updates)

### Steps to reproduce

Haven't tried reproducing yet

### Expected Behavior

Skips checking the corrupted mod, continues loading

### Actual Behavior

Crashes

**Comment by Solxanich** [comment]
Resolved in #2097
