### ISSUE TITLE
[1.4] Game fails to launch when audio device is not directly plugged in

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2112]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If the user has no audio device directly plugged in through USB or 3,5mm (i.e. a headset or speakers), the game fails to go past loading `FAudio.dll`, and closes without throwing an exception. This also occurs whenever an audio device is plugged in through different means (adapter, bridge, mixer, etc.)

This issue started appearing after #2000 got merged. 

A user who had this issue was asked to troubleshoot using files prior to the PRs merge, and it worked for him (with a mixer setup)

### Log File

Log: [link](https://hst.sh/emavumimom.cs)

**Comment by Chicken-Bones** [comment]
The hard crash has been fixed with 927e175d6492eb428e8514249416f1c3c106782f, but I need some help reproducing the mixer/bridge/adapter issue. I'm an audio novice

**Comment by Solxanich** [comment]
Just tossing an FAudio related log line here from someone trying to get audio trhough a PS4 controller:
```Assertion failed: speakerMaskIsValid == 1 && "SpeakerChannelMask is invalid. Needs to be one of" " MONO, STEREO, QUAD, 2POINT1, 4POINT1, 5POINT1, 7POINT1," " SURROUND, 5POINT1_SURROUND, or 7POINT1_SURROUND.", file C:\Games\Terraria\tModLoader\FNA\lib\FAudio\src\F3DAudio.c, line 133```

This still hard crashes

**Comment by direwolf420** [comment]
Same thing as above but with a USB wireless (bluetooth) adapter

**Comment by Solxanich** [comment]
Some notes from Discord:
ChannelMask = 0 is a valid speaker mask where the device will handle the management of audio. This combination isn't in FAudio. 
No one has confirmed what the particular value is of speakermask on crash.
For headphones, it was found that setting the Chat device as 'default communications device' and the Speakers device as 'default device' fixed the problem sometimes.

**Comment by Chicken-Bones** [comment]
Fixed in #2687
