### ISSUE TITLE
1.4 town NPC dialogue and buttons don't support tags

### ISSUE THREAD

**Issue by terrynmuse** [bluemagic123/tModLoader#2113]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Text such as "[c/00ff00:text]" no longer works for town NPC dialogue or buttons.

Previously, it was possible to make buttons such as this: https://i.imgur.com/3Wko7jf.gif
Instead, this occurs: https://i.imgur.com/266YaiO.png or https://i.imgur.com/keCQ1Lo.png

### Steps to reproduce

1. For a town NPC's SetChatButtons or GetChat, use a tag like "[i:1612]" or "[c/00ff00:text]"
2. Talk to the town NPC

### Expected Behavior

An input like "[c/00ff00:text]" should cause "text" to appear in red.
"[c/" + Main.DiscoColor.Hex3() + ":Receive Gift]" should cause "Receive Gift" to appear in rainbow text.

### Actual Behavior

The chat tags aren't used and instead appear as raw text.
The button seems to remove the colon as well.

**Comment by Rijam** [comment]
Bump because this issue has not been fixed. I also tested with the new "ModItem support to ItemTags".

![Capture2](https://user-images.githubusercontent.com/11262234/174429171-8cc33f94-b444-40e7-b9ab-c7ecbe9a3e22.PNG)
