### ISSUE TITLE
[1.4 Alpha] No sounds or music

### ISSUE THREAD

**Issue by DamianRada** [bluemagic123/tModLoader#2116]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

All volume sliders are at 100%, PC sounds work and the game is at max in the volume mixer. Tried reinstalling both tModLoader and Terraria. The sounds worked the first time I installed the 1.4 alpha, but when I went and launched tModLoader again 2 days after, I couldn't get the sounds to work no matter what.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7951119/client.log)

### Expected Behavior

Working sound and music.

### Actual Behavior

The game is completely silent.

### Reproduction frequency

Always

**Comment by Chicken-Bones** [comment]
Please try the workaround in https://github.com/tModLoader/tModLoader/pull/2687
