### ISSUE TITLE
[1.4 alpha] Bee's Knees fires twice per use

### ISSUE THREAD

**Issue by terrynmuse** [bluemagic123/tModLoader#2120]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Firing Bee's Knees once shoots two arrows. Seems to have 24 use animation but 23 use time, meaning the weapon fires again 1 tick before animation ends despite clicking only one time

### Reproduction frequency

Disabled all mods and issue still occurred. Used a Bee's Knees with no speed modifier. 

### Additional Information

May be related to vanilla nerfing Bee's Knees by making it shoot 1 tick slower?

**Comment by ilija04** [comment]
@Solxanich (and any other developer), you guys forgot to close this.
