### ISSUE TITLE
[1.4 Alpha] Game crashes when near sunflower and modded crafting table at spawn in journey mode

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2123]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I fly near or within a sunflower with fledgling wings while approaching a modded crafting table, the game freezes.
Another problem is that when I am even near a sunflower and a modded crafting table without flying, the game freezes.
This all happens in journey mode at the world spawnpoint.
![image](https://user-images.githubusercontent.com/70764728/151674476-fc5345c6-c8e0-4ae4-863a-b02c78603d74.png)
![image](https://user-images.githubusercontent.com/70764728/151674482-bd520c26-9e7c-4ca0-bc26-90b2993b447f.png)

### Log File

1st log: [client.log](https://github.com/tModLoader/tModLoader/files/7964379/client.log)
2nd log: [client.log](https://github.com/tModLoader/tModLoader/files/7964390/client.log)
 

### Steps to reproduce

1. Have a journey mode character and world
2. Enter the world and be near sunflowers at spawn. Fledgling wings are to be equipped.
3. Have a modded crafting table and place it down near the sunflowers (modded anvil, modded furnace, etc)
4. Game should be frozen or crash by that time.

### Expected Behavior

What should happen is that the crafting menu gets updated and no supposed further problems occur.

### Actual Behavior

The game freezes and/or crashes

### Reproduction frequency

Every time I join a world and get near a loaded modded crafting table and sunflowers.

**Comment by Solxanich** [comment]
Please direct all unverified bug reports to the # (alpha) support channel of the tmodloader discord, per the option presented when creating issues. (https://discord.gg/xFpbKkJ3)
It has active support available, and it is very unlikely you will receive a support response here normally on anything introduced by a mod.

With respect to your particular issue, someone in the discord saw this and has suggested this may be caused by the WMITF mod itself. 
IE, this is NOT a tml bug. 

I would recommend performing basic troubleshooting first before reporting these to reconfirm its not caused by the mod. For help with that, please reach out in the discord.

**Comment by Setnour6** [comment]
> Please direct all unverified bug reports to the # (alpha) support channel of the tmodloader discord, per the option presented when creating issues. (https://discord.gg/xFpbKkJ3) It has active support available, and it is very unlikely you will receive a support response here normally on anything introduced by a mod.
> 
> With respect to your particular issue, someone in the discord saw this and has suggested this may be caused by the WMITF mod itself. IE, this is NOT a tml bug.
> 
> I would recommend performing basic troubleshooting first before reporting these to reconfirm its not caused by the mod. For help with that, please reach out in the discord.

I do not have discord, but of course, I will take a closer look at it!
I originally thought that it would be a tml issue because this never happened back at tml 1.3.
I'll close this issue, hoping that this gets deleted because it's not really important, with love and respect to your response, of course. Thank you for letting me know about this!
