### ISSUE TITLE
Launching TML through batch file not working right(?)

### ISSUE THREAD

**Issue by IdrisQe** [bluemagic123/tModLoader#2130]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

using a batch file to launch the game with the -tmlsavedirectory option appears to fail.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7999759/client.log)

### Steps to reproduce

1. A batch file with the following code is made in Documents\My Games\Terraria\Instances\!_INSTANCE_BASE (a folder to test the functionality before starting to use it)
`start "" "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.exe" -tmlsavedirectory %~dp0`
2. The file is launched, with Steam open
3. (Optional) Try again running the batch file as an Administrator

### Expected Behavior

A seperate save directory should be created, similar to the "Documents\My Games\Terraria\ModLoader" default save directory, in the specified folder, with its own Worlds, Players, Mods, Mod Configs and Logs folders, and config.json and input_profiles.json files. The game should launch and run using this as its save directory.

### Actual Behavior

![image](https://user-images.githubusercontent.com/40530630/152466629-f82b0427-d64c-4b00-aed5-7879ebe23953.png)
A log file is created where the save directory should be, but the rest of the directory is not made, and the game fails to launch entirely, citing being unable to find the content directory (which is still in the same location as the tModLoader executable file, as always).

### Reproduction frequency

Happens every time.

### Additional Information

Running tModLoader through the executable normally works perfectly fine, so it appears to be some sort of issue with either the tmlsavedirectory option trying to find the content folder in the save directory, or some sort of issue with running it from a batch located in a different folder? No idea, but it's weird.

**Comment by Chicken-Bones** [comment]
You should come to the Discord and ask in #support. In answer to your question though, you need to `cd` to `C:\Program Files (x86)\Steam\steamapps\common\tModLoader`  before running the exe
