### ISSUE TITLE
Reversion of data-oriented tiles prevents world loading

### ISSUE THREAD

**Issue by Unknowneth** [bluemagic123/tModLoader#2141]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Due to the reversion of data-oriented tiles, worlds cannot be opened. It just says "Load failed! No backup found!". I tried creating new worlds and it does not solve the problem.

### Steps to reproduce

1. Open a world

### Expected Behavior

World opens fine.

### Actual Behavior

The world fails to load regardless of creation date.

### Reproduction frequency

100%, as of this test build

**Comment by Solxanich** [comment]
Data Oriented Tiles has since be re-implemented, so this loading issue should no longer apply.

Any remaining issues pertain to the mods you are using not being able to keep up with tML changes. Disable those in the event of that being the case.
Closing in light of that.
