### ISSUE TITLE
alpha 1.4 not loading worlse

### ISSUE THREAD

**Issue by gamerpogmandude** [bluemagic123/tModLoader#2142]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to load a world, even one that I has just created, it will say "load failed no backup found" on every single world no matter what.

**Comment by Solxanich** [comment]
Data Oriented Tiles has since been implemented, which breaks mods that haven't been keeping up with tML changes.

Any remaining issues pertain to the mods you are using not being able to keep up with tML changes. Disable those in the event of that being the case.
Closing in light of that.
