### ISSUE TITLE
don't come NPC to town

### ISSUE THREAD

**Issue by Serron5628** [bluemagic123/tModLoader#2143]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Player

### Description

NPCs don't come to our town. If NPCs dead, they never have return alive.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8041751/client.log)

### Steps to reproduce

1. NPCs are dead.
2. They never come to my town.

**Comment by direwolf420** [comment]
Please verify that this happens with 0 mods enabled. It is very likely that one of your mod is broken/not updated and causes issues like these. Also, test both singleplayer and multiplayer.

**Comment by JavidPack** [comment]
The log suggests that broken mods were enabled, closing.
