### ISSUE TITLE
tModLoader not launching, unabled to download dotnet 6.0.0

### ISSUE THREAD

**Issue by Nebdir** [bluemagic123/tModLoader#2147]
### Version

Latest public-1.4-alpha

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

upon changing to alpha-1.4 i noticed thet te modloader wont start, but upon digging deeper an vieweing logs i noticed that it wont be abled to download dotnet, as the 6.0.0 version isnt accessible anymore. as an workaround ive run LaunchUtils/dotnet-install.sh after first crash, copied the downloaded sdk from ~/.dotnet to dotnet/6.0.0 and limited the dotnet folder to be readonly (rxrxrx or 555) after that tmodloader launches as expected. ive reproduced this procedure on a second vm. 

Notice: Steam is installed via flatpak

### Log File

sadly lost, and i would like to keep the state as the tmodlaoder is running.

where is the line of my memories :

Cleanup Complete
Checking dotnet install...
undefined variable  ${link_types[$link_index]}, unknown index
Dotnet should be present in "/mnt/steamlib/steamapps/common/tModLoader/dotnet/6.0.0"
Attempting Launch...

### Steps to reproduce

1. install tModlaoder
2. set version to alpha-1.4
3. launch

### Expected Behavior

launching after a few seconds

### Actual Behavior

crash without any player visible notice, noticed in logs

### Reproduction frequency

every launch as long as not fixed via workaround

**Comment by Solxanich** [comment]
Could you double check this isn't a duplicate of #2140 ?
The behavior you described matches the comment I've provided on that.

If #2140 is accurate to your situation to a reasonable extent, we can close this issue

**Comment by Nebdir** [comment]
I'm sorry, I've missed the workaround you mentioned in #2140. I've done that and it's working great now.

ive noticed that you can work around the steam issues via flatpak-spawn, by that your spawning a proccess on the host that can access the correct environment and therefor get the correct dotnet runtime url. But using this might be considered as violation of the sandbox restrictions....

im not shure how fast stem can solve your issues, as this might only affect one game  within a special usecase.
maybe adding a workaround via flatpak-spawn (snap might have something similar) solve this as long as steam cant provide a solution.

but as the core issus of this is dublicated by this im closing this issues
