### ISSUE TITLE
tModLoader can't find mono

### ISSUE THREAD

**Issue by floatyHrzn** [bluemagic123/tModLoader#2159]
### Version

Latest Official

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When i press "Enable Developer Mode" it says i don't have mono 5.20 or above, but i have mono 6.12.

**Comment by Chicken-Bones** [comment]
Please come to the discord for problems like this. `mono` needs to be on your system path. If you can open a terminal and type `mono --version` but it still doesn't work, It's possible that it's part of the exports in your terminal startup file, but not part of the environment variables when tML is launched via steam. You can test this by running `./start-tModLoader.sh` yourself and see if it can find mono then. Past that my experience with Mac and Linux is limited so I'm not sure on the right way to get your path setup to work with steam, but a quick google should suffice
