### ISSUE TITLE
[1.4] Reverting FAudio to ffmpeg causes music to glitch once again

### ISSUE THREAD

**Issue by ilija04** [bluemagic123/tModLoader#2167]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

PR #2000 fixed this, but Mirsario reverted it, why?! Issue #1693 explains it, so i don't have to go through it again. Proof of reversion: https://github.com/tModLoader/tModLoader/commit/06eae28de3e9195041abdf120d5a17c924b50ff1

### Steps to reproduce

No steps needed

### Expected Behavior

Music not glitching

### Actual Behavior

Music is glitching

### Reproduction frequency

100%

### Additional Information

None currently

**Comment by dedisvoin** [comment]
почему при выборе персонажа он с поднятой рукой.????

**Comment by Solxanich** [comment]
Revert was due to #2112 

Simply put, game not launching is considered worse than audio not glitch. 

If someone is able to fix FAudio with the other backend, we can re-add it.

**Comment by Xaymar** [comment]
I'm unsure if my issue is the same or not, but I have this audio glitch for _all_ audio, not just music. It is as if the audio backend is being initialized with a buffer size slightly too short for the actual sample rate, and so it ends repeating a few milliseconds of audio.

**Comment by Chicken-Bones** [comment]
Follow #1693. I've reopened it since that's the original issue
