### ISSUE TITLE
PartyZombie NPC to have a replicated loot pool

### ISSUE THREAD

**Issue by justreq** [bluemagic123/tModLoader#2175]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A loot pool to PartyZombie that automatically replicates a particular vanilla NPC loot pool. That's pretty much it

**Comment by Solxanich** [comment]
Possible duplicate of #2174  due to mismatched timing.
Please confirm.

**Comment by justreq** [comment]
> Possible duplicate of #2174  due to mismatched timing.
> 
> Please confirm.

Yea it is, didn't see that one
