### ISSUE TITLE
Make NPC.DecideFallThroughPlatform a tML hook

### ISSUE THREAD

**Issue by Cyrillya** [bluemagic123/tModLoader#2178]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Add a new hook to NPCLoader called DecideFallThroughPlatform (or maybe a bool) which returns a bool. Allow collision NPCs to fall through platform if they wish. Instead of using On hook.

### What does this proposal attempt to solve or improve?

The only way to make custom AI collision NPCs to fall through platform now is to use the On hook NPC.DecideFallThroughPlatform.
Make it a new hook in NPCLoader would allow modders to decide if their NPCs can fall through platforms.

**Comment by Mirsario** [comment]
Handled with the above PR.
