### ISSUE TITLE
[1.4] When creating the 05162020 secret seed world, the moon isn't a smiley face during the world generation screen

### ISSUE THREAD

**Issue by ilija04** [bluemagic123/tModLoader#2184]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

Title again

### Steps to reproduce

1. Make a world with the secret seed 05162020
2. Look at the moon while it is generating
3. See error

### Expected Behavior

The moon should be a smiley face

### Actual Behavior

The moon is not a smiley face

### Reproduction frequency

Always

**Comment by qoobek** [comment]
maybe cuz the version you are playing is older than the seed. the seed was edded in 1.4.0.1 so mabye you have an older version?

**Comment by ilija04** [comment]
You don't understand what the title is saying. This IS a 1.4 report not a 1.3 one

**Comment by JavidPack** [comment]
Confirmed the issue.
