### ISSUE TITLE
".NET 4.5 Reference Assebmlies not found."

### ISSUE THREAD

**Issue by qoobek** [bluemagic123/tModLoader#2185]
### Version

Latest Official

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

When im going to mod sources it says this: ".NET 4.5 Reference Assemblies not found. Please install Visual Studio with the .NET 4.5 targetting pack." but i have visual studio but what about this .net 4.5 pack? i really dont know why it dosent work. when i clicking the button that downloads the tergetting pack it dosent change at all. am i dumb or is it sort of a glitch?

**Comment by Rijam** [comment]
This is covered in this guide: https://github.com/tModLoader/tModLoader/wiki/Developing-with-Visual-Studio#Prerequisites

For 1.3 modding, you need to install the .NET desktop development package using Visual Studios **2019**. You can use VS 2022 after you have done that if you prefer VS 2022.
Also, you cannot build mods on 64-bit tModLoader. Use 32-bit tModLoader to build mods.

**Comment by qoobek** [comment]
Thanks @Rijam ! Now i can open mod sources
