### ISSUE TITLE
Increase prefix id limit

### ISSUE THREAD

**Issue by Grimm590** [bluemagic123/tModLoader#2186]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

if its possible please increase prefix id limit for tmodloader 1.3 because most of the good mods are in the 1.3 version

### What does this proposal attempt to solve or improve?

be able to have more mods enabled

**Comment by JavidPack** [comment]
This is not likely to happen, 1.3 will not be receiving any breaking changes.

**Comment by genderneutralnoun** [comment]
+1 on this, or at least _some_ way of bypassing the prefix ID limit. I play some stuff on 1.4 but many of my favorite mods like Yoshi's Island are still on 1.3. It's really incredibly frustrating to have so much stuff divided between 1.3 and 1.4 right now. It's why I couldn't stay with Minecraft modding - there's too much of people being judgemental about which version you use.
