### ISSUE TITLE
problem with treasure bags

### ISSUE THREAD

**Issue by fabian123z3** [bluemagic123/tModLoader#2187]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

hello, when trying to open queen slime's treasure bag flashes the inventory and does not open, change the keys but it does not work either

**Comment by JavidPack** [comment]
We can't help you as you didn't post your client.log file. Most likely you have a broken mod though

**Comment by Solxanich** [comment]
Please inquire in the discord about support - this is not a bug with tmodloader but rather an issue with a mod you have installed using outdated code. 
Our support staff only operate on the discord at this time, and would be able to help narrow down which mod is the cause via the client.log.

The discord can be found here: https://discord.gg/7gjXZhQx
