### ISSUE TITLE
Modified executable

### ISSUE THREAD

**Issue by YAUIO** [bluemagic123/tModLoader#2188]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Executable is not modified&Steam checked, but i can't run tmodloader

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8193127/client.log)

**Comment by Solxanich** [comment]
Please inquire in the discord about support - this is not a bug with tmodloader but rather an issue with how you've installed tmodloader. Our support staff only operate on there at this time.

The discord can be found here:  https://discord.gg/7gjXZhQx

**Comment by YAUIO** [comment]
> Please inquire in the discord about support - this is not a bug with tmodloader but rather an issue with how you've installed tmodloader. Our support staff only operate on there at this time.
> 
> The discord can be found here: https://discord.gg/7gjXZhQx

k, thx <3
