### ISSUE TITLE
Не могу запустить tModLoader, что делать? 

### ISSUE THREAD

**Issue by limbusik** [bluemagic123/tModLoader#2193]
### Version

Latest Official

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

![Безымянный](https://user-images.githubusercontent.com/101392592/157836331-c4124f1d-5443-488f-a21d-a124c6076dd9.png)

**Comment by Mirsario** [comment]
## RU
В настоящее время вам необходимо иметь ванильную версию `v1.4.3.2` для того чтобы 1.3 TML распозновал ее как законную. Это изменится с `v0.11.8.7` TML, который выйдет сегодня/завтра (хотя я не заведую релизами).

Для справки в будущем - такие технические вопросы лучше задавать в [Discord](discord.gg/tModLoader), *на английском языке*. 

## EN
Currently, you need to have the `v1.4.3.2` vanilla version for 1.3 TML to recognize it as legitimate. This will change with `v0.11.8.7` of TML, which will be out today/tomorrow (I'm not the one managing releases though.)

For future reference - such tech support questions are better asked in [TML's discord](discord.gg/tModLoader), *in English*.
