### ISSUE TITLE
[1.4] Blocks are unable to be broken

### ISSUE THREAD

**Issue by theguywhoplaysterraria** [bluemagic123/tModLoader#2200]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When attempting to break any block or decoration it will fail to start breaking the block and if blocks are removed using cheat sheet natural plants will bug out.

### Steps to reproduce

1. Create a new world or enter an existing one
2. Attempt to break blocks

### Expected Behavior

Blocks will begin to break

### Actual Behavior

They never start breaking

### Reproduction frequency

It happens every time i attempt to break blocks

**Comment by Solxanich** [comment]
Please seek help in the Discord, not here. 
Our Support Volunteers only really operate there.
https://discord.gg/rBeRUrGF

This is not a bug with tml. 

A mod you have is incompatible with the current tml 1.4 version. 
Disable the appropriate mod. For help with that process, please ask in the discord.

**Comment by theguywhoplaysterraria** [comment]
Thank you
