### ISSUE TITLE
Compiling mods with "ModifyWorldGenTasks" hook doesn't work.

### ISSUE THREAD

**Issue by ronitrocket** [bluemagic123/tModLoader#2202]
### Version

Latest Official

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Any mods I have in the mod sources folder that override "ModifyWorldGenTasks()" in ModWorld do not build. To clarify, this occurs even if you override "ModifyWorldGenTasks()" but don't actually do anything inside of the hook. Mods that did not override this function are compiling and building as normal. In other words, it only occurs when modifying how the world generates. From what I can tell this problem is not widely or easily reproducible, as I have seen only one other post with a matching error and stack trace, with no replies.

### Log File

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/34007295/158294182-00529297-f5d5-4df9-809c-262fea8423ef.png">

### Steps to reproduce

1. Create mod with a file that inherits from ModWorld
2. Add world gen hook to the new mod world
3. Build the mod

### Expected Behavior

Builds the mod as normal.

### Actual Behavior

Does not compile with the error message "Value cannot be null. Parameter name: document". Seems to be that somewhere some file is pulled as null.

### Reproduction frequency

Every time.

**Comment by direwolf420** [comment]
If you get the "System.ArgumentNullException: Value cannot be null" error when building your mod on linux or mac, add `includePDB = false` to your build.txt. It is not specific to `ModifyWorldgenTasks` but rather (seemingly) any method that uses types like `List<T>`.

This is a platform deficiency (can you tag this issue with it @Solxanich) which is fixed in 1.4 as it's now all unified via netcore.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
