### ISSUE TITLE
[1.4 Alpha] Music boxes fails to record music for certain tracks

### ISSUE THREAD

**Issue by Awsomekeldeo** [bluemagic123/tModLoader#2204]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When a music box is equipped in an accessory slot and it attempts to record certain songs the recording sound will play, but the music box will not record the track.

The following tracks are not being recorded:
Hallow
Overworld Day
Jungle Day
Corruption
Underground Corruption
Underground
Underground Hallow
Boss 1
Boss 2
Boss 3
Eerie
Title

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8281716/client.log)

### Steps to reproduce

1. Equip a music box
2. Wait for it to record one of the above specified tracks, only the sound for recording plays but the music box doesn't record the song.

### Expected Behavior

The music box should record the song and play the record sound.

### Actual Behavior

The music box only plays the record sound, and doesn't record the song.

### Reproduction frequency

The issue is consistently reproducible.

### Additional Information

I suspect it has something to do with the fact that all of the music boxes for the affected songs have an internal item ID of less than 576, the ID of the blank music box.

**Comment by direwolf420** [comment]
Your logs mention mods being loaded. When you report bugs, make sure they happen without any mods enabled.
Here we see HEROs Mod causing an exception, which could be related to your bug:
```
[22:30:12] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at HEROsMod.HEROsModServices.InventoryManager.Update() in HEROsModServices\InventoryManager.cs:line 76
```

Try disabling it, and then testing again. If it doesn't happen anymore, report your bug to the HEROs Mod developer on the steam workshop.

**Comment by Awsomekeldeo** [comment]
I disabled HEROs Mod, and the bug still occurs.
Here's the log without any mods enabled:
[client.log](https://github.com/tModLoader/tModLoader/files/8288566/client.log)
