### ISSUE TITLE
My game audio is not working

### ISSUE THREAD

**Issue by OnlyLove01** [bluemagic123/tModLoader#2207]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I open my game, I get an error with the text "no audio hardware found. Disabling all audio."

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8301611/client.log)

### Steps to reproduce

It just runs my game and when it opens it has no audio

### Expected Behavior

that the game open and have audio

### Reproduction frequency

every time i open my game

### Additional Information

in my terraria the audio works normal, also in the tmodloader 1.3 version the audio works fine, it is only in this version that my audio does not work.

**Comment by Rijam** [comment]
It has something to do with FAudio. Try using wired speakers/headphones if you aren't already.
Join the tModLoader Discord and ask for help in the alpha-support channel. You are more likely to get help there: https://tmodloader.net/discord

**Comment by OnlyLove01** [comment]
> It has something to do with FAudio. Try using wired speakers/headphones if you aren't already.
> Join the tModLoader Discord and ask for help in the alpha-support channel. You are more likely to get help there: https://tmodloader.net/discord

Ty
