### ISSUE TITLE
0.11.8.8 not working

### ISSUE THREAD

**Issue by qoobek** [bluemagic123/tModLoader#2210]
### Version

Latest Official

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When i try to open tmodloader 0.11.8.8 it dosent work.

i tried EVERYTHING to try activate it and it didnt work

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8309661/client.log)

### Expected Behavior

It should open

### Actual Behavior

tModLoader dosent open

**Comment by Rijam** [comment]
Join the tModLoader Discord and ask for help in the support channel. You are more likely to get help there: https://tmodloader.net/discord

**Comment by Solxanich** [comment]
Needs Terraria version 1.4.3.6 B on GoG (ie latest)
You likey have 1.4.3.6 A installed.
Not a bug in tml. If you need additional support, please reachout through the discord mentioned.
