### ISSUE TITLE
I Cant Make a mod

### ISSUE THREAD

**Issue by qoobek** [bluemagic123/tModLoader#2211]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

0.11.8.7

Im trying to make a mod but i cant make it cuz it says this:

Error: C:\Users\awboz\OneDrive\Dokumenty\My Games\Terraria\ModLoader\Mod Sources\roboxmod\Items\Weapons\roboxSwordOfEternity.cs(34,33) : error CS0103: The name 'ItemType' does not exist in the current context

And the code of the item is this:

using Terraria.ID;
using Terraria.ModLoader;

namespace roboxmod.Items
{
	public class roboxSwordOfEternity : ModItem
	{
		public override void SetStaticDefaults() 
		{
			DisplayName.SetDefault("R0B0X's Sword of Eternity"); // By default, capitalization in classnames will add spaces to the display name. You can customize the display name here by uncommenting this line.
			Tooltip.SetDefault("The Sword of the hero!");
		}

		public override void SetDefaults() 
		{
			item.damage = 500;
			item.melee = true;
			item.width = 40;
			item.height = 40;
			item.useTime = 3;
			item.useAnimation = 7;
			item.useStyle = 1;
			item.knockBack = 6;
			item.value = 1000000;
			item.rare = -12;
			item.UseSound = SoundID.Item1;
			item.autoReuse = true;
			item.useTurn = true;
		}

		public override void AddRecipes() 
		{
			ModRecipe recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemType<StarFragment>(), 50);
			recipe.AddIngredient(ItemType<RoboxBar>(), 1);
			recipe.AddTile(TileID.Anvils);
			recipe.SetResult(this);
			recipe.AddRecipe();
		}
	}
}

### Expected Behavior

It should load the mod

### Actual Behavior

It dosent load

**Comment by JavidPack** [comment]
Please keep programming and support questions to our discord in the future. This issue tracker is only for bugs, not user error.

To answer your question, the correct code is `ModContent.ItemType<RoboxBar>()`,
