### ISSUE TITLE
Strange bug making tmod unopenable.

### ISSUE THREAD

**Issue by Naruto123Uzi** [bluemagic123/tModLoader#2215]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

<img width="305" alt="Screenshot 2022-03-18 125854" src="https://user-images.githubusercontent.com/101990268/159175213-12c3114d-0729-409e-871b-5750892df1ea.png">

Game won't open. I've tried every solution and this issue persists.

### Log File

Log files are not being made with this bug. Latest one is from two months ago.

### Steps to reproduce

I have no idea.

### Expected Behavior

The game should be opening correctly.

### Actual Behavior

Crashes and doesn't offer any solution.

### Reproduction frequency

Everytime.

**Comment by Awsomekeldeo** [comment]
I don't think this is a bug with tModLoader, it seems as though you don't have permissions for that folder and that's why it's crashing. Are you logged in to the Owner account on that computer? If so, try moving the C:/Users/Documents/My Games/Terraria/ModLoader/Logs folder somewhere else and re launching the game.

**Comment by Rijam** [comment]
Follow this guide on how to solve that: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#SystemUnauthorizedAccessException-Access-to-the-path-is-denied

**Comment by Naruto123Uzi** [comment]
> I don't think this is a bug with tModLoader, it seems as though you don't have permissions for that folder and that's why it's crashing. Are you logged in to the Owner account on that computer? If so, try moving the C:/Users/Documents/My Games/Terraria/ModLoader/Logs folder somewhere else and re launching the game.

No way just moving the damn file worked. Thank you.
