### ISSUE TITLE
Open Sources button does not work due to not escaping space in 'Mod Sources' folder path

### ISSUE THREAD

**Issue by daud-ahn** [bluemagic123/tModLoader#2218]
### Version

Latest Official

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When i press the Open Sources button in Mod Sources menu, it does not do anything

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8312729/client.log)
![image](https://user-images.githubusercontent.com/72173079/159197916-bdda7843-9d3f-4141-b152-89fb2eec4c85.png)

### Steps to reproduce

1. Enable Dev mode
2. Open "Mod Sources" menu
3. Click 'Open Sources'

### Expected Behavior

It should open 'Mod Sources' in the file manager

### Actual Behavior

nothing

### Reproduction frequency

100%

### Additional Information

Linux Mint 20.2 Cinnamon 64 bit

**Comment by JavidPack** [comment]
Ok, seems like we need to quote that. In the meantime, just open the folder it mentions.

An update won't come anytime soon for 1.3.

**Comment by Solxanich** [comment]
This is fixed in 1.4 as of #2133 . Closing as won't be fixed in 1.3
