### ISSUE TITLE
Requests for some new hooks, modification requests for old hooks, and others

### ISSUE THREAD

**Issue by shb201902040125** [bluemagic123/tModLoader#2223]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

About the old hook：
    When loading data or savedata, request to add whether the data has already created a file. If a file has been created, request to pass the file path (similar to ModPlayer.LoadData), which is helpful for the implementation of some independent archives, such as my own LargerInvtory.tomd now has to Obtain this information by other means
    Sometimes, we care about whether the player holds an item and need to know its location, such as the item slot or accessory slot, and its Index. In fact, many mods will implement this function repeatedly, which is not conducive to the improvement of game performance. Maybe you can make it official
    
    
About the new hook:
    About Player:
    CanBuy,CanSell,modifyPrice in need
    About Recipe:
    Requires a method that can dynamically modify Recipe requirements, such as determining whether the Recipe is displayed and its required items according to the player's game progress during synthesis
    About Modloader:
    Dynamic ModIcon and WorldIcon display in the interface
    The method of adding IsTerraria in ModContentLoader, like adding public bool IsTerrair(int type) in ItemLoader to easily and save space to determine whether it is the original content. There are also methods like public bool FromMod(int type, out Mod mod)

About the new content
    ModLiquild please
    ModEvent and normalization
    Customize player appearance, such as hair style
    Translations of custom hotkey for
    ModAchievement, I'm sure there have been many modders who have been longing for this for a long time

About the bug or content of the public version
    When I was writing custom-sized subworlds, I noticed that you didn't check the map's array size. Seems like this should be taken seriously if subworlds are considered in the future
    I hope someone can standardize the IEntitySource, the current classification is too messy, and I hope this data can be passed to the modder, because sometimes it may be necessary to determine where a new entity comes from
    The color settings in the current version of setshopbutton are invalid like [c:xxxxxx]
    In the current version, automatic continuous use is unavailable after right-clicking is enabled.
    Selling an item expects not to give coins but to return the specified special item (when its purchased with a custom currency)

Only these are currently recorded, and may continue to be submitted in the future.Thanks for taking the time to review this issues.
Due to my limited English level, the above content is from Google Translate, please understand

### What does this proposal attempt to solve or improve?

LoadData/SaveData add new param about file can help modders create custom archive files to read and write.
HasItem(out Info) can Realize some combination effects of fixed arrangement, like only the correct arrangement of some items can make it activate the effect.
CanBuy/Sell and modifyprice just like the environment affects trading, like you need to defeat certain bosses to be able to buy or reduce the price when buying
Recipe like modifyprice,Modders have requirements for a certain item to be synthesized differently or hidden in different periods. For example, I have a spray used to purify the world. I hope that before and after defeating Plantera, I need a different amount of moonlight grass and display it, but The current composition query doesn't do this (I know it's possible to create multiple compositions and constrain them with Condition, but this can be changed using a modify when the UI is drawn, instead of asking for more memory space)
Dynamic ModIcon and WorldIcon can sse a separate class, or a method subordinate to the Mod class, if you visit the steam workshop, you can see that some mods from China are already doing this, but they all use reflection and don't have exception handling measures. I'm concerned that they will have bad effects on other mods (once they go wrong it will cause the mod loading page to be inaccessible, creating issues like not being able to uninstall)
ModLiquid and ModAchievement It has long been something that Chinese modders have been expecting, especially after the release of starriver. I noticed that the Steam Workshop has a LiquidLibrary, which actually doesn't perform well enough.

**Comment by shb201902040125** [comment]
I found there had canbuy.please ignore it

**Comment by JavidPack** [comment]
Modders shouldn't really be saving player data to their own files, that won't be compatible with how the game manages backups and cloud saves.

Everything else you mentioned already has existing issues or is actively being discussed in the discord as far as I can see.

We can't really do anything about this Issue, as there are dozens of completely different topics being suggested. I'd suggest coming to our discord to talk if any of these topics are of particular importance.

**Comment by shb201902040125** [comment]
>

**Comment by shb201902040125** [comment]
> 修改者不应该真的将玩家数据保存到他们自己的文件中，这与游戏管理备份和云保存的方式不兼容。
> 
> 据我所知，你提到的其他事情已经存在问题，或者正在不和谐中积极讨论。
> 
> 我们对这个问题真的无能为力，因为有几十个完全不同的主题被提出来。如果这些话题有什么特别重要的话，我建议到我们的分歧处来谈谈。
It seems so. But I don't know how to delete this issue.its almost useless.Maybe I should think more carefully.
But I still expect to be able to implement ModLquid.
