### ISSUE TITLE
Fatal Error when running tModLoaderServer.exe in mono and systemctl service

### ISSUE THREAD

**Issue by VividLemon** [bluemagic123/tModLoader#2234]
### Version

Latest Official

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I downloaded the server files from the Terraria homepage, then downloaded the tModLoader files, both latest. Everything works fine on manual startup. I am running tModLoaderServer.exe using Mono on an armv7 chip with aarch64. (Raspberry pi) The server will start and run fine on manual startup. However, when attempting to run the server using a cron job or systemctl service, it crashes at the very end of the server initialization. Read the log file for the exact exception. It may be related to how the system chooses to receive input from the command line. Though, I don't know for sure and cannot se what is null in the exception. I cannot seem to fix this using this entire setup. 

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/8393243/server.log)

### Steps to reproduce

1. Using raspberry pi (or any armv7 chip)
2. Using mono
3. Creating a cron job, or systemctl service
4. Error

### Expected Behavior

It should start up without issues. 

### Actual Behavior

Null execption

### Reproduction frequency

Never works

### Additional Information

It works fine when not running it in a service. Running the scripts manually works fine.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
