### ISSUE TITLE
Dotnet install script is broken in linux

### ISSUE THREAD

**Issue by DuendeInexistente** [bluemagic123/tModLoader#2238]
### Version

Latest public-1.4-alpha

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Trying to launh the game from steam (Latest stable branch) does nothing. Launching steam from terminal, I see the error is:
```
pid 54173 != 54070, skipping destruction (fork without exec?)
pid 54168 != 54070, skipping destruction (fork without exec?)
./dotnet-install.sh: line 1173: link_types[$link_index]: unbound variable
Dotnet should be present in "/media/cammera/ExtStor/Juegos/SteamLibrary/steamapps/common/tModLoader/dotnet/6.0.0"
Download of portable dotnet runtime seems to have failed,
proceeding will probably use system wide installed runtime
Please press Enter to try to run the game anyway...
```
This makes it impossible to launch the game.

### Log File

There is no log, the game doesn't reach that point.

**Comment by Solxanich** [comment]
Duplicates #2140
