### ISSUE TITLE
Interface.MessageBoxShow shows wrong log path

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2241]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When a fatal error occurs, the incorrect log path is shown to the user

![image](https://user-images.githubusercontent.com/4522492/161366786-09366d43-be30-4669-8df2-50c88fcc8d32.png)

`string message = Language.GetTextValue("tModLoader.ClientLogHint", text, Path.Combine(Main.SavePath, "Logs"));`

**Comment by Solxanich** [comment]
Fixed in [49bea95dae222c12a0409c8bc8fa73be7953180a](https://github.com/tModLoader/tModLoader/commit/49bea95dae222c12a0409c8bc8fa73be7953180a)
