### ISSUE TITLE
Parts of HUD Missing

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2244]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Parts of HUD are not displaying on the new 1.4 preview branch.
![image](https://user-images.githubusercontent.com/70764728/161404815-ebf3e262-74d3-4f9c-be7f-21e0f50a97a4.png)
![image](https://user-images.githubusercontent.com/70764728/161405049-46776ddd-da8a-4fcf-b7e0-d4d1d0f66ad0.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8403539/client.log)

### Steps to reproduce

1. Create new character or import character
2. Create new world or import world
3. Join world
4. There you have it.

### Expected Behavior

HUD loads normally, and everything is shown.

### Actual Behavior

Parts of the HUD are missing.
There is no Life/Mana display, no Cursor display (except when opening settings in bottom right corner), no item info display.

### Reproduction frequency

Always, since the new preview update.

**Comment by JavidPack** [comment]
Since you have various mods enabled, it is likely an issue with one of them. You'll need to disable mods and reload to discover which mod is causing the issue.

This issue tracker is for bugs with tmodloader, not support for broken mods. You can come to the discord server support channel for live support type questions related to mod issues.

**Comment by Setnour6** [comment]
So I checked the mods I have, and there are more than one mods that cause the issue, but it happens many times. It doesn't seem normal in my perspective to have mods make the tooltips and cursor invisible.
I don't have discord, unfortunately, but I thought that it could originally be a tModLoader issue, because I've done some testing beforehand, but it just feels very ambiguous -- the whole "invisible tooltips, missing UI, invisible cursor" thing. As I said earlier, it never happened before until the introduction of the new branches.
**Edit:** I disabled every mod, and the item tooltips and cursor is brought back, but the health and mana bars are still gone. It has to be a tML issue.

Also, one more question for the new 1.4 mod thing. Do the 1.3 rules still apply? (i.e. using Git Bash, tModLoader Patcher, etc.) Because I have this error where child process couldn't be forked or something like that on Git Bash.
`Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.
`
I haven't been able to rebase or anything like that. I think uninstalling Git Bash could be the answer, and then reinstalling it.

**Comment by JavidPack** [comment]
The issue is caused by errors in mods. You joined the preview branch, which most mods haven't updated to, so that's why multiple mods are causing the issue. You should be on stable if you want to avoid these issues, or wait for those mods to update. 

If you want to determine which mods are causing the issue, you can read the log: <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#reading-clientlog>

I'm not sure about your git issues, running setup.bat with git installed should be sufficient. These sorts of issues are best solved in the Discord chat, come on by.

**Comment by Setnour6** [comment]
> The issue is caused by errors in mods. You joined the preview branch, which most mods haven't updated to, so that's why multiple mods are causing the issue. You should be on stable if you want to avoid these issues, or wait for those mods to update.
> 
> If you want to determine which mods are causing the issue, you can read the log: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#reading-clientlog
> 
> I'm not sure about your git issues, running setup.bat with git installed should be sufficient. These sorts of issues are best solved in the Discord chat, come on by.

Thank you for the welcome (and I know that it's been 6 days already), but I do not have discord, and I am not planning on making a discord account. I will think about it though. I prefer the older way, where Gmail messaging comes in, and YouTube.

I did receive a couple of errors when running setup.bat, but I think it could be the work of my antivirus (I'm using an external antivirus software) preventing some things from loading some required stuff. I also cannot add an allowed app, because I have the external antivirus installed. I'll try to find another way.
I sort of found one way though by making a small change to something and sending a pull request (about an item resprite).

Once again, thank you for the welcome and for letting me know about this!

**Comment by luks556** [comment]
Hola, tengo un problema con algunas trxturas de tmodloader, el rastro que dejan la terrablade aparece blanco, los tintes en las ropas aparecen como un cadrado blanco al rededor del personaje, algunas cosas del hud del menu de pausa aparecen en blaco, ¿que hago para solucionarlo? Ya probe desactivar todos los mods y packs de textura y sigue igual. Soy de linux y juego por steam
