### ISSUE TITLE
csteamworks.dll is not present in the current steam release

### ISSUE THREAD

**Issue by mav1o1** [bluemagic123/tModLoader#2245]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

csteamworks.dll is not present in the latest steam release.

### Steps to reproduce

1. Install Terraria from Steam.
2. Browse the game files.

### Expected Behavior

csteamworks.dll should be located in the /Terraria folder.

### Actual Behavior

csteamworks.dll is not located in the /Terraria folder.

**Comment by JavidPack** [comment]
I checked and the file is there. Maybe your antivirus or something else is quarantining it.

<https://steamdb.info/depot/1281932/>
