### ISSUE TITLE
[1.4] Can't hover right

### ISSUE THREAD

**Issue by terrynmuse** [bluemagic123/tModLoader#2249]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Holding DOWN+JUMP to hover doesn't let you move right, only left.

**Comment by JavidPack** [comment]
Works for me, make sure you have 0 mods enabled, as any bug with mods enabled is likely a mod error. You also didn't post the log file.

**Comment by terrynmuse** [comment]
Bug occurs with no mods enabled using starboard. Nothing seems to appear in client.log

**Comment by JavidPack** [comment]
Just tested celestial starboard, works fine as well. Might be your keyboard? Try testing in regular terraria again.

**Comment by terrynmuse** [comment]
Turns out it's vanilla behaviour. Probably because I have an external keyboard plugged into my laptop. Built-in keyboard can hover right and external keyboard can hover right but only if I bind any key except D to right. Bizarre

**Comment by JavidPack** [comment]
K, well, since this seems to be an issue with your hardware, I'm closing this.
