### ISSUE TITLE
[1.4] IndexOutOfRangeException at the end of Credits roll after defeating Moon Lord

### ISSUE THREAD

**Issue by blahblahbal** [bluemagic123/tModLoader#2250]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I defeated the Moon Lord in a fresh world and watched the credits, and at the end of them, I got an IndexOutOfRangeException. I'm the latest 1.4-stable on Steam (v2022.3.35.3).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8406144/client.log)

### Steps to reproduce

1. Spawn and defeat the Moon Lord.
2. Watch the credits until the end
3. Note the error in the chat

### Expected Behavior

No error

### Actual Behavior

The error shows up in chat

### Reproduction frequency

I haven't tested it more than once, since it's a rather long process

### Additional Information

Nothing

**Comment by Solxanich** [comment]
Fixed in #2256
