### ISSUE TITLE
interfaz desapears

### ISSUE THREAD

**Issue by alexjred** [bluemagic123/tModLoader#2251]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

happen when i start a fight whit a boss the interfaz disapears and i dont know what to do :C i want to play tmod but nothin y tried to desactive all my mods an the bug stills :c please help me

### Steps to reproduce

start a fight whit a boss
nothing more xd
happens automatically  when the fight stars whit every boss

https://user-images.githubusercontent.com/102942169/161481099-65915081-0c89-469b-84af-8091bf6e3e64.mp4

### Expected Behavior

# # #

### Additional Information

the mods i had where lights and shadows omniswing better boss healt not consumable boss sumon fast builder and max stack plus

**Comment by JavidPack** [comment]
You didn't post the log file, so we can't really solve this for you.
