### ISSUE TITLE
Ability to use Page Up/Down And/Or Arrow Keys to rapidly navigate Mod Browser

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#2253]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

The current Mod Browser UI works solely off of the MouseScroll event. 
This makes navigating difficult if your scroll wheel locks up, and reasonably looking through pages of mods difficulty to line up.

It would be nice to have the ability to page up/down through mods using the Page Up/Down keys OR the arrow keys.

### What does this proposal attempt to solve or improve?

Ability to navigate the tons of mods in a consumer-friendly fashion

**Comment by steviegt6** [comment]
FYI, this functionality would be implicitly provided if we get around to adding controller support to the UIs. Elements with supported controls will cause the UIList to automatically scroll when accessing scissored elements.
