### ISSUE TITLE
Loading screen always stuck at "setting up" 

### ISSUE THREAD

**Issue by LonePerv** [bluemagic123/tModLoader#2255]
### Version

Latest Official (1.3)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Every time I freshly launch tmodloader, I always get stuck at "setting up" screen and I have no idea why. The first time I got this, it got automatically resolved after few hours out of nowhere without doing anything. Second time I got stuck, I reinstalled tmodloader which helped for that one time. Next time I got stuck again and reinstalling didn't resolve the issue. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8416315/client.log)

### Steps to reproduce

Just launching

### Expected Behavior

Setting up screen should go away in few seconds going to next step

### Actual Behavior

Setting up screen is stuck very long time, minimum 10 minutes and nothing changes

### Reproduction frequency

Every tmodloader launch

**Comment by JavidPack** [comment]
There is not much to go on here. If I were you, I'd try with 0 mods enabled, then slowly add mods until you can figure out what is breaking.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
