### ISSUE TITLE
[1.4 -stable] dotnet.exe error ( decided ) 

### ISSUE THREAD

**Issue by OverKot** [bluemagic123/tModLoader#2261]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![2324](https://user-images.githubusercontent.com/58006439/162180672-ebe108d8-e562-47ff-b2a5-ab41fa106cca.png)
But game start

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8442050/client.log)

### Steps to reproduce

1. Start game in steam
2. Error but game start

https://user-images.githubusercontent.com/58006439/162181852-c14bcc7a-751d-4caf-b027-1f77dba8f41c.mp4

**Comment by devraza** [comment]
I presume that you haven't install .NET 5/6 properly? Since it seems as though Windows can't find the `dotnet.exe` file.

**Comment by OverKot** [comment]
> 

I reinstall .net 5 and 6, error still here.
![434](https://user-images.githubusercontent.com/58006439/162236164-af179011-2146-4ec3-9d4b-04da8b2eee7f.png)
maybe i need to put the files in the tmod folder?

**Comment by devraza** [comment]
You're right, wherever you installed it, it wants it in a different directory.

**Comment by JavidPack** [comment]
Try deleting the dotnet folder and trying again. Also check your antivirus quarantine, it is a common culprit for this. If you want support help, please visit the discord chat, we mainly deal with reproducible bugs and feature requests on github.

**Comment by OverKot** [comment]
I don't have an antivirus and I killed the Defender service. I deleted the folder and ran tmod, it downloaded again, but the error remained, I'll try again.

**Comment by OverKot** [comment]
No longer needed, I solved the problem
1. delete dotnet folder from tml
2. running tml installed dotnet itself ( but my internet speed dropped, and it took a long time to download )
