### ISSUE TITLE
[1.4-stable] File size that upload to Steam Workshop is HUGE

### ISSUE THREAD

**Issue by Cyrillya** [bluemagic123/tModLoader#2263]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When I tried to publish a mod to Steam Workshop:
![image](https://user-images.githubusercontent.com/35227653/162566479-36bbb6d4-95bf-4ba3-b72b-8901913d81d3.png)
The mod file size becomes huge, with 67+Mb addition.
![image](https://user-images.githubusercontent.com/35227653/162566739-3cecae0e-a999-4b24-b8ea-cc0e447404f9.png)
This didn't happen until the 1.4-stable and 1.4-preview branches were out.

### Log File

It doesn't require a log file I think.

### Steps to reproduce

1.Create a mod in tModLoader
![image](https://user-images.githubusercontent.com/35227653/162566594-bc274b65-86a6-4871-bb52-e12953d65748.png)
2.Use visual studio debug to run the mod once.
![image](https://user-images.githubusercontent.com/35227653/162566636-b39c8a0c-771b-4272-926b-9a9ae165f874.png)
3.Close tModLoader and reopen it from steam. Publish the mod.
![image](https://user-images.githubusercontent.com/35227653/162566702-5365fb5f-93f2-4cde-af88-3b77812d7eab.png)
4.It becomes huge now.
![image](https://user-images.githubusercontent.com/35227653/162566719-92b080b8-8107-4771-ba21-9c995d316577.png)

### Expected Behavior

The mod file size should be under 1Mb

### Actual Behavior

The mod file size becomes huge, with 67+Mb addition when I publish the mod to Steam Workshop.

### Reproduction frequency

Every time

**Comment by Cyrillya** [comment]
I just noticed it seems that tModLoader publishes the entire source code folder of the mod to workshop.
Maybe excluding bin/ and obj/ folder will help?
All I can do to reduce size is to delete the entire mod from the steam workshop and publish it again. If you delete bin/ folder and publish an update, the mod size will still be huge.

**Comment by Solxanich** [comment]
It shouldn't be posting the entirety of the Mod Sources folder to Steam. 

THat seems like an error; what you can start with for troubleshooting is go to:
steamapps\workshop\content\1281930 
Find your mod in one of the subfolders; delete the unnecessary files, and than push out a new update and see how that goes.

There is nothing in the publishing code that would cause it to copy the entire folder currently.

**Comment by Kabaril** [comment]
I noticed the same problem when publishing my mod. When downloading the mod from the steam workshop the following is the content of the folder.
![grafik](https://user-images.githubusercontent.com/39504487/162592455-287223f4-865e-4302-a8a1-edef3ad421ad.png)

The compiled .tmod file seems to be in the '2022.3' Folder, but the entire source folder was uploaded to the workshop.
![grafik](https://user-images.githubusercontent.com/39504487/162592681-706e71ef-166e-46a2-8566-73855185a7a7.png)

![grafik](https://user-images.githubusercontent.com/39504487/162592692-b4be50a3-e839-446c-8efb-d9477ada44e0.png)

**Comment by ScalarVector1** [comment]
The same appears to have happened to me according to comments on my mod's workshop page, with the entire source being published to the workshop. While this isnt a problem for me as my project is open source, it could certainly be an issue for some users.

**Comment by Solxanich** [comment]
Folks, did any of you use 1.4/1.4 preview github builds between March 23rd and April 1st?
If you published with that, that may be related.

Otherwise I can't seem to reproduce on the latest preview/stable

The only file I'm aware of that had changes that could cause this is : https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.TML.cs

**Comment by Solxanich** [comment]
Ah, found the issue. Newly published mods are messed up. 

https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/Social/Steam/WorkshopSocialModule.cs.patch

Temporary Folder method needs to be like WorkshopTemp/ instead of ModSources. 

I'll see if someone can fix that real quick

**Comment by Solxanich** [comment]
All, I've heard that there has been trouble with getting the source files out of the published mods for those who were unlucky to have published net-new mods prior to this being fixed.

For those in that situation, please follow these instructions:

1) Download the attached tmodloader.dll and replace the tmodloader.dll in your installation
2) Re-publish the mod - this custom tmod stable version will treat all files as if its the first publish - meaning it will wipe out all files currently on steam workshop. 
3) If your mod is on preview - not to worry! Just publish a dummy mod on stable that contains no-code using steps 1&2, and than you can proceed to publish on preview again. 
4) Finally, the important step here is to restore the original tmodloader.dll afterwards! This is not a proper version.

[New Compressed (zipped) Folder.zip](https://github.com/tModLoader/tModLoader/files/8550687/New.Compressed.zipped.Folder.zip)
