### ISSUE TITLE
Modded items disappear from chests along with NPC's 

### ISSUE THREAD

**Issue by cohen537** [bluemagic123/tModLoader#2275]
### Version

Latest Official (1.3)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

All of the modded items in my chest have disappeared and all of the modded NPCs have also disappeared. There are still modded items in my inventory and NPCs still sell modded items.

### Expected Behavior

My modded items in chests existing.

### Actual Behavior

My modded items in chests not existing

### Reproduction frequency

None

**Comment by JavidPack** [comment]
This is more of a support question, so you'll find better luck in the discord support channels. My guess is your .twld file got deleted or a mod you are using is broken. You can restore from backups or disable the broken mods if those are the cases. We won't be able to help you here.
