### ISSUE TITLE
The chat is permanent and won't go away unless you save and quit. It will scroll down but not disappear.

### ISSUE THREAD

**Issue by Cirilloboy** [bluemagic123/tModLoader#2276]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Chat won't disappear. It affects my vision and makes me think an npc has arrived when it didn't.

### Steps to reproduce

1. have any text appear.

### Expected Behavior

It disappears.

### Actual Behavior

Won't disappear.

### Reproduction frequency

At all times

**Comment by JavidPack** [comment]
Works for me, hides after 10 seconds or so. You didn't post your log, so I can't check if its being caused by a mod, but you can check by trying with 0 mods enabled.

**Comment by Cirilloboy** [comment]
figured it out it was my easy pot breakers mod
