### ISSUE TITLE
Outdated ItemUseStyleID (SwingThrow, etc.) Magic Number to ID Prompt used in 1.4 modding (should be Swing)

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2283]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![image](https://user-images.githubusercontent.com/70764728/163084049-51348a78-e6fa-4e7b-8008-232127e4a853.png)
Should be provided as Swing, not SwingThrow. Same goes for some other IDs. EatingUsing should be EatFood.
![image](https://user-images.githubusercontent.com/70764728/163084454-c7e30855-e275-4014-96f7-0f8a216eb115.png)
EatFood is the correct definition for style IDs in 1.4 modding.
EatingUsing is obsolete.

Must be from old style ids file provided or something. Basically ItemUseStyleID.cs is being used but listing is outdated in/for 1.4 use.

### Steps to reproduce

1. Open your mod.csproj file.
2. Navigate to and open your item.cs file that contains a ItemUseStyleID.
3. If prompted, change magic number to ID,
4. changed to SwingThrow or any obsolete ID provision. This gives you an error and prompts you to change it to the appropriate style ID. It should be Swing or any new ID saying.

### Expected Behavior

Magic Number change to ID, ID being Swing, for example.

### Actual Behavior

ID is SwingThrow instead of Swing.

### Reproduction frequency

Whenever I work on an item that uses ItemUseStyleID.

### Additional Information

What are all of the brand new style IDs in order? I want to make sure I have the names right (i.e 1 = Swing, 2 = EatFood. I know these are right, but correct me otherwise).

**Comment by direwolf420** [comment]
This is an issue for https://github.com/tModLoader/tModLoader.CodeAssist/issues

**Comment by Setnour6** [comment]
> This is an issue for https://github.com/tModLoader/tModLoader.CodeAssist/issues

Perhaps the Code Assist Repo can receive an update because of this issue, or to be duplicated and updated for 1.4 use.

Also, do you know where the Style IDs are listed in the wiki here are? I want to update the page to say "in 1.4, the ItemUseStyle will be ...", or something like that.

**Comment by direwolf420** [comment]
They are listed here: https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide

**Comment by Setnour6** [comment]
> They are listed here: https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide

Thank you Direwolf!

**Comment by JavidPack** [comment]
Fixed as of tModLoader.CodeAssist v0.1.4, VS should update it automatically I think.

**Comment by Setnour6** [comment]
> Fixed as of tModLoader.CodeAssist v0.1.4, VS should update it automatically I think.

Thank you Javid!
