### ISSUE TITLE
Constant Updates which don't need to release (because no new commits shown or done)

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2296]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Github Actions has gone haywire.
I think some people already know that, which might make this issue post useless and un-needed, but it's better so more people can think of how to fix it.

There hasn't been a new commit in quite a while, and yet there are still updated released but by github actions, which aren't supposed to happen because there hasn't been any commits in a while, or so it says on my screen. Last time there was a commit by Javid and JamzOhJamz but that was two releases ago, if you get what I am saying.

### Additional Information

This issue might be useless if everyone already knows what is happening. I just wanted to put it out there and say it quickly before something bad actually happens.

**Comment by JavidPack** [comment]
It's working as intended. We brought over about 10 fixes from 1.4 into 1.4-stable over the last 24 hours. No API changes, just fixes. The updates are intended

You might be looking at the wrong branch. The updates to stable come from commits to 1.4-stable

**Comment by Setnour6** [comment]
> It's working as intended. We brought over about 10 fixes from 1.4 into 1.4-stable over the last 24 hours. No API changes, just fixes. The updates are intended
> 
> You might be looking at the wrong branch. The updates to stable come from commits to 1.4-stable

Ohhh how did I not realize earlier?!? Thank you Javid! Now I know that the 1.4 stable branch is receiving the 1.4 preview commits.
