### ISSUE TITLE
Linux: Wrong version of Mono used *only* when launched from Steam

### ISSUE THREAD

**Issue by mszegedy** [bluemagic123/tModLoader#2302]
### Version

Latest Official (1.3)

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

This is both a player-facing bug and a modder-facing bug. When tModLoader is launched via Steam, via _any_ executable, it uses the bundled (?) version of Mono, which is 4.6.1.

However, if I launch `~/.steam/steam/steamapps/common/tModLoader/tModLoader-mono` via the command line, then it uses my own installed version of mono, which is 6.12.0 at the time of writing.

### Log File

https://pastebin.com/NjCyaUKn

### Steps to reproduce

Launch tModLoader on Linux via Steam, then read the log file.

### Expected Behavior

It should launch with whatever version of Mono you have installed in `/usr/bin/mono`.

### Actual Behavior

It launches with Mono 4.6.1.

### Reproduction frequency

Every time.

### Additional Information

When tModLoader uses Mono 4.6.1, it is broken in several ways, most notably via the SecureChannelFailure error that usually prevents it from using the internet (leading to a hang-on-boot bug if set to developer mode, when it tries to fetch the latest `ModCompile_XNA.zip` from the Github releases and can't), but also leading to drastic performance issues on Linux. Seriously, I thought this was just something I had to put up with, but no, it's easily fixable.

When using my machine's Mono 6.12.0, the slowdowns disappear, and it can access the mod database without issues, allowing it compile mods correctly and just generally be a usable developer platform.

I understand that the 1.4 branch uses .NET 5.0 anyway, and is no longer reliant on Mono. (That one crashes on boot for me, but that's a separate issue altogether.) This is a massive quality of life improvement, though, so I felt compelled to document it still.

**Comment by JavidPack** [comment]
You'll have to replace `tModLoader` and `tModLoaderServer` with the `-mono` versions. I believe the game has some way to migrate from one file to the mono versions, but I guess that didn't work for you.

**Comment by mszegedy** [comment]
In the "custom command" box on Steam, I told it to use the `-mono` executable, though. Does that just not work?

**Comment by JavidPack** [comment]
I don't think adding that would do anything. As far as I know we never programmed something like that in.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
