### ISSUE TITLE
tModLoader "Please ensure Steam is logged in and running." Error.

### ISSUE THREAD

**Issue by Joestanky** [bluemagic123/tModLoader#2306]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When opening tModLoader, I am presented with this text box:

![image](https://user-images.githubusercontent.com/104093920/164288869-8c86f194-e26e-423f-8138-50a61a81b104.png)

I have steam running, I have checked compatibility with my OS, ran as administrator, verified my files, deleted and re-acquired the tModLoader.exe file as well as redownloaded tModLoader and Terraria.

If there are any other suggestions I would be glad to take them.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8523835/client.log)

### Steps to reproduce

1. Open tModLoader
2. Error may pop up.

### Expected Behavior

The app should load presumably?

### Actual Behavior

The app is not loading and is instead giving me an error.

### Reproduction frequency

100% of the time.

### Additional Information

Nothing else except I was able to run the app last night though I couldn't access the Mod Browser from the app.

**Comment by JavidPack** [comment]
We've never been able to track down any reason for this issue over the years, it usually goes away with time or a restart. Sorry.

**Comment by keskokavero** [comment]
you don't own Terraria on your steam account. i guess it's shared from another account (i had same issue)

**Comment by EldritchCrow** [comment]
I have the same issue, and I own my copy of Terraria. It persisted after a restart.

**Comment by Leo777-max** [comment]
there is a steam_api.dll file above the tmodloader, I deleted it and I managed to enter tmodloader

**Comment by Fetnak** [comment]
i found smth interesting.

If the original terraria executable file has the name "Terraria.exe ", then it defines the distribution platform as "GOG", but when it has a name "Terraria_v1.4.3.6.exe ", then it defines the distribution platform as "Steam".

I hope this helps fix it.

"Terraria.exe" log
`[18:55:09] [Main Thread/INFO] [tML]: Save Are Located At: C:\Users\Fetnak\Documents\My Games\Terraria\tModLoader
[18:55:09] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built сб,02.07.2022 0:14
[18:55:09] [Main Thread/INFO] [tML]: Log date: пт,29.07.2022
[18:55:09] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 6.0.0
[18:55:09] [Main Thread/INFO] [tML]: Executable: D:\Games\Terraria\tModLoader\tModLoader.dll
[18:55:09] [Main Thread/INFO] [tML]: Working Directory: D:\Games\Terraria\tModLoader
[18:55:10] [Main Thread/INFO] [tML]: Distribution Platform: GoG. Detection method: Terraria.exe found, no steam files or directories nearby.
[18:55:10] [Main Thread/FATAL] [tML]: D:\Games\Terraria\Terraria.exe is not the unmodified Terraria executable.

GOG installs must have the unmodified Terraria executable to function.

If you patched the .exe, you can create a copy of the original exe and name it "Terraria_v<VERSION>.exe"
`

"Terraria_v.1.4.3.6.exe" log
`[18:42:40] [Main Thread/INFO] [tML]: Save Are Located At: C:\Users\Fetnak\Documents\My Games\Terraria\tModLoader
[18:42:40] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built сб,02.07.2022 0:14
[18:42:40] [Main Thread/INFO] [tML]: Log date: пт,29.07.2022
[18:42:40] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 6.0.0
[18:42:40] [Main Thread/INFO] [tML]: Executable: D:\Games\Terraria\tModLoader\tModLoader.dll
[18:42:40] [Main Thread/INFO] [tML]: Working Directory: D:\Games\Terraria\tModLoader
[18:42:42] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.3.6_B.exe not found nearby`

**Comment by nyazexs** [comment]
bro all you have to do to fix this is copy and paste the tmod files to the terraria folder and have steam launched

**Comment by Chicken-Bones** [comment]
tModLoader for 1.3 is no longer supported. You can try asking in the tModLoader Discord for #support, but the best thing you can do is make sure your Terraria is up to date, and do a fresh re-install of Terraria and tModLoader.

**Comment by Namra606** [comment]
i done everythink i saw in comment but the error is not fixing someone pls help

**Comment by Kamomiki** [comment]
I think the problem is the Steamworks.NET.dll
when I test the TML 0.11.8.9, it still connect to steam.

**Comment by tmuaprep** [comment]
same here bruh

**Comment by Wevowavo231** [comment]
Yo Listen, When you have the folder of the tMod with all of its files just copy all those and paste it to the same files where you put the original Terraria, when you have that done just open Steam and let it open there go back to the files find the file named "start-tModLoader" or "start-tModLoader.bat" and yeah I think that's all it you only need a cracked terraria too to make it worked somehow the paid terraria on steam is down.

I do hope it helps.

**Comment by H20Alex** [comment]
So i had TModLoader on desktop, then i moved it in the Terraria folder. The game launched, so i entered my world. Almost every item had the same texture (item unkown) so i went in the workshop and installed all my previous mods (they got deleted). Now the game runs perfectly fine.

**Comment by Zero37dot4** [comment]
If you don't own tmodloader and got it from a friend, then plz don't put it on onedrive. Move it to C: drive or D: drive

**Comment by acefaa** [comment]
nahhh
