### ISSUE TITLE
No oceans

### ISSUE THREAD

**Issue by GlizzyGloblin** [bluemagic123/tModLoader#2322]
### Version

Latest Official (1.3)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i use the mod world previewer and see what my world looks like the ocean doesn't generate so when I disable it and check it for myself in a new world the ocean doesn't generate. i keep trying to make a new world and even installing tmodloader but it wont work

**Comment by iamrusskih** [comment]
It's one of ur mods issue, use https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart and report an issue to creator of the mod is causing it

**Comment by Rijam** [comment]
This is a known issue with Plentiful Ores. Don't use that mod.
