### ISSUE TITLE
Tmod 1.4 sound issue

### ISSUE THREAD

**Issue by Zukamia** [bluemagic123/tModLoader#2323]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Both branches presents this annoying glitching sound. Already tried fresh reinstall and does nothing.

https://youtu.be/khF6Z5Q57R0

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8578995/client.log)

### Reproduction frequency

Everytime tmod is open.

**Comment by goldengear1111** [comment]
Don't worry this will be fixed

**Comment by RealZyther** [comment]
I'm also encountering a bug like this, strange part is this only happens on alpha for me.
The strange part is that it doesn't occur on the unofficial 64-bit branch of 1.3.5.3 tModLoader, even though they both use FAudio.

**Comment by Mirsario** [comment]
What audio formats are your default devices set to? This sounds like that could be related.
On Windows, you find it out like this: Control Panel -> Small Icons -> Sound -> Playback -> Right click the default device -> Properties -> Advanced -> See 'Default Format'.
Mine's currently `16bit, 48000hz`, which is the most common.

**Comment by RealZyther** [comment]
> What audio formats are your default devices set to? This sounds like that could be related. On Windows, you find it out like this: Control Panel -> Small Icons -> Sound -> Playback -> Right-click the default device -> Properties -> Advanced -> See 'Default Format'. Mine's currently `16bit, 48000hz`, which is the most common.

I'm also encountering the same issue Zukamia is having, and I have the same format you do, 16-bit, 48,000hz, 2 channels.

**Comment by Bhased** [comment]
I have the same issue as zyther kinda, it says no audio device located

**Comment by Zukamia** [comment]
> What audio formats are your default devices set to? This sounds like that could be related. On Windows, you find it out like this: Control Panel -> Small Icons -> Sound -> Playback -> Right click the default device -> Properties -> Advanced -> See 'Default Format'. Mine's currently `16bit, 48000hz`, which is the most common.

Was using 24bit 48khz, changed for every option and still the same, sadly.

**Comment by RealZyther** [comment]
Hey did you ever manage to fix this? Calamity Mod is now on 1.4 and I really want to play it, but the audio being bugged ruins it for me. I've tried several headsets, wired or wireless and nothing works...

**Comment by Chicken-Bones** [comment]
See workaround in #1693
