### ISSUE TITLE
Angler reward duplication

### ISSUE THREAD

**Issue by neswii** [bluemagic123/tModLoader#2325]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Angler non-consumable rewards are duplicated and can merge when stored or sold.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8587983/client.log)

### Steps to reproduce

Complete quest from angler
retrieve reward that is non-consumable
two copies of non-consumable items are received
sell or store one of the copies and the other may disappear

### Expected Behavior

All rewards from angler should not be duplicated

### Actual Behavior

Non-consumable rewards from angler are duplicated.

### Reproduction frequency

I have been able to reproduce the issue every time. With all mods disabled, it is there. 

### Additional Information

Using mods like fargo's mutant mod's infinite fisher quest tweak can help test this feature more quickly.

Polaritz reported the bug as well in discord and spoke with Thomas on April 19, direct link to video by them showing the issue: https://discord.com/channels/103110554649894912/871289059396448337/965998818929832017

**Comment by Chicken-Bones** [comment]
Fixed in #2326
