### ISSUE TITLE
Day EoL is blue

### ISSUE THREAD

**Issue by Ouroel** [bluemagic123/tModLoader#2327]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

EoL projectiles are blue instead of yellow during the day

### Steps to reproduce

Spawn Empress of Light during the day

Wait for her to spawn projectiles

### Expected Behavior

EoL projectiles should be yellow

### Actual Behavior

EoL projectiles are blue

### Reproduction frequency

Every time

**Comment by Setnour6** [comment]
I can confirm that the same issue applies to me as well

**Comment by JavidPack** [comment]
Why was this closed?

**Comment by Setnour6** [comment]
> Why was this closed?

I don't know

**Comment by Setnour6** [comment]
> > Why was this closed?
> 
> I don't know

Oh wait I think I know why. I just tested it in game and the problem is no longer there. I'll keep testing and see if the problem persists with some mods enabled. This could be a mod problem, but I'll have to confirm.

**Comment by Ouroel** [comment]
Day EoL is blue again

**Comment by Chicken-Bones** [comment]
`client.log` required. Does it happen with no mods enabled?

**Comment by Chicken-Bones** [comment]
Note for future testers, may be date related?

**Comment by JavidPack** [comment]
Sorry, I thought the answer was already here, since it came up a lot in the discord. This happens as an easter egg that happens randomly and on specific dates. It's not present in 1.4.4 though.

So, not a bug, intended.
