### ISSUE TITLE
[1.4] [Feature Request] Update Mod Type Resolution

### ISSUE THREAD

**Issue by steviegt6** [bluemagic123/tModLoader#2332]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

tModLoader only allows mod assemblies to contain one type which derives from `Terraria.ModLoader.Mod`.[^1]

[^1]: https://github.com/tModLoader/tModLoader/blob/d6c564c66d81fe7b1d5fac3e714d455501f3b4d6/patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs#L178

### What does this proposal attempt to solve or improve?

While this is _normally_ fine, it poses an issue if you were to do something like offer an abstraction on top of `Terraria.ModLoader.Mod`. I develop and maintain a library where the default implementation of library features reside within a mod class. These default implementations should ideally be made available to users of the library.
You could argue that these should be delegated to `ModSystem`s or something similar, but a direct association is cleanest.

A demonstration of the issue as as follows:
```cs
public interface ILibraryMod
{
		ILibraryFeature Feature { get; }
}

// Used by both the Library AND serves as a *default implementation* for mods that wish to use the library.
public class LibraryMod : Mod, ILibraryMod
{
		public ILibraryFeature Feature { get; } = new DefaultLibraryFeature();
}
```
Here, you may observe how both a library and mods that use the library have a reason to use some sort of default implementation to reduce boilerplate. This is dangerous because you cannot have an abstract `Mod`-extending class that implements this behavior.

Here is how I currently solve the issue:
```cs
public class LibraryMod : Mod, ILibraryMod
{
		public ILibraryFeature Feature { get; } = new DefaultLibraryFeature();

		public override void Load()
		{
				ExecutePrivately(() => { /* some library-specific task */ });
		}

		private bool ExecutePrivately(Action task)
		{
				if (!GetType().Assembly.FullName?.StartsWith("LibraryName, ") ?? false)
						return false;

				task();
				return true;
		}
}
```
I have to wrap library-specific logic in a hacky method that checks if the type belongs to my library.
This entire hassle could be avoided if we were given the ability to define abstract `Mod` types.

### Which (other) solutions should be considered?

N/A

**Comment by steviegt6** [comment]
Some internal discussions have made me realize this may require a rewording to make my reasoning for this change clear. Some questions have been brought up regarding the necessity of this implementation. I'll be making some edits tomorrow to reflect these developments.

**Comment by Chicken-Bones** [comment]
I'd suggest you make `LibraryMod` abstract, and have your actual 'mod class for the library' extend it

**Comment by steviegt6** [comment]
> I'd suggest you make `LibraryMod` abstract, and have your actual 'mod class for the library' extend it

The issue is this causes an error while loading. While this would work under normal circumstances, tML throws an exception if two `Terraria.ModLoader.Mod` types are resolved, regardless of whether one is marked `abstract` or not.

**Comment by Chicken-Bones** [comment]
Sounds like a better and easier thing to fix

**Comment by Chicken-Bones** [comment]
Super easy to address if not already. @ExterminatorX99 did you want to look at this?
