### ISSUE TITLE
Daytime EoL Attacks Are Blue Instead of Yellow

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2334]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

[Written on behalf of @Ouroel. See issue #2327]

Empress of Light's Projectiles and Attacks are blue instead of the usual yellow color during the day.
(Note that I have just tested it on May 2 and the problem is no longer there, but it was there the day before. Further testing is needed to confirm.)

### Steps to reproduce

1. Enter a world
2. Summon Empress of Light during the day
3. Wait until she attacks with her projectiles

### Expected Behavior

The projectiles that come from Empress of Light are yellow during the day

### Actual Behavior

The projectiles that come from Empress of Light are blue, as if the time for her is night time.

### Reproduction frequency

Every time (Prior to May 2)
Little or None.

### Additional Information

Again, this might be a mod issue, but the mods I had enabled at the time never affected the sprites of the bosses, or so I see it. It has likely been fixed as of the new tModLoader update, but I'm not sure.

**Comment by JavidPack** [comment]
I believe this is an unintentional side effect of various date based easter eggs in tmodloader.
