### ISSUE TITLE
[1.4] Memberwise clone should not be the default behavior for ModX classes

### ISSUE THREAD

**Issue by ScalarVector1** [bluemagic123/tModLoader#2337]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

As of the latest stable patch, all mod types default to a memberwise clone as opposed to calling the default constructor of the class as before. This is both very unclear to developers and is inconsistent with the frequency of use of memberwise cloning vs default constructor use for most users. It also requires large amounts of repetitive code in the form of re-intializing all instanced refference type fields in the Clone hook whenever an instanced refference type field is desired on any child of these classes.

Note this is specifically for ModX classes, not GlobalX classes. This includes things such as ModNPC, ModItem, etc.

### What does this proposal attempt to solve or improve?

Reverting to the previous default behavior would make the behavior of cloning on these types match the expected behavior of nonstatic fields, and eliminate the need to re-initialize fields in the clone hook for normal applications such as items and NPCs storing refferences to other objects in the game world.

### Which (other) solutions should be considered?

Having the creation of new entities not require cloning some existing instance of the ModX class associated with those entities may address symptoms of this problem (as it is also slightly unintuitive that this is how they're created)

**Comment by Chicken-Bones** [comment]
I agree. See #2338

**Comment by Chicken-Bones** [comment]
Fixed in #2398 and #2421
