### ISSUE TITLE
[Critical] Lists are not instantiated per entity

### ISSUE THREAD

**Issue by Ouroel** [bluemagic123/tModLoader#2338]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Lists assigned to ModProjectile are shared between instances of ModProjectile

### Log File

none

### Steps to reproduce

#1 - Create a projectile with InstancePerEntity on and a list

#2 - Add something to the list in SetDefaults

#3 - Create 2 instances of the projectile

#4 - Call Main.NewText(list.Count)

### Expected Behavior

There is 1 item in the list

### Actual Behavior

There are 2 items in the list

### Reproduction frequency

All the time

### Additional Information

This wasn't present in previous versions

**Comment by Chicken-Bones** [comment]
Since a recent change, you must override `Clone` on any `ModType` you create which can't be copied via `MemberwiseClone`. I'm considering reverting this behaviour

**Comment by Ouroel** [comment]
How do you overwrite Clone on GlobalProjectile/GlobalNPC/etc

**Comment by Chicken-Bones** [comment]
Fixed in #2398 and #2421
