### ISSUE TITLE
ModLoader Mod name does not match its assembly name

### ISSUE THREAD

**Issue by pbone64** [bluemagic123/tModLoader#2339]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

tML ModCompile (and I believe mod loading) require mod names to match their assembly names, with the exception of tModLoader's internal ModLoader Mod. I suggest changing the name of the ModLoader Mod to `tModLoader` to be consistent with all other tModLoader mods.

**Comment by JavidPack** [comment]
This would break mods at this point, so we won't be doing this. Sorry this issue seemed to have been forgotten.
