### ISSUE TITLE
Glowmask: Unable to retrieve texture

### ISSUE THREAD

**Issue by Illvidri** [bluemagic123/tModLoader#2340]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

While attempting to apply a glowmask, the .GetTexture() method seems to be missing, or the namespace has been changed and is not recorded in the docs.

### Expected Behavior

My goal is to use .GetTexture() to get the filepath of a texture, and then convert it to a Texture2 type.

### Actual Behavior

After attempting various methods proposed by the internet in the form of glowmask application tutorials, I have found that none of the various supposed methods work due to the missing .GetTexture() method.

### Reproduction frequency

100% of the time.

### Additional Information

The documentation has the namespace as Terraria.ModLoader.ModLoader.GetTexture( string name ) as a static Texture2D. I cannot find any other working alternatives. Also, if I am somehow missing something, knowing what that is would be helpful.

**Comment by Rijam** [comment]
Try `ModContent.Request<Texture2D>("Path/Glowmask")`
If it says it can't convert it into a Texture2D, try adding `.Value` to the end (or cast as `(Texture2D)`).

**Comment by Illvidri** [comment]
Thank you very much. This worked. I did find that a full path name is required, including the mod name. Regardless, once again, thank you.
