### ISSUE TITLE
calamity and fargo's mod error

### ISSUE THREAD

**Issue by ThomasPoloBelgini** [bluemagic123/tModLoader#2347]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

so, i've recently been trying to enable fargo's mod and calamity mod together, but it didn't work and always got the same error, see a image: https://user-images.githubusercontent.com/103902330/165602490-1d757b1c-0ead-489d-a9c0-ef9004e6e951.png / 
![image](https://user-images.githubusercontent.com/103902330/167012628-b9f3ed2d-9c29-42cd-9ce4-016d7bc8c503.png)

Note:im on 11.8.9 version,

so how can i solve that?

(i used google translator to translate that)

### What does this proposal attempt to solve or improve?

a fargo's and calamity mod error

### Which (other) solutions should be considered?

i doon't know

**Comment by JavidPack** [comment]
This is a mod error, you should come to the discord for support with mod errors. We do not do mod support here. Here is what you would be told if you came to discord with this error:

> If you're getting the following error when trying to use Fargo's Mutant Mod, disable Calamity Mod (No Calamity Music) and Fargo's Mutant Mod, reload mods, enable Fargo's Mutant Mod,. reload mods again, then disable the banner recipes option in the Fargo's Mutant Mod configs.

**Comment by ThomasPoloBelgini** [comment]
THANKS!!!!!!!!
