### ISSUE TITLE
Targeting reticle for summons doesn't show up when holding whips

### ISSUE THREAD

**Issue by Ender19** [bluemagic123/tModLoader#2352]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When holding a whip, the targeting reticle for your summons doesn't appear.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8646038/client.log)

### Steps to reproduce

1. Obtain a whip
2. Attack an enemy
3. The reticle doesn't appear

### Expected Behavior

The targeting reticle should appear.

### Actual Behavior

The targeting reticle doesn't appear.

### Reproduction frequency

Every time.

### Additional Information

The targeting reticle shows up if you hold any other summon weapon.
The targeting reticle still seems to function, it's just invisible.
It seems like the whip is being treated as a non-summon weapon.
This behavior was produced with an empty mod list.

**Comment by Rijam** [comment]
Fixed in #2360 ?
