### ISSUE TITLE
World generation not equal to vanilla Linux and quite different to vanilla Windows

### ISSUE THREAD

**Issue by Unftf** [bluemagic123/tModLoader#2354]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

A world seed is supposed to generate the same world for everyone who want to use it. 
Currently (1.4.3.6) the world generation is not equal for vanilla Windows and vanilla Linux (Mac not tested here probably similar/equal to Linux)
tModloader generates a world which matches neither of those. However it is quite similar to the vanilla Linux version. But to share it with people who dont use or can't use tModloader (like speedrunner) it would be very nice if world generation matches at least one vanilla version.
Here some example of the seed '1'
On windows it looks like:
![image](https://user-images.githubusercontent.com/39495683/167317124-90cc2f3f-917c-42e3-b025-062283b9ae58.png)
On linux:
![image](https://user-images.githubusercontent.com/39495683/167317170-2343c303-1c17-405c-8459-40eb745b9496.png)
On tModloader: (different in later world gen step e.g.Enchanted sword shrine, minecart track, jungle underground tree. cobweb)
![image](https://user-images.githubusercontent.com/39495683/167317271-789581be-7eb5-4251-817d-4f966672242b.png)

### Steps to reproduce

1. Start tModloader without any mods
2. Generate a certain seed there
3. Start vanilla Terraria and generate the same seed there
4. Compare to world file size or with some map viewer e.g.: https://terramap.github.io/

### Expected Behavior

one world seed should lead to the same world as in vanilla Terraria (at least for one OS)

### Actual Behavior

The generated world has minor differences (but those can have huge impact on playing) to vanilla Linux world generation.
The difference to vanilla Windows is much greater. However the difference in between vanilla Linux and Windows is a vanilla problem. This bug report is only about tModloader not equal to vanilla version.

### Reproduction frequency

100% (but only tested 2 seeds for now)

**Comment by Solxanich** [comment]
TerrariaNetCore on Windows: 
![Foundation of Contentment](https://user-images.githubusercontent.com/59670736/167520571-d5efa737-e1a4-4eca-8a1d-78743b2d9e71.png)

Can confirm the variance between Linux Vanilla and Windows tModLoader is an issue at the tModLoader patch level.

**Comment by Unftf** [comment]
For a better view of the differences here a picture of differences in between the current 1.4-preview (on linux) and vanilla linux world gen of seed 1
![image](https://user-images.githubusercontent.com/39495683/167683601-ea2d769d-30c6-4e4e-9134-8ce9891f1626.png)

**Comment by jaydevelopsstuff** [comment]
I suspect this probably has to do with how random numbers/noise are generated on different platform, maybe that could be looked into.

**Comment by Unftf** [comment]
1.4.4.9 Update: Almost equal!

It looks like windows and Linux world gen is 100% equal for vanilla. Could not find any mismatch so far (out of 10 seeds).
tModloader Worldgen is also equal on Linux and Windows.

But there is still some small discrepancies in between vanilla and modded world gen.
Here seed '1' in vanilla:
![image](https://user-images.githubusercontent.com/39495683/216905464-ef08948f-fae1-446a-aee0-b1bc775d942d.png)
and here with tModloader: 
![image](https://user-images.githubusercontent.com/39495683/216905825-9d66383b-7114-466b-9025-b70ac24eab2a.png)
They look almost equal. But if we do some diff picture:
![image](https://user-images.githubusercontent.com/39495683/216915352-3e0f5c82-0602-48f4-bd7b-b5a3c47a4399.png)
we can see small differences.

Depending on the seed it can look different.
difference from seed 's1' looks like this:
![image](https://user-images.githubusercontent.com/39495683/216914690-ca129675-da4f-4c4c-b6c4-02a05ee4510a.png)

or 's2'
![image](https://user-images.githubusercontent.com/39495683/216913991-6847bdbb-d50c-431f-93fe-6f578eb9a539.png)


If we look closer
![image](https://user-images.githubusercontent.com/39495683/216917570-5c16f021-ec7a-4ac4-b2d3-440b9d16bddc.png)
![image](https://user-images.githubusercontent.com/39495683/216917160-0f106569-4c63-42b7-a13e-dfe51ac99c6c.png)
We can see it is mainly (all?) deco with TileID 165 and gem-trees

------------------------------------------
edit:
Thank you so much Chicken-Bones!

but e.g. secret seeds can not be generated again in vanilla (maybe 1.4.5). tModloader mods can assist with that.

**Comment by Chicken-Bones** [comment]
I put significant effort into solving the playform difference in vanilla so I'm glad it paid off!

Closing this issue as tML to vanilla world gen parity is not a priority for us to maintain (and may not even be possible while also providing a good modded experience).

You can always generate a world on vanilla and play it on tModLoader
