### ISSUE TITLE
[1.4] [Multiplayer] Players and NPCs in not yet visited places fall through the map

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2359]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Happens on both stable and preview.

![Screenshot_1](https://user-images.githubusercontent.com/15894498/167658607-6cc84ce7-9b3d-4bdc-a20c-2e48b8d39eda.png)

In multiplayer, players and NPCs that are in not yet loaded chunks (pre-tile rework: tiles are all null) appear as not having any tile collision. This makes town NPCs falling perpetually on the minimap. Same happens to players, but player update packets get sent regularly so it always rubberbands up and down. The latter player issue also *sometimes* affects teleport effect, such as wormhole potion: You end up teleporting to a location several dozens of tiles below the player, usually suffocating in tiles as a result of that.

This wasn't happening pre-tile rework.

### Log File

No errors in the logs when this happens, neither client nor server

### Steps to reproduce

Place a town NPCs far away from spawn
Host world in multiplayer
Open world map
Watch the NPC fall into the abyss

**Comment by absoluteAquarian** [comment]
Can confirm for players at least.  After the tile rework, the following checks for if a player is "out of range" (see: `Player.Update()`) fail due to tiles never being null:

```cs
                int num2 = (int)(base.position.X + (float)(width / 2)) / 16;
                int num3 = (int)(base.position.Y + (float)(height / 2)) / 16;
                if (!WorldGen.InWorld(num2, num3, 4))
                    flag = true;
                else if (Main.tile[num2, num3] == null)
                    flag = true;
                else if (Main.tile[num2 - 3, num3] == null)
                    flag = true;
                else if (Main.tile[num2 + 3, num3] == null)
                    flag = true;
                else if (Main.tile[num2, num3 - 3] == null)
                    flag = true;
                else if (Main.tile[num2, num3 + 3] == null)
                    flag = true;
```

`flag` being true flags this other client's player as being "out of range" of this client's player

**Comment by Chicken-Bones** [comment]
Then it looks like what we need is a client side version of `RemoteClient.TileSections` which gets cleared on MP world join, and set in `DecompressTileBlock_Inner` and then a call like `IsAreaLoadedOnClient(num2, num3, 3)`

**Comment by Chicken-Bones** [comment]
I'm assigning myself to eventually fix this, but I'd love for someone else to try it out if they have time before I do.

**Comment by JavidPack** [comment]
good idea, every time I come across needing to know if a client has a section, I remember that only the server knows that, which is frustrating.

**Comment by Chicken-Bones** [comment]
`Main.sectionManager.SectionLoaded` has always existed, but didn't actually work in MP! This is now fixed. 
I've also added `TileLoaded` and `TilesLoaded` for easier querying.
Just make sure you don't try and use `Main.sectionManager` on a server, it will be null!
