### ISSUE TITLE
TModLoader Mod Browser is broken again. Any suggestions?

### ISSUE THREAD

**Issue by DannyPhantoast** [bluemagic123/tModLoader#2364]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Terraria v1.3.5.3
tModLoader v0.11.8.9
No VPN
Solid internet connection
javid.ddns.net link does not work

**Comment by JavidPack** [comment]
The server was off, should be on now.
