### ISSUE TITLE
Ranged Weapon Knockback and Projectile Knockback do not add together

### ISSUE THREAD

**Issue by Sean-Memerson** [bluemagic123/tModLoader#2370]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

It appears that the knockback of an ammo is not properly adding itself to the knockback of the weapon that fires it, and only the weapon knockback is being counted.

this is most notable with a weapon such as the snowball cannon, a weapon that is powerful largely because of its high knockback. The snowballs have significantly more knockback when thrown on their own than they do when fired by the cannon.

also notable is weapons with no knockback (such as early bows) will continue to have no knockback regardless of the knockback on the weapon.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8673566/client.log)

### Steps to reproduce

1. Fire a range weapon with no knockback, using an ammo that has knockback
Result: no knockback will be seen

OR

1. Throw a snowball and view the knockback
2. Fire a snowball with the snowball launcher and view the knockback
Result: The snowball launcher will have significantly lower knockback than the thrown snowball

### Expected Behavior

The knockback of a ranged attack should be 'Weapon Knockback' + "Ammo Knockback"

### Actual Behavior

The knockback of a ranged attack is only Weapon Knockback

### Reproduction frequency

This happens every time with the ranged weapons I have tested it on.

### Additional Information

This applies without any mods installed, and so it is not a problem with any mods. I am not a programmer, so I don't know any technical details beyond what I was able to find with simple testing.

I noticed it with a few weapons before doing testing, but I have only properly tested this with the Gold Bow and the Snowball Cannon. I also know it applies to the minishark, that is the weapon I first noticed it on. I do not know if it is weapon specific or not, as I have only know for sure these 3 weapons.

**Comment by direwolf420** [comment]
Can you please test this on preview? It was fixed recently, a confirmation would be nice, so it can be closed.

**Comment by Sean-Memerson** [comment]
Very sorry direwolf, I didn't realize there was already a report on this, I thought I looked thoroughly enough. 

I just tested it on preview and you are correct, it appears to be working as it should be on the preview version, Thanks for letting me know. 

I am going to close with this comment, I hope that is the correct thing to do - I have never used github before.
