### ISSUE TITLE
Attempting to Configure any mod results in Tmodloader "not responding", making it impossible to config mods.

### ISSUE THREAD

**Issue by PrinceOfLemons** [bluemagic123/tModLoader#2371]
### Version

Latest Official (1.3)

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

attempting to configure any mods on Mac using Tmodloader will result in a crash. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8674207/client.log)

### Steps to reproduce

1. Download any mod that can be configured
2. Click on the gear button

### Expected Behavior

It should allow the player to configure the mods.

### Actual Behavior

It makes the game stop responding, meaning that a force-quit must be initiated. This also means that not a single mod can be configured at all.

### Reproduction frequency

Very consistently. Every single time I try, I can get it to happen.

### Additional Information

I am playing on a Macbook Air with the M1 Chip. It is OS Monterey, Version 12.3.1. Any other mac should have the same issue, but this is the one I use.

**Comment by PrinceOfLemons** [comment]
If the log is incomplete it is due to Mac weirdness.

**Comment by JavidPack** [comment]
I haven't seen this reported before, so I'm not sure if we have anything to go on. Hopefully someone else might mentions something someday.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
