### ISSUE TITLE
GlobalNPC.SetDefaults does not affect npc's with a negative IDs

### ISSUE THREAD

**Issue by BaltaToday** [bluemagic123/tModLoader#2378]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Expected Behavior

Being able to use SetDefaults to alter stats of green slime (or other variants).

### Actual Behavior

SetDefaults seems to be called then overwritten.

### Reproduction frequency

Always; but only applies to npc's with negative ids.

**Comment by Chicken-Bones** [comment]
Please provide some sample code, and a log file preferably.

**Comment by BaltaToday** [comment]
```
public class NPCDefense : GlobalNPC
{
        public override void SetDefaults(NPC npc)
        {
	        npc.defense = 2000;
	        npc.lifeMax = 20000;
        }
}
```

[client.log](https://github.com/tModLoader/tModLoader/files/8711953/client.log)

Log doesn't look like it has any useful info... *shrug*

**Comment by JavidPack** [comment]
Looks like this was addressed in https://github.com/tModLoader/tModLoader/pull/3955
