### ISSUE TITLE
Placing (and clentaminating) natural desert walls does not create underground desert, even without mods (and on windows instead of linux)

### ISSUE THREAD

**Issue by Trisscar05** [bluemagic123/tModLoader#2381]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Trying to create an artificial underground desert, and I can't get anything but cavern mobs (skeletons, bats, black slimes, etc) and surface slimes to spawn.
Tried so far:
-Hardened Sand Walls from the graveyard recipe (later learned this doesn't work, yes thank you)
-Tedit placed "natural" Hardened Sand Walls, failed
-Clentaminator corruption and then purification of said Tedit-placed walls, same result (though the corruption-based Devourer did spawn occasionally, the eaters of souls consistently refused to appear)
-Clentaminator crimson-ization and then purification of the walls, same result (no crimson mobs at all)

Please note that I can make surface desert biomes just fine, as well as every other biome thus far. I have not tested with spider walls as of yet.
Tested first with Linux based world and mods, and then with cloud-swapped Windows and no mods. Same result in both cases.

It should also be noted that the antlion larva-spawning eggs appear just fine, even without walls, on hardened sandstone only. This appears to be intended behavior.

### Expected Behavior

I would expect at least one of these attempts to fulfill the requirements to "create an artificial underground desert", which mostly just means giving a place for the various antlion types to spawn, as well as the Golfer NPC.

### Actual Behavior

The "natural" underground desert walls (at least the hardened sand one) do not appear to function, and in fact appear to be blocking corruption and crimson spawns when either overriding biome is applied.

### Reproduction frequency

Always.

**Comment by JavidPack** [comment]
Sound like you want to place unsafe walls. You can't get unsafe walls in the base game, even the echo recipe walls are safe. Try this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2843249019

**Comment by Trisscar05** [comment]
And I would agree, except as stated, the specifically unsafe TEdit walls also did not function.

**Comment by JavidPack** [comment]
Must be something else. I'm looking at the golfer spawn code and it seems like lots of these require that the spawn location is underground, that might be what is missing on your end. There is also a check here for 50 tiles of sand walls above the spawn position

**Comment by Trisscar05** [comment]
I filled in both the first layer of dirt background, and the second layer of stone-ish background texture, with desert walls from TEdit. I could try the lava-cracks-style area if you want, but I feel like that's not going to help unless this is a really strange one.

**Comment by JavidPack** [comment]
Well, I tried this myself, was able to get things spawning after going deep enough, copy and pasting sections of original desert to the new area, placing unsafe walls, sand, sandstone, and hardened sand block. I'm not sure the exact conditions, you can read the npc spawn code if you really need to. If you still can't figure it out, maybe someone interested in this would be willing to help you in the tmodloader discord chats.
