### ISSUE TITLE
Player list order not what should be expected

### ISSUE THREAD

**Issue by JPANv2** [bluemagic123/tModLoader#2382]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When listing the players during the player selection screen, the players that are favourited should appear on top of the list, followed by whatever players that are not favourited. Also, I think that the players that are already from 1.4-stable should appear before any of the import-players. However, as shown in the example collage below, the players are all scrambled together. The player "Tester the New", favorited, appears below even "?" player, that is not favorited (nor ever was).
Also, it's a bit tedious having to scroll through all possible import players to reach the ones actually being played with in this version, specially during this time where 1.3 and 1.4 are played pretty much in parallel.

### Log File

![PlayerOrderBug](https://user-images.githubusercontent.com/24964085/168414665-6e35c2c7-bec7-4104-a294-599e4752d14a.png)

### Steps to reproduce

1. Open the player list
2. Favourite any character
3. The character moves to a different position, but not necessarily where it should go in relation to others

### Expected Behavior

The players should be ordered by favorite, then alphabetically by version, with priority to the version currently being played.

### Actual Behavior

Players are displayed in a seemingly random, yet reproduceable fashion.

### Reproduction frequency

I only tested with two instances of 1.4-stable, both displayed this same issue.

### Additional Information

I checked the code for sorting the characters, and the compare function is nearly correct (if we don't count the version of terraria the player comes from), but I can't seem to find anywhere a Sort is called on the _playerList variable that keeps the player data. The only sort I found was applied only to the player files in UICharacterSelect.UpdatePlayersList (line 137), ordering them by filename and favorites, but aftereards the _playerList is no longer sorted. 

By checking the code of this update function, it seems like the list should be ordered in the correct manner just by virtue of how it was made, so the altering code could be elsewhere.

Also, after attempting to migrate a 1.3 character, the character was completely remade and is not even the same gender as it was in 1.3, let alone the sprite looking the same. Also appears to have items it didn't have on 1.3 (the character in 1.3 was equipped with shroomite and now has no armor, but has a shield of cthulhu that did not have in 1.3)

**Comment by xKirtle** [comment]
UICharacterListItem elements update the order of their UIList parent (_playerList) on favoriting, renaming, deleting, etc.. with the UpdateOrder() method, however, Main.PlayerList does not reflect those changes, yeah.

The method UICharacterSelect.AddIndividualPlayerMigrationButtons() only seems to be called after UICharacterListItem's have been sorted and added to the _playerList in UICharacterSelect.UpdatePlayerList() so the characters migrating from 1.3 (from my understanding) will not be affected by the sort since they don't have their PlayerFileData in the Main.PlayerList list at that point (which is used to sort the elements, as seen below)
```cs
private void UpdatePlayersList() {
    _playerList.Clear();
    List<PlayerFileData> list = new List<PlayerFileData>(Main.PlayerList);
    list.Sort(delegate (PlayerFileData x, PlayerFileData y) {
        if (x.IsFavorite && !y.IsFavorite)
            return -1;

        if (!x.IsFavorite && y.IsFavorite)
            return 1;

        return (x.Name.CompareTo(y.Name) != 0) ? x.Name.CompareTo(y.Name) : x.GetFileName().CompareTo(y.GetFileName());
    });

    int num = 0;
    foreach (PlayerFileData item in list) {
        _playerList.Add(new UICharacterListItem(item, num++));
    }

    AddIndividualPlayerMigrationButtons();
    
    ...
}
```

With that said, I don't really understand how could the UIPanels to copy players from 1.3/Terraria appear before UICharacterListItem elements since, on update, they're always added after?
