### ISSUE TITLE
TML's current version (2022) makes it incompatible with almost all other mods not on the steam workshop (run on version 0.x)

### ISSUE THREAD

**Issue by ChedRed** [bluemagic123/tModLoader#2384]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Monthly TML stable updates are posted with a version of 2022.xx.x.x instead of 0.xx.x.x, making mods from the mod browser (such as Calamity, Thorium, etc.) not load.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8693175/client.log)

### Steps to reproduce

1. Download a mod from the Mod Browser Website (https://mirror.sgkoi.dev/)
2. place the .tmod file into /tmodloader/mods
3. run tModLoader
4. enable the mod you downloaded and press 'reload mods'

### Expected Behavior

Mod loads normally

### Actual Behavior

An error message appears stating that the mod can not be loaded on this version (2022.xx.x.x) because the mod version is on 0.xx.x.x

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
The website you mentioned is a mirror of the 1.3 mod browser, it has no relation to the 1.4 mod browser, which you can browse on the steam workshop page.

The error is intended, 1.3 mods aren't compatible with 1.4. Don't attempt this, just download mods in-game. The mods you mentioned aren't on 1.4 yet as well, the authors still have a lot of work to do on the porting process.
