### ISSUE TITLE
Allow Loading Common Mod Data on Player/World before anything else

### ISSUE THREAD

**Issue by JPANv2** [bluemagic123/tModLoader#2385]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Right now, ModData for players and worlds is both the last thing to be saved and the last thing to be loaded. However, there are cases where said ModData loading first would allow for some gains over the current solution, such as allowing the creation of replaceable entries for heavy mod structures included in items that must be saved in either Player or World.

### What does this proposal attempt to solve or improve?

With ModData loading happening at the bottom of the load order, data that is collected during the mod's saving process of other player/world data cannot be directly used during the load of that player/world data without some post-load workaround.

For example, when all ModItems of a modded type use the same instanced data with small variations, a modder may want to save the common data someplace else and then, when the item is loaded, restore that data into the item. Without allowing the modder to load the ModData before the item's, there is no simple way to just restore that data, and he must forcefully save it with the item to be able to use it Restoring it after the item was loaded, by running it in the next code after the player load and before an item field is called, can be complicated, as if the field determines the look of an armor, only Player.ResetEffects() is run before equip slot and equip display is used.

In my particular case, I'm working on a mod where some structures that are being saved multiple times in every item instance of that ModItem. Those structures are, mostly, unchanged from item to item, and even copied inside the item, but may be altered during gameplay. To reduce save size and load times, I tried to implement a "cache" system that places those structures either in the ModPlayer cache (for inventory and bank items) or the ModWorld cache (for items placed in chests and laying around in the world). Saving that cache presents no problem, as all the items already replace their struct's value by a cache location during save. Loading it, however, is impossible without some major changes to the mod's code, as the cache is only loaded after all the items are loaded. This problem would not exist if the ModData saved at the end of the saving process was loaded at the begining of the loading process.

### Which (other) solutions should be considered?

This is definitely up for discussion. While the current behaviour works great for most cases, cases where modders may want to create said "caches" of data to minimize save space and object references could be useful to others. But if the current modder was counting on the ModData to be loaded last, it could break irreparably their own mod.

While the simplest solution would be to simply reverse load order from what it is right now, it could also be implemented as a new Save/Load hook pair that Saves/Loads before anything else in that mod. This would not break what the current modders expect of tMod's saving/loading, but would be a bit more difficult to implement, as it would require new Hooks in the Player and ModSystems, and would add some confusion in what Save/Load function to use (we could suggest using only this new one if you absolutely have to load first).

Edit: After looking through the code again, it seems a simple new "EarlyLoad" hook would suffice, as an early Save does not offer as much advantages as an early Load.

**Comment by Chicken-Bones** [comment]
After discussion in Discord, an alternate implementation was found for the driving use case of this proposal. It's difficult to figure out how to implement this for other content, or what the other use cases would be, so this is tabled until someone finds a motivating use case.
