### ISSUE TITLE
Credits do not roll when opened

### ISSUE THREAD

**Issue by xKirtle** [bluemagic123/tModLoader#2388]
### Version

Latest 1.4-stable

### OS

Tested on Windows/Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Credits do not roll when opened

### Steps to reproduce

1. Launch tModLoader
2. Click on the Credits menu button

### Expected Behavior

Credits should start rolling

### Actual Behavior

Blank screen with a Back button
![image](https://user-images.githubusercontent.com/30240961/168839464-cbfbae33-3363-41bd-b353-c9d52db36f5b.png)

### Reproduction frequency

100%

### Additional Information

This bug is present in both stable and preview versions as of 17th May

**Comment by Rijam** [comment]
It wasn't working for me either on Preview (Steam, Windows), but then I defeated Moon Lord in a new world with no mods enabled and the credits work now.

**Comment by direwolf420** [comment]
It draws but doesn't update, hence nothing happens:
`SkyManager.Update`:
![Screenshot_1](https://user-images.githubusercontent.com/15894498/169004665-9421fea9-bb9e-4705-be11-5402c1f8b0bb.png)

`Main.desiredWorldEventsUpdateRate` is 0 so the loop never enters and `CustomSky.Update` is not called. 
Entering a world calculates the variable again, and doesn't reset if when leaving, hence why Rijams steps work

**Comment by direwolf420** [comment]
This explanation above is also directly related to #2247
