### ISSUE TITLE
Make normal engine for tmodloader 1.4

### ISSUE THREAD

**Issue by Siniy-Kot** [bluemagic123/tModLoader#2391]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

make a normal engine for tmodloader, terraria 1.4 works fine, tmodloader 1.3.5.3 with large-scale mods like calamity is also calm at 60 fps, and with 1.4 tmodloader it works for me at 40 fps, and if you also turn on discord, it will be 20-30

**Comment by hammad11ali** [comment]
I am a little confused about the question. Please elaborate a bit.

Here's my initial guess
With large mods on the 1.4 version game would utilize more system resources than the 1.3 version hence the fps might drop in some cases.
Can you share your device specs and system resource utilization at the time when fps drop?

**Comment by Siniy-Kot** [comment]
as I said, the original 1.4 and tmodloader 1.3 work at 60 fps, and with 1.4 tmodloader EVEN WITHOUT MODs it works at 20-50 fps, even if you set 600 to 800, my fps does not rise above 50, although the usual terraria works even in 2k graphics at maximum settings.
What about system devices, amd ryzen 5 3500U with radeon vega mobile gfx, 8gb ram (only available 5.95) gtx 1050,
![image](https://user-images.githubusercontent.com/68147582/169344815-40c0f57a-8b36-463a-bf58-b4e17e7b9056.png)

**Comment by JavidPack** [comment]
We are tracking more concrete performance issues in other issues, I will close this in favor of them.
