### ISSUE TITLE
Impliment base PlayableCharacter class for Player and Npc

### ISSUE THREAD

**Issue by Shadowblitz16** [bluemagic123/tModLoader#2396]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

I think there should be a base PlayableCharacter class for player and npc.
This would mean exposing or implementing a missing functionalities for example player knockback.

### What does this proposal attempt to solve or improve?

Allows easier implementation of generic pvp and pve functionalities. 

### Which (other) solutions should be considered?

idk.

**Comment by JavidPack** [comment]
This seems like far too big of a change to maintain, I don't think we'll be doing this.
