### ISSUE TITLE
Requesting ModSystem.OnModUnload

### ISSUE THREAD

**Issue by CXUtk** [bluemagic123/tModLoader#2399]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

The `ModSystem.OnModLoad()` method ensures that its contents are not called until after `Mod.Load()`. However, there is no corresponding `ModSystem.OnModUnload()` method that is guaranteed to be called before `Mod.Unload()`. 

### What does this proposal attempt to solve or improve?

For some specific `ModSystem` instances, I would like them to be scoped within the mod's scope so that I can manage these resources in my own way. I don't know why this method is not provided, but from a symmetry point of view, it would be better to have an unload method corresponding to load.

### Which (other) solutions should be considered?

Maybe some other kind of ModSystem class that only lives in Mod's scope?

**Comment by direwolf420** [comment]
You have access to `ILoadable.Unload`, which is available to `ModSystem` too. Try whatever you are doing with `ModSystem.Unload` and report back.

I assume you want `ModSystem.OnModUnload` here?
![Screenshot_16](https://user-images.githubusercontent.com/15894498/169577646-904d7995-09fa-4075-bec2-3c09279d21df.png)

**Comment by CXUtk** [comment]
@direwolf420 ILoadable.Unload will be executed **after** the mod was unloaded. And I'd like the `OnModUnload` to be placed **before** mod unload.
