### ISSUE TITLE
Linux version 0.8 does not load

### ISSUE THREAD

**Issue by Kf4btg** [bluemagic123/tModLoader#24]
I saw a couple of people on the forum thread mention this issue, but, there being so few of us (modded-Terraria-Linux-players), any discussion of Linux issues on there is probably going to be lost in the sea of other comments.  I also figured GitHub is probably a better place to discuss technical issues, anyway, so here we go!

I'm on Arch Linux x86_64 (with an Nvidia card, if that matters). As the other posters said, trying to launch tModLoader now results in the game crashing immediately after the Re-Logic loading screen.  I think that's when the mod-loading status messages would be shown?  Since I wanted to make sure that none of the old mods caused issues, I emptied out the Mods, Players, and Worlds folder before ever trying to start v0.8, so I think we can rule those out as possible causes.

Here's the terminal output from steam when trying to launch Terraria (I also get the same result and output when attempting to launch the game directly from the command line):

```
Setting breakpad minidump AppID = 105600
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198025017831 [API loaded no]
OpenGL Device: GeForce GTX 970/PCIe/SSE2
OpenGL Driver: 4.5.0 NVIDIA 361.28
OpenGL Vendor: NVIDIA Corporation
MojoShader Profile: glsl120
Using EXT_swap_control_tear VSync!
Using EXT_swap_control_tear VSync!
Resolution changed to: 1920x1018.
Using EXT_swap_control_tear VSync!
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MethodBase.GetMethodBodyInternal (intptr) <0xffffffff>
  at System.Reflection.MethodBase.GetMethodBody (intptr) <0x00013>
  at System.Reflection.MonoMethod.GetMethodBody () <0x00017>
  at Terraria.Program.ForceJITOnAssembly (System.Reflection.Assembly) <0x000b9>
  at Terraria.Program.ForceLoadAssembly (System.Reflection.Assembly,bool) <0x00013>
  at Terraria.Program/<>c.<LaunchGame>b__7_0 () <0x00017>
  at (wrapper delegate-invoke) <Module>.invoke_void__this__ () <0xffffffff>
  at Terraria.Main.DrawMenu (Microsoft.Xna.Framework.GameTime) <0x007fe>
  at Terraria.Main.do_Draw (Microsoft.Xna.Framework.GameTime) <0x0b0bf>
  at Terraria.Main.Draw (Microsoft.Xna.Framework.GameTime) <0x0001b>
  at Microsoft.Xna.Framework.Game.Tick () <0x007bb>
  at Microsoft.Xna.Framework.SDL2_GamePlatform.RunLoop () <0x00763>
  at Microsoft.Xna.Framework.Game.Run () <0x000cd>
  at Terraria.Program.LaunchGame (string[]) <0x0023f>
  at Terraria.LinuxLaunch.Main (string[]) <0x00033>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(+0xcb624) [0xf7422624]
        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(+0x11e758) [0xf7475758]
        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(+0x29dae) [0xf7380dae]
        linux-gate.so.1(__kernel_rt_sigreturn+0) [0xf771dbd0]
        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(mono_method_body_get_object+0x1f2) [0xf7545cf2]
        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(+0x1553d4) [0xf74ac3d4]
        [0xcae0f25c]
        [0xcae0f20c]
        [0xcae0f1d0]
        [0xe73dbf5a]
        [0xe73dbe64]
        [0xe73dbc60]
        [0xcc11f683]
        [0xe74197ff]
        [0xcae1d0c0]
        [0xcc10a55c]
        [0xdba32a9c]
        [0xdba31e1c]
        [0xe9e63336]
        [0xf7321fb0]
        [0xf731edf4]
        [0xf731eeb6]
        /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0(+0x29753) [0xf7380753]

Debug info from gdb:

ptrace: Operation not permitted.
No threads.

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

./Terraria: line 38: 22023 Aborted                 (core dumped) ./${BASENAME}.bin.${ext} $@
```

Everything up until the "Stacktrace:" line is just regular Steam/Terraria output.  Unfortunately(?), none of the methods named in the stacktrace directly involve the modloader, which could make this harder to pin down. 

I did run the coredump through gdb, but the output was less than helpful:

```
(gdb) bt
#0  0xf77b4be9 in __kernel_vsyscall ()
#1  0xf722dc49 in raise () from /usr/lib32/libc.so.6
#2  0xf722f1a7 in abort () from /usr/lib32/libc.so.6
#3  0xf7482756 in ?? () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#4  0xf74d5758 in ?? () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#5  0xf73e0dae in ?? () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#6  <signal handler called>
#7  0xf75a5cf2 in mono_method_body_get_object () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#8  0xf750c3d4 in ?? () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#9  0xe61f8f34 in ?? ()
#10 0xe61f8ee4 in ?? ()
#11 0xe61f8ec8 in ?? ()
#12 0xe61edf5a in ?? ()
#13 0xe61ede64 in ?? ()
#14 0xe61edc60 in ?? ()
#15 0xcc324683 in ?? ()
#16 0xe61c77ff in ?? ()
#17 0xc960b0c0 in ?? ()
#18 0xcc30f55c in ?? ()
#19 0xde627284 in ?? ()
#20 0xde62665c in ?? ()
#21 0xe90912ce in ?? ()
#22 0xf41c5ed8 in ?? ()
#23 0xf41b8df4 in ?? ()
#24 0xf41b8eb6 in ?? ()
#25 0xf73e0753 in ?? () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#26 0xf759441b in mono_runtime_invoke () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#27 0xf7598b81 in mono_runtime_exec_main () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#28 0xf759abc0 in mono_runtime_run_main () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#29 0xf7452f02 in mono_jit_exec () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#30 0xf74547cd in mono_main () from /home/wuli/.local/share/Steam/steamapps/common/Terraria/lib/libmonosgen-2.0.so.0
#31 0x08049008 in main ()
```

Same memory addresses, of course, from the unhelpful ??().  If you happen to have (or can create) a debug-enabled version of the linux launcher, I'd be happy to test it and see if we can't get some more useful symbols in the stacktrace. I was going to build one myself, but despite some frustratingly intense efforts, I simply could not get tModLoader to compile on my machine--and I realize you say up front that Windows is needed for that, but I don't have a Window box easily available and, hey, I had to try!  It's mainly that the 'setup' program won't run, I think. Neither through native mono nor WINE. I can decompile Terraria just fine on my own--the result of which I've been using for mod development--but I end up with a very different format than your setup program produces, apparently, and the patches won't apply.  Although, full disclosure, I'm not a .Net developer in the slightest, and making a mod for Terraria was my first time using C#, so it's entirely possible that I'm missing something.

But this is a bit of a tangent, sorry. Back on the main topic, I'm going to see if I can manage to squeeze something more helpful from the program. If you need more information from me or help with testing something, just let me know.

**Comment by JavidPack** [comment]
K, I tested 40 commits back (71dd9d1d42d452804e055905addc3bdc9b567c18), still didn't work, then I tested 60 commits back (799b3d36d1b31071bc0b5c3ab12335dddaaa2d6b), and it did work. I'll try to figure out what happened between those 20 to cause this.

**Comment by Kf4btg** [comment]
I think the commit you're looking for is 743be6dc97fa480ea0705552c7087728ec0eb8ed. I was just somewhat aimlessly browsing for a clue when the commit message for that one caught my eye. The changes included references to Ionic.Zip.Reduced.dll, and I didn't recall seeing that .dll anywhere on my machine. So I downloaded the raw file from here, dropped it in the Terraria folder, and voila! The Terraria menu loads up like normal, no more crashing!

So this is a happy discovery, though admittedly I have yet to load any mods, much less try compiling one. But hopefully the only need here is adding that missing dll to the tModLoader distribution (for Linux at least, I don't know if this is affecting Macs, too).  If the tModLoader team members agree that this is the fix, I can drop a message on the forums letting other Linux users know to download the library until a new zip is made available.

**Comment by bluemagic123** [comment]
Ooh, woops! Looks like we forgot to include that; I'll put up a new download as soon as possible.

**Comment by Kf4btg** [comment]
The new download seems to work just fine, thanks! I'll go ahead and close this issue, then.
