### ISSUE TITLE
[1.4] Going above 14 active info accessories causes UI to break.

### ISSUE THREAD

**Issue by WhitePhant0m** [bluemagic123/tModLoader#2407]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When you have more than 14 active info accessories your hotbar and some other parts of the UI break.
It also doesn't display the 15th or above info accessories.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8747201/client.log)

### Steps to reproduce

https://i.gyazo.com/a54b326954450ba294e77c27efb7b40a.mp4

1. Have 14 active info accessories
2. Enable a 15th info accessory
3. UI breaks when out of inventory

### Expected Behavior

UI not breaking when having more than 14 info accessories active.
And displaying the rest of the info.

### Actual Behavior

UI breaks when you have more than 14 info accessories active, not displaying the rest of the info.

### Reproduction frequency

4 out of 4 times so far.

**Comment by Solxanich** [comment]
@ThomasThePencil  - courtesy ping

**Comment by JavidPack** [comment]
Reproduction steps
Mods: Luck info, Summoners Association
Have luck accessory and cell phone
Show all info displays

UILinkPointNavigator.SetPosition(1558 + num3 - 1, vector2 + icon.Size() * 0.75f); probably needs to be changed.
