### ISSUE TITLE
Adding IsCloneable broke UnloadedItem data

### ISSUE THREAD

**Issue by Ved-s** [bluemagic123/tModLoader#2409]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

https://github.com/tModLoader/tModLoader/blob/05ba5c9460e81c0cfb734753e1c4a28f94706265/patches/tModLoader/Terraria/ModLoader/Default/UnloadedItem.cs#L32
UnloadedItem loads its data tag as item's `data` and passing it to item's LoadData, resulting in this
![image](https://user-images.githubusercontent.com/53968411/169646268-4dd5451e-8a27-4cf7-96b9-20947312e695.png)
![image](https://user-images.githubusercontent.com/53968411/169646281-635d1884-9feb-4312-a325-911fe7c4443a.png)

### Steps to reproduce

Try to load a ModItem after it's been unloaded and saved

### Expected Behavior

UnloadedItem should call LoadData with the right tag

### Actual Behavior

UnloadedItem calling LoadData with its own `UnloadedItem` data tag

**Comment by Solxanich** [comment]
Can I get more information?
On the current 1.4 branch, I am unable to reproduce
