### ISSUE TITLE
how do i fix hash mismatch, data blob has been modified or corrupted

### ISSUE THREAD

**Issue by waterex1** [bluemagic123/tModLoader#2412]
### Version

Latest Official (1.3)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i load my mods with fargo souls and mutant it show  

### Log File

![image](https://user-images.githubusercontent.com/105990629/169666019-dfecf7fd-4cdc-45e1-9693-1003d88393c7.png)

**Comment by JavidPack** [comment]
This is a mod error, you should come to the discord for support with mod errors. We do not do mod support here. Here is what you would be told if you came to discord with this error:

> If you're getting the following error when trying to use Fargo's Mutant Mod, disable Calamity Mod (No Calamity Music) and Fargo's Mutant Mod, reload mods, enable Fargo's Mutant Mod,. reload mods again, then disable the banner recipes option in the Fargo's Mutant Mod configs.

**Comment by waterex1** [comment]
what is the discord

**Comment by JavidPack** [comment]
https://tmodloader.net/discord
