### ISSUE TITLE
Whip damage is duplicated

### ISSUE THREAD

**Issue by SolarAweTM** [bluemagic123/tModLoader#2415]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whips, after swinging 1-3 times, start dealing damage twice.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8750374/client.log)

### Steps to reproduce

1. Obtain any whip
2. Swing at enemies
3. Notice double damage numbers and DPS

### Expected Behavior

Whips should only be dealing damage once i.e. only one number over the enemy per hit.

### Actual Behavior

Whips deal damage twice to enemies (two numbers over the enemy on hit), and is reflected on the DPS Meter as such.

### Reproduction frequency

100% of the time, with every whip in the game.

### Additional Information

![dotnet_lbfmNnw35g](https://user-images.githubusercontent.com/97848738/169718402-c8a5ca03-144a-46f7-815b-1f4ad916fdea.gif)

**Comment by SolarAweTM** [comment]
After looking closer at the whip itself, it looks like after 1-3 swings, the player is actually swinging two whips. Note that this only happens if some form of melee autoswing is enabled, in this case, Feral Claws.
![image](https://user-images.githubusercontent.com/97848738/169718622-1309177a-28ef-4494-a368-8da2618314f2.png)

**Comment by Solxanich** [comment]
Yes, this is a known bug.
The fix for it is included in the next monthly release for June, so we had closed the old issue. #1654 
Thanks for reporting and looking a bit into it though, apologies for the confusion
