### ISSUE TITLE
[1.4] Mod Update Indicator in wrong place

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#2419]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The small icon appended to mod names does not move if the mod's name moves. For example, it does not move if the mod has the "didn't unload properly" error, making it overlap with text.

### Log File

![Screenshot_676_dotnet](https://user-images.githubusercontent.com/33076411/169842024-151d901e-2bda-4913-9c1b-255052d2241c.png)

### Steps to reproduce

1. Download any mod that doesn't unload fully -- for example, one with a config (#2137).
2. Close _tModLoader_, then let the mod receive an update on the Steam Workshop.
3. Reopen _tModLoader_, enable the mod, and reload mods.

### Expected Behavior

The little blue circle should move with the mod name.

### Actual Behavior

The circle remains static, overlapping with the mod name.

### Reproduction frequency

100%.

### Additional Information

I only tested this with the mod update indicator and the "didn't fully unload" warning, but I'd imagine this bug is present for all indicators.

Edit: See #2420.

**Comment by direwolf420** [comment]
It's also displaced on mods that use chat tags in them.

![Screenshot_2](https://user-images.githubusercontent.com/15894498/169864875-7b196cee-680d-4a03-be7f-81c2253babff.png)

**Comment by JavidPack** [comment]
Right, I forgot about the didn't unload indicator or chat tags
