### ISSUE TITLE
Tome of Infinite Wisdom un-aimable

### ISSUE THREAD

**Issue by Kiwsage** [bluemagic123/tModLoader#2425]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Weapon "Tome of Infinite Wisdom" does not function properly. (persistent after disabling all mods, issue reproduced by discord user Kirtle)
Edit: Clarification, it is un-aimable

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8764412/client.log)

### Steps to reproduce

1. Equip the weapon
2. Try to aim it
3. Fire the weapon

### Expected Behavior

The weapon's projectiles should be fired towards the direction of the cursor.

### Actual Behavior

The weapon's projectiles fire towards a fixed position on the screen, facing either left or right, it is essentially un-aimable. This is regarding the left-click ability.

### Reproduction frequency

100% consistent

### Additional Information

tModloader discord user Kirtle was kind enough to confirm this issue on their end and found that using the mod "Head rotates to cursor" causes this issue to not exist.
This I was able to confirm on my end aswell.

Hopefully this provides some insight as to what might be causing this issue.

**Comment by Setnour6** [comment]
I can confirm this problem affects me too.
The aim is pretty much that of a shortsword except you can't aim it anywhere else. Using the tornado attack makes the tome move in a different direction, but then it gets stuck in the direction that the tornado attacked fired towards. When your character faces in a direction opposite to where it faced when the tornado fires, the tome's left click attack fires in the direct opposite of the direction your character once faced.
To simplify this, if you shoot downwards diagonally to the right with the tornado attack, having the character face the opposite direction and firing causes the tome to fire upwards diagonally to the left.

**Comment by Kiwsage** [comment]
Yes that is indeed a lot more of a detailed description of what happens and yes it is exactly that behavior.

Thanks for the clarification.

**Comment by Setnour6** [comment]
> Yes that is indeed a lot more of a detailed description of what happens and yes it is exactly that behavior.
> 
> Thanks for the clarification.

You're welcome!

**Comment by Setnour6** [comment]
I just tested it now, and the problem is no more.

**Comment by Chicken-Bones** [comment]
Assuming fixed. Feel free to reopen.
