### ISSUE TITLE
tModLoader won't start

### ISSUE THREAD

**Issue by TheAnimePope** [bluemagic123/tModLoader#2434]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I start tModLoader on steam it'll say running for a split second and then immediately cancel without actually starting. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8777734/client.log)

### Steps to reproduce

Press play

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
Looks like the game thinks you are on windows for some reason. Check that you don't have Proton enabled, then delete the dotnet folder in the install directory.

**Comment by TheAnimePope** [comment]
I don't have Proton enabled and I even reinstalled terraria and tModLoader just to make sure and I deleted the dotnet folder but it still doesn't start and the log file hasn't changed

**Comment by TheAnimePope** [comment]
Actually I just realized that a log file is only generated if I execute the start-tModLoader.sh file manually. When I start it through steam the only difference is that an empty dotnet folder is generated.

**Comment by JavidPack** [comment]
Hm, well, if you still haven't figured this out, come to discord, we try not to do support questions on github, tmodloader.net/discord

**Comment by TheAnimePope** [comment]
OK I'll check out the discord
