### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Bhased** [bluemagic123/tModLoader#2438]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I load up TML and I get a popup: no audio device found. Disabling all audio

### Steps to reproduce

I do not really know, ive seen people talk about this said issue but they are all from 2 years ago

### Expected Behavior

Sound plays and I don't get this popup

### Actual Behavior

I get a popup saying no audio device found. Disabling all audio

### Reproduction frequency

Always.

**Comment by Chicken-Bones** [comment]
Please try the workaround in #2687
