### ISSUE TITLE
Add Mod Tag Descriptions

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2439]
### Do you intend to personally contribute/program this feature?

Maybe
(Note: I can add the descriptions, but I don't know how to make it that way in the code. Someone can add the mod tags internal name in the localization files with the same placeholder descriptions, and I can change the placeholder descriptions into actual descriptions.)

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

There should be actual descriptions of mod tags when selecting mod tags.
Example: "New Content" Tag. Description: "This mod adds new items and/or features to the game".

### What does this proposal attempt to solve or improve?

By removing placeholder descriptions and replacing them with real descriptions, these real descriptions tell you what the mod tags mean, so you can have a better understanding of what mod tags to use.

**Currently:**
![image](https://user-images.githubusercontent.com/70764728/170608893-d124700e-0d9c-4bf3-8422-ca3b6b474092.png)

**Comment by Solxanich** [comment]
So, I'll make this easy, I did setup the localization file when doing the plsceholders:
https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json

So as desired, you can just PR the descriptions without doing any real coding

**Comment by Setnour6** [comment]
> So, I'll make this easy, I did setup the localization file when doing the plsceholders: https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
> 
> So as desired, you can just PR the descriptions without doing any real coding

Perfect! I'm thinking that either when I put the new descriptions, I can have it apply to all other language choices and others can translate it, or put the new descriptions but also have the placeholder descriptions active in the other languages.
I'll most likely do the first choice.
