### ISSUE TITLE
Error when starting tModLoader

### ISSUE THREAD

**Issue by ARMIGOgog** [bluemagic123/tModLoader#2443]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

when starting tModLoader gives an error I don’t know how to fix it help
![image](https://user-images.githubusercontent.com/106396139/170735069-65191787-5b24-4518-a058-553e6efb150a.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8787887/client.log)

### Steps to reproduce

1.click on tModLoader
2.and an error pops up

### Expected Behavior

tModLoader will start

### Actual Behavior

an error

### Reproduction frequency

constantly

### Additional Information

no

**Comment by JavidPack** [comment]
I'm confused, it looks like you tried to launch 0.11.8.9, which is tModLoader 1.3, but you selected "Latest 1.4-stable" in the version selector.

If you are trying to launch 1.3, then it looks like you didn't install tmodloader next to terraria. It can't find Terraria.exe in C:\terka\Terraria.

If you are trying to launch 1.4, you need to download and install the latest stable release next to your existing terraria install.

Here are the manual install instructions: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Comment by dimaspaf14** [comment]
I also had same problem...
I have fresh install v1.4.3.6 gog version, then i install tmodloader, a few minutes of running & downloading tml things, i got this error, i installed at terrariafolder/tmodloader.
Whats wrong with it?

**Comment by dimaspaf14** [comment]
Also there's something I don't understand itn the TML wiki:
[1.4 ONLY] GoG users will need to install Steam if they haven't already. Our Mod Browser uses some of the steam install files to facilitate accessing the Steam Workshop. You should NOT need an account/be logged in for this to work.

What does it mean? I already have steam. what i have to do with my steam?

**Comment by dimaspaf14** [comment]
Use legal installation & work, this should be closed
