### ISSUE TITLE
Tmod Affects youtube in the background

### ISSUE THREAD

**Issue by Allaark** [bluemagic123/tModLoader#2448]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When watching YouTube on a second monitor while playing TMod, the "Why This Ad?" button in YouTube becomes unclickable.

### Log File

There is no "Logs" folder in the tModLoader folder

### Steps to reproduce

1. Launch tModLoader [1.4-stable] on steam
2. Open YouTube in your browser of choice
3. Click through YouTube videos until an ad plays
4. The "Why This Ad?" button in the bottom left corner is un-clickable

### Expected Behavior

What should be happening is that the Why This Ad? button should be working just fine while playing tMod

### Actual Behavior

When an ad plays while tMod is open (doesnt matter what tMod is currently doing as long as it is open) the Why This Ad button becomes unclickable.

### Reproduction frequency

This issue occurs on every startup of tModLoader.

**Comment by JavidPack** [comment]
I was not able to replicate, if this issue continues and adversely affects you, feel free to reopen.
