### ISSUE TITLE
[1.4] Worlds being unmarked as Constant worlds

### ISSUE THREAD

**Issue by NellielDP** [bluemagic123/tModLoader#2451]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Worlds generated using one of the Constant secret seeds, whether in tModLoader or transferred from Terraria, are immediately unmarked as being Constant worlds. World generation itself is not effected, but the in-game effects associated with a Constant world are deactivated.

**Comment by direwolf420** [comment]
Your post doesn't include a log, a mod list, or mention of the enabled mods. Please verify that this happens on a game instance that has no mods loaded.

**Comment by NellielDP** [comment]
I disabled all mods and it worked. Then I went through to test each of the mods I was using. Turns out the problem was with Fargo's Mutant Mod.

**Comment by direwolf420** [comment]
that mod sets all worldgen flags to false, so go into its config to enable the ones you want
