### ISSUE TITLE
Using -join skips mod loading

### ISSUE THREAD

**Issue by Ved-s** [bluemagic123/tModLoader#2456]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Using -j/-join command line argument skips mod (or even ModLoader) loading
![image](https://user-images.githubusercontent.com/53968411/170917788-1360e05d-9e94-4728-a1ca-6e93e57694cc.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8795456/client.log)

### Steps to reproduce

Add -j or -join arg with valid hostname

**Comment by JavidPack** [comment]
Seems to have been fixed in https://github.com/tModLoader/tModLoader/pull/2971
