### ISSUE TITLE
Running tModLoader also runs Terraria

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2462]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

This new stable update...
![image](https://user-images.githubusercontent.com/70764728/171310632-ef5e1622-04bb-4de2-8c87-eceeb5cd5e0b.png)
At least Terraria also gets some counted play time, but it's ambiguous. I didn't download any of Solxan's mods.

### Steps to reproduce

1. Open tModLoader
2. Look at Terraria in the steam library
3. Terraria is also running

### Expected Behavior

Terraria should not be running, as it is a separate game.

### Actual Behavior

Terraria is counted as part of tModLoader. Before the new stable update, it wasn't counted.

### Reproduction frequency

100% of the time (further testing is needed)

### Additional Information

Maybe it could be a mod problem, but I don't have any mods that have caused this issue. Nothing like that happened at the time. No new mods were downloaded.

**Comment by Setnour6** [comment]
There's also this other issue:
Why must I be told to run tModPorter when I built a mod on 1.4?
![image](https://user-images.githubusercontent.com/70764728/171312287-ffb852ae-be86-43fd-a7cf-401aa4e9e89f.png)

**Comment by Solxanich** [comment]
Terraria counting for playtime  - intentional, was requested by ReLogic, RIP my mod, now belongs to tML.

tModPorter prompt: we didn't have an icon on hand for the button. You do not have to action it. 
Exclamation mark was a bad choice.

**Comment by Setnour6** [comment]
> Terraria counting for playtime - intentional, was requested by ReLogic, RIP my mod, now belongs to tML.

I didn't think ReLogic would want that but okay lol.

> tModPorter prompt: we didn't have an icon on hand for the button. You do not have to action it. Exclamation mark was a bad choice.

What's a good idea for the icon? Here's mine (as a concept):
![image](https://user-images.githubusercontent.com/70764728/171323700-0a651644-bb25-4e4c-87b4-12b6dd5e8349.png)

**Comment by Chicken-Bones** [comment]
> There's also this other issue: Why must I be told to run tModPorter when I built a mod on 1.4? ![image](https://user-images.githubusercontent.com/70764728/171312287-ffb852ae-be86-43fd-a7cf-401aa4e9e89f.png)

You can always run tModPorter! From time to time there may be new changes to the tML API which tModPorter can help you keep up to date with more easily.

**Comment by Setnour6** [comment]
> > There's also this other issue: Why must I be told to run tModPorter when I built a mod on 1.4? ![image](https://user-images.githubusercontent.com/70764728/171312287-ffb852ae-be86-43fd-a7cf-401aa4e9e89f.png)
> 
> You can always run tModPorter! From time to time there may be new changes to the tML API which tModPorter can help you keep up to date with more easily.

I suppose I could. I'll run tModPorter since I get this issue relating to no longer used methods and is JIT related, and tModPorter might fix it (I haven't tried it yet but I will after finishing making this comment)
