### ISSUE TITLE
Game freezes and crashes upon entering the mod browser

### ISSUE THREAD

**Issue by UomoNormale4** [bluemagic123/tModLoader#2464]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

As soon as the mod browser finishes buffering, and mods/GUI and such visually appear. The game freezes, and crashes (without giving an error/crash pop-up).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8810907/client.log)

### Steps to reproduce

Launch Game.
Click Workshop.
Click Download mods.

### Expected Behavior

Functional access to mod browser

### Actual Behavior

opening mod browser causes instant crash (once it finishes buffering)

### Reproduction frequency

100% so far, after many attempts, otherwise i would just keep trying until it works, but it doesn't.

### Additional Information

I first had this problem monthes ago, and it has persisted this entire time. The game runs fine, mod management (enabling/disabling them, reloading, configuring), it all works fine. As does playing, as long as i never go to the mod browser itself ("Download Mods")
I have: Removed all mods, all config settings, everything. Completely uninstalled both terraria and tmodloader, rebooted and tried reinsalling them. And even tried clicking into the mod browser, and clicking away asap to see if it would still crash (it did).

**Comment by xKirtle** [comment]
Make sure you don't have any antivirus blocking tModLoader from accessing the steam servers

**Comment by UomoNormale4** [comment]
hmm, good point
although if that's the case than it's only effecting tmodloader, and specifically 1.4 (as 1.3 mod browser works fine) which would be weird. i'll check it out thanks 8)

EDIT: i turned off my firewall, and it just works now! tysm, really
