### ISSUE TITLE
[1.4] ExampleFlail and ExamplePaperAirplane are missing in the stable branch

### ISSUE THREAD

**Issue by ilija04** [bluemagic123/tModLoader#2465]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

Why aren't these on stable?! These are the only ones that aren't included in the stable branch.

**Comment by Chicken-Bones** [comment]
Because they were added after stable was finished for the month. In general we won't be merging example mod things across, people can just get them from preview, or they'll come across next month.
