### ISSUE TITLE
You can't switch to another weapon while using whips with auto swing

### ISSUE THREAD

**Issue by Cyrillya** [bluemagic123/tModLoader#2478]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

It should be able to switch your weapon by holding left while using the whip with auto swing accessories, which is doable in vanilla.
I don't want this feature to disappear though if you consider it as a bug and fix it. Since this has become a special way to use the whip to defeat bosses
For example:
You can attack the enemies using Durendal once, which grants you the Durendal's Blessing buff that increases your melee speed for 3s. Then you can switch to Dark Harvest to gain the  Harvest Time buff that also increases your melee speed. Before these buffs run out, you can switch to whips such as Kaleidoscope to use whips at a insanely fast speed to deal a lot of damage.
It has also became a tip on wiki: [Dark Harvest](https://terraria.wiki.gg/wiki/Dark_Harvest)
![image](https://user-images.githubusercontent.com/35227653/171649934-de4e7400-7ed3-4dab-b5b1-2fca11702fe1.png)

### Steps to reproduce

1. Prepare two whips in the hotbar, here I suppose that they are in the 1st slot and the 2nd slot
2. Equip an accessory like Feral Claws that enables auto swing for whips
3. Select the first slot, holding left
4. Click "2" in your keyboard. In vanilla, it switches to the 2nd slot when you use the whip once more. But in tModLoader, it just keeps using the whip in the 1st slot and only switches to the 2nd slot when you release the left.

**Comment by Chicken-Bones** [comment]
It's definitely a bug. When using feral claws on an item which doesn't have `autoReuse` without it, vanilla gives you one frame where you're 'not using the weapon' allowing you to swap. 

We could bring this back uniformly for _all_ weapons as an intended mechanic. Otherwise you can probably bring it back with a mod.

**Comment by Chicken-Bones** [comment]
After some discussion, we'd like to allow hotbar swap on _all_ weapons (not just ones that get `autoReuse` with feral claws) but it'll take some time to figure out where to do it, and it's far from the top of priority list.

**Comment by Jofairden** [comment]
Related
https://github.com/tModLoader/tModLoader/issues/1770

**Comment by Cyrillya** [comment]
Simply wrapping these checks in `Player.SmartSelectLookup` to `itemAnimation == 1` will help reimplement the feature (for all items)
![f15b09a74d2b932d436864c936093fc7](https://github.com/tModLoader/tModLoader/assets/35227653/f41b0565-9768-4d7b-878f-b302676b34de)
But I'm not sure if it will break other things
