### ISSUE TITLE
Mod uploading experience is poor

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#2483]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Just so I remember later, it was that the mod uploading experience is extremely slow? Like, I shouldn't need to search the mod browser for competing mod names unless I know it wasn't already published?
I know its a gap right now that ought to be fixed.

also:
- have to always remember to manually select the big icon versions
- have to up the version number even when publishing the same thing for both preview & stable.. Later that will result in version spaghetti if it's not tied to TML's date-based version.
- Steam's descriptions get reset, and I want to keep an image embed on steam while not having ugly unparsed bb code in the mod's metadata description.
-  Info like the last selected tags seems to be stored per TML edition.
- ~~I sure hope the image tab doesn't get affected by new versions?? Yet to test that.~~
Edit: Doesn't.

**Comment by Setnour6** [comment]
> * have to always remember to manually select the big icon versions

I'm thinking that there can be a text display that shows which image/icon you chose or is selected to be displayed (Example: icon_512.png, or icon_large.png), but that's just a feature proposal.

**Comment by JavidPack** [comment]
We should just default to icon_large.png if it exists. it should become the norm for a mod to have an appropriately sized workshop icon.

**Comment by Solxanich** [comment]
> We should just default to icon_large.png if it exists. it should become the norm for a mod to have an appropriately sized workshop icon.

The main reason I think I didn't is the mod browser which pulls the preview image to use in its display. 
IE the 512x512 would also show there, which isn't necessarily a problem. 
With respect to that, all the related code for most of these is probably in APublishMenu.tml or something

**Comment by Setnour6** [comment]
> I'm thinking that there can be a text display that shows which image/icon you chose or is selected to be displayed (Example: icon_512.png, or icon_large.png), but that's just a feature proposal.

I just realized that it's already a thing
![image](https://user-images.githubusercontent.com/70764728/171882943-2d01cc02-908d-4b57-bf68-fce5199b2a35.png)

**Comment by jaydevelopsstuff** [comment]
This should be closed, was fixed in #2561.

**Comment by Solxanich** [comment]
All items on this have been addressed with Workshop_Description and Workshop_Icon being introduced.
