### ISSUE TITLE
The credits won't show at all

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2486]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When clicking the credits button in the menu, no text appears. Not even the little animations.
![image](https://user-images.githubusercontent.com/70764728/171777362-6dc0d554-65a4-4d9f-9e27-964d6f5d11e4.png)

### Steps to reproduce

1. Open tModLoader
2. Click the credits button
3. No actual credits appear

### Expected Behavior

Credits, as in texts and animations, appear and scroll like normal.

### Actual Behavior

No text nor animations appear. Basically nothing really happens.

### Reproduction frequency

100% of the time (verify?)

**Comment by direwolf420** [comment]
Test if it happens on preview.
if it doesn't, this means this commit hasnt been merged to stable https://github.com/tModLoader/tModLoader/commit/99ed1250e0651ebc8dba6a3721123b503e728ae9

**Comment by ilija04** [comment]
@direwolf420 I can agree, the commit isn't present on stable but it is on preview. Why are some commits skipped in stable?

**Comment by direwolf420** [comment]
Either deemed not important enough to merge to preview during freeze, or forgotten. It will be in stable next month guaranteed

**Comment by Setnour6** [comment]
I just tested it on preview and it works there.
