### ISSUE TITLE
Eye of Cthulhu incorrect sound played when dashing

### ISSUE THREAD

**Issue by Nobisyu12** [bluemagic123/tModLoader#2498]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In Expert Mode and above when the Eye of Cthulhu does it's special faster dash it plays the normal roar sound effect. In vanilla, it plays a shorter and more high pitched version of the normal roar. Probably a simple mistake when making the new sound overhaul if I had to guess.

### Steps to reproduce

1. Spawn Eye of Cthulhu in Expert Mode or above difficulties
2. Get it to second form
3. Wait until it does the special dash
4. It plays the wrong sound

### Expected Behavior

It should play the correct sound

### Actual Behavior

It plays the wrong sound

### Reproduction frequency

100% of the time

**Comment by Mirsario** [comment]
This has been fixed on `Jun 15, 2022` in [`#2520`](https://github.com/tModLoader/tModLoader/pull/2520), but I forgot to close this issue.
