### ISSUE TITLE
No hook to PortalHelper

### ISSUE THREAD

**Issue by supermandrew** [bluemagic123/tModLoader#25]
Any chance we can get a hook or some way to modify Terraria.GameContent/PortalHelper.cs?

Awhile ago I had made some modifications to this file to allow portals to handle projectiles and enemies, and this required me to add some code into PortalHelper.cs.  Would allowing a hook into this file make this possible?

As a side question- I also had to make some modifications to Projectile.cs in order to make the projectiles work properly with portals.  Maybe I'm just not seeing it, or maybe it's just not possible, but is there any way to add properties to already created projectiles?  For instance, in Projectile.cs, a list of variables exist for each projectile, such as aiStyle, knockBack, maxPenetrate, etc.  Is it possible to add a property here and then have it set within the SetDefaults method?

Thanks in advance.

**Comment by bluemagic123** [comment]
Where exactly do you want the hooks to be in PortalHelper?

It's possible to make your own properties by using ProjectileInfo. The ExampleMod doesn't have any example of that, but it does use NPCInfo, which is similar.

Sorry for taking so long to get to this!

**Comment by JavidPack** [comment]
Reopen this later if you are still interested in this.
