### ISSUE TITLE
unable to open modded terraria since it stops right away again 

### ISSUE THREAD

**Issue by iSimpFor** [bluemagic123/tModLoader#2508]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i click play, the stop button turns back into play near instantly

the game doesn't open at all

### Log File

![Screenshot from 2022-06-06 18-07-24](https://user-images.githubusercontent.com/44514667/172263863-c32dfcb8-2b6e-490c-9773-e2a3f5ef9f2b.png) (said files never actually become valid despite being redownloaded by steam) 
[Natives.log](https://github.com/tModLoader/tModLoader/files/8848834/Natives.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/8848835/Launch.log)
(the client log doesn't seem touched when opening)

### Expected Behavior

the game should open normally

### Actual Behavior

the game never actually opens, and the stop turns back to play

### Reproduction frequency

happens everytime

**Comment by xianhui3** [comment]
Your error log states that you're missing  your .NET installation.

> Dotnet should be present in "/home/watashi/.steam/debian-installation/steamapps/common/tModLoader/dotnet/6.0.0" 

Have you checked that you have all the required dependencies?

**Comment by iSimpFor** [comment]
![Screenshot from 2022-06-07 15-43-47](https://user-images.githubusercontent.com/44514667/172478871-04d08a0b-54fc-4b4f-bb6f-29a9438d1277.png)
it's in there alright

**Comment by iSimpFor** [comment]
update: the steam files are valid when downloaded until the game is ran, turning the files invalid instead of steam downloading invalid files themselves

**Comment by iSimpFor** [comment]
> Your error log states that you're missing your .NET installation.
> 
> > Dotnet should be present in "/home/watashi/.steam/debian-installation/steamapps/common/tModLoader/dotnet/6.0.0"
> 
> Have you checked that you have all the required dependencies?

i checked and realized that i had the wrong os dotnet

i put it the correct dotnet and the issue is fixed for 1.4

1.3 however "runs" without opening a window
