### ISSUE TITLE
[1.4] [ExampleMod] Reorganize Common.Configs code (mostly ModConfigShowcases code)

### ISSUE THREAD

**Issue by NothyariS0** [bluemagic123/tModLoader#2510]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

Reorganize Common.Configs code by:

* Splitting ModConfigShowcases.cs code into multiple files, proposed structure:

![examplemod-config-reorg-v1](https://user-images.githubusercontent.com/105995054/172356540-793576bc-ccc6-405d-b07c-bf253bfd5b5e.png)

* Adjusting comments after creating new files, to accomodate possible changes caused by reorganization

### What does this proposal attempt to solve or improve?

This change aims mostly to make maintenance of ExampleMod configs easier, in cases of adding new fields to existing ModConfig showcases, making new ExampleMod configs or porting old ExampleMod config to 1.4 (it appears that there are few things left from the Old ExampleMod config to port).

From the modder perspective, this change could possibly make ExampleMod config showcase code more readable and encourage modders to split ModConfig-related code into separate files.

### Which (other) solutions should be considered?

N/a. I think that there are only few things for possible discussion (after this change proposition will be initially approved):

* Is proposed file structure acceptable (**CustomDataTypes** for modder-defined data types, **CustomUI** for modder-defined ConfigElements, **ModConfigShowcases** for "template" configs)? Otherwise, what changes should be made in proposed structure?
* Should remaining old ExampleMod config stuff be ported along with this change, in one PR? Personally, I think that this should be addressed as a separate matter.

**Comment by JavidPack** [comment]
Yeah, this is all fine. Try to keep as much as possible the same text as before, so I don't have to worry that you deleted anything important.

If you want to do this, I would just do the VS Move Type to something.cs button for all of them. 

I'll add additional comments if needed later. No need for porting anything, those TODOs have bigger underlying issues that need to be addressed.

You mentioned that you would be willing to do it, but I can do it if you'd rather, I'd follow your namespace layout.

**Comment by NothyariS0** [comment]
Thank you for your reply. As it appears that the "layout" is OK, I can work on it.

In case of text, I only wanted to change comments that could be no longer valid after separating files and leave any additional adjustments up to you. For example:
* "_This file contains several fake ModConfig classes that each showcase various features of ModConfig._" - will be no longer valid after splitting files,
* "_The rest of this file are many other ModConfig classes that show off various UI capabilities. [...]_" - same as above, I could also create similar comments per each "new" showcase file,
* "_These are some classes and enums used in the ModConfig above._" - will be no longer valid after splitting files, "data types" don't contain any additional comments on top of them so I wanted to keep them without comments as well or adapt this comment per each "data type",
* "_ATTENTION: Below this point are custom config UI elements._" - will be no longer valid after splitting files, I think that the only thing to do here is to adapt this comment per separate file and probably copy/paste comments for Gradient and Corner elements to new files.

If those adjustments are fine, please let me know. Otherwise, I'll just leave all existing comments (but in that case, I'm not sure where I'll put comments described above though).

There are also few things that needs to be confirmed, I guess:
* As "main" ModConfigShowcase file will become obsolete, I think that it could be removed. Is that fine? I don't have any idea how this file will be useful after this "refactoring".
* I've also planned to remove unused "using" statements after separating files. Is that also fine?

**Comment by JavidPack** [comment]
Yeah, that's fine. I imagine there will be nothing left in the old file so it'll be gone. As long as the classnames remain consistent it should be fine.
