### ISSUE TITLE
Manual 1.4 TML install will not launch on family shared accounts

### ISSUE THREAD

**Issue by dozzzz02** [bluemagic123/tModLoader#2516]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am on a family shared account, where I have Terraria from another account. Manually installing 1.4, downloaded from GitHub inside of the game folder, will not work. 

### Log File

[client2.log](https://github.com/tModLoader/tModLoader/files/8854822/client2.log)

**Comment by Jofairden** [comment]
I remember this issue being prevalent when we were just on steam.
Please see https://github.com/tModLoader/tModLoader/issues/881
Please continue the discussion in that issue as well.
I think the workaround is to [install tML manually](https://github.com/tModLoader/tModLoader/releases) (install into steamapps/common/tModLoader
