### ISSUE TITLE
Broken Audio Bug 

### ISSUE THREAD

**Issue by CosmicSnail64** [bluemagic123/tModLoader#2519]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Upon opening Tmodloader, the audio sounds extremely compressed, and slowed down. It misses with every given sound in the game.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8857410/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/8857411/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/8857412/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/8857413/terrariasteamclient.log)

### Steps to reproduce

1. Open up Tmodloader
2. Allow everything to load normally
3. Audio breaks

### Expected Behavior

Everything else is functional, just the audio being broken.

### Actual Behavior

Everything boots up fine except for the audio which sounds choppy and slowed down.

### Reproduction frequency

100% of the time. I have yet to hear clear audio since it was last launched in Late April-Early May.

### Additional Information

https://imgur.com/a/7hycyoS
Sample of the audio bug.

**Comment by Rainboww** [comment]
Having the same issue here - w10 with v2022.6.96.4 (although i tried v2022.05.103.34 as well, which had the same issue)

Game plays fine, stable 60fps with video running smoothly, but audio sounds heavily distorted and slowed down as soon as the game launches, even on the main menu and while the re-logic logo is fading in on startup

Other software and games sound fine, vanilla terraria sounds fine, tmodloader 1.3 legacy sounds fine, 1.4 sounds terrible

I tried restarting my computer, reinstalling terraria, reinstalling tmodloader, manual installs of tmodloader, deleting config files on both, changing the ingame frame skip setting, disabling mods, deleting mods, reinstalling .net, reinstalling XNA, updating my graphics drivers(somehow), deleting players/worlds, all to absolutely no effect (and in no particular order)

Logs attached just in case they're helpful:
[client.log](https://github.com/tModLoader/tModLoader/files/9032405/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9032406/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9032407/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/9032408/terrariasteamclient.log)

**Comment by Chicken-Bones** [comment]
Please try the workaround in #1693

**Comment by Echo-0776** [comment]
As a workaround, please try replacing Libraries\Native\Windows\FAudio.dll in your tModLoader steam dir with https://github.com/tModLoader/tModLoader/blob/927e175d6492eb428e8514249416f1c3c106782f/patches/Terraria/Terraria/Libraries/Native/Windows/FAudio.dll?raw=true

**Comment by Chicken-Bones** [comment]
Updated version of the workaround is in https://github.com/tModLoader/tModLoader/pull/2687

**Comment by mateusfcolla** [comment]
A big fat thank you, replacing the dll worked for me.

**Comment by Zambeid** [comment]
> As a workaround, please try replacing Libraries\Native\Windows\FAudio.dll in your tModLoader steam dir with https://github.com/tModLoader/tModLoader/blob/927e175d6492eb428e8514249416f1c3c106782f/patches/Terraria/Terraria/Libraries/Native/Windows/FAudio.dll?raw=true

Works for everyone, thanks

**Comment by DirtyDannners** [comment]
> As a workaround, please try replacing Libraries\Native\Windows\FAudio.dll in your tModLoader steam dir with https://github.com/tModLoader/tModLoader/blob/927e175d6492eb428e8514249416f1c3c106782f/patches/Terraria/Terraria/Libraries/Native/Windows/FAudio.dll?raw=true

Made an account just to say thank you for this resolution my audio is completely fixed now tysm

**Comment by OrtmanBipacks** [comment]
ty so much!

**Comment by Mentojacka** [comment]
> 

Thank you very much this worked like a charm

**Comment by MuchSquid** [comment]
Amazing work, Still working!! thanks

**Comment by gabozv** [comment]
Keeps working, thank you very much
