### ISSUE TITLE
Damage Calculation Error - All DamageClasses bonuses are applied to Melee Calculations

### ISSUE THREAD

**Issue by EzequielDM** [bluemagic123/tModLoader#2521]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Every sort of damage bonus applied, be it _DamageClass.Magic_, _DamageClass.Summon_ or others change the damage of melee weapons.

Behavior is only present on TModLoader and doesn't happen on normal Terraria.

![In-Game Screenshot](https://user-images.githubusercontent.com/17010688/172533662-3f8bbeb8-24e5-4aa1-a103-d4236ed8ec20.png)

(No buffs, no mods [except for CheatSheet on this screenshot but it was tested without and the behavior persists])

### Log File

[client.log (probably not needed)](https://github.com/tModLoader/tModLoader/files/8858333/client.log)

### Steps to reproduce

1. Create a new character
2. Add in Papyrus Scarab, Summoner Emblem, Celestial Emblem and any other class specific damage bonus accessories
3. Equip them
4. Watch the melee damage of any weapon change as you equip and unequip them

### Expected Behavior

I think the description of expected behavior is not needed.

### Actual Behavior

`magicDamage += 0.2f` should not change `meleeDamage` at all, but for some reason it is on TModLoader.

### Reproduction frequency

Consistent.

### Additional Information

I'm pretty sure this has to do with the new patches for Player#GetDamage(DamageClass damageClass) or Player#GetWeaponDamage(Item sItem, [bool forTooltip = false])

**Comment by Jofairden** [comment]
This seems like an odd one. My first thought is that this is probably some kind of reference error
Tagging @Chicken-Bones and @Mirsario

**Comment by Chicken-Bones** [comment]
Fixed in #2523
