### ISSUE TITLE
Please make the server software headless

### ISSUE THREAD

**Issue by xaetacorenet** [bluemagic123/tModLoader#2526]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

Developers are having a very hard time getting your software to run in Docker containers, The main reason is a lack of documentation, and the fact your software has prompts build in on boot up, it would be better if the program had an option for a config file to be loaded in, since auto starting the software is impossible at the moment, which is really bad for the game/mod since its basically unusable on any serious server hardware.

Please implement a feature so that we can use config files instead, if this already exists please document it, I have spend 5 hours trying to get the newest version to work in a docker container to no avail, and in the DeticatedServer folder of the zip i also did not get any wiser, it refered to a git repository for an outdated version.

### What does this proposal attempt to solve or improve?

Makes it possible to use the application as a server on real hardware or container orchestration platforms

### Which (other) solutions should be considered?

None

**Comment by Jofairden** [comment]
I think this is a serious concern, except it will take a thorough look over the server code
Can you explain this?
```
it would be better if the program had an option for a config file to be loaded in, since auto starting the software is impossible at the moment, which is really bad for the game/mod since its basically unusable on any serious server hardware.
```
As far as I know, there is a config. Or, what do you mean? And what do you mean with auto starting is impossible on any 'serious' server hardware? It would be useful if you can share some host services that are having problems for example. Also, do you mean 100% headless, or just text interface? Thanks

**Comment by direwolf420** [comment]
To start a server without being prompted about steam, invoke `start-tmodloader.sh/bat` with parameters:
`-server -config serverconfig.txt <other parameters desired>`
This is equivalent to running `start-tmodloaderServer.sh/bat` and selecting `steam=n`

**Comment by xaetacorenet** [comment]
@direwolf420 I would reccomend adding this to the README.md so that users can find this information, thanks for the swift answer

**Comment by Jofairden** [comment]
> @direwolf420 I would reccomend adding this to the README.md so that users can find this information, thanks for the swift answer

I assume this is solved now, so I will go ahead and close.
I added the information for you here: https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#starting-server-headless
