### ISSUE TITLE
tmodloader literally just not opening

### ISSUE THREAD

**Issue by lordgoop** [bluemagic123/tModLoader#2528]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I click the play button, a weird code screen pops up, runs some strands of texts and then disappears and then the game does not open
![code screen](https://user-images.githubusercontent.com/107150600/172710308-85c36c7c-ef96-4c9d-86cd-b0ecc24928ca.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8864816/client.log)

### Steps to reproduce

1. click play
2. code screen pops up
3. nothing happens

### Expected Behavior

the game should just open as normal but it does not

### Actual Behavior

This weird code screen (attached above) shows up and then the game does not launch

### Reproduction frequency

it happens every time

### Additional Information

no

**Comment by Ju4nse** [comment]
Literally the same thing happens to me, did you find a solution or something?

**Comment by lizardhead** [comment]
omg so abboying

**Comment by Chicken-Bones** [comment]
Please come to the discord for support with these issues. Check the pinned flowchart in the #support channel.
