### ISSUE TITLE
[1.4] [Linux] Thumb mouse buttons can't be binded

### ISSUE THREAD

**Issue by MrD4rk5oul** [bluemagic123/tModLoader#2540]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Mouse4 and Mouse5 can't be binded in Settings>Controls>Keybindings.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8883337/client.log)

### Steps to reproduce

1. Go to Keybidings settings
2. Try to bind any mouse thumb button to any option

### Expected Behavior

The button should be binding.

### Actual Behavior

The button isn't binding.

### Reproduction frequency

All the time.

### Additional Information

Checked Issue #1766 but to no avail.

Using Arch Linux/Cinnamon.
Mouse used is a Redragon M710.

**Comment by jpsalis** [comment]
I've noticed this as well, though it also effects the vanilla terraria game too.

**Comment by JavidPack** [comment]
It would be good if we could get additional confirmation on if vanilla Terraria has or does not have this issue.

**Comment by LennyPhoenix** [comment]
Vanilla also has this problem.

**Comment by pokerhawk** [comment]
For archlinux distro base, install [xbindkeys](https://wiki.archlinux.org/title/Xbindkeys)
That fixed the problem for me
