### ISSUE TITLE
[1.4] Deerclops' ice spikes attack sounds are too low

### ISSUE THREAD

**Issue by Polaritz** [bluemagic123/tModLoader#2543]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Deerclops ice spikes attack sound is hardly audible

### Steps to reproduce

1. spawn deerclops
2. wait until it uses ice spike attack

### Expected Behavior

Ice spike attack sounds play normally

### Actual Behavior

Ice spike attack sounds are way too low compared to vanilla

### Reproduction frequency

always

**Comment by Mirsario** [comment]
Cannot reproduce in modern TML, the volume is exactly the same as in vanilla. Perhaps someone fixed this and forgot to close the issue.
