### ISSUE TITLE
Cannot open mod links in firefox: profile missing

### ISSUE THREAD

**Issue by SandWoodJones** [bluemagic123/tModLoader#2544]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whether I'm in my mod list or in the mod browser if I click the "Visit the Mod's Homepage for even more info" button I receive an error message from firefox that claims my profile is missing. This happens with any mod I try.
I've tried the solutions from [this support page](https://support.mozilla.org/en-US/kb/how-run-firefox-when-profile-missing-inaccessible) from firefox but none of them worked.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8884885/client.log)

### Steps to reproduce

1. Load tModLoader
2. Open the mod browser
3. Pick any mod that has a homepage button
4. Click the button
5. Receive the error message

### Expected Behavior

Either a new tab on my firefox should open with the mod's homepage or the link to the homepage to be copied to my clipboard.

### Actual Behavior

I receive this error message
![image](https://user-images.githubusercontent.com/35671374/173207980-315591be-e232-4428-bd21-fbecc9b358c3.png)

### Reproduction frequency

Every time I launch the game and try to access a mod's homepage

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
Same thing for me with a French locale and otherwise identical parameters.
