### ISSUE TITLE
Backgrounds being too low

### ISSUE THREAD

**Issue by Lion8cake** [bluemagic123/tModLoader#2546]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The backgrounds feel way too low in the 1.4 version. Also the mid background is lower than the close background making the close background feel too overpowering at some times.

### Expected Behavior

The backgrounds should be higher and the close background should be lower than the mid background.

### Actual Behavior

They feel too low and are much lowwer than the vanilla backgrounds when compared to eachother.

### Reproduction frequency

Almost every time

**Comment by Lion8cake** [comment]
Edit: Close being taller than mid is only present in the menu background

**Comment by JavidPack** [comment]
This needs a screenshot or something. Load the same world file in Terraria and tModLoader, stand in the same position, and take a screenshot. Otherwise, it looks fine to me.

If anyone can confirm this issue, we can reopen and look into it.
