### ISSUE TITLE
Opening the Mod Configuration screen does not freeze the game

### ISSUE THREAD

**Issue by Nobisyu12** [bluemagic123/tModLoader#2548]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In vanilla, when you open the settings screen, it automatically will freeze the game in single player. This works as intended. However, when you click Mod Configuration option and open its menu, the game unfreezes.

### Steps to reproduce

1. Load into a single player world
2. Open the settings menu, then the Mod Configuration menu
3. Notice how the world does not freeze and you can still move around and do things

### Expected Behavior

The game should freeze

### Actual Behavior

The game does not freeze

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
Fixed in #2871
