### ISSUE TITLE
When I cut down the tree, I down get the timber badge.

### ISSUE THREAD

**Issue by rendomiszed** [bluemagic123/tModLoader#2551]
### Version

Latest 1.4-preview

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when I cut down a tree I didn't get the timber badge

**Comment by Chicken-Bones** [comment]
Linking #1491, but there's definitely a smaller todo item, which is to just allow you to get vanilla achievements in tML (but not tracked on steam).
