### ISSUE TITLE
Mod build success，but can not found "mod button" to add mod.

### ISSUE THREAD

**Issue by snake89322** [bluemagic123/tModLoader#2556]
### Version

Latest 1.4-preview

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![image](https://user-images.githubusercontent.com/10811862/173849319-5076685c-d8e9-42ad-b34c-4cb7c102920e.png)
![image](https://user-images.githubusercontent.com/10811862/173849422-3100f479-6157-47ff-908b-6e444818887b.png)
![image](https://user-images.githubusercontent.com/10811862/173849541-4e260e02-ca9d-4ad5-b352-76b0aaef68f0.png)
![image](https://user-images.githubusercontent.com/10811862/173849754-c891aa02-cbbc-4234-9ae9-2e0ae8c6219b.png)
![image](https://user-images.githubusercontent.com/10811862/173850420-b486ec5d-fa50-4cd6-a613-dcb954ce68a1.png)

### Steps to reproduce

Just Get start tutorial.

**Comment by sgkoishi** [comment]
你认为具体哪一步/哪一张图片和你料想的不同呢？

**Comment by JavidPack** [comment]
I'm not sure what the issue is here. The mod should not show up in the mod configurations page unless it has a ModConfig. If the issue persists, feel free to explain the issue and reopen this issue.
