### ISSUE TITLE
TModloader 1.3 legacy keeps crashing do to a "Graphics engine failure". 

### ISSUE THREAD

**Issue by ThinkTomato2039** [bluemagic123/tModLoader#2558]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I have tried doing as it says by going into config.json and turning support4k off but, I'm still getting the same error.

### Reproduction frequency

every time

### Additional Information

The only reason im even trying this version is because calamity is not appearing in the mod browser for the other versions.

**Comment by direwolf420** [comment]
disable the "Razer Cortex" program.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
