### ISSUE TITLE
Changing Max Health, Defense, or Damage causes other stats to be affected in-game.

### ISSUE THREAD

**Issue by jaydevelopsstuff** [bluemagic123/tModLoader#2563]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When modifying the `lifeMax`, `defense`, or `damage` of an NPC, other stats get affected in game.

### Log File

There are no abnormalities in the `client.log` file.

### Steps to reproduce

1. Create a mod with one NPC that has `lifeMax` set to `30` and another NPC that has `lifeMax` set to `30` as well.
2. Set the first NPCs `defense` to `2`, and set the second's to `10`.
3. Compile the mod in game.
4. Spawn in the NPCs and observe that the second NPC has less health, and does less damage than the first.

### Expected Behavior

NPC stats (max health, defense, and damage) should be individual of each other and not affect one another in-game.

### Actual Behavior

NPC stats (max health, defense, and damage) do affect each other in-game.

### Reproduction frequency

All the time.

**Comment by Chicken-Bones** [comment]
Can you send us a little test mod, or a .cs file that we could add to ExampleMod?

**Comment by jaydevelopsstuff** [comment]
> Can you send us a little test mod, or a .cs file that we could add to ExampleMod?

Sure, I can't at the moment but I'll try to give you guys a test mod tomorrow.

**Comment by jaydevelopsstuff** [comment]
@Chicken-Bones Here you go: https://github.com/jaydevelopsstuff/BugTestMod.git

**Comment by Chicken-Bones** [comment]
![image](https://user-images.githubusercontent.com/388233/175112959-02761293-7b26-44bd-97df-f2e4aaa871a6.png)
![image](https://user-images.githubusercontent.com/388233/175112976-85c04f7e-062e-4e73-ab02-7dd526c7a09e.png)
I used CheatSheet
![image](https://user-images.githubusercontent.com/388233/175113058-a40de8da-f8dc-4ee5-bff8-47d62c42fdc4.png)
![image](https://user-images.githubusercontent.com/388233/175113079-82e4f36e-f8fc-4748-bc1d-f42d33fc43c0.png)

**Comment by Chicken-Bones** [comment]
Unable to replicate. Re-open if more info found.

**Comment by jaydevelopsstuff** [comment]
Closing due to issues with reproducibility.
