### ISSUE TITLE
Can't delete mods / Unexpected behavior when deleting mods

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2567]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I delete a mod, instead of it being deleted the version just downgrades and to delete a mod I have to click the delete button twice. The mod doesn't go away, it doesn't appear in the mod manager but the mod browser won't let me install the mod again, tried uninstalling terraria/tmodloader, restarted steam and pc but nothing changed, I can't install the previously "deleted" mods.
I tried to manually delete the mods but when I click on the "open mod folder" button it opens this directory "..Terraria\tModLoader\Mods" and the only files that are inside of it are an empty folder and a .json empty file.

![1](https://user-images.githubusercontent.com/67590845/174292458-3237d8fd-7bf8-4ff8-b8a5-3fc104ddbed1.png)
![2](https://user-images.githubusercontent.com/67590845/174292460-d915bc23-1f69-4d32-b847-4b49191b8bc9.png)
![3](https://user-images.githubusercontent.com/67590845/174292462-33477bd8-3545-4a34-85f3-14e8992e6140.png)
![4](https://user-images.githubusercontent.com/67590845/174292465-476f22c4-6fb4-4b1e-997c-764f998ea03c.png)
![5](https://user-images.githubusercontent.com/67590845/174292468-96cc44db-9371-4908-94c4-feaef2d464ff.png)

### Steps to reproduce

1. Open the "manage mods" section
2. Click the delete button on a mod and on the dialogue click "yes"
_At this point the mod should still be there but downgraded_
3. Click again the delete button on a mod and on the dialogue click "yes"
_Then the mod will disappear_

### Expected Behavior

The mod should be uninstalled when clicking the remove button

### Actual Behavior

The mod just downgrades by a version and then I have to click twice to make it disappear from the mod list

### Reproduction frequency

Every single time with every single mod

**Comment by ibaldwin** [comment]
Similar behavior for me too, and I'm seeing this persist through game uninstalls/reinstalls and file clears. Process im using during uninstall: 
uninstall tmodloader and terraria from the steam library (right click -> manage -> uninstall)
go to steamapps -> common and delete remnants of the previous installs for both games
go to My Games and delete the Terraria folder (which includes a child tmodloader folder)
install terraria and launch game
close terraria
install tmodloader and launch game
check the modlist, mods are present until double click delete

a difference I'm seeing from original report, once I hit delete twice from the mod list I do see the mods show up in the mod browser, but I am presented with the following image (I have tried restarting and no change in what I see)
![image](https://user-images.githubusercontent.com/4235908/174419419-79e1a1ad-8044-4281-b341-2be583a79c46.png)

**Comment by H-isaac23** [comment]
I've experienced the same thing, but I found this temporary workaround for re-installing mods. It should work for any mod afaik by just unsubscribing on the mod's steam page. @ibaldwin @valikek 
![282228288_5170234269724020_5694089679511009684_n](https://user-images.githubusercontent.com/72616353/174591163-af73fa8d-1abf-4eb3-8bf2-2830fad6d2fe.png)
