### ISSUE TITLE
tml error

### ISSUE THREAD

**Issue by Pokefan447** [bluemagic123/tModLoader#2569]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i launch tmodlader, i get this error message
![terraria doesnt work](https://user-images.githubusercontent.com/107719026/174392650-57fec75d-3779-4552-ae26-40a3cd8271ad.PNG)

### Steps to reproduce

launch tmodlader 
the game crashes

### Expected Behavior

the game launches

### Actual Behavior

tmodlader crashes on startup

### Reproduction frequency

every time

**Comment by Chicken-Bones** [comment]
Uninstall and re-install Terraria and tModLoader

**Comment by Pokefan447** [comment]
I tried that recently and it still didnt work :(

**Comment by JavidPack** [comment]
Come to discord for support. This is a clear support issue, not a bug
