### ISSUE TITLE
Mod browser not showing all mods/not updating

### ISSUE THREAD

**Issue by winsatid62** [bluemagic123/tModLoader#2577]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I opened the mod browser and clicked to sort using the most popular. The top mod is "[1.4 Alpha] Shorter Respawn Time" and I can't find mods like "Magic Storage" or "Recipe Browser." Also, all mods show that they were last updated 52 years ago.

<img width="1440" alt="Screen Shot 2022-06-19 at 4 32 24 PM" src="https://user-images.githubusercontent.com/73169721/174476148-f41ba4c2-88bc-4e1b-8768-a35ff1205513.png">

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8935142/client.log)

### Steps to reproduce

1. Open Tmodloader
2. Click "Workshop" from main menu
3. Click "Download mods"

### Expected Behavior

My brother use window and have no problem and it shows up-to-date mods and more mods

### Actual Behavior

It only shows limited mods and missing some mods I want to install

### Reproduction frequency

It always happens for me

### Additional Information

What I am using:

MacBook Air (M1, 2020)

macOS Monterey
Version: 12.4 (21F79)

**Comment by NoxAurea** [comment]
FYI I am also having this problem. Adding mods through the Steam Workshop for TML works for me as a workaround. The mods load, run, and can be configured in-game properly thus bypassing this issue with the in-game Mod Browser.

My System Info (FWIW):
Terraria 1.4.3.6
tModLoader 2022.5.103.34
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) Intel
MacOS Monterey 12.4 (21F79)

**Comment by JavidPack** [comment]
Can someone confirm if this is still an issue on 1.4.4-preview?

**Comment by realstuffie** [comment]
> Can someone confirm if this is still an issue on 1.4.4-preview?

Yes, 
I have the same issue, on 1.4.4-preview, and issue persists when subscribing from steam 

Tmodloader V2023.6.25 preview d87eeo85
Windows 10 Pro build: 19045.3208, Version 22H2
