### ISSUE TITLE
Clicking publish has a long delay

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2578]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Opening "Mod Sources" or pressing "Publish" on one of the mods causes a big delay (that seemingly scales with the amount of mods you have in the menu and the amount of already published mods on the workshop)
In my current constellation (35 mods) it freezes the game for about 10 seconds

### Log File

No logs

**Comment by jaydevelopsstuff** [comment]
I get the same issue but only when clicking publish.

**Comment by Solxanich** [comment]
From discord, thanks for making issue:
![image](https://user-images.githubusercontent.com/6795251/191370397-65f19d95-771b-4dde-a7d7-82db203632fd.png)

**Comment by direwolf420** [comment]
This is what is causing the Mod Sources freeze:
https://github.com/tModLoader/tModLoader/blob/8ef29f1a7ec0aa7d7890d86ec98c81237d28239d/patches/tModLoader/Terraria/ModLoader/UI/UIModSourceItem.cs#L159-L161

**Comment by Solxanich** [comment]
Fixed in 99c0328b85a0203f5da2cd76e4bd6014a165cf04
