### ISSUE TITLE
Item.consumable not working without use of UseItem method

### ISSUE THREAD

**Issue by SheepishShepherd** [bluemagic123/tModLoader#2580]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

ModItems must have the following in order for the item to actually consume:
```
Item.consumable = true;
```
AND
```
public override bool? UseItem(Player player) => true;
```
From a modder's perspective, it seems like just having `Item.consumable = true;` should be enough to make an item reduce its stack by 1 and shouldn't require another method.

**Comment by Chicken-Bones** [comment]
Can you confirm with `ExampleBuffPotion`?

**Comment by SheepishShepherd** [comment]
Potions and buff potions still work as expected, however for items where you just want to apply outside changes (ei: start an event, update ModPlayer variables, etc) the UseItem method must be passed with true instead of its default value of null (use vanilla behavior).

I found this while attempting to make a Town Pet License, where it would update a world-based bool to true, allowing the Town Pet NPC to spawn naturally.

**Comment by JavidPack** [comment]
I believe to have an item be "use"able, it needs a set of other things. usetime, useanimation, usestyle, maybe some others. The code is a maze. The solution might just be to document the code necessary for an item to be considered usable/consumable

**Comment by SheepishShepherd** [comment]
I have all of those as well, as I was trying to make a Town Pet License and I just copied what the Bunny License had in the base game. So unless it is some other variable I'm missing, I don't know why I would have to force call it. If this is how it should be, then so be it.
```
// My Mod
public override void SetDefaults() {
	Item.useStyle = ItemUseStyleID.HoldUp;
	Item.consumable = true;
	Item.useAnimation = 45;
	Item.useTime = 45;
	Item.UseSound = SoundID.Item92;
	Item.width = 28;
	Item.height = 28;
	Item.maxStack = 20;
	Item.rare = ItemRarityID.Green;
	Item.value = Item.buyPrice(gold: 5);
}
```
```
// Source code
case 4910:
	this.useStyle = 4;
	this.consumable = true;
	this.useAnimation = 45;
	this.useTime = 45;
	this.UseSound = SoundID.Item92;
	base.width = 28;
	base.height = 28;
	this.maxStack = 20;
	this.SetShopValues(ItemRarityColor.Green2, Item.buyPrice(0, 5));
	break;
```

**Comment by Chicken-Bones** [comment]
Vanilla has the following in `ItemCheck_UsePetLicenses`
```cs
if (sItem.type == 4910 && !NPC.boughtBunny && itemAnimation > 0 && ItemTimeIsZero) {
	ApplyItemTime(sItem);
	if (Main.netMode == 0) {
		NPC.boughtBunny = true;
		Main.NewText(Language.GetTextValue("Misc.LicenseBunnyUsed"), 50, byte.MaxValue, 130);
	}
	else {
		NetMessage.SendData(61, -1, -1, null, whoAmI, -14f);
	}
}
```

Because there are so many ways an item can be used, and many of those require certain conditions which can fail, items are only consumed if an item use is actually performed, either because a vanilla code path runs `ApplyItemTime` or because your mod returns `true` from `UseItem`

```cs
if (ItemLoader.UseItem(item, this) == true)
	ApplyItemTime(item, callUseItem: false);
```

Because the pet license code is locked to the bunny license item-id, your item doesn't do anything when used, and thus is not consumed. That's what `return true;` in `UseItem` is for.
