### ISSUE TITLE
MusicLoader Crash

### ISSUE THREAD

**Issue by FlynnSMT** [bluemagic123/tModLoader#2581]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to load in a mod like Stars Above or Gensokyo it always says that it couldn't be unloaded properly because of something called MusicLoader
Here's my client.log file for more info

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8937442/client.log)

### Steps to reproduce

Use a mod like Stars Above and Gensokyo
### Expected Behavior

Crashes the game

**Comment by Chicken-Bones** [comment]
Fixed in 7d024a1
