### ISSUE TITLE
Game Crashes When Loading Mod Content

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2582]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I open the game, the game stops responding and gives an error stating that an asset from the mod I was developing was unable to load.
I am unable to continue development modding as I cannot use the game.
This is not an issue with my code.
All files are properly named and I have disabled my firewall and other restrictions before opening the game.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8939348/client.log)

### Steps to reproduce

1. Open tModloader
2. Wait for mods to begin loading
3. Game crashes

### Expected Behavior

Mods should load normally and the game should not crash

### Actual Behavior

The game crashes and gives an error seen in console.log when loading mods

### Reproduction frequency

This issue occurs every time I attempt to start the game

**Comment by ghost** [comment]
This issue can be ignored by switching out of the window when loading and pressing ok on the error message. The game then allows you to build/reload your mods and I have not encountered the issue since.

**Comment by Chicken-Bones** [comment]
Looks like an issue with `IvyStuff` trying to load `Content\Items\Weapons\Test` which didn't exist because the path is wrong.
