### ISSUE TITLE
[1.4-preview] All worlds made before this preview are unusable (Load Failed!)

### ISSUE THREAD

**Issue by terrynmuse** [bluemagic123/tModLoader#2589]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

All worlds I've tried loading that aren't generated on this preview, are unusable

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8944822/client.log)

### Additional Information

[Worlds.zip](https://github.com/tModLoader/tModLoader/files/8944823/Worlds.zip)

**Comment by Chicken-Bones** [comment]
Fixed in f046767
