### ISSUE TITLE
Incorrect error reporting

### ISSUE THREAD

**Issue by LuckyPants12** [bluemagic123/tModLoader#2590]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When Building and reloading my own mod, a error come up on the loading phase which states the error, but isnt really pointing towards the right place to look for, unless i go in the client.log myself and look for the error,

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8947864/client.log)

### Steps to reproduce

1) Using the Projectile and bullet files given ( please adjust namespace as needed) build and reload the mod ,
2) the build will be sucessfull but while loading the mod , the mod will fail to load with a error.

### Expected Behavior

It should correctly point towards where the error is in the mod files itself ( see client log for actual place where error is)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/75674528/174775892-2f6c901f-9170-42d3-bd38-6457d7ab925c.png">

### Actual Behavior

It is not correctly displaying the error in the files needed to fix the errors, unless you go to the client.log

### Reproduction frequency

100%

### Additional Information

[TechArrow.txt](https://github.com/tModLoader/tModLoader/files/8947930/TechArrow.txt)
[TechProjectileArrow.txt](https://github.com/tModLoader/tModLoader/files/8947933/TechProjectileArrow.txt)

These files are required ( i think so according to the client log) for the error to occur. Normally compiling should work after building and reloadng, the  line 29 in TechProjectileArrow seems to be doing this ( i had to upload in .txt as it wont work in .cs)

**Comment by Chicken-Bones** [comment]
Fixed in f002609
