### ISSUE TITLE
I can't open the 1.3-legacy of tml

### ISSUE THREAD

**Issue by UnknowUserLi** [bluemagic123/tModLoader#2593]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I can run tml on 1.4 or 1.4-preview ,but i cant run tml on 1.3-legacy.
When i open tml on 1.3-legacy , nothing happens , maybe in the backend something got wrong , 
but i have no clue, i have no error popups.
Also i can ran tml on 1.3-legacy before,but  i might use alt+f4 to close the game,and the next day this bug happened.
i dont konw if this can help.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8949932/client.log)

### Steps to reproduce

1:change tml version to 1.3-legacy
2:open the game
3:nothing happens

### Expected Behavior

The game is running normally

### Actual Behavior

I cant open the game on 1.3-legacy

### Reproduction frequency

All the time

**Comment by direwolf420** [comment]
Try disabling/uninstalling "Razer Cortex", unplugging controllers, disabling virtual controller programs (vjoy for example), or doing this:
1. Go to your install directory, right click tModLoader.exe, 'properties', then 'compatibility'
2. then set tick on 'compatibility mode' and select win 8 (or try others)
3. Click 'Apply' then relaunch tModLoader

**Comment by UnknowUserLi** [comment]
> Try disabling/uninstalling "Razer Cortex", unplugging controllers, disabling virtual controller programs (vjoy for example), or doing this:
> 
> 1. Go to your install directory, right click tModLoader.exe, 'properties', then 'compatibility'
> 2. then set tick on 'compatibility mode' and select win 8 (or try others)
> 3. Click 'Apply' then relaunch tModLoader

thank UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU !
options 2 works
