### ISSUE TITLE
Mod List Page slow/stuttering FPS

### ISSUE THREAD

**Issue by viniciusdel** [bluemagic123/tModLoader#2596]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Hey all. I saw a closed issue on this, but I am still experiencing this issue on the latest version (stable 1.4).

Whenever I open Workshop > Download Mods, the page loads and then once the mods appear the FPS goes to 3-4. This happens every time, I tried both on steam and downloading the latest stable version. 

Is there a known fix to this? 

Thank you, and sorry if this was open somewhere and I did not find it. 

### Steps to reproduce

Workshop > Download Mods

### Expected Behavior

Stable FPS like other versions

### Actual Behavior

Low Fps

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
There have been fixes for this issue over the past year, this should be resolved, closing for now.
