### ISSUE TITLE
[v2022.5.103.32] Cross-mod recipes won't work

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2599]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The recipes for items from other mods won't register, despite the code being available and running from my mod that I made.
**The Code**
```csharp
namespace CraftableTreasureBags
{
	public class CraftableTreasureBagsVitalityRecipes : ModSystem
	{

		public override void AddRecipes()
		{
			if (!ModLoader.TryGetMod("VitalityMod", out var VitalityMod)) return;
			{
				if (!ModContent.TryFind("VitalityMod/StormCloudBossBag", out ModItem StormCloudBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/GrandAntlionBossBag", out ModItem GrandAntlionBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/MoonlightDragonflyBossBag", out ModItem MoonlightDragonflyBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/DreadnaughtBossBag", out ModItem DreadnaughtBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/AnarchulesBeetleBossBag", out ModItem AnarchulesBeetleBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/AnarchulesBeetleCrimsonBossBag", out ModItem AnarchulesBeetleCrimsonBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/ChaosbringerBossBag", out ModItem ChaosbringerBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/PaladinSpiritBossBag", out ModItem PaladinSpiritBossBag)) return; //VitalityMod

				StormCloudBossBag.CreateRecipe()
					.AddIngredient<Items.EmptyTreasureBag>()
					.AddIngredient<Items.VitalityModItems.PureVase>()
					.AddIngredient(VitalityMod, "CloudCore")
					.AddIngredient(1243, 1)
					.AddIngredient(317, 3)
					.AddIngredient(VitalityMod, "CloudVapor", 28)
					.AddIngredient(VitalityMod, "StormCloudMask")
					.AddTile(26)
					.AddCondition(Recipe.Condition.NearWater)
					.Register(); //Storm Cloud Phase 1 Type
				StormCloudBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.PureVase>().AddIngredient(VitalityMod, "CloudCore").AddIngredient(1243, 1).AddIngredient(317, 3).AddIngredient(VitalityMod, "CloudVapor", 28).AddIngredient(VitalityMod, "StormCloudMask2").AddTile(26).AddCondition(Recipe.Condition.NearWater).Register(); //Storm Cloud Phase 2 Type
				GrandAntlionBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.PureVase>().AddIngredient(VitalityMod, "AncientCrown").AddIngredient(VitalityMod, "AntlionHide").AddIngredient(VitalityMod, "DriedBar", 22).AddIngredient(169, 50).AddIngredient(3271, 50).AddIngredient(VitalityMod, "GrandAntlionMask").AddTile(26).Register(); //The Grand Antlion
				MoonlightDragonflyBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.PureVase>().AddIngredient(VitalityMod, "MoonlightLotusFlower").AddIngredient(VitalityMod, "GlowingGraniteBar", 3).AddIngredient(314, 3).AddIngredient(VitalityMod, "MoonlightDragonflyMask").AddTile(26).Register(); //Moonlight Dragonfly
																																																																																						   // Hardmode Recipes Start Here
				DreadnaughtBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.FireFrostVase>().AddIngredient(VitalityMod, "Dreadcandle").AddIngredient(175, 12).AddIngredient(318, 5).AddIngredient(VitalityMod, "DreadnaughtMask").AddTile(26).Register(); //Dreadnaught
				AnarchulesBeetleBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.FireFrostVase>().AddIngredient(VitalityMod, "AnarchyCrystal").AddIngredient(VitalityMod, "AnarchyBar", 40).AddIngredient(60, 20).AddIngredient(316, 5).AddIngredient(VitalityMod, "AnarchulesBeetleMask").AddTile(26).Register(); //Anarchules Beetle (Corruption)
				AnarchulesBeetleCrimsonBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.FireFrostVase>().AddIngredient(VitalityMod, "AnarchyCrystalCrimson").AddIngredient(VitalityMod, "AnarchyBarCrimson", 40).AddIngredient(2887, 20).AddIngredient(316, 5).AddIngredient(VitalityMod, "AnarchulesBeetleCrimsonMask").AddTile(26).Register(); //Anarchules Beetle (Crimson)
				ChaosbringerBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.FireFrostVase>().AddIngredient(VitalityMod, "TotemofChaos").AddIngredient(VitalityMod, "ChaosBar", 40).AddIngredient(VitalityMod, "ChaosCrystal", 100).AddIngredient(2317).AddIngredient(315, 3).AddIngredient(VitalityMod, "ChaosbringerMask").AddTile(26).Register(); //Chaosbringer
				PaladinSpiritBossBag.CreateRecipe().AddIngredient<Items.EmptyTreasureBag>().AddIngredient<Items.VitalityModItems.FireFrostVase>().AddIngredient(VitalityMod, "SpiritBox").AddIngredient(VitalityMod, "EquityCore").AddIngredient(VitalityMod, "SoulofVitality", 40).AddIngredient(VitalityMod, "Ectosoul", 25).AddIngredient(314, 5).AddIngredient(VitalityMod, "PaladinSpiritMask").AddTile(26).Register(); //Paladin Spirit

			}
		}
	}
}
```
I have the using directives in place btw.

**The Issue:** No expected recipe, which is the Treasure Bag.
![image](https://user-images.githubusercontent.com/70764728/175014638-153498d4-8371-4922-945b-71f17c2b71f3.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8957022/client.log)

### Steps to reproduce

1. Enter your cross-mod recipe code (or skip this step if you already have it).
2. Reload your mod and the mod you are utilizing for the cross-mod code, making sure that they are both enabled.
3. Check recipe browser and/or the guide's crafting help for the item you have and what to use it for.
4. The recipe for your specific item (in my case, treasure bag) is not there.

### Expected Behavior

The item should appear in the recipe browser and/or crafting help, also taking into account that the item you used for your recipe should say material.
For example:
![image](https://user-images.githubusercontent.com/70764728/175016970-da6a136a-7d13-4388-952b-6f8114adecb0.png)
However, this does not say "Material", even though it's supposed to be registered as a material.

### Actual Behavior

The item that can be crafted does not appear in recipe browser and/or crafting help, and thus cannot be crafted or used to craft.

### Reproduction frequency

About 100% of the time.

### Additional Information

References #2070

**Comment by JavidPack** [comment]
This is quite a large amount of code, did you step through while debugging to see which lines are executed? My guess is you just have a typo somewhere. You would need to confirm to us that you've stepped through and that each .Register method is being reached.

If the code is being reached, make an example recipe using an ExampleMod item so we can actually test this, we can't test against VitalityMod.

**Comment by Setnour6** [comment]
> This is quite a large amount of code, did you step through while debugging to see which lines are executed? My guess is you just have a typo somewhere. You would need to confirm to us that you've stepped through and that each .Register method is being reached.
> 
> If the code is being reached, make an example recipe using an ExampleMod item so we can actually test this, we can't test against VitalityMod.

I do recall that this code was working before and everything went well. I haven't made any changes to it since the code stopped working properly and since this issue became a thing.

**Comment by Chicken-Bones** [comment]
I can't test the issue with the code you've given, because I don't have the rest of the mod. Like jopo said, if you can confirm it's broken with an example item recipe then we can test it. Also please come to the discord to discuss.

Most likely, VitalityMod has just changed the internal names of some items.

**Comment by Setnour6** [comment]
> I can't test the issue with the code you've given, because I don't have the rest of the mod. Like jopo said, if you can confirm it's broken with an example item recipe then we can test it. Also please come to the discord to discuss.
> 
> Most likely, VitalityMod has just changed the internal names of some items.

I checked the internal names and compared it to the code I wrote, and there hasn't been any changes. I will write the code for Example Mod and see if it works, and you can test it.

**Comment by Setnour6** [comment]
So I wrote this code:
```csharp
namespace CraftableTreasureBags
{
	public class CraftableTreasureBagsExampleRecipes : ModSystem
	{

		public override void AddRecipes()
		{
			if (!ModLoader.TryGetMod("ExampleMod", out var ExampleMod)) return;
			{
				if (!ModContent.TryFind("ExampleMod/MinionBossBag", out ModItem MinionBossBag)) return; //ExampleMod

				MinionBossBag.CreateRecipe()
					.AddIngredient<Items.EmptyTreasureBag>()
                                        .AddRecipeGroup("CraftableTreasureBags:Gold/Platinum Pendant")
					.AddIngredient(ExampleMod, "MinionBossSummonItem")
					.AddIngredient(ExampleMod, "ExampleItem", 999)
					.AddIngredient(ExampleMod, "MinionBossMask")
					.AddTile(26)
					.Register(); //Minion Boss
			}
		}
	}
}
```
So this somehow works, but the VitalityMod content does not. I checked the entries for the StormCloudBossBag recipe and the names were written correctly, otherwise I would get an error or the item would just be excluded from the recipe. I don't expect the entire recipe to be excluded.

Here are all of the mod internal names for the StormCloudBossBag item that are being used:
![image](https://user-images.githubusercontent.com/70764728/175166663-4b7aa87c-b442-4e1a-b1d4-fa5c7de92836.png) 
![image](https://user-images.githubusercontent.com/70764728/175166755-675f57b5-9682-4029-b50b-975f472f273d.png)
![image](https://user-images.githubusercontent.com/70764728/175166775-29d84ce3-c914-4064-83bc-fe16bd239150.png)
![image](https://user-images.githubusercontent.com/70764728/175166798-48d0402c-4725-4553-9a05-4488c385221c.png)

You can compare this with the code I wrote in the description above.

**Comment by Chicken-Bones** [comment]
You'll probably fine that _one_ of these items is missing or misspelled
```
				if (!ModContent.TryFind("VitalityMod/StormCloudBossBag", out ModItem StormCloudBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/GrandAntlionBossBag", out ModItem GrandAntlionBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/MoonlightDragonflyBossBag", out ModItem MoonlightDragonflyBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/DreadnaughtBossBag", out ModItem DreadnaughtBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/AnarchulesBeetleBossBag", out ModItem AnarchulesBeetleBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/AnarchulesBeetleCrimsonBossBag", out ModItem AnarchulesBeetleCrimsonBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/ChaosbringerBossBag", out ModItem ChaosbringerBossBag)) return; //VitalityMod
				if (!ModContent.TryFind("VitalityMod/PaladinSpiritBossBag", out ModItem PaladinSpiritBossBag)) return; //VitalityMod
```
