### ISSUE TITLE
[1.4] tModLoader won't open (No errors)

### ISSUE THREAD

**Issue by Satoshinshin** [bluemagic123/tModLoader#2603]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I try to launch TmodLoader witht steam a black screen opens, last for less than a second then won't open the game, I tried re-installing both Terraria and TML, even using the package here on GitHub, but it won't open.

On the log files, the last line just say "Launched Using Local Dotnet", but the game wont open and on the task manager doesn't appear anything.

### Log File

Verifying .NET....
Logging to D:/SteamLibrary/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
Success!
Verifying .NET platform specific libraries are correctly deployed
I'm on Windows, no need to do anything
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "D:/SteamLibrary/steamapps/common/tModLoader/dotnet/6.0.0"
Launched Using Local Dotnet

### Steps to reproduce

1. Click "PLAY" button on Steam
2. For less than a second says "Running" on Steam then closes
3. It stops then the green button to "PLAY" reapears on steam

### Expected Behavior

The game launching

### Actual Behavior

The game doesn't launch

### Reproduction frequency

Every time I try to open the 1.4 version of TML

**Comment by foics** [comment]
I had the same problem as you what fixed it for me was going back to the legacy 1.3 version then back to 1.4 and it worked

**Comment by Chicken-Bones** [comment]
Please come to Discord for support with launch issues.

**Comment by ThankYouQuill01** [comment]
have the same issue, and it seems to be an absolute pain to find a solution anywhere. i tried goin to the discord, however it seems the verification didnt go through on that and i have been stuck on the welcome page. and anywhere else i look says the same 4 things that i have tried and have failed. if you know the solution to this problem please tell me, its been like a week

**Comment by JavidPack** [comment]
A summary of potential fixes that we know of are all documented on the FAQ: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#black-windows-appears-and-closes-but-nothing-else

**Comment by Tomm2538** [comment]
> have the same issue, and it seems to be an absolute pain to find a solution anywhere. i tried goin to the discord, however it seems the verification didnt go through on that and i have been stuck on the welcome page. and anywhere else i look says the same 4 things that i have tried and have failed. if you know the solution to this problem please tell me, its been like a week

i had the same problem and i couldnt find a fix anywhere but what ended up working is going into the dotnet/6.0.0 folder and unchecking the "run as administrator" box in properties in the compatibility tab for the dotnet.exe, hope this works for you too

**Comment by ThankYouQuill01** [comment]
> i had the same problem and i couldnt find a fix anywhere but what ended up working is going into the dotnet/6.0.0 folder and unchecking the "run as administrator" box in properties in the compatibility tab for the dotnet.exe, hope this works for you too

bro, i thank you from the depths of my soul, this actually worked
