### ISSUE TITLE
Calamity wont work how do I fix this?

### ISSUE THREAD

**Issue by Metric2** [bluemagic123/tModLoader#2611]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

An error occurred while loading CalamityMod v2.0.0.2
It has been detected that this mod was built for tModLoader v2022.5.103.32
However, you are using tModLoader v2022.6.86.0 Preview a7c8a5d3, built 6/23/2022 12:48 PM
The mod(s) have been automatically disabled.

### Log File

![logs](https://user-images.githubusercontent.com/108136047/175545861-a5037c5a-69cd-4416-b634-269a644d21e7.PNG)

### Actual Behavior

I try and load the mod

### Reproduction frequency

quite frequently

**Comment by JavidPack** [comment]
You didn't include the log file. A picture of the log file won't do us any good.

**Comment by Chicken-Bones** [comment]
You're on preview. Switch back to the default (none) beta branch in steam
