### ISSUE TITLE
Swords that shoot have wrong rotation for 1 tick

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2613]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever you swing a sword to shoot a projectile, and the player changes direction because of it, it shows the sword in the wrong position (rotated roughly 180 degrees) for one tick from where it should be.

![Screenshot_5](https://user-images.githubusercontent.com/15894498/175613399-af14271e-6a7f-40b6-9314-1c05c472da41.png)

<details>
  <summary> >>>>>>VIDEOS (CLICK HERE)<<<<<<<<</summary>
  
A modded sword that doesn't shoot anything (proper behavior):
https://user-images.githubusercontent.com/15894498/175613136-ebf4c9aa-8d80-4997-9cd2-ff95cec25203.mp4

A modded sword that shoots something:

https://user-images.githubusercontent.com/15894498/175613273-ca87b5dd-e26e-4e9c-b9ae-3b7789f33cd0.mp4

A vanilla sword that shoots something (Ice Blade, on a cooldown):

https://user-images.githubusercontent.com/15894498/175613353-3e589a27-628c-4e22-9b68-7ee7c1496d63.mp4
  
</details>

### Log File

No

### Steps to reproduce

1. Get Ice Blade or Christmas Tree Sword
2. Either stand still, or run in one direction
3. Shoot (in case of ice blade, not every swing) in the opposite direction the player is facing
4. Observe

### Expected Behavior

No 1 tick glitched position

### Actual Behavior

1 tick glitched position

### Reproduction frequency

100% if the sword actually shoots things, it doesn't matter if it has `useTurn` true or not.

### Additional Information

This can be observed on modded swords that shoot. They don't behave like this when you return false in `CanShoot` though.

**Comment by VortexOfRainbows** [comment]
Unless I'm missing something, this is also something that happens in vanilla Terraria.
![image](https://user-images.githubusercontent.com/13910999/175757730-ea2c6877-e73c-4cac-bc19-5e049dc39def.png)

**Comment by JavidPack** [comment]
I've mentioned this to the Terraria devs, we shall see if they get to it. If not, we can probably fix this, but it would be best if it is fixed in Terraria too.

**Comment by Chicken-Bones** [comment]
I'm not sure whether some `ItemCheck_` code relies on the correct positioning of use/hold style, so I've opted for the safe approach of calling `ItemCheck_ApplyUseStyle` again after `ItemCheck_OwnerOnlyCode`. @JavidPack can forward-port this to tML

**Comment by JavidPack** [comment]
Fix needs more work. Fix would result in too many changes by modders. We also need more hooks to sufficiently delineate various effects modders are currently using UseStyle for.
