### ISSUE TITLE
Language pack don't work

### ISSUE THREAD

**Issue by Cyrillya** [bluemagic123/tModLoader#2615]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Language pack don't work at all

### Steps to reproduce

1. Enable a resource pack for modifying text
2. Get into the game and check it. The text has not changed.

### Expected Behavior

The text should be changed

### Actual Behavior

The text doen't change

**Comment by Cyrillya** [comment]
I solved the issue myself #2617

**Comment by MysticalPlane** [comment]
How did you solve your issue?

**Comment by Cyrillya** [comment]
> How did you solve your issue?

By committing a pr to tML which contains the code to fix the issue in tML itself

As a player, you can subscribe [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2800050107) and enable it in your game to fix the issue

**Comment by MysticalPlane** [comment]
Holy… thanks so much!

**Comment by MysticalPlane** [comment]
@Cyrillya If you're interested, can you make a mod that makes certain items, NPCs, events, etc. unobtainable (not appear in the game) for $100?

I will mention what to "remove" and what to change. It's for my personal playthrough.
