### ISSUE TITLE
Failed to load asset:"Fonts\Item_Stack"  

### ISSUE THREAD

**Issue by Grildner** [bluemagic123/tModLoader#2621]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I run the tml via steam,after the CMD window closed,the tml window pops up with a white screen.Then without seeing the loading screen,it crashes.
The Error Texts mainly are:
Failed to load asset:"Fonts\Item_Stack"   
ReLogic.Content.AssetLoadException: Asset could not be found: "Fonts\Item_Stack"
Integrity checked.  Terraria and tml are up to date.  No anti-virus software.  Has local dotnet 6.0.0.  The file Item_Stack exists.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8984222/client.log)

### Steps to reproduce

1.Run the tml via Steam
2.Crash.Everytime.

### Expected Behavior

The tml runs normally.It runs,loads,and then is able to play mods.

### Actual Behavior

TML just crashes right after the tml window is opened.I don't even see the loading screen.

### Reproduction frequency

Everytime.
Since 1.4 version tml was published.
I tried to open tml every time a new 1.4 version tml update came out,it crashed with same error.
I never saw the loading menu successfully. 

### Additional Information

This also happen in GOG version.
The 1.3 version never meets this error.

**Comment by Grildner** [comment]
![11114](https://user-images.githubusercontent.com/52600537/175765594-d0a58809-a6da-46c3-9d4f-554a4b1283cf.png)

The error text goes like this

**Comment by Grildner** [comment]
The cmd window goes like this

![dddd](https://user-images.githubusercontent.com/52600537/175765705-92990126-a7a1-4aa2-afce-b1911b4d08e4.png)

**Comment by ExterminatorX99** [comment]
Reinstall Terraria

**Comment by Grildner** [comment]
Reinstall doesn't work, yet the problem doesn't occur in v2022.06.96.4, the previous version where met with the error was v2022.05.Now my computer runs tModloader without any problems.

**Comment by Terrakatt** [comment]
yo new issue i tried opening the game after updating it from the undelux version from april fools to play with my friend but when i tried to open the game it happened that u guys are talking about with exactly the same things and sorry for not doing this in a fancy way

**Comment by JavidPack** [comment]
> yo new issue i tried opening the game after updating it from the undelux version from april fools to play with my friend but when i tried to open the game it happened that u guys are talking about with exactly the same things and sorry for not doing this in a fancy way

You'll need to switch back to normal Terraria to play tmodloader. If you have further issues please come to our discord for support.
