### ISSUE TITLE
Unable to setup linux server

### ISSUE THREAD

**Issue by SLDDL** [bluemagic123/tModLoader#2622]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Unable to setup linux server. Mod browser doesnt find steamcmd install and when mods are installed from files ( grab .tmod file from steamworkshop install folder on a windows computer ) the server aborts after loading.

https://imgur.com/aUhT1hK
https://imgur.com/UYpMMEF

### Steps to reproduce

install server on linux

**Comment by SLDDL** [comment]
[server.log](https://github.com/tModLoader/tModLoader/files/8984871/server.log)

**Comment by SLDDL** [comment]
the setup in dedicatedserverutils seems to work with steamcmd

**Comment by Falloira** [comment]
Also having this issue

**Comment by SLDDL** [comment]
removing craftable dev items fixed it
