### ISSUE TITLE
error: system io directory not found

### ISSUE THREAD

**Issue by Dreassil** [bluemagic123/tModLoader#2631]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Tmodloader doesnt even load after starting up. I reinstalled it couple times and nothing changed.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8986169/client.log)

![bruh](https://user-images.githubusercontent.com/92592354/175804465-4a1f9ce5-6d11-4756-8351-26801fa0bd5e.JPG)

### Steps to reproduce

1. Start Tmodloader

**Comment by direwolf420** [comment]
If you use or used tml64bit before, go to their discord/homepage for this
