### ISSUE TITLE
The chest in the Example Mod cannot be replaced normally

### ISSUE THREAD

**Issue by skywhale-zhi** [bluemagic123/tModLoader#2643]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I tried to replace the Example Chest with another original Chest, no Example Chest fell

### Steps to reproduce

1.Let's put down an example chest
2.Replace it with a wooden chest

### Expected Behavior

Example chest is replaced by wooden chest, and the replaced chest falls down

### Actual Behavior

The replacement was successful, but no example chest fell

### Reproduction frequency

always

### Additional Information

I don't know whether it was deliberately designed like this or something else. I found this problem when learning ExampleMod. Normal chests can be replaced normally. The chest in ExampleMod will not be returned after being replaced.

**Comment by direwolf420** [comment]
For anyone who implements this fix, looks like `WorldGen.KillTile_GetItemDrops`, the if block with `includeLargeObjectDrops` needs to include modded chests and dressers somehow (and NOT use `GetChestItemDrop/GetDresserItemDrop`, those methods only work for vanilla (and their callsites have a type check to not include modded types))

**Comment by skywhale-zhi** [comment]
Can you be more specific? I can't find what kind of method to use.

**Comment by direwolf420** [comment]
Did you figure out a solution?

**Comment by JavidPack** [comment]
This is still unsolved.
