### ISSUE TITLE
Multiplayer non-owning clients do not display UFO attack particles

### ISSUE THREAD

**Issue by Ouroel** [bluemagic123/tModLoader#2655]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

https://imgur.com/a/fttFqPA

### Steps to reproduce

start a client with start_tmodloader.bat
start another client in the same way

in the first client, host a server
in the second, join the server

summon ufo and any dummy-target

**Comment by gabehowe** [comment]
couldn't reproduce

**Comment by JavidPack** [comment]
Confirmed, confirmed in Terraria too, labeling as a vanilla bug

To clarify, the Xeno Staff minion attacks are mostly invisible. Some of the time dust trails appear but when they do they seem to be aiming towards a point past the enemy that is being attacked. (Not the martian saucer enemy, that was unrelated)

Vanilla:
![image](https://user-images.githubusercontent.com/4522492/190465930-d59ede4e-c4dc-41b1-9610-8fba1164fbae.png)

**Comment by JavidPack** [comment]
We've informed Terraria devs, closing
