### ISSUE TITLE
SceneEffectPriority is not used in Main.UpdateAudio_DecideOnTOWMusic()

### ISSUE THREAD

**Issue by DavidF-Dev** [bluemagic123/tModLoader#2656]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

``SceneEffectPriority`` is not taken into account for ``Main.UpdateAudio_DecideOnTOWMusic()``.

### Steps to reproduce

1. Use a ``ModSceneEffect`` to override the vanilla music.
2. Notice that the music IS overridden - as intended.
3. Switch to the Otherworld soundtrack.
4. Notice that the Otherworld soundtrack overrides the ``ModSceneEffect``, regardless of priority.

### Expected Behavior

The ``ModSceneEffect`` and ``SceneEffectPriority`` systems should also be used on the Otherworld soundtrack - just like the original soundtrack. The fact that it doesn't may prevent all mods that use the ``ModSceneEffect`` system from playing custom music.

### Actual Behavior

Looking at the source, the ``SceneEffectPriority`` system is used in ``Main.UpdateAudio_DecideOnNewMusic()``, but not in ``Main.UpdateAudio_DecideOnTOWMusic()``.

### Additional Information

Note: Toggle the Otherworld soundtrack by speaking to the Party Girl NPC after visiting the "drunk mode" seed at least once.

**Comment by Solxanich** [comment]
Addressed in #3161
