### ISSUE TITLE
tModLoader launches for 3 seconds and then closes if I use stable or preview but it launches in 1.3 legacy.

### ISSUE THREAD

**Issue by Biofraem** [bluemagic123/tModLoader#2658]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I press play in steam it shows like a command prompt and then it becomes blank and lastly closes. I really want to try 1.4 features with mods so I appreciate any help I can get.

### Log File

Verifying .NET....
Logging to C:/Program Files (x86)/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
Success!
Verifying .NET platform specific libraries are correctly deployed
I'm on Windows, no need to do anything
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "C:/Program Files (x86)/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
Launched Using Local Dotnet

### Steps to reproduce

Set Beta to 1.3 Legacy and launch
close it
Set Beta to 1.4 Stable and launch
bug appears

### Expected Behavior

I should be playing calamity with pylons and using a magic conch.

### Actual Behavior

Shows the command prompt with the stuff in log file turns blank then closes.

### Reproduction frequency

100% of the time.

### Additional Information

Launch 1.3 Legacy first and then swap to 1.4 preview and then swap to 1.4 stable.

**Comment by P-Ramos16** [comment]
MANAGED TO MAKE IT WORK:
-Delete Libraries folder (in steam files);
-Verify Integraty of game files;
-Start game.

Worked on my machine running manjaro with 5.15 kernel.
Good Luck!

**Comment by Chicken-Bones** [comment]
Discord is the place for support for these issues
