### ISSUE TITLE
food items not placing on plates (multiplayer issue)

### ISSUE THREAD

**Issue by nunfykon** [bluemagic123/tModLoader#2664]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to place a food item on a plate, the food item immediately is put back into my inventory. I would love to display food items, so this is a problem for me.

### Steps to reproduce

1. right click on a plate with a food item in your hotbar

### Expected Behavior

The food item should place on the plate, so ut is displayed.

### Actual Behavior

The food item does not place, and is simply put back in the user’s inventory

### Reproduction frequency

Every time

**Comment by gabehowe** [comment]
![Capture 2022-07-03 12_32_36](https://user-images.githubusercontent.com/31964173/177048816-e7fc8053-e061-4ee4-8352-cc4860f29f88.png)
food on plates

**Comment by nunfykon** [comment]
Through further testing, I’ve discovered that food places on plates just fine in singleplayer, but it does not work in Multiplayer
