### ISSUE TITLE
System.Runtime.InteropServices.SEHException(0x80004005): External component has thrown an exception On Linux

### ISSUE THREAD

**Issue by lorolol** [bluemagic123/tModLoader#2665]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After the most recent update the game has stopped launching at all. I've reinstalled everything, including xna framework.
Before the update it worked flawlessly when running with(? I don't quite remember if I needed proton to run or not) proton and now it's just completely broken. Another thing that I noticed change was that now whenever I try to launch a black terminal screen appears for a bit until the error pops up.
![image](https://user-images.githubusercontent.com/108548755/176970433-a0d01b5e-e7ee-435a-a1ab-3157dc3326c6.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9031751/client.log)

### Steps to reproduce

1. Update game
2. ???
3. broken

### Expected Behavior

Game launches and I am able to have fun

### Actual Behavior

Game doesn't launch and I am not able to have fun

### Reproduction frequency

100% of the time

### Additional Information

OS is Arch Linux and kernel is 5.18.7-arch1-1.
The kernel might be the culprit here, since it recently updated as well, but I don't want to install an older version of it before making sure it's not something else.

**Comment by Solxanich** [comment]
1) Don't use proton. 
2) Delete all files in the Install Folder - there is a Steam Bug where case sensitive file names don't get updated when Steam deploys its updates, the workaround is to delete all files and run 'verify files'
3) Try running again

**Comment by lorolol** [comment]
> 1. Don't use proton.
> 
>     2. Delete all files in the Install Folder - there is a Steam Bug where case sensitive file names don't get updated when Steam deploys its updates, the workaround is to delete all files and run 'verify files'
> 
>     3. Try running again

Somehow this worked, even though I had already done this earlier with no luck (not complaining lol). Thanks for helping
