### ISSUE TITLE
Vanilla Worldgen bug

### ISSUE THREAD

**Issue by YokujinKaze** [bluemagic123/tModLoader#2673]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

this bug is present in the vanilla version of terraria, affects tmod and might never be fixed

the world gen wont generate stalagmites that should be in bee hives

reference 1.3 with stalagmites:
https://media.discordapp.net/attachments/436261964017303553/993037414870306836/unknown.png

reference 1.4 both vanilla and tmod without stalagmites:
https://media.discordapp.net/attachments/436261964017303553/993037443043434596/unknown.png

**Comment by JavidPack** [comment]
I've received confirmation that this is a Terraria bug, and have communicated this bug with the Terraria team. I'll be closing this since it's up to them now. The hope is that this will be fixed in an upcoming release.
