### ISSUE TITLE
'projectile' does not exist in the current context

### ISSUE THREAD

**Issue by ohyesss** [bluemagic123/tModLoader#2675]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

the code i put in the part to define the projectile's properties won't compile due to the error (i made the code based off the "basic projectile page" https://github.com/tModLoader/tModLoader/wiki/Basic-Projectile )

### Log File

Terraria.ModLoader.Exceptions.BuildException: Compiling BabilUltraPack.dll failed with 7 errors and 0 warnings
Error: /home/da/.local/share/Terraria/tModLoader/../tModLoader/ModSources/BabilUltraPack/ThrownSawblade.cs(16,4): error CS0103: The name 'projectile' does not exist in the current context

**code:**
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace BabilUltraPack
{
	public class ThrownSawblade : ModProjectile
	{
		public override void SetStaticDefaults()
		{
			DisplayName.SetDefault("ThrownSawblade");
		}

		public override void SetDefaults()
		{
			projectile.arrow = true;
			projectile.width = 24;
			projectile.height = 24;
			projectile.aiStyle = 3;
			projectile.friendly = true;
			projectile.ranged = true;
			aiType = ProjectileID.WoodenArrowFriendly;
		}
	}
}

### Steps to reproduce

1. make a projectile in the structure i did
2. Compile it

### Expected Behavior

I expect the code to build without an error and for the projectile to work like an arrow

### Actual Behavior

i think maybe something might be in the wrong place or maybe the set defaults need to be in a different category

### Reproduction frequency

every time i try to build the code

**Comment by ohyesss** [comment]
btw im fairly certain it's a problem with the set defaults, as when i remove all of them i can build without it getting an error

**Comment by direwolf420** [comment]
You are using 1.3 code in 1.4. Read this: https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide
Next time, for mod coding related questions, please visit the discord https://tmodloader.net/discord

**Comment by ohyesss** [comment]
> You are using 1.3 code in 1.4. Read this: https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide Next time, for mod coding related questions, please visit the discord https://tmodloader.net/discord

oh wait i forgot to capitalize the lines whoops (also thanks)
