### ISSUE TITLE
tModLoader says it is in v2022.6.96.4. However, it seems some mods which should've been uploaded to 1.4 tModLoader aren't working, saying they're in a previous version.

### ISSUE THREAD

**Issue by Aletom99** [bluemagic123/tModLoader#2677]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I was trying to run mods, but when I tried to reload Calamity 1.4, it keeps coming up with the same problem: It says tModLoader is in v2022.6.96.4, and that the mod was built for tModLoader v2022.5.103.32. It also does this with Fargo's Mutant Mod, but not all mods. Is there a way to fix this? Neither of the mods have any updates pending, and none of the betas for tModLoader helps.
![Uploading Screenshot (4).png…]()

### Log File

[Uploading client.log…]()

### Steps to reproduce

1. Launch tModLoader on the latest version.
2. Attempt to run the Calamity Mod
3. Wait for it to load, and the box of text saying the mod could not be run will appear.

### Expected Behavior

I don't know where this problem came from. It was working for a couple of days, and then just stopped. It should just run the Calamity mod as per usual.

### Actual Behavior

It keeps popping up with the text saying tModLoader is in v2022.1.6.96.4, and that the mod was built for tModLoader v2022.5.103.32. It then asks me to skip loading mods, or continue loading mods without Calamity.

### Reproduction frequency

Every time I try to run Calamity or Fargo's, the same problem happens.

**Comment by direwolf420** [comment]
Please re-upload the screenshots and the log, they self-reference this issue currently.
Also if your mods appear with a purple background instead of blue in the mods list, delete them.

**Comment by Calebkrzak** [comment]
I had the same problem with Calamity recently, and I found that by deleting the mod, restarting TModLoader, and re-downloading the mod fixes it. I don't know if its temporary as I just started experimenting ways to fix it, but all I know is that it works.

**Comment by Chicken-Bones** [comment]
Calamity has updated
