### ISSUE TITLE
tModLoader 1.3.5.3 and 1.4 issue; 'Load failed! No backup found' when world was literally just generated

### ISSUE THREAD

**Issue by RealZyther** [bluemagic123/tModLoader#2679]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I and many others have been having the same issue for quite some time now, and none of us have found a fix.
The issue is 'Load failed! No backup found' and this isn't just a case of a corrupted world, the world is literally corrupt on the world make like you literally just made the world and the world won't work and I am not sure what to do, I used to play 1.3 a lot but ever since 1.4 came out in alpha, it's the only thing I've been playing, I changed literally no mods, no updates, nothing, and now this happens with everything
(The Error) (https://user-images.githubusercontent.com/86556103/177059092-3510a262-a658-4b85-847a-1b788037daa5.png)
When I checked in terra map earlier, this was the issue
https://hst.sh/egujixuzen.cpp
(No .bak files?) (https://user-images.githubusercontent.com/86556103/177059103-02c0d262-e2eb-42fc-b9f7-932823c64675.png)
When I checked the worlds folder, there were no .bak files created
I looked in Backups and the latest backup I had was from a playthrough I started a month ago, and never ended up going past hardmode
(No Backup in Backups either) (https://user-images.githubusercontent.com/86556103/177059114-4bb5cefd-a367-4ccb-99fa-e6b6facab7e1.png)
This is the mod list; https://hst.sh/qigepunise.json
This issue happens in both 32-bit, so I'll just be using 64-bit so that everything is faster and easier.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9035585/client.log)

### Steps to reproduce

1. Open tModloader
2. Wait for mods to load
3. Create a character or use a character you have
4. Make a world
5. Attempt to Load world
6. Receive error
7. Go to tModLoader #support and wait for several hours and get no response
8. Go to Github

### Expected Behavior

I think that a Archery.wld.bak and an Archery.twld.bak file should be created.

### Actual Behavior

There are no .bak files being made

### Reproduction frequency

Literally anytime, it always happens and prevents me from doing a playthrough

### Additional Information

Perhaps the mod list? I don't think it's related to the mods since these are the same mods I've had for like 6 months (I stopped playing 1.3 3 months ago and I came back yesterday, but I've been unable to play, I've literally not updated or changed any of the mods) https://hst.sh/qigepunise.json

**Comment by RealZyther** [comment]
This issue happens to a lot of other people too (bicky#7477, ExplosiveFlare#4881, Jumped Shark#4978, DoctorDalekProd.#3935, sTier ♡#1145, and smecherul003#3113) some being 1.4 and some being 1.3, so I'm not entirely sure what the issue is, and I don't think the issue is related to a mod but it might be.

**Comment by RealZyther** [comment]
Hi there, I went to the tModLoader64bit discord and they read through my logs and told me what the issue was, it was a mod that recently became unstable (due to 0.11.8.9) due to the fact it's "as for your specific error, it's trying to load "bass.dll" which isn't one of our files and isn't a tmodloader file, it shouldn't be in the folder to begin with and it comes from "crit sound effects" mod"

I let everyone else who is having the issue know about the fix.

**Comment by Sajmon815** [comment]
Hello, i just encountered the issue on the on: TModLoader v2022 9.47.47
![skill_issue](https://github.com/tModLoader/tModLoader/assets/133050443/2839833e-d73f-4cc9-b666-051ce34f8bff)

**Comment by JavidPack** [comment]
@Sajmon815 you should make your own issue with logs and the world files, if you want help and are certain that it is a tmodloader issue, not a mod issue. Make sure your error happens with 0 mods enabled. If it doesn't happen with 0 mods enabled, see which mod causes it and get into contact with the mod author to fix their mod.

**Comment by Sajmon815** [comment]
@JavidPack The issue is with Calamity difficulty buttons and i saw a lot of comments on the steam that the issue is occuring so i think creators are aware abound bug. Thanks for help :)
