### ISSUE TITLE
windows_nt help fix

### ISSUE THREAD

**Issue by lizardhead** [bluemagic123/tModLoader#2683]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![2022-06-23 (3)](https://user-images.githubusercontent.com/108688088/177197209-074d0f49-2d21-4934-9ef5-b55a33e3f08b.png)
help its bothered me for so long

### Log File

![Uploading 2022-06-23 (3).png…]()

### Steps to reproduce

1 i open it
2 it comes up with windows_nt issue
3 it crashes, or something???

### Expected Behavior

it opens

### Actual Behavior

it crashes

### Reproduction frequency

it happens alot

### Additional Information

dffsfsfsffsf

**Comment by Chicken-Bones** [comment]
Please come to the discord for support.
