### ISSUE TITLE
[Multiplayer] Dropped items vanishing when picked up

### ISSUE THREAD

**Issue by Wyrdean** [bluemagic123/tModLoader#2686]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When items are dropped, they often don't appear again when picked up by another, or the same player.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9042761/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/9042762/server.log)

### Steps to reproduce

1. Create a multiplayer game
2. Drop Item (As an example, starting pickaxe)
3. Either pick it up yourself (Other players not required for issue) or have someone else pick it up
4. Notice lack of item in your inventory

### Expected Behavior

You should be able to pick up dropped items

### Actual Behavior

Not getting items you dropped back

### Reproduction frequency

95%, and I've created extra worlds, and tested without mods enabled as seen in the logs

### Additional Information

Happens most often with "complex" items, such as tools, weapons, furniture items like chests or doors, etc
In addition, it seems to happen with items from boss or modded bags 
But not items such as blocks or potions

**Comment by JavidPack** [comment]
No hints in the logs, you'll have to do trial and error testing yourself to figure out which mod is causing this. I'd recommend testing on a new world, new player. By trial and error I mean disable mods to determine the mod at fault.

**Comment by Wyrdean** [comment]
As stated in the reproduction frequency section I've tested without mods, I can continue testing, but so far I've been able to repeat it every single time.

**Comment by JavidPack** [comment]
Your logs do not show testing without mods. Make sure to get a clean log file by restarting the client after disabling all mods. We can look at those clean logs if it persists

**Comment by Wyrdean** [comment]
After extensive testing, and I do mean extensive, I have isolated the cause to the "upgraded research" mod
