### ISSUE TITLE
[1.4 Linux Server] headless server not starting/working

### ISSUE THREAD

**Issue by Luka3006** [bluemagic123/tModLoader#2688]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When i try to host a headless linux server with the latest tModLoader version it crashes everytime.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9047152/client.log)

### Steps to reproduce

1. install the server:
tml=`curl -s https://api.github.com/repos/tModLoader/tModLoader/releases/latest | jq -r '.assets | map(select(.name == "tModLoader.zip" )) | .[].browser_download_url'`
wget $tml
mkdir tModLoader
unzip tModLoader.zip -d tModLoader
chmod +x tModLoader/*.sh tModLoader/LaunchUtils/*.sh
rm tModLoader.zip

2. Run server:
./start-tModLoader.sh -steam -config serverconfig.txt

3. Main engine crashes

### Expected Behavior

Server starts

### Actual Behavior

Main engine crash or local net dot "no permission error" and wild blinking in the terminal afterwards

### Reproduction frequency

every time i try to start the server

### Additional Information

[serverconfig.txt](https://github.com/tModLoader/tModLoader/files/9047168/serverconfig.txt)
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/9047169/client-crashlog.txt)

**Comment by Chicken-Bones** [comment]
Try 1.4-preview! You can get it via steam beta, or https://github.com/tModLoader/tModLoader/actions/runs/2618482194

**Comment by Luka3006** [comment]
> Try 1.4-preview! You can get it via steam beta, or https://github.com/tModLoader/tModLoader/actions/runs/2618482194

Wow, the server actually starts!
But how does the mod browser steam workshop access works? It says:

> ERROR: Error: Unable to access Steam Workshop.
> You must have a valid Steam install on your system in order to use the in-game Mod Browser.

steamcmd is installed in /usr/games/steamcmd and i created a link in the server directory:
`ln -s /usr/games/steamcmd steamcmd`


When i type "y" for steam support on startup, the server crashes after "Using local dotnet" without any log entries

**Comment by Chicken-Bones** [comment]
There's some instructions in the DedicatedServerUtils folder, aside from that, come to the Discord for more help.

I don't actually know if steamcmd works on linux. I suggest you copy the mods across to the server manually for now.

**Comment by Solxanich** [comment]
FYI folks, I've updated the server setup guide around this question, based on someone else's experience. Thanks
https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server

**Comment by Luka3006** [comment]
> FYI folks, I've updated the server setup guide around this question, based on someone else's experience. Thanks https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server

thanks for the update! But the headless start doesn't work for me. with the start-tModLoaderServer.sh everything is fine, but when i start headless with ./start-tModLoader.sh -server  -config serverconfig.txt -lobby friends
this is the output:
[https://gyazo.com/a00a61a6cea26f6a0228e2d3a2d2ef4b](https://gyazo.com/a00a61a6cea26f6a0228e2d3a2d2ef4b)
Log is attached:
[server.log](https://github.com/tModLoader/tModLoader/files/9050187/server.log)
