### ISSUE TITLE
Wont launch after small command window?

### ISSUE THREAD

**Issue by Goose1602** [bluemagic123/tModLoader#2690]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I havetn played in about a year and after trying to play recently this issue keeps blocking me. Whenever set to launch a black command prompt window pops up, runs a small command and dissapears. However Tmodloader doesn't launch and steam says its not running at all. I have never had this problem

### Log File

Windows Version 10.0
Quick Edit Disabled
Verifying .NET....
Logging to C:/Program Files (x86)/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
mv: can't rename 'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET': Permission denied
'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET' -> 'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/steamworks.net/Steamworks.NET'
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "C:/Program Files (x86)/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
Launched Using Local Dotnet

### Steps to reproduce

1. Install Tmodloader
2. Launch

### Expected Behavior

Launch program

### Actual Behavior

command window disappears and Tmodloader does not launch

### Reproduction frequency

Reproduced at every trial without fail

**Comment by Chicken-Bones** [comment]
Please come to the #support channel in Discord and read the pinned flowchart for help with issues like these.
