### ISSUE TITLE
The search does not work and the text comes out

### ISSUE THREAD

**Issue by V8ST8K** [bluemagic123/tModLoader#2695]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

 The text gets out of the interface, and the search does not work! Huawei laptop device.
![Screenshot_15](https://user-images.githubusercontent.com/85753549/177635512-6f43c2f1-a93a-4d7d-b1c4-e77c9ce293f7.png)
k

**Comment by JavidPack** [comment]
We'll need to dynamically resize this UIText, I think
