### ISSUE TITLE
Client crashing when entering Mod Packs menu

### ISSUE THREAD

**Issue by AbzZero** [bluemagic123/tModLoader#2701]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I attempt to enter the modpack menu and the game crashes, usually after entering it and exiting the menu at least once. It sometimes crashes on the first attempt.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9072470/client.log)
[client_1.log](https://github.com/tModLoader/tModLoader/files/9072472/client_1.log)
[client_2.log](https://github.com/tModLoader/tModLoader/files/9072473/client_2.log)
[client_3.log](https://github.com/tModLoader/tModLoader/files/9072536/client_3.log)

### Steps to reproduce

1. Load the game with no mods (it happens either way)
2. Go to Workshop -> Mod Packs
3. Enter and exit the Mod Packs menu until it crashes. (For me, crashes commonly on the 2nd/3rd attempt)

### Actual Behavior

The game proceeds to crash with more or less the same error message and logs.

### Reproduction frequency

100% so far

**Comment by JavidPack** [comment]
A similar issue happens on the download mods menu, probably a similar issue with a separate thread removing the UILoaderAnimatedImage causing this exception

![unknown (10)](https://user-images.githubusercontent.com/4522492/189477736-88d800c5-4902-4680-9647-5789823b475d.png)

**Comment by JavidPack** [comment]
This crash is unrelated to the fix.
