### ISSUE TITLE
item splitting issues when using weapons/items having m2 skills

### ISSUE THREAD

**Issue by YokujinKaze** [bluemagic123/tModLoader#2702]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

unable to split items if holding items like weapons that use m2 (in this case a calamity weapon that uses m2 to charge) 

example:
https://gyazo.com/bf6de0e6761a210f0a3c90e92b48c224

disclaimer: not sure if vanilla/tml or calamity bug

### Expected Behavior

when inventory is open and clicking on an item it should activate weapon skills

**Comment by JavidPack** [comment]
We should check vanilla weapons that have right click functionality to determine if this should be fixed or is intended.

**Comment by Chicken-Bones** [comment]
No issues with Tome of Infinite Wisdom. @Ozzatron to determine if this is a Calamity bug, or tML deficiency. Possibly not replicable anymore in 1.4.4

**Comment by Ozzatron** [comment]
Unquestionably a Calamity bug with the right click listener. Holding certain Calamity weapons that need to be able to detect holding RMB enables an input handler; this handler will mindlessly consume all right mouse button input events, preventing them from propagating to GUI.
