### ISSUE TITLE
It doesn't work with Windows 11

### ISSUE THREAD

**Issue by TheFrog1888** [bluemagic123/tModLoader#2708]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When we lauch tMod Loader, there is a cmd that open, quickly close, then nothing happens.

### Reproduction frequency

Always

### Additional Information

It worked before the 1.4 release, but I was on Windows 10.

**Comment by Chicken-Bones** [comment]
Please come to the discord for support issues like this. Make sure to read the pinned flowchart in #support.
