### ISSUE TITLE
Crash on DotNet startup screen, Found a startling issue in code

### ISSUE THREAD

**Issue by Slotherak** [bluemagic123/tModLoader#2710]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After selecting the game and clicking RUN in steam overlay, the game begins loading and inexplicably quits. Searching through the logs presented me with the issue: something is missing from my library in the ReLogic folder. "ReLogic.OS.IPathService". Sounds rather important to have as it triggered a fatal crash before the game even loaded...

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9097475/client.log)

### Steps to reproduce

1. Select TModLoader on steam.
2. Click RUN button to start the program.
3. Wait.

### Expected Behavior

Game loads, fun and terror begins.

### Actual Behavior

blackbox program loads up, blinks twice, saying "Loading from local DOTNET" on second appearance, and then unexpectedly quits without error notification. That window is supposed to stay open, I thought.

### Reproduction frequency

Every. Single. Time.

### Additional Information

I have double- and triple-checked my antivirus settings, Terraria install, game file integrity, minimum requirements, and so on. I only just now found the log file entry stating the issue in black and white: 

[18:57:37] [Main Thread/FATAL] [Terraria]: Failed to Handle Save Data
System.TypeLoadException: Could not load type 'ReLogic.OS.IPathService' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Terraria.Program.SetSavePath()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185

unfortunately, I am not qualified to write in this "type", as I don't even know its parameters.

**Comment by Slotherak** [comment]
Woops, wrong button. Anyways, been testing various "fixes", but I'm still unable to get past that error. 1.4, 1.4 alpha, 1.3, they are all unable to run. Delete the ReLogic library folder and reinstall, nothing. Delete the whole program, and reinstall, still nothing. This is really starting to get under my skin. I am a programmer, I should be able to get this to work...

**Comment by VNLoverMay** [comment]
Don't have much to add other than I've encountered this exact same error, on windows 10, so it's more than one instance.

**Comment by VNLoverMay** [comment]
Deleting Rrelogic.dll in the tmodloader folder seemed to fix this? I suggest trying that.

**Comment by Slotherak** [comment]
Success! Rrelogic.dll was the problem! Thanks, greggbot!

**Comment by Dreamer3-3** [comment]
i am sorry, but where EXACTLY is this .dll file?

**Comment by JavidPack** [comment]
The ReLogic.dll file mentioned here is in the install folder nested under "\Libraries\ReLogic\1.0.0\ReLogic.dll". The install folder can be found via by following the instructions: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install

Deleting the file shouldn't actually help if you installed correctly, if you are having an issue please come to our Discord, that is where we provide support: https://discord.gg/tmodloader
