### ISSUE TITLE
Info icons being "squished"

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#2711]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![image](https://user-images.githubusercontent.com/65787578/178655102-c4528609-b420-4322-8efe-511c7df67b06.png)

See the squished text? In my opinion, it should be not squished, because otherwise it makes text harder to read. This is more of a vanilla thing, but I think it should be fixed.

### Expected Behavior

Not being squished, and maybe text could go on line below, similarly how npc chat text box ui does.

### Actual Behavior

Text inside info icon is being squished.

### Reproduction frequency

Always, if text is way too long.

**Comment by JavidPack** [comment]
I'll test, if this happens on vanilla, we'll close since that is the intention.

**Comment by JavidPack** [comment]
I've confirmed that this happens on Terraria as well. I'm not seeing this as a bug, since it seems intentional. It would cause a lot of issues with UI layout if these occupied multiple lines.
