### ISSUE TITLE
Give us the ability to choose between .tmod or workshop

### ISSUE THREAD

**Issue by Da-nu** [bluemagic123/tModLoader#2714]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I am trying to make a mod and have already published it to the workshop. I am hosting a server for me and my friends to play and due to me having a .tmod version of my mod and them having the workshop version they cant join. What I am asking for is a choice to pick between using the workshop .tmod or local .tmod file if tmodloader detects that there is both a local and workshop .tmod with the same mod name installed.

### What does this proposal attempt to solve or improve?

This would make it easier for mod developers to be able to have an easier time playing multiplayer with their own mod with other people.

**Comment by Chicken-Bones** [comment]
Try 1.4-preview, it should work again. `You can also use -tmlsavedirectory path` when launching the game to play with friends to point to another save folder that doesn't have your development stuff in it

**Comment by JavidPack** [comment]
The recent reworks should address this issue. Multiplayer clients will download mods that differ. Depending on the version number differences, users might want to consider a local modpack if necessary.
