### ISSUE TITLE
start-tModLoader.bat installing "Netsupport" RAT (client32.exe). Please Confirm!?!

### ISSUE THREAD

**Issue by seeu3** [bluemagic123/tModLoader#2715]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Fair warning, this could be a false positive. Please confirm.
Hadn't played in a while.
1) I updated terraria from steam.
2) I installed tmodloader from steam and at one point downloaded tModLoader.Windows.v0.11.8.9.zip from:
https://github.com/tModLoader/tModLoader/releases/download/v0.11.8.9/tModLoader.Windows.v0.11.8.9.zip

during batch-file install, I had to let powershell and curl.exe through the firewall...
Doing so also installed NetSupport remote control software. (client32.exe)
This also installed a shortcut link inside Startup Folder called "autorunns.ini" which pointed to client32.exe.
Again, could be a false positive, but the timestamps of the prefetch files for the tmodloader.exe and client32.exe match up. So unless powershell or curl were hacked before this install? 

Ini file of client32.exe pointed to two control servers:
aeriarnwly14.com (registered in russia a few days ago to IP 185.230.143.110
aeriarnwly15.com (not yet registered)

someone plz confirm?
if false positive plz delete.

### Steps to reproduce

1. run start-tmodloader.bat during fresh install.
2. does client32.exe appear on the computer? (use search everything to confirm)

### Expected Behavior

tmodloader installs WITHOUT NetSupport RAT

### Actual Behavior

tmodloader installs WITH NetSupport RAT

### Reproduction frequency

once. didn't want to try for two. but i DID verifiy timestamps on client32.exe and tmodloader files (matched within seconds)

### Additional Information

again, sorry if false positive, but seemed legit.

**Comment by JavidPack** [comment]
If you installed from steam, I'm not sure why you manually downloaded tmodloader zips. The timeframe of your issue coincides with the timeframe where someone maliciously edited some links on the wiki to point to a similar looking url that was presumably malicious. If you found the manual install link from the wiki, that might explain how this happened. 

For the record, just install 1.3 tmodloader through the steam betas menu.

If I were you, I'd clear out all of the things that did, we don't install anything with the 1.3 tmodloader install, it should just work. The bat file just launches the game, it doesn't download anything. Clear out the install dir too and install again through steam.

**Comment by achillesmitchill-lgtm** [comment]
hey guys I am trying to save my terraria progress can you give me advice?
