### ISSUE TITLE
Title theme changes from "tmodloader" to "1.3" when you grab the sun with your mouse cursor

### ISSUE THREAD

**Issue by EpicOweo** [bluemagic123/tModLoader#2719]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Clicking on the sun on the main menu changes the title theme from tmodloader to 1.3.5.3

### Steps to reproduce

1. run game
2. click on the sun at any point without changing the theme

### Expected Behavior

the theme should not change

### Actual Behavior

the theme is changing

### Reproduction frequency

every time the game is reloaded

**Comment by direwolf420** [comment]
From what I know, this is intended

**Comment by ufgf** [comment]
additional info about issue: occurs only when loading mods

**Comment by Mirsario** [comment]
This is an intended vanilla feature.
