### ISSUE TITLE
Hooking IL.Player.PlaceThing_Tiles_PlaceIt breaks original method

### ISSUE THREAD

**Issue by dhozou** [bluemagic123/tModLoader#2724]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Hooking `IL.Player.PlaceThing_Tiles_PlaceIt` causes calls to `Player.PlaceThing_Tiles_PlaceIt` to throw `System.NullReferenceException`, even without IL modification.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9126875/client.log)

### Steps to reproduce

1. Create, build, and load a new mod with the attached example code.
2. Enter a world and attempt to place a tile.

### Expected Behavior

The tile is placed as normal.

### Actual Behavior

The tile is not placed and the error `Object reference not set to an instance of an object. (see client.log for full trace)` is printed in chat.

### Reproduction frequency

100% reliably.

### Additional Information

```csharp
using Terraria.ModLoader;

namespace ModName {
	public class ModName : Mod {
		public override void Load() {
			IL.Terraria.Player.PlaceThing_Tiles_PlaceIt += _ => { };
		}
	}
}
```

**Comment by SanAndreaP** [comment]
I have the same issue with a mod that uses the hook: https://github.com/TheLuxure/AltLibrary/issues/8

**Comment by JavidPack** [comment]
Tested on v2023.8.3.4 today, no errors. Seems to have fixed itself as a result of monomod updates over the recent months.
