### ISSUE TITLE
tModLoader crashing on launch

### ISSUE THREAD

**Issue by Ccrafter707** [bluemagic123/tModLoader#2730]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

tModLoader attempts to launch, showing the black window that would normally be followed by the ReLogic screen, but then fails before it is rendered, with a crash log reading that the file "Images/Extras_241" is missing. Uninstalling all mods did not help. Files have been verified multiple times, and the game is not being blocked by firewall.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9136643/client.log)

### Steps to reproduce

Unknown.

### Expected Behavior

The game should be launching as normal.

### Actual Behavior

The game crashes before loading the ReLogic screen,

### Reproduction frequency

100% as of the first occurance.

### Additional Information

No additional mods were installed and none were uninstalled before launching. The computer had been restarted and kept signed out for three days, and only after then did the game no longer successfully launch. The computer has a 600w power supply that is nearing the end of its usability, although the only problems it has posed so far is in crashing when running certain resource intensive games.

**Comment by Chicken-Bones** [comment]
Please come to the Discord #support channel for issues like this. Make sure to read the pinned posts there.
