### ISSUE TITLE
very strange error when running TModLoader.exe

### ISSUE THREAD

**Issue by MatrasFigurov** [bluemagic123/tModLoader#2736]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When I try to launch TML, the game itself does not start, but the TML installation window in steam opens. By the way, the install button does not work. I have GOG version.

**Comment by Chicken-Bones** [comment]
Please come to the discord #support channel for issues like this. Make sure to read the pinned posts.
