### ISSUE TITLE
crash from System.AccessViolationException on close

### ISSUE THREAD

**Issue by Tyfyter** [bluemagic123/tModLoader#2739]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I try to close the game, it crashes and won't fully close without using task manager or the Visual Studio "Stop Debugging" button

### Log File

[Natives.log](https://github.com/tModLoader/tModLoader/files/9156225/Natives.log)

### Steps to reproduce

1. Open the game
2. Close the game

### Additional Information

[DxDiag.txt](https://github.com/tModLoader/tModLoader/files/9156237/DxDiag.txt)

**Comment by Chicken-Bones** [comment]
Fixed in af3f3c949ebed839a9326d3167c814b14e9ca2b7
