### ISSUE TITLE
Grab Bags not assigned to Boss NPCs can be opened infinitely every frame when holding right click.

### ISSUE THREAD

**Issue by VortexOfRainbows** [bluemagic123/tModLoader#2745]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Opening Grab Bag items, such as crates, can be done infinitely. All you need to do is hold right click instead of tap it.
However, this does not affect boss bags if `public override int BossBagNPC` is set to something.

### Log File

N/A

### Steps to reproduce

1. Download Example Mod
2. Attempt opening the crate by holding right click, then attempt opening the boss bag by holding right click.
3. Watch how the crate spams items everywhere. You can even do this with a stack size of 1, as long as you hold right click before hovering over it.
4. If you set a boss bag to not have an NPC assigned to it, then it will break as well.

### Expected Behavior

The crate should open in the same way boss bags assigned to NPCs do.

### Actual Behavior

Crates spam items everywhere without being consumed.

### Reproduction frequency

I was able to reproduce it with example mod and my own mod. And I was able to stop it by assigning a boss bag npc.

### Additional Information

![e5fba97ceabd7c724ec61109923811b5](https://user-images.githubusercontent.com/13910999/180334362-383644ed-0912-4a24-aca7-56bf41861b34.gif)

Same thing happens with Example Mod Fishing Crate.

**Comment by Chicken-Bones** [comment]
Should be fixed in #2742

**Comment by VortexOfRainbows** [comment]
Confirmed. It is now fixed
