### ISSUE TITLE
Grab Bags don't work in Multiplayer.

### ISSUE THREAD

**Issue by VortexOfRainbows** [bluemagic123/tModLoader#2753]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Grab Bags give no loot on Multiplayer worlds, even though they work fine on singleplayer worlds. This is with the new system.

### Log File

N/A

### Steps to reproduce

1. Open treasure bag on singleplayer world. Watch as it gives items.
2. Open treasure bag on multiplayer world. Watch as it disappear and scam you.

### Expected Behavior

It should be giving you items in both modes.

### Actual Behavior

Multiplayer worlds do not give items.

### Reproduction frequency

The issue is reproducible with both Vanilla crates and treasure bags, as well as modded ones. 

### Additional Information

![3ddb7260ad2e2c1b3cf6f69b7f8ea171](https://user-images.githubusercontent.com/13910999/180628667-b285914b-1129-45fd-b2b1-4b123f8229ce.gif)

The only thing that drops properly is developer items.

**Comment by Chicken-Bones** [comment]
Fixed in #2751
