### ISSUE TITLE
Problem with the autogenerated key {NPCName}

### ISSUE THREAD

**Issue by Brutaliaa** [bluemagic123/tModLoader#2755]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When using the autogenerated key {NPCName}, it gets the full name + the title of the NPC.

Example : LikeNPC: "{NPCName} is a cool person!" --> In-game will be : Andrew the guide is a cool person!

I asked on the modding-help and Glasses-san tells me to make an issue here for that, because it should only take the NPC name, not the NPC name + the title.

### Expected Behavior

Show the NPC name without its title when talking to a NPC

### Actual Behavior

Showing the full thing (NPC name + title)

**Comment by nullapple** [comment]
Assuming that you're adding a string to `GetChat()` using `chat.Add()`, this is what it should look like: 
![image](https://user-images.githubusercontent.com/89311561/183881713-9aaa521a-f88a-40e6-9463-65fa35063ea5.png)
I can't reproduce the bug as I don't know precisely how you're adding dialogues to NPCs. Perhaps you're not using npc.GivenName to pass through the argument for NPCName?

**Comment by Brutaliaa** [comment]
I didn't say where I did it, my bad.

It's in the en-US.hjson in Localization, the autogenerated keys {NPCName}
`TravellingMerchant:
			{
				Content: Hey! Are you searching for goods today?
				NoHome: I'd like to have a home, too, you know :(
				LoveSpace: Aaah, lot of space! Now, I can think about my buisiness! 
				FarFromHome: Help! I can't find my way back home. Please, guide me back.
				DislikeCrowded: Seems like there are a little too much customers here, huh?
				HateCrowded: Well, I have a limited stock... I can't support all of you guys, give me space...
				LoveNPC: Oh, there's {NPCName}... Oh no, am I blushing again?
				LikeNPC: "{NPCName} has a good merchant soul. I like that!"
				HateNPC: Please, can I just live without {NPCName} near me? He's stealing my life savings...
				LoveBiome: Aaah, the Forest... Relax and peaceful place to live, as well of lots of customers!
				LikeBiome: Yea, desert is cool. Love the scenery here and... Oh, a customer!
				HateBiome: Also, I have a question... What do you want me to do here... Seriously, it's just too dangerous and nobody will buy my stuff. I just hate this place.
			}`
			
Right here

**Comment by JavidPack** [comment]
I did some testing on Terraria 1.4.4.9 and it seems that this is the intended behavior.
