### ISSUE TITLE
Main Engine Crash

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2757]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I was fighting a boss and my game crashed.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9180115/client.log)

### Additional Information

I don't know if it's because of Terraria Overhaul, but it crashes often.

**Comment by JavidPack** [comment]
This issue tracker is for tModLoader, not individual mods. If you can confirm this issue happens without any mods enabled, please post a new log file and re-open this ticket.
