### ISSUE TITLE
Vanilla Grab Bags open twice

### ISSUE THREAD

**Issue by CharizUniv** [bluemagic123/tModLoader#2761]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

As of the #2751 fix, all vanilla grab bags are now opened twice in one click

Also, if you only have 1 of the grab bag then it gives you the loot that you've gained from opening 2

This does not apply to modded grab bags

### Steps to reproduce

1. Get 1 or more vanilla grab bags
2. Right click said grab bag
3. You'll open 2 bags at once and get the loot from both (even if you only have 1)

**Comment by Chicken-Bones** [comment]
Fixed in #2764
