### ISSUE TITLE
Filter mods list for mods with modconfig configs

### ISSUE THREAD

**Issue by Xetaxheb** [bluemagic123/tModLoader#2762]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Essentially another button or hidden inside mod-sidedness filter button, a filter for mods that have the gear that leads to config.

### What does this proposal attempt to solve or improve?

Making it easier to go through configs quickly with lots of mods installed, and reducing the incidence of scrolling past one by mistake.

### Which (other) solutions should be considered?

Putting as an option in all/enabled/disabled filter could make more sense because if a mod has the gear than by necessity it is **_loaded_**, though that doesn't always mean it is **_enabled_**.  This 'edge case' (disabling mods as you go through configuring) will probably in practice crop up way more than someone wanting to filter simultaneously for gear and for mod-sidedness, even though at face value it may seem more valuable to be able to filter sidedness and configurability... so I don't know which solution is better. 
Adding a 4th button adds more clutter to the UI, obviously. I don't think putting it under sorting is a good choice, because it can be desirable to sort alphabetically or by recent changes.

**Comment by JavidPack** [comment]
This has been addressed by now. In current tmodloader, all mods with configs are easily accessible within the Mod Configuration menu
