### ISSUE TITLE
In-game mod configuration menu does not show up

### ISSUE THREAD

**Issue by Ryanisnotacat** [bluemagic123/tModLoader#2765]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In the manage mods menu, some mods allow configuring their settings, and the ability to configure mod settings shows up as a gear icon next to the mod information button. On Linux (or at least Ubuntu) this gear icon does not show up, preventing mods from being configured in game.
![Screenshot from 2022-07-26 15-13-02](https://user-images.githubusercontent.com/91003335/181121381-a1a93193-52cf-4aa5-ad92-3d1ca9f6bf0d.png)
.
For example, these two mods should be configurable, however the configuration icon does not appear.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9193653/client.log)

**Comment by Chicken-Bones** [comment]
Mods must be enabled and loaded for their configs to appear.

**Comment by Ryanisnotacat** [comment]
Oh

Well I am an idiot lol.
Thank you for helping.
