### ISSUE TITLE
Bestiary additional empty page

### ISSUE THREAD

**Issue by Auuki** [bluemagic123/tModLoader#2770]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Bestiary has additional empty page at the end. If there's 500 entries, there will be an additional page 500-500 that is empty. It shows up on pure tml as well as with mods and filters. It does not occur in vanilla.

### Steps to reproduce

1. Open Bestiary
2. Scroll to the end of the list

### Expected Behavior

You're on the last page

### Actual Behavior

You're on an empty page past last page

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
Some code in https://github.com/tModLoader/tModLoader/pull/1063/commits/9632957ed29c8852ff053090155f854f60127eb6 was causing this, I reverted it since the reasoning didn't seem correct in my testing.
