### ISSUE TITLE
Add ModItem.MeleePrefix/RangedPrefix/etc. hooks

### ISSUE THREAD

**Issue by Tyfyter** [bluemagic123/tModLoader#2772]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Hooks for the ItemLoader.MeleePrefix, ItemLoader.WeaponPrefix, ItemLoader.RangedPrefix, ItemLoader.MagicPrefix methods would allow weapons to receive prefixes other than the ones their damage type normally allows, such as allowing a modded whip to receive the same prefixes as vanilla whips

### What does this proposal attempt to solve or improve?

Currently making a whip receive the same prefixes as vanilla whips without remaking Item.Prefix requires code such as the following:

```cs
public override int ChoosePrefix(UnifiedRandom rand) {
	if (Item.noUseGraphic) {
		Item.DamageType = DamageClass.Melee;
		Item.noUseGraphic = false;
		Item.Prefix(-2);
		Item.DamageType = DamageClass.SummonMeleeSpeed;
		Item.noUseGraphic = true;
		return Item.prefix;
	}
	return -1;
}
```

### Which (other) solutions should be considered?

None that I can think of.

**Comment by Chicken-Bones** [comment]
Completed
