### ISSUE TITLE
Beetle armor is missing

### ISSUE THREAD

**Issue by jamiruo** [bluemagic123/tModLoader#2775]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Can only make Beetle Shell and others are missing Turtle armor and Turtle Leggings have material listed on but without none on it.

**Comment by Chicken-Bones** [comment]
This is probably a mod change. Please only make issues if they happen with _no mods enabled_.
