### ISSUE TITLE
Desert key/biome key  is missing on calamity mod

### ISSUE THREAD

**Issue by jamiruo** [bluemagic123/tModLoader#2776]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Every other boss on calamity mod have key not desert. My idea is having desert hardmode boss which drop biome key and other stuff. hardmode boss can be huger Antlion or Vulture.

**Comment by Chicken-Bones** [comment]
This is not the calamity issue tracker. We do not make Calamity, only the mod loader
