### ISSUE TITLE
No Hardcore Metals after WOF and breaking altars

### ISSUE THREAD

**Issue by Zafkiel510** [bluemagic123/tModLoader#2777]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

So I don't have any log files but I have the TRRA (A RWBY Mod), Calamity mod, Gensokyo mod and a few others that are more covinence than anything and the only mod that really screws with world gen is the Calamity mod but after I beat WOF and I broke probably around 10 altars and got no message saying i got any hardcore metals. I ignored it and kept mining didn't find anything other than cobalt and palladium. I then booted up 2 worlds, 1 without dust from the TRRA mod and one without it and still couldn't find hardcore metals other than cobalt and palladium after breaking a few altars. I literally can't progress past this so a little help?

**Comment by CharizUniv** [comment]
This is a Calamity change, you'll get the next tier of hardmode ores after beating each Mech boss (one Mech = Mythril/Orichalcum, two Mech = Titanium/Adamantite, three Mech = Hallowed)

**Comment by Chicken-Bones** [comment]
Please don't report mod issues here. Only make a bug report if you see an issue with _no mods enabled_.
