### ISSUE TITLE
"Please ensure Steam is logged in and running" error on Terraria from GOG

### ISSUE THREAD

**Issue by Fetnak** [bluemagic123/tModLoader#2784]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

After running tModLoader I get this error:

![изображение](https://user-images.githubusercontent.com/32810797/182008233-c6233514-1f57-44b4-ab5d-7203f88e0284.png)

I do not know the reason for this, but i noticed, that if the original terraria executable file has the name "Terraria.exe", then it defines the distribution platform as "GOG", but when it has the name "Terraria_v1.4.3.6.exe ", then it defines the distribution platform as "Steam". You can see it in log files

### Log File

"Terraria_v1.4.3.6.exe"

[client.log](https://github.com/tModLoader/tModLoader/files/9227990/client.log)

"Terraria.exe"

[client.log](https://github.com/tModLoader/tModLoader/files/9227992/client.log)

### Steps to reproduce

1. Launch start-tModLoader.bat
2. An error pops up
3. Crying

### Expected Behavior

Starting the tModLoader

### Actual Behavior

Error instead of starting the game

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
This is expected, Terraria_v1.4.3.6.exe isn't what it is looking for, it is looking for Terraria_v1.4.3.6_B.exe. Looks like you need to download the latest terraria, v1.4.3.6_B from gog galaxy. (You seem to be on the old non-B version.)

**Comment by Apestein** [comment]
> This is expected, Terraria_v1.4.3.6.exe isn't what it is looking for, it is looking for Terraria_v1.4.3.6_B.exe. Looks like you need to download the latest terraria, v1.4.3.6_B from gog galaxy. (You seem to be on the old non-B version.)

what tmodloader version work with normal gog 1.4.3.6 version. You don't need to break the game for us every update

**Comment by JavidPack** [comment]
No, you need to download it from gog galaxy, same as you did before

**Comment by JavidPack** [comment]
The B thing was long ago, just update

**Comment by Fetnak** [comment]
> This is expected, Terraria_v1.4.3.6.exe isn't what it is looking for, it is looking for Terraria_v1.4.3.6_B.exe. Looks like you need to download the latest terraria, v1.4.3.6_B from gog galaxy. (You seem to be on the old non-B version.)

thanks, it helped
