### ISSUE TITLE
Pylons in Multiplayer break immediately upon placing them

### ISSUE THREAD

**Issue by blahblahbal** [bluemagic123/tModLoader#2787]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Placing a Pylon (both modded and vanilla) in multiplayer results in it immediately breaking, dropping an item, and leaving a ghost behind (meaning that it actually placed, but is invisible on the screen and on the map until you load the world in singleplayer, which then is unusable).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9229790/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/9229791/server.log)

### Steps to reproduce

Load a world in mulitplayer using Host & Play, then get a pylon and try to place it.

### Expected Behavior

The pylon places normally.

### Actual Behavior

Pylon breaks immediately.

### Reproduction frequency

Every time.

### Additional Information

I can send a video of this issue if needed.

**Comment by Chicken-Bones** [comment]
Fixed in ad7cc7b7406d5e5e52f93bde0cbf3371e0cb8e57
