### ISSUE TITLE
tModPorter not working on v2022.7 preview

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2789]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Due to an extra "" argument, checking `if (args.Length > 0 && args[0] == "-tModPorter") {` doesn't work, it'll need to be augmented to check more.

**Comment by Chicken-Bones** [comment]
Fixed in fe558708211d105fd30eeec2a95867ef7016230f
