### ISSUE TITLE
Make it so that you can load all mods previously loaded for a character with the click of a button

### ISSUE THREAD

**Issue by Syuvivju** [bluemagic123/tModLoader#2792]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

There is already an exclamation mark next to the characters. Just add a button after you click into the exclamation mark that loads all mods previously loaded for the character. 

### What does this proposal attempt to solve or improve?

QoL. Modpacks currently break for me and I usually play with dozens of mods so it's quite a chore if I want to play with different mods. 

### Which (other) solutions should be considered?

Idk fix modpacks. I'll post a bug report for that.

**Comment by Chicken-Bones** [comment]
Yeah, we're going to go more in the 'fix modpacks' direction this coming month.

**Comment by Syuvivju** [comment]
Alrighto
