### ISSUE TITLE
PreHurt() returning false doesnt prevent damage (does same thing as return true)

### ISSUE THREAD

**Issue by brianmlatimer** [bluemagic123/tModLoader#2796]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

v2022.06.96.4 - Works
v2022.07.58.4 - Broken

PreHurt() returning false used to negate damage, now, PreHurt() returning false does the same thing as if it returned true, meaning it deals damage normally.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9245317/client.log)

### Steps to reproduce

Make ModPlayer's PreHurt() return false.
Go in game and get hurt
see that it didn't negate the damage.

### Expected Behavior

Returning false should prevent damage

### Actual Behavior

Returning false does not prevent damage

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
You need to override the method again, the parameters have changed. You should see a message in visual studios that the method is overriding an obsolete method.

**Comment by brianmlatimer** [comment]
What did it change to?

**Comment by brianmlatimer** [comment]
Nevermind, it was ref int cooldowncounter
