### ISSUE TITLE
World generation with Calamity is persistently broken

### ISSUE THREAD

**Issue by didymos-pael** [bluemagic123/tModLoader#2800]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

So, I hope I'm barking up the right tree, and if I'm not, please let me know.

I installed world generation mod Super Seed Search (world search engine), and couldn't get it to work and it would just throw this error:
A problem was encountered during world generation
CalamityDungeonBiomeChests
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.WOrld.MiscWorldgenRoutines.GenerateBiomeChest(GenerationProgress progress, GameConfiguration config) in CalamityMod\WOrld\MiscWorldgenRoutines.cs:line 30
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30

So I disabled Super Seed Search and I kept getting the error.  I disabled Calamity and world generation worked, But I want to generate a world with Calamity, so now I'm stuck.  I eventually uninstalled every part of terraria and the mods, deleting the folders and reinstalled on a different disk drive.  I can't tell if the issue is with the tModloader files or with Calamity Mod files.  I thought I'd cleared them all out and a fresh! install would fix the issue, but I've deleted _all_ the files from user/documents/my games/terraria and D:\Program Files (x86)\steamapps\common\tModLoader and D:\Program Files (x86)\steamapps\common\Terraria and D:\Program Files (x86)\steamapps\workshop, but I must be missing something.

Thanks if you can help!

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9255469/client.log)

### Steps to reproduce

1. Install Calamity Mod
2. Install Super Seed Search Mod
3. Attempt to use Super Seed Mod to generate a world
4. Error
5. Uninstall all mods
6. Error persists

### Expected Behavior

World generation should return to normal after removing Super Seed Search mod from tModLoader, but it has affected tModLoader and/or Calamity Mod.

### Actual Behavior

When using normal world generation with Calamity Mod enabled, getting this error:
A problem was encountered during world generation
CalamityDungeonBiomeChests
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.WOrld.MiscWorldgenRoutines.GenerateBiomeChest(GenerationProgress progress, GameConfiguration config) in CalamityMod\WOrld\MiscWorldgenRoutines.cs:line 30
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30

### Reproduction frequency

100% of the time since the first instance.

**Comment by biswop** [comment]
for me all you need is a fresh install and the Calamity Mod
for it to give the error.

if you revert to the "v2022.06.96.6" release it will generate, the generation error starts in the "v2022.07.58.1" release

**Comment by Tabizzz** [comment]
wait for calamity to update, i think it's a calamity problem not tmod

**Comment by didymos-pael** [comment]
Thanks!  That worked!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by didymos-pael** [comment]
Thank you for your reply.  I reverted to a version from last month and was able to create a new world and that will do for now.  Since I’m new to the calamity mod, I don’t have any worlds with those features and just wanted to get started on one.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by raiden-py** [comment]
There's a new SteamWorkshop released called "[Fix Calamity Bug About World Creating](https://steamcommunity.com/sharedfiles/filedetails/?id=2844842520)," that does what its title says.
