### ISSUE TITLE
Gladius has delay after use

### ISSUE THREAD

**Issue by MingCate** [bluemagic123/tModLoader#2802]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After the Gladius is used, the player's arm will continue swinging for a moment with no sword, during which time items also cannot be used.

### Reproduction frequency

100% of the time the sword is used.

**Comment by JavidPack** [comment]
Seems to be working correctly on 1.4.4-preview as tested today

https://github.com/tModLoader/tModLoader/assets/4522492/2f3d9d2f-45d2-4c0c-9ccc-be84cd38993f
