### ISSUE TITLE
Can‘t create world with calamity installed 

### ISSUE THREAD

**Issue by Dodu99** [bluemagic123/tModLoader#2806]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to create a new world i ran into an issue with the World gen. What can i do to avoid the Problem? Pls help me. 

The issue:

A problem was encountered during world generation CalamityDungeonBiomeChests System.NullReferenceException: Object reference not set to an instance of an object. at CalamityMod.World.MiscWorldgenRoutines.GenerateBiomeChests(GenerationProgress progress, GameConfiguration config) in CalamityMod\World\MiscWorldgenRoutines.cs:line 30 at Terraria.GameContent.Generation.PassLegacy.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Generation\PassLegacy.cs:line 226 at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30

**Comment by ghost** [comment]
This issue has been encountered before. This is just because Calamity hasn't updated to the new 1.4 stable update. Nothing related to tModLoader, just give Calamity some time.

**Comment by Solxanich** [comment]
This is a bug with Calamity not tModLoader per previous comment. 
Calamity will eventually update with a fix, give them time. 

Closing as no action required by tModLoader
