### ISSUE TITLE
"Unknown error" on character

### ISSUE THREAD

**Issue by Ymisor** [bluemagic123/tModLoader#2811]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I can't play my character
![Uploading Снимок экрана (15).png…]()
.

### Steps to reproduce

1. launch TModLoader
2. Solo game
3.  And I can't play 

### Reproduction frequency

The first time. There has never been such a mistake before

**Comment by Chicken-Bones** [comment]
Please come to the #support channel in the Discord for issues like this. Make sure you disable all mods, and try and see if it's a mod causing the error

**Comment by Ymisor** [comment]
Ok, thanks
