### ISSUE TITLE
Spawn Rate is much higher than vanilla

### ISSUE THREAD

**Issue by Nobisyu12** [bluemagic123/tModLoader#2816]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The spawn rate of enemies on tModLoader is much higher than in vanilla. It gets very annoying when fighting a boss and there are 30,000 enemies around me compared to the normal 3,000. That was a bit of exaggeration, but you get what I mean. The spawn rate in tModLoader is much higher than in vanilla.

### Steps to reproduce

1. Open a world
2. Enemies spawn a lot more

### Expected Behavior

Enemies should not spawn as often as they do

### Actual Behavior

Enemies spawn a lot more frequently

### Reproduction frequency

It happens with all mods, no mods, and in all worlds

**Comment by JavidPack** [comment]
So, you found that it was normal then?

**Comment by Nobisyu12** [comment]
Lol, actually what happened was that I was used to the 1.3 spawn rates and was unaware that 1.4 increased the spawn rate. At first I thought it was a bug, but everything is actually alright.
