### ISSUE TITLE
NullReferenceException when trying to run a dedicated server in debian VM

### ISSUE THREAD

**Issue by lugia19** [bluemagic123/tModLoader#2820]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am unable to run a server as it crashes with the outlined errors.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9305317/client.log)

### Steps to reproduce

1. Create debian VM
2. Attempt to run tmodloader server

### Expected Behavior

The server should be running.

### Actual Behavior

The server fails with the aforementioned errors.

### Reproduction frequency

Every time I try to run the server.

### Additional Information

I am trying to run the server in a debian VM hosted on a freeBSD host.

**Comment by Chicken-Bones** [comment]
Please post `server.log`

**Comment by lugia19** [comment]
There is no server.log, unless it's not within the tModLoader-Logs folder. I only have client.log, Launch.log and Natives.log.

**Comment by Chicken-Bones** [comment]
It will be on the VM. How are you launching the server?

**Comment by lugia19** [comment]
I'm an idiot who was running start-tModLoader.sh instead of start-tModLoaderServer.sh is the explenation, because it's the script mentioned in the "running headless" section of this wiki page https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server, running the appropriate script works fine.

**Comment by Chicken-Bones** [comment]
Ah, thanks for the info. Will be good to know for support. Yes, `start-tModLoader.sh` disconnects from the parent process to make steam think the game has exited immediately for... reasons. It means your shell will no-longer be connected.
