### ISSUE TITLE
Input/output error when running dedicated server in debian VM

### ISSUE THREAD

**Issue by lugia19** [bluemagic123/tModLoader#2824]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The server keeps redrawing the initial menu to the screen over and over, and hangs.

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/9312438/server.log)

### Steps to reproduce

1. Install tmodloader server
2. Attempt to run it with the -server option

### Expected Behavior

It should display the menu and accept input

### Actual Behavior

It continues redrawing the initial menu to the screen and hangs.

### Reproduction frequency

Every time.

### Additional Information

The issue can be worked around by avoiding the startup menu by supplying all the necessary parameters via the command line.

**Comment by Chicken-Bones** [comment]
Please PM (or ping) me on the Discord and I'll help resolve this with you. You may be launching the server in an unusual way. It looks like the stdout console stream/pipe is broken.

**Comment by lugia19** [comment]
Similarly to my other issue, this was due to me running the start-tModLoader.sh file with the -server argument instead of the start-tModLoaderServer.sh script. Thank you for your help.

**Comment by Chicken-Bones** [comment]
Thanks for the update
