### ISSUE TITLE
Server guide gives an incorrect folder structure for mods

### ISSUE THREAD

**Issue by lugia19** [bluemagic123/tModLoader#2825]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The guide says, if copying the mods manually, to "copy the entirety of the steamapps/workshop/1281930 folder from your computer to Steam/tmod/steamapps/1281930". This is incorrect (or at the very least unclear) as copying the contents of the aformentioned folder to Steam/tmod/steamapps/1281930 means they won't be detected, as they actually need to be in Steam/tmod/steamapps/workshop/content/1281930, which is where the steamcmd method puts them.

**Comment by Solxanich** [comment]
Updated with the tested README from #2817 .
Please re-open if the information is insufficient.
