### ISSUE TITLE
game crash when i try to open it

### ISSUE THREAD

**Issue by Daomax1** [bluemagic123/tModLoader#2827]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

it loads then it opens a page with a bunch of text

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9316769/client.log)

**Comment by JavidPack** [comment]
Looks like a Razer issue. This might have been fixed recently, try again.

If that doesn't work, can you try setting the "UseRazerRGB" setting to false in ":\Documents\My Games\Terraria\tModLoader\config.json"?


Edit: Other reports say this is fixed, closing
