### ISSUE TITLE
Summoner weapons crit even though they shouldn't and whips hit same enemy twice instead of just once

### ISSUE THREAD

**Issue by Mariocraze14** [bluemagic123/tModLoader#2830]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In Vanilla, summoner weapons don't have a critical strike chance and it is also rather strange that whips also hit the same enemy more than once, this mostly resulted in mods, most notably Fargo, nerfing whips due this kind of quirky behavior

**Comment by Chicken-Bones** [comment]
Please fill out all the fields in the form when making a bug report.
Please make sure it happens with no mods enabled.
Please send a `client.log`

I'm not sure what you mean. Crit and double hit issues were fixed months ago to my knowledge.
