### ISSUE TITLE
CTD on Linux after initializing any mod

### ISSUE THREAD

**Issue by Plantterror** [bluemagic123/tModLoader#2832]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I encounter an unknown crash to desktop after attempting to load or reload any mod, crashing at the "Adding Content" phase. By holding shift, I am able to skip past loading mods and successfully enter the main menu. From the client.log I am unable to tell if anything is wrong on my own.

[Specs](https://cdn.discordapp.com/attachments/978760466459406367/1007889615463661619/unknown.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9330904/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9330905/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9330906/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/9330907/terrariasteamclient.log)

### Expected Behavior

I should be able to enter the main menu with a loaded mod.

### Actual Behavior

A crash to desktop happens during the "Adding Content" phase.

### Reproduction frequency

Guaranteed for now. I will continue to test and may update this post if I discover a mod I can load without issue, but I doubt that will happen.

### Additional Information

This does not happen on Preview 98f99016, although my issue has existed long before the previous preview build became stable build, so I am unsure if this even matters.

**Comment by JavidPack** [comment]
Can you try with Modders Toolkit disabled? You can manually edit the enabled.json file in /home/plantterror/.local/share/Terraria/tModLoader/Mods to disable that.

**Comment by Plantterror** [comment]
After further testing, it does appear to be a Modder's Toolkit issue. I will close and repost there.
