### ISSUE TITLE
Wireless mouse "disconnects" after closing the game

### ISSUE THREAD

**Issue by ProPeperos** [bluemagic123/tModLoader#2833]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

My wireless mouse (SteelSeries Rival 3 Wireless) can't connect to the computer after few seconds of closing tModloader. It's connected via usb stick that sends the information from the mouse to the computer. After the bug occurs the mouse starts blinking as it's trying to find the connection. This only happens with tModloader and nothing else. It didn't happend like a 1 or 2 weeks ago, but im not sure about correct time or it didn't happen even as i might had a diffrent mouse.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9331465/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9331466/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9331467/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/9331468/server.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/9331469/terrariasteamclient.log)

### Steps to reproduce

1. Open the game
2. Close the game
3. Move the mouse around for few seconds

### Expected Behavior

I can move my mouse on the screen after closing the game

### Actual Behavior

I can't move my mouse on the screen after closing the game

### Reproduction frequency

Always

**Comment by Chicken-Bones** [comment]
Not sure what I can do about this, short of buying that mouse and seeing if it happens to me. Even then, no guarantee I'd be able to fix it.

**Comment by ProPeperos** [comment]
Seems like this also happens to vanilla game, so i suppose it isn't a tmodloader issue
gonna close this now and move to report it at the vanilla forums
