### ISSUE TITLE
Error: CalamityDungeonBiomeChests

### ISSUE THREAD

**Issue by MisterBruno13** [bluemagic123/tModLoader#2834]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Por favor, alguien que me ayudee :((

### Log File

![image](https://user-images.githubusercontent.com/111207997/184518129-223fdcca-55d8-4242-869a-f4a699dcf7ed.png)

### Steps to reproduce

1.Abro TmodLoader 2. Entro a Single Player 3. Creo/Elijo un personaje 4.Creo un mundo y a la mitad del proceso se corta y me sale este error

### Expected Behavior

Tal vez haya un error en los comandos del mod, que no deje que siga avanzando el proceso

### Actual Behavior

No lo se

### Reproduction frequency

Siempre se puede utilizando el Mod

### Additional Information

Antes si se podia crear un mundo, pero el problema comenzó hace unas semanas

**Comment by JavidPack** [comment]
This is a problem with Calamity, you'll have to have them fix it. This issue tracker is not for bugs in mods.
