### ISSUE TITLE
Block Swapping below Modded Chests breaks them, Crashing the game

### ISSUE THREAD

**Issue by VortexOfRainbows** [bluemagic123/tModLoader#2835]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Block swapping platforms below modded chests causes them to break. If they have items inside, this also causes a game crash.

### Log File

N/A

### Steps to reproduce

1. Place 2 normal blocks in midair.
2. Swap blocks below to platforms.
3. When the left block is swapped, the chest will break (if there are blocks to the left and right of the suspended block, it will actually break with the right-side block replaced)

### Expected Behavior

The chest should not break, as is the case with Vanilla chests.

### Actual Behavior

The chests are breaking, potentially causing game crashes.

### Reproduction frequency

I was able to repoduce this issue with (chests from) Example Mod, Calamity Mod, and Secrets of the Shadows.

### Additional Information

https://user-images.githubusercontent.com/13910999/184523548-dbfb4e27-112d-4e84-a7bb-4f5b2bfb0c3d.mp4

**Comment by Seven-B** [comment]
Also for me it made a very loud noise.
