### ISSUE TITLE
steamapps folder do not creating (not license terraria)

### ISSUE THREAD

**Issue by ItsOnlyMeInHere** [bluemagic123/tModLoader#2840]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

my friend's issue
steamapps folder do not creating (not licensed terraria)

![image](https://user-images.githubusercontent.com/111360810/184880729-295d599b-53fa-4d7d-87eb-43033f20cd09.png)

### Log File

maybe without?

### Steps to reproduce

1) start tmodloader starter
2) issue

### Expected Behavior

normally browse mods

### Actual Behavior

mod browser dont work

### Reproduction frequency

once and continueing

### Additional Information

no

**Comment by Chicken-Bones** [comment]
Please come to the Discord for support. If you don't own Terraria on Steam, you'll need to buy it.
