### ISSUE TITLE
ModPylon's DefaultDrawPylonCrystal Method Using The Wrong Draw Offset

### ISSUE THREAD

**Issue by shb201902040125** [bluemagic123/tModLoader#2843]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

It can't be said to be a mistake, but it is inconsistent with the drawing of the original crystal tower. Makes modpylon appear taller
![image](https://user-images.githubusercontent.com/102274564/185159710-ede24a87-29cb-43eb-a479-f5585a0016be.png)
If it is consistent with the original pylon, the red underlined parameter should be 2 instead of 1.5

### Log File

No Log File.

### Steps to reproduce

It can be triggered at any time, if you don't change it

### Expected Behavior

I think it should be the same as the original

### Actual Behavior

Made modpylon look inconsistent with vanilla

### Reproduction frequency

EverTime

### Additional Information

Maybe you guys think this is a trivial thing, but I think ModPylon should be as consistent as possible with the original if it is a mod example version of the original Pylon. So I raised this Issue

**Comment by Chicken-Bones** [comment]
Is this "Latest 1.4-preview" or is this 1.4-stable?
There's a new `DrawDefaultCrystal` with different params on 1.4-preview

**Comment by shb201902040125** [comment]
Yes, it seems to be normal after I updated it.
