### ISSUE TITLE
Spears increase range with melee speed

### ISSUE THREAD

**Issue by TaterLord** [bluemagic123/tModLoader#2846]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When increasing melee speed, the extension distance on (vanilla) spears increases significantly, whereas in vanilla their range increases marginally. Occurs with no mods enabled.

### Log File

No crash, just a logic error

### Steps to reproduce

1. On any character, equip melee speed increasing armour/accessories. e.g. Monk's Brow, Shinobi Torso, Solar leggings, and all upgrades of feral claws with violent reforge. 
<img width="25" alt="Screenshot 2022-08-18 200220" src="https://user-images.githubusercontent.com/111498793/185369919-0fb9b347-93fb-4c23-87ce-1e9aa71d275c.png">

2. Get the regular spear, as it is easiest to see the bug with
3. Press/hold left click
4. Watch as the spear travels out of holding distance

### Expected Behaviour

Spear's range is approximately 7 blocks.
<img width="157" alt="Screenshot 2022-08-19 083628" src="https://user-images.githubusercontent.com/111498793/185560656-2fddff89-2616-4673-b8f4-fc53ac5d1a18.png">

### Actual Behaviour

Spear's range increases to approximately 12 blocks (hard to capture at max range).
<img width="260" alt="Screenshot 2022-08-18 200034" src="https://user-images.githubusercontent.com/111498793/185560721-e725153e-dc0b-4b20-86d9-126734b97284.png">

### Reproduction frequency

First time with mods installed, 2nd & 3rd time in tmod without any mods installed, tested in vanilla 3 times, additional test in tmod 1.4 preview.

**Comment by ThomasThePencil** [comment]
this isn't a bug. spears gainin' additional range from melee speed modifiers is vanilla behavior
more info here: https://terraria.wiki.gg/wiki/Attack_speed

please close this

**Comment by Chicken-Bones** [comment]
As Thomas said. You can see this documented here https://terraria.wiki.gg/wiki/Attack_speed

**Comment by TaterLord** [comment]
They still shouldn't have that much range increase. There is a discrepancy between the amount vanilla increases the range and tmod increases the range. my edit has made the report more cohesive and added an additional screenshot from more tests.

Can this issue be re-opened, unless it has been fixed for the next tmod update that is yet unreleased.
