### ISSUE TITLE
X32 bits version of terraria 1.4

### ISSUE THREAD

**Issue by Terrarialover9212** [bluemagic123/tModLoader#2849]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I really would love to play terraria 1.4 with mods but i cant really play it.For some reasons my tmodloader 1.4 console is shutting down.also when i tried to download Runtime broker its just cant download on my pc
Old x32 bits version terraria 1.3 worked, worked even with mods.

### What does this proposal attempt to solve or improve?

It will help to other with the same problem

### Which (other) solutions should be considered?

So can you please make x32 version of Tmodloader for 1.4? I hope i will help to other people with the same problem.

**Comment by Chicken-Bones** [comment]
Can you please post your system specs (run dxdiag from start menu and take screenshots). I'm interested in your cpu/gpu.
tModLoader might be making a 32bit version, but expect fewer and fewer games to support 32bit going forward.
