### ISSUE TITLE
Muffled audio

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2851]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Recently, I have noticed a strange issue with my audio. The music and menu sounds are fine, but all of the in-game sound effects (running, mining, etc.) sound more muffled than they used to. For some odd reason, the coin pickup sound has also changed from its normal high pitch, to a lower pitch clunk sound.

### Expected Behavior

Normal Terraria audio

### Actual Behavior

Muffled/worse sounds

### Reproduction frequency

Happens every time I load the game

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
