### ISSUE TITLE
Game freezes on startup, then crashes shortly after

### ISSUE THREAD

**Issue by hokhahey** [bluemagic123/tModLoader#2852]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When starting tModLoader, the game instance freezes a few seconds after startup, crashing the game shortly

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9378380/client.log)

### Steps to reproduce

1. Initialize tModLoader
2. Wait for a few seconds

### Expected Behavior

Head into the menu screen normally

### Actual Behavior

Game freezes in a short amount of time, crashing the game

### Reproduction frequency

Always

**Comment by Chicken-Bones** [comment]
Your tML install is broken somehow. Suggest deleting it and re-installing. In the future please come to the Discord for support.
