### ISSUE TITLE
tmodloader for steam keeps getting stuck on adding recipes

### ISSUE THREAD

**Issue by catmodtr** [bluemagic123/tModLoader#2853]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i load up tmodloader for 1.4 steam stable it will start to load and stop on the adding recipes screen and if i cancel it then it will freeze and i have to reload it. if i cancel it at the start and disable all of the mods i have installed it will still freeze on the adding recipes screen. 

### Expected Behavior

the recipes should be loaded within 30 seconds for me usually

### Actual Behavior

freezing on loading recipies

### Reproduction frequency

100% of the time right now.

**Comment by Chicken-Bones** [comment]
Please come to the Discord for support with issues like this. Most likely, you're having an issue with a mod. You can try checking the logs, or disabling all mods and re-enabling them bit by bit until you figure out which mod it is.
