### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by TwoBadBlue** [bluemagic123/tModLoader#2854]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I currently have a bug that makes any item in my bottom left inventory menu pretty much just add a new hot bar space and force use it regardless of the item. I've tried uninstalling the game and reinstalling the game, and among other things, the only "fix I've found is not having anything in the very bottom left slot of the inventory menu.

### Steps to reproduce

Not having anything in the bottom left corner slot of the inventory menu

### Expected Behavior

The game should not be recognizing the bottom left corner of the inventory mennu as a hot bar slot. 

### Reproduction frequency

I have this issue anytime something is in the bottom left corner slot of the inventory menu

**Comment by Chicken-Bones** [comment]
Discord is for help, not here. Make sure you disable all mods before reporting a bug with tModLoader.
