### ISSUE TITLE
player.GetDamage().ApplyTo() seemingly doesnt work.

### ISSUE THREAD

**Issue by SkippZzMods** [bluemagic123/tModLoader#2862]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Trying to use GetDamage().ApplyTo() or GetTotalDamage().ApplyTo() seemingly doesnt nothing. It doesn't seem to reduced, increase, or modify the input parameter "baseValue". I tried with multiple DamageClasses, vanilla and modded, and nothing worked. The code I was using is as follows:

player.GetDamage(DamageClass.Ranged).ApplyTo(100);
player.GetTotalDamage(DamageClass.Ranged).ApplyTo(100);

player.GetDamage<HymenoptraDamageClass>().ApplyTo(100); HymenoptraDamageClass is a custom damageclass that works completely as intended.
player.GetTotalDamage<HymenoptraDamageClass>().ApplyTo(100);

making 100 into 100f also did nothing. nothing I tried seemed to fix this issue, and nobody seemed to know the answer so I'm just going to assume it is a bug.

### Steps to reproduce

use player.GetDamage().ApplyTo()

### Expected Behavior

the method should be returning baseValue increased/decreased by the specified damage class.

### Actual Behavior

nothing. baseValue is not modified whatsoever.

### Reproduction frequency

every time.

**Comment by JavidPack** [comment]
please show an example with the actual context (what class and hook you are using this code in). For example, if you are trying to use this method before damage bonuses are applied, you'll see no change.

**Comment by SkippZzMods** [comment]
Hey, sorry first time writing an issue. It was in a ModBuff Update(player, buffIndex), although I assume Update(player, buffIndex) runs after damage bonuses are applied?

**Comment by JavidPack** [comment]
ModBuff.Update is one of the places intended for damage bonuses to be applied to the damage classes, so attempting to determine the final damage there will not work.

Something like ModPlayer.PlayerLoader should work, or other hooks depending on what content you are doing.

**Comment by SkippZzMods** [comment]
Okay that makes sense, thanks, luckily won't be a big issue.
