### ISSUE TITLE
Typo in documentation for ModBiome BackgroundColor

### ISSUE THREAD

**Issue by The-Mad-Duck** [bluemagic123/tModLoader#2867]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

There is a minor typo in the description for ModBiome's property BackgroundColor. It says "The color of the **bestary** background" when it should say "bestiary".

### Log File

N/A

### Steps to reproduce

Read the tooltip for the property BackgroundColor in Visual Studio when eiditing a ModBiome type class.

### Expected Behavior

Tooltip reads "The color of the bestiary background"

### Actual Behavior

Tooltip reads "The color of the bestary background"

### Reproduction frequency

Always

**Comment by Chicken-Bones** [comment]
I suggest making a pull request for minor changes like this! Easily mergeable then.
