### ISSUE TITLE
i cant open the game

### ISSUE THREAD

**Issue by Lucks-git** [bluemagic123/tModLoader#2876]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i try to open the game show the cmd panel and i show this
![2022-08-26](https://user-images.githubusercontent.com/112194186/186950939-00975d3c-8468-41a7-901f-ca647f3476e6.png)

**Comment by Chicken-Bones** [comment]
You have to buy Terraria on Steam to play tModLoader. You can't crack it. If you still have issues, please try a fresh re-install.
