### ISSUE TITLE
New Preview doesn't allow wide-screen resolution

### ISSUE THREAD

**Issue by VortexOfRainbows** [bluemagic123/tModLoader#2886]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Tmodloader resets the screen resolution when pixel width exceeds 1920. This is not the case in Stable (no mods are enabled)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9466415/client.log)

### Steps to reproduce

1. May be hard to reproduce since you may need a large monitor..?
2. Have big monitor.
3. Try doing windowed fullscreen, or alternatively stretch width farther than 1920 pixels.
4. Epic failure.

### Expected Behavior

Tmodloader should fill the full screen

### Actual Behavior

Tmodloader shrinks the window shortly after attempting to change window size

### Reproduction frequency

Able to reproduce consistently on preview. Does not happen on Stable. This did not happen yesterday, so I believe it is with the very recent commit.

### Additional Information

![f921160bf178f3f7519ddec3a13db5c2](https://user-images.githubusercontent.com/13910999/187821124-b990e80d-c0ee-4e64-99a9-005e1fbad553.gif)
![b75e32fe782371f04cdb00fafd365ac1](https://user-images.githubusercontent.com/13910999/187821126-988e02c3-9ae2-4f14-81d5-14942b894e6d.gif)

Fullscreen also causes stretching, remaining on inappropriate resolution.

**Comment by Rijam** [comment]
Probably caused by the changes made in response to #2020

**Comment by JavidPack** [comment]
Can you check this again? There have been some recent code changes that might have fixed this.

**Comment by VortexOfRainbows** [comment]
Checked again. It's fixed!
