### ISSUE TITLE
ошибка tModLoader dotnet-install.ps1 

### ISSUE THREAD

**Issue by izgach** [bluemagic123/tModLoader#2888]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

когда я хочу запустить тмодлоадер , у меня появляется ошибка связанная с dotnet-install.ps1 .
я не знаю как решить эту ошибку , помогите пожалуйста .

### Log File

![image](https://user-images.githubusercontent.com/112631493/187916786-b941a622-bb84-4231-9d67-96405d79db8d.png)

### Steps to reproduce

1.нажимаю в стиме кнопку играть. 2. появляется файл-скрипт который существует , а затем сам закрывается .

### Reproduction frequency

каждый раз при запуске tModLoader

### Additional Information

в самом конце файла-скрипта написно:
Failed to donload dotnet-install.ps1 . Relying on powershell to work.

**Comment by Chicken-Bones** [comment]
Please come to the Discord for support with issues like this
