### ISSUE TITLE
cannot update mods and uninstalling mods causes them to not be downloadable again

### ISSUE THREAD

**Issue by ShadowHawk055** [bluemagic123/tModLoader#2893]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

newest release, updating mods only reloads tmodloader. deleting mods causes them to be unable to be downloaded.

### Log File

this error does not produce logs

### Steps to reproduce

1. go to mod browser
2. update a mod
3. wait for it to finish
4. go to mod browser again
5. mod still needs to update

---

1. go to mod browser
2. delete a mod
3. go to mod browser
4. find the mod, download button gone

### Expected Behavior

it should update my mod

i am able to download it again

### Actual Behavior

in only reloads tmodloader

i need to unsubscribe to it in steam

### Reproduction frequency

always

**Comment by Chicken-Bones** [comment]
Can you confirm this is still happening on the latest stable? If so, please provide a `client.log` file

**Comment by ShadowHawk055** [comment]
this bug is fixed on the newest version
