### ISSUE TITLE
Please help ASAP

### ISSUE THREAD

**Issue by Aceplante** [bluemagic123/tModLoader#2894]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

What does "Requires preview v2022.9.6.0" mean? When I click it just brings me here with nothing to download.

**Comment by KennethHoff** [comment]
It's here, but I'm going to assume you downloaded something weird if you got this warning

https://github.com/tModLoader/tModLoader/releases/tag/v2022.09.6.0

**Comment by Mirsario** [comment]
It means that a mod requires you to be on the `1.4-preview` steam branch to be used.
