### ISSUE TITLE
Mod download don't start or/and doesn't update other mods

### ISSUE THREAD

**Issue by Benioteniso** [bluemagic123/tModLoader#2896]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

To summarize

Can't download any mod and Can't update any other mod i have

### Steps to reproduce

1. Open the mod browser
2. Try to update or download any mod
3. The mod, or doesn't download or doesn't update

### Expected Behavior

Expected to be just a stability

### Reproduction frequency

everytime i try to download or update

**Comment by MHRaaj** [comment]
yes I am having the same problem. Game just froze whenever pressing download or update. I am using SteamCMD to download mods. it's quite a tidious process of back and forth to see which mod is updated and which isn't.

**Comment by Chicken-Bones** [comment]
Can you confirm if this is still happening?
