### ISSUE TITLE
Crash on entering Sunken Sea

### ISSUE THREAD

**Issue by Fluffballes** [bluemagic123/tModLoader#2898]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

Upon entering the Sunken Sea, the game freezes for around 7 seconds before crashing, with no traces of any reason.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9484360/client.log)

### Steps to reproduce

1. Taking the path to my Sunken Sea.
2. Entering it.
3. Crash.

### Expected Behavior

Entering the sunken sea normally.
Even on crash, leave some logs to read on.

### Actual Behavior

Crashes without a single trace or without giving a clue on what just happened.

### Reproduction frequency

It occurs every time I enter the Sunken Sea.

### Additional Information

The side of the desert it's on is full of crimson. Upon entering on the sides, the crash is effectively delayed. The version is 2022.07.58.8

Mod list:
[LastLaunchedMods.txt](https://github.com/tModLoader/tModLoader/files/9484385/LastLaunchedMods.txt)

**Comment by ilija04** [comment]
This isn't for Calamity or any other mod issues. This is just for the mod loader issues.
