### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files

### ISSUE THREAD

**Issue by HPV3G4N** [bluemagic123/tModLoader#2904]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

So basically it says that there is a missing file in this directory 'C:\Program Files(x86)\Steam\steamapps\common\tModLoader\Content\Images', we've tried all we could think of so far, reinstall Terraria, tModLoader, remove 64bit version (Removing it only made it say something like "There is a missing executable"), verified file integrities, changing beta to 1.4 preview and none (1.3 worked). If there's no solution for this for now then hopefully they get a fix on it soon.

### Log File

![unknown (1)](https://user-images.githubusercontent.com/113041564/188907386-189319c6-05ba-41a3-8b8e-24da47b23afd.png)
[a.txt](https://github.com/tModLoader/tModLoader/files/9507158/a.txt)

### Steps to reproduce

1. Launch Steam
2. Launch tModLoader with 64bit
3. See the magic

### Expected Behavior

The game should work alright with 64bit, my friends have no problems on their end but mine is for some reason different.

### Actual Behavior

It refuses to launch because of a missing part of the path in the directory.

### Reproduction frequency

I don't know but it just happens every time I launch tModLoader.

### Additional Information

There might be a way to recover the missing Content\Images file and fix the bug or remove 64bit completely and hopefully remove the bug (I think the tModLoader steamapp requires 64bit to execute now so if I just delete them from the folder, it makes it so that it will not be executable at all).

**Comment by Chicken-Bones** [comment]
tModLoader64Bit is not supported here. tModLoader for 1.4 is 64bit by default.

If you want to play 1.4 mods, please do a clean reinstall of tModLoader
