### ISSUE TITLE
Modded chest vanity removes legs

### ISSUE THREAD

**Issue by Endie-157** [bluemagic123/tModLoader#2906]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I equip a piece of modded vanity that modifies the chest of the player character it stops rendering player legs. However vanilla vanity pieces behave normally. Armor also behves normally, both modded and vanilla.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9508396/client.log)

### Steps to reproduce

1. Equip modded vanity item that affects the chest.
2. Legs don't render.

### Expected Behavior

The legs should stay.

### Actual Behavior

Legs just disappear.

### Reproduction frequency

All the time.

### Additional Information

mods:
-cheat sheet
-the stars above
-fargo's souls
-fargo's mutant
-serge vanity mod
-secret of the shadows
-MrPlague's authentic races
-more accessory slots
-angler shop
-imkSushi's mod
-more endless ammo
-omniswing
-subworld library
-better boss health bars
-boss cursor
-which mod is this from
-max stack plus extra
-wing slot extra
-alchemistNPC lite
-ore excavator
-calamity mod music
-recipe browser
-calamity mod

**Comment by direwolf420** [comment]
please reproduce it with no mods except the one that adds the accessory. If it's yours, also post its code

**Comment by Endie-157** [comment]
It's not limited to one accessory, it's all chest accessories from different mods.

**Comment by oliverrook** [comment]
Can confirm this issue.
Using a modified version of the charm of example.
When I have the body changing code enabled, the legs disappear.
But when I commented out the body changing code, the legs reappeared.

I also saw this issue in Mr. Plague's Race mod.

Edit: Note, I am NOT using the race mod in my test of this issue.

Edit 2: I was mistaken, I was using it. And I believe it's the cause upon further investigation.

**Comment by JavidPack** [comment]
Yeah, we need a reproduction from 0 mods or a single mod that adds a normal vanity item. Sounds like this is most likely a bug in a mod at the moment.

**Comment by Endie-157** [comment]
Tested and MrPlague's authentic races is causing the issue.

**Comment by JavidPack** [comment]
Ok, sounds like this is a modded issue. If anyone can replicate with 0 mods, we can reopen, but as it is this sounds like something the mods doing this type of thing need to fix.
