### ISSUE TITLE
Search bar in installed mod list doesn't clear on right click

### ISSUE THREAD

**Issue by ExterminatorX99** [bluemagic123/tModLoader#2911]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In `1.3` the search bar in the install mod list could be cleared using right click.
This is no longer the case in `1.4`.

### Steps to reproduce

1. Open `Workshop` menu
2. Open `Manage Mods` menu
3. Search for a mod
4. Right click search bar

### Expected Behaviour

Search bar is cleared

### Actual Behaviour

Search bar is not cleared

### Reproduction frequency

Every time

**Comment by JavidPack** [comment]
Other menus (mod sources, mod browser) have similar issues too. Need to fix dimensions and make sure click handlers are assigned to correct element.
