### ISSUE TITLE
No sound in tmodloader

### ISSUE THREAD

**Issue by SilveonSenpai** [bluemagic123/tModLoader#2916]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

No sound from game, a lot of people having the same issue

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9542354/client.log)

### Expected Behavior

Normal sound from the game

### Actual Behavior

No sound(

**Comment by Chicken-Bones** [comment]
Duplicate of #2797, please try the workaround in my comment there
