### ISSUE TITLE
IO save more fine-grained

### ISSUE THREAD

**Issue by zzp198-old** [bluemagic123/tModLoader#2917]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

Currently, when saving mod data, if there is an error in saving mod data, all mod data will be lost.

### What does this proposal attempt to solve or improve?

Catch errors so that they do not affect the saving of other mod data.

**Comment by Chicken-Bones** [comment]
Follow proposal #2935 for planned fix
