### ISSUE TITLE
[Feature Request] Modify "Journey Mode Duplication menu" item availability via tabs

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2921]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

**[Vanilla wiki link for reference](https://terraria.wiki.gg/wiki/Journey_Mode#Duplication)**

It is currently not possible to control in which tab items go in the Journey Mode Duplication menu. Some filters check for fields on the item, some are using private & hardcoded sets, or both (found in `ItemFilters.cs`).
Currently, you have to detour the `FitsFilter` method in the desired filter and adjust the return value as desired.

Use case:
* Adding a custom bug net item to the "Tools" tab

### What does this proposal attempt to solve or improve?

Make the Journey Mode Duplication menu more intuitive to use for the player.

### Which (other) solutions should be considered?

No solution has been concidered so far, just pointing out a gap in the API.

**Comment by JavidPack** [comment]
I suppose we can expose the Tools._itemIdsThatAreAccepted by making it public or making an itemid.sets. I'd like to get more use-cases for this before someone implements, my hope is that we can ensure that the automatic detection and sets is sufficient for the filters, without having to make a new hook for this.

**Comment by Nil256** [comment]
Hi, I've created the special tools (example: Shovels, Flashlights, Map Pin, etc...), but I have trouble that I can sort them to the Tools Tab.
I tried to use the Detour, but it causes to crash the game...
I hope the feature is implemented.
