### ISSUE TITLE
Support for taller head armor sprites like the wizard's hat

### ISSUE THREAD

**Issue by Photonic0** [bluemagic123/tModLoader#2923]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Vanilla features are often very hard to re-implement and having an item property or hook to allow for drawing of taller hats like badger's hat, wizard's hat and bunny perch would be more convenient.

### What does this proposal attempt to solve or improve?

It is currently impossible to use a "default" spritesheet format for the aformentioned hats, as they will get "cropped"(see image)
The code, item sprite and spritesheet are also included.
![image](https://user-images.githubusercontent.com/62021912/189794902-5dc8bf8b-0b80-4527-bcaf-3ac4d4cc4cbb.png)
![image](https://user-images.githubusercontent.com/62021912/189794938-7edd536f-8e7c-49e4-b0ed-b236302724ed.png)

![DevHat](https://user-images.githubusercontent.com/62021912/189795215-3835f905-820c-4de1-adf9-69ca1cd58ce5.png)
![DevHat_Head](https://user-images.githubusercontent.com/62021912/189795317-ae908288-8438-4c1e-9673-b9cdd515a0ce.png)
https://hst.sh/amilokemux.cs

**Comment by JavidPack** [comment]
More info: In `DrawPlayer_21_Head`, vanilla hats like this are checked
```
bool flag = drawinfo.drawPlayer.head == 14 || drawinfo.drawPlayer.head == 56 || drawinfo.drawPlayer.head == 114 || drawinfo.drawPlayer.head == 158 || drawinfo.drawPlayer.head == 69 || drawinfo.drawPlayer.head == 180;
```

This is later used to adjust the coordinates of the `DrawData` added to the player render.

We can fix this with a ArmorIDs.Heads.Sets. Or we can use this as an example of finding and editing DrawData manually, but this is something many would want so a set sounds right.

**Comment by cozykoko** [comment]
done and closable?
