### ISSUE TITLE
FNA crashes with bad SDL_VIDEODRIVER environment variable

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2926]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Game can't launch for some users with this issue. 

![unknown (11)](https://user-images.githubusercontent.com/4522492/190300166-61e72596-3c20-4061-892e-e3019844fb20.png)

Lines in question:

https://github.com/tModLoader/FNA/blob/24a2c585c08af681718d437f3f793a5ced1b49c5/src/FNAPlatform/SDL2_FNAPlatform.cs#L223-L225

### Log File

[message.txt](https://github.com/tModLoader/tModLoader/files/9571227/message.txt)

**Comment by Chicken-Bones** [comment]
Hmm, most likely `videoDriver` is null. Other lines use `==` instead of `.Equals`. Can someone who is experiencing this issue ping me on Discord?

**Comment by Chicken-Bones** [comment]
Investigating in https://discord.com/channels/103110554649894912/1019436159924969533

**Comment by Chicken-Bones** [comment]
Confirmed, issue is env var, `SDL_VIDEODRIVER=directx`, no longer supported. <https://wiki.libsdl.org/FAQUsingSDL>

Was difficult to debug due to lack of <https://github.com/FNA-XNA/FNA/pull/395>
