### ISSUE TITLE
Game slows down and quickly crashes if Calamity mod is enabled

### ISSUE THREAD

**Issue by Shahelion** [bluemagic123/tModLoader#2927]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If the Calamity mod is enabled, the game will start slowing down, and eventually crash, usually within the minute. Happens on the main menu, haven't even been able to try making a world yet. There is another issue on here that is similar, but it has a different error, it seems.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9576057/client.log)

### Steps to reproduce

Download Calamity mod
Enable Mod
Wait for crash

### Reproduction frequency

Every time

### Additional Information

On the Calamity discord, they said to wait for tModLoader to update, as it "can't handle the graphics of this particle".

**Comment by Chicken-Bones** [comment]
This issue tracker is for tModLoader, not individual mods. Please try switching to the 1.4-preview beta in steam to get the latest tML versions ahead of time. 

The vast majority of people do not experience crashes with CalamityMod. It's the responsibility of the CalamityMod developers to report a more specific issue with tML that can be addressed (if there is one)
