### ISSUE TITLE
1.4.4 Breaking Change List

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2929]
- #2181
- #2930
- #3212
- #3101 
- #3302 
- #3210
- #3420
- #3219
- #3341
- #3420
- #3500

**Comment by steviegt6** [comment]
📌?

**Comment by BasicallyIAmFox** [comment]
mind updating #3072 to #3219 ? 3072 is badly corrupted, so i made new pr
