### ISSUE TITLE
Figure out how to do an 'extended preview' for 1.4.4

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2932]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

We should consider how to run a multi-month preview.

Need to figure out:
- How to prevent automatic git stable rollover
  - Disable the action temporarily?
- Whether the preview version should reflect the month as it goes into the second month
  - I think yes
- Make sure that publishing on the second preview month doesn't delete stable (2 month old) versions of the mod from workshop
- No freeze in the first month?
- Anything else I haven't thought of

### What does this proposal attempt to solve or improve?

Terraria 1.4.4 will contain breaking changes, and mods may want more than 1 month to update. We should consider an extended preview. 

### Which (other) solutions should be considered?

- Moving stable to a legacy steam branch 
  - Probably not a good idea, break everyone's playthroughs with mods which haven't updated yet
- Publish a '1.4.4 stable' version to another steam beta branch and continue as normal
  - Still need to make sure that all 3 versions of a mod are kept in the steam folder (stable, 1.4.4 stable, preview)
  - Need to consider any text that directs people to 'preview' when their tML version is outdated
  - Does this help at all? Who would play on a 1.4.4 stable, when not enough mods have updated. If mods have updated, we would just make this the actual stable.
  - Would having two active 'stable' versions create issues? Probably not, no different from users who just haven't updated for a while.

**Comment by Solxanich** [comment]
Closing as resolved under #2973

Note that all github actions scripts contain commented out lines of which are NOT dynamic- so we have to be conscious accordingly.
