### ISSUE TITLE
Autosave characters, and exit world to error screen when mod saving fails.

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2935]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

- If save and exit fails due to mod throwing an exception
  - Display an informative error ui (`UIErrorMessage`)
  - The previous save should not be overwritten
- Players should auto-save every 5 minutes.
- If auto-save fails
  - Exit the current world/server and display error message as above

### What does this proposal attempt to solve or improve?

Solution to #2917

### Which (other) solutions should be considered?

This solution can be extended with a recovery option to remove all save data from a specific mod at fault.

**Comment by zzp198** [comment]
I separate the encapsulation function from the save function. Get the data first, and then write it when there is no problem.
