### ISSUE TITLE
I think modpacks are broken again 2022.08.54.6

### ISSUE THREAD

**Issue by PassiveLemon** [bluemagic123/tModLoader#2943]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When creating a modpack, the modpack folder no longer contains the selected .tmods and the install.txt is empty.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9591648/client.log)

### Steps to reproduce

1. Select mods and make modpack
2. Open up the modpack
3. See that there are no .tmods and the install.txt is empty.

### Expected Behavior

There should be mods and a complete install.txt

### Actual Behavior

When creating a modpack, the modpack folder no longer contains the selected .tmods and the install.txt is empty.

### Reproduction frequency

Every time.

### Additional Information

Unless this is intentional, this will make server hosting much harder.
Before on 2022.08.54.4, modpacks could be made just fine but now on 2022.08.54.6, this issue happens.

**Comment by Nightreaver** [comment]
For 2022.8.54.6 this seem to work (again)

**Comment by JavidPack** [comment]
Please check 2022.9, I think things were recently changed. I'll close this issue later if there is no further response.

**Comment by PassiveLemon** [comment]
I'm just gonna close this. I forgot it was still open and the issue has been fixed for a while.
