### ISSUE TITLE
Using World/Tree globes on surface makes underworld background not load

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2946]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After using a world or tree globe to change the world and tree looks on the surface or anywhere else, going to the underworld does not allow for the underworld background to load.
![image](https://user-images.githubusercontent.com/70764728/190922051-b26ae312-cd7d-47e8-97b1-86ca6d184183.png)
Note how backgrounds are turned on but the underworld background appears as if backgrounds are turned off.

This has happened on a master - for the worthy world (which is a medium world for this case), and the mods I had enabled do not change the underworld in any way.

### Steps to reproduce

1. Enter your world
2. Obtain a world or tree globe
3. Throw a world or tree globe (I did it multiple times)
4. Go to the underworld
5. You will notice that the underworld background is not appearing, despite the setting being enabled (if it is enabled for you)

### Expected Behavior

The underworld background loads as it should be. The world globes only change the way a biome world looks, not all of the worlds, as far as I know

### Actual Behavior

The underworld background does not load, as if the background setting is disabled, despite the setting being enables.

### Reproduction frequency

Unknown, but presumably high reproduction chance.

### Additional Information

For clearing purposes, the "underground background" shown in the underworld does not count as a background for the sake of this issue.

**Comment by Chicken-Bones** [comment]
Please confirm this happens with no mods enabled. Also please post a `client.log` file

**Comment by JavidPack** [comment]
I attempted to replicate this just now in various ways, could not replicate. A client.log file and confirmation that it happens with 0 mods would really help, as chicken-bones mentioned.

**Comment by Setnour6** [comment]
Sorry for being late. I tested it and apparently disabling all mods (except for HERO's Mod/Cheat Sheet of course because I needed it) and the underworld seemed normal after.
I didn't think it would be a mod issue. My bad.
Here's the log
[client.log](https://github.com/tModLoader/tModLoader/files/9659819/client.log)
I'll update the post with the log as well.
I'll also close this post because the issue is no more. I'll contact the mod developers and talk to them about the underworld loading issue.

**Comment by JavidPack** [comment]
sounds good, thanks for looking into this again.
