### ISSUE TITLE
Pushing "Update all mods" button crashes the game

### ISSUE THREAD

**Issue by kromer61** [bluemagic123/tModLoader#2948]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

Maybe its only on my side, but game crashes everytime when I trying to update all mods.

### Log File

No updates in log

### Steps to reproduce

"Workshop" -> "Download mods" -> "Update all mods"

### Reproduction frequency

Every time I'm pushing the button

**Comment by JavidPack** [comment]
We need logs or we can't investigate this.

**Comment by kromer61** [comment]
Like I said, the logs don't update after that. And I was a little not correct in the description of the error. The game freezes after pressing the button.

**Comment by Chicken-Bones** [comment]
You still need to send a `client.log` (from after you've experienced the issue) for us to investigate this.

**Comment by Chicken-Bones** [comment]
You can find it in the `tModLoader-Logs` folder in your tModLoader steam directory (right click > Browse Local Files in Steam)

**Comment by kromer61** [comment]
Okay, it's useless
