### ISSUE TITLE
Network Issue for TML

### ISSUE THREAD

**Issue by CalAl2009** [bluemagic123/tModLoader#2950]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to download TML, it always says something like "Network Issue, Could not download". And it won't download. My dad bought Terraria on Steam, but I don't know his password, and he's locked out.

### Log File

???

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Expected Behavior

It would download like normal files, and playable.

### Actual Behavior

It's doing what I said above

### Reproduction frequency

I have no clue what that means...

### Additional Information

No more info.

**Comment by Chicken-Bones** [comment]
Please post a screenshot

**Comment by Chicken-Bones** [comment]
Please come to our Discord support channel https://discord.com/channels/103110554649894912/1019958533355229316

You will need to provide as much information as possible, particularly screenshots
