### ISSUE TITLE
docs.tmodloader.net outdated

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2957]
docs.tmodloader.net doesn't update from the github action and currently hosts old documentation files, which is confusing for some users who find the docs on tmodloader.net. 

It should probably just link to http://tmodloader.github.io/tModLoader/ or have some way of updating.

**Comment by Setnour6** [comment]
There could be 1.3 code sections and 1.4 code sections, and modders can look at both if they need to. Just an idea though

**Comment by JavidPack** [comment]
There is, but this issue is about how the tmodloader.net website needs to update.

**Comment by JavidPack** [comment]
I seem to have fixed this, or maybe jof did. As far as I can tell the actual content is hosted on http://tmodloader.github.io/tModLoader/ and not duplicated on tmodloader.net server.
