### ISSUE TITLE
ContentSamples.CreativeHelpder.GetItemGroup exception messages aren't helpful

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2959]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Sometimes modders make a mistake in a ModItem, and that mistake causes index out of bounds in CreativeHelpder.GetItemGroup. A bad Item.createTile, Item.buffType, or a bad item.shoot can all cause this. (This can be done with using the wrong ID class, for example)

The error message is particularly unhelpful, and doesn't mention the item at all, meaning that the modder has to search all recently edited files for a mistake they might not know is a mistake.

We should add to the exception message the item name that is causing the issue.

![image](https://user-images.githubusercontent.com/4522492/191576664-caadf85b-0f99-4547-b11e-c60ef7313abe.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9619186/client.log)

### Steps to reproduce

1. Make mod skeleton with item
2. add `Item.buffType = 5400;` to the item
3. build reload, see error message

**Comment by JavidPack** [comment]
Some code in https://github.com/tModLoader/tModLoader/pull/1063/commits/9632957ed29c8852ff053090155f854f60127eb6 was causing this, I reverted it since the reasoning didn't seem correct in my testing.

**Comment by Chicken-Bones** [comment]
How, did you link the wrong commit? That commit only alters `UIBestiaryEntryGrid`

**Comment by JavidPack** [comment]
I did, guess I had both tabs open. This is fixed by https://github.com/tModLoader/tModLoader/pull/3051
