### ISSUE TITLE
Add a way to apply item stats without relying on EntitySource_ItemUse

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2963]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

`Projectile.HandlePlayerStatModifiers` automatically assigns fields like `originalDamage`, `CritChance` and `ArmorPenetration` based on the stats of an item (or parent projectile). 

Changing the pattern matching to an interface like `IEntitySource_WIthItem` could allow for better sources to be created, such as an extension of `OnHit` which includes an item (similar to `ItemUse_WithPotentialAmmo`)

### What does this proposal attempt to solve or improve?

If you want item stats to apply to a spawned projectile, you have to use `EntitySource_ItemUse` currently. This does not allow for expressing the _source_ of the projectile more accurately (eg an OnHit effect from an armor piece or accessory)

### Which (other) solutions should be considered?

Make a method like `Projectile.ApplyItemSource(Item)` that can be manually called if you want a different source.
- Downside is that mods can't transfer their own item stats to the projectile in `OnSpawn`

Rework entity sources to be a `List` or some other composition of 'source data' rather than relying on inheritance

**Comment by direwolf420** [comment]
Big agree. I'm personally facing two issues:
* Can't use "proper context" sources (i.e. `Projectile.GetSource_OnHit()`) when spawning projectiles because most of the time they won't crit, so I have to use lesser, more general sources (`Projectile.GetSource_FromThis()`)
* No way to "compound" sources, need to make custom classes, which may disrupt code checking for the more basic sources. Example:
    I want to pass an additional value to the spawned entity (which it retreives with `OnSpawn` hook). This requires me to either make a custom source entirely, or inherit from the source that you would normally use in that context, and expand it to accomodate for the additional value)

A design I am using in mods currently is interfaces as proposed in the issue:
```cs
public interface IEntitySource_HasTimeLeft : IEntitySource
{
	public int TimeLeft { get; }
}

public class TimeLeftParentEntitySource : EntitySource_Parent, IEntitySource_HasTimeLeft
{
	public int TimeLeft { get; init; }

	public TimeLeftEntitySource(Entity entity, int timeLeft, string context = null) : base(entity, context)
	{
		TimeLeft = timeLeft;
	}
}

public override void OnSpawn(IEntitySource source)
{
	if (source is not IEntitySource_HasTimeLeft timeLeftSource)
	{
		return;
	}

	GivenTime = timeLeftSource.TimeLeft;
}
```

This has the advantage or the spawn source still being the `EntitySource_Parent` class for TML to pick up the crit inheritance, but also allows the spawned projectile to only focus on the thing it actually needs. This sadly falls apart when you need more than one vanilla source "type" at once, as there's no multiclass inheritance.

**Comment by Chicken-Bones** [comment]
Fundamentally, entity sources are designed backwards. Typically, you pass parameters with an intended outcome, and give _only_ the information needed for the outcome to be achieved. Entity sources are the opposite, where you give as much information about the context as possible, because you have no idea what information the target entity may need.

The reason they were designed this way, was because mods often want to situationally change vanilla behaviour, but were unable to differentiate different vanilla call-sites. In any good code-base, this would be perfect, functions are _meant_ to be caller independent.

The use of `OnSpawn` to transfer crit, armor pen, etc from items to projectiles, and projectiles to their children is definitely a thing of convenience. But in doing so, we now made certain sources (`_ItemUse` and `_Parent`) the only way to achieve a certain behavior, which is at odds with 'providing as much context as possible'.

Some stopgap solutions could be:
- Make `EntitySource_OnHit` extend from `EntitySource_Parent`
- Make `IEntitySource_WithStatsFromItem` and `IEntitySource_InheritStatsFromProjectile` and use these instead of `_ItemUse` and `_Parent`
- A combination of the two
