### ISSUE TITLE
Add new secret seed conditions for ItemDropRules ByCondition

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#2972]
### Do you intend to personally contribute/program this feature?

Yes (but I can't do everything)

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

So far, there are two secret seed conditions implemented within the ItemDropRules.Conditions, and that being TenthAnniversaryIsUp and DontStarveIsUp.
![image](https://user-images.githubusercontent.com/70764728/192102494-d9428109-e974-4e27-a92b-72c6c5fad6f2.png)
This is one of the ItemDropRule Conditions for world seeds, being TenthAnniversaryIsUp.
Of course, there is also the inverse condition, "SecretSeed"Is**Not**Up

I noticed that there is no drop conditions for any other seed, like the "For The Worthy" seed world and Drunk World.
So why don't we add drop conditions for the other seeds?

Here is an example for the "For The Worthy" seed condition implementation:
```cs
public class ForTheWorthyIsUp : IItemDropRuleCondition, IProvideItemConditionDescription
        {
            public bool CanDrop(DropAttemptInfo info)
            {
                return Main.getGoodWorld;
            }

            public bool CanShowItemDropInUI()
            {
                return Main.getGoodWorld;
            }

            public string GetConditionDescription()
            {
                return Language.GetTextValue("Bestiary_ItemDropConditions.IsForTheWorthy");
            }
        }
````
Now obviously it's not perfect, and I do want something like this in the game for the potential to make it so loot can be dropped exclusively or increasingly on drunk or worthy worlds, or who knows what.

### What does this proposal attempt to solve or improve?

In a worthy world, players would join the world and defeat bosses as usual; but with an extra challenge, there should be a way for players to have a chance at receiving greater rewards, like an exclusive item.
There are already exclusive/alternative droprate items in the Tenth Anniversary seed worlds (not that I would know because I haven't tried the tenth anniversary world for droprule related stuff), and in the Constant seed world.

Say that a mod decides to make it so when a boss is defeated in a "Not The Bees" world, an extra drop is included, being a special item with bee-like properties on the item, such as releasing stingers or bees alongside their other properties (or other special properties).

### Which (other) solutions should be considered?

Alternatively, you can just use an if statement and check if the player is in a seed world, and then add your drop rule there like you normally would.

**Comment by Chicken-Bones** [comment]
These seem like reasonable tML additions. Please open a PR
