### ISSUE TITLE
[Feature Request] A way to make modded tiles sway in wind/on player movement

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#2975]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

The code responsible for drawing tiles that "sway" (be it from wind or when a player walks by) is currently super hardcoded to only support vanilla tiles (either by vanilla type checks, or the variables related to sway being private). A way to either automatically handle this through sets, and/or (optionally) through hooks, on a tml level would benefit modders greatly.

### What does this proposal attempt to solve or improve?

Make it much easier to implement swaying tiles, such as lanterns, vines, banners, etc.

### Which (other) solutions should be considered?

No solution proposed directly here

**Comment by JavidPack** [comment]
I looked into this while trying to port the banners, but there was a lot of new stuff that I didn't recognize the purpose of so I didn't finish that. I might make a branch with my current changes, but they aren't much.

**Comment by blahblahbal** [comment]
I would love if this was added. Been messing around with coding this kind of thing and there are many things that are strange with doing this without a TML solution; swaying tiles aren't drawn correctly and their rotation is choppy.

I also don't quite understand why this is marked as "Benefit - Low" when this would improve visuals and overall mod player's experience.
