### ISSUE TITLE
Stackable Items Use Void Bag Text On Pickup

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#2976]
### Version

Self-Compiled (please specify branch)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Picking up any item that could go into an existing stack in the player's inventory makes the pickup text use the Void Bag effect.
This only occurs if the item can stack with an item already in the player's inventory.

Unstackable Item:

https://user-images.githubusercontent.com/33076411/192169845-80479334-4c36-4262-8139-915f7e57cdac.mp4

No Existing Stack:

https://user-images.githubusercontent.com/33076411/192169848-3c88eccc-e49a-4870-826b-bf3732aa1d4d.mp4

Existing Stack (Bug):

https://user-images.githubusercontent.com/33076411/192169852-be88245f-3c72-4fe3-97d5-50b10ea9e8cf.mp4

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9641959/client.log)

### Steps to reproduce

1. Put less than a full stack of an item in the player's inventory (ex: 100 Dirt)
2. Pick up any amount of that item.

### Expected Behavior

The pickup text should act normally.

### Actual Behavior

The pickup text uses the Void Bag effect.

### Reproduction frequency

100%

### Additional Information

Branch: 1.4
Last Commit: https://github.com/tModLoader/tModLoader/commit/bb9255799e7be035f62c602f58d3917b2eb5bc55

**Comment by Chicken-Bones** [comment]
Fixed in #2978
