### ISSUE TITLE
Can't change resolution above 1920x1080

### ISSUE THREAD

**Issue by k2aj** [bluemagic123/tModLoader#2997]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Since the latest tModloader update I am incapable of changing the game resolution to anything above 1920x1080
- All resolution options above 1920x1080 have disappeared from the settings menu.
- If I try to change the resolution to 4k manually via config.json, the game still renders at 1920x1080 in the upper left quarter of the screen, while the rest of the screen is filled with garbage (screenshot below). The game starts rendering properly as soon as i change the resolution using the settings menu, but it still doesn't allow me to choose any resolution above 1920x1080.

![4k](https://user-images.githubusercontent.com/43889210/193405479-8923b7d5-d8f4-4b5d-b090-68fe3484caac.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9690105/client.log)

### Steps to reproduce

1. Start the game
2. Attempt to change resolution to 3840x2160.

### Expected Behavior

The game allows me to change resolution to 3840x2160.

### Actual Behavior

The game does not allow me to change resolution above 1920x1080.

### Reproduction frequency

Always.

### Additional Information

The issue does not occur in unmodded Terraria (without tModloader).
The issue did not occur in the previous stable tModloader release (v2022.08.54.6).
I'm using a 3840x2160 monitor. Display scaling is set to 100%.

**Comment by TheDelinquant** [comment]
Same thing for me since TModloader update.
OS : Windows 10
Platform : Steam

I cant go above 1920 * 1200.

2560*1440 is not available anymore.
Forcing  "DisplayWidth": 2560 and  "DisplayHeight": 1440 in config.json doesnt work.

**Comment by SammCheese** [comment]
Can confirm this bug.

OS: Linux
Platform: Steam

resolutions above 1920x1080 are gone

**Comment by Duckapple** [comment]
Can confirm too.
OS: Linux (Arch)
Platform: Steam

When I change from a small window to maximized, the window glitches out for about a single frame (looking like it would maximize), then shrinks back to the small window, producing this output:

```
[16:24:39.118] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: 0, DisplayMode: {{Width:2560 Height:1600 Format:Color}}, Profile: HiDef, Width: 1280 -> 2560, Height: 800 -> 1527, Fullscreen: False, Display: \\.\DISPLAY1
[16:24:39.143] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: 0, DisplayMode: {{Width:2560 Height:1600 Format:Color}}, Profile: HiDef, Width: 2560 -> 1280, Height: 1527 -> 800, Fullscreen: False, Display: \\.\DISPLAY1
Resolution changed to: 1280x800.
[16:24:39.152] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: 0, DisplayMode: {{Width:2560 Height:1600 Format:Color}}, Profile: HiDef, Width: 1280, Height: 800, Fullscreen: False, Display: \\.\DISPLAY1
[16:24:39.152] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: 0, DisplayMode: {{Width:2560 Height:1600 Format:Color}}, Profile: HiDef, Width: 1280, Height: 800, Fullscreen: False, Display: \\.\DISPLAY1
```
Line three is probably invoked from [this line in the patch of Main.cs](https://github.com/tModLoader/tModLoader/blob/a10475f1423c92cd556627e3a84ff8fbc3cc1b0b/patches/tModLoader/Terraria/Main.cs.patch#L4352), but I  haven't been able to find the debug statements.

**Comment by schmidsgo** [comment]
Same thing.

OS: Win 11
Platfrom: Steam

Monitor with resolution 5120x1440 now only 1920x1080 is possible ingame.
Normal Terraria works just fine.

**Comment by Bunni** [comment]
Same thing here,
OS: Win 10
Platform: Steam
TMod: v2022.9.47.1
Terraria: v1.4.3.6


Ultra wide of 3440x1440 worked fine for the last 8 months or so. Overnight my resolution is capped at 1920x*
