### ISSUE TITLE
Cannot set resolution higher than 1080p in v2022.09.47.1

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2999]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Ever since yesterday i cannot set my resolution higher than 1080p. Worked fine before, not sure if this is a issue on windows too.
Tried setting my resolution forcefully by config.json That just results in the game becoming a small square, rest of the pixels are black

### Steps to reproduce

1. Launch the game with a monitor using 1440p/4K 
2. Video settings
3. Toggle between resolutions

### Expected Behavior

The game should automatically set 2560x1440 as my resolution.

### Reproduction frequency

Every time.

**Comment by Bunni** [comment]
Duplicates https://github.com/tModLoader/tModLoader/issues/2999

**Comment by FluffyDiscord** [comment]
same issues with this version, using 3840×1600 monitor, windows 11

**Comment by Xydal** [comment]
i had the same issue with 3840x1600, installed the 2022.09.47.2 version manual and with stream but now i have no tiles displayed ingame

**Comment by Xydal** [comment]
> i had the same issue with 3840x1600, installed the 2022.09.47.2 version manual and with stream but now i have no tiles displayed ingame

okay. found the issue. i read about a workaround before the patch, which didn't work. had to remove the "/gldevice:OpenGL" from my start parameter in stream(tmod)

or v2022.09.47.3 fixed it ... just noticed now

**Comment by Solxanich** [comment]
ok. The core issues should be fixed. 

Yes, v2022.09.47.3 fixed a lot of these bugs. 

I'm going to close this given I haven't heard of further issues on that version.

**Comment by grossmetal** [comment]
The problem still exists on the 2022.9.47.4 version.
