### ISSUE TITLE
My Tmodloader don't open.

### ISSUE THREAD

**Issue by BeatrhabaGamer** [bluemagic123/tModLoader#3008]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![image](https://user-images.githubusercontent.com/114924235/193575068-a3a29dd8-b427-4fa9-9543-90ef327065ac.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9697392/client.log)

### Steps to reproduce

Open the Tmodloader 1.4 Preview

### Actual Behavior

Don't open

### Reproduction frequency

Every time today

**Comment by steviegt6** [comment]
Duplicate of #2996.
