### ISSUE TITLE
TModloader 1.4 stable version (v2022.09.47.4) runs in both 1.4.4.2 and 1.4.3.6 versions with errors.

### ISSUE THREAD

**Issue by nvcutrb** [bluemagic123/tModLoader#3009]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I ran the stable version of tmodloader 1.4 in 1.4.4.2, and then changed it to 1.4.3.6. The problem still occurred.
I checked the MD5 verification under the source code. It is clear that the MD5 verification is consistent, but an error is reported.
![1](https://user-images.githubusercontent.com/73949891/193593258-9310ff16-2aa4-4f58-bf18-44da0784cb07.png)
![2](https://user-images.githubusercontent.com/73949891/193593328-ed142f34-bf2a-48f6-a286-f88fc1175cd8.png)
![3](https://user-images.githubusercontent.com/73949891/193593351-3ac99384-1c6c-4cc7-b448-c5724f400e17.png)

### Log File

[2022-10-03-1.zip](https://github.com/tModLoader/tModLoader/files/9698014/2022-10-03-1.zip)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9698438/Launch.log)

### Steps to reproduce

Step 1
Unzip tModLoader.zip to the Terraria directory or side by side with the Terraria folder.
Step 2
Run start-tModLoader.bat
Wait for the installation to complete NET 6.0
CMD window information refresh
Then report an error!!!

**Comment by JavidPack** [comment]
I don't know what you are doing. You need to follow the instructions in https://github.com/tModLoader/tModLoader/issues/3011 to downgrade to get it working.
