### ISSUE TITLE
New GOG tModLoader users can't launch tModLoader since Terraria v1.4.4

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3011]
If you are a new tModLoader user and have installed Terraria from GOG, tModLoader currently won't launch. We are waiting for Terraria 1.4.4 hotfixes to finish up to update the install checks that check to ensure you have the correct version of Terraria installed.

In the meantime, the easiest solution is to use GOG galaxy and downgrade to "v1.4.3.6 v2", then launch tModLoader. This will create a "Terraria_1.4.3.6_B.exe" backup in the Terraria install folder, this file, if correct, will allow tModLoader to launch. You can then install the latest Terraria again.

**Comment by nvcutrb** [comment]
Thank you very much for your help. Thank you!

**Comment by JavidPack** [comment]
With the release of v2022.09.47.9, GOG users on 1.4.4.5 should now be able to launch the game.

**Comment by JavidPack** [comment]
Current stable and preview both support 1.4.4.9, closing.
