### ISSUE TITLE
Please ensure Steam is logged in and running error on Terraria from GOG

### ISSUE THREAD

**Issue by TheVoit** [bluemagic123/tModLoader#3014]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When starting  tmod loader i have this
![Screenshot_432](https://user-images.githubusercontent.com/90259394/193800579-56294d5b-6a83-49cd-b488-9b1911428ca2.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9705216/client.log)

### Steps to reproduce

1. Start tModloader.bat
2. Error
3. Sad

### Expected Behavior

Starting the tModLoader

### Actual Behavior

Error when trying to start the game

### Reproduction frequency

All times

**Comment by JavidPack** [comment]
Looks like you didn't follow the GOG install instructions correctly. tModLoader should not be installed in the Terraria folder, but a tModLoader folder next to the Terraria folder. Come to discord support channel if you need further assistance, we use the issue tracker for bugs, not support.
