### ISSUE TITLE
Not the server host ? 

### ISSUE THREAD

**Issue by Kastiel-Myraziel** [bluemagic123/tModLoader#3021]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Hello, i've installed the server on a virtual machine i own. We can connect / We can play. 
But everytime i try to change settings it's says 
" Server rejected changes : You are not the server host ! "

![](https://cdn.discordapp.com/attachments/1028328549372919963/1028331587680608316/unknown.png)

Well i own the virtual machine, i have the console, but there is no admin permission ... 
Can someone help me ? Thanks

**Comment by ryanaltvater** [comment]
What was the solve for this? I'm dealing with the same issue on a Bisect Hosting dedicated server. I can't make any changes to server/world-based configs in mods because of the error that I'm not the host.
