### ISSUE TITLE
Player.DemonConch(); not always working

### ISSUE THREAD

**Issue by RomanTheGithub** [bluemagic123/tModLoader#3026]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Player.DemonConch(); not consistently working.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9743084/client.log)

### Steps to reproduce

1. Join a multiplayer world
2. Use Player.DemonConch();
3. It will either work every time, or not work and just make a particle effect. If it is not working you will have to rejoin and hope.

### Expected Behavior

Player.DemonConch(); should always teleport you to the Underworld.

### Actual Behavior

Sometimes Player.DemonConch(); either teleports you to the Underworld, or just makes a particle effect and you stay where you are.

### Reproduction frequency

Never reproduced on singleplayer, seems a bit like a 50/50 on multiplayer.

**Comment by JavidPack** [comment]
Look at how vanilla code uses DemonConch, it doesn't use it directly in multiplayer. Also, this type of mod making question is more suited for the discord chat: tModLoader.net/discord

**Comment by RomanTheGithub** [comment]
Hey, quick question. How do I see how the vanilla code uses it?

**Comment by JavidPack** [comment]
something like ilspy <https://github.com/tModLoader/tModLoader/wiki/Advanced-Prerequisites>
