### ISSUE TITLE
Blinking vines on high resolutions

### ISSUE THREAD

**Issue by Veeveene** [bluemagic123/tModLoader#3029]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The vines (vegetation) in game appear to be blinking as soon as the player moves when the game is set to 2560x1440.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9758136/client.log)

### Steps to reproduce

This seems to always be happening when displaying vines in 2560 x 1440 resolution.

### Expected Behavior

The vines should not be blinking or disappearing.

### Actual Behavior

The vines are disappearing and reappearing very fast.

### Reproduction frequency

Every single time vines are displayed in-game.

### Additional Information

Video Clip : 
https://cdn.discordapp.com/attachments/1029430236321939536/1029430237420859514/Terraria__Dr._Bones_and_The_Temple_of_Blood_Moon_2022-10-11_18-22-08.mp4

NB : the vines appear to disappear due to the framerate of the video, but are rapidly blinking.
Lowering the screen refresh rate to 60hz did not fix the issue.

I tried :
I have no resource packs.
Disabling all mods
Reinstalling tModloader
 -> (deleting ..\steamapps\common\tModLoaderfiles and redownloading them)
Reinstalling Terraria
 -> (deleting ..\steamapps\common\Terrariafiles and redownloading them)
Restating my Computer
Creating a new World
Creating a new character.

Lowering the resolution under 2560x1440 seems to fix the issue.
This same issue does no seem to happen in vanilla Terraria.
This issue started happening today.

EDIT : 
The issue only seems to appear when the lightning is set to "Color", and disappears when set to "White", "Retro" or "Trippy".

**Comment by schmidsgo** [comment]
Playing on same OS and Platform and on Resolution 5120x1440 and have the same issue

**Comment by Setnour6** [comment]
The same thing happens to me but it's when I'm in a certain spot, and it only happens once for me. My resolution is 1920 x1080 (I play with the maximized window, so 1920 x 1018), and my refresh rate is set to 144hz, so that's why it's rarer for me.
My case is most likely a mod issue since it doesn't happen when I don't use any mods.

**Comment by Veeveene** [comment]
The issue only seems to appear when the lightning is set to "Color", and disappears when set to "White", "Retro" or "Trippy".

**Comment by Solxanich** [comment]
Possibly fixed in e8977e6e3de46774228be3bf6df2636ea3d6b08f 
Commit is on 1.4-preview. Just need to know if it works. 

The build should be done in about ten minutes
