### ISSUE TITLE
GOG: Can't re-install mod because uninstalling doesn't go properly without Steam Store.

### ISSUE THREAD

**Issue by Luna-Nocturna** [bluemagic123/tModLoader#3032]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

As the title pretty much gave away here's a more detailed description:

If you disable and delete a mod it keeps being ready for proper deletion. At this point tMod requests to restart the game before you can re-add the same mod again. On the Steam side when this doesn't work you're advised to unsubscribe and resubscribe for the mod in the Steam Workshop. This in my experience solves the issue. However on GOG you get the same advise, which, of course won't work as there's no Steam Workshop to (un)subscribe. So the mod remains stuck in a void.

### Log File

[11:19:08.751] [Main Thread/ERROR] [tML]: Item is/was already installed: More Accessory Slots (More Accessories). 
If attempting to re-install, restart your game first because Steam is weird
If restarting your game does not work, apply the following steps:
1) Open Steam Client
2) Find the Mod on tModLoader Workshop
3) Unsubscribe and Resubscribe on the actual Workshop.
These steps are required if Steam fails to handle unsubscribing you properly.

### Steps to reproduce

1. Start up Terraria through tModloader.
2. Download any mod of choice.
3. Enable said mod as per usual.
4. Disable the mod through the UI.
5. Delete the mod through the UI.
6. Restart the game as requested by tModloader.
7. Search for the mod again and it'll have an exclamation mark explaining why you cannot download.
8. An explanation shows you the explanation to resubscribe through the Steam Workshop which of course won't affect the GOG version.

### Expected Behavior

A proper removal of a mod, allowing you to re-download it again.

### Actual Behavior

Improper removal, dependent on the Steam Workshop.

### Reproduction frequency

Always, following the steps at the reproduction.

### Additional Information

Deleting the ACF file in \tModLoader\steamapps\workshop will fix it. However that'll make you have to redo all your mods. I guess I could figure out how to edit this myself but obviously that's a lot of effort.

Possibly tModloader needs a proper way to edit the file when it comes to removing a mod.

**Comment by Solxanich** [comment]
This is an interesting one, we do have code already that edits the ACF. The main question for me is why isn't it working. I haven't looked at the file in over a year, so seems something changed.

We delete this section to remove the mod.
![image](https://user-images.githubusercontent.com/59670736/196084510-07d097b1-71e1-4606-b231-621cc31a63f3.png)

This section is new to me: 
![image](https://user-images.githubusercontent.com/59670736/196084583-7a200365-222e-4bf2-b6c8-32641f83e3cc.png)

For the code savvy folks, we've had a function that deletes parts of the ACF that are relevant to the mod for over a year now. It was based on the former - find the ID, and remove that section from the file. But, this would corrupt the file with the new second block added.
https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/Social/Steam/SteamedWraps.cs#L311

May take a bit of thought to fix. ACF files aren't the cleanest to work with.

**Comment by Luna-Nocturna** [comment]
Thanks for the fix! I'll await the next update.
