### ISSUE TITLE
(Later Version) players

### ISSUE THREAD

**Issue by KerZeps** [bluemagic123/tModLoader#3033]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

So I just got tmodloader a couple minutes ago. I go in and try to migrate my players automatically. And when I do I have no stuff. no mana no armor no nothing. I cant even play it. and it says (later version) and then player name. so I try to uninstall it and reinstall it. but this time, I do it manually. And guess what? It doesn't work! Can somebody please help me?

**Comment by JavidPack** [comment]
tModLoader is still 1.4.3.6, it won't load your 1.4.4+ players or worlds: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#laterversion-on-player-or-world

**Comment by KerZeps** [comment]
do you mean there fixing the bug?

**Comment by JavidPack** [comment]
It's not a bug, really, it's just it'll be a couple months until we update to 1.4.4, since that just came out and changes much.

In the meantime, you can cheat in whatever items you had to a new player if you want with a mod like cheat sheet.
