### ISSUE TITLE
Memory leak with repeated mod reloads

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3035]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

**Tested on both stable and preview, same behavior**

After about 15 (forced) mod reloads, the game starts to hang at the "Unloading tModLoader v2022.XXX" step for several seconds, with task manager showing drastic increases of memory usage on dotnet.exe, which presist after a mod reload.

### Log File

Nothing peculiar in the log.

### Steps to reproduce

1 Make sure enabled.json is empty, to eliminate mods causing this
2. open task manager to monitor dotnet.exe memory usage
3. start the game
4. go to workshop, mods, forced reload, repeat 15 times (or until you notice slowdowns/memory increase)
5. the game stays progressively longer on "Unloading tModLoader" step, with memory visibly increasing
6. This effect gets exponentially worse with subsequent reloads to the point where the game hangs for 30+ seconds and/or memory is in the 4+ GB

### Expected Behavior

Reloads should not cause a memory leak

### Actual Behavior

Reload causes a memory leak

### Reproduction frequency

100%.

### Additional Information

 This is not a clean/fresh computer so I have mods in my workshop/Mods folders, meaning they (try to) get displayed in the Mods menu where I go to every time I want to reload mods, maybe it has something to do with that. I have not tested it with 0 "existing" mods

After running the game through a blank mod in VS, and testing this, I found that this is the culprit, it keeps multiplying this count every reload:
![Screenshot_6](https://user-images.githubusercontent.com/15894498/195917248-6f81575b-bfc1-4352-bb3a-bec3dc46327b.png)
![Screenshot_7](https://user-images.githubusercontent.com/15894498/195917776-3714a79e-8639-48e1-bdd1-6c35f84a6648.png)
![Screenshot_8](https://user-images.githubusercontent.com/15894498/195917794-5ed05754-f089-40f6-bbb4-ab71815199da.png)

**Comment by Pannoniae** [comment]
(this should be closed btw due to #40eb3d9)

**Comment by Chicken-Bones** [comment]
Cherry picked to stable.
