### ISSUE TITLE
Detours (randomly) stop applying after reload/rebuild

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3036]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Detours seem to randomly stop applying under certain circumstances (which includes - but has not been traced to specifically - Reload Mods and Build+Reload), even though the logs mention successful detours.

### Steps to reproduce

1. Create a template mod from ingame Mod Development menu
2. add this code to the Mod class:

```cs
        public override void Load()
        {
            On.Terraria.Player.PickTile += Player_PickTile;
            On.Terraria.HitTile.AddDamage += HitTile_AddDamage;
        }

        private static int HitTile_AddDamage(On.Terraria.HitTile.orig_AddDamage orig, Terraria.HitTile self, int tileId, int damageAmount, bool updateAmount)
        {
            Terraria.Main.NewText("AddDamage is running");
            return orig(self, tileId, damageAmount, updateAmount);
        }

        private static void Player_PickTile(On.Terraria.Player.orig_PickTile orig, Terraria.Player self, int x, int y, int pickPower)
        {
            Terraria.Main.NewText("PickTile is running");
            orig(self, x, y, pickPower);
        }
```

3. enter a world, use your pickaxe to hit a tile. AddDamage should appear twice in the chat, and PickTile once.
4. now leave the world, reload mods, or rebuild+reload the modified template mod
5. Repeat 3+4 until either one, or both chat messages stop appearing (it's seemingly random, usually takes 5-10 reloads)

### Expected Behavior

the chat messages should always appear

### Actual Behavior

after some repeats, either one or both chat messages disappear

### Reproduction frequency

Sadly I haven't found a 100% reproduction yet. For me it was reproducible when modifying the steps slightly:
* enable Cheat Sheet mod (it's known to cause references to be held for any mod that has a `GlobalItem` class when entering, then leaving a world), then enable the modified template mod but with an additional class extending `GlobalItem`. The logs should then mention that both Cheat Sheet and the modified template mod hold references after unload.

### Additional Information

This never happens on 1.4-stable, no matter the mod list, the amount of reloads, etc.
It also doesn't matter if the appended method is static or not.

**Comment by VortexOfRainbows** [comment]
I thought I was going crazy, but I'm having the exact same issue with the same detour (PickTile). None of the other detours I've used break like this. Good to know it works on stable though, so I can do my testing there.

EDIT: Interestingly, it usually takes me 2 rebuild+reload before it breaks, which is quite a bit different from your 5-10.

**Comment by Chicken-Bones** [comment]
Please try on latest 1.4 (1e61b8f)

**Comment by direwolf420** [comment]
Had me and 2 other people test it, seems to be fixed
