### ISSUE TITLE
tModLoader v2022.9.47.8 Fatal error

### ISSUE THREAD

**Issue by Benioteniso** [bluemagic123/tModLoader#3039]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When i try to open Tmodloader, a popup appears saying "tModLoader v2022.9.47.8 Fatal error", this never appeared before and im pretty sure its a problem with the version i have (terraria 1.4.4.5). The client.log have the whole error log.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9812548/client.log)
(the 1° line of the client.log is modified, because i removed name of user and put "My user name"

### Steps to reproduce

1. i try to open Tmodloader
2. a cmd window, loading some configs
3. the popup appear
4. sad moment :(

### Reproduction frequency

everytime i try to open tmodloader

### Additional Information

i updated to 1.4.4.5 GOG
and this never happened before.

**Comment by JavidPack** [comment]
You didn't post the client.log file. Are you sure you aren't just seeing this error? https://github.com/tModLoader/tModLoader/issues/3011

**Comment by Benioteniso** [comment]
> You didn't post the client.log file. Are you sure you aren't just seeing this error? #3011

sorry i forgot to put the client log
Also i probably did something in the folder while i was downloading, but i cant remember (or even i didnt)

**Comment by JavidPack** [comment]
Ok, this is just the normal gog install issue, since gog is checking for an older release of Terraria currently, I'm updating the install checks right now. Once v2022.09.47.9 shows up in https://github.com/tModLoader/tModLoader/releases, that version should work

**Comment by dc2aoc** [comment]
请问这个怎么使用 我也出现了这种情况

**Comment by Benioteniso** [comment]
> Ok, this is just the normal gog install issue, since gog is checking for an older release of Terraria currently, I'm updating the install checks right now. Once v2022.09.47.9 shows up in https://github.com/tModLoader/tModLoader/releases, that version should work

thanks for the help

**Comment by JavidPack** [comment]
> 请问这个怎么使用 我也出现了这种情况

just install normally. https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players

**Comment by dc2aoc** [comment]
> > 请问这个怎么使用 我也出现了这种情况
> 
> 只需正常安装。https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players


> > 请问这个怎么使用 我也出现了这种情况
> 
> 只需正常安装。https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players

谢谢，解决了
