### ISSUE TITLE
tModLoader black screen except for UI elements when playing game

### ISSUE THREAD

**Issue by wispii** [bluemagic123/tModLoader#3042]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever playing tModLoader, even with no mods installed, the entire screen is completely black when in gameplay, the user interface, as shown in the image below
![20221016115711_1](https://user-images.githubusercontent.com/33157385/196031590-421149c1-93b7-4a34-bdfb-44fcf2050f29.jpg)
And whenever I exit the game, this error pops up;
![Selection_002](https://user-images.githubusercontent.com/33157385/196031617-12915fc6-0d05-428e-a1b8-f775f32bdc83.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9794263/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/9794264/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9794265/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9794266/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/9794267/terrariasteamclient.log)

### Steps to reproduce

1. Launch into the game
2. Launch into a world

### Expected Behavior

The game should display a normal world, with the world assets clearly visible

### Actual Behavior

The entire screen, barring the UI elements, are only shown as a black screen

### Reproduction frequency

Every time I launch into a world

### Additional Information

Running the game in Linux Via Proton

**Comment by ilija04** [comment]
Relates to #2994.

**Comment by steviegt6** [comment]
Is there a reason you can't just run the game without Proton?

**Comment by wispii** [comment]
Initially I was playing with Proton due to the native version crashing every time at launch.
I have since switched back to the native version, and after deleting the dotnet files has begun to work again.

**Comment by JavidPack** [comment]
I believe the plan is to detect Proton and warn the user. Not sure if we can get it working with Proton due to some code we use.
