### ISSUE TITLE
[Wiki] Add one of my mods to the "Open Source Mods" page

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3043]
Nothing too serious, it's just a mod that has gained a bit of of attention back in 1.3, has been rewritten to 1.4, and it covers treasure bags being craftable, which is impossible to do in vanilla terraria, and is technically a cheat mod (because the game is easier that way).
It also adds a bit of new items to use for crafting the treasure bags, making use of recipe groups as well. It's not worked on much because I am in post-secondary education (and am generally a busy guy), but I encourage people to help work on the mod.
Idk which category Craftable Treasure Bags would fit in.
Link to "Open Source Mods" page: https://github.com/tModLoader/tModLoader/wiki/Open-Source-Mods
Link to Craftable Treasure Bags GitHub page: https://github.com/Setnour6/CraftableTreasureBags

If you want, you can deny this feature request and leave the page the way it is.

**Comment by steviegt6** [comment]
You can edit the page yourself.

**Comment by Setnour6** [comment]
> You can edit the page yourself.

It's better that I ask for permission before editing the page.

**Comment by Solxanich** [comment]
Is there anything in particular that this Open Source mod demonstrates?
Typically our wiki is focused around supporting how to mod, not necessarily for listing all mods that are Open Source.

If it provides useful examples that a new modder might learn from, that would make it easier to add to the "Other Mods" section with that description

**Comment by JavidPack** [comment]
I went ahead and added it, thanks.

**Comment by Setnour6** [comment]
> Is there anything in particular that this Open Source mod demonstrates? Typically our wiki is focused around supporting how to mod, not necessarily for listing all mods that are Open Source.
> 
> If it provides useful examples that a new modder might learn from, that would make it easier to add to the "Other Mods" section with that description

Sorry for the long wait. So it uses cross-mod recipes, a lot of them, and also demonstrates recipe groups.
