### ISSUE TITLE
Now im having a bunch of other error, one of them are related to wavebank.xwb 

### ISSUE THREAD

**Issue by Benioteniso** [bluemagic123/tModLoader#3049]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

after i resolved the problem with my tmodloader having error, im having other error, and one is related with wavebank.xwb being missing.
But i didnt remove the wavebank.xwb from Terraria folder, and this happened after i updated the tmodloader v2022.09.47.9.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9822915/client.log)
like i did before, i removed my user name and changed to "my user name"

### Steps to reproduce

1. try to open tmodloader (now updated)
2. cmd window appear, loading the game
3. another window appear saying tmodloader v2022.9.47.9 Fatal error

### Expected Behavior

some files missing

### Reproduction frequency

everytime i open tmodloader

### Additional Information

before the cmd windows appears, other cmd appear before with file loading (i guess), then a red phrases or something appears.
The phrase is something related to some missing file i guess, because this appeared in the other problem i had (but i forgot to mention because i thinked that wasan't something to worry about)

**Comment by Benioteniso** [comment]
> ### Version
> Latest 1.4-stable
> 
> ### OS
> Windows
> 
> ### Platform
> GOG
> 
> ### This bug affects
> Gameplay as a Player
> 
> ### Description
> after i resolved the problem with my tmodloader having error, im having other error, and one is related with wavebank.xwb being missing. But i didnt remove the wavebank.xwb from Terraria folder, and this happened after i updated the tmodloader v2022.09.47.9.
> 
> ### Log File
> [client.log](https://github.com/tModLoader/tModLoader/files/9822915/client.log) like i did before, i removed my user name and changed to "my user name"
> 
> ### Steps to reproduce
> 1. try to open tmodloader (now updated)
> 2. cmd window appear, loading the game
> 3. another window appear saying tmodloader v2022.9.47.9 Fatal error
> 
> ### Expected Behavior
> some files missing
> 
> ### Actual Behavior
> _No response_
> 
> ### Reproduction frequency
> everytime i open tmodloader
> 
> ### Additional Information
> before the cmd windows appears, other cmd appear before with file loading (i guess), then a red phrases or something appears. The phrase is something related to some missing file i guess, because this appeared in the other problem i had (but i forgot to mention because i thinked that wasan't something to worry about)

**Comment by JavidPack** [comment]
Looks like you installed tModLoader in the same folder as Terraria, that is not supported. It must be in a folder next to the Terraria folder or in a tModLoader folder nested in the Terraria folder.  https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

I'd suggest just reinstalling Terraria and tModLoader, this time in the correct locations, since the wavebank was deleted due to your current install setup.

**Comment by Benioteniso** [comment]
> Looks like you installed tModLoader in the same folder as Terraria, that is not supported. It must be in a folder next to the Terraria folder or in a tModLoader folder nested in the Terraria folder. https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation
> 
> I'd suggest just reinstalling Terraria and tModLoader, this time in the correct locations, since the wavebank was deleted due to your current install setup.

Thanks for the help 
But i already download the game inside terraria folder and this didnt happened.

**Comment by JavidPack** [comment]
The best place is in a folder next to the Terraria folder, not inside. Sounds like you need live support, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord).
