### ISSUE TITLE
Modded doors don't work with Smart Doors when obstructed

### ISSUE THREAD

**Issue by ben-tk** [bluemagic123/tModLoader#3052]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to walk through a modded door when something obstructs it from opening one way, the door fails to open.  Vanilla doors will simply open the other direction.
This was checked with the Example Mod door as well and the same issue occurs.

### Steps to reproduce

1. Place a modded door
2. Place a piece of furniture next to one side of the door
3. Try to walk through the door

### Expected Behavior

The door should just open the other direction where it's not obstructed.

### Actual Behavior

The door doesn't open automatically.

### Additional Information

Short video for demonstration of a vanilla (Solar) and modded (Calamity's Statigel) door:
https://user-images.githubusercontent.com/45545085/197290852-971dcf73-d609-4d28-bf0f-004dd6b65a4a.mp4

I think [DoorOpeningHelper.cs.patch](https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/GameContent/DoorOpeningHelper.cs.patch) isn't checking modded doors.
There's checks for `Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type != 10` from what I can tell instead of `TileLoader.OpenDoorID(Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y]) < 0`

**Comment by sgaregaeg** [comment]
helping please 
![image](https://user-images.githubusercontent.com/92227728/197304087-e75aec23-f339-4c28-9bf3-7a9d3e63c540.png)

**Comment by JavidPack** [comment]
@sgaregaeg Support questions happen on our discord: tModLoader.net/discord.

I'll look into this ben-tk
