### ISSUE TITLE
tmodloader can't download dotnet

### ISSUE THREAD

**Issue by Sk0rl** [bluemagic123/tModLoader#3053]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

when i launch tmodloader it tries to download dotnet and then fails
![Screenshot_87](https://user-images.githubusercontent.com/116430759/197332805-3fad5787-ca32-4f4b-bfff-ee10b51f32c5.png)

### Log File

Quick Edit Disabled
Verifying .NET....
Logging to C:/Users/loppp/Desktop/Terraria/tmodloader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
mv: can't rename 'C:/Users/loppp/Desktop/Terraria/tmodloader/Libraries/Steamworks.NET': Permission denied
'C:/Users/loppp/Desktop/Terraria/tmodloader/Libraries/Steamworks.NET' -> 'C:/Users/loppp/Desktop/Terraria/tmodloader/Libraries/steamworks.net/Steamworks.NET'
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Update Required. Checking for Windows pre-deployed x64 dotnet files
None Found. Attempting downloading win x64 portable dotnet runtime directly...
This can take up to 5 minutes
Extracting...
unzip: can't open C:/Users/loppp/Desktop/Terraria/tmodloader/dotnet/6.0.0[.zip]
Update Required. Will now attempt downloading using official scripts.
This can take up to 5 minutes
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

Dotnet should be present in "C:/Users/loppp/Desktop/Terraria/tmodloader/dotnet/6.0.0"

### Steps to reproduce

1. launch tmodloader

### Expected Behavior

i think it should launch normaly

### Actual Behavior

it doesnt

### Reproduction frequency

every time after new terraria update

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.

I'd suggest trying everything in https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#launch-issues
