### ISSUE TITLE
Changing the language doesn't update some tModloader UI elements

### ISSUE THREAD

**Issue by Jadams505** [bluemagic123/tModLoader#3055]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Switching languages doesn't update some text on UI elements added by tModloader

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9851776/client.log)

### Steps to reproduce

1. Switch the language to anything other than English (Settings->Language) (I used Spanish)
2. Go to Workshop->Develop Mods (Atrás->Atrás->Taller->Desarrollar mods)
3. Switch the language back to English (Atrás->Ajustes->Idioma->English)
4. Go back to Workshop->Develop Mods

### Expected Behavior

The text should be in the selected language

### Actual Behavior

The title text, search bar, and bottom buttons are all in the wrong language

### Reproduction frequency

Everytime

### Additional Information

This is an issue for many of tModloader's UI elements (Mod Sources, Mod Browser, Mod Packs, Mod Configuration, etc)
Pretty much every element in `Interface.cs` is affected in someway

**Comment by JavidPack** [comment]
This has been known, but it might be more effort than it is worth. We shall see.
