### ISSUE TITLE
ModAccessorySlots cause dyes to "bleed" into vanity accessories

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#3061]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Dyes used in modded accessory slots "bleed" over into the player's vanity accessories.

https://user-images.githubusercontent.com/33076411/198497969-47031d7d-c21a-4edb-ace4-1b40ffd9f4c5.mp4

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9884803/client.log)

### Steps to reproduce

1. Enter a world with only ExampleMod enabled, which adds a default modded accessory slot.
2. Place an accessory with a visible equipment texture (ex: Worm Scarf) in the functional slot of a modded accessory slot. Ensure that the accessory is visible.
3. Place any dye in the dye slot of the same modded accessory slot. This should correctly dye the accessory.
4. Place an accessory of the same equipment type (Ex: Apprentice's Scarf) in any vanity accessory slot, including other modded slots.

### Expected Behavior

The player should show the accessory in the vanity slots, and that accessory should be undyed.

### Actual Behavior

The correct accessory is shown, but the dye bleeds over from the modded slot.

### Reproduction frequency

100%, on both stable and preview.

### Additional Information

* This appears to happen with exclusively modded accessory slots.
* Visibility has different effects based on the equip type: Wings appear to always be dyed, while other equips are only dyed if the functional equip is visible.

**Comment by JavidPack** [comment]
Thanks for the good write up and video, I was able to replicate because of the good instructions.
