### ISSUE TITLE
tModLoader server http api

### ISSUE THREAD

**Issue by x0620x** [bluemagic123/tModLoader#3076]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Can you consider developing a server api interface application, so that the server can be managed through the api, without the need to execute management commands in the background cmd window, such as query

Um participant: HTTP: 127.0.0.1: port/bosslist
returned messages
status=200
The defeated: king slime,
undefeated: Eye of the Crusus, world eater,

### What does this proposal attempt to solve or improve?

Manage the server through the api

### Which (other) solutions should be considered?

no

**Comment by Chicken-Bones** [comment]
This would be more suitable as a mod. Only if it became very popular would we consider adding it to tML.
