### ISSUE TITLE
No hooks run on projectile self-damage

### ISSUE THREAD

**Issue by Tyfyter** [bluemagic123/tModLoader#3077]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Currently there are no references to hooks in ProjectileLoader or PlayerLoader (ModifyHitPlayer, OnHitByProjectile) whatsoever in the part of Projectile.Damage which deals with projectiles damaging their owners, which means the only way to modify self-damage or apply affects when it occurs is to use ModPlayer.Hurt and reflection

### Steps to reproduce

1. create a ModPlayer, GlobalProjectile, or a ModProjectile which fits the vanilla qualifications to deal self-damage
2. override any or all hooks which run when a/the player is hit by a/the projectile
3. hit yourself with a projectile

### Expected Behavior

The relevant hooks should run

### Actual Behavior

The relevant hooks don't run

### Reproduction frequency

100% (also verified in source code)

**Comment by Chicken-Bones** [comment]
Please post an example `ModProjectile` and `ModPlayer` class that we could add to `Example Mod` which does what you want (via reflection if need be). 

We will use this to guide and test any improvement/implementation we make to the hooks.

**Comment by Tyfyter** [comment]
> Please post an example `ModProjectile` and `ModPlayer` class that we could add to `Example Mod` which does what you want (via reflection if need be).

where should I post it and precisely what do you mean by "which does what you want (via reflection if need be)"?

**Comment by Chicken-Bones** [comment]
In your original post:
> the only way to modify self-damage or apply affects when it occurs is to use ModPlayer.Hurt and reflection

We need something like (but with an actual thing that people would actually want to do):
"A thingymabob projectile that damages/heals/buffs/messages/etc the player when it hits them"
```cs
class ExampleThingyProjectile : ModProjectile {
...
}

class ExampleThingyPlayer : ModPlayer {

}
```

Without this, it's hard to know _exactly_ what is needed, and how much it's needed (whether there are other options)

**Comment by Tyfyter** [comment]
```
//makes the miner set set bonus make player take less damage from their own projectiles (i.e. bombs, )
public class ExampleMinerSetBonusPlayer : ModPlayer {
  // stuff to declare and set minerSet, not relevant here
  ...
  // end stuff to declare and set minerSet, not relevant here
  public override void ModifyHitByProjectileOrNewHook(Projectile proj, ref int damage, ref bool crit) {
     if (minerSet && proj.owner == Player.whoAmI && proj.friendly && !proj.trap && !proj.npcProj && !proj.originatedFromActivableTile) {
       damage = damage / 2;
     }
  }
}
```

```
public class ExampleBurnyBombThatDeals26DamageToPlayersButDoesntProccessSelfDamageItselfAndJustUsesTheDamageMethod : ModProjectile {
  // exact copy of regular bombs otherwise
  public override void ModifyHitPlayer(Player target, ref int damage, ref bool crit) {
    damage = 26;
  }
  public override void OnHitPlayer(Player target, int damage, bool crit) {
    target.AddBuff(BuffID.OnFire, 99999);
  }
  // maybe kill override, I can't remember if you need to do that if you use the grenade/bomb/dynamite ai style
}
```

how these currently need to be implemented (how the reflection is handled can obviously be different, but I think this is the most readable way to do it):
```
public class ExampleMinerSetBonusAndTheBombPlayer : ModPlayer {
  internal static FieldInfo _sourcePlayerIndex;
  static FieldInfo SourcePlayerIndex => _sourcePlayerIndex ??= typeof(PlayerDeathReason).GetField("_sourcePlayerIndex", BindingFlags.Instance | BindingFlags.NonPublic);

  internal static FieldInfo _sourceProjectileIndex;
  static FieldInfo SourceProjectileIndex => _sourceProjectileIndex ??= typeof(PlayerDeathReason).GetField("_sourceProjectileIndex", BindingFlags.Instance | BindingFlags.NonPublic);

  public override bool PreHurt(bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource, ref int cooldownCounter) {
    if ((int)SourcePlayerIndex.GetValue(damageSource) == Player.whoAmI) {
      Projectile sourceProjectile = Main.projectile[(int)SourceProjectileIndex.GetValue(damageSource)];
      if(sourceProjectile.type == ModContent.ProjectileType<ExampleBurnyBombThatDeals26DamageToPlayersButDoesntProccessSelfDamageItselfAndJustUsesTheDamageMethod>()){
        damage = 26;
        Player.AddBuff(BuffID.OnFire, 99999);
      }
      if (minerSet && sourceProjectile.owner == Player.whoAmI && sourceProjectile.friendly && !sourceProjectile.trap && !sourceProjectile.npcProj && !sourceProjectile.originatedFromActivableTile) {
        damage = damage / 2;
      }
    }
    return true;
  }
}
```

**Comment by MacaylaMarvelous81** [comment]
I think this is because of returning before hook is called in Terraria.Projectile.Damage. it will return here:

```cs
10652 |
10653 | if (Main.netMode == 2 || !hostile || Main.myPlayer >= 255 || damage <= 0)
10654 |     return;
```
and the hooks will be called later after the switch expression.

**Comment by Chicken-Bones** [comment]
Need to re-investigate this now that #3212 has merged

**Comment by Chicken-Bones** [comment]
Looks like it has been resolved.
