### ISSUE TITLE
tMod 1.4 on steamdeck choose chinese language didnt work, please someone to fix it QAQ

### ISSUE THREAD

**Issue by Devolicoo** [bluemagic123/tModLoader#3084]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am using machine translation. Sorry for any grammatical problems QAQ
tmod 1.4 I played on my steamdeck( Proton 7.0-4 ), If I use the default environment , I can't even open the tmod.
Setting - Language - Chinese , it didn't work , it's still English .
And when I got into the game , The screen was dark and only menus，UI could be displayed.
Every time I quit the game, tmod always definitely die

**Comment by steviegt6** [comment]
Does tModLoader work without Proton for you? AFAIK it should since Steam Deck is x86, not ARM.

**Comment by Devolicoo** [comment]
>

**Comment by Devolicoo** [comment]
> Does tModLoader work without Proton for you? AFAIK it should since Steam Deck is x86, not ARM.
I can't even open the tmod1.4 without Proton, My guess is dotnet caused the problem ?

**Comment by Devolicoo** [comment]
It was stupid of me to accidentally close this issue OTL

**Comment by steviegt6** [comment]
> > Does tModLoader work without Proton for you? AFAIK it should since Steam Deck is x86, not ARM.

>  I can't even open the tmod1.4 without Proton, My guess is dotnet caused the problem ?

Hmm, could you provide your logs when launching without Proton?

**Comment by Devolicoo** [comment]
> > > Does tModLoader work without Proton for you? AFAIK it should since Steam Deck is x86, not ARM.
> 
> > I can't even open the tmod1.4 without Proton, My guess is dotnet caused the problem ?
> 
> Hmm, could you provide your logs when launching without Proton?

I'm so excited. I don't know how to thank you !!!
I realized the lack of dotnet runtime environmental when i saw Natives.log and Launch.log.
I installed the runtime of dotnet manually through a script , and I copied them to this path ’/home/deck/.local/share/Steam/steamapps/common/tModLoader/dotnet/6.0.0/‘
Finally, I can run tmodloader without Proton and fixed the bug of choose Chinese!!!
Thank you very much for your help!

**Comment by steviegt6** [comment]
> I'm so excited. I don't know how to thank you !!! I realized the lack of dotnet runtime environmental when i saw Natives.log and Launch.log. I installed the runtime of dotnet manually through a script , and I copied them to this path ’/home/deck/.local/share/Steam/steamapps/common/tModLoader/dotnet/6.0.0/‘ Finally, I can run tmodloader without Proton and fixed the bug of choose Chinese!!! Thank you very much for your help!

No problem! Glad I could help
