### ISSUE TITLE
Presented ExampleMod doesn't work

### ISSUE THREAD

**Issue by Flightflame** [bluemagic123/tModLoader#3094]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I'm starting to develop terraria mods and I really need to view working code, but when I compilate this mod it write 57 errors
![image](https://user-images.githubusercontent.com/118290334/201961267-b008dac2-1719-4950-9328-102dc347654c.png)

**Comment by JavidPack** [comment]
Looks like you downloaded ExampleMod from the 1.4 branch, what you needed to download was the 1.4-stable branch or from the release.  https://github.com/tModLoader/tModLoader/archive/refs/heads/1.4-stable.zip or https://github.com/tModLoader/tModLoader/releases/download/v2022.09.47.14/ExampleMod.zip
