### ISSUE TITLE
Incompatibility of legacy mods (eg. 0.11.8.9) for recent versions of tModLoader (eg. 2022.9.47.14)

### ISSUE THREAD

**Issue by StickyChannel92** [bluemagic123/tModLoader#3099]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Various mods from the web require Legacy tModloader (1.3). When loading said mods on the latest stable version of tModLoader, the mod unloads with an error.
![image](https://user-images.githubusercontent.com/48563620/202734816-7ab804a7-b555-462f-ab14-c80a14e191ef.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10042334/client.log)

### Steps to reproduce

1. download and put any legacy mod in the mods folder (Thorium, for example)
2. start tModLoader
3. click Workshop, then Manage Mods
4. click enable on the mod you just installed
5. click Back in order to start the mod to get the error.

### Expected Behavior

The mod(s) should load without an error. It would take shorter amount of time to launch the mod.

### Actual Behavior

An error appears telling you that you are using the latest version of tModLoader, while the mod supports, specifically, legacy version 0.11.8.9. The mod(s) get unloaded automatically.

### Reproduction frequency

Always. (with legacy mods only. mods downloaded from the "Download Mods" section (Steam Workshop page) will load.)

**Comment by Ved-s** [comment]
Legacy mods can't be and never will be able to load in 1.4

**Comment by Rijam** [comment]
Follow this guide to access 1.3 tModLoader: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#to-access-13-legacy-tmodloader
