### ISSUE TITLE
for some reason my PlayerCharacters keep getting deleted.

### ISSUE THREAD

**Issue by halogone** [bluemagic123/tModLoader#3103]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i go back to the title screen be they cloud saved or not, the PCs get deleted, why? i don't have the slightest idea.

### Log File

[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/10068318/terrariasteamclient.log)
[client.log](https://github.com/tModLoader/tModLoader/files/10068319/client.log)

### Expected Behavior

leave the world, when i want to go back PCs should be there, and i go play again

### Actual Behavior

leave the world, when i want to go back PCs should be there, but no they're gone. 

### Reproduction frequency

till now every time

### Additional Information

for some reason one mod right now has caused the great fiery sword is bugged because of the mod cooler item visual or something like that.

**Comment by JavidPack** [comment]
You'll want to check that this isn't a mod issue, see the https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-mods guide to confirm if it is a mod or tmod issue.

If it is a tmod issue, send the fresh logs generated after disabling all mods. If it is a mod issue, disable whatever mods are causing the issue.

Also, your cloud storage looks full, which would prevent cloud players from saving, I'd make some room: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#cloud-storage-limit-reached-unable-to-move-to-cloud

**Comment by halogone** [comment]
update i also noticed the configs also reset like tmod keeps downloading for the first time every time i open it

**Comment by JavidPack** [comment]
That sounds like something is preventing the program from saving to the documents folder. The most common reason for this is the safe files feature, but antivirus or other computer settings can also do this.

Well, you can check the safe files feature, it might be preventing things:
https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#controlled-folder-access

You can also tell tmodloader to use a custom save directory, as a test: https://github.com/tModLoader/tModLoader/wiki/Command-Line

Either make a shortcut with -tmlsavedirectory assigned or create a file named "savehere.txt" in the install directory.

**Comment by JavidPack** [comment]
Also, your cloud is full, so if the player was on the cloud it might not be saving correctly, you might need to uncloud some Terraria worlds, <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#cloud-storage-limit-reached-unable-to-move-to-cloud>
