### ISSUE TITLE
Menu select button gets physically pushed to the left (if there's too much raw text?)

### ISSUE THREAD

**Issue by QUIDD60x** [bluemagic123/tModLoader#3109]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Using a lot of text on the modded menu swap button will physically move the button to the left. This issue is also affected by the text in color codes ( i presume), meaning a moved menu button for no apparent reason to the naked eye.

### Expected Behavior

Menu swap button should remain in place, at the bottom center.

### Actual Behavior

Menu button is pushed to the left varying amounts, based on how much text you have.

### Reproduction frequency

yes.

### Additional Information

I would attach an image but I can't, so here's https://imgur.com/4HKuHiY as a refrence image of what I'm talking about.

**Comment by QUIDD60x** [comment]
For any future refrence, I have `public override string DisplayName => "[c/5EAFF1:Y][c/74acda:o][c/82abcc:u][c/96a9b8:r] [c/c1a48d:T][c/c1a48d:a][c/e7a067:l][c/e7a067:e] menu";` as the menu name, which is probably why it gets pushed to the left.

**Comment by MacaylaMarvelous81** [comment]
I think that the color codes are included when measuring the string but not actually displayed, causing the displacement.

**Comment by QUIDD60x** [comment]
> I think that the color codes are included when measuring the string but not actually displayed, causing the displacement.

Well I thought that much, I just don't know if there's a possible fix or not. The menu select button ends up really messed up, but if there isn't a fix then oh well.
