### ISSUE TITLE
Failure in tModLoader setup.bat process

### ISSUE THREAD

**Issue by romiyake** [bluemagic123/tModLoader#3114]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I´ve been trying to contribute to the project but my setup process keeps failing in the same spot and I can´t figure why.

### Log File

src/TerrariaNetCore/Terraria/Initializers/LinkButtonsInitializer.cs,	exact: 0,	offset: 0,	fuzzy: 0,	failed: 1
FAILURE: @@ -17,12 +17,17 @@

### Steps to reproduce

1. Install 1.4.3.6 version of terraria
2. Start setup process with this version
3. Failure

### Expected Behavior

Setup process completing with success

### Actual Behavior

Error while setuping

### Reproduction frequency

Everytime

**Comment by JavidPack** [comment]
Seems like you have 1.4.3.6 not 1.4.3.6_B. B was a small update that changed the wiki link to https://terraria.wiki.gg/

**Comment by romiyake** [comment]
that's it! thank you so much!
