### ISSUE TITLE
Tmodloader setup check

### ISSUE THREAD

**Issue by andrey6498** [bluemagic123/tModLoader#3120]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Make tmod check for mod folders existing upon each start and automatically re-execute setup scripts, if there's none. So you will be able to completely remove tmod folder in documents to reset it without reinstalling it on steam, or potentially use this as a fallback if it fails to run for other reasons.
Also may add some interaction with the user if it fails to run post init, prompting for a restore operation, or do it completely automatically just with notification.

### What does this proposal attempt to solve or improve?

Like if you just remove tmod folder in documents/MyGames/Terraria it completely refuses to start.
While with this tmod instead will try to restore folders/ re-init setup scripts to get back to working automatically.

**Comment by JavidPack** [comment]
I'm not following, tModloader runs perfectly fine if the tmodloader folder didn't exist when the game launches. 

It sounds like you have some support issue, you might want to check the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ) or come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). My guess is you are running into the Controlled Folder Access
issue.

**Comment by andrey6498** [comment]
Well that's not quite my issue but i guess you re right. Though i figured out some more info on this: like if it ever happens to not run in default/stable tmod, it will crash at startup and after several reinstalls it will refuse to run saying things about ram issues(out of memory with no mods with 16gb ram on machine, logs also don't give anything pointing to the issue), but it's also not the case since preview runs just fine. May be something tied with broken config/allocated memory issue.
@JavidPack

**Comment by andrey6498** [comment]
![000](https://user-images.githubusercontent.com/8511369/205686840-e9639057-3669-4557-ac61-1a9cca968502.png)
![111](https://user-images.githubusercontent.com/8511369/205686580-995290e9-8305-4ea4-ac47-0357da4b5303.png)

**Comment by andrey6498** [comment]
Some more data on this,
these happened after out of memory crash
then out of memory repeated after several reinstalls

**Comment by JavidPack** [comment]
Yeah, this is a support issue, this can be handled on discord, where you will post your log files.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
