### ISSUE TITLE
Inconsistencies within ExampleRecipes (Little to no effect on what it acomplishes)

### ISSUE THREAD

**Issue by Mangochicken13** [bluemagic123/tModLoader#3122]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

There are one or two small inconsistencies within the comments in ExampleRecipes, the comment on line 44 mentions that the next line adds a requirement of one dirt to the recipe, but the next line adds a stone block. Line 40 also specifies that the ingredients are 1 stone block, so changing the dirt to stone in line 44 would make the most sense.

There is potentially another on line 69, which is showing that you have to select mod items differently to vanilla items, but the item in the comment differs to the one in the actual code.

### Which (other) solutions should be considered?

This is completely a non-issue, and I am happy to do this myself, It just bugged my OCD a bit while relearning how to mod

**Comment by Mangochicken13** [comment]
I'm happy to go through other files too, and rewrite the comments where necessary, and I also fully understand what said comment is trying to convey, just tell me what/how to do if necessary.
I'm also willing to do some more comments in other files if requested to, where they may be useful to some people (like myself)

**Comment by Chicken-Bones** [comment]
Feel free to submit a PR with any tweaks you feel appropriate. Keep it minimal and easy to review. Please work from the 1.4.4 branch at this time.
