### ISSUE TITLE
linux server "Please ensure Steam is logged in and running" error

### ISSUE THREAD

**Issue by specificocean23** [bluemagic123/tModLoader#3127]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when booting up the server (using ./start-tmodloaderserver.sh), an error occurs that says i must be logged into steam. I don't have steam as it's on a VM and I'm not sure how anyone can use a VM for a server if this issue is common. Thanks for any help! Running Debian

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/10181505/server.log)

### Steps to reproduce

1. chmod the start-tmodloaderserver.sh
2. ./start-tmodloaderserver.sh
3. wait a min for loading then error pops up

### Expected Behavior

server should run

### Actual Behavior

error preventing launch

### Reproduction frequency

every time, tried on 2 VM's, same result

**Comment by ppebb** [comment]
According to your logs, you're running with the args `-steam -lobby friends`. How are you launching `start-tModLoaderServer.sh`? 

If you are launching with `-steam`, then of course it will try to use steam, and will break because you do not have it installed. If so, you will either need to find a way to install steam on the server and run it, or have your friends connect via ip.

**Comment by specificocean23** [comment]
> According to your logs, you're running with the args `-steam -lobby friends`. How are you launching `start-tModLoaderServer.sh`?
> 
> If you are launching with `-steam`, then of course it will try to use steam, and will break because you do not have it installed. If so, you will either need to find a way to install steam on the server and run it, or have your friends connect via ip.

It should have worked with -steam because I installed terraria and tmodloader on the VM, although i tried to run it without -steam and it worked. Issue still persist if I needed to run -steam although I don't so its solved for me. Running sudo ./start-tModLoaderServer.sh
