### ISSUE TITLE
CustomCurrencyManager retrieving Currencies

### ISSUE THREAD

**Issue by utz32** [bluemagic123/tModLoader#3133]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Currently unable to get Instances of Terraria.GameContent.UI.CustomCurrencySystem back out of Terraria.GameContent.UI.CustomCurrencyManager.
Please give us a public Accessor to Terraria.GameContent.UI._currencies or a method that retrieves a CustomCurrencySystem for a given Terraria.ID.CustomCurrencyID

### What does this proposal attempt to solve or improve?

Dynamic Access to modded Currencies is currently impossible. This would allow Iteration of all Currencies.

**Comment by JavidPack** [comment]
You indicated that you'd want to implement this, is that the case? If so, we can give some guidance on the collaborators channel in the tmodloader discord if you want advice on how we usually do this sort of thing. Otherwise we can open this up for anyone to implement.

**Comment by Exiled1** [comment]
This one looks interesting! I'll take a shot at implementing it 🦀

**Comment by Exiled1** [comment]
Okay, implementation done. Writing an Example now :).

**Comment by Exiled1** [comment]
Okay! @utz32 Done :), when this merges go ham.
