### ISSUE TITLE
start-tModLoaderServer.sh can't work

### ISSUE THREAD

**Issue by dilinhuo** [bluemagic123/tModLoader#3137]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I can't run start-tModLoaderServer.sh.

### Additional Information

I try to change [[ -v steam_server ]] to [ -v "$steam_server" ] and it works.

**Comment by JavidPack** [comment]
This looks like some shell syntax incompatibility I guess? Hopefully someone with some shell knowledge will chime in and confirm the issue here.

**Comment by JavidPack** [comment]
@Mirsario It seems you did some changes recently in an attempt to fix things, https://github.com/tModLoader/tModLoader/commit/2a1fcc5c91ac12b7f96442b24f3f993e345a0ce6, are you aware of this issue with `[[` and `]]`? Maybe we need to change the launch script in a similar manner to this fix: https://github.com/tModLoader/tModLoader/issues/1778 ? If you don't know, we can probably find someone else who knows this stuff.

**Comment by Mirsario** [comment]
Those changes I did [based on findings](https://discord.com/channels/103110554649894912/445276626352209920/1025762046987477012) done by Solxan - he should know more than me about shell syntaxes, but isn't a full expert either. 

Google says that the double bracket syntax is an extension, none of which we should use, yes.. If the alternative works on a basic mac shell, then it should work on busybox (`ash`, which is basic but apparently not as much as older Macs') and all the better Linux shells -- just need to push to preview and make sure first.

**Comment by Solxanich** [comment]
Hi There @dilinhuo,

Before I push a fix, would you mind testing the 1.4-preview branch (the 1.4-preview Steam Beta option) to see if the server start script works for you there?
I noticed that the fix Mirsario and I made previously never made it to our stable branch.

Alternatively, try replacing [[ -v steam_server ]]; with [ -z $"{steam_server}+x" ]; 
The -v argument isn't supported on older versions of Mac, but I do want to confirm the latter works for you.
