### ISSUE TITLE
Crash on startup: "Multiple extensions for asset Music\Music_19, (.ogg, .mp3)"

### ISSUE THREAD

**Issue by theluigiduck** [bluemagic123/tModLoader#3140]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Tmodloader crashes on startup: Seems that there are formatting discrepancies with some music files

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10236865/client.log)

### Steps to reproduce

Launch Tmodloader

### Expected Behavior

Tmodloader opens

### Actual Behavior

Tmodloader does not open

### Reproduction frequency

Consistently

### Additional Information

Base Terraria opens fine. Tired verifying the game files' integrity for both Terraria and Tmodloader, had no effect. Tried reinstalling Tmodloader; had no effect. Tried disabling resource packs; had no effect. Have not tried unsubscribing from resource packs; would very much prefer not to do that.

**Comment by acrinym** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/10237837/client.log)
Experiencing the same issue.

**Comment by Cyrillya** [comment]
Disabling all resource packs might help: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-resource-packs

**Comment by acrinym** [comment]
Fixed by going to C:\Program Files (x86)\Steam\steamapps\workshop\content\105600\2440081576\Content\Music
and deleting the extra files. 
But why were they there in the first place?

**Comment by direwolf420** [comment]
This is caused by the ["Terraria Overhaul Music Pack"](https://steamcommunity.com/sharedfiles/filedetails/?id=2440081576) resource pack. Disable it like this: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-resource-packs

**Comment by theluigiduck** [comment]
> This is caused by the ["Terraria Overhaul Music Pack"](https://steamcommunity.com/sharedfiles/filedetails/?id=2440081576) resource pack. Disable it like this: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-resource-packs

Aw, but the Overhaul music is so good... Hope it gets fixed soon

**Comment by theluigiduck** [comment]
> This is caused by the ["Terraria Overhaul Music Pack"](https://steamcommunity.com/sharedfiles/filedetails/?id=2440081576) resource pack. Disable it like this: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-resource-packs

Aw, but the Overhaul music is so good... Hope it gets fixed soon
