### ISSUE TITLE
wave bank.xwb not found 

### ISSUE THREAD

**Issue by Nerathz** [bluemagic123/tModLoader#3149]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

unable to run terraria because the wave bank is missing

![Capture d’écran 2022-12-20 160550](https://user-images.githubusercontent.com/102364784/208698825-bc5b9c41-38a4-4e49-aa18-8e20cd35c16a.png)

### Reproduction frequency

crash when starting 

### Additional Information

i can't play

**Comment by Lebgdu64** [comment]
bruh me too

**Comment by Lebgdu64** [comment]
on steam

**Comment by Nerathz** [comment]
> on steam

yeah but i found how to fix that 
: -do a backup of your mods 
-unistall terraria (and tmod)
-re install your game via steam
-replace tmod in your file  
-and when you start tmodloader don't press enter when you see the red text just close the console
that's all

**Comment by viktortrtre** [comment]
help please.Every time I open the game this error comes out .How to fix it?

**Comment by viktortrtre** [comment]
I can't install the game via steam

**Comment by GeniusNDS** [comment]
> > on steam
> 
> yeah but i found how to fix that : -do a backup of your mods -unistall terraria (and tmod) -re install your game via steam -replace tmod in your file -and when you start tmodloader don't press enter when you see the red text just close the console that's all

Thank you, man! It helps! 👍 
It works also on GOG version.

**Comment by mman35580-tech** [comment]
provide a download link to wave bank.xwb
