### ISSUE TITLE
[JIT] Faulty Override Member JIT Checking Results in Error

### ISSUE THREAD

**Issue by steviegt6** [bluemagic123/tModLoader#3158]
### Version

Latest 1.4-stable

### This bug affects

Mod capability as a Modder

### Description

Faulty check in `AssemblyManager::ForceJITOnMethod` somewhere in here: https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs#L388-L395

Causes an error when implementing an interface within an interface:
```cs
public interface IAnimatedTreeTop
{
    Rectangle? GetTreeTopFrame(Texture2D treeTex, Rectangle regFrame);
}

public interface IAnimatedTreeTopWithDrawAnimation : IAnimatedTreeTop
{
    DrawAnimation TreeTopDrawAnimation { get; }

    Rectangle? IAnimatedTreeTop.GetTreeTopFrame(
        Texture2D treeTex,
        Rectangle regFrame
    )
    {
        // ...
    }
}
```

![image](https://user-images.githubusercontent.com/27323911/209785558-c813d3ec-ea7d-4767-87d0-ea35f98d5ecf.png)

**Comment by absoluteAquarian** [comment]
Bumping this issue.  Trying to use interface inheritance in a similar manner for my Terran Automation mod has also caused problems.

**Comment by Chicken-Bones** [comment]
Please confirm whether the fix works for your default interface methods
