### ISSUE TITLE
setup.bat's setup button error: Terraria Version 1.4.4.9. Expected 1.4.3.6

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3163]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When clicking on the setup button that appears after the dev setup UI appears, I get the message where /src changes will be lost. After clicking "Ok", I immediately receive the message from the setup UI saying "Error: Terraria Version 1.4.4.9. Expected 1.4.3.6"
![image](https://user-images.githubusercontent.com/70764728/210268603-679d33c4-d52c-469a-b484-d9e33d02c12a.png)

I believe it's because the dev setup is meant to be for the very latest developer branch build (1.4.4 branch), but I am not sure.

### Context
I wanted to work on #2987 using the dev setup UI and also learn more about the dev setup UI

### Steps to reproduce

1. Open setup.bat
2. go to Options --> Select Terraria
3. After selecting Terraria, click "Setup"
4. Click "Ok"
5. You should receive the error message on the bottom left corner of the dev setup UI

### Expected Behavior

You would have the "Decompiled" folder in src

### Actual Behavior

You can't get the "Decompiled" folder in src because of the error

### Reproduction frequency

100% of the time

### Additional Information

It would be nice if vanilla terraria can have older versions that match tModLoader's current older versions (if you know what I mean).

**Comment by Solxanich** [comment]
Yes, you are correct that the setup tool for the '1.4' branch is based on 1.4.3.6 Terraria exe. 
The 1.4 branch is only really used for hot fixes right now, as we carry through to preview and stable from it. 

If you are looking to work with a dev copy, I would get 1.4.3.6B terraria exe for 1.4-stable. 
If you are looking to contribute, we recommend targeting 1.4.4 branch. I'll look at the other issue soon

**Comment by Setnour6** [comment]
> Yes, you are correct that the setup tool for the '1.4' branch is based on 1.4.3.6 Terraria exe. The 1.4 branch is only really used for hot fixes right now, as we carry through to preview and stable from it.
> 
> If you are looking to work with a dev copy, I would get 1.4.3.6B terraria exe for 1.4-stable. If you are looking to contribute, we recommend targeting 1.4.4 branch. I'll look at the other issue soon

I don't know how to get 1.4.3.6B for 1.4 stable. I only know the 1.4.3.6 version, and the hashes for it referring to the version as 1.4.3.6.
I am looking to contribute, and I am for sure targeting the 1.4.4 branch.

**Comment by Solxanich** [comment]
Closing as expected behaviour for 1.4-stable/preview/base that only accepts patching from 1.4.3.6B terraria.exe, as unfortunately we don't have control over compatibility.
Rely on workarounds to target 1.4.4

Issue #3164  covers off the issue with 1.4.4 not starting.
