### ISSUE TITLE
Download mods in chunks other than download them in a stream, would result in better ram usage.

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3176]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Title states this. 
Try making the download system download files in chunks, instead of a stream. This issue is most prominent in mods like Calamity Mod Music.
Internet speed is not the issue. Tested on Gigabit internet, on Windows and MacOS

### Steps to reproduce

1. Download a large mod
2. wait 500 years

### Expected Behavior

Download the mod quickly.

### Actual Behavior

Mods don't download.

### Reproduction frequency

100%
this issue occurs every time. 

### Additional Information

You could allow us to receive the mods in a .txt file when connecting to a server, then we could implement our own checks and downloading methods.

**Comment by Chicken-Bones** [comment]
Sorry, tML for Terraria 1.3 is no longer being supported.
