### ISSUE TITLE
Attack speed boosts can create unintended burst-firing

### ISSUE THREAD

**Issue by Tyfyter** [bluemagic123/tModLoader#3179]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Specific attack speed buffs and specific base useTime and useAnimation values combine to change how many shots some weapons fire per-click

### Steps to reproduce

1. set any item capable of burst-firing when useAnimation is greater than useTime to 33 useAnimation and useTime
2. give 10% boost to attack speed
3. shoot the item
4. the item will fire twice

alternatively, apply a 10% attack speed boost then display the results of TotalUseAnimationMultiplier and TotalUseTimeMultiplier, which will be 0.909090936 and 0.9090909 respectively

### Expected Behavior

A single attack speed buff that applies to both useAnimation and useTime should keep the ratio of the two as close to the original ratio as possible

### Actual Behavior

Something — likely floating-point imprecision — causes extremely small differences in how single realistically-sized speed buffs apply to both values at reasonable starting values

**Comment by Chicken-Bones** [comment]
Can you supply an example weapon code please?

**Comment by Tyfyter** [comment]
`using Terraria; 
using Terraria.ID; 
using Terraria.ModLoader; 
  
namespace Example.Items { 
     public class ExampleItem : ModItem { 
         public override void SetDefaults() { 
             Item.CloneDefaults(ItemID.SniperRifle); 
             Item.useAnimation = 33; 
             Item.useTime = 33; 
         } 
 }` should work as an example unless there's some sort of extremely specific condition that I wasn't aware of applying to every gun I tried it with

**Comment by Chicken-Bones** [comment]
Fixed. Please note the fix I chose causes an item with `useTime = 33` to have an animation and use time of `29` under `attackSpeed = 1.1f`. But now they're consistent (not one being 29 and the other 30)

This might be able to be mitigated through use of double, but I'm doubtful of the issues just popping up elsewhere instead.
