### ISSUE TITLE
Odd Visual Bug

### ISSUE THREAD

**Issue by GalaxyDragon245** [bluemagic123/tModLoader#3181]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Recently I started having an odd visual glitch, that appears even without mods and texture packs (Vanilla works fine)

Male characters appear this way: ![Screenshot_6](https://user-images.githubusercontent.com/69798658/211208097-a9464f88-b3e0-4944-b06e-8fde8ad07c97.png)

Female characters appear this way: ![Screenshot_7](https://user-images.githubusercontent.com/69798658/211208098-d819c59e-04ce-442f-ae7f-e08e27bd81e8.png)

Stars appear oddly stretched: ![Screenshot_8](https://user-images.githubusercontent.com/69798658/211208099-489e992a-edd5-4bb4-93fd-a369c5b22dc3.png)

Other things like food appear with a half sprite and certain enemies like demons and vultures have their animation sprite glitched.
I tried verifying the integrity of files and reinstalling, with no avail. Thanks in advance

### Expected Behavior

Textures are applied correctly

### Actual Behavior

The graphics are glitched and messed up

### Reproduction frequency

Every time I start the game

**Comment by Chicken-Bones** [comment]
Does it only happen with certain players or worlds?

**Comment by GalaxyDragon245** [comment]
It happens with every newly created players and every world

**Comment by JavidPack** [comment]
This is caused by texture files left over from an old install. Reinstalling or verifying the game integrity won't work, you need to fully reset the tmodloader install dir. This comes up everyday in our discord, this is what fixes it for everyone:


> Tag: hardreset
> (Steam Instructions) Follow these steps to get a fresh install of your game files:
> Terraria Instructions:
> 1)  Delete the Terraria folder in C:/Program Files (x86)/Steam/steamapps/common.  If you're on a non-Windows computer or have Steam installed elsewhere, type .findinstall in botworld to get to the tModLoader folder, then just go back one folder to end up in the common folder mentioned earlier.
> 2)  Uninstall, then reinstall Terraria in Steam.
> 
> tModLoader Instructions:
> 1)  Delete the tModLoader folder in C:/Program Files (x86)/Steam/steamapps/common.  If you're on a non-Windows computer or have Steam installed elsewhere, type .findinstall in botworld to get to this folder.
> 2)  Uninstall, then reinstall tModLoader in Steam.
> 
> (Note:  your player and world saves are stored in a completely separate folder than the ones mentioned above.  If you delete any other folders, we are not responsible for you losing any of your saves.)
>

**Comment by GalaxyDragon245** [comment]
> This is caused by texture files left over from an old install. Reinstalling or verifying the game integrity won't work, you need to fully reset the tmodloader install dir. This comes up everyday in our discord, this is what fixes it for everyone:
> 
> > Tag: hardreset
> > (Steam Instructions) Follow these steps to get a fresh install of your game files:
> > Terraria Instructions:
> > 
> > 1. Delete the Terraria folder in C:/Program Files (x86)/Steam/steamapps/common.  If you're on a non-Windows computer or have Steam installed elsewhere, type .findinstall in botworld to get to the tModLoader folder, then just go back one folder to end up in the common folder mentioned earlier.
> > 2. Uninstall, then reinstall Terraria in Steam.
> > 
> > tModLoader Instructions:
> > 
> > 1. Delete the tModLoader folder in C:/Program Files (x86)/Steam/steamapps/common.  If you're on a non-Windows computer or have Steam installed elsewhere, type .findinstall in botworld to get to this folder.
> > 2. Uninstall, then reinstall tModLoader in Steam.
> > 
> > (Note:  your player and world saves are stored in a completely separate folder than the ones mentioned above.  If you delete any other folders, we are not responsible for you losing any of your saves.)

I tried fresh installing them but it didn't work

**Comment by JavidPack** [comment]
Are you sure you deleted both the Terraria and tModLoader install folders? There is a possibility you installed the game in multiple locations, I'd double check that the install locations you deleted were the ones steam pointed to. This fix has worked for everyone who reports this in our support channel on discord. If you are still having issues, you might want to come by for live support, going back and forth here won't get anywhere.

**Comment by GalaxyDragon245** [comment]
> Are you sure you deleted both the Terraria and tModLoader install folders? There is a possibility you installed the game in multiple locations, I'd double check that the install locations you deleted were the ones steam pointed to. This fix has worked for everyone who reports this in our support channel on discord. If you are still having issues, you might want to come by for live support, going back and forth here won't get anywhere.

yeah I'm sure, specially because I completely resetted my pc. I deleted both install folders into the steam library (I did click on properties and file location) and also tried to delete the data in documents but I still have the problem

**Comment by JavidPack** [comment]
Ok, well, we'll need to solve this in Discord (tModLoader.net/discord) support, we won't get anywhere going back and forth here with how long that would take.
