### ISSUE TITLE
Newline characters adding space on tooltips

### ISSUE THREAD

**Issue by Tyndareus** [bluemagic123/tModLoader#3185]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Technically the bug affects both, but also doesn't prevent the game from running it just doesn't look right compared to other buffs.

A while back I moved my buff text into a localization file and everything was fine. 
I am recently back checking buff stuff before I move on to the next system test and noticed that theres this huge space between the buff title and the buff description, after some playing around it appears however the sizing is calculated causes this additional spacing to occur with newline characters. 

![image](https://user-images.githubusercontent.com/13440433/211434152-21bb2f7a-4700-4864-b3d9-bc8eac6d734b.png)

There is the first image where I noticed it, and after testing around it simply just _happens_. 

And here is another string just made up of "test\ntest\ntest"
![image](https://user-images.githubusercontent.com/13440433/211434358-686f4af1-5bad-4c79-ba88-45c0991816cc.png)

I am using ModifyBuffTip, so just simply put tip = string.

And here is the same ModifyBuffTip but without the newline characters
![image](https://user-images.githubusercontent.com/13440433/211434433-f6791235-3771-4719-87ce-57b952938742.png)

![image](https://user-images.githubusercontent.com/13440433/211435061-32fac591-b861-4fa2-af9e-62b13f852ed8.png)
Also happens on the Description (ModBuff Description member) which is shown above, the string works normally but when I add the newline characters it decides its had enough.

I have had a poke around with the various commits and updates to see where it may have broke but haven't been able to pinpoint anything yet. (Done things like calling the old code for the chat tags in buff tooltips, and the ChatManager.GetStringSize change for a newline issue that came up previously... #2980? but they didn't seem to change anything).
I have also disabled other mods, only one running is my own.

### Log File

Unfortunately the log doesn't provide anything. Runtime generates the same 'WaveMaskData texture recreated. {resolution}'

### Steps to reproduce

1. Have a buff, or potentially any other tooltip based element but buff is where its been found.
2. Have the tooltip for that buff use newline characters (either Environment.NewLine or \n)
3. See that theres some factor based spacing depending on how many newlines are provided.

### Expected Behavior

There shouldn't be any spacing, especially between the title and description. Theres probably an acceptance for it being after the description (where its not visible)

### Actual Behavior

Using newline characters create a space, either an issue with GetStringSize or how the string is used afterwards. 

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Fixed in #3128, will be in stable once we fix a few more bugs I think.
