### ISSUE TITLE
Mac Server Command Line Incorrectly Assigns the -steam Parameter

### ISSUE THREAD

**Issue by blanky6739** [bluemagic123/tModLoader#3186]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When setting up server in the command line, it asks whether steam server should be used when -steam is an arg.

### Log File

No log file created at this stage of setting up server
<img width="568" alt="image" src="https://user-images.githubusercontent.com/66869807/211465137-0729a813-d72d-47cd-b3d1-236869d2799a.png">

### Steps to reproduce

1. Start server on mac using the command line with the parameter -steam

### Expected Behavior

1. Start server with the command line parameter -steam
2. It should ask for lobby type or start server depending on whether the lobby was specified

### Actual Behavior

1. Start server with the command line parameter -steam
2. It will ask whether steam servers should be used

### Reproduction frequency

100%

### Additional Information

According to my testing, line 31 of `/tModLoader/start-tModLoaderServer.sh` has uneccesary parts which inverts which change the output. Should be
`if [ -z $steam_server ]; then`
instead of 
`if ! [ -z $"{steam_server}+x" ]; then`

The behaviour seems to occur due to $"{steam_server}+x" never being able to be empty due to {steam_server}+x being a string. This leads -z to report it as always having a non 0 length returning false. Then the ! negates it, always leading the expression to be evaluated to true.

**Comment by Solxanich** [comment]
Fixed in #3217
