### ISSUE TITLE
Ошибка в Tmodloader( у меня пиратка)

### ISSUE THREAD

**Issue by didor00** [bluemagic123/tModLoader#3188]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

Когда я включаю tmodloader на пиратку как делают это все мои знакомые .Я захожу в расположения файла и включаю start-tModLoader сначала все как обычно

### Log File

![tModLoader v2022 9 47 17 Fatal Error 11 01 2023 19_48_12](https://user-images.githubusercontent.com/122474439/211874303-522bd620-5072-4fb9-875e-2ae034613b5c.png)

### Steps to reproduce

1 создаем папку и перекидываем все содержимое crfxtyjuj  файла в тот файл и навсякий случай ставим название tModLoader
2заходим в тот файл и ищем start-tModLoader после нажимаем на него и у нас выходит командная строка (она выходит у всех) ждем загрузку в той командной строке (dotnet у меня установлен)

### Expected Behavior

у меня должен запустится tmodloader

### Actual Behavior

вылезает фатальная ошибка(там таки написано)

### Reproduction frequency

всегда могу даже сделать видео

### Additional Information

это ссылка на видео в ютубе https://youtu.be/uuJoULrjrok

**Comment by Mirsario** [comment]
Piracy is not tolerated here, and I suggest you to use English in English communities.
