### ISSUE TITLE
[1.4.4] Wires don't show at all

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3189]
### Version

Other (Latest 1.4.4-Dev)

### OS

Windows 11

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I hold a wire or the Grand Design in this case, no wires display, even when I place wires down
![image](https://user-images.githubusercontent.com/70764728/211879067-7057c27b-fa6a-49c6-916c-4b68dee73adb.png)
Note: In the image, I am actually holding the Grand Design
![image](https://user-images.githubusercontent.com/70764728/211879336-1f974d28-6069-44e9-8fee-730a2f9f2996.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10394764/client.log)

### Steps to reproduce

1. Enter your world
2. Hold wires, or the Grand Design in this case
3. Place wires
4. Check to see if places wires appear.

### Expected Behavior

Wires should display on-screen

### Actual Behavior

Wires do not display on screen

### Reproduction frequency

100% of the time, given the circumstances

### Additional Information

The only mod that is enabled is the Secret Seed Conditions Example, which only adds item drop examples to the Lava bat and Hellbat NPCs.

**Comment by Jadams505** [comment]
Are you using the getfixedboi or fortheworthy seeds? Because in 1.4.4 it is vanilla behavior for the player to not see wires before defeating skeleton in both of those seeds.

**Comment by Setnour6** [comment]
> Are you using the getfixedboi or fortheworthy seeds? Because in 1.4.4 it is vanilla behavior for the player to not see wires before defeating skeleton in both of those seeds.

Yes, I am using the secret seed “getfixedboi”. I forgot to say that earlier

**Comment by Chicken-Bones** [comment]
And have you beaten skeletron?

**Comment by Setnour6** [comment]
> And have you beaten skeletron?

I have not. Does the wires only show if I beat skeletron, and is it an intended function in vanilla Terraria?

**Comment by Chicken-Bones** [comment]
Yes, so you can't just ignore traps. Is vanilla

**Comment by Setnour6** [comment]
I checked the wiki and I found out that it’s actually a real thing, and I somehow missed that one line of information. Now I learned something 😆
