### ISSUE TITLE
Add UseImageX method overloads

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#3196]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Currently, there no way to apply modded texture to shaders (armor or misc) without reflection. Which might be disappointing and confusing at first.

### What does this proposal attempt to solve or improve?

New method overloads could let modders use their own sprites instead of creating extension method and using reflection or simply using vanilla sprites.

**Comment by JavidPack** [comment]
This is certainly something I've heard mentioned before. My initial thought is replacing `Main.Assets.Request` calls with `ModContent.Request` and changing things like `UseImage("Images/Misc/noise")` to `UseImage("Terraria/Images/Misc/noise")`, but I fear that will end up being a lot of code to maintain.

Another thought I had was adding an overload that accepts a `Asset<Texture2D>` directly, this could allow runtime generated texture assets to be used as well.

If you still plan on contributing this and need help or want to plan out your approach, feel free to chat with us in the #collaborators channel of the tModLoader Discord.

**Comment by BasicallyIAmFox** [comment]
👍

**Comment by steviegt6** [comment]
> This is certainly something I've heard mentioned before. My initial thought is replacing `Main.Assets.Request` calls with `ModContent.Request` and changing things like `UseImage("Images/Misc/noise")` to `UseImage("Terraria/Images/Misc/noise")`, but I fear that will end up being a lot of code to maintain.
> 
> Another thought I had was adding an overload that accepts a `Asset<Texture2D>` directly, this could allow runtime generated texture assets to be used as well.
> 
> If you still plan on contributing this and need help or want to plan out your approach, feel free to chat with us in the #collaborators channel of the tModLoader Discord.

I'm more in support of the latter rather than the former, though I wouldn't necessarily mind both.
