### ISSUE TITLE
Mounts do not show or show incorrectly to other players in multiplayer

### ISSUE THREAD

**Issue by Mach12** [bluemagic123/tModLoader#32]
When riding a mount in multiplayer, other players will see the rider still on foot, at regular speed, periodically teleporting back to actual position, airborne included. Flying on a mount effectively makes others see one repeatedly fall from where one actually is.

**Comment by gamrguy** [comment]
Is this with a modded mount or all mounts?

**Comment by Mach12** [comment]
All mounts. It was also tested with an Antlion charger mount which is vanilla.

**Comment by bluemagic123** [comment]
Does the same thing happen in vanilla? I remember also seeing some mount-related glitches while playing vanilla with my brother.

**Comment by JavidPack** [comment]
Can anyone confirm this bug is happening in the latest version? If not, we should close this since it was probably the buffid bug.

**Comment by JavidPack** [comment]
K, seeing no response, I'll assume this was a modders error.
