### ISSUE TITLE
Friends Can't Join

### ISSUE THREAD

**Issue by RomanTheGithub** [bluemagic123/tModLoader#3202]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Opening tModLoader, it says I'm playing Terraria, and invites/joins will not work for my friends.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10472673/client.log)

### Steps to reproduce

1. Open tModLoader
2. Invite a friend/ask them to join you
3. There will be no join option on the profile/invite/anywhere

### Expected Behavior

It should say I'm playing tModLoader, and friends should be able to join.

### Actual Behavior

It says I'm in Terraria, and invites won't have the Join button, and right clicking my profile won't either.

### Reproduction frequency

95% of the time.

### Additional Information

There is a workaround if you start Terraria, wait for it to open, then open tModLoader and then close Terraria, though I often forget to do this, and it's quite inconvenient. (Clicking Stop on Terraria whilst tModLoader is running does nothing, so it requires me to fully restart my game, and reload all mods if I ever forget.)

**Comment by direwolf420** [comment]
if someone shows as playing Terraria, have them keep restarting the game until it shows as tModLoader. Unavoidable race condition

**Comment by Chicken-Bones** [comment]
Another workaround is to use the `start-tModLoader.bat` file in the steam install directory. Then you will always only launch `tModLoader`

**Comment by RomanTheGithub** [comment]
I am using Mac

**Comment by Chicken-Bones** [comment]
`start-tModLoader.sh` for you then

**Comment by stomarver** [comment]
You have saved our survival route

**Comment by PedroZborowski** [comment]
I made an open source repo that explains the bug and installs a shortcut that launches tMod in a specific way so that it launches as tMod: https://github.com/PedroZborowski/tmod-multiplayer-linux-launcher
