### ISSUE TITLE
Weird char put as the first char when reading the content of a json file in my mod

### ISSUE THREAD

**Issue by Ishigh1** [bluemagic123/tModLoader#3205]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

So I've got this little file here that should be read as a JSON array, but it refused to be read for a while because of a bad character
[Goals.json](https://github.com/tModLoader/tModLoader/files/10482100/Goals.txt)
Turns out if you read the file with the usual code
`byte[] fileBytes = ModContent.GetInstance<BingoModClass>().GetFileBytes("Goals/Goals.json");`
`string text = Encoding.UTF8.GetString(fileBytes);`
then `text` has an extra character at space 0, with value `65279 '﻿'` according to the debugger, which completely screws the JSON reader
This character appears nowhere else and can be easily removed by removing the first character, but it's still a weird issue to me and could be more annoying if it appears in other places for some reason
No clue of how to test more about this issue so I can't be more complete though

**Comment by JavidPack** [comment]
Sounds like you are running into an issue with UTF-8-BOM encoding. You can use notepad++ to change your text file to UTF-8 instead, then save it.

This is a mod making issue, not a bug in tmodloader. You should ask these questions on the tmodloader discord from now on.

**Comment by Ishigh1** [comment]
I did say it there first and no one mentioned I could be having an issue with the encoding

**Comment by Chicken-Bones** [comment]
As jopo mentioned, it sounds like UTF8-BOM. It's worth doing a quick read on BOM on wikipedia or similar.

Note that UTF8-BOM is not recommended these days, unless you have an explicit reason where the consumer of your text file does do BOM detecting for encodings, and does not parse as UTF8 by default.

Thus the preferred solution is to save all your files without BOM (which you can do in Notepad++ for example under the encoding setting).

If you want to convert bytes to UTF8 and automatically ignore an optional BOM, you can use `new UTF8Encoding().GetString(bytes)`. See https://learn.microsoft.com/en-us/dotnet/api/system.text.utf8encoding?view=net-6.0
