### ISSUE TITLE
IL Editing QoL Additions

### ISSUE THREAD

**Issue by Destructor-Ben** [bluemagic123/tModLoader#3213]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

1) Generate text files of IL before and after a method is edited, and create a diff of them. This could be done either automatically or a modder manually calling a method like `WriteILToFile(Mod mod, ILContext il)`, or `CreateILDiff(string filePath1, string filePath2)`.

2) A method that logs an error indicating that a mods IL editing has failed, e.g. "IL Patch Error: Mod 'XX' failed to patch method 'XX' in '{Class that did the patching}'". This isn't that important, but it would allow for consistent and detailed error messages between mods.

### What does this proposal attempt to solve or improve?

Currently, IL editing is painful because there isn't an easy way to actually tell what went wrong. With this, there is a consistent error message when IL editing fails and modders can easily check what changes their code actually made.

### Which (other) solutions should be considered?

Allowing modders to implement this themselves. This would require examples of how to do this in EM instead of being built into tML.

EDIT:

This should also include dumping a list of registered IL hooks and detours (moved from https://github.com/tModLoader/tModLoader/pull/3240)

**Comment by Chicken-Bones** [comment]
For suggestion 2, what happens currently? What kind of failures do you want to protect against. Can you provide sample code which throws an unhelpful error?

**Comment by Destructor-Ben** [comment]
> what happens currently?

I think most mods just say something like "IL edit failed" or don't say anything when a patch fails, though some have detailed error messages. I know at least 2 that don't have patch fail messages.


> What kind of failures do you want to protect against.

When the game updates some mods IL edits might not get updated and will fail, so it can help modders that aren't actively working their mods to fix them without hassle. It also is consistent, so you can always expect to get a lot of information no matter each mods implementation of the error message.

> Can you provide sample code which throws an unhelpful error?

This is the worst I've found so far:
`mod.Logger.Error("Do you want a cake?");`
This probably only exists so the mod developer knows that there is an error, but it doesn't say where.

One of the best I've found is Calamity, which has its own LogFaliure method for IL editing fails, which looks like this:
```
public static void LogFailure(string name, string reason)
{
	CalamityMod.Instance.Logger.Warn("IL edit \"" + name + "\" failed! " + reason);
}
```
Magic storage is also great but I can't be bothered pasting a snippet of code here, though one thing it does is track how many patches it has been able to do successfully until an error occurs.

I typically put this method in my mod class:
```
// Ideally, this would also tell me the line or TryGoto it failed on to track down bugs even faster
public static void ILPatchError(ILContext il, object patchingClass, string name, string reason)
{
    Instance.Logger.Warn($"{Instance.Name} IL Patch Error: Failed to patch method \"{il.Method.Name.Replace("::", ".")}\" for \"{name}\" in \"{patchingClass.GetType().Name.Replace("::", ".")}\". Reason: {reason}");
}
```

And use it accordingly:
```
if (!c.TryGotoNext(i => i.MatchLdcI4(0))
{
    ModName.ILPatchError(il, this, "Example feature", "Unable to locate <insert>");
    return;
}
```

**Comment by Chicken-Bones** [comment]
I see, so you're not suggesting tML automatically log failures, because there's no exception or way for tML to detect that a patch has failed. Instead you're proposing a helper method mods could use to standardise the logging and add helpful info.

I think this is easy enough, but educating modders so they actually use it would be a challenge

**Comment by Destructor-Ben** [comment]
> I see, so you're not suggesting tML automatically log failures, because there's no exception or way for tML to detect that a patch has failed. Instead you're proposing a helper method mods could use to standardise the logging and add helpful info.
> 
> I think this is easy enough, but educating modders so they actually use it would be a challenge

I wiill put it in the wiki and in Example mod when I do this, but it definitely won't be enough. 

On a different note, should the implementation for the IL dumps and diffs be helper methods as well? I can't think of any other way of doing it other than modifying HookEndpointManager.Modify to automatically do it, since you can't rely on the autogenerated hooks because modders might use reflection. You will also only want it to generate it if you're developing mods, since it could make loading times longer.

**Comment by Chicken-Bones** [comment]
I'm tempted to do a MonoMod PR for this. It's entirely possible to dump the before-after of each manuipulator automatically. We could hook MonoMod itself in TML too.

Relevant line is: https://github.com/MonoMod/MonoMod/blob/master/MonoMod.Utils/Cil/ILContext.cs#L86
