### ISSUE TITLE
Steam Version Won't Start Up Silent Crashing!

### ISSUE THREAD

**Issue by DerpyPandaKitty** [bluemagic123/tModLoader#3234]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I can't get TML to load up at all. Silent Crashes! Here are my Logs!
Attempts to Fix the issue at this discord Thread on tModLoader discord Support Forum!
https://discordapp.com/channels/103110554649894912/1071341299778719794

[Natives.log](https://github.com/tModLoader/tModLoader/files/10608208/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/10608209/terrariasteamclient.log)
[client.log](https://github.com/tModLoader/tModLoader/files/10608210/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/10608211/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/10608212/Launch.log)

### Steps to reproduce

1. Open Steam
2. Click play on tModLoader
3. Wait for game to launch
4. Nothing happens
5. Game shuts self down

### Expected Behavior

When I Launch tModLoader for the game to actually start up!

### Actual Behavior

Nothing! Legit Nothing! No Game, No Error Codes **NOTHING!**

### Reproduction frequency

99% of the time It happens I got it to launch once then restarted game and haven't been able to play since.

### Additional Information

Got help from Rijam a Contributor Ran out of ideas!

**Comment by JavidPack** [comment]
I'm assuming you either figured it out or gave up, feel free to reopen if you still need help.
