### ISSUE TITLE
tModLoader v2022.9.4.30 and 1.4.3.6 issue; 'Load failed! No backup found' when world was literally just generated 

### ISSUE THREAD

**Issue by spazzleweed** [bluemagic123/tModLoader#3235]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I can't create/play any worlds.

Whenever I try to enter a world (even a freshly created one) it states "Load failed! No backup found."

I've tried re-verifying the files. Tried making backups. Completely uninstalled and re-installed it.

Nothing seems to work.

Modlist is as below
- Summoners Association
- - Max stack plus extra
- Advanced world generation
- Shorter respawn time
- cheat sheet
- Which mod is this from?
- cheat extension for hero's/cheat sheet
- hero's mod
- antisocial
- auto trash
- ore excavator
- compare item stats
- Fargos crafting tree generator
- wing slot extra
- armor modifiers & reforging
- Omni swing
- recipe browser
- MoreZenithItems
- Banner Bonanza
- Potions charms
- lights and shadow
- Planet World
- Census
- Auto reforge
- ParticleLibrary
- Impact Library
- Subworld Library
- Structure Helper
- Bestiary shows all loot
- Boss bag glows in Inventory
- TWAILA
- Better crafting interface
- Improved movement visuals
- Boss cursor
- Better Blending
- Recipe Browser && Magic Storage
- Atmospheric Torches
- Lighting Essentials
- Brighter Torches
- zzp198's Weaponout
- imkSushi's Mod
- Ultimate Banner Merging
- Calamity Difficulty Buttons
- WorldGen Previewer
- Koko Net Lib
- Loot Beams
- WysteriaMod
- Item Checklist
- Town NPC Shop Text
- Fargos Soul mod DLC
- Magic Storage
- The Stars Above
- The Amulet of Many Munions: Combat Pets
- Fargos Mutant Mod
- AlchemistNPC Lite
- Echoes of the Ancients
- Ancient's Arsenal
- Rothus Mod
- Boss Checklist
- Aequus
- Liber Creaturarum
- Assorted Crazy Things
- Weapon Enchantments
- Fargo's Souls Mod
- Calamity Mod
- Calamirt's Vanities
- Secrets of the Shadows
- Universe of Swords Reborn
- Mod of Redemption
- Thorium

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10608592/client.log)

### Steps to reproduce

1.) Create fresh world
2.) Try and enter fresh world
3.) "Load failed! No backup found."

### Expected Behavior

Should be able to enter a freshly created world

### Reproduction frequency

100% of the time

**Comment by Rijam** [comment]
Disable the Calamity difficulty buttons in the Fargo's Mutant Mod configs.
