### ISSUE TITLE
Terraria Server Docker is failing to start

### ISSUE THREAD

**Issue by robin-thoene** [bluemagic123/tModLoader#3236]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to start a tmodloader terraria server on ubuntu using docker, the startup of the container fails after adding the mod content.

## The following log is taken from the docker container startup:

steamcmd found...
No workshop mods to install
Moving mods to /home/tml/.local/share/Terraria/tModLoader/Mods
Copying .tmod files to the mods directory
Copying enabled.json to the mods directory
Copying serverconfig.txt to the install directory
Launching tModLoader...
You are on platform: "Linux"
Verifying .NET....
This may take a few moments.
Logging to /home/tml/tModLoader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/home/tml/tModLoader/dotnet/6.0.0"
cat: can't open '/home/tml/tModLoader/cli-argsConfig.txt': No such file or directory
Loaded Custom Arguments:
Attempting Launch...
Launched Using Local Dotnet
Permission denied (see server.log for full trace)
Finding Mods...
Sandboxing: Better Boss Health Bar v0.8.2.1
Sandboxing: Boss Checklist v1.3.9
Sandboxing: Calamity Mod v2.0.1.5
Sandboxing: Fargo's Best of Both Worlds v0.2.1
Sandboxing: Magic Storage v0.5.7.9
Sandboxing: Recipe Browser v0.9.6.1
Sandboxing: Wing Slot Extra v1.3.4
Constructing Mods...
Adding Content: tModLoader v2022.9.47.31
Adding Content: Better Boss Health Bar v0.8.2.1
Adding Content: Boss Checklist v1.3.9
Adding Content: Calamity Mod v2.0.1.5
Adding Content: Fargo's Best of Both Worlds v0.2.1
Adding Content: Magic Storage v0.5.7.9
/home/tml/tModLoader/start-tModLoaderServer.sh: line 55:    31 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args

## Steps

1. connect to linux 
2. mkdir tmodloader
3. cd tmodloader
4. wget https://raw.githubusercontent.com/tModLoader/tModLoader/3f8a16291efbcf3a053d5be6a43320cd234803d1/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Docker/Dockerfile
5. wget https://raw.githubusercontent.com/tModLoader/tModLoader/3f8a16291efbcf3a053d5be6a43320cd234803d1/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Docker/docker-compose.yml
6. Remove docker-compose version line because 1.0 throws an error on my machine indicating the version 1.0 is wrong
7. mkdir Terraria
8. create serverconfig.txt with the following content:
9. create enabled.json with the following content:
10. copy the .tmod files to the Terraria folder
11. I do not edit the compose file with GID and UID because 1000 is my user that shall start the server
12. cd .. (we are now in the folder tmodloader)
13. run docker-compose build
14. run docker-compose up

### Content of `serverconfig.txt`

world=/home/tml/.local/share/Terraria/tModLoader/Worlds/Molfsland.wld \
autocreate=3 \
worldname=Molfsland

### Content of `enabled.json`

[ \
"BetterBossBar", \
"BossChecklist", \
"FargoSeeds", \
"MagicStorage", \
"RecipeBrowser", \
"WingSlotExtra", \
"CalamityMod" \
]

### Screenshot of the Terraria folder structure

![215349786-851f984e-7145-47c3-8e86-906a3a3fd365](https://user-images.githubusercontent.com/110201991/216773426-70e47b50-0640-420a-aa37-a3f2c7de76c4.png)

### Expected Behavior

The container starts and the terraria server with loaded mods is available.

### Actual Behavior

The startup of the container fails with the following error:

`/home/tml/tModLoader/start-tModLoaderServer.sh: line 55:    31 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args`

### Reproduction frequency

Every time.

### Additional Information

This is related to another issue reported before:

https://github.com/tModLoader/tModLoader/issues/3223

**Comment by robin-thoene** [comment]
This is related to another issue reported before:

https://github.com/tModLoader/tModLoader/issues/3223

**Comment by shinysocks** [comment]
Same issue on Ubuntu Server.

**Comment by shinysocks** [comment]
Follow these steps: https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#using-the-docker-container
You should get a different bug... #3319

**Comment by johnnytony** [comment]
@robin-thoene have you find out what was the issue?
I am having the same exact problem.

**Comment by robin-thoene** [comment]
> @robin-thoene have you find out what was the issue? I am having the same exact problem.

Hey @ryzenboi98, I am sorry, my friends lost interest in playing Terraria shortly after I submitted this issue so I did not investigated any further.
