### ISSUE TITLE
[1.4.4.9] @linux Does not find dotnet sdk 6 (in game at develop mods button) but it is installed

### ISSUE THREAD

**Issue by Unftf** [bluemagic123/tModLoader#3237]
### Version

Latest 1.4-preview

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

While testing the 1.4.4.9 beta branch the game did not found dotnet sdk 6 which I installed on the system.
I was unable to build my mods in 'Develop Mods' menu.

But if I type that command into bash I get:
```
~$ dotnet --list-sdks
6.0.405 [/usr/share/dotnet/sdk]`
```

I installed it with
```
sudo apt-get install dotnet-sdk-6.0 
from rep: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
```

### Log File

On clicking onto it I get this error message in bash:
```
[Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "dotnet" --list-sdks
[Main Thread/INFO] [tML]: 

[Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan\1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Terraria.ModLoader.UI.UIModSources.CheckDotnet() in tModLoader\Terraria\ModLoader\UI\UIModSources.cs:line 284
   at Terraria.ModLoader.UI.UIModSources.ShowInfoMessages() in tModLoader\Terraria\ModLoader\UI\UIModSources.cs:line 252
   at Terraria.ModLoader.UI.UIModSources.OnActivate() in tModLoader\Terraria\ModLoader\UI\UIModSources.cs:line 230
   at Terraria.UI.UIElement.Activate() in tModLoader\Terraria\UI\UIElement.cs:line 452
   at Terraria.UI.UserInterface.SetState(UIState state) in tModLoader\Terraria\UI\UserInterface.cs:line 262
   at Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenModSourcesMenu(UIMouseEvent evt, UIElement listeningElement) in tModLoader\Terraria\GameContent\UI\States\UIWorkshopHub.TML.cs:line 83
   ..

[Main Thread/DEBUG] [tML]: 'dotnet --list-sdks' check failed: 
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Terraria.ModLoader.UI.UIModSources.CheckDotnet() in tModLoader\Terraria\ModLoader\UI\UIModSources.cs:line 284
```

### Steps to reproduce

1.Select the 1.4.4 preview as beta branch in steam and update tModloader
2.Start tModloader
3.Click Workshop -> Develop Mods
-> Game drops the error message posted above and says I have to download .NET 6 SDK

### Expected Behavior

Expected to build my mods there as in the versions before

### Actual Behavior

tModloader don't allow my to build my mods in game

### Reproduction frequency

always

### Additional Information

It does also **not** work at the 1.4.3.6 -preview beta build
But it **does** work at the 1.4.3.6 stable build 

Removing the tModloader game folder + downloading again, verify data, restart the system did not work out.

If I used dotnet build inside my mod source folder (on linux with 1449 preview) I get the following error:
```
dotnet : symbol lookup error : ..../steamapps/common/tModLoader/Libraries/Native/Linux/libFNA3D.so.0: undefined symbol: SDL_SIMDRealloc [..../Terraria/tModLoader/ModSources/modname/modname.csproj]
..../steamapps/common/tModLoader/tMLMod.targets(21,3): error MSB3073: The command "dotnet tModLoader.dll -server -build ..../Terraria/tModLoader/ModSources/modname/ -eac ..../Terraria/tModLoader/ModSources/modname/bin/Debug/net6.0/modname.dll -define "TRACE;DEBUG;NET;NET6_0;NETCOREAPP;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER" -unsafe false " exited with code 127. [..../Terraria/tModLoader/ModSources/modname/modname.csproj]
```

EDIT:
It can be compiled in command line (+ tmod file):
`tModLoader/start-tModLoader.sh -build <YourModFolder>`

**Comment by Fili-pk** [comment]
The same issue also occurs on Fedora Linux

**Comment by shinysocks** [comment]
Same issue occuring within the Docker container.

**Comment by shinysocks** [comment]
Follow these steps: https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#using-the-docker-container

**Comment by Fili-pk** [comment]
I found out that problem in code in  src/tModLoader/Terraria/ModLoader/UI/UIModSources.cs on line 275
```c#
string output = Process.Start(new ProcessStartInfo{
    FileName = "dotnet",
    Arguments = "--list-sdks",
    UseShellExecute = false,
    RedirectStandardOutput = true
})!.StandardOutput.ReadToEnd();
```
This code checks for available sdks in dotnet located in "tModLoader/dotnet/6.0.0/dotnet" instead of system one. Which results in returning no sdks.
Workaround: deleating dotnet located in tModLoader directory after starting game.

**Comment by boomdoom123** [comment]
This isnt solved, I dont want a workaround, I want a solution ://

**Comment by Fili-pk** [comment]
> This isnt solved, I dont want a workaround, I want a solution ://

What do you mean?

**Comment by MechWaffle** [comment]
This issue is still not resolved for all linux machines. I am running on KDE Neon with dotnet 6.0.119, and my tmodloader still does not recognize the system dotnet version on the 1.4.4-preview. 

This is what shows up in client.log when trying to enter the develop mods section in tmodloader:
```
[00:06:03.064] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "which" dotnet
[00:06:03.091] [Main Thread/DEBUG] [tML]: Can't find dotnet on PATH
```
But when trying to use the which command in my terminal, I get this:
```
~$ which dotnet
/usr/bin/dotnet
```
Also when listing sdks using my system's dotnet, I get this:
```
~$ dotnet --list-sdks
6.0.119 [/usr/lib/dotnet/sdk]
```

**Comment by Chicken-Bones** [comment]
This might be resolvable by changing `UseShellExecute = True` but the root of the current issue is that the `PATH` is not updated with the location of `dotnet` at the time that steam launches, instead it comes directly to your shell (somehow).

**Comment by Chicken-Bones** [comment]
Please contact me on Discord and I will send you a test build to see if it resolves your issue.

**Comment by MechWaffle** [comment]
I sent you a dm on discord.

**Comment by Chicken-Bones** [comment]
For others curious:
- Proton will block tML from seeing/using the system dotnet sdk for linux users. tML doesn't support proton in general.
- Flatpak will also block tML from seeing/using the system dotnet sdk due to sandboxing. A message has been added in 2d3d2a4

**Comment by TheSkyFather** [comment]
Hi my dear friend. I recorded a video about this problem. Solved

https://youtu.be/SagJ4sI45lk

**Comment by Chicken-Bones** [comment]
> Hi my dear friend. I recorded a video about this problem. Solved
> 
> https://youtu.be/SagJ4sI45lk

Please note that while this video may be helpful to some users, we have taken steps to ensure that all dotnet sdk installs on Linux work _automatically_ as much as possible, so installing to specific locations and passing `DOTNET_ROOT` environment variables should not be required.
