### ISSUE TITLE
[1.4.4] About `ContainerName` Code Update

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3239]
Not something that is too serious, but...

I'm trying to update some 1.4.3.6 code towards 1.4.4.9 to test features (even though 1.4.4.9 TML is meant for testing.
The problem is that some methods have not been updated by TMPorter, like ContainerName (in the case of applying the intended method). I tried to fix the errors in the code manually, but I do not know how to do it, and I'm stuck on the original method name being `ContainerName.SetDefault()`
![image](https://user-images.githubusercontent.com/70764728/216787652-556c83cc-8bf9-4a09-8534-fe9b0cba7313.png)
The new method uses tile frames x and y, and I don't know how exactly I can incorporate them without further trouble.
![image](https://user-images.githubusercontent.com/70764728/216787743-be17aa40-26b9-4521-9dc7-e686053b9c2d.png)

I guess providing more functions and code change directions for tModPorter could work. I had to manually change `SetDefaults` to `ToNetworkText`, and I don't know if that's the right thing to do.
The GitHub Wiki should have 1.4.4 pages that describe item information and other such things regarding code changes. A 1.4.4 migration guide should also be present, but I suppose it's being worked on.

**Comment by JavidPack** [comment]
We are still in the process of redesigning ContainerName, once the Tile Item drop changes are merged into 1.4.4, we'll make sure to address this.

**Comment by Setnour6** [comment]
Wait when was this finished @JavidPack? I haven’t heard or seen any commits that resolve this issue.
Edit: nevermind I see it now. #3311
