### ISSUE TITLE
Calamity Mod Corruption, Unable to find file

### ISSUE THREAD

**Issue by jacobhallburns** [bluemagic123/tModLoader#3266]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![Screenshot (12)](https://user-images.githubusercontent.com/118143191/220531741-7114cad0-a9c6-437a-ae21-6b713c636121.png)

It was running fine for a while. I have uninstalled the mods, tModLoader, and deleted all the files off of my PC. Redownloaded it all and it still will not work. 

Thank you so much for the help!

**Comment by Kogsey** [comment]
Looks like an issue with calamity mod, not tModLoader, it's probably just a renamed .cs file without renaming the .png tbh
