### ISSUE TITLE
My world is not loading. And i have a backup but that too refuses to load.

### ISSUE THREAD

**Issue by Wiinniewhoo** [bluemagic123/tModLoader#3268]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I saved my world and shut down my computer. now when i reload tmod and select my world, it doesent have a title, and it says "load failed" i have checked in my files, and yes i do have a backup but it wont load properly.

### Log File

![Screenshot_20230225_100823](https://user-images.githubusercontent.com/126295866/221318332-b5bd870d-9d26-44fd-8bf7-f276f2a39b0a.png)

### Expected Behavior

The world should load.

### Actual Behavior

its not loading.

### Reproduction frequency

This is the first time ive ran into this issue.

**Comment by George0079** [comment]
I'm having the same problem. I just got back into modding, updated my game and my mods since I knew the last update was a month ago, and I assumed all of the bugs would've been ironed out on the modder's side.

I've been looking for solutions, and so far the only reference is to a mod titled "Large World Enabler" that no longer exists, since some conflicts happen with the world's size limit.

**Comment by George0079** [comment]
By any chance do you have the Calamity difficulty buttons mod active? I just turned mine off and the game suddenly became functional.

**Comment by Wiinniewhoo** [comment]
> By any chance do you have the Calamity difficulty buttons mod active? I just turned mine off and the game suddenly became functional.

Sadly i don't, i disabled all my mods but it still doesn't work :(

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. 

For support, I'd suggest coming to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support. Other things to try are disabling all mods or restoring the world from an older backup (see FAQ).
