### ISSUE TITLE
liquids really slow inside of multiplayer...

### ISSUE THREAD

**Issue by Wapplee** [bluemagic123/tModLoader#3269]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when pouring honey and hosting a multiplayer server, you will notice it will almost never fall.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10829827/client.log)

### Steps to reproduce

1. pour slow liquid
2. done

### Expected Behavior

water should move fast

### Actual Behavior

water is slowmo or something

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
I haven't seen any other reports of this since this report, did this issue ever clear up for you?
