### ISSUE TITLE
Attack speed changes lead to itemTime desyncs

### ISSUE THREAD

**Issue by Altixal** [bluemagic123/tModLoader#3270]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Certain weapons that usually fire once per use can fire twice by modifying attack speeds to specific amounts

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10832297/client.log)

### Steps to reproduce

1. Decrease attack speed by 15%, this can be done for any specific class or generic damage class
2. Obtain any shooting weapon with useTime and useAnimation both equal to 17 or 34 (ie. Paper Airplanes or Tactical Shotgun) which is affected by the prior attack speed change
3. Use the weapon once, causing two bursts of projectiles

This may be reproduced with other specific ratios which also results in float rounding errors ( previously found #3179 )

### Expected Behavior

The player's itemAnimation and itemTime should match up and equal to itemAnimationMax on the first frame of usage and run out at the same time, causing the weapon to shoot once as intended.

### Actual Behavior

The itemTime has a lower offset by 1, causing the weapon to shoot an additional time on its final frame of use.

For auto-reusing weapons, itemTime continues to desync as the player keeps using the item, though any differences in use time seem marginal at that point as the player maintains a constant fire rate.

### Reproduction frequency

Always replicable

### Additional Information

Mod source file used to replicate and diagnose the issue:

[Debug.zip](https://github.com/tModLoader/tModLoader/files/10832303/Debug.zip)

**Comment by Chicken-Bones** [comment]
Unable to reproduce on 1.4.4, both `useTime` and `useAnimation` go from `17 -> 19` with `attackSpeed -=0.15f`

**Comment by DarkWav** [comment]
<details>
<summary>Original Comment</summary>
I'm experiencing this too when equipping itemes with the Melee Speed modifer

- `item.useTime` and `item.useAnimation` are not adjust at all when using melee speed.
- Only `player.itemAnimationMax` is reduced by the correct amount, however, `player.itemTimeMax` is not.
- `player.itemTimeMax` stays at the original value without any reduction, even when wearing a lot of melee speed accessories.

This causes the useTime/useAnimation ratio to seemingly get corrupted.

**My question: is it intended that "Melee Speed" only reduced the item's useAnimation and not the useTime?**
</details>

**EDIT: Nevermind, I think this is intended and I found a solution for my usecase.**
The wiki even states that melee speed does not generally affect `player.itemTimeMax`: https://terraria.wiki.gg/wiki/Attack_speed

**Comment by Chicken-Bones** [comment]
@DarkWav specifically, in tML, the vanilla behaviour mentioned in the wiki is enabled for vanilla items only, and is controlled by the `Item.attackSpeedOnlyAffectsWeaponAnimation` field

**Comment by DarkWav** [comment]
@Chicken-Bones thanks for this insights, that is going to be very useful.
I've noticed that it sometimes has rounding errors and will reduce `player.itemTimeMax` by one less than `player.itemAnimationMax`, but managed to work around that without problems with a `UseTimeMultiplier` override.
