### ISSUE TITLE
[BUG as well] "start-tModLoaderServer" allow friends of friends does not exist

### ISSUE THREAD

**Issue by BeyondMagic** [bluemagic123/tModLoader#3279]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Doesn't have an option to enable the option of "Host & Play" in Terraria's menu to host a server of "Allow Friends of Friends".

### Expected Behavior

Should have such option to enable on the "serverconfig.txt" or by the command-line.

**Comment by JavidPack** [comment]
So, Terraria doesn't seem to have this in their server launch scripts or configs either, so it might be better for us to ask them to update their scripts.

In the meantime, it looks like you can add ` -friendsoffriends` as a command line parameter to however you are launching the server and it should do that.

**Comment by JavidPack** [comment]
Ok, I've added an option to the launch script, it'll be in 1.4.4 later.
