### ISSUE TITLE
Add ItemID.Sets.SlimeDrops

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#3283]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

`ItemID.Sets.SlimeDrops` is a `Dictionary<int, (int minStack, int maxStack)>` which allows modders to add or change the ores that can appear and drop from slimes.

### What does this proposal attempt to solve or improve?

This new feature would allow easier implementation of alternative ores.

**Comment by Chicken-Bones** [comment]
This seems fine to go ahead with, in the same vein as geodes
