### ISSUE TITLE
Cleanup Mods Menu on Preview builds to be easier to work with / localization

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#3286]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Bug: 
Hovering over the obsidian skull warning on preview builds doesn't load the correct localized tooltip.

Feature: 
We maybe should also offer filter option on preview builds to 'Hide Potential Unsupported Mods' or something like that, so that not skimming a list for what actually works.

**Comment by JavidPack** [comment]
I think we added a panel showing that a mod is for an older version now, is this good to close now?

**Comment by Solxanich** [comment]
I think still an outstanding bug that "Enable All" ignores unusable versions. 
This can be closed in favor of a separate bug report though
