### ISSUE TITLE
The official TModLoader website has a dead link (the Documentation link leads to a dead 404 error page not found website)

### ISSUE THREAD

**Issue by ExLuck6** [bluemagic123/tModLoader#3288]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The official tModloader website has a dead link in it, the documentation button leads to a 404 page not found website.

### Log File

![image](https://user-images.githubusercontent.com/109993483/223251674-e539ec8b-a145-4650-9071-c66c2c37d1e8.png)

### Steps to reproduce

1. Go to https://www.tmodloader.net/
2. Click "Documentation"
3. it will lead to this page https://docs.tmodloader.net/html/index.html

### Expected Behavior

It should lead to the actual documentation. 

### Actual Behavior

it leads to a 404 page not found

### Reproduction frequency

Every time I click the documentation button in the official website

**Comment by JavidPack** [comment]
Ok, I've added a redirect to the correct page. Thanks.
