### ISSUE TITLE
[1.4.4.9] workshop upload not working anymore: 'Mod version information must be incremented prior to updating' (did that)

### ISSUE THREAD

**Issue by Unftf** [bluemagic123/tModLoader#3294]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

If I try to upload a new version of my mod it always tells me I have to increment the mod version.
I did that in build.tx.t and changelog.txt. I also tried way bigger numbers. Did not help.

I always rebuild+reload before pressing the publish button.
The new mod version is also shown at the mod menu.

Reinstalling tModloader multiple times did not help. Verifying also had not effect.

It worked fine on earlier tModloader update in February. Did changed nothing else.
Also tested my old published mod version with just a higher version number in build.txt  -> same error

I'm trying to update from 0.4.1.15 to 0.4.2.0
At the steam workshop page it is also showing 0.4.1.15 as most recent update.

### Log File

log files also show nothing special except this:
except in Launch.log:
```
mv: can't rename '(mypathtosteam)/Steam/SteamApps/common/tModLoader/Libraries/Steamworks.NET': Permission denied
'(mypathtosteam)/Steam/SteamApps/common/tModLoader/Libraries/Steamworks.NET' -> '(mypathtosteam)/Steam/SteamApps/common/tModLoader/Libraries/steamworks.net/Steamworks.NET'
```
The folder is named steamworks.net but has no sub folder 'Steamworks.NET' but instead named '20.1.0'. Introducing another Steamworks.NET folder inside the steamworks.net will result in a game not working anymore.
(No anti-virus program was running during this)

```
and in client.log
'[15:40:06.227] [Main Thread/ERROR] [tML]: Error: Mod Version information must be incremented prior to updating.'
```

### Steps to reproduce

1. Build+Reload your mod with a higher version than before
2. Try to publish
3. Error window will pop up 'Mod Version information must be incremented prior to updating'

### Expected Behavior

Normal publish as it worked with a prior version of the 1.4.4.9 tModloader preview beta

### Actual Behavior

Getting this error no matter what I do.

To completely document my journey:
On some trials I got the message it is unable to access steam workshop.
Once it sad a mod with same name already exists.
On some trials (after changing to a different beta or stable version) it said it need to download new dependencies. Pressing Install result in error message not able to reaching Steam workshop.
(steam workshop might be offline during this. I also could not access the mod browser)

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
I ran into a similar issue, and managed to fix it somewhat I think. It's a partial fix, you might need to open the workshop folder for your mod and delete the 2023.3 folder first. (C:\Program Files (x86)\Steam\steamapps\workshop\content\1281930\somenumber\2023.2\) 

Give it a try and let me know.

Please note that if you actually posted the client.log file, I probably would have seen the cause for this when you posted this, rather than waiting to experience this myself. Please just post the log files next time you make an issue.

**Comment by Unftf** [comment]
Thank you very much! It is working again!.

Some note: I deleted 2023.2, opened Terraria build+reload and the error did happend again. 
Did checked the folder again. 2023.2 was present again. I deleted it again + folder 2023.**3** as well. 
(with Terraria still open) I build+reload again. The error did not appeared again. I successfully uploaded a new mod version. 
Thanks again!

(besides the tModloader version and times the client.log of the working and non working look very similar. Did not upload bc haven't seen anything else crucial in there and they contain some private data I had to change first (maybe some tModloader feature to remove this by default?))

**Comment by Coronel-Wee-Booties** [comment]
I have stumbled upon this same issue, and there's no 2023.2 nor 2023.3 folder? Any help would be appreciated

**Comment by DaDuckLord** [comment]
I have just returned to modding and I made some changes and wanted to publish them, but it came up with this issue. I do not  have a "1281930" folder inside my content but I do have two other numbers, I checked through everything they have and no 2023.3 anywhere. What should I do?

**Comment by DaDuckLord** [comment]
nevermind I just build and reloaded it sorry
