### ISSUE TITLE
Projectiles that do not have a sprite will often look wrong

### ISSUE THREAD

**Issue by Mach12** [bluemagic123/tModLoader#33]
If a projectile is only supposed to have particles for a visual, it will look really odd.
Sometimes it seems well handled, like for the water bolt that has a little spinning blue thing that does not cause too much visual pollution.
Sometimes it goes funny, for example the wand of sparking shoots rotating sticks.
Aaand sometimes it goes really wrong, i.e with the Purify spell from Thorium, that literally just shoots a 4-block-sized blue-purple blinking square.

I guess this is due to the recent changes in how projectiles are handled, but it really get ugly sometimes.

**Comment by bluemagic123** [comment]
Hm, I'm unable to replicate this problem. Is there anything specific that was going on when this all happened? And what mods are you using?

**Comment by Mach12** [comment]
No special context. Here's my mod list and other specs:

- Windows 10
- Terraria 1.3.1.1
- tModLoader 0.8.1.2
- Mods:
    - Annoying dog
    - Cheat sheet
    - Cheeze's content pack
    - Cosmetic Variety
    - Creative Mode
    - Dye Easy
    - Ersion
    - Galaxite
    - Greatswords
    - Helpful Hotkeys
    - imkSushi's mod
    - imkSushi's drop addon
    - Infinity
    - Ivysaur's level system
    - Joost
    - Lunar Rings
    - MaxStackPlus
    - Miners Extra
    - More Accessories
    - More Mirrors
    - Nice
    - Potions Plus
    - Quality of Life Standard
    - Randomod
    - RPG
    - Shorter Respawn Time
    - SummonersOP
    - Luggage
    - Thorium
    - Tremor
    - Yoyo Expansion
    - Zoaklen

**Comment by bluemagic123** [comment]
Hmm, that's a lot to go through. Do you still get the problem when every mod is disabled?

**Comment by Gredys** [comment]
Had yesterday same problem. Disabling all mods (tested with/without cheat sheet mod) seems fixing the problem with "Wand of Sparking".
P.S. About "block-sized blue-purple blinking square" - same happens to me, but with green cubes (hitting modded door with ball/projectile/arrow weapon made green-block-sized dust to appear on hit). Will post few screenshots with more information a bit later.

**Comment by Mach12** [comment]
After experimentation, it seems the problem comes from... ZoaklenMod.
I honestly am clueless regarding why that is, but disabling Zoaklen removes literally all projectile-related glitches.
