### ISSUE TITLE
Cultist

### ISSUE THREAD

**Issue by Mechint0** [bluemagic123/tModLoader#3301]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

The Cultists are not spawning when i add mods like the stars above, thorium, mod of redemption, vitality mod. basically mods that add quite alot of content  i tried only using i beat golem but still nothing even if i restart the game

### Expected Behavior

cultist spawn after beating the golem

### Actual Behavior

there are no cultists spawning at the dungeon

**Comment by ExterminatorX99** [comment]
If it's an issue that only happens with mods enabled, then it's the fault of one of the mods, not tML.

**Comment by JavidPack** [comment]
This issue tracker is for tModLoader, not individual mods. If you can confirm this issue happens without any mods enabled, please post a new log file and re-open this ticket. 

You can follow this process https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart to identify the mod responsible, and then check the mod's steam workshop page for bug report guidance.
