### ISSUE TITLE
[1.4.4] New 1.4.4 head vanity items don't draw player hair

### ISSUE THREAD

**Issue by qwerty3-14** [bluemagic123/tModLoader#3303]
### Version

Latest 1.4-preview

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

New vanity items from 1.4.4 remove the player's hair when equiped.

### Expected Behavior

In Vanilla 1.4.4, Vulkelf Ear and Goblorc Ear don't remove the player's hair when equiped. Raynebro's Hood, Jim's Cap, and Dizzy's Rare Gecko Chester use hat hair.

### Actual Behavior

Tmodloader 1.4.4 these items remove the player's hair when equiped

### Reproduction frequency

Equip the items in head vanity slot.

**Comment by Rijam** [comment]
Can confirm. This also happens with the Garland and Eyebrella. The vanity items mentioned were added 1.4.3 or later as the Royal Tiara, which was added in 1.4.1, works correctly. https://terraria.wiki.gg/wiki/Armor_IDs
Captures from in game 1.4.4 tModLoader vs images from the wiki:
Garland
![Capture 2023-03-12 16_21_39](https://user-images.githubusercontent.com/11262234/224577586-d9703410-1dcc-4d71-bfc4-8809d7b6c654.png) ![](https://terraria.wiki.gg/images/9/9f/Garland_%28equipped%29.png)
Vulkelf Ears
![Capture 2023-03-12 16_15_04](https://user-images.githubusercontent.com/11262234/224577580-8ed4de62-d2df-4a75-9eaf-04c65fea8cc2.png) ![](https://terraria.wiki.gg/images/f/f1/Vulkelf_Ears_%28equipped%29.png)
Eyebrella
![Capture 2023-03-12 16_21_58](https://user-images.githubusercontent.com/11262234/224577587-37dd1a84-79ec-44fa-837b-f37ff2d7c03a.png) ![](https://terraria.wiki.gg/images/9/93/Eyebrella_%28equipped%29.png)
Goblorc Ears
![Capture 2023-03-12 16_15_11](https://user-images.githubusercontent.com/11262234/224577581-61d67a17-f7e7-4c8f-ad9b-6f55c5329353.png) ![](https://terraria.wiki.gg/images/1/17/Goblorc_Ears_%28equipped%29.png)
Jim's Cap
![Capture 2023-03-12 16_15_17](https://user-images.githubusercontent.com/11262234/224577582-8a2850a5-2f0e-4d4d-96ce-f81c90e18195.png) ![](https://terraria.wiki.gg/images/c/c0/Jim%27s_Cap_%28equipped%29.png)
Dizzy's Rare Gecko Chester
![Capture 2023-03-12 16_15_24](https://user-images.githubusercontent.com/11262234/224577584-90185441-71cd-4c71-a2d3-428cdd8f48de.png) ![](https://terraria.wiki.gg/images/4/44/Dizzy%27s_Rare_Gecko_Chester_%28equipped%29.png)
Raynerbro's Hood
![Capture 2023-03-12 16_15_21](https://user-images.githubusercontent.com/11262234/224577583-447f5a12-a15b-4535-b51a-938ae043017c.png) ![](https://terraria.wiki.gg/images/a/ab/Raynebro%27s_set.png)
