### ISSUE TITLE
Add a buffName parameter to ModifyBuffTip hooks

### ISSUE THREAD

**Issue by stormytuna** [bluemagic123/tModLoader#3307]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Adding a `buffName` parameter to `ModifyBuffTip` hooks would allow modders to easily change a buff's display name dynamically. I propose adding a `ref string buffName` parameter, similar to how buff tooltips are changed using the same hook.

### What does this proposal attempt to solve or improve?

It's currently difficult to dynamically change a buff's display name, requiring advanced methods like IL or reflection (unless I'm missing something obvious)

One example could be for animating a buff's display name, if a Modder wanted something like Minecraft's glitched/scrambled text (see the *k* part of [this gif](https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/7e/Minecraft_Formatting.gif/revision/latest?cb=20200828001454))

### Which (other) solutions should be considered?

It would be possible to separate out modifying the tooltip and modifying the display name into two different hooks, possibly `ModifyBuffTip` and `ModifyBuffName`

**Comment by JavidPack** [comment]
This seems reasonable. I think the easiest solution is rename `ModifyBuffTip` to `ModifyBuffText` and add the `buffName` parameter.

Whoever implements this should also make sure to add the tModPorter rule and test cases.
