### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array while running Docker container.

### ISSUE THREAD

**Issue by shinysocks** [bluemagic123/tModLoader#3319]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to run the docker container with mods, it repeatedly spits an `System.IndexOutOfRangeException: Index was outside the bounds of the array.` error.

### Log File

Finding Mods...
docker-tml-1  | Sandboxing: Calamity Mod v2.0.2.2
docker-tml-1  | Sandboxing: Calamity Mod Music v2.0.2.2
docker-tml-1  | Constructing Mods...
docker-tml-1  | Adding Content: tModLoader v2022.9.47.39
docker-tml-1  | Adding Content: Calamity Mod v2.0.2.2
docker-tml-1  | Adding Content: Calamity Mod Music v2.0.2.2
docker-tml-1  | Resizing...
docker-tml-1  | Configuring Content: tModLoader v2022.9.47.39
docker-tml-1  | Index was outside the bounds of the array. (see server.log for full trace)
docker-tml-1  | An error occurred while loading 
docker-tml-1  | The mod responsible is unknown and tModLoader must be restarted.
docker-tml-1  | 
docker-tml-1  | System.IndexOutOfRangeException: Index was outside the bounds of the array.
docker-tml-1  |    at Terraria.ModLoader.Default.Patreon.xAqult_Lens.SetStaticDefaults() in tModLoader\Terraria\ModLoader\Default\Patreon\xAqult.cs:line 86
docker-tml-1  |    at Terraria.ModLoader.ModItem.SetupContent() in tModLoader\Terraria\ModLoader\ModItem.cs:line 90
docker-tml-1  |    at Terraria.ModLoader.Mod.<>c.<SetupContent>b__100_0(ModType e) in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 26
docker-tml-1  |    at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 49
docker-tml-1  | --- End of stack trace from previous location ---
docker-tml-1  |    at Terraria.ModLoader.Core.LoaderUtils.ForEachAndAggregateExceptions[T](IEnumerable`1 enumerable, Action`1 action) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 57
docker-tml-1  |    at Terraria.ModLoader.Mod.SetupContent() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 26
docker-tml-1  |    at Terraria.ModLoader.ModContent.<>c.<Load>b__42_1(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 328
docker-tml-1  |    at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 383
docker-tml-1  |    at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 327
docker-tml-1  |    at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 125

### Steps to reproduce

1. follow steps outlined [here](https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#using-the-docker-container) to setup and run docker container.
2. error continues to loop repeatedly

### Expected Behavior

Docker container should start...

### Actual Behavior

Error continues looping

### Reproduction frequency

Every time.

### Additional Information

- Using CalamityMod and CalamityModMusic and checking within Terraria directory reveals that the mods are loading in?
- Ubuntu Server 20.04 but it shouldn't matter cause it's docker
- Followed [this](https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#using-the-docker-container)

**Comment by DavidF-Dev** [comment]
Note. Also occurs when attempting to start a server. Also occurs with no mods enabled.

**Comment by alanescarcha** [comment]
Do NOT upgrade to this version if you use a server, it will not start.

**Comment by shinysocks** [comment]
Which version should I use?

**Comment by Pannoniae** [comment]
In patches/tModLoader/Terraria/ModLoader/Default/Patreon/xAqult.cs , line 76, (xAqult_Lens class) if you remove the netMode check, it seems to work.

**Comment by Pannoniae** [comment]
It's probably related to the netMode check in xAqult_Lens. Commenting it out fixes the error but it introduces desync between server and client so it is not a full solution.

**Comment by Solxanich** [comment]
Sorry, just getting to this.  
Uhhh.... yes, thanks for narrowing down, the issue is Line 89 on 1.4.4 / Line 86 on stable.

![image](https://user-images.githubusercontent.com/59670736/226149093-5cfcd243-a154-489b-b01c-9a3da87ea9ec.png)

Equiploader has no contents on the server, so GetEquipSlot will fail. 

I'll check and push in a moment

**Comment by Solxanich** [comment]
Github actions has completed - should be able to pull a new server update and problem should be resolved.
Please confirm

**Comment by shinysocks** [comment]
First test yielded a new error...Progress!! I think the cause of that one may just be me being silly. I'll do more testing and create another issue if I can't figure it out. THANK YOU SO MUCH FOR YOUR HELP!!!!

**Comment by Pannoniae** [comment]
@Solxanich why did you revert the fix?

**Comment by Solxanich** [comment]
I reverted both the fix and the issue causing it, given the root issue had a fair few other problems.
