### ISSUE TITLE
[Feature Proposal] Better ShaderData.Apply error handling

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3320]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Currently, if modders forget to add certain parameters to their shader files, and that shader is about to be applied ingame, they will get greeted by the infamous error (in this example, a dye shader):
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Shaders.ArmorShaderData.Apply(Entity entity, Nullable`1 drawData) in tModLoader\Terraria\Graphics\Shaders\ArmorShaderData.cs:line 22
   at Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(Player player, Int32 cHead, DrawData& cdd) in tModLoader\Terraria\DataStructures\PlayerDrawHelper.cs:line 27
```

In the case of missing or malformed parameters, TML should make sure to report the missing one alongside the original error.
Note: This issue most often appears when porting 1.3 shaders which are notoriously missing a few parameters (listed in the migration guide)

### What does this proposal attempt to solve or improve?

Modders no longer being clueless about an error.

### Which (other) solutions should be considered?

Instead of erroring, default the missing parameters and output a silent exception instead

**Comment by JavidPack** [comment]
I wonder how this can be done cleanly. As far as I know that parameter name isn't accessible from the exception. 

A modder should be able to just look up the line number of the exception, but that isn't ideal.

**Comment by Chicken-Bones** [comment]
We can probably just add some defensive coding (no-op) to the `Apply` calls when certain effect parameters don't exist.

**Comment by JavidPack** [comment]
I was thinking we could write an il edit to throw an exception instead of returning null: https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/Effect/EffectParameterCollection.cs#L48

I don't think we can do anything in the Apply calls since the `EffectParameter` itself is null.

Another option is just a big patch with 
```
base.Shader.Parameters["uColor"].SetValue(_uColor);
...
```
changed to 
```
base.Shader.Parameters["uColor"]?.SetValue(_uColor);
```

I think it is good to make sure the shader has all the expected parameters, so an exception logging the value passed into the indexer would be great in my opinion, rather than ignore them.

**Comment by Chicken-Bones** [comment]
No need for an IL edit, we run our own fork of FNA for reasons like this.

**Comment by JavidPack** [comment]
Right, I always forget that.

**Comment by JavidPack** [comment]
Implemented in https://github.com/tModLoader/tModLoader/commit/30b2b9b1e3347a1c98ebe6924811ba5e82391dc3
