### ISSUE TITLE
[Feature Proposal] Language documentation

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3322]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Many localization related methods and properties are not documented. With 1.4.4 now forcing localization usage, having documentation for the various methods inside `Language`, `Lang`, `LocalizedText`, and other classes is vital.

### What does this proposal attempt to solve or improve?

Teach modders proper localization handling.

**Comment by JavidPack** [comment]
I think I've covered most of the ones modders should be using, is anything still missing that would be helpful?

**Comment by direwolf420** [comment]
`LocalizedText.ToNetworkText`, `Lang.Get[Item/NPC/Projectile]Name(Value)`, `Language.GetTextValue` (all it's overloads), `Language.ActiveCulture` are ones I am using but have no documentation
