### ISSUE TITLE
[Feature Proposal] NPC gravity property/hook

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3324]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

There is currently no way to adjust or get the true (momentary) gravity value of an NPC. This is most useful for changing how fast an NPC falls without having to manually mess with `Entity.velocity`, and to get the values for i.e. predictive logic.
The current parameters (`NPC.gravity` and `NPC.UpdateNPC_UpdateGravity(out float maxFallSpeed)` are all private.
A start would be to make the method/field public (to be able to retreive the values), and the field non-static (it only seems to be used within instanced methods in `NPC`), and then add a hook/property to change `maxFallSpeed`.

### What does this proposal attempt to solve or improve?

Access to gravity related properties of an NPC

**Comment by Kogsey** [comment]
I'll do it, but Q: leave gravity as vertical only or make it a 2D vector? Becuase tbh looking at it now the only thing that might be a little bit of work is slope collision if it starts spitting the dummy.

**Comment by JavidPack** [comment]
I assume vertical only. I don't think we'll be able to test a 2D gravity well enough to verify that it wouldn't have any issues.

**Comment by Kogsey** [comment]
I think the PR has functionality listed plus some other stuff, anyone have anything extra they want in there?
