### ISSUE TITLE
Enemy defense is more effective than it should be 

### ISSUE THREAD

**Issue by JotaBame** [bluemagic123/tModLoader#3325]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Try a Minishark with Musket Balls against the Angry bones variant with 14 defense. 

The enemy should be reducing all damage by 7, so my 13 damage minishark should be dealing about half its usual damage, but instead the enemy is reducing all damage down to 1.

**Comment by Chicken-Bones** [comment]
Please provide a log file

**Comment by direwolf420** [comment]
1.4-preview or 1.4.4-preview? In discord a user also reported this problem on 1.4.4-preview.
