### ISSUE TITLE
Multiplayer drop table glitch

### ISSUE THREAD

**Issue by Betamalee** [bluemagic123/tModLoader#3332]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The items I pick up from mob drops and others differ from what other players see. Even though we are pre-Moon Lord the drops I get are post-Moon Lord and are mostly difficult items to get or craft, not something I should be getting from drops.  When I give these items to other players they see completely different ones. 

![image](https://user-images.githubusercontent.com/128318719/226198996-d2064407-0dfc-4e78-b437-ac83881cb8c2.png)
![Screenshot_2023-03-19_192330](https://user-images.githubusercontent.com/128318719/226198999-7c5e035c-6e71-482c-ba74-9f653b3c3365.png)
![Screenshot 2023-03-19 192149](https://user-images.githubusercontent.com/128318719/226199009-92a886e9-0288-471e-84f8-3716916afc41.png)

The attached images show an example of this glitch. Other than the weapon, I got a mount that should be inaccessible to me, but though other players can see my mount, they can't see the items when they pick it up. We do to know how to proceed further and would like some feedback.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11011982/client.log)

### Expected Behavior

I get the same drops as other players

### Actual Behavior

I get drops from different drop tables than other players

### Reproduction frequency

I do not know how to reproduce the issue but the bug is persistent across saving and exiting.

### Additional Information

It started at a floating cloud pool while fishing. The mobs my summons killed started to drop these items.

**Comment by direwolf420** [comment]
Solution here: #3331

**Comment by JavidPack** [comment]
Should be fixed, make sure to updated server and client to at least v2022.09.47.42
