### ISSUE TITLE
Tmodloader not launching no matter what

### ISSUE THREAD

**Issue by Osjoud** [bluemagic123/tModLoader#3342]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I try to open tmod from steam
It show console with log below then disappear
Then steam show play button 
I downloaded all Microsoft stuff
I reinstalled, verify, deleted dotnet file 
Mamy timesssss

### Log File

Launch log:
Windows Version 6.1
Verifying .NET....
Logging to D:/SteamLibrary/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
mv: can't rename 'D:/SteamLibrary/steamapps/common/tModLoader/Libraries/Steamworks.NET': Permission denied
'D:/SteamLibrary/steamapps/common/tModLoader/Libraries/Steamworks.NET' -> 'D:/SteamLibrary/steamapps/common/tModLoader/Libraries/steamworks.net/Steamworks.NET'
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "D:/SteamLibrary/steamapps/common/tModLoader/dotnet/6.0.0"
Loaded Custom Arguments: 
Launched Using Local Dotnet

Native log:
Failed to load the dll from [D:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\host\fxr\6.0.0\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from D:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\host\fxr\6.0.0\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

**Comment by Chicken-Bones** [comment]
@JavidPack @Solxanich should we, at the very least, implement a check for `hostfxr.dll` and try a re-install of dotnet?

**Comment by JavidPack** [comment]
In #3058 we had a check for the number of files. It's certainly a good idea, we could probably finish that.

**Comment by Chicken-Bones** [comment]
It's worth finishing, but @direwolf420 has mentioned to me in passing that `hostfxr.dll` missing is very common, so we could probably cut a lot of install issues with a simple check

**Comment by Solxanich** [comment]
Huh. Yeah, no concerns for me with checking that one file. 
I'm guessing that is one of the last to unzip, so might be an easy one to check.

Anything to trim down the number of reports is always pleasing.

**Comment by Osjoud** [comment]
Ummm guys sorry to interrupt
But what should i do

**Comment by JavidPack** [comment]
Sorry. Follow the FAQ section linked here https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#hostpolicydll-error

You'll also want to check your antivirus and safe files settings, those are also in the FAQ page

**Comment by Osjoud** [comment]
> Sorry. Follow the FAQ section linked here https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#hostpolicydll-error
> 
> You'll also want to check your antivirus and safe files settings, those are also in the FAQ page

Ireally did everything in this link nothing works
Im so sad

**Comment by Osjoud** [comment]
I mean look at native log
Installing .NET prerequisites might help resolve this problem. htt/ps://go.microsoft.com/fwlink/?linkid=798306
Idid install everything in it nothing works

**Comment by Osjoud** [comment]
SOLVEDDDDD ITTTT
ON WINDOWS 7 64BIT YOU NEED TO DOWNLOAD 
KB3063858 UPDATE HERE IS THE LINK for the 64bit
https://www.microsoft.com/download/details.aspx?id=47442
32 bit: https://www.microsoft.com/download/details.aspx?id=47409

**Comment by Osjoud** [comment]
> I mean look at native log Installing .NET prerequisites might help resolve this problem. htt/ps://go.microsoft.com/fwlink/?linkid=798306 Idid install everything in it nothing works

Addmins and devs should add this to to installation guide
