### ISSUE TITLE
Sliders in mod configuration are not interactable

### ISSUE THREAD

**Issue by Kulihrasek456** [bluemagic123/tModLoader#3354]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Cannot interact with sliders in ModConfig menu.
It isn't affected by which mods i load (i tried it with only one mod loaded and was still unable to interact with them).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11075230/client.log)

### Steps to reproduce

1. Start world
2. open settings
3. open Mod Configuration
4. open configuration for any mod that has sliders in settings
5. try to move slider

### Expected Behavior

i should be able to drag slider to desired position thus setting the value

### Actual Behavior

sliders update with values but i'm unable to controll them. 
For instance: in better lighning mod, i can change any value and the preset slider changes to "custom" but i am unable to move it manually

### Reproduction frequency

always

### Additional Information

it should be reproducable with any mod that has settings that use sliders.

**Comment by JavidPack** [comment]
Can you test the sliders in examplemod configs? I'm pretty sure if sliders weren't working we would have heard of this by now. My guess is you are trying to change a read-only slider, but I don't know the mod you are talking about. Is the slider white or slightly gray? A screenshot would help.

There isn't anything in your log that suggests an error

**Comment by Kulihrasek456** [comment]
I wasn't able to reply yesterday sorry.
I tried to reproduce the issue and send you the screenshots you asked for, but i am unable to reproduce the issue. I didn't change anything and was able to reproduce it 2 days ago, but it fixed itself somehow.
So, thank you for your reply, i am going to close this issue now.

**Comment by JavidPack** [comment]
Ok, thanks for getting back, glad it is working again for you.

**Comment by PolterTzi** [comment]
I just happened to have run into a similar issue in what I think is the latest build.
It seems to happen whenever Frame Skip is specifically set to On.

**Comment by justAnyNiko** [comment]
> I just happened to have run into a similar issue in what I think is the latest build.

yep, it happens beacuse of frame skip
