### ISSUE TITLE
Bring old PreHurt hooks back

### ISSUE THREAD

**Issue by gugudao** [bluemagic123/tModLoader#3357]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Bring old PreHurt hook back;Yes the new strike hook is more standardized but not free and convenient at all: If modders have to use IL or On editing in order to realize their simple ideas, it is much worse than the so-called cross-mod compatibility; The new hook even can't make the NPC take 0 damage directly but goes around in a big circle!If that's just what modders want ,why make things so much trouble?How dare you assume that modders need to have hit-effects while dealing 0 damage? And the solution is to have NPCs take at least 1 damage?The callback of ModifyHurtInfo seems to be a reluctant compromise. If it is used, it will destroy the so-called compatibility, so why did you add it?Just for making trouble？

### What does this proposal attempt to solve or improve?

Old hook only had cross-mod compatibility issues
New hook not only had cross-mod compatibility issues (if you register callbacks), but also harder to use

**Comment by Chicken-Bones** [comment]
The current design of the hooks has been discussed at length in Discord. You are welcome to review the discussion there for more understanding on the choices and why they were made. 

You mention `PreHurt` in the title, but that was a player hook. There are new hooks for allowing a player to dodge a hit entirely.
For NPCs, `CanHit` hooks are the easy way to avoid taking damage entirely. 

Please note that the limits around not being able to deal 0 damage once an item/projectile hits, is mostly related to vanilla code limitations, where much of the code assumes that damage dealt is at least 1. I _did_ try and support dealing 0 damage, but it was too hard to decide which effects should run and which ones shouldn't, and weave the result through the vanilla code.

In order for me to evaluate your request, I need examples (including code) of the features you previously had implemented, and are struggling to implement in the new system. If they are likely to be wanted by multiple modders, I will see what can be done.

**Comment by Chicken-Bones** [comment]
See #3359
