### ISSUE TITLE
Buff Immunities (NPCID.Sets.DebuffImmunitySets) too difficult to use

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3358]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Ever since 1.4, `NPCID.Sets.DebuffImmunitySets` contains default buff immunity data for every NPC. During `NPC.SetDefaults`, the `NPC.buffImmune` array is filled out in accordance with the data contained within. If no entry is found, the NPC is set to be immune to no buffs. Importantly, this runs after `NPCLoader.SetDefaults(this);`, meaning that there is no sensible place to set immunities in the way taught in 1.3 code.

Currently, mods can use `ModNPC.SetStaticDefaults` to register a `NPCDebuffImmunityData` to `NPCID.Sets.DebuffImmunitySets`. This covers the use case of setting specific immunities for a specific npc, but there are still situations that are difficult.

- Buff that acts like or "inherits" the behavior of another buff:
  - For example, Meteor Head is immune to `OnFire` and `OnFire3` ("Hellfire"), which is stronger version of a fire based debuff. 
  - A modded fire based debuff might want to inherit the immunity, but the code to do so is very verbose due to the dictionary and int[] elements.
  - In 1.3, modders would simply add `NPC.buffImmune[ModContent.BuffType<MySuperOnFire>()] = NPC.buffImmune[BuffID.OnFire];` in `GlobalNPC.SetDefaults`, but the current design doesn't allow that.
 
- Adding buff immunities to specific vanilla NPC:
  - Adding specific immunities is also hard, for the same reasons.

## Workaround
Some mods do the work to edit `NPCID.Sets.DebuffImmunitySets` directly, but it is very verbose code. Some mods bypass the system altogether and run their own 1.3 style code in PreAI and edit `NPC.buffImmune` directly. I think it is useful for default npc immunities to be data, so it would be nice to facilitate the use cases with some helper methods.

## Dynamic immunities
Immunity changes resulting from AI code are all still possible and work the same.

Discord discussion link: https://discord.com/channels/103110554649894912/445276626352209920/1090218856028581898

Thorium approach
[LAEZPTXu.txt](https://github.com/tModLoader/tModLoader/files/11092836/LAEZPTXu.txt)

**Comment by Chicken-Bones** [comment]
From a quick glance at the code, it seems reasonable to move `NPCID.Sets.DebuffImmunitySets` code in `NPC.SetDefaults` to run before `NPCLoader.SetDefaults`

**Comment by JavidPack** [comment]
That is true, but I was thinking there might be value in using the `NPCID.Sets.DebuffImmunitySets` as the sole source of defaults. Going back to editing `NPC.buffImmune` directly in `Global/ModNPC.SetDefaults` would work, but then there are 2 ways to do things.

I was imagining the data centric approach would allow for a mod that added debuff immunities to the bestiary, for example. 

I guess in the end, the ContentSamples would end up with the correct `buffImmune` values and those can be used for referencing the default immunity data.

Does using `NPCID.Sets.DebuffImmunitySets` get us anything, or should we just interpret it as a data structure of vanilla data to import? ModNPC will still use it, to properly use  `ImmuneToAllBuffsThatAreNotWhips` and `ImmuneToWhips`, so we might end up teaching 2 approaches for different things.

**Comment by Chicken-Bones** [comment]
I'm normally all in favour of static data, but as noted, it's difficult to edit, and not expandable by mods. I think the _right_ thing to do, would be to internalize `DebuffImmunitySets` and split the relevant data into 3 `NPCID.Sets` entries.
- `bool?[] ImmuneToWhipDebuffs`
- `bool[] ImmuneToAllDebuffsByDefault`
- `List<int>[] ImmuneToDebuffs[]` (or something with some built-in null safety)

The vanilla code is the way it is partly due to performance, but we can get most of the benefits with something like:
```cs
// in SetDefaults
if (ImmuneToAllDebuffsByDefault[type])
    Array.Fill(buffImmune, true);

foreach (var buffType in ImmuneToDebuffs[type])
    buffImmune[buffType] = true;

if (ImmuneToWhipDebuffs[type] is bool whipBuffImmunityOverride)
    for (int i = 0; i < buffImmune.Length; i++)
        if (BuffID.Sets.IsAnNPCWhipDebuff[i])
            buffImmune[i] = whipBuffImmunityOverride;
```

That way mods could copy the `ImmuneToWhipDebuffs` pattern in their own `SetDefaults` methods, but otherwise just modify `ImmuneToDebuffs` in `SetStaticDefaults`
