### ISSUE TITLE
Wave bank.wmb Considered as a third-party software and removes and gets completely erased

### ISSUE THREAD

**Issue by Eugene496** [bluemagic123/tModLoader#3367]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

So it gives a error that some files ("Wave Bank.wmb" file is included) and says it needs to be removed with the button "Enter" then after that it just does a "Main crash" with the specified words "Couldn't find *Wave bank.wmb*", what to do?
(I have a solution but it requires timing and im a some what impatient teenager)
So I just delete the wave bank file and put it on after I launch Tmodloader.bat so that the game launcher thought I didn't have the wave bank file but I do after the game actually launches

### Steps to reproduce

1. I put Terraria 1.4.4.9
2. I shove in Tmodloader v2022.9.47.14 into Terraria
3. I start Tmodloader through the bat file
4. and bam I have the problem saying I should remove the third-party software within the click of a "Enter" button

**Comment by JavidPack** [comment]
> 2\. I shove in Tmodloader v2022.9.47.14 into Terraria

You are installing tModLoader incorrectly, you do not install tmodloader into the terraria folder. I'd suggest doing a clean install of terraria to ensure that you didn't leave any tmod files in the terraria folder, then follow the install instructions. https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players
