### ISSUE TITLE
Error CS0117

### ISSUE THREAD

**Issue by HumanNotAlien** [bluemagic123/tModLoader#3369]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I'm trying to make a basic boomerang, but it isn't working.
my code for the weapon and projectile is below.

### Log File

Weapon:
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace Mod.Items
{
	public class WoodDisc : ModItem
	{
		public override void SetStaticDefaults()
		{
			// DisplayName.SetDefault("Wood Disc"); // By default, capitalization in classnames will add spaces to the display name. You can customize the display name here by uncommenting this line.
			Tooltip.SetDefault("A weapon.");
		}

		public override void SetDefaults()
		{
			Item.damage = 5;
			Item.DamageType = DamageClass.Melee;
			Item.width = 30;
			Item.height = 30;
			Item.useTime = 25;
			Item.useAnimation = 22;
			Item.useStyle = 1;
			Item.knockBack = 2;
			Item.value = 25;
			Item.rare = 1;
			Item.shootSpeed = 12f;
			Item.shoot = Mod.Projectile(WoodDiscProjectile);
			Item.UseSound = SoundID.Item1;
			Item.crit = 2;
			Item.autoReuse = true;
		}

		public override void AddRecipes()
		{
			Recipe recipe = CreateRecipe();
			recipe.AddIngredient(ItemID.Wood, 8);
			recipe.AddTile(TileID.WorkBenches);
			recipe.Register();
		}
	}
}

Projectile:

namespace Mod.Projectiles
{
    public class WoodDiscProjectile : ModProjectile
    {
        public override void SetStaticDefaults()
        {
            DisplayName.SetDefault("Boomerang");
            Projectile.width = 30;
            Projectile.height = 30;
            Projectile.aiStyle = 3;
            Projectile.friendly = true;
            Projectile.ranged = true;
            Projectile.magic = false;
            Projectile.extraUpdates = 1;
            aiType = ProjectilesID.ThornChakram;

        }
    } 
}

### Steps to reproduce

follow the code, I know very little.

### Expected Behavior

A simple Boomerang

### Actual Behavior

6 errors.

### Reproduction frequency

never made a boomerang before

### Additional Information

I know very little about modding.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide programming support for individual user issues here. If you need help with C#, come to the #mod-programming-help channel in our [Discord chat](https://tmodloader.net/discord).
