### ISSUE TITLE
A weapon and projectile similar to arkhalis

### ISSUE THREAD

**Issue by wyavern** [bluemagic123/tModLoader#3376]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A weapon similar to arkhalis that is a projectile only melee sword and a projectile that acts like the arkhalis' projectile. It could use a sprite similar to the arkhalis' projectile.

### What does this proposal attempt to solve or improve?

I've had a really hard time trying to make one (especially the projectile) as I couldn't find any tutorials on it, or they were outdated and I've seen some people who also had a hard time making this. People could use this to make the modding experience easier while making a weapon like that.

**Comment by wyavern** [comment]
My bad, I didn't mean to set "Do you intend to personally contribute/program this feature?" to yes 💀

**Comment by noctisatrae** [comment]
To achieve your goal, here's what you have to do (at least I believe): 

- [ ] Create the sprite for your sword (those shown are gorgeous)
- [ ] Create a custom projectile using [dust](https://github.com/tModLoader/tModLoader/wiki/Basic-Dust) (kinda hard I think) and the [Projectile Class](https://github.com/tModLoader/tModLoader/wiki/Projectile-Class-Documentation)
- [ ] When you have a prototype, debug using the [Modder's toolkit](https://forums.terraria.org/index.php?threads/modders-toolkit-a-mod-for-modders-doing-modding.55738/) (I don't know how to leverage its power yet). It will allow you (one of its many features) to control the variables in `setDefaults` so you can tweak until you manage to do what you want.

I think the most difficult part of this project is creating the projectile physics (you could look at a flail for inspiration), and create its animation & dust. Hope I helped!

EDIT: typos

**Comment by JavidPack** [comment]
This is certainly something that can be added, but I believe following the adaption guide you should have no trouble making an arkhalis clone, in the meantime: https://github.com/tModLoader/tModLoader/wiki/Advanced-Vanilla-Code-Adaption

**Comment by Setnour6** [comment]
I'm having concerning thoughts about this itself, considering that the projectile is greatly identical to the Calamity Mod's Murasama, with the only difference being the colour of the projectile.
See wiki entry here: https://calamitymod.wiki.gg/wiki/Murasama

**Comment by Chicken-Bones** [comment]
Posting recoloured sprites of another mod is not allowed (nor is using them in your own mod). I agree that an arkhalis example would be useful, but I'm closing this post because of the clear intent to duplicate _Calamity_ rather than vanilla

**Comment by noctisatrae** [comment]
When I answered I didn’t even know about it :D haven’t finished my first playthrough of Terraria, currently searching for Plantera!

**Comment by wyavern** [comment]
yeah it was a calamity sprite
the reason I used it was because I was trying to do something that a "UHF Murasama" would be today (I saw a UHFMurasama.png file when I decompiled calamity)
Yes I could've attached a different file
well I don't think doing that now will change anything
