### ISSUE TITLE
Example mod pylons not localized

### ISSUE THREAD

**Issue by ScalarVector1** [bluemagic123/tModLoader#3379]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The example pylons in ExampleMod do not have proper localization

![image](https://user-images.githubusercontent.com/5168952/229664563-52dc590a-031c-4fe6-b03b-0684855005b7.png)

### Log File

N/A

### Steps to reproduce

Enable ExampleMod
Place the example pylon
Open the map and hover over it
Observe default display name

### Expected Behavior

A localized name such as "Example Pylon" to be displayed

### Actual Behavior

The default unlocalized name is displayed

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
Fixed in [956ccbf](https://github.com/tModLoader/tModLoader/commit/956ccbfce0e3d3a0bd97ab176151a99e78b38013)
