### ISSUE TITLE
Obtaining previous states of sound and dusts before modifying hurt.

### ISSUE THREAD

**Issue by pl752** [bluemagic123/tModLoader#3380]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

I would like to have either old hurtinfo provided in `ModifyHurt`, or some getters for previous states of the sound and dusts in the `HurtModifiers` struct, or maybe an another way of getting such information before modification.

### What does this proposal attempt to solve or improve?

In the old version there was a way to conditionally replace hurt sound in the extension of `ModPlayer` class by hiding original sound, while getting previous state of "if the hurt sound had been disabled before"

```
public override bool PreHurt(...ref bool playSound...) {
      if (!_replaceCondition) {
        return true;
      }

      if (!playSound) return true;
      playSound = false;
      _useCustomHurtSound = true;
      return true;
    }

    public override void PostHurt(...) {
      if (!_useCustomHurtSound) return;
      _useCustomHurtSound = false;
      PlaySound(custom_sound, 0.75f);
    }
```

In the new version there seems to be no way to legally get "if the hurt sound had been disabled before" state before modifying modifier

```
public override void ModifyHurt(ref Player.HurtModifiers modifiers) {
      if (!_replaceCondition) return;
      //if(!IsSoundDisabled) _useCustomHurtSound = true; //No way of obtaining condition
      modifiers.DisableDust();
      modifiers.DisableSound();
    }

    public override void PostHurt(Player.HurtInfo info) {
      if (!_useCustomHurtSound) return; //No way to check then
      _useCustomHurtSound = false;
      PlaySound(custom_sound, 0.75f);
    }
```

So I need to omit checking for previous state or use reflection in order to try to obtain desired values.

### Which (other) solutions should be considered?

If there is some better practice of achieving the same effect in the new version I will be happy to know.

**Comment by Chicken-Bones** [comment]
The reason modifiers don't let you read the values of fields, is because we don't want to encourage order-dependent effects. Sound is never disabled by vanilla, so the only reason it would be disabled is if another mod decided the hit was meant to be silent. In the case where that mods `ModifyHurt` hook runs after yours, their request to silence the sound would be ignored by your mod.

I think your use-case could possibly be supported by adding a `SoundStyle? SoundOverride` property, similar to `HitDirectionOverride`

**Comment by Chicken-Bones** [comment]
On further reading, I'm not sure how to make this work in multiplayer without custom packets. `ModifyHurt` only runs on the local client, and `SoundStyle`s cannot be synchronized over the network.

What would you do if 2 mods both wanted to change the hurt sound? Ideally one of them would override the other, but how would we mediate this?

**Comment by pl752** [comment]
Thanks for an answer, that totally makes sense, I will then omit checks, as I will try to resolve mod intercompatibility through some alternative ways.

**Comment by Chicken-Bones** [comment]
Thankyou for your understanding. If changing the hurt sound is a popular request, we could consider a separate hook for it. The vanilla code for altering hurt sounds relies solely on flags like `Player.stoned` which can be set in `OnHurt`. We could implement something similar via a new hook like `ModPlayer.GetHurtSound()`
