### ISSUE TITLE
Config Localization

### ISSUE THREAD

**Issue by 312784123** [bluemagic123/tModLoader#3383]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

if original modder doesn't write config things in en-us, then other mod can't localize that mod configs.

ex) A mod's config things don't exist in A mod's localization en-US, B mod's localization for A mod(en-US.Mods.A_Mod's_Name.hjson in B mod's localization folder) isn't applied with config things(Item can be applied well).

If documentation exists related to this issue, let me know please.

Thanks

### What does this proposal attempt to solve or improve?

Add config localizing documentation or

Writing config things in external mod en-us can be applied even though config  things don't exist in original en-us

**Comment by JavidPack** [comment]
An issue for this exists: https://github.com/tModLoader/tModLoader/issues/3259
A WIP implementation is here: https://github.com/tModLoader/tModLoader/pull/3302

So, it's on the way.
