### ISSUE TITLE
Field to control if an item shooting turns the player

### ISSUE THREAD

**Issue by Destructor-Ben** [bluemagic123/tModLoader#3384]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Adding a field to items something along the lines of `shootingTurnsPlayer` which is used in `Player.ItemCheck_Shoot`.

### What does this proposal attempt to solve or improve?

Currently you have to use IL editing to prevent the player from facing a projectile when it is shot, and the vanilla behaviour that prevents this is hardcoded to the Grand Design and Beam Sword.
Vanilla Code:
```cs
bool flag = true;
int type = sItem.type;
if (type == 723 || type == 3611)
    flag = false;

Vector2 value = Vector2.UnitX.RotatedBy(fullRotation);
Vector2 vector = Main.MouseWorld - pointPoisition;
Vector2 v = itemRotation.ToRotationVector2() * direction;
if (sItem.type == 3852 && !ItemAnimationJustStarted)
    vector = (v.ToRotation() + fullRotation).ToRotationVector2();

if (vector != Vector2.Zero)
    vector.Normalize();

float num = Vector2.Dot(value, vector);
if (flag) {
    if (num > 0f)
        ChangeDir(1);
    else
        ChangeDir(-1);
}
```

```cs
if (type == 723 || type == 3611)
    flag = false;
```
Should be changed to
```cs
if (sItem.shootingTurnsPlayer)
    flag = false;
```

**Comment by Chicken-Bones** [comment]
Normally I advocate for `ItemID.Sets` entries, but I think this makes sense as an `Item` field.

**Comment by Destructor-Ben** [comment]
Close?
