### ISSUE TITLE
Drawing hook for Dusts 

### ISSUE THREAD

**Issue by ElizaYamamoto** [bluemagic123/tModLoader#3388]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A drawing hook for ModDust would be exceptionally helpful for creating stuff like DustID.Electric, which has a trail behind it to give it a more energized feel. Currently, dusts like this one cant be recolored because they have hardcoded drawcode, so i think it might just be easier to allow us to make dusts to replicate it. 

Example of how DustID.Electric cant have its color changed
https://user-images.githubusercontent.com/56371051/230525163-d113b552-119a-47ec-a65f-84ae2c040f4a.mp4

### What does this proposal attempt to solve or improve?

It will allow us to make some dusts that look nice and on par with more modern vanilla dusts

### Which (other) solutions should be considered?

While it is possible to apply shaders to dusts, sometimes you just cant find one you're looking for or the dust you are using doesn't behave how you want it to.

**Comment by Chicken-Bones** [comment]
I haven't looked at the code, but on the surface this seems reasonable to add to `ModDust`
