### ISSUE TITLE
Localization tooltip code expose issue

### ISSUE THREAD

**Issue by 312784123** [bluemagic123/tModLoader#3396]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

![툴팁](https://user-images.githubusercontent.com/118354239/230865451-220f8849-00a2-4055-a579-ae3c0315953a.PNG)

![코드](https://user-images.githubusercontent.com/118354239/230865456-abbcef88-6814-426c-b9e2-ef75f80bb8c1.PNG)

if no tooltip item is localized, tooltip exposes that way

of course, 

![툴팁2](https://user-images.githubusercontent.com/118354239/230866227-625bf181-f830-441e-b5b8-41696198b516.PNG)

![툴팁3](https://user-images.githubusercontent.com/118354239/230866242-6ea0d2cb-6652-4329-9ea4-9cf19b3ba460.PNG)

adding tooltip blank space proves problem, but I think tooltip exposing should be fixed.

thanks

### What does this proposal attempt to solve or improve?

Even if localization tooltip doesn't exist, internal tooltip code doesn't expose

**Comment by JavidPack** [comment]
This was an issue specifically with the tmodloader provided items. Modded items should work as normal
