### ISSUE TITLE
Server wont work with normal port forwarding

### ISSUE THREAD

**Issue by vityou** [bluemagic123/tModLoader#34]
When I port forward, I can host a normal terraria server on my PC, but when i try to host a tmodloader server, everyone who tries to connect just gets stuck at the connecting to screen.  The only way I've found that works is using hamachi, i'm not sure why it works, and my friends can't get hamachi.

**Comment by bluemagic123** [comment]
Hm, are people able to join if you host through Steam?

**Comment by vityou** [comment]
Yes it does seem to work when I host through steam, but like normal terraria stem hosting, its pretty laggy.

**Comment by vityou** [comment]
Is the starting and ending port to forward still 7777?

**Comment by JavidPack** [comment]
Checking with http://www.canyouseeme.org/, I can see that this is working as of now.
