### ISSUE TITLE
Improved "World Load Failed" Menu

### ISSUE THREAD

**Issue by absoluteAquarian** [bluemagic123/tModLoader#3401]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

A new, custom menu for displaying proper information about what caused world loading to fail.

### What does this proposal attempt to solve or improve?

The current implementation simply shows `Load Failed! No backup found.`, which is not only inaccurate to the actual problem, but it doesn't give any information about what actually caused the loading to fail.

Most users aren't aware of the `tModLoader/tModLoader-Logs/client.log` file existing, so they only have this misleading information to rely on.

This proposal (and its subsequent PR) aims to completely overhaul this menu by displaying an actual error stacktrace indicating where an exception was thrown.

### Which (other) solutions should be considered?

n/a

**Comment by ScalarVector1** [comment]
Some thoughts:

We 100% need something to make this distinct from a mod load failure stack trace. Big box with "WORLD LOAD FAILED" or something at the top so mod developers can tell what they're being sent from screenshots

What do we want the users options from this screen to be? 'Back' is a given, but do we want to have a 'Retry' option? It seems intuitive to have but likely would not be useful most of the time. Additionally, do we want to consider a 'Delete world' option? It may be the best course of action a lot of the time but also may lead to users prematurely consigning their world to the void

Should we consider map loading failures the same as other, more critical failures? IIRC this is one of the most common causes of this screen and in actuality most users would likely rather proceed with their map reset than lose access to their world entirely.

**Comment by JavidPack** [comment]
The discussion for this PR happened in https://discord.com/channels/103110554649894912/1095112982427619381

I don't think there has been any code written for this, right?
