### ISSUE TITLE
Error Loading Mods

### ISSUE THREAD

**Issue by Lokju223** [bluemagic123/tModLoader#3413]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

A friend of mine tried to download mods but it kept saying that there was an error and that the version were playing isn't the version its supposed to be downloaded. Even though I have the exact same mods and it works fine for me.

### Steps to reproduce

loaded Tmod64bit, error occurs, mods disable

### Expected Behavior

mods should be enabled and run properly.

### Actual Behavior

Mods won't load with an error

**Comment by cozykoko** [comment]
this is not the tmod64bit github. go to their discord
