### ISSUE TITLE
Melee speed bonus from accessories and armors do not apply to vanilla swords that have stylish swing(Terra blade, Excalibur, and so on)

### ISSUE THREAD

**Issue by Polaritz** [bluemagic123/tModLoader#3419]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Melee speed bonus from accessories, accessory prefix, and armors do not apply to vanilla swords that have stylish swing.
Weapon prefix does apply to the melee speed, working properly.
List : Night edge, True night edge, Excalibur, True excalibur, Terra blade, The horseman's blade

### Steps to reproduce

1.  Prepare accessories and armors that increases melee speed
2.  Test those swords on the list with the gear
3.  Test those swords on the lsit without gear
4.  Compare the result

### Expected Behavior

With gear, melee swing should be faster

### Actual Behavior

Melee speed bonus from the gear does not apply to those swords, result in no difference in speed

### Reproduction frequency

always

**Comment by Chicken-Bones** [comment]
Thanks for the report!
