### ISSUE TITLE
Expression Body methods not supported fully by tModPorter

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3421]
In https://github.com/tModLoader/tModLoader/commit/835057fd67841a5c3a73dc63fc9d7f65afb26b18 I've added a few tModPorter tests that fail. 

The original issue reported on Discord was that `public override SetStaticDefaults() => DisplayName.SetDefault("Test");` in a ModPrefix class would not port correctly, but it seems to apply to all situations.

I'm not sure if the final result should be 
`public override SetStaticDefaults() => return; // DisplayName.SetDefault("Test");` 
or 
`// public override SetStaticDefaults() => DisplayName.SetDefault("Test");`

**Comment by Chicken-Bones** [comment]
Went with the second option, since it's easiest to implement, sensible, and compiles
