### ISSUE TITLE
Enabling IME causes UI issue

### ISSUE THREAD

**Issue by 312784123** [bluemagic123/tModLoader#3425]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

1.

![ime1](https://user-images.githubusercontent.com/118354239/233272491-67da1bdf-5850-4696-b524-4e9cad363f5b.gif)

Journey menu search isn't possible.

2.

![ime2](https://user-images.githubusercontent.com/118354239/233272842-5f4c28a4-d9e9-488d-b3c5-1c95ea32688c.gif)

I don't know this is modding issue. Enabling IME for searching makes  UI disappear, Searching is possible but players can't see letter. Also, Mouse disappears and Key input isn't possible(except letter). so Player can't control. 
I think IME release doesn't work properly

Chatting is fine.

### Steps to reproduce

1. Enabling IME(In UI cases)
2. Then issue will happen

### Expected Behavior

not to disappear UI elements

### Actual Behavior

disappearing UI

### Reproduction frequency

Always

### Additional Information

Chatting is fine. 
I think IME releasing doesn't work properly when UI opening states

**Comment by Chicken-Bones** [comment]
Hi, Please always provide a `client.log` file when reporting issues. In addition, the Korean IME double typing issue has been fixed, so you shouldn't need the on-screen keyboard

**Comment by 312784123** [comment]
> Hi, Please always provide a `client.log` file when reporting issues. In addition, the Korean IME double typing issue has been fixed, so you shouldn't need the on-screen keyboard

Yes. To show not displaying letter and UI, I use that screenkeyboard.

**Comment by Chicken-Bones** [comment]
Please keep an eye out for Terraria 1.4.5, it should have better IME support (yellow composition string showing in more UIs)

**Comment by 312784123** [comment]
> Hi, Please always provide a `client.log` file when reporting issues. In addition, the Korean IME double typing issue has been fixed, so you shouldn't need the on-screen keyboard

[client.log](https://github.com/tModLoader/tModLoader/files/11281329/client.log)

Logfile


Sorry I'll keep that in mind, Additional IME supprot  in 1.4.5 Thanks. But in tmodloader, Searching is broken. player can't play even in English IME

**Comment by Chicken-Bones** [comment]
Please test again, should be fixed (v2023.04.55.0 or newer)

**Comment by 312784123** [comment]
> Please test again, should be fixed (v2023.04.55.0 or newer)

It's fixed. thx for patching. Thanks a lot!!!
