### ISSUE TITLE
Add HasWall property in Tile

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#3432]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A new property called `HasWall` in `Tile`.
It would be shorthand for `WallType == 0`.

### What does this proposal attempt to solve or improve?

Currently, if you want to check for air or "none" wall, you have to type this: `WallType == 0`.
However, for tiles you can simply do: `!HasTile`. Thus a modder could suppose that there's `HasWall` property, but _there isn't_.
Adding `HasWall` could solve that weird inconsistency.
Perhaps `IsAir` property could be added too.

**Comment by Chicken-Bones** [comment]
The inconsistency exists because `HasTile` is actually a special bit, independent from `Tile` type. Adding `HasWall` would obscure this significant difference.

**Comment by BasicallyIAmFox** [comment]
> The inconsistency exists because `HasTile` is actually a special bit, independent from `Tile` type. Adding `HasWall` would obscure this significant difference.

i ukow that astile is diFFEret ad special ad etch buk astile 77 walltype == 0 Feels weird

**Comment by BasicallyIAmFox** [comment]
also sorry FOr late reply
