### ISSUE TITLE
The game is not working on any other resolution other than 1024

### ISSUE THREAD

**Issue by PapiJusis** [bluemagic123/tModLoader#3436]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game works perfectly fine in the 1024 resolution but once I change the resolution to other resolution or to fullscreen, the screen freezes but I can still hear the sounds.

https://user-images.githubusercontent.com/131834957/234446442-2344a147-c8b3-4be0-ab61-b7ed2eaf114d.mp4

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11328256/client.log)

**Comment by JavidPack** [comment]
I hope you figured this out, I'm not seeing anything strange in your log. If it's not working, try 1.4.4-preview, if you aren't playing tmod anymore, we can go ahead and close this, since it seems to be an issue only affecting you.
