### ISSUE TITLE
Example Minecart?

### ISSUE THREAD

**Issue by tomiscool850** [bluemagic123/tModLoader#3438]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Just like a Mount, except it only activates on tracks and dosent have the buff

**Comment by direwolf420** [comment]
I would be willing to contribute this (in a few weeks). Just need to look into the new Minecart Upgrade Kit item, and find someone to make the sprites

**Comment by Chicken-Bones** [comment]
Desaturating a vanilla sprite and increasing contrast is a perfectly acceptable method of making example sprites :)

**Comment by JavidPack** [comment]
I noticed that vanilla minecarts have a left and right buff, I imagine it is necessary for some multiplayer syncing. Make sure to look into that, try to figure out why it is necessary.

**Comment by tomiscool850** [comment]
epic, also ik i said with no buff, i didnt know minecarts have buffs
