### ISSUE TITLE
example spinner weapon and advanced Spinner Weapon

### ISSUE THREAD

**Issue by tomiscool850** [bluemagic123/tModLoader#3439]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

so basically The Sleepy Octopod item except (non-advanced) has no projectile, so it just spins and another one (Advanced) where it shoots/does a slam after a little

**Comment by JavidPack** [comment]
Sleepy Octopod is just another held projectile, it should be easy to adapt or clone using the https://github.com/tModLoader/tModLoader/wiki/Advanced-Vanilla-Code-Adaption

ExampleMod does have a number of held projectiles (search player.heldProj), https://github.com/tModLoader/tModLoader/blob/1.4.4/ExampleMod/Content/Projectiles/ExampleCustomSwingProjectile.cs is one that is completely custom with custom animations.
