### ISSUE TITLE
An item similar to Rod of Discord

### ISSUE THREAD

**Issue by wyavern** [bluemagic123/tModLoader#3443]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

This would help people that want to make an item with teleporting abilities.

### What does this proposal attempt to solve or improve?

I didn't see any people struggling with this, but I myself have no clue how to make this, and maybe, sine new modders would want to make something similar to Rod of Discord.

**Comment by JavidPack** [comment]
I think something this niche probably doesn't need to be in ExampleMod. 

I took a look, and it seems like any modder following the https://github.com/tModLoader/tModLoader/wiki/Advanced-Vanilla-Code-Adaption guide should be able to make a similar item.
