### ISSUE TITLE
Launching TML on Steam Deck launches regular Terraria in a separate process

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [bluemagic123/tModLoader#3448]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I launch TML on Steam Deck (don't know if this occurs on Windows, haven't tried it there), the regular Terraria is launched alongside it, in a separate window.

### Log File

This isn't a crash or an error, so I don't think that would help too much.

### Steps to reproduce

1. Launch tModLoader through Steam

### Expected Behavior

It shouldn't be launching regular Terraria at all. I don't recall the legacy 1.3 version ever doing this.

### Actual Behavior

The regular, unmodded Terraria is launched alongside TML as a separate window, and the former can be safely closed.

### Reproduction frequency

Whenever I launch TML.

**Comment by Chicken-Bones** [comment]
Please provide logs and a video. Please don't tell us that logs wouldn't help. We can't investigate without them

**Comment by UsernamesAreNotMyThing** [comment]
I tried to upload a video directly to GitHub but it wouldn't let me: https://drive.google.com/file/d/10vxSQHzoFv5x7_X15dJ0bnsXxOEWB6sM/view?usp=share_link

[client.log](https://github.com/tModLoader/tModLoader/files/11379215/client.log)

**Comment by Chicken-Bones** [comment]
This looks like intended behavior. Terraria is not actually running at the same time. Steam just reports you as playing both tML and Terraria.

**Comment by UsernamesAreNotMyThing** [comment]
Okay, but couldn't the fact that Steam thinks I'm playing both simultaneously be considered a bug, because that doesn't seem like ideal behavior? I believe that is ultimately what the issue in question is.

**Comment by cozykoko** [comment]
No relogic wants it that way afaik
