### ISSUE TITLE
Vanilla Whips deal far less damage than they are supposed to

### ISSUE THREAD

**Issue by MarfMaster** [bluemagic123/tModLoader#3449]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The amount of damage lost seems to coincidentally be the same as they are supposed to lose AFTER having hit an enemy with the whip once, so that is most likely the issue. Further whip damage reductions after the first hit seem to work as intended.
Firecracker's explosion on-hit also seems to deal far less damage than intended, but I haven't noticed any other problems with vanilla whips apart from what is mentioned above.
Thankfully, modded whips do not have this issue. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11379296/client.log)

### Steps to reproduce

Hit any enemy with a vanilla whip (ideally disable damage variation so the damage difference becomes obvious)

### Expected Behavior

Whips should be dealing as much damage as the items state

### Actual Behavior

They are dealing far less damage than the items state

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
Thanks for the report, can confirm the issue.
