### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by alirezahemiten** [bluemagic123/tModLoader#3452]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When i install tmodloader it change my game version from 1.4.4.9 to 1.4.3.6 , when i run terraria.exe its 1.4.4.9 but when i run game through tmodloader it change to 1.4.3.6 , also try to reinstall and delete all config file in my documents folder but it didn't work

### Additional Information

this is when i run Terraria.exe
![terrarianoloader](https://user-images.githubusercontent.com/120275063/236235089-3bb8b678-a17d-47fc-9640-fdd3584cc264.png)
and this is when i run through tmodloader
![terrariaTmodloader](https://user-images.githubusercontent.com/120275063/236235415-e451d12c-a8b3-4fbf-9664-5f43234f47dc.png)

**Comment by JavidPack** [comment]
tModLoader is currently based on Terraria v1.4.3.6. This is expected.

If you would like to join the highly work-in-progress beta for tModLoader updated to v.1.4.4 Terraria, you can do that by joining the 1.4.4-preview branch: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#switch-to-stable-tmodloader-or-to-preview-tmodloader

**Comment by JavidPack** [comment]
Oh, I see you are on GOG, installing the 1.4.4 preview is a bit more involved. 

Visit https://github.com/tModLoader/tModLoader/actions/workflows/build.yml?query=branch%3A1.4.4+, find the latest entry at the top, click it, scroll down all the way to the artifacts section, click on "Release Build" to download. Then, manually install the contents of the zip into the install folder.
