### ISSUE TITLE
Update serverconfig.txt

### ISSUE THREAD

**Issue by DemonGamingLP** [bluemagic123/tModLoader#3462]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I noticed the serverconfig.txt is unchanged since 1.3 while the whole file structure was changed; no TerrariaServer.exe anymore ("#use the command 'TerrariaServer.exe -config serverconfig.txt' to use this configuration or run start-server.bat") as well as new config options not being listed there (not sure how many, however at least all journey mode configs). people not knowing how the server actually works (me included) will probably have issues properly using that config file.

### What does this proposal attempt to solve or improve?

Updating makes it easier to configure dedicated modded servers without getting frustrated or trial and error because of outdated info

**Comment by JavidPack** [comment]
Thanks for bringing this to our attention, I'll make sure this gets done, it does seem important.

**Comment by DemonGamingLP** [comment]
Thanks.

also if you dont mind me asking: why did you change the file structure THAT much for 1.4? it feels kinda weird to start the game/server without a exe, also it feels weird that you need to use BOTH .bat files if you start the server bat first (steam sees "tmodloader" as running when starting the server).

**Comment by JavidPack** [comment]
In moving to .net core, we ended up with a bat that runs a dll file rather than an exe. This also helps our goal of a single file for all platforms.

I'm not sure what you mean by your other question, you only need to run the client bat to run the client, or the server bat to run the server. If you are asking about how Terraria and tModLoader are both "running" in steam, that's just for playtime tracking, nothing is actually running.

**Comment by DemonGamingLP** [comment]
Thanks for the quick explanation.

with the other thing i meant: running the server bat first makes it impossible to run the client from steam as steam will see tmodloader is running due to the server being there. while this is basically not a big issue it just feels weird.

would love to eventually see a "true" dedicated server pack, just a downloadable containing only the files needed for a server that is able to run "on its own" without being somewhat forced to be with the client files and not tied to steam (if thats even possible? not sure in what way tmodloader is tied to the vanilla files) for windows. i dont know if its just me but i prefer to save my server files fully dedicated from a game in a different folder. mainly for organization purposes

thanks for your time, you may respond to this or leave it as is. dont want to "waste" time here ^^ have a great day!

**Comment by JavidPack** [comment]
Sounds like you typed "y" when it asked you if you wanted to use steam server. If you do that, it'll do that. Same with Terraria if you run the start-server-steam-friends.bat file. If you type "n", it won't be seen as running the game.

As for a dedicated server, we do have scripts and instructions in https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server.

The bat files in the root of the install directory are typically used for hosting a server locally by typical users who have the game installed on their machine, the dedicated server page goes into details about hosting a server on another machine with or without steam that will automatically do the install and such.

**Comment by DemonGamingLP** [comment]
i indeed did type "y", didnt know it acts like that, just thought its simply better when my friends all come from steam. thanks for pointing that out!

either i do not really understand what your link wants to tell me and i am doing smth wrong or this is not exactly what i was looking for; following the instructions via github install with the manage script creates a normal and full installation (client + server) of tmodloader. i meant just server files without anything of the stuff required to run the client and only the stuff required to run the server.

but it should be fine like it is. its probably just a me "issue". thanks a lot for your time ^^

**Comment by JavidPack** [comment]
Yeah, it's all the same. We could have the dedicated server trim out the texture files, but there is no reason to do that, they are small.
