### ISSUE TITLE
tModloader crash while being offline - no error log, tModloader uploading data/needs internet connection to work?

### ISSUE THREAD

**Issue by Unftf** [bluemagic123/tModLoader#3469]
### Version

Latest 1.4.4-preview

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

To find some fancy worlds I sometimes generate worlds over night. While doing this I disable my network connection.
Sometimes the game ends during this without leaving any error message in log or console.
It's not a single or random issue. I start tMoaderloader multiple times in a console (to see info). After the night not just a single game is gone but all of them.
Sometimes all survive. So it's either 0 or all. 
I did this many times before the 1.4 update and it worked fine. Did not much for 1.4.1/2/3 - due to non-vanilla WorldGen but never happend there.

Does tModloader/Terraria need a internet connection all the time?
System monitor (KSysGuard) showing me tModloader is uploading ~13 Kibyte/sec all the time. However it is not shown in other network tools I tried. 
tModloader/Terraria sending some data all the time?

### Log File

picture of KSysGuard
![image](https://github.com/tModLoader/tModLoader/assets/39495683/6436ec6b-1a34-40c6-aede-7ced6fee0f29)

### Steps to reproduce

1.Start tModloader (maybe only in console instead of steam library)
2.Turn off your internet connection
3.Wait

### Expected Behavior

tModloader should run, independent of a internet connection

### Actual Behavior

sometimes all tMoadloader close

### Reproduction frequency

Did no statistics about it but it already happend 3 times out of ~10.
Once it happend just minutes after leaving the PC, sometimes after hours.

### Additional Information

No other mods but mine are used. Those do not intend to connect to any server. tModloader/Terraria might connect to some cloud save during storing the world (it is disabled). 
It also shows uploading without any mods running. Terraria itself does this too.

**Comment by JavidPack** [comment]
can you post a server.log from a time when it did crash? 

As for the network traffic, I don't think that is worth worrying about, it could a number of things or an error in that program.

**Comment by Unftf** [comment]
../steamapps/common/tModLoader/tModLoader-Logs/server.log?
It contains no new entry. Last update of this file is over a week ago. 
This upload is also at the main menu doing nothing. It spikes to a higher number while selecting character and world menu (200KiB/sec).
Yes, it could also be some bug from KSysGuard.
But it would not explain why all instances of the game end. Maybe it's Steam related.
Will try to trigger it some more times with an open game doing nothing.

**Comment by JavidPack** [comment]
Have you played tMod recently? Is this still an issue? If you aren't playing, we can close this issue. I'm not sure what else to try given that the logs aren't being very useful.
