### ISSUE TITLE
JIT exception on mod despite errors fixed

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3471]
This happened while I was trying to voluntarily port Subworld Library to 1.4.4

### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When building the [Subworld Library forked repo under my name with 1.4.4 changes](https://github.com/Setnour6/SubworldLibrary/tree/1.4.4_porting_manually), I receive a JIT mod-reload compilation error, despite me fixing said errors in the mod source code; the code would be underlined in red and would signify an error.

To test the code, download the forked repository and add it to Mod Sources, and then open `<modname>.sln` or `<modname>.csproj`, `<modname>` referring to the name of the mod or repository, and build and reload the sln or csproj internally (CTRL + B). Then you can launch tModLoader and check to see if it appears during mod loading.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11445897/client.log)

Search inside the sln or csproj file for the methods/method names shown on the log file (example: `In SubworldLibrary.SubworldSystem.LoadSubworld, Field not found: 'Terraria.WorldGen.waterLine'.`, you would search for "waterLine" by pressing CTRL + SHIFT + F and searching the entire solution)

### Steps to reproduce

1. Install or implement the forked repository, following the instructions written in the description
2. Build and reload the mod if it is not enabled
3. An error should appear.

### Expected Behavior

The forked repo of Subworld Library under my name should work and load

### Actual Behavior

The forked repo of Subworld Library under my name fails to work and load

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
Looking at your fork, you have a SubworldLibrary.dll file in the root directory. If there is a dll file named the same as the mod like that, it will override the dll built by the compiler and tmod will end up loading that outdated dll. Delete that dll and rebuild everything.

**Comment by Setnour6** [comment]
> Looking at your fork, you have a SubworldLibrary.dll file in the root directory. If there is a dll file named the same as the mod like that, it will override the dll built by the compiler and tmod will end up loading that outdated dll. Delete that dll and rebuild everything.

How the heck did I miss that?

I removed the DLL file that was there and tested the mod loading again, and the mod still fails because there can only be one mod extending, but I do recall that SubLib worked that way. After removing the ModCallExample folder, I received an error about an unexpected null in `System.Void`. Here's the log for that:
[client.log](https://github.com/tModLoader/tModLoader/files/11446476/client.log)

I'll probably extend this issue to include the unexpected null issue, and/or (also) make an issue in either the forked repo or the original repo.

**Comment by JavidPack** [comment]
Glancing and the errors in your log, I believe it is just caused by outdated IL edit code that you'll need to fix. Make sure to disable all other mods and restart the game to get a fresh log if you still don't think the issue is in your mod code.

**Comment by Setnour6** [comment]
> Glancing and the errors in your log, I believe it is just caused by outdated IL edit code that you'll need to fix. Make sure to disable all other mods and restart the game to get a fresh log if you still don't think the issue is in your mod code.

I don't know how to update IL code, specifically SubLib IL code. I'll have to ask John (creator of SubLib) or someone else with subworld knowledge to update the code for porting to 1.4.4. You can also volunteer if you want to. You made Subworlds before in your Alternate Dimensions mod, or something like that.

**Comment by Setnour6** [comment]
> > Glancing and the errors in your log, I believe it is just caused by outdated IL edit code that you'll need to fix. Make sure to disable all other mods and restart the game to get a fresh log if you still don't think the issue is in your mod code.
> 
> I don't know how to update IL code, specifically SubLib IL code. I'll have to ask John (creator of SubLib) or someone else with subworld knowledge to update the code for porting to 1.4.4. You can also volunteer if you want to. You made Subworlds before in your Alternate Dimensions mod, or something like that.

John said he's almost done with the update. I didn't know that he was already working on porting SubLib to 1.4.4.
