### ISSUE TITLE
Custom summoning items don't support resummoning

### ISSUE THREAD

**Issue by Varriount** [bluemagic123/tModLoader#3478]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Custom minion-summoning items (I've tested using Thorium- and Calamity-specific items) don't support "resummoning" a minion when a player's minion slots are full. With normal vanilla items, attempting to summon a minion when all minion slots are full replaces an existing minion (the oldest one?) with a new one.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11472548/client.log)

### Steps to reproduce

1. Install a mod with minion summoning items (such as Calamity).
2. Start a world with the mod enabled.
3. Obtain a vanilla minion summoning item (such as a slime staff) and a mod-specific minion summoning item (such as Calamity's Squirrel Squire Staff).
4. Use the vanilla minion summoning item multiple times.
5. Use the mod-specific minion summoning item multiple times.

### Expected Behavior

When using a minion summoning item multiple times, one should be able to resummon a minion (to reposition them, replace them, etc.).

### Actual Behavior

The minion summoning item does nothing.

### Reproduction frequency

100%

### Additional Information

Notes:
  - Vanilla minion-summoning items will replace minions from custom minion-summoning items.
  - Sometimes a minion *can* be resummoned if the player uses the summoning item within ~2 seconds of the initial summon.
  - This only affects *minions*, not sentries.

**Comment by direwolf420** [comment]
This is a bug with the mods you are testing it with, not a TML bug. Report it to the respective mod's authors

**Comment by Varriount** [comment]
@direwolf420 I'll contact the developers, but do you have any idea what the bug might be? Is it just a lack of implemented functionality, or some flag that needs to be set?

**Comment by direwolf420** [comment]
Just to clear this up for any modders that might see this; the primary minion of the summoning item (the one assigned via `Item.shoot`) needs to have `Main.projPet` and `ProjectileID.Sets.MinionSacrificable`
