### ISSUE TITLE
error when opening tmodloader

### ISSUE THREAD

**Issue by justinlamiel12** [bluemagic123/tModLoader#3481]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

Gives me this error when manually launching tmodloader i already have steam opened
![Screenshot (236)](https://github.com/tModLoader/tModLoader/assets/133955885/317dfbc2-25b6-4e9a-86aa-39892bdbdd75)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11505928/client.log)

### Additional Information

i tried restarting and its still not fixed

**Comment by JavidPack** [comment]
Looks like you messed up the install instructions, the game thinks you are running the steam version. Delete the folder and install again. Come to discord if you need help, we don't provide support on Github.

**Comment by justinlamiel12** [comment]
ok
