### ISSUE TITLE
Main Engine Crash window when closing multiplayer server

### ISSUE THREAD

**Issue by Rhoenicx** [bluemagic123/tModLoader#3482]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When a multiplayer server is closed, a crash window appears.

![image](https://github.com/tModLoader/tModLoader/assets/55693487/9d5bee1d-4c33-44fc-82a0-b4a509044d41)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11508427/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/11508428/server.log)

### Steps to reproduce

1. Open a multiplayer server.
2. Close the server.
3. Crash window appears.

### Expected Behavior

Multiplayer server should close without a crash.

### Actual Behavior

A crash window appears when the server is closed.

### Reproduction frequency

Every time a multiplayer server is closed.

### Additional Information

Tested without mods enabled.

**Comment by JavidPack** [comment]
Fixed recently
