### ISSUE TITLE
When I enter the game, I have control of the gamepad.

### ISSUE THREAD

**Issue by TyMaxiss** [bluemagic123/tModLoader#3485]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I enter the game, I have control of the gamepad. But I don't have it, much less connected

### Expected Behavior

Launch with mouse control

### Actual Behavior

Launch with gamepad control

### Reproduction frequency

Every time

**Comment by direwolf420** [comment]
You left the Log file field empty.

Please attach the client.log file here. You'll find the log files in the logs folder. Look for the client.log file.
On the 1.4 versions it can be found in the "tModLoader-Logs" folder in your tModLoader install directory (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files")

In 1.3 it can be found in the following folders:
Windows Logs: C:\Documents\My Games\Terraria\ModLoader\Logs
Linux Logs: ~/.local/share/Terraria/ModLoader/Logs/ or $XDG_DATA_HOME/Terraria/ModLoader/Logs/
Mac Logs: ~/Library/Application support/Terraria/ModLoader/Logs/

Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by TyMaxiss** [comment]
I have already reinstalled windows and it helped. Most likely it was a problem in one of the drivers. In any case, these files are no longer there. But thanks for the answer
