### ISSUE TITLE
ModifyDisplayValue in GlobalInfoDisplay will not modify the display value of Lifeform Analyzer

### ISSUE THREAD

**Issue by DarthHA** [bluemagic123/tModLoader#3490]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

As it is written, I guess the display value of Lifeform Analyzer will be overwritten in DrawInfoAccs() in Main.cs, making it useless to modify the value in GlobalInfoDisplay

### Steps to reproduce
The code is as followed:
`public class BeeGID : GlobalInfoDisplay`
`{`
`    public override void ModifyDisplayValue(InfoDisplay currentDisplay, ref string displayValue)`
`    {`
`        displayValue += " Mechanical Bee";`
`    }`
`}`

### Expected Behavior
All infos displayed will be appended with " Mechanical Bee"

### Actual Behavior
All infos take effect except the Lifeform Analyzer

### Reproduction frequency
All the time

**Comment by JavidPack** [comment]
Works for me. My guess is you didn't test the mod alone and a different mod is also changing the info display.

![image](https://github.com/tModLoader/tModLoader/assets/4522492/1f95a2fc-cfdd-404a-b657-482986072562)

**Comment by Chicken-Bones** [comment]
As jopo said, you need to test with no mods enabled to report tML issues. You also need to post a `client.log` file at the minimum for us to investigate anything
