### ISSUE TITLE
Crashing whenever I open the game, no mods downloaded or enabled, no characters in folders, no worlds.

### ISSUE THREAD

**Issue by NorthBlade** [bluemagic123/tModLoader#3491]
*Note, my tModLoader is now working. No, I didn't do anything else to fix it. I closed Steam and reopened it the next day (that's something I tried as well), but it works now. For some reason. Idk man.

### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I try to open the game, it crashes. I get an error message labeled "Fatal Error" and "Main engine crash."

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11525662/client.log)

### Steps to reproduce

1. Click "Play" on Steam.
2. Wait about 3 seconds.
3. Get error message.

### Expected Behavior

1. Click "Play" on Steam
2. Wait varied amount of time, based on system.
3. tModLoader opens.

### Actual Behavior

1. Click "Play" on Steam. 
2. Small wait period.
3. Error message.
4. If you press "Ok" on the error message, it closes, and Steam says the game is closed.

### Reproduction frequency

Every time I open the game, this happens.

### Additional Information

![Screenshot_3](https://github.com/tModLoader/tModLoader/assets/134237131/6904db45-b64f-4dbb-93a9-8a484313976c)
I have tried multiple fixes, such as opting out of the Steam Beta, deleting and unsubscribing from all mods, deleting all worlds, deleting all characters, verifying the integrity of game files for both Terraria and tModLoader before and after all other fix attempts, and deleting and redownloading tModLoader.

**Comment by JavidPack** [comment]
This is caused by a resource pack, so maybe it updated.

https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#multiple-extensions-for-asset

The issue itself is being tracked in https://github.com/tModLoader/tModLoader/issues/2913
