### ISSUE TITLE
Clicking mod sources in tmod legacy prompts me with Enable dev mod screen (already enabled)

### ISSUE THREAD

**Issue by stupidratcreature1000** [bluemagic123/tModLoader#3495]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I was backporting my mod to 1.3.5 and when I click on mod sources it prompts me with the "Enable developer mode screen" even though i already enabled it

### Log File

no log

### Steps to reproduce

no idea

### Expected Behavior

supposed to bring me to mod sources screen

### Actual Behavior

brought me to enable developer mode screen

**Comment by JavidPack** [comment]
You can try deleting the ModCompile folder. If that doesn't work, come to discord, we don't do support here.
