### ISSUE TITLE
tModLoader Building Issue

### ISSUE THREAD

**Issue by quinnzore** [bluemagic123/tModLoader#35]
So I've been trying to build my mods that I have created but every time I try I get an error (error will be at the bottom), and this doesn't just happen with my mods it happens with other mods as well, I've tried  building the Example Mod as well but I always get the same error.
If could help, please do.

Error:
error CS1703: An assembly with the same identity 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' has already been imported. Try removing one of the duplicate references.

error CS1704: An assembly with the same simple name 'Steamworks.NET, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null has already been imported. Try removing one of the references or sign them to enable side-by-side.

P.S. I don't know anyway to open .dll files to try make them side-by-side, I've even tried removing them from the Terraria Directory but I just get more errors saying that it can't find that file.

**Comment by quinnzore** [comment]
I don't know what to say, I was kinda gone for like 2 months thinking someone might say something on this matter, i'm not accusing anyone it's just that I had my hopes up, but the reason this is so important to me is because, if I don't find a way to fix it, I won't be able to continue my project/mod as I won't be able to test it. Thanks to bluemagic for the tModLoader API and I hope I find a way to fix this soon.
(Sorry, if you feel i'm accusing you or someone else, but i'm really desperate)

**Comment by bluemagic123** [comment]
This is actually a very common user error. You'll need to go to your Terraria's steam directory, then delete Newtonsoft.Json.dll and Steamworks.NET.dll. (It's safe to delete them since they should already be embedded in the Terraria.exe itself.)

**Comment by quinnzore** [comment]
THANK YOU! Oh my goodness, I am almost crying right now, thank you bluemagic you are such a life saver.

**Comment by ParismaX** [comment]
I tried doing this but it didn't seem to work, it just gave me an error saying:
![image](https://cloud.githubusercontent.com/assets/23120795/19807486/3590e11a-9d18-11e6-9488-b2c7444ec90b.png)
