### ISSUE TITLE
ProcessHitAgainstNPC does not respect DamageClass.UseStandardCritCalcs

### ISSUE THREAD

**Issue by jjohnsnaill** [bluemagic123/tModLoader#3504]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Damage classes have a UseStandardCritCalcs property to disable random critical hits on weapons of that class. This works for projectiles, but not for hitting NPCs with the item directly.

### Steps to reproduce

Swing a weapon with a damage type that sets UseStandardCritCalcs to false at an NPC.

### Expected Behavior

The weapon never critically hits.

### Actual Behavior

UseStandardCritCalcs isn't checked, and the weapon is capable of critically hitting.

**Comment by Chicken-Bones** [comment]
Seems like an easy fix
