### ISSUE TITLE
IsTileBiomeSightable hook

### ISSUE THREAD

**Issue by Lion8cake** [bluemagic123/tModLoader#3507]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A new hook for mod tiles called IsTileBiomeSightable that would allow for the tile to be picked up by the biome sight potion and its buff.

### What does this proposal attempt to solve or improve?

This would allow for any spreadable biome or any biome intended to be clensed similar to Calamity's Astral Infection to be picked up by the biome sight potion to be clensed easier.

**Comment by Chicken-Bones** [comment]
Will a `TileID.Sets` entry work for you, or do you need a hook?

**Comment by Lion8cake** [comment]
I do not mind personally, some people way wish to have checks in place to enable biome sight at a point in progression so it might be better to have it be a hook.
