### ISSUE TITLE
Stuttery movement

### ISSUE THREAD

**Issue by FaeMagician** [bluemagic123/tModLoader#3508]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I walk, unless I jump, my movement will be stuttery. By this I mean I will move for a moment, stop, continue, stop, continue, stop, ad infinitum. Jumping before walking, or walking, jumping, then continuing will fix the issue until I stop moving or try to turn.
I tried this with mods disabled, without any equipment, with Terraspark boots on, and with the Shield of Cthulu active and dashing, none of these helped.
Something to note that I tried using both the Shield of Cthulu and the Terraspark boots together and I noticed that sometimes I'd get it to the glitch would occur, but I'd suddenly speed back to how fast I should be with the Terraspark boots active before stopping and then going again.
Also, to note with the Shield of Cthulu, dashing even after jumping reactivates the glitch.
I restarted my computer and it did not fix the issue.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11595321/client.log)

### Steps to reproduce

1. Enter a Terraria World
2. Walk in either direction without jumping

### Expected Behavior

Movement should be smooth and not jittering

### Actual Behavior

Movement is not smooth and is jittering

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Please try with 0 mods enabled, we need you to rule out that it is caused by mods. Send new client.log too when you do

**Comment by FaeMagician** [comment]
"I tried this **with mods disabled**, without any equipment, with Terraspark boots on, and with the Shield of Cthulu active and dashing, none of these helped."

**Comment by FaeMagician** [comment]
I'd like to inform you that this seems to be a problem with my computer as it's
1. Happening on vanilla Terraria
2. Happening with other video games
Sorry for the false alarm, tModLoader happened to be the second game I encountered this glitch with since my computer was repaired recently and I didn't make a connection until I tried playing a third game and encountered the same issue, then tried with a fourth, fifth, and sixth game.

**Comment by JavidPack** [comment]
Thanks for getting back. To me it seems like what would happen if the batteries on a wireless keyboard were dying, or wireless interferance, or a wired keyboard with a cord that has been damaged. Might want to test with a different keyboard, just to rule that out. Hope you figure it out.

**Comment by FaeMagician** [comment]
Thank you for the suggestion, I just figured out the issue about the time you sent this message. After unplugging the keyboard and plugging it back in in a different port it fixed itself.
