### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by dominicwild** [bluemagic123/tModLoader#3513]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I try to launch the game via the bat file or Steam, it gives me some command prompts and then disappears without doing anything. 

Here are the logs `Lanch.log`
```
Windows Version 6.1
Verifying .NET....
Logging to G:/Program Files (x86)/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
mv: can't rename 'G:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET': Permission denied
'G:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET' -> 'G:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/steamworks.net/Steamworks.NET'
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "G:/Program Files (x86)/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
Loaded Custom Arguments: 
Launched Using Local Dotnet
```

`Natives.log`
```Failed to create CoreCLR, HRESULT: 0x80004005```

I've tried reinstalling .NET 6 and the SDK, fresh Terraria and tModLoader installs. But it is the same error. The fact that it can't rename a directory seems odd in the Launch.log. I'm not sure if that relates to anything.

### Steps to reproduce

1. Run `start-tModLoader.bat`
2. Nothing happens

### Expected Behavior

tModLoader launches

### Actual Behavior

Silently fails

### Reproduction frequency

Happens every time

**Comment by JavidPack** [comment]
Please try on 1.4.4-preview if you still haven't figured this out, hopefully the issue has solved itself or is no longer relevant.

I noticed you are on Windows 7. Steam and eventually tModLoader won't work on Windows 7 soon, so you might just want to update your operating system. 

I do know some users needed to install additional things for the game to run on Windows 7: <https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#additional-deps>

If the issue persists, please come to our Discord for support, we don't do support here on Github.
