### ISSUE TITLE
Pausing time causes some projectile/summon AI to malfunction

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3516]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When pausing time through any way (e.g. Journey Mode Time Freeze, HERO's Mod Time Pause, DragonLens Time Stop, etc.) the AI for some of the projectiles or summons stop functioning properly.
This is noticable in the [Everglow](https://github.com/Solaestas/Everglow) mod's two weapons (by internal name): EvilChrysalis and TsunamiShark

Time is normal:
![image](https://github.com/tModLoader/tModLoader/assets/70764728/3d73e37e-b078-44a5-a67d-3e889e3705b2)
Proper function; the sharks summoned through the TsunamiShark weapon are spinning in a tornado-like fashion, as intended.

Time is frozen:
![image](https://github.com/tModLoader/tModLoader/assets/70764728/8497ed09-dd6b-4df1-a1e5-4b4c402a062d)
Improper function; the sharks summoned do not spin around the player anymore, and are stuck glitching in place.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11646245/client.log)

### Steps to reproduce

1. Download ZIP of [TmodSources](https://github.com/Solaestas/TmodSources). You can extract it to your downloads folder.
2. Download ZIP of [Everglow](https://github.com/Solaestas/Everglow) and add it to /TmodSources/ModSources/ directory folder.
3. Open Everglow.sln
4. Start in Visual Studio. You can use either debugging or without debugging.
5. Enter a world you created
6. Use any item giver or spawner from HERO's Mod, DragonLens, etc. to give yourself the Evil Chrysalis or Tsunami Shark weapons
7. Use either weapons. Moths or Sharks will spawn depending on the chosen weapon
8. Freeze time using either Journey Mode Time Freeze power or HERO's Mod/Cheat Sheet/DragonLens Time Pausing buttons
8-2. Make sure no enemies are nearby during reproduction.
9. The issue should become apparent, where the entities move or stay in one place and start spazzing out.

If you want to use other mods instead of Everglow, skip steps 1 - 4 and start on step 5, and choose any weapon that summons any entities. Use the weapons, freeze time, and see if the issue occurs for you.

### Expected Behavior

The projectile or summon should still function regardless of time change

### Actual Behavior

The projectile or summon does not function regardless of time change

### Reproduction frequency

100% of the time with the two weapons written in the description. I haven't tested it with other weapons from other mods.

### Additional Information

I highly doubt that a client log file was needed. This issue has been a thing for a long time.

**Comment by JavidPack** [comment]
Since this problem is with a specific mod and a vanilla feature (journey mode time pause), you'll have to report this to developer of that mod. This issue tracker is for bugs with tmodloader itself, not mods.

My guess is whoever made those projectiles is using Main.time for some effect, they should not be using "World Time" in this manner.

**Comment by Setnour6** [comment]
I'll ask the developers
