### ISSUE TITLE
[1.4.3] UIVirtualKeyboard doesn't disappear when it should

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#3517]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

UI Virtual Keyboard for MainMenu 30 doesn't disappear when it should. I have not been able to identify why, suspect this also happens with xbox controllers but haven't tested.

### Log File

Reported on behalf of Discord Thread: 
https://discord.com/channels/103110554649894912/1110016620895674409/1110041186510569502

### Steps to reproduce

1. Start Host&Play multiplayer on steam deck in console mode
2. Return to Main Menu

### Actual Behavior

![image](https://github.com/tModLoader/tModLoader/assets/59670736/dc68890b-9e52-4233-8107-6a7d95d55f74)

### Additional Information

Likely a vanilla bug fixed in 1.4.4

**Comment by Solxanich** [comment]
@Chicken-Bones to confirm if this is fixed already in vanilla in 1.4.4 or if thus is a tml bug

**Comment by JavidPack** [comment]
Can confirm that this is working correctly on Terraria 1.4.4, still an issue on tModLoader stable/dev.
