### ISSUE TITLE
Cannot build mods on M1 Macs

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#3520]
### Version

Latest 1.4.4-preview

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Several issues:
- The default `dotnet` on an M1 is ARM version and cannot run tML. As such the `dotnet tModLoader.dll` command in the `BuildMod` target for mod packaging will not load due to MonoMod not supporting ARM Macs yet. 
- Packing images requires reading pngs, which requires loading `SDL2.dylib`. The `AfterBuild` command doesn't run via `ScriptCaller.sh` or `UnixLinkerFix.sh` which means there was an `rpath` issue.
- Launch configurations/debugging. Untested. Have to fix build issues first.

Additionally, it would be worth looking at some of the linker fixes and such that we have in the launch scripts and seeing if we can move them into `tModLoader.dll` for a more robustly callable executable.

### Log File

This issue needs work from someone with an M1 Mac, sending builds back and forwards is a bit tedious, so I won't bother posting log files here.

**Comment by LittleJay1985** [comment]
These precompiled MacOS native libraries currently don't support ARM64 (only x64 or x86/x64) in TModLoader:
libFAudio.0.dylib
libFNA3D.0.dylib
libnfd.dylib
libSDL2-2.0.0.dylib
libtheorafile.dylib

They will need to be recompiled as macos universal binaries with ARM64.

I don't own a Mac but as you are a modder maybe you would be willing to rebuild the libraries and do a pull request?

Hopefully it should fix the Mac ARM64 issues we've been seeing.

**Comment by Chicken-Bones** [comment]
There is no need to build ARM versions of mac natives. M1's are capable of running x86 programs and libraries via Rosetta. This is what allows tML to run on M1 macs currently, and the build system need not be any different.

**Comment by zhuher** [comment]
@LittleJay1985 https://github.com/Candygoblen123/TerrariaArmMac might be of interest to you

**Comment by JavidPack** [comment]
We've had many mac modders and no reports of this issue anymore, underlying issues have probably been fixed.
