### ISSUE TITLE
Dungeon Coordinates don't work in Multiplayer

### ISSUE THREAD

**Issue by RomanTheGithub** [bluemagic123/tModLoader#3523]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Main.dunegonX and Main.dungeonY return as 0, 0 in Multiplayer. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11668706/client.log)

### Steps to reproduce

1. Join/host a multiplayer world.
2. Try to use dungeonX or dungeonY (ex. [ExampleMapLayer](https://github.com/tModLoader/tModLoader/blob/1.4.3-dev-archive/ExampleMod/Common/ExampleMapLayer.cs))

### Expected Behavior

The coordinates should be at the dungeon, and the same as in singleplayer.

### Actual Behavior

The coordinates are both 0, the corner of the map

### Reproduction frequency

100% of the time

### Additional Information

It works fine in singleplayer

**Comment by Chicken-Bones** [comment]
I suppose this is a feature request. You could sync them yourself with a `ModSystem`
