### ISSUE TITLE
Let us Enable "Mod Packs" as "Addons" to current already Enabled Mods. (Enable Multiple Mod Packs)

### ISSUE THREAD

**Issue by Kristijan1001** [bluemagic123/tModLoader#3527]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Lets us enable Mod Packs on top of each other without disabling the ones enabled. 

This would allow to create for example a Utility Mod Pack, that can be enabled alongside everything else.

Example. 

Utility Mod Pack that Contains Utility Mods & QoL Mods. - This one can be enabled with Content Mod Packs.

Content Mod Packs - Mods that add a lot of Content in the game, usually bundled with other mods that add on to the experience of the Content mod.

### What does this proposal attempt to solve or improve?

Faster Troubleshooting being able to enable mods in a batch. 

Be able to enable Mod Packs as addition to current enabled Mod Pack.

Create Addon Mod Packs.

Instead of updating the Main "Content Mod Pack" with utility mods constantly and resaving it. This will alow to only edit that "Utility Mod Pack" so if you want to switch a Content Mod you play you don't have to add the Utility Mods AGAIN.

### Which (other) solutions should be considered?

Simply have a checkmark system to do this in the UI, then you click a button to load all of it. Instead of loading each Mod Pack individually.

**Comment by Kristijan1001** [comment]
@Solxanich i see this was a bug that got fixed. But can we also be able to select multiple ModPacks then load them at once. Instead of click load, click load, click load ?

**Comment by Solxanich** [comment]
Unfortunately,  no, given how mod loading works relative to mod packs, the 'enable list' button does require trigger a reload. 
Not the most convenient, I'm aware, and could be  changed with a lot of effort, but also at the risk of creating other issues. 
If the need is there, happy to leave a second github issue for that and prioritize it regardless
