### ISSUE TITLE
NPCs Acting Weirdly In Water

### ISSUE THREAD

**Issue by xInspectrEx** [bluemagic123/tModLoader#3528]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I was testing my mod earlier today when I noticed that slimes were not floating on water correctly. After tons of screwing around, I found out that even without mods, they were not floating on water, and would simply glide across the ground. And just a few moments ago, I noticed a skeleton not even trying to get out of the water, in a situation where it usually would (seen in the attached video).
https://github.com/tModLoader/tModLoader/assets/51129924/f433f1ed-2eac-4075-b06c-72c9b83a7669

### Steps to reproduce

1. Get an NPC to enter water (that can collide with water)
2.  Enjoy :)

### Expected Behavior

Anything with the Slime AI would simply float atop the water, and anything with the Fighter AI would still be able to jump while submerged.

### Actual Behavior

It seems as if the NPCs are forcefully being pushed down when in the water, which the skeleton in the video above does when walking down some blocks.

### Reproduction frequency

100% of the time.

### Additional Information

This weird behavior also applies for Lava, Honey, and Shimmer. It also seems as if anything that touches water that doesn't use the Swimming or Jellyfish AIs are affected by this issue. My only guess as to why this is happening is because of the recent gravity changes added.

**Comment by ilija04** [comment]
The NPC gravity PR changes are the most likely culprit, devs know better than me, so they'll see and fix it
