### ISSUE TITLE
Unusually poor performance

### ISSUE THREAD

**Issue by AprilDerg** [bluemagic123/tModLoader#3535]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I first noticed the issue when i started playing the game after a long hiatus, ending off before 1.4 was introduced for tmod. When I opened it again for the first time, the game ran horribly. I had no mods installed, yet even in the menu it was running extremely poorly. Since then it has been getting worse as I progressed through the game, with me having gotten to a point where just tap-firing a gun in the game slows the game down to 1fps for a good second or 2. This is in absolutely unprecedented, as the game uses a small fraction of my memory, never more than a quarter of my cpu, and barely any gpu. I have tried lowering the graphical settings of the game but even that did barely anything. Considering this started before I even downloaded any mods, I am confident that the issue lies in tmodloader itself, though I am happy to do additional testing if need be.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11715315/client.log)

### Steps to reproduce

1. Launch game
2. Play game
3. Any major game event should induce lag, especially with many particles, a good example being the lunatic cultist boss

### Expected Behavior

It should run well, the way vanilla terraria does, or at least somewhat comparably

### Actual Behavior

It runs horribly while seemingly shooting itself in the foot with how many system resources it is using

### Reproduction frequency

It was subtle at the start of the game but it is now impossible to do just about anything in the game without running into lag spikes, even to the point where I can wander into unloaded parts of the world

**Comment by direwolf420** [comment]
Disable all mods, restart the game, and then try replicating it

**Comment by AprilDerg** [comment]
The game still experiences occasional stutters with no mods on. After further testing it seems that the CPU usage scales with mods overall, and as I progressively added mods back in, the CPU usage started to rise, but hit a cap around 25% or so and instead of further increasing in CPU usage it instead started to dip in framerate, worsening the stuttering.

**Comment by JavidPack** [comment]
Capping at 25% sounds like your CPU has 4 cores and tModLoader is maxing out 1 of them. Terraria is mostly a single threaded application and won't use more than 1 core, so this is expected. This might just be a case of the game being more cpu demanding on 1.4+. I'm not sure if there is anything actionable we can do from this report, but we'll continue to look into performance issues.
