### ISSUE TITLE
Tiny gap on the top of a tree appears when wind is set to little/none when zoom is set to maximum

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3538]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

There's a tiny gap of space on the top tree tile/space when the camera zoom is set to the maximum (200%) limit and there is little/no wind.

![image](https://github.com/tModLoader/tModLoader/assets/70764728/3990e128-690f-422c-a255-ccbc1044735e)

I even tested it without large content mods.

Edit: this also affects banners

![image](https://github.com/tModLoader/tModLoader/assets/70764728/3331b85e-499c-4430-87f5-aa84ccae8124)
So additionally, tiny gap on the banners appears when wind is set to little/none when zoom is set to maximum.

### Log File

I don't think that's needed in this case.

### Steps to reproduce

1. Open a world, preferably in Journey Mode
3. Zoom in all the way (or set the zoom to maximum/closest to player (200%)
4. Use Journey Mode powers, Open Weather Menu --> Open Wind Control Slider --> Click on No Wind.
5. Disable wind change via the button that says Wind Change Enabled. Have it say Wind Change Disabled
6. Look very closely at the top of the trees. You should notice a gap

### Expected Behavior

The tree does not have any small space that appears detached

### Actual Behavior

The tree does have a small space

### Reproduction frequency

100% of the time.

### Additional Information

I found it by accident. I get that it's a tiny thing nobody notices or needs to have concern over but I had an attention to detail for that part.

**Comment by JavidPack** [comment]
Thanks, can confirm. Looks like it might be hard to track down the cause.

**Comment by Chicken-Bones** [comment]
Can you test in vanilla?

**Comment by JavidPack** [comment]
I checked vanilla, it does not have this problem.

**Comment by JavidPack** [comment]
![image](https://github.com/tModLoader/tModLoader/assets/4522492/aba2fb1d-abd9-40bc-8e22-ca741a30342e)

A similar issue happens with waterfalls. This happens at any non-100% zoom.

**Comment by Setnour6** [comment]
I tested it now, even updating the tModLoader repository on my side, and the problem is still there for me:
![image](https://github.com/tModLoader/tModLoader/assets/70764728/d8a572b6-70bb-4f04-a3dd-e2b71bbdf3a0)
![image](https://github.com/tModLoader/tModLoader/assets/70764728/2fa0366e-0de7-4285-b354-dd9aea4193a4)

**Comment by Chicken-Bones** [comment]
@Setnour6 log please

**Comment by JavidPack** [comment]
Did you manually download the build from github actions? Send client.log, it'll have more info so I can verify if you have the fix or not.

**Comment by Setnour6** [comment]
> Did you manually download the build from github actions? Send client.log, it'll have more info so I can verify if you have the fix or not.

No, I use only the steam 1.4.4 preview beta all the time, and the tModLoader repository 1.4.4 branch with the latest changes there if needed (which I don't consider it being part of github actions if stated as such).

Here's the client.log for the official (steam preview) build: 
[client.log](https://github.com/tModLoader/tModLoader/files/11889402/client.log)

Here's the client.log for the development (repo 1.4.4 branch) build version:
[client.log](https://github.com/tModLoader/tModLoader/files/11889515/client.log)
