### ISSUE TITLE
On_ItemDropRule.BossBagByCondition hook doesn't work

### ISSUE THREAD

**Issue by HumanGamer** [bluemagic123/tModLoader#3539]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The hook for ``On_ItemDropRule.BossBagByCondition`` is not being called when it should be.

### Log File

This shouldn't be relevant here. If a log is needed, I can provide one upon request.

### Steps to reproduce

1. Make a mod with the following code in the Load method:
```cs
On_ItemDropRule.BossBag += (orig, itemId) =>
{
    return ((DropBasedOnExpertMode)orig(itemId)).ruleForExpertMode;
};

On_ItemDropRule.BossBagByCondition += (orig, condition, itemId) =>
{
    return ((DropBasedOnExpertMode)orig(condition, itemId)).ruleForExpertMode;
};
```
2. Put a break point on the body of each hook. You will notice that only the first one gets hit.
3. Add the following code to the bottom Load method
```cs
On_ItemDropDatabase.RegisterBoss_EOW += (orig, self) =>
{
    orig(self);
};
```
4. Now you will notice that the break point in ``On_ItemDropRule.BossBagByCondition`` is now hit.

### Expected Behavior

``On_ItemDropRule.BossBagByCondition`` should be called without hooking a method that calls it.

### Actual Behavior

The hook for ``On_ItemDropRule.BossBagByCondition`` never gets called for some reason. However, ``On_ItemDropRule.BossBag`` works fine.

If you implement the ``On_ItemDropDatabase.RegisterBoss_EOW`` hook and just make it call the original, then ``On_ItemDropRule.BossBagByCondition`` works fine.

### Reproduction frequency

This happens 100% of the time.

### Additional Information

This may be related to JIT compiling.

**Comment by Chicken-Bones** [comment]
Sorry for not responding to this sooner. This sounds like a classic case of inlining. The method you're trying to hook is short, and likely eligible.

When you add the `On_ItemDropDatabase.RegisterBoss_EOW` this forces a reJIT of just the `RegisterBoss_EOW` method, which then causes your hook to be called, but only from `RegisterBoss_EOW`, not from any other place where it has already been inlined.

Unfortunately there's not much we can do about inlined methods at the moment, it's just a limitation of hooking
