### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented. (macOS, GOG, 1.4.4)

### ISSUE THREAD

**Issue by poachedegg12** [bluemagic123/tModLoader#3542]
### Version

Latest 1.4.4-preview

### OS

Mac

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I've tried opening 1.4.3 tModLoader on my Mac with it giving an error which I found a solution to in another issue (it was apparently fixed in 1.4.4-beta.) However, when trying to run the .sh file it gives the error in the title. How can I fix this?

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11731579/client.log)

### Steps to reproduce

1. Install tModLoader 1.4.4 beta as normal
2. Run the .sh file
3. Profit

### Expected Behavior

Opening tModLoader

### Actual Behavior

Not opening tModLoader

### Reproduction frequency

Every time

### Additional Information

Any help would be appreciated.

**Comment by LittleJay1985** [comment]
Are you trying to run on an arm64 Mac?
Looks like it's trying to load a x64 lib and failing due to incorrect architecture.

Does SDL2 support Mac arm64?

**Comment by poachedegg12** [comment]
Yes, I'm using the M1 Mac, and I'm not sure if SDL2 supports it. Can I fix it somehow?

**Comment by poachedegg12** [comment]
I've installed SDL2 and it's still giving the same error.

**Comment by LittleJay1985** [comment]
Sorry I thought I replied a few hours ago with a list of none macos ARM64 libraries.
Currently most of the native macos libraries in tmodloader aren't universal x64/ARM64
I don't own a Mac but I'm under the impression that you can still run x64 software?

**Comment by LittleJay1985** [comment]
Currently these libraries need to be recompiled as universal binaries for macos with ARM64:
libFAudio.0.dylib
libFNA3D.0.dylib
libnfd.dylib
libSDL2-2.0.0.dylib
libtheorafile.dylib


If anyone reading this has a Mac or MacOS VM setup, recompiling these with ARM64 support should fix these issues.

**Comment by poachedegg12** [comment]
Are there instructions anywhere on how to do this? I've never tried anything like this before.

**Comment by LittleJay1985** [comment]
Download the latest dotnet osx x64 runtime https://download.visualstudio.microsoft.com/download/pr/8b68e217-8a0a-4398-9559-7767c973b26c/e322082fa4280a2b1f0904d74750aeec/dotnet-runtime-6.0.18-osx-x64.tar.gz
Extract to your TModLoader\dotnet\6.0.0 folder making sure that you end up with the the contents of TModloader\dotnet\6.0.0 as:
host
shared
dotnet
LICENCE.txt
ThirdPartyNotices.txt

Try to run.
According to https://support.apple.com/en-gb/HT211861 It will ask you to Rosetta.
Then Play

Hopefully that helps.

**Comment by poachedegg12** [comment]
I think it's working now, but I can't open the program due to restrictions that prevent me from opening the .dylib files (saying they're from an unverified developer.) If you can think of a fix for this (forcing apple to open the program doesn't work), please let me know, otherwise I think it should work on most Macs now.

**Comment by LittleJay1985** [comment]
You could try https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

Could you post the latest launch.log and client.log?

**Comment by poachedegg12** [comment]
[Launch.log](https://github.com/tModLoader/tModLoader/files/11750640/Launch.log)
[client.log](https://github.com/tModLoader/tModLoader/files/11750641/client.log)
At the end of launch.log is where the message comes up saying the .dylib can't be opened. Unfortunately the apple guide doesn't work, however I'm working on signing the files with a certificate myself.

**Comment by poachedegg12** [comment]
After painstakingly creating certificates and signing .dylib files and unquarantining files myself, I have finally launched tModLoader. Thank you so much for all your help.
Final .log files:
[Launch.log](https://github.com/tModLoader/tModLoader/files/11750760/Launch.log)
[client.log](https://github.com/tModLoader/tModLoader/files/11750763/client.log)
Helpful links if someone wants to try the things I did:
https://stackoverflow.com/questions/61168329/how-can-i-sign-a-dylib-using-just-a-normal-apple-id-account-no-developer-accou/61176509#61176509
https://stackoverflow.com/questions/58457958/visual-studio-code-cant-be-opened-because-apple-cannot-check-it-for-malicious

**Comment by LittleJay1985** [comment]
I'm glad your all up and running now.
