### ISSUE TITLE
tmodLoader cant run because i didnt run it on steam ig?

### ISSUE THREAD

**Issue by helloworld578** [bluemagic123/tModLoader#3544]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

It says that "A client log file error information has been generated in E:\CUMO ESTAS\*******\Terraria.v.1.4.4.9.v4\tModLoader-Logs
(You will need to share this file if asking for help)" it says

What can I do here i've been trying to fin

### Log File

[tModLoader-Logs.zip](https://github.com/tModLoader/tModLoader/files/11737674/tModLoader-Logs.zip)

### Steps to reproduce

I copied the whole files and put the tmodloader files into the original terraria
then i put terraria into steam and ran it right after that the tmodloader automatically ran but it said that the file must be run to steam 

I dont really know why it said that but there must be an error or smthn?

### Expected Behavior

the tmodloader menu opens up?

### Actual Behavior

it doesnt run

### Reproduction frequency

3 times i did it and checked the internet if theres a way to do it i even tried dnspy but i never knew how to use it and where to change some stuff i know so little about coding but still i can somewhat understand some stuff

### Additional Information

nothing much rlly

**Comment by JavidPack** [comment]
Since you indicated you bought the game on Steam, you should be installing the game through Steam. Installing the game in the way you did is not supported, please follow the install instructions: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#steam-installation

**Comment by helloworld578** [comment]
im using a cracked version sorry for not specifying that part.

**Comment by JavidPack** [comment]
Sorry, that is obviously not something we can help with.

**Comment by helloworld578** [comment]
No problem, I understand.

**Comment by getCursorsExe** [comment]
> im using a cracked version sorry for not specifying that part.

Lock this thread right now.

**Comment by getCursorsExe** [comment]
And do not allow helloworld578 to open any more issues.
