### ISSUE TITLE
Interface Overlay Bug (Controller)

### ISSUE THREAD

**Issue by LightStreakz** [bluemagic123/tModLoader#3548]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

This seems to be a bug where the "Enter Server Password" interface is overlapped with the "Starting Server" display. Even when I leave the multiplayer world, the "Enter Server Password" interface is still there while overlapping the main menu. If you try to cancel, it will keep switching between the world select and "Enter Server Password" interface which eventually causes a crash. I have addressed this issue before nothing was done about it.

### Log File

![image](https://github.com/tModLoader/tModLoader/assets/39343006/913fcf32-6819-4696-bea6-3ab5792893b9)

### Steps to reproduce

1. Start the game and select the "Multiplayer" option.
2. Select the player and world until you get to the "Enter Server Password".
3. Enter a password and wait for the world to start. The "Enter Server Password" interface is still there causing a functional and visual error. 
4. Leave the world and the "Enter Server Password" interface is still there.
5. Trying the cancel or mashing the button on the controller to exit causes a Main Engine Crash.

### Expected Behavior

The "Enter Server Password" interface should disappear once you have entered the password and the "Enter Server Password" interface shouldn't be present once you leave the world. 

### Actual Behavior

Once the password is entered, the "Enter Server Password" interface is still there and overlaps the "Starting Server" and it still remains even once you have left the world, causing an overlapping with the main menu.

### Reproduction frequency

Every single time.

### Additional Information

This only occurs on Multiplayer, and it occurs for both 1.4.3 and 1.4.4 preview. Even with or without mods, this happens. 
Using a Controller.

**Comment by LittleJay1985** [comment]
I'm struggling to replicate this issue.
Could you please post your logs?

**Comment by JavidPack** [comment]
I also couldn't replicate. Make sure when testing with no mods that you disable all mods, then completely close the game and reopen the game. Send us logs after you do that and replicate the issue.

**Comment by LightStreakz** [comment]
I have video proof, but the file size is too big.

**Comment by LightStreakz** [comment]
![Screenshot 2023-06-14 151551](https://github.com/tModLoader/tModLoader/assets/39343006/a018abb3-1633-43e1-8e8d-0f5b857eb621)

**Comment by LightStreakz** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/11750629/client.log)

**Comment by LightStreakz** [comment]
I have zero mods enabled. Don't know why it's saying it could be a mods' fault.

**Comment by LittleJay1985** [comment]
It TModLoader being blocked by Windows firewall?

Edit: I've just tried blocking in windows firewall but it didn't replicate the issue.

**Comment by LittleJay1985** [comment]
1. Can you also post the server.log
2. Have you tried creating a new character and world?
3. was the log file after you disabled all mods? for example Exalt

Looking at the client.log it seems to be crashing at tModLoader\Terraria\GameContent\UI\States\UIWorldSelect.cs:line 158
`bool num = Main.ActivePlayerFileData.Player.difficulty == 3;`
when populating the world list?

In the client.log it doesn't even get to loading into the world.

**Comment by LightStreakz** [comment]
1. [server.log](https://github.com/tModLoader/tModLoader/files/11759808/server.log)
Nothing really happens with the interface other than the Redigit's Pick error but that's it. 
2. I have done that multiple times and the same issue still occurs.
3. Yes, the log is after I disable all mods and the same thing happens.

**Comment by LightStreakz** [comment]
![Screenshot 2023-06-15 090143](https://github.com/tModLoader/tModLoader/assets/39343006/d65addab-f798-46b5-9f35-3debed235912)
Just did this now before I enter a world.
![Screenshot 2023-06-15 090249](https://github.com/tModLoader/tModLoader/assets/39343006/f95907ce-d267-4fb4-8425-e8090b592248)
And this is when I leave the world.

**Comment by JavidPack** [comment]
This is quite strange. Have you tried loading a brand new world and player instead? (make these when no mods are enabled)

**Comment by LightStreakz** [comment]
Did it then and did it now. The same issue still occurs with controller. Made sure to do it with no mods enabled.

**Comment by Chicken-Bones** [comment]
#3517 related possibly

**Comment by Mirsario** [comment]
Resolved in e842f3b87dc860ec24d34a6cc0b826fbcaa653a6, was indeed the same issue as above.
