### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by ShitTraesh** [bluemagic123/tModLoader#3562]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I really dont know what is happening and if it is a bug coming from the loader or any mod, but i've been trying to solve it for like 2 weeks now, in discod someone told me to come and left it here, the problem is that when i start a server via steam my friends can't join, they be joining and then a sudden "Connection Lost" error pops up on the game, and we cant play

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11804396/client.log)

### Steps to reproduce

1. Open the game
2. Start a steam server 
3. Friends can't join :(

**Comment by direwolf420** [comment]
Please see if it happens if you host a fresh world with no mods enabled.

**Comment by ShitTraesh** [comment]
> Please see if it happens if you host a fresh world with no mods enabled.

Just tried it and shows the same message

**Comment by direwolf420** [comment]
Post the client log of the joining player, and the server log of the host

**Comment by ShitTraesh** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/11885007/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/11885009/server.log)
 
 Sorry, i wasnt being able to play, so i couldnt get the logs, i think this is what u asked for

**Comment by direwolf420** [comment]
This is with mods enabled, I asked you to test if this happens with no mods enabled. Post logs when you have no mods enabled.
