### ISSUE TITLE
The Game Freezes And Crashes When Clicking Single/Multiplayer

### ISSUE THREAD

**Issue by AlanB2010** [bluemagic123/tModLoader#3566]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When clicking single or multi the game crashes and there is no crash message or anything it's just "Net Host Stopped Working"

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11815107/client.log)

### Steps to reproduce

1.Loading the game
2.Choosing singleplayer or multiplayer
3.Game freezes
4.Clicking the screen 2 times
5.NetHost stopped working

### Expected Behavior

It should go to the character creation/selection

### Reproduction frequency

It Does this every time

### Additional Information

Only 1.3 loads normally and i can play it's just TmodLoader 1.4.3.6

**Comment by JavidPack** [comment]
Looks like a bug with something Calamity saved in one of your players. I suggest taking the player files out of the My Games\Terraria\tModLoader-1.4.3\Players folder and see if you can load the players menu, then move the players back in one at a time refreshing the players menu. Once it stops, that's the broken player file.

Or you can visit the Calamity discord, they might know about your bug and have a fix.

**Comment by AlanB2010** [comment]
it somehow fixed itself when reinstalling tmod but not sure if it is permanent
