### ISSUE TITLE
cant launch the tmodloader

### ISSUE THREAD

**Issue by GaS-PEDaL** [bluemagic123/tModLoader#3572]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

launching the game as player

### Description

when i try to open the tlmodloader the prompt vanishes instantly with no error but in the logs says this 

launch log:

Windows Version 10.0
Quick Edit Disabled
Verifying .NET....
Logging to E:/SteamLibrary/steamapps/common/tModLoader-1.4.4/patches/tModLoader/Terraria/release_extras/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "E:/SteamLibrary/steamapps/common/tModLoader-1.4.4/patches/tModLoader/Terraria/release_extras/dotnet/"
Loaded Custom Arguments: 
Launched Using Local Dotnet

Natives log:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-tModLoader.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

what should i do to fix this ?

**Comment by GaS-PEDaL** [comment]
"as a player"

**Comment by JavidPack** [comment]
Given that the logs says it is logging to `E:/SteamLibrary/steamapps/common/tModLoader-1.4.4/patches/tModLoader/Terraria/release_extras/tModLoader-Logs/Launch.log`, it really looks like you downloaded the tModLoader source code and tried to build tModLoader yourself and messed something up while doing that.

We don't expect users to build the game themselves, I suggest deleting what you have and following our manual install instructions: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Comment by GaS-PEDaL** [comment]
im just a player that want to open tmodloader with gog copy of the game i looked up the wiki it said to open the tmodloader from E:\SteamLibrary\steamapps\common\tModLoader-1.4.4\patches\tModLoader\Terraria\release_extras\start-tModLoader 
to launch the tmodloader

**Comment by JavidPack** [comment]
Can you link me to where it says that?
