### ISSUE TITLE
Move Remix Hallow worldgen into HardmodeGoodTask void

### ISSUE THREAD

**Issue by Lion8cake** [bluemagic123/tModLoader#3574]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

A change to smCallBack to make the remix worldgen call both the "Hardmode Good" and the "Hardmode Evil" Passes and have the remix hallow worldgen be ran in the "Hardmode Good" pass

Here is my pull request fixing this issue
https://github.com/tModLoader/tModLoader/pull/3575

### What does this proposal attempt to solve or improve?

This is to allow modders to add ontop or edit the remix world gen as HardmodeGoodTask and other tasks are never ran in the remix seed.

**Comment by Lion8cake** [comment]
actually made it a pull request instead of a commit to my fork (rip)

**Comment by JavidPack** [comment]
Handled in #3606
