### ISSUE TITLE
Coatings World Save Issue (1.4.4-preview)

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3580]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to apply coatings to Tiles/Walls the world doesn't save them properly if the player has tried painting the walls in certain directions. This applies to echo coating too.

This only applies to the 1.4.4-prevew the previous versions seem to be lacking this problem.

I have provided 2 images:
* The one with the spiral is the one before the world was saved
* The one which appears to have some of the walls not painted is after the world was saved and the player joined the world

![spiral1](https://github.com/tModLoader/tModLoader/assets/114251424/4779d4ed-a167-48a4-ad4c-8d8cdd0c783e)
![spiral2](https://github.com/tModLoader/tModLoader/assets/114251424/c4fb1afb-8d90-4e20-b086-74a491ba8659)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11858002/client.log)

### Steps to reproduce

1. Build a simple rectangle of any walls
2. Paint a simple spiral with any of the coatings
3. Exit and save the world
4. Reopen the world to get the bug

### Expected Behavior

Upon world exit, save, loading again you should have walls which have their coatings in the same place as you painted them last time you were in the world.

### Actual Behavior

Upon world exit, save, loading again you should have walls which are lacking coatings.

### Reproduction frequency

Everytime

**Comment by Rijam** [comment]
I can confirm. I was able to reproduce this. It only saves the rows of coating and not the columns. This does not happen with paints, btw (only coatings).
