### ISSUE TITLE
Localization overrides

### ISSUE THREAD

**Issue by Tyndareus** [bluemagic123/tModLoader#3581]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Put in some option to override values and use the old system as it was. I have a system using the LocalizationLoader as well as the standard DisplayName setting.

I was using LocalizationLoader.GetOrCreateTranslation, because I have various custom keys and data in my hjson that represent things like titles, unique npc dialogue. Even areas where I have formatted the string based on localization because in the localization I have put `string.Format(ClassTooltip.GetTranslation(Language.ActiveCulture), lifePercent, damageIncrease);` and similar usage with LocalizedText (returned directly from my LocalizationSystem, which is a light way of saying `LocalizationLoader.GetOrCreateTranslation($"Mods.MyMod.{key}").` Similarly I have a "dynamic buff" which needs to update the display/tooltip when a state changes, so this also runs the usage of GetOrCreateTranslation.

### What does this proposal attempt to solve or improve?

It's currently impossible to manage your own Localizable data. Things that you manually draw or things that you may access differently. Language.GetText may still work but is a little off the beaten path for new modders

**Comment by Tyndareus** [comment]
As mentioned, Language.GetText may be the functional route now, but for existing items it would likely still be preferred to manually override it.
In the Industry we usually keep large systems functionally working when updating, by marking the previous use as "Deprecated" and then produce some documentation to follow with the intention that the next minor push the functionality would be removed. DisplayName you would have to leave the same until that deprecation pass has been done. At which point you have given people enough of a warning to change the code or it will break... Rather than this large change without much of an upgrade guide other than "It's changed, good luck"

For now I will be reworking around usage of Language.GetText but honestly would have just been more preferred if the type was changed, I then had to go "Alright just switch to DisplayName = [insert tmod approved method in the migration guide]"

Some good changes in other areas though

**Comment by direwolf420** [comment]
> It's currently impossible to manage your own Localizable data

I don't get the point. I utilize tmls new localization system and have had no issues with it organization/data wise. More specifically, you can store localizations returned from `Language.GetOrRegister` as `LocalizedText` objects to then use in various ways, i.e. `LocalizedText.Format` or `LocalizedText.WithFormatArgs`. Can you showcase something very specific that you did the old way which just doesn't work with the new system at all now?

The things you mentioned can all be done in the new system, check the wiki page for details. https://github.com/tModLoader/tModLoader/wiki/Localization.

**Comment by Chicken-Bones** [comment]
Please re-open if you have a specific issue which you can describe in detail with code snippets or links to specific lines in your repo. Otherwise, if you're struggling with the system after reading the guide linked above, please come to https://discord.com/channels/103110554649894912/1037051160705634369
