### ISSUE TITLE
Shorten the 1.4.4-preview message in the BETAS opt in panel on Steam

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3582]
### Do you intend to personally contribute/program this feature?

No, I don't have access to that sort of information

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Given the new Steam layout update, the way the BETAS are displayed now are unreadable when you have a very long message. In other words, only the ending of the message is shown because of it's length, and the beginning of the messages do not display.

![image](https://github.com/tModLoader/tModLoader/assets/70764728/d70a8073-348d-4873-84ed-d1eff5880daf)

What can happen is that the entire message gets shortened, to remove the "The none branch is the stable 1.4 version" part of the message. Also, you can remove "1.4.4" in "Test 1.4.4 API changes" because the branch is already for 1.4.4 (that one is up to you).

### What does this proposal attempt to solve or improve?

Right now, you can only see this:
![image](https://github.com/tModLoader/tModLoader/assets/70764728/bf5065a4-657c-4598-b70c-06cc4cac0d0e)

But I want to see the entire message. That's why I want it to be shortened.

### Which (other) solutions should be considered?

You can wait until another Steam update arrives which could make the selection panel scrollable, or just message them to make the update right away.

**Comment by direwolf420** [comment]
That sounds more like a steam bug to me

**Comment by Solxanich** [comment]
I think Steam fixed this in the last update? 
Please confirm

**Comment by JavidPack** [comment]
Still bugged, even tried the Steam client beta.

**Comment by Solxanich** [comment]
![image](https://github.com/tModLoader/tModLoader/assets/59670736/941085c5-a6a9-49ba-a5ed-a82661d084ff)

My current display on Steam Desktop Client. 

And my steam version : 
![image](https://github.com/tModLoader/tModLoader/assets/59670736/3a170b98-2550-4b23-abcb-4a03ae5cb958)

**Comment by Setnour6** [comment]
I have the same version:
![image](https://github.com/tModLoader/tModLoader/assets/70764728/77c7931a-a1a0-4461-a9e7-80aa6ebd366d)
I'm also using the desktop client

I see that the size of the dropdown is based on the selected beta text length.
![image](https://github.com/tModLoader/tModLoader/assets/70764728/4c1d5882-5ee2-401a-b463-5c1b3aae4d74)
![image](https://github.com/tModLoader/tModLoader/assets/70764728/40969dd6-c02c-4f07-a5aa-da5cef872765)

We might have to contact the steam developers to see if they can fix that dropdown sizing issue.

**Comment by JavidPack** [comment]
We did report this through a contact we have, haven't heard back yet, but if someone wants to make a post on https://steamcommunity.com/groups/SteamClientBeta/discussions/0/ and others upvote/comment, it might get more priority from the steam devs.

**Comment by KosMos-pv** [comment]
This is finally fixed in latest steam beta client so it will be fixed as soon as this fix will be available in release version of steam.

**Comment by JavidPack** [comment]
Thanks for letting us know. I just checked myself and it looks fixed. Hopefully it'll come to stable quickly.

**Comment by JavidPack** [comment]
Looks like the fixed UI is now in steam client stable. Closing.
