### ISSUE TITLE
'featured' property of stacked items works improperly

### ISSUE THREAD

**Issue by Polaritz** [bluemagic123/tModLoader#3584]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when picking up stacked-featured-items from inventory with right click, 'featured' property moves to right-clicked-stacked items

### Steps to reproduce

1. feature stacked-items like dirt
2. pick it from inventory with right click, more than 2
3. put them down to another slot of inventory to check

### Expected Behavior

right-clicked items are separated from featured-stacked items
'featured' property remains to preexisting stack

### Actual Behavior

'featured' property moves to separated stack
which means 'featured' property of preexisting stack disappears

### Reproduction frequency

always

**Comment by Chicken-Bones** [comment]
Fixed in https://github.com/tModLoader/tModLoader/commit/e64e561f4a4a9b890df8330dadee366882c1493c
