### ISSUE TITLE
Tmodloader performance issue caused by Service Host DCOM server process launcher.

### ISSUE THREAD

**Issue by cozykoko** [bluemagic123/tModLoader#3590]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Performance of the game tanks big time whenever i join my world. With or without mods and 1.4.4 or 1.4.3. Its all the same. Doesn't happen in normal terraria though.  Already tried some fixes like changing the timezone, updating windows, disabling live tiles. 

Pc: w11 9700k 16gb 3200mhz rtx 2070 super 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11888059/client.log)
![Screenshot_2023-06-27_184735](https://github.com/tModLoader/tModLoader/assets/76956629/43c442a9-13a9-48e3-94c2-d0ad7ae7d4a1)

dottrace https://send.vis.ee/download/78cf7c9b6bcf926f/#dVNFM-wK232VR2iQQKrFiw

**Comment by Chicken-Bones** [comment]
Googling "DCOM Server Process Launcher" performance issues shows that many people have experienced the same thing and it's not just tModLoader related. You'll have to look elsewhere on the internet for a fix, but please update us with what you find.

Since you went to the effort of providing a dotTrace file, I will look at it to see if there's anything that could guide your search

**Comment by Chicken-Bones** [comment]
The dump doesn't tell me much other than CPU starvation. If you DM me on Discord I could try and send you some tML test builds to experiment with some things

**Comment by Chicken-Bones** [comment]
You got me curious, and I was able to reproduce the same sort of performance issues by causing contention on my own system. Ultimately, something is still using 75% of your CPU and that's not tML's fault, but tML performance can be improved under contended scenarios so I will be attempting that

**Comment by Chicken-Bones** [comment]
The performance improvements will arrive sometime in the future, not sure when yet.

**Comment by cozykoko** [comment]
I think youre right the problem seems to be with my pc/cpu. Wasnt able to fix it though.

**Comment by cozykoko** [comment]
Fixed it by going back to windows 10 ltsc
