### ISSUE TITLE
Linux Servers

### ISSUE THREAD

**Issue by StripedMonkey** [bluemagic123/tModLoader#36]
I'm coming into this knowing nothing of modded terraria (Friend is trying to get me to host), I understand that insofar there is only a windows server?

**Comment by JavidPack** [comment]
That is correct. There is a bug that we have yet have time to look into.

**Comment by Rahmiel** [comment]
So are Linux servers working now or not? I'm terribly confused by this whole process. If they are working is there documentation on how to get a Linux server running, because for all our attempts we have not been able to do so.

**Comment by JavidPack** [comment]
I thought they were, since I was able to run the server using Bash on Ubuntu on Windows, but further testing tells me others haven't been able to do it yet. I'll have to test more on an actual linux partition. For the record, I just ran mono tModLoaderServer.exe

**Comment by StripedMonkey** [comment]
.exe is not something you can run on linux. If you would like me to test
this for you I'm fine with giving you results and feedback.

**Comment by StripedMonkey** [comment]
Unless you use wine which is not ideal in any way shape or form for a
server.

**Comment by bluemagic123** [comment]
.exe files actually can be run on Linux; the mono command mentioned earlier will run C# programs. Terraria itself is an .exe, even on Linux.

**Comment by StripedMonkey** [comment]
Oh really? I never could get the .exe to run. On the other hand Terraria
has a .x86 executable that you can run which is what I assumed it was
running.

**Comment by Chicken-Bones** [comment]
@JavidPack @bluemagic123 take a look at the accompanying files in the distributed mac/linux server. They use https://github.com/OutOfOrder/MonoKickstart
