### ISSUE TITLE
Get rid of countdown on migration warning.

### ISSUE THREAD

**Issue by SakoPolis** [bluemagic123/tModLoader#3607]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

When being warned about the 1.4.4 migration there is a countdown before you can proceed. This is an anti-feature and dark pattern that has no place in open-source software. Also, it is way too long for such a short message.

### What does this proposal attempt to solve or improve?

Removing the countdown makes the software less intrusive.

### Which (other) solutions should be considered?

You could have the message show up somewhere else without being intrusive if you don't want it to be closed to early.

**Comment by JavidPack** [comment]
Is the message unclear or displaying when you are on 1.4.3-legacy branch as directed? The whole point is for the user to follow the instructions, thereby being "safe" from the upcoming changes. We are trying to prevent a situation where a user in the middle of a playthrough would find themselves in a broken state come August. 

What is the use-case where a user shouldn't close the game and follow the instructions immediately?

**Comment by SakoPolis** [comment]
I takes a couple of seconds for tmodloader to load all of the mods, it can be shown then, or just not have a countdown at all.

**Comment by Chicken-Bones** [comment]
You need to follow the instructions to make the message go away permanently

**Comment by SakoPolis** [comment]
sorry I might have explained it wrong. I am aware of what the warning is, it just shouldn't hijack the game with a countdown like a windows update would.
