### ISSUE TITLE
some of the mods doesnt work for the newst version.

### ISSUE THREAD

**Issue by NG7652** [bluemagic123/tModLoader#3609]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

**Comment by Setnour6** [comment]
This issue goes towards the mods themselves, as some of the mod authors haven't updated their mod(s) to the latest version of tModLoader that you are running.
The best course of action is to wait for the mod authors to update the mod. You can also ask them to do so.

**Comment by Solxanich** [comment]
Please provide more detail as to which mods exactly and client.log files. 
Otherwise, may have to close as insufficient info to action
