### ISSUE TITLE
failed to handle save data, fatal error

### ISSUE THREAD

**Issue by LeToast69** [bluemagic123/tModLoader#3611]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

upon startup it will crash shortly after launching using dot net on the console

### Log File

![image](https://github.com/tModLoader/tModLoader/assets/139006182/218782b5-90b1-42e0-ac95-7bafe77ca6be)

![image](https://github.com/tModLoader/tModLoader/assets/139006182/02927821-0044-4a57-82e4-e48678ba88d5)

[client.log](https://github.com/tModLoader/tModLoader/files/11991463/client.log)

### Expected Behavior

launching succesfuly

### Actual Behavior

fatal error almost immediately 

### Reproduction frequency

100%

### Additional Information

problem continued even after redownload

**Comment by Solxanich** [comment]
https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#save-data-file-issues

Please take a look there at the JSON Reader instructions to resolve

**Comment by yagercore** [comment]
Thanks for the help
