### ISSUE TITLE
[NixOS] Cannot launch the game

### ISSUE THREAD

**Issue by PassiveLemon** [bluemagic123/tModLoader#3612]
### Version

Other (please specify elsewhere)

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When launching the game, Steam will show the launch process but then stops and no window ever shows up.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11995604/client.log)

I can try to launch it through the terminal too. Here is the output:
```
$ steam steam://rungameid/1281930
steam.sh[3766889]: Running Steam on nixos 23.11 64-bit
steam.sh[3766889]: STEAM_RUNTIME is enabled automatically
setup.sh[3767046]: Steam runtime environment up-to-date!
run.sh[3767063]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[3766889]: Steam client's requirements are satisfied
```

### Steps to reproduce

1. Launch game
2. Observe problem

### Expected Behavior

Game launches

### Actual Behavior

Game does not launch

### Reproduction frequency

Every single time, with all versions in the betas tab. This is why I did not specify a version.

### Additional Information

I'm worried that this is more so an issue with my distro (NixOS) just because of the way it manages executables. However, I have used TML on it before, I only encountered the error recently.

**Comment by Solxanich** [comment]
My initial thoughts are:
1) Try deleting the 'dotnet' folder in the install folder
2) Verify you are running with no compatibility tools from Steam - no Proton, no steam sniper. 
3)  Can you post other logs like natives.log? I'm curious if same error from terminal is there

My gut says this is an issue with steam desktop client itself.  I've never seen this error before
executing "/sbin/ldconfig -XNv"

**Comment by PassiveLemon** [comment]
1. I have completely deleted the game folder 
2. I don't have proton running but I'm not able to remove sniper because of shared libraries
3. Here's the other logs:
[environment.log](https://github.com/tModLoader/tModLoader/files/12014479/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12014480/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/12014481/Natives.log)

On the topic of launching, do you maybe happen to know why Steam will no longer launch games after being open for a while? I will then have to completely restart Steam to be able to launch games. This doesn't really have to do with TML but maybe you know?

**Comment by PassiveLemon** [comment]
Solution: Install `dotnet-sdk` from nixpkgs and create a symlink from the store binary to your TML installation. Ex: `ln -s /run/current-system/sw/bin/dotnet /home/<user>/.local/share/Steam/steamapps/common/tModLoader/dotnet/6.0.0/dotnet`

**Comment by Solxanich** [comment]
Thanks for the tip on how you fixed it!

I've added that tip our Usage FAQ as well for future users.

**Comment by PassiveLemon** [comment]
I would update that to say: "Install the dotnet sdk from your package manager and symlink the binary to the tmodloader dotnet location," and then mention that the example I had provided is for NixOS. Just some better clarity for users who don't use NixOS
