### ISSUE TITLE
Virtualize LocalizationCategory property in all ModX classes that implement ILocalizedModType interface

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#3613]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Virtualize `LocalizationCategory` property in `ModX` classes.

### What does this proposal attempt to solve or improve?

Currently, you can't override that property in any of existing classes (except `ModTile` and `ModWall` since they inherit `ModBlockType` which forces implementation of that property). That means if you want to make it so localization path is same as namespace (e.g. `ExampleMod/Content/Items/ExampleItem` namespace -> `ExampleMod.Items.ExampleItem`), you forced to override `DisplayName` (and `Tooltip` in `ModItem`) and use `Language.GetOrRegister` instead of that one extension method. While it is fine. It would be much simpler if we could just override `LocalizationCategory`.

**Comment by direwolf420** [comment]
This is done here <https://github.com/tModLoader/tModLoader/commit/ffea871bc30f5eea3ba0f4d2162ce26c38d8eb2d>, will be on preview next month

**Comment by BasicallyIAmFox** [comment]
> This is done here [ffea871](https://github.com/tModLoader/tModLoader/commit/ffea871bc30f5eea3ba0f4d2162ce26c38d8eb2d), will be on preview next month

![image](https://github.com/tModLoader/tModLoader/assets/65787578/6136679c-d84c-48de-91ac-a79e58c6cf5e)
Uh huh?

**Comment by JavidPack** [comment]
It's not next month yet

**Comment by BasicallyIAmFox** [comment]
> It's not next month yet

im on 1.4.4 preview tho. isnt it supposed to be on preview?

**Comment by BasicallyIAmFox** [comment]
ok mb, just was confused a little lol
