### ISSUE TITLE
tModLoader on termux

### ISSUE THREAD

**Issue by subtogash** [bluemagic123/tModLoader#3618]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

~/tModLoader $ sh start-tModLoaderServer.sh 
start-tModLoaderServer.sh: 7: [[: not found
start-tModLoaderServer.sh: 25: [[: not found
Use steam server (y/n): y
start-tModLoaderServer.sh: 33: [[: not found
You are on platform: "Linux"
Verifying .NET....
This may take a few moments.
Logging to /data/data/com.termux/files/home/tModLoader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Update Required. Will now attempt downloading using official scripts.
This can take up to 5 minutes
./BashUtils.sh: line 33: ./dotnet-install.sh: cannot execute: required file not found
Dotnet should be present in "/data/data/com.termux/files/home/tModLoader/dotnet/6.0.0"
Download of portable dotnet runtime seems to have failed,
Proceeding will probably fall back to system wide installed runtime
cat: /data/data/com.termux/files/home/tModLoader/cli-argsConfig.txt: No such file or directory
Loaded Custom Arguments: 
Attempting Launch...
Launched Using System Dotnet

### Log File

Verifying .NET....
Logging to /data/data/com.termux/files/home/tModLoader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Update Required. Will now attempt downloading using official scripts.
This can take up to 5 minutes
./BashUtils.sh: line 33: ./dotnet-install.sh: cannot execute: required file not found
Dotnet should be present in "/data/data/com.termux/files/home/tModLoader/dotnet/6.0.0"
[31mDownload of portable dotnet runtime seems to have failed,[0m
[31mProceeding will probably fall back to system wide installed runtime[0m
Loaded Custom Arguments: 
Launched Using System Dotnet

### Steps to reproduce

1. install this (1.4.3-Legacy Version Update: v2022.09.47.74) from github versions on termux
2. run (sh start-tModLoaderServer.sh), ./start-tModLoaderServer.sh not work on my termux
3. have an error

**Comment by JavidPack** [comment]
Am I correct that you are trying to launch tModLoader on an Android OS using a terminal emulator? That's definitely not a supported configuration, I'm pretty sure this won't work.

**Comment by m3t4f1v3** [comment]
well first off you should be using bash instead of sh to launch but the underlying issue is that there are seemingly no cli builds for android, your best bet would be to use a linux proot

**Comment by subtogash** [comment]
> well first off you should be using bash instead of sh to launch but the underlying issue is that there are seemingly no cli builds for android, your best bet would be to use a linux proot

I don't understand how to do it, I'm new to Linux and I don't know what Proot is.

**Comment by m3t4f1v3** [comment]
[here](https://wiki.termux.com/wiki/PRoot) are some resources
i'd go with ubuntu for ease of use
