### ISSUE TITLE
Profile for mods

### ISSUE THREAD

**Issue by A7Delta57** [bluemagic123/tModLoader#3622]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Dear Tmodloader devs.
I tend to have a crazy playstyle style when it comes to modded terraria, most of the time running two passthroughs at the same time and also play a lot with my friends. As a consequence i have to swap between my mods so frequently that i though if i could make a profile and have some certain mods disabled or enabled by one click it would help me out so much since while swapping between two major mods like fargo's soul mod and calamity i need to switch 10+ mods. I would like to have a profile feature added to the mod manager section. 
Love.❤

**Comment by JavidPack** [comment]
This does exist, it is called "mod packs". You'll find the mod packs menu in Workshop->Mod Packs. You can use that menu to create or enable specific mod packs.

To make it even easier and to save time reloading mods, you could make desktop shortcuts for each modpack to launch the game directly using a specific modpack: https://github.com/tModLoader/tModLoader/wiki/Command-Line#windows-shortcut
