### ISSUE TITLE
tmodloader couldt handle save data

### ISSUE THREAD

**Issue by okamisa** [bluemagic123/tModLoader#3623]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

ive been playing for like a month now and suddenly like 5 days ago it popped up an error that tmodloader couldnt handle my save data when i tried to launchand then i searched it up and someone said i should download the desktop runtime 6 and i thought because its an microsoft official nothing there could make it worse so then i did but it didnt do anything and then i tried to replace the config.json file with the one in the problem fixing thingy but still nothing so then im here

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12031123/client.log)

**Comment by JavidPack** [comment]
We are looking into this.

In the meantime, you can manually copy all the files from C:\Users\kimha\Documents\My Games\Terraria\tModLoader to C:\Users\kimha\Documents\My Games\Terraria\tModLoader-1.4.3 to avoid this issue, I think.

**Comment by JavidPack** [comment]
This should work better in the recent updates we've published. I notice that you have a space in a foldername somehow, so you'll need to follow these instructions to delete the illegal filenames: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#illegal-filenames
