### ISSUE TITLE
Hide tooltip lines instead of removing them

### ISSUE THREAD

**Issue by BasicallyIAmFox** [bluemagic123/tModLoader#3640]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Add `TooltipLine.IsHidden` property.

### What does this proposal attempt to solve or improve?

Currently, modders are forced to remove tooltip line if they want to hide it.
Removing potentially leads to mod conflicts. (In fact there were cases of that in past)

**Comment by JavidPack** [comment]
Related: #2072

**Comment by Chicken-Bones** [comment]
I think this is a simple subset of the larger and more controversial proposal that is easy to implement. Go ahead and PR. Follow the `PlayerDrawLayer` example and do
```cs
public bool Visible { get; private set; } = true;
public void Hide() => Visible = false;
```

**Comment by Chicken-Bones** [comment]
You may also consider doing the same thing to `GenPass` (`Enabled` and `Disable()`)
