### ISSUE TITLE
Erroneous HJSON File Reading Errors

### ISSUE THREAD

**Issue by absoluteAquarian** [bluemagic123/tModLoader#3651]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Attempting to load a mod with seemingly correctly-formatted `.hjson` files instead throws an error.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12137429/client.log)

### Steps to reproduce

1. Boot up `1.4.3-legacy` Betas option
2. Compile code from https://github.com/blushiemagic/MagicStorage/tree/1.4 via `F5` in Visual Studio
3. Wait for mod loading screen to appear
4. Observe errors

### Expected Behavior

Mod loading should just continue like usual, since the localization file — `MagicStorage/Localization/en-US.hjson` — has no formatting issues

### Actual Behavior

Mod loading fails before reaching the main menu

### Reproduction frequency

100%

### Additional Information

n/a

**Comment by JavidPack** [comment]
Fixed in https://github.com/tModLoader/tModLoader/commit/bc6b12bae872718d13cf455e08b8dbaa2bc6d2bc

The issue was a different file, the error message now shows which file.
