### ISSUE TITLE
More localization files for git repo

### ISSUE THREAD

**Issue by Blueberryy** [bluemagic123/tModLoader#3654]
### Description

It would be great if devs can add these texts to this repository and let community translate it.
![steamwebhelper_f7R0MKWChN](https://github.com/tModLoader/tModLoader/assets/36592509/1d05ac45-0624-4d5a-b47f-7f0bd542fa35) "Mods"

![steamwebhelper_KAS7W58kVn](https://github.com/tModLoader/tModLoader/assets/36592509/11239dee-d2e6-4c5a-9e18-4f707596ec19) Front page title and description.

![steamwebhelper_8zZFZJkaeN](https://github.com/tModLoader/tModLoader/assets/36592509/1e6bf55e-ed1f-42f0-8ef9-212fbe5285ba) Developer's Choice custom section.

And store page on Steam would be dope, i'm surprised it's not there yet...

### What does this proposal attempt to solve or improve?

more things to translate for translators.

**Comment by Solxanich** [comment]
Added something for now that can use to localize some large parts of Steam.
Still could be optimized, but gives something

**Comment by Blueberryy** [comment]
> Added something for now that can use to localize some large parts of Steam. Still could be optimized, but gives something

hey can you add "Dual Core 3.0 Ghz", "GB" and "MB" to store page file?

upd; if it's too hardseted then no need

**Comment by Blueberryy** [comment]
And it would be awesome if you could get text like these in tModLoader localization files https://github.com/tModLoader/tModLoader/blob/5164c51d339a9778f2c8a9d9fae3a734fe453802/patches/tModLoader/Terraria/ModLoader/Config/UI/CollectionElement.cs#L123C121-L123C121

**Comment by JavidPack** [comment]
> And it would be awesome if you could get text like these in tModLoader localization files https://github.com/tModLoader/tModLoader/blob/5164c51d339a9778f2c8a9d9fae3a734fe453802/patches/tModLoader/Terraria/ModLoader/Config/UI/CollectionElement.cs#L123C121-L123C121

I've just added these.

**Comment by Blueberryy** [comment]
Now i think that only workshop "Mods" left. It should be translateable in tags panel customization

**Comment by JavidPack** [comment]
I'm not seeing a way to do that one, unfortunately.
