### ISSUE TITLE
Bugged bug sprite.

### ISSUE THREAD

**Issue by EpicCamer** [bluemagic123/tModLoader#3657]
### Version

Latest 1.4.4 preview

### OS

Windows

### Platform

Steam

### This bug affects

Mob sprites

### Description

When found in the world or spawned manually the stinkbug sprite looks not how its supposed to.

### Log File

https://github.com/tModLoader/tModLoader/assets/140448555/ec23e4d9-e817-483e-84a0-9b5945555bad

![20230724_224702](https://github.com/tModLoader/tModLoader/assets/140448555/ea3afcfb-a645-43b9-bae5-a4b091d164f3)

**Comment by JavidPack** [comment]
I wish you posted the client.log, I would like to rule out resource packs. I just tested and it's working.

**Comment by Destructor-Ben** [comment]
Wasn't this caused when the vanilla assets didn't update from 1.4.3 to 1.4.4 properly so some sprites were left out and verifying the game files fixed it?

**Comment by EpicCamer** [comment]
Issue resolved after deleting and freshly installing tModLoader. Don't know what caused the issue but it was probably something like what Ben commented about.
