### ISSUE TITLE
it seems the players can't obtain the carrot on tmodlaoder 1.4.3 

### ISSUE THREAD

**Issue by Jacky10X** [bluemagic123/tModLoader#3661]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If you are a "Collector's Edition" 's player. you can obtain the carrot when you start a new player.
But when you are using tML 1.4.3. you can't obtain the carrot.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12162676/client.log)

### Steps to reproduce

1. Start a new player.
2. Does not obtain carrot.

### Expected Behavior

Obtain carrot.

### Actual Behavior

Does not obtain carrot

### Reproduction frequency

Always.

### Additional Information

It seems tML 1.4.4 has fixed the glitch while tML 1.4.3 still has this issue.
But there are plenty of mods still on 1.4.3. I hope tML 1.4.3 also fixes this glitch.

I am using Windows platforms. So I don't know if Collector's Edition on Mac or Linux also works in tML.

**Comment by JavidPack** [comment]
Should be fixed via 5e4cce92f65a091e68595539847a4ddf82c17962

**Comment by Jacky10X** [comment]
@JavidPack 
Hello, thanks for the fix. 
It seems the fix only applied to the Windows platform.
Mac and Linux can also enable Collector Edition. Instead of using the Windows registry. 
The Mac and Linux use mono registry. And I found Mono registry provides Microsoft.Win32.Registry class for accessing the registry.

So I think the solution is
there is no need to check if the operating system is Windows or not. Because the mono registry also works like the Windows registry.

And I found that 1.4.4 tML also has this issue. [Mac & Linux]

**Comment by JavidPack** [comment]
We no longer use mono, so I believe we can no longer use that workaround. The current code will crash on non-windows if we enable it.

We will likely not fix this on linux and mac, any solution would be far too involved to be worth the effort. The windows fix was easy since it was already done elsewhere.

**Comment by steviegt6** [comment]
https://retkomma.wordpress.com/2011/10/01/registry-settings-in-mono-on-linux/

This should shed some light on how Mono simulated the Windows Registry. Given the limited usage in Terraria, writing a really simple method for \*nix that checks the appropriate file is all that's really needed.

**Comment by JavidPack** [comment]
Well, I don't mind if someone on linux implements that and tests it, if they want to make a Pull request. You can make a separate issue for that if you want.
