### ISSUE TITLE
ModTree.Shake createLeaves parameter unused

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3665]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Title. It's added by tml but not used

**Comment by JavidPack** [comment]
Not sure what to do about this one, 1.4.4 changed it so leaves always spawn regardless of if an item is spawning, the parameter is now unused by vanilla. I guess we could leave it for if someone does a custom treefx for a specific drop...

It would now default to true though instead of false.

**Comment by Chicken-Bones** [comment]
Need to review and decide whether to remove. @direwolf420 do you think the lack of ability to disable leaf creation would be a significant regression?

**Comment by JavidPack** [comment]
Oops, didn't see this. I assumed modders might want to be able to do a custom shake effect in specific situations, so I left it in and fixed it so it'll skip the vanilla tree fx code. The default is now true to match vanilla changes.
