### ISSUE TITLE
Melee speed incorrectly affects mining speed

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3667]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

According to https://youtu.be/wns19sBE5L0?t=73, accessories that affect melee speed are incorrectly affecting mining speed.

**Comment by jjohnsnaill** [comment]
Setting `attackSpeedOnlyAffectsWeaponAnimation` to true (or `DamageType` to `MeleeNoSpeed`?) on items with `pick`, `axe` or `hammer` > 0 fixes the issue. Not sure if any items don't fit this criteria but it'd be such an obscure difference that I'd consider it a vanilla bug fix at that point.

**Comment by Chicken-Bones** [comment]
I don't know why this idea escaped me. Does melee speed actually make pickaxes swing faster in vanilla? What about drills?
