### ISSUE TITLE
Certain unsafe walls drop their shimmer variant when broken

### ISSUE THREAD

**Issue by Destructor-Ben** [bluemagic123/tModLoader#3668]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When breaking any unsafe wall that also has a variant that can be obtained from shimmer (spider walls, lihzhard walls, dungeon walls, and the 2 underground sandstone walls), the item obtained from shimmer is dropped instead of nothing.

### Log File

N/A

### Steps to reproduce

1) Find or place an unsafe wall in game, such as the Infested Spider Wall
2) Break it
3) Observe that it drops an item that allows it to be placed again instead of nothing

### Expected Behavior

Nothing should drop

### Actual Behavior

The item used to place it should drop

### Reproduction frequency

Always

**Comment by Destructor-Ben** [comment]
Cause is likely because `WallLoader.FinishSetup()` doesn't have a check for only modded walls. Tiles may have the same issue as well.
```cs
internal static void FinishSetup()
{
  for (int k = 0; k < ItemLoader.ItemCount; k++) {
    Item item = ContentSamples.ItemsByType[k];
    if (!ItemID.Sets.DisableAutomaticPlaceableDrop[k]) {
      if (item.createTile > -1) {
        // TryAdd won't override existing value if present. Existing ModTile.RegisterItemDrop entries take precedence
        tileTypeAndTileStyleToItemType.TryAdd((item.createTile, item.placeStyle), item.type);
      }
    }
  }
}
```

**Comment by JavidPack** [comment]
Thanks. I'll be able to fix it. Tiles are fine, the dictionary is only consulted for modded tiles, I just need to add the same guarantee for walls.

**Comment by Destructor-Ben** [comment]
Ah sorry didn't see the comment till I made the PR, I can let you do it if you still want to?
I can also remove the part fixing tiles if they are fine.
