### ISSUE TITLE
screen shaking, intense lag, and parts of game not loading.

### ISSUE THREAD

**Issue by Musicmarie** [bluemagic123/tModLoader#3669]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

screen shaking violently when inside of the menu and when loading into a world the screen doesn't properly fit.

![Screenshot 2023-07-28 213350](https://github.com/tModLoader/tModLoader/assets/140869541/ab4a3c9a-ab54-438e-bfc1-2237b39072e5)
![Screenshot 2023-07-28 213242](https://github.com/tModLoader/tModLoader/assets/140869541/14418f6b-064e-45bb-b50c-96869ddc1e5c)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12206203/client.log)

### Expected Behavior

Normally it doesn't shake and worlds don't lag, as well as the world properly being oriented instead of having an unloaded area.

### Actual Behavior

Menu's are shaking. worlds lag and the screen won't properly orient.

### Reproduction frequency

I haven't been able to reproduce this issue as i can't get it to stop even via reinstallation.

**Comment by JavidPack** [comment]
Can you disable all mods, then restart the game and confirm the issue? If you do that, post the new client.log

**Comment by Musicmarie** [comment]
> 
Sure thing. all the mods are disabled and it still persisted. 
here's my client log.
[client.log](https://github.com/tModLoader/tModLoader/files/12206228/client.log)

**Comment by Musicmarie** [comment]
How strange. I came back the next day and it seems to have fixed itself.
