### ISSUE TITLE
Weapon swapped bug in GFB/Don't dig up and The cut wires will not automatically enter my backpack

### ISSUE THREAD

**Issue by ckbso19** [bluemagic123/tModLoader#3680]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description
The cut wires will not automatically enter my backpack (any seeds）
![image](https://github.com/tModLoader/tModLoader/assets/105469076/51a790dd-f9db-441a-8018-48fd57fdecf4)

the Treasure Bag of Duke Fishron in GFB has something wrong
the Bubble Gun and Aqua Scepter has swapped in this seed( GFB/Don't dig up)
![image](https://github.com/tModLoader/tModLoader/assets/105469076/e0f6576d-ea0b-46f5-a2a7-b54800b1cc44)
but we still can get the Aqua Scepter from the Golden Lock Box before the Hard mode
Instead, the Bubble Gun appears  which has only 9 magic damage in the Duke Fishron treasure bag
There are many similar examples that have not been fixed（almost all the weapon which has swapped in GFB/Don't dig up)

**Comment by JavidPack** [comment]
The drops have also been fixed in a recent commit.
