### ISSUE TITLE
Bug or Glitch

### ISSUE THREAD

**Issue by Patrikus88** [bluemagic123/tModLoader#3681]
### Version

Latest 1.4.3-legacy

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The color of Switch Menu Theme is blue on newest update v2022,9,47,82 and its suppost be yellow beacouse in the newest 1,4,4,9 update the color is normal yellow and i find that color change in defferents places too like in volue bar or on camera mode icon and housing.
Sorry about my bad English.

### Log File

the color on Switch Menu Theme is wrong its supost to be yellow not blue the same issue is on camera mode and volue music bars.
This i the newest 1,4,3 update on 1,4,4 there is no problem.
![obraz_2023-08-01_172913144](https://github.com/tModLoader/tModLoader/assets/141161448/9ce07452-bfa7-4733-a742-e5871e159cc8)
![image](https://github.com/tModLoader/tModLoader/assets/141161448/5605d4e9-4b3f-43bc-b9e4-b56e6536856a)
![image](https://github.com/tModLoader/tModLoader/assets/141161448/0466747f-fde5-4bee-b90b-931ac4623565)

### Expected Behavior

the color supost to be a yellow no blue

### Reproduction frequency

one time i see this problem like 2 moths ago or more but a few days letter was update and patch fix it

**Comment by JavidPack** [comment]
This is an intended easter egg, not a glitch or bug. It is removed in 1.4.4 however.
