### ISSUE TITLE
Add a hook [OnQuitWorld] at ModPlayer

### ISSUE THREAD

**Issue by ReishyouSose** [bluemagic123/tModLoader#3687]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

There is an [OnEnterWorld] hook in the ModPlayer class, why not add one when saving and exiting?
I checked the source code and finally used [On_WorldGen.SaveAndQuit] to achieve my goal, Maybe I didn't find the right hook.
I want to close the opened Mod UI window in a suitable place, which is not suitable in [OnEnterWorld], it will stay there for a short while because it is loading.

### What does this proposal attempt to solve or improve?

Let Modder do some operations when the player exits the world without using On or IL

**Comment by direwolf420** [comment]
The hook you are looking for exists here: <https://docs.tmodloader.net/docs/stable/class_mod_system.html>, PreSaveAndQuit

**Comment by ReishyouSose** [comment]
OKKK
