### ISSUE TITLE
PrefixDefinition does not support modded prefixes

### ISSUE THREAD

**Issue by Jacklz** [bluemagic123/tModLoader#3690]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When looping through PrefixLoader, if you attempt to create a new PrefixDefinition that is of type 85 or higher (modded) the game will freeze and need to be force closed.

### Log File

The following error is spammed in the log: [Main Thread/ERROR] [Terraria]: System.Collections.Generic.KeyNotFoundException: The given key '85' was not present in the dictionary.

### Steps to reproduce

Such an issue can be created by creating a loop like this:

![Capture](https://github.com/tModLoader/tModLoader/assets/5264573/cffa4d12-7ba5-4b00-8b83-da7fb87749c6)

### Expected Behavior

Creating a PrefixDefinition should work fine with modded prefixes

### Actual Behavior

Trying to create a PrefixDefinition of a modded prefix will fail and cause the game to need to be force closed

### Reproduction frequency

100%

### Additional Information

Prefix Definitions are also not supported in ModConfig

**Comment by JavidPack** [comment]
We'll need to check on 1.4.4-preview, the recent fixes for PrefixDefinition will be in 1.4.4-preview, they are not yet in stable: https://github.com/tModLoader/tModLoader/commit/c6afafcf9f803292d5c7a8e63ac88d5404f74327

Currently there is no 1.4.4-preview branch, so we'll need to wait or manually download the latest 2023.07 build to test (https://github.com/tModLoader/tModLoader/releases)

**Comment by JavidPack** [comment]
Ok, preview-v2023.07 is now up, please test there and make sure it's all working as expected.

**Comment by Jacklz** [comment]
will do! ill report back here once ive tested

**Comment by Jacklz** [comment]
The issue appears to be fixed!
