### ISSUE TITLE
Able to summon multiple bosses at the same time

### ISSUE THREAD

**Issue by NotJeb** [bluemagic123/tModLoader#3693]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am unsure exactly what things this applies to, or what mods could be causing it if it's to do with specific mods, but I can summon multiple bosses at the same time by alternating between my weapon slot and my boss summon spot with hotkeys while spamming click. The video contains an example of it happening.

https://github.com/tModLoader/tModLoader/assets/38151698/83e22b60-567e-475a-857d-506c21900e32

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12266946/client.log)

### Steps to reproduce

Use the most recent version of TMod Loader
Use the mods: Calamity, Alchemist NPC Lite, Boss Checklist, Magic Storage, Recipe Browser.
Open up a multiplayer server(Was done Locally), and have two players(including yourself)
Use the Flawless Hypothermia and Desert medallion
Alternate between the two slots with hotkeys, spamming click as you do so(I used butterfly click)
Every so often, mutliple Desert scourges will spawn.

### Expected Behavior

Spawn one desert scourge when on the Desert medallion slot(assuming that there are none alive), and attack with the Flawless Hypothermia when in that slot.

### Actual Behavior

It is spawning multiple desert scourges and also attacking with the weapon

### Reproduction frequency

I haven't tested it much, but it seems to happen every couple of spawns.

### Additional Information

At the time, I was post devourer of gods, in a hallowed desert.

**Comment by direwolf420** [comment]
Test this with vanilla summon items, otherwise this is just a mod specific issue

**Comment by JavidPack** [comment]
Did you test with vanilla summons yet NotJeb?

**Comment by NotJeb** [comment]
No, sorry. I may test it later but I'm not sure if I can be bothered to do more than submit the issue. Sorry if I'm wasting anyone's time.
