### ISSUE TITLE
World crashing when using cheat sheet's paint feature on a block with a tree

### ISSUE THREAD

**Issue by RageTHD** [bluemagic123/tModLoader#3694]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Using cheat sheet's paint feature on a block with a tree crashes the world forcing you to close the game.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12267058/client.log)

### Steps to reproduce

1. Have Cheat Sheet and Terraria Overhaul enabled
2. Use Cheat Sheet's paint feature to eye drop some blocks to paint with
3. Paint on a block with a tree on it

### Expected Behavior

Blocks gets "painted" and tree destroys itself because it's not on a block that can grow on.

### Actual Behavior

The moment you "paint" over the block world crashes booting you out to the menu while the world tries to make a backup and sometime it changes the game window resolution

### Reproduction frequency

Every time when I "paint" over the block with a tree

**Comment by Mirsario** [comment]
I've accidentally sent Rage the wrong issues/new link, my bad.
