### ISSUE TITLE
Self-inflicted damage by explosives scales with difficulty

### ISSUE THREAD

**Issue by filiplohynsky** [bluemagic123/tModLoader#3695]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### Description

For example, when I get hit by my own dynamite on master mode, I will get hit for 700 damage. The same for normal bomb and grenade.

**Comment by Setnour6** [comment]
I can confirm this.
In vanilla, the damage is the same no matter what difficulty I set it to in Journey Mode (125).
In tModLoader, the damage is different, dealing the same damage in Journey Mode (125), but Journey-Master Mode makes the dynamite deal around 750 damage when it should still be 125 damage.

**Comment by JavidPack** [comment]
Duplicate of #3666 , we'll be tracking this over there, but I'll leave this open since others might search for specific words here.
