### ISSUE TITLE
When in a world the screen fully is black without any UI elements (only when tabbing out it appears back)

### ISSUE THREAD

**Issue by night2000000** [bluemagic123/tModLoader#3705]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Well it's a bug i've been experiencing right now and it just is a bug making a black screen without any ui elements and can move. When i tab out i see the game but when i tab back in i don't.
![Tmodissue](https://github.com/tModLoader/tModLoader/assets/43761256/f9f92dfb-a44b-440e-8a32-945838fb8939)

### Log File

![Tmodissue](https://github.com/tModLoader/tModLoader/assets/43761256/14f997dd-d5e2-43d6-be1b-08e93f1bdec7)

### Steps to reproduce

1.make or select a character
2.make a world or join a world
3.well the thing happends

### Expected Behavior

well not a black screen

### Actual Behavior

a black screen

### Reproduction frequency

well everytime i join a world

**Comment by JavidPack** [comment]
We need the actual client.log file, you skipped that. Also make sure that you have 0 mods enabled.

**Comment by night2000000** [comment]
I disabled all the mods and now it's fixed maybe a mod was causing it thanks tho
