### ISSUE TITLE
guard stack error

### ISSUE THREAD

**Issue by themansetty** [bluemagic123/tModLoader#3709]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

im doing a playthrough with calamity and thorium with quality of life mods (veinminer and magic storage) everything was fine until i killed skeletron then my game crashed with a error code of "a new guard page for the stack could not be created" please help

### Steps to reproduce

1.play thorium calamity and amulet of  many minions with the quality of life mods
2.kill skeletrom
3.error

### Expected Behavior

i dont think the game should crash

### Actual Behavior

game crashes

### Reproduction frequency

it happends every time i load my map

**Comment by Solxanich** [comment]
Closed as a bug with Calamity.
Saw something about you have to mine the looted abyss chests as somehow you looted them before supposed to
