### ISSUE TITLE
World keeps crashing on Skeletron kill after opening Ancient Treasure Chest

### ISSUE THREAD

**Issue by Ellelel** [bluemagic123/tModLoader#3712]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In my playthrough I killed skeletron with Lionfish and 2-10 seconds after the game crashed.

I believe if you open Abyss chests before killing Skeletron, the game breaks when it tries to "unlock" them?
Tried with 3 separate worlds and bug was possible to recreate.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12302007/client.log)

### Steps to reproduce

1. Make new world
2. Find Abyss
3. Open Ancient treasure chest
4. Find dungeon
5. Kill Skeletron
6. Wait for crash in less than 30 seconds

### Expected Behavior

Chests should not be available to be unlocked before skeletron? Or atleast not crash if they are opened.

### Actual Behavior

Chests are unlockable at any time in game but it will crash after skeletron

### Reproduction frequency

I recreated 3 times in same world and made 2 new worlds to test it also.
Tried also saving straight after defeating Skeletron and loading back in but it keeps crashing after 2 seconds.

**Comment by Solxanich** [comment]
Closed as a bug with Calamity.
Saw something about you have to mine the looted abyss chests as somehow you looted them before supposed to
