### ISSUE TITLE
Missing Dependencies are Not Shown, Despite Message

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3716]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I launch the game, I am told that some dependencies are missing. However, none are listed.
It might be because of the latest commits present in 1.4.4 stable. (link: [1.4.4 commits link](https://github.com/tModLoader/tModLoader/commits/1.4.4))
![image](https://github.com/tModLoader/tModLoader/assets/70764728/b7d2025e-6f38-4525-9447-7c0c8121f04b)

After I click on "install dependencies", I get to the loading part but nothing loads and is stuck.
![image](https://github.com/tModLoader/tModLoader/assets/70764728/6b81cfaa-1e1a-4d83-8ef6-a62396b1b077)

I closed the game after by pressing the big red X button on the top right corner.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12321120/client.log)

### Steps to reproduce

1. Open your game
2. You get the message
3. Click "Install Dependencies"
4. Softlock on loading, you have to close the game

### Expected Behavior

The game should not display the missing dependencies message

### Actual Behavior

The game displays the missing dependencies message

### Reproduction frequency

Once, and that's it.

**Comment by JavidPack** [comment]
Fixed in https://github.com/tModLoader/tModLoader/commit/7b342144cd09c088c99a954bc68da45c81864035
