### ISSUE TITLE
tModLoader 1.4 Load failed No Backup found Cannot enter World

### ISSUE THREAD

**Issue by leZZox** [bluemagic123/tModLoader#3719]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I have a World were I played a few hours, and now when i try to join it says "Load failed No Backup Found". It is only this World and every other one works fine
![Screenshot 2023-08-12 103711](https://github.com/tModLoader/tModLoader/assets/142084121/6c8d12dc-fd1f-4ad1-bd52-a1762a24c37b)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12326987/client.log)

### Steps to reproduce

1.) Try entering World
2.) "Load failed! No backup found."

### Expected Behavior

Normally I would be able to play on my World

### Reproduction frequency

Always

### Additional Information

Mod List:
Boss Checklist
Fargos Mutant Mod
Can I Shimmer This?
Magic Storage
AlchemistNPC Lite
Start with Base
Fargos Best of Both Worlds
Auto Trash
Bags
Recipe Browser
absoluteAquarian Utilities
Vanilla Calamity Mod Music
Calamity Mod Music
Calamity Mod
Wich Mod is this From?
Angler Shop 
Boss Cursor
Ore Excavator
Auto Reforge 
Better Zoom
Lights and Shadow
![Screenshot 2023-08-12 105046](https://github.com/tModLoader/tModLoader/assets/142084121/ed142532-1f2d-43fc-ab2b-696ef8756ca6)
![Screenshot 2023-08-12 105100](https://github.com/tModLoader/tModLoader/assets/142084121/a32b8489-f533-416e-9579-c5da04d576ae)
![Screenshot 2023-08-12 105111](https://github.com/tModLoader/tModLoader/assets/142084121/8a2bdf85-e1f1-4e7c-923c-0141c67a2135)
![Screenshot 2023-08-12 105147](https://github.com/tModLoader/tModLoader/assets/142084121/39fb3f78-5ec7-4875-bee9-2c5867be9d34)
![Screenshot 2023-08-12 105200](https://github.com/tModLoader/tModLoader/assets/142084121/23eff70a-3784-468b-b9f6-96cce10da6fa)

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
