### ISSUE TITLE
Item duplicating when pressing autosort

### ISSUE THREAD

**Issue by Neudron** [bluemagic123/tModLoader#3720]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Items getting dupped when pressing autosort near a chest with the same item.
![image](https://github.com/tModLoader/tModLoader/assets/87911761/62ef41e4-ed6c-4b2b-8ab1-9d1efef9d69a)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12328265/client.log)

### Steps to reproduce

Put 1 item inside of a chest, ej: Diamond
Get another diamond
Press the autosort module 
Item should go to the chest without lossing the one in your inventory.

### Expected Behavior

Item should go to the chest and removing the one from the inventory

### Actual Behavior

The item is going into the chest without removing the one from the inventory

### Reproduction frequency

Almost every time.

### Additional Information

Windows 10 22h2

ONLY TESTED ON SERVER.

**Comment by absoluteAquarian** [comment]
This is a bug from Magic Storage.  It will be fixed when v0.6.0.3 of that mod releases
