### ISSUE TITLE
Typing doesn't trigger ModKeybind when the player opens the chat

### ISSUE THREAD

**Issue by ReishyouSose** [bluemagic123/tModLoader#3729]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I registered a ModKeybind for opening the UI
but it also trigger when I type chat in game

### What does this proposal attempt to solve or improve?

can Improve player experience

### Which (other) solutions should be considered?

Although the modder can make their own judgment of "whether to open the chat window", but I think this is not good

**Comment by JavidPack** [comment]
I tested with some mods and hotkeys are correctly not triggering while typing in chat. 

Are you suggesting that they should be able to trigger? Or are you running into an issue where they are triggering?

If this is just an issue with your keybind, I'm guessing you aren't using ModPlayer.ProcessTriggers correctly.

**Comment by ReishyouSose** [comment]
Er, yes, I didn't write in ModPlayer.ProcessTriggers，no problem now
