### ISSUE TITLE
My game will not update to 1.4.4

### ISSUE THREAD

**Issue by superkailan** [bluemagic123/tModLoader#3735]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![image](https://github.com/tModLoader/tModLoader/assets/142584206/b859dac9-af5b-4f53-812c-0109cd2415df)
there is no button for 1.4.4

### Expected Behavior

the game should have an update button in betas or normal steam

### Actual Behavior

No way to update

### Reproduction frequency

100%

### Additional Information

i used the 1.4.4 beta but switch back to 1.4.3 as there werent many mods

**Comment by direwolf420** [comment]
![Screenshot_4](https://github.com/tModLoader/tModLoader/assets/15894498/202563ff-6536-4a02-82fb-403db03aaa21)

**Comment by superkailan** [comment]
> omg tysm im so fucking stupid
