### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by Maksikinchik** [bluemagic123/tModLoader#3736]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I've downloaded the game, Started, And... Loading screen with sunflower, Waiting 1 minute, 5, 10 Minutes, Going to interent to check what to do, Tried all methods, Nothing works, Still black screen with sunflower, What to do?

**Comment by JavidPack** [comment]
You skipped posting the log files, please do that.
