### ISSUE TITLE
Vanilla "UseMana" tooltip does not account for ModifyManaCost hooks

### ISSUE THREAD

**Issue by stormytuna** [bluemagic123/tModLoader#3739]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Currently, if a modded item has its mana cost changed through one of the `ModifyManaCost` hooks, that change is not reflected in its tooltip by default. Though this is easily fixable with a few lines in `ModifyTooltips`, I believe it may be an oversight in tML

The fix I'm proposing, is just slightly changing how the mana cost tooltip is created. Currently, it checks the item has mana and isn't space gun + meteor armour:
```cs
if (item.mana > 0 && (item.type != 127 || !player[myPlayer].spaceGun)) {
    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", (int)((float)item.mana * player[myPlayer].manaCost));
    toolTipNames[numLines] = "UseMana";
    numLines++;
}
```

Vanilla sets a precedent here - items that normally cost mana, but currently cost 0 mana due to some other effect do not have the `UseMana` tooltip displayed. I think we should follow it, doing a similar check:
```cs
int manaCost = player[myPlayer].GetManaCost(item);
if (manaCost > 0) {
    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", manaCost);
    toolTipNames[numLines] = "UseMana";
    numLines++;
}
```

### What does this proposal attempt to solve or improve?

It better conveys the true mana cost of an item to the player

### Which (other) solutions should be considered?

If we don't want the line to be removed when mana cost is zero, we could just inline the `GetManaCost` call
```cs
if (item.mana > 0 && (item.type != 127 || !player[myPlayer].spaceGun)) {
    /*
    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", (int)((float)item.mana * player[myPlayer].manaCost));
    */
    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", player[myPlayer].GetManaCost(item)));
    toolTipNames[numLines] = "UseMana";
    numLines++;
}
```

**Comment by JavidPack** [comment]
Hm, space gun is a well known effect, but with modded effects reducing mana costs in a variety of ways, I'm wondering if not showing the mana cost when reduced to 0 would be interpreted as an error by users rather than a feature. 

This is certainly useful to implement, but wait for another opinion before making the PR I guess. If you want to bring this up on the Collaborators channel in the Discord and quickly gauge what seems most appropriate, that would probably be the best way to know which approach makes sense to users.

**Comment by stormytuna** [comment]
Great point, though I dont seem to have access to the collaborators channel. My username on discord is the same as here, `stormytuna` if you or another admin to grant me access to it
