### ISSUE TITLE
Mod Hairs Do Not Sync in Multiplayer

### ISSUE THREAD

**Issue by Rijam** [bluemagic123/tModLoader#3744]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Just a simple issue that Mod Hairs don't sync in multiplayer, causing it to look like the default hair for other players.

Here are two images. The player with the Mod Hair is on the left.
![ModHairNoSync1](https://github.com/tModLoader/tModLoader/assets/11262234/b4cee2c5-649a-42bf-b806-76b0efa65714)
![ModHairNoSync2](https://github.com/tModLoader/tModLoader/assets/11262234/918f3be3-f1c3-49e9-956e-a007b3860db6)

### Log File

N/A

### Steps to reproduce

1. "Equip" a hairstyle that was added by a mod using ModHair.
2. Have other players view your default hair.

### Expected Behavior

The hair should sync to all players, so all players see the Mod Hair.

### Actual Behavior

Only the player with the Mod Hair sees the Mod Hair. Other players see the default hairstyle.

### Reproduction frequency

Always.

### Additional Information

I didn't test modded hair dyes, but it might be worth looking into that too.

**Comment by JavidPack** [comment]
Can you check in Preview? This was fixed in https://github.com/tModLoader/tModLoader/commit/14d1ad03a2977dc388ff0be0c6cd3388fe7ece43, but that is only on Preview at this time.

**Comment by Rijam** [comment]
Confirmed fixed in Preview (v2023.7)
