### ISSUE TITLE
Add pagination to the Workshop > Download Mods section

### ISSUE THREAD

**Issue by cesarblender** [bluemagic123/tModLoader#3753]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Rewrite Workshop > Download Mods section to add pagination. The problem is, that section fetch all mods available on the workshop, and it is so slow to charge for the first time and is so laggy, my FPS down on my computer.

### What does this proposal attempt to solve or improve?

This new feature will fix the slow time to charge the workshop section

**Comment by Solxanich** [comment]
This is already implemented in current 2023.07 preview under #3346 .
It will be available on stable branches during yhe next release.

Thanks for your patience
