### ISSUE TITLE
ModPlayer OnPickup hook

### ISSUE THREAD

**Issue by stormytuna** [bluemagic123/tModLoader#3754]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

An equivalent for `Mod/GlobalItem` `OnPickup` on `ModPlayer` 

### What does this proposal attempt to solve or improve?

It would be less annoying to do something on item pickup that relies on stuff in the modplayer

The use case I have is similar to the nebula item boosters - all the code related to the effects are in a `ModPlayer` and I'd prefer to keep triggering the effect in the same class, but cannot

### Which (other) solutions should be considered?

Name could be changed, `OnPickupItem` or `OnItemPickup` might make more sense

**Comment by BasicallyIAmFox** [comment]
`OnPickup` methods **do** provide `Player` instance though? You can just provide extension method if you want to make it less annoying

**Comment by Chicken-Bones** [comment]
Seems reasonable.
