### ISSUE TITLE
Unloaded tiles with some TileFrameY values that aren't multiple of 18 cause render exception

### ISSUE THREAD

**Issue by Ved-s** [bluemagic123/tModLoader#3758]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

If tile with TileFrameY that isn't a multiple of 18 gets unloaded, rendering its "Unloaded tile" causes exceptions with some TileFrameY values
(checked some values up to 80, none of them breaks)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12434744/client.log)

### Steps to reproduce

Minimal mod:
```cs
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace BuggyMod
{
	public class BuggyMod : Mod
	{
	}

	public class TestItem : ModItem 
	{
		public override string Texture => $"Terraria/Images/Item_{ItemID.StoneBlock}";

        	public override void SetDefaults()
        	{
			Item.DefaultToPlaceableTile(ModContent.TileType<TestTile>());
        	}
    	}

	public class TestTile : ModTile 
	{
        	public override string Texture => $"Terraria/Images/MagicPixel";

        	public override void SetStaticDefaults()
        	{
        	    Main.tileFrameImportant[Type] = true;
        	}

        	public override bool TileFrame(int i, int j, ref bool resetFrame, ref bool noBreak)
        	{
            		var tile = Main.tile[i, j];
            		tile.TileFrameY = 88; // Normally would be set by tree generator, multiple of 22
           		 return false;
        	}
    	}
}
```

1. Compile and run the mod
2. Enter a world, place TestTile
3. Exit the world, save and quit
4. Unload the mod (force reload or full restart)
5. Load into the world
6. Rendering tile's "Unloaded tile" causes exceptions

### Expected Behavior

No exceptions should happen

### Actual Behavior

Exceptions gets thrown while calculating tile draw positions

### Reproduction frequency

all the time

**Comment by JavidPack** [comment]
Finally found the buggy logic, thanks for making the report.
