### ISSUE TITLE
GOG Version Not Launching Via STEAM

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3764]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I have terraria on GOG, and i download the game via heroic and add to steam.
Works without any issue.

Then i want to use tModLoader.
So it get it install it via NESTED option (was recommended for GOG)

1. Issue launching via `start-tModLoader.sh`
when i do this i get error `line 6: PPID: readonly variable`
i wait.
still nothing further and nothing happens

so i see what is is trying to do, and launch `ScriptCaller.sh` directly
it works! downloads .NET launches to mod loader, i can download and play!
END OF STORY!    ...or is it?

so it try to add `ScriptCaller.sh` to Steam

2. Issue `System.Exception` because of `SetAppId`
![grafik](https://github.com/tModLoader/tModLoader/assets/85245131/e48ec578-56b0-47da-9b0d-539c3d8dc8dd)
this only happens when starting via STEAM

It tries to set the AppID for tModLoader for achievments, etc...
which only works on the STEAM version

WHERE IT ALREADY DETECTED IT IS RUNNING THE GOG VERSION WHY IS IT DOING THIS?!?

and i need it added to STEAM for it to work in GAMING-MODE

### Log File

i cant find the `~/.local/share/Terraria/ModLoader/Logs/` or `$XDG_DATA_HOME/Terraria/ModLoader/Logs/` (both dont contain folder called `Logs`) but i can share the ones in the tmodloader installed folder

Forget THAT, GITHUB IS ERRORING ME, so i will upload it as the first comment...
this is so stupid...

### Steps to reproduce

1. add GOG tmodloader to steam
2. ded

### Expected Behavior

Work

### Actual Behavior

Crash

### Reproduction frequency

100%

### Additional Information

Searched the whole internet, couldnt find anything...

**Comment by ghost** [comment]
its still not letting me upload logs, i come back later and upload on GOOGLE-DRIVE

**Comment by ghost** [comment]
~~https://drive.google.com/file/d/1DNxI-gNVw8RPOpNM3tz6Q4zWe7F1zKfN/view?usp=sharing~~
oops, wrong logs
https://drive.google.com/file/d/1L72pGeLsE6DOclVBfF-YgiwLE9aa_mEs/view?usp=sharing

**Comment by ghost** [comment]
tried on my main linux PC too, still crashes when trying to start via steam (both Issues are there (readonly when start-tModLoader, and SteamAppId))

**Comment by Chicken-Bones** [comment]
This is a new one for us. A GoG linux user trying to run tML with steam client overlay, without owning it on steam. I just have to say this isn't supported at this time. Your use case is too unique for us to prioritise. My apologies for the inconvenience.

**Comment by ghost** [comment]
ahh ok, i thought this was more common, since its not just for the steam overlay but so i can use it on steam decks GAMING mode, which is more optimized, you could try a quick fix by disabling the `SetAppId` function when it detected a GOG version

(i can't test the change since i only have Linux, and can't compile tML because of that)

**Comment by Solxanich** [comment]
Fixed in 2023.8

**Comment by ghost** [comment]
Nice :+1:
(haven't tested yet, but i assume it works!)
