### ISSUE TITLE
Hotbar swap buffering is different from Vanilla due to use time changes

### ISSUE THREAD

**Issue by jjohnsnaill** [bluemagic123/tModLoader#3775]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In vanilla, you can press one of the hotbar keys while already using an item to buffer a swap when you stop using it. Funnily enough, this works because of the longstanding bug where all items are a frame slower.

But because tML fixes that bug, you now have to manually stop using the item for at least a frame for the swap to go through.

### Steps to reproduce

Hold down the use key, then press one of the hotbar keys while the item is in use

### Expected Behavior

Item swaps right when it's done being used

### Actual Behavior

Item doesn't swap until you manually let go of the use key

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Related to #2478
