### ISSUE TITLE
Early crash

### ISSUE THREAD

**Issue by stmblbmbl** [bluemagic123/tModLoader#3780]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

![image](https://github.com/tModLoader/tModLoader/assets/139252592/1d614ecd-3685-4f85-a9d2-13a957146996)
Upon opening 1.4.4, it gets stuck at this screen then crashes. 
This is not there in 1.4.3, but it is in the unstable 1.4.4 mode as well

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12490780/client.log)

### Steps to reproduce

dont know how it happened, just started one day

### Expected Behavior

opening fully

### Actual Behavior

crashing early

### Reproduction frequency

100%

**Comment by fyrestrike4** [comment]
I have the same issue. It started today and nothing on the wiki helped.

**Comment by Chicken-Bones** [comment]
Please come to the discord and make a post in the support-forum.
