### ISSUE TITLE
ModAccessorySlot doubling its effects

### ISSUE THREAD

**Issue by Zoryn4163** [bluemagic123/tModLoader#3785]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When equipping any (vanilla?) accessory to an additional ModAccessorySlot, its effects are being doubled.
Vanilla slot: [https://i.imgur.com/jJwz5qp.png](https://i.imgur.com/jJwz5qp.png)
Modded slot: [https://i.imgur.com/npVndtX.png](https://i.imgur.com/npVndtX.png)

Code is as barebones as it gets:
`public class TestSlot : ModAccessorySlot
{
    
}`

### Log File

client log file: [https://pastebin.com/9J5JW4cH](https://pastebin.com/9J5JW4cH)

### Steps to reproduce

Have a mod implement the ModAccessorySlot
Place an accessory in the newly added slot
Notice its effects are doubled

### Expected Behavior

The accessory effects should not be doubled

### Actual Behavior

The accessory effects are being doubled

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
This is a bug with that `MoreAccessories` mod you have enabled. It has a `public class MoreAccessoriesPlayer : ModAccessorySlotPlayer` in it, causing the effects to be doubled. I'll mention this to them in their steam comments section.

**Comment by Zoryn4163** [comment]
That's my mod lol. I wasn't aware that could cause it, I will try changing that, thanks.
