### ISSUE TITLE
Armor Pieces and Custom Modifiers

### ISSUE THREAD

**Issue by tieeeeen1994** [bluemagic123/tModLoader#3788]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

There might be something wrong with PrefixCategory.Custom and ChoosePrefix.

I have a GlobalItem.ChoosePrefix that returns a mod prefix.

When I reforge in goblin tinkerer, it will be reforged as this, but subsequent reforges will make it prefixless, unless I remove said item from tinkerer slot and put it back, then it will work again (subsequent reforges from this will still result in a prefixless item, sadly).

Refer to the following code that I have:
1. https://hst.sh/alezabiqat.csharp - GlobalItem
2. https://hst.sh/oyejafezup.csharp - ModPrefix (Child)
3. https://hst.sh/ejevewesax.csharp - ModPrefix (Parent)

The following prefix affects Armor pieces only. However...

https://cdn.discordapp.com/attachments/534215632795729922/1148509920015163393/image.png

Once I changed this part of code, the same behavior stated above is still happening! There's no reason for ChoosePrefix to turn my item into a prefixless version.

With additional findings about my problem, this does not happen in weapons. Reforging is correctly applied, and succeeding reforges still correctly apply the prefixes as normal.
However... if the item is an armor piece, the behaviour i reported will show.
Accessories also work properly. Only armor (which is not supposed to have any modifiers in vanilla) will have the said bug as reported.

Here is a video that displays this behaviour.

https://cdn.discordapp.com/attachments/534215632795729922/1148510478654517258/Screen_Recording_2023-09-05_at_2.49.55_PM.mov

### Log File

I can't find the logs for some reason...

### Steps to reproduce

Install Hero's Mod.

Spawn any armor.

Reforge with Goblin Tinkerer.

Reforged item will have modifier.

Reforge again.

Modifier disappears.

Reforging more will make the item have no modifiers still.

Remove item from reforge slot.

Put it back to reforge slot.

Reforge.

Item will have modifier.

Reforge again.

Item will have no more modifier.

### Expected Behavior

The modifier should keep rerolling depending on what is coded in ChoosePrefix.

### Actual Behavior

Modifier disappears on 2nd reforge or more, unless removed and placed back again in reforge slot.

### Reproduction frequency

Always.

**Comment by tieeeeen1994** [comment]
Is it possible to do a follow-up on this issue?

**Comment by tieeeeen1994** [comment]
Hello. I am still waiting for this issue. The issue still persists as the video provided. I can provide the video if the issue is looked onto. The media keeps expiring.

**Comment by tieeeeen1994** [comment]
I would like to follow up on this issue. The armor pieces cannot properly be added a prefix, but if you use the same modded prefix logic to weapons, the reforging works as expected. Details have more information about the behavior.

**Comment by tieeeeen1994** [comment]
Following up on this issue.

**Comment by tieeeeen1994** [comment]
Follow up. I shan't give up!

**Comment by tieeeeen1994** [comment]
Follow-up!

**Comment by JavidPack** [comment]
It seems to be working for me. I couldn't use your code to replicate since it is missing a lot, so I had to replicate it myself, so there might be some differences due to methods you omitted from the code you posted. You didn't mention how you forced the game to even allow prefixes on armor in the first place, so that might also be related.

https://github.com/tModLoader/tModLoader/assets/4522492/9ddb72fd-0e88-47ae-b706-64b2ee64d282

**Comment by tieeeeen1994** [comment]
Hello jopo.

Wow. That then looks like a code error on my side.

Do you want to get the my code checked then? I really am lost as to what my error is.

Here is the repository of the mod that I am having trouble with: https://github.com/tieeeeen1994/tModLoader-ArmorModifiers/tree/master/Modifiers

The global item code is here for applying the prefixes: 
https://github.com/tieeeeen1994/tModLoader-ArmorModifiers/blob/master/GlobalItems/GlobalArmor.cs

This above code worked properly before in 1.4.3, and I somehow can't make it work properly in 1.4.4.

Thanks for checking out the issue. I really appreciate this.

Edit: For additional info, I had to also do this in another mod and I got the same results of the described bug. This is most likely an implementation problem in my end.

**Comment by tieeeeen1994** [comment]
Hello again. I can provide a video of what's happening (recorded using the changes I currently have.)

https://streamable.com/kx67ip

> You didn't mention how you forced the game to even allow prefixes on armor in the first place, so that might also be related.

How did you do it?

Mine's on ModPlayer.PostUpdate:
```cs
if (CheckArmorValidity(Main.HoverItem)) Main.HoverItem.accessory = Main.InReforgeMenu;
if (CheckArmorValidity(Main.mouseItem)) Main.mouseItem.accessory = Main.InReforgeMenu;
```

**Comment by tieeeeen1994** [comment]
Thank you so much for pointing that out for me. I have refactored the code and used a hook instead. Thankfully, vanilla has an `Item.CanHavePrefixes` that I can use. I implemented it like so:

```cs
private bool Item_CanHavePrefixes(On_Item.orig_CanHavePrefixes orig, Item self)
{
    return orig(self) || IsArmorPiece(self);
}
```

Cheers!
