### ISSUE TITLE
Projectile problem

### ISSUE THREAD

**Issue by ImPumpkin** [bluemagic123/tModLoader#38]
My projectile does not hit NPCs, so i cant use:
- OnHitNPC
- ModifyHitNPC
- Projectile.NewProjectile (can i use this in projectiles code?)
It just goes through the NPC and nothing happens.

Also...
I cant modify the damage of the projectile (when it eventually hit by using the damage from "the gun")

**Comment by JavidPack** [comment]
This doesn't sound like a tModLoader bug, but rather a bug in your code. Asking for help debuggin that sort of thing is more appropriate in the Terraria Community Forum or the Discord channel. Off the top of my head, I'm guessing you aren't setting damage, friendly, or hostile variables correctly.

**Comment by JavidPack** [comment]
With no response, we have to assume this is a programming error on the modders part.
