### ISSUE TITLE
[Feature Proposal] Add warning when publishing to preview if latest was on stable

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3806]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

An indicator that the modder is currently publishing their mod to the preview branch, even if it might not be intended (because their mod is only available on stable and they want to keep it that way). This can notably happen if they are on preview, work on porting their mod, then preview rollover happens and they are still on preview but it'll be the next month's one. If it just so happens that the mod can still compile, it will be published to preview, with no way of reaching current stable playerbase.

Implementation wise it would be best to just make it some mouseover (in red color). An intermediate UI window (popup) would be possible aswell but requires more work and is more annoying to handle.

Disclaimer: It should not _prevent_ the modder from publishing, just warn them.

### What does this proposal attempt to solve or improve?

Accidental publishing to the wrong tml version, potentially leaving players without a playable version of a mod for a month.

**Comment by JavidPack** [comment]
I believe this isn't an issue anymore with the new preview and mod loading changes. Can you confirm?

**Comment by direwolf420** [comment]
In what sense? Will the game not let me accidently publish on preview?

**Comment by JavidPack** [comment]
Well, modders won't automatically roll over to newer previews anymore and stable users will load the highest version mod they can even if it was originally published on preview (and preview uploads must be a higher version as well, that is enforced). I'm not seeing a way a user could be left without a mod to load as it is.

**Comment by direwolf420** [comment]
Fair, will close then
