### ISSUE TITLE
world generation tuck and crashing

### ISSUE THREAD

**Issue by brianzooming** [bluemagic123/tModLoader#3812]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when generating worlds with the preview mod and no any other mod on it only generates mud and dungeon on the left side after generating a world and canceling. Even with the preview mod when the error occurs i cannot exit the game and is forced to close it on steam. the multiplayer one was just discovered. the first three images are about world gen and the last is the message that appears after multiplayer crash

<img width="1280" alt="Screenshot (108)" src="https://github.com/tModLoader/tModLoader/assets/145192949/4bcc4f2c-cd49-4b26-a404-cd3412455884">
<img width="1280" alt="Screenshot (109)" src="https://github.com/tModLoader/tModLoader/assets/145192949/05589bc1-3da6-46bb-aa09-7876ba6f1491">
<img width="1280" alt="Screenshot (110)" src="https://github.com/tModLoader/tModLoader/assets/145192949/c90bc6af-b652-4bb8-b19d-7d69f930be97">
<img width="686" alt="Screenshot (111)" src="https://github.com/tModLoader/tModLoader/assets/145192949/0bae312d-d301-41e1-8dc0-cb55f2c51be4">

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12640272/client.log)

### Steps to reproduce

1. generate a world and leave using the preview mod (i use that to get a good world to play on)(the first world is normal)
2. generate another world
3. stuck after world only generating mud and dungeon (world gen stopped)

### Expected Behavior

it should generate the world normally

### Actual Behavior

it is not gnerating a correct world

### Reproduction frequency

always

**Comment by brianzooming** [comment]
the multiplayer one has nothing to do with the world generation. i found out about it when i decided to play with my friends cuz i can't generate worlds

**Comment by brianzooming** [comment]
.

**Comment by JavidPack** [comment]
This is an issue with the WorldGenPreviewer mod, not tModLoader itself. It's been mentioned to me on my Discord, but I haven't had time to look into it. You can repost your issue here if you like: https://github.com/JavidPack/WorldGenPreviewer/issues

I'll be closing this issue here since it is not a tModLoader issue.

**Comment by brianzooming** [comment]
but it wtill doesn't work after uninstalling the world gen previewer

**Comment by JavidPack** [comment]
Well, we'd need to see a client.log and the issue you are getting from the time it didn't work with the mod disabled.
