### ISSUE TITLE
 I had a Maine engine crash and I don't know why

### ISSUE THREAD

**Issue by Proeliumm** [bluemagic123/tModLoader#3816]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

One day tmodloader just stopped starting and started giving the main engine error 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12643359/client.log)

**Comment by JavidPack** [comment]
One of your resource packs in incompatible with tModLoader. Disable them all then try to enable in game. https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#multiple-extensions-for-asset
