### ISSUE TITLE
Cant even get net. and I dont know were else to ask.  Literally just made an account for this. never used github before.

### ISSUE THREAD

**Issue by Iamsadpleasework** [bluemagic123/tModLoader#3817]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I would download visual studio. open the launcher. a green loading bar would appear for about a minute. it finishes and asks for permission to change things on my computer. I press ok. nothing happens.

**Comment by Iamsadpleasework** [comment]
Literally just made an account for this. never used github before.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. I suggest coming to the #mod-programming-help channel in our [Discord chat](https://tmodloader.net/discord). People there might have some suggestions and would be better suited for giving live support. 

Issues with installing Visual Studio itself aren't something that we'll be able to solve in a forum like this.

**Comment by Iamsadpleasework** [comment]
thank you for telling me this, but the link doesent work

**Comment by JavidPack** [comment]
Sorry about that, our website seems to be down at the moment, here is an alternate link: http://discord.gg/tmodloader
