### ISSUE TITLE
GlobalNPC.AppliesToEntity does not account for netID

### ISSUE THREAD

**Issue by ThomasThePencil** [bluemagic123/tModLoader#3818]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

`AppliesToEntity` cannot allow you to check against an NPC's `netID`, as it is not set until the end of `NPC.SetDefaults`

yes, I classify this as a bug, because it's a glarin' oversight in the development of a critical core feature of tML
yes, I'm aware this bug has likely existed for as long as `AppliesToEntity` has, and likely longer
no, I don't plan to fix this myself, as I'm not entirely certain how to do so

### Log File

let's not and say we did. this isn't the sort of thing a log file would be useful for

### Steps to reproduce

1. make a GlobalNPC
2. in `AppliesToEntity`, check against `npc.netID == NPCID.Pinky; // or any other negative net ID enemy variant you can think of`
3. load up a world, spawn your NPC, and watch as nothing you just did actually works on it

### Expected Behavior

a `GlobalNPC` should be able to, in `AppliesToEntity`, check against `netID` to specify certain variants of enemies

### Actual Behavior

it doesn't let me. why do I still have to explain what's goin' on twice after >8 years

### Reproduction frequency

103%. margin of error: 3%

**Comment by ThomasThePencil** [comment]
there's a different, less substantial problem at play that I want to get at in a separate issue, actually

**Comment by Chicken-Bones** [comment]
This is high difficulty low benefit. See #3819 for the use-case.
