### ISSUE TITLE
Disabling a mod due to load failure does not disable dependencies

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#3821]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

An issue with our new 'automatically enable dependencies on load' feature. If a dependency gets disabled due to a load failure (`The mod(s) have been automatically disabled`), the dependent remains enabled, causing the dependency to be re-enabled next loop.

This means they can get stuck in a reload loop. The only way out currently is to skip loading mods, and identify the dependencies to disable as well.

### Steps to reproduce

- Have mod B which depends on mod A. 
- Write an exception during loading in mod A.
- Enable B and load the game.

### Expected Behavior

The dependent mods should also be disabled (if the dependency is a strong one, and not a weak one).

### Actual Behavior

The dependency remains enabled, and re-enables the dependent on each load, leaving the user stuck in a loop.

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Fixed in #4112
