### ISSUE TITLE
tModLoader Fatal Error

### ISSUE THREAD

**Issue by rodsmarel** [bluemagic123/tModLoader#3824]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Log File

![image](https://github.com/tModLoader/tModLoader/assets/145592065/87aef8ef-42ce-4e72-8ced-1fb7887209c8)

### Additional Information

Everytime I log in a server or equip the porfane soul artifact the server crashes

**Comment by JavidPack** [comment]
You didn't post client.log. This also looks like a mod specific issue, since ProfanedGuardians is from a mod, so you might be better off contacting the mod author. As a reminder, this issue tracker is for issues with tmodloader itself, not specific mods.
