### ISSUE TITLE
Infernum mod crash on launch

### ISSUE THREAD

**Issue by KAMN1** [bluemagic123/tModLoader#3826]
Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![image](https://github.com/tModLoader/tModLoader/assets/84623626/268260b6-556d-4d92-9fea-be1ffd0066d3)
### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12684377/client.log)

**Comment by JavidPack** [comment]
This is an issue with the InfernumMode mod, not tModLoader. You'll need to report this to the mod creator (on their workshop, discord, or github. whatever they have) and see what they have to say.
