### ISSUE TITLE
Regarding the problem of transmitting parameters for NewProjectile

### ISSUE THREAD

**Issue by ReishyouSose** [bluemagic123/tModLoader#3834]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Change the parameter type of the `ai` array in the `NewProjectile`   from  `int`  to  `int?`
Whenthey are null, no values are assigned to the `Projectile.ai`

### What does this proposal attempt to solve or improve?

The current `NewProjectile` will assign a value to the `ai` array after calling `ModProjectile.SetDefaults(),` so it is impossible to set a universal initial value in `SetDefaults`.
In this way, modders can set the initial value in `SetDefaults` without passing the same parameters in `NewProjectile` everywhere.

**Comment by Antirhinnum** [comment]
You can currently set a universal value using `ModProjectile.OnSpawn()`, which runs after the automatic `ai` assignment.

**Comment by JavidPack** [comment]
We will not be changing the parameters of `NewProjectile` for that, that would be incredibly error prone with the source code we have and will break every mod.

As mentioned, the ai slots are not intended to be set in SetDefaults.
