### ISSUE TITLE
Smart cursor deleting items when using it combined with torches

### ISSUE THREAD

**Issue by blahblahbal** [bluemagic123/tModLoader#3838]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When spamming your smart cursor hotkey with a small amount of torches (say, 5-6) in your inventory while attempting to mine trees using an axe (I used the Picksaw), items in the first 2 slots will be deleted.

### Log File

Not applicable, no errors in log

### Steps to reproduce

Unsure exactly how to write a steps to reproduce for this, but I'll try:
1. Give yourself around 5 or 6 torches, an axe (preferably a fast one, maybe the picksaw), and a weapon to put in slot 2 using a cheat mod, then disable all mods.
2. Load into a world (preferably a new one) and use the axe item while spamming your smart cursor hotkey (to attempt to place torches).
3. Notice how when the torch stack reaches 0, items will be deleted out of your hotbar.

### Expected Behavior

It should not delete your items.

### Actual Behavior

Items are deleted.

### Reproduction frequency

Every time I try it.

### Additional Information

I recorded a video clip of this happening, and uploaded to YT. It's near the end of the video.

[https://www.youtube.com/watch?v=fuxMfAYiuzY](https://www.youtube.com/watch?v=fuxMfAYiuzY)

**Comment by blahblahbal** [comment]
Oh forgot to mention, tested this with 0 mods enabled.

**Comment by JavidPack** [comment]
Video replication:

https://github.com/tModLoader/tModLoader/assets/4522492/5ab2e24c-722e-4543-b281-4861c4c58667
