### ISSUE TITLE
TreeLeaf() isn't required for ModTree

### ISSUE THREAD

**Issue by Lion8cake** [bluemagic123/tModLoader#3842]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

TreeLeaf() isn't required for ModTree despite locking up the game when in the range of the ModTree without TreeLeaf() hook or a TreeLeaf() hook without a return. 

### What does this proposal attempt to solve or improve?

We should make it required to compile and load mods with ModTree, This will clearly show modder's what is wrong with their mod trees and to prevent game freezes for both the mod developer and player. 
ModTrees should print an error when TreeLeaf() is not found inside of said ModTree or has TreeLeaf() without a return.

### Which (other) solutions should be considered?

Making TreeLeaf() optional for modders who have trees that visually dont have leaves although a counter to this is returning null instead of the Treeleaf() hook.

**Comment by Lion8cake** [comment]
This should also extend to the CreateDust() hook as well

**Comment by JavidPack** [comment]
I think since ModTree hasn't required this initially, as far as I know, we should just fix whatever regression is causing the game to lock up.

#3589 might be tangentially related.

**Comment by JavidPack** [comment]
Ok, I did some testing and I'm not noticing the game locking up when `ExampleTree.TreeLeaf` returns -1. Is there anything else that might be a factor here that I'm not testing? I have a few trees on screen, in SinglePlayer.

**Comment by Lion8cake** [comment]
just fully remove the hooks from the mod tree, the game will lock up the same way. In the current stable release this isn't present and trees both wont produce any leaves/produce normal wooden dust if they do not have these hooks

**Comment by JavidPack** [comment]
Are you saying that in stable there is no issue? So are you seeing this error only on preview? By lock up, you mean lock up totally right? I'm still seeing 60 fps on the development branch after removing the method entirely, maybe I need to test specifically on preview?

**Comment by Lion8cake** [comment]
now this extendeds to the Shake() hook as well
if you dont have shake and hit a tree the game freezes

**Comment by Lion8cake** [comment]
> Are you saying that in stable there is no issue? So are you seeing this error only on preview? By lock up, you mean lock up totally right? I'm still seeing 60 fps on the development branch after removing the method entirely, maybe I need to test specifically on preview?

Sorry I didn't initially see this message. 

- Yeah preview does not have this issue and both doesn't print an error or freeze the game like preview does.

- What I ment by lock up is that the player cannot move, open inv, open map, do anything but close the game.

- This does only happen on the preview version on the steam workshop. This might have been fixed on the development branch but im not too sure.

- Yeah removing the hooks (shake(), TreeLeaf(), CreateDust()) causes this to happen too which in the stable version this does not occur and will default to (returning true, having no leafs/gores, default tree wood dusts) respectively.

**Comment by JavidPack** [comment]
K, I believe something fell through the cracks and some changes were made on preview that shouldn't be there. We plan on removing the faulty code for the release tomorrow so we'll want to test this once v2023.08 is live on stable.

**Comment by JavidPack** [comment]
Checked on 2023.09.3.2 stable, seems to all be good.
