### ISSUE TITLE
ModItem.ModifyWeaponDamage() not applying to all frames of a Melee weapon

### ISSUE THREAD

**Issue by ckeyboard** [bluemagic123/tModLoader#3846]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

ModifyWeaponDamage() is not applying calculated damage to the final frames of a Melee weapon.

### Log File

using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace TestDouble.Items
{
	public class TestSword : ModItem
	{
		public int charge = 0;

		public override void SetDefaults()
		{
			Item.damage = 50;
			Item.DamageType = DamageClass.Melee;
			Item.width = 40;
			Item.height = 40;
			Item.useTime = 20;
			Item.useAnimation = 20;
			Item.useStyle = 1;
			Item.knockBack = 6;
			Item.value = 10000;
			Item.rare = 2;
			Item.UseSound = SoundID.Item1;
			Item.autoReuse = true;
		}

		public override void AddRecipes()
		{
			Recipe recipe = CreateRecipe();
			recipe.AddIngredient(ItemID.DirtBlock, 10);
			recipe.AddTile(TileID.WorkBenches);
			recipe.Register();
		}

		public override void ModifyWeaponDamage(Player player, ref StatModifier damage) {
			damage *= charge;
		}

		public override bool CanUseItem(Player player) {
			/* Right-clicking charges the weapon */
			if (player.altFunctionUse == 2) {
				charge += 1;
				return false;
			}
			return true;
		}

		public override bool AltFunctionUse(Player player) {
			return true;
		}

		public override bool? UseItem(Player player) {
			/* Remove charged effect for the next use of this item (not this time around) */
			charge = 0;

			return (player.whoAmI == Main.myPlayer); // && (Main.netMode == NetmodeID.??);
		}

	}
}

### Steps to reproduce

1. Run the above code in a test mod.
    This will allow you to craft a TestSword.
2. Enable CheatSheet so you can make dummies.
3. Open a new world (any world will do)
4. Craft the TestSword.
5. Place a dummy very close to the character.
    We want the sword to strike at it's beginning frames.
6. Swing the TestSword at the dummy.
    Observe the **normal** damage.
7. Tap right-click to 'charge' the test sword.
8. Swing the TestSword at the dummy.
    Observe the increased **charge** damage.
9. Stand further away from the dummy.
    We now want the sword to strike at it's final frames.
10. Tap right-click to 'charge' the test sword.
11. Swing the TestSword at the dummy.
    Observe the charge damage does **not** apply at the final frames.

### Expected Behavior

The calculated charge damage is supposed to apply to all frames of the swing.

### Actual Behavior

The calculated charge damage is only applying to the beginning frames.

### Reproduction frequency

By running the code and following the steps, the issue can be produced reliably. Right-click a few more times if necessary.

### Additional Information

I suspect ModifyWeaponDamage() is being called a 2nd time before UseItem() can finish. This could explain why the damage boost goes away during the final frames.

**Comment by JavidPack** [comment]
Ok, I did some testing and the method is being called, the issue is you aren't using the hooks correctly. How you are using CanUseItem and UseItem is not going to work with the order and how often the methods are actually called. 

What you are trying to do definitely doesn't mesh well with how the game works, but I did find a way to hack it out.

You'd need to somehow remember the charge throughout the swing, I did this with a 2nd variable

```
....
		public int charge = 0;
		public int activeCharge = 0;

....
		public override void ModifyWeaponDamage(Player player, ref StatModifier damage) {
			if(player.itemAnimation > 0)
				damage *= activeCharge;
			else
				damage *= charge;
		}
....
		public override bool? UseItem(Player player) {
			/* Remove charged effect for the next use of this item (not this time around) */
			activeCharge = charge;
			charge = 0;

			return (player.whoAmI == Main.myPlayer); // && (Main.netMode == NetmodeID.??);
		}

```

You can ask in the Discord for more programming help. This isn't a bug, just a misuse of the hooks and opposite of how the hooks are designed to be used.
