### ISSUE TITLE
Auto-select malfunctioning

### ISSUE THREAD

**Issue by Wackydude27** [bluemagic123/tModLoader#3856]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Auto-select isn't maintained after removal of the bound key. I.e. when using auto-select while mining, placing torches, etc., letting go of LeftShift stops the auto select, even whilst maintaining left click.

### Steps to reproduce

1. Hold Auto-select key.
2.  Hold Left click on area in Terraria
3. Release Auto-select key.

### Expected Behavior

Upon letting go of left click, auto-select should be maintained.

### Actual Behavior

Upon letting go of left click, auto-select isn't maintained.

### Reproduction frequency

consistant with latest stability update (10/01/23).

**Comment by TGWeaver** [comment]
I noticed this as well, thought it might be some mod update but after stripping out all mods it does appear to be the new update of TModloader itself. Having to hold shift the entire time while using tools is pretty obnoxious and it breaks from standard Terraria behavior.
There are a number of swap related pulls in the last month that might have led to this, but while I'm not very familiar with the codebase I suspect it might be related to #3804 and potentially some of the issues linked there.

**Comment by JavidPack** [comment]
Thanks for the report. We are aware of the issue and reworking things.

**Comment by Chicken-Bones** [comment]
Fixed in e9753ed960f46c054780132f5ced18595932ebee. Will be released on stable after some mod compatibility testing
