### ISSUE TITLE
A More "Complete" Builder Toggle API

### ISSUE THREAD

**Issue by Cyrillya** [bluemagic123/tModLoader#3857]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Based on an earlier discussion in discord and my suggestions, we should allow mod builder toggles to:
- Customize frame rectangle based on state
- Have custom ordering
- Have custom left click functionality
- Have any right click functionality for that matter
- Play custom sound when being toggled (This can be combined with the custom left/right click functionality mentioned above)
- Allow custom drawing to make cooler vfxs on them

### What does this proposal attempt to solve or improve?

`BlockSwap` and `TorchBiome` toggles in vanilla have custom sound (which plays `SoundID.Unlock` when being toggled) and custom framing based on state. So how can we call it a complete API if we can't reproduce the features that vanilla has?

**Comment by JavidPack** [comment]
Sounds like a plan, if anyone has anything else to mention, please do so whoever gets to this can anticipate it.
