### ISSUE TITLE
v2023.08.3.3 results in an instant crash on launch for MacOS devices

### ISSUE THREAD

**Issue by SnailPerson** [bluemagic123/tModLoader#3862]
### Version

Latest 1.4.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When i try to launch tmodloader (on MacOS), it instantly crashes on launch.
Im 99% certain this has to do with tmodloader v2023.08.3.3, as i played with friends yesterday and everything ran perfectly fine.
When i tried to launch today, well, tmodloader crashed.
I restarted steam, uninstalled tmodloader, restarted computer, that did not work.
I changed beta program to "preview-v2023.08", which did launch & work, although most mods were broken by this preview version.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12809054/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/12809055/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12809057/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/12809058/Natives.log)

### Steps to reproduce

1. Have latest tmodloader version enabled in steam (v2023.08.3.3) - "none" in beta program
2. Lauch game
3. Watch it crash 3 seconds after launch
4. Profit?

### Expected Behavior

The game should launch normally and be playable.

### Actual Behavior

The game crashes in ~3 seconds after launch. Not even the menu screen can show up.

### Reproduction frequency

100% crash rate so far

### Additional Information

help

**Comment by Chicken-Bones** [comment]
Please try verifying your game files in steam.

Please try removing `/gldevice:Vulkan` from your launch args. 

Also, please try preview 2023.09 and provide another `client.log` if it doesn't work.

**Comment by SnailPerson** [comment]
~~Where do i find the launch args and how would i go about removing Vulkan?~~
nvm, found it, removed it.

v2023.8.3.3 can be launched successfully now.
Preview 2023.09 can also be launched without issues.
