### ISSUE TITLE
Player.accFlipper has no getter.

### ISSUE THREAD

**Issue by nakano15** [bluemagic123/tModLoader#3868]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Since October 1st update, Player.accFlipper no longer returns values. It only accepts setting a value, not returning.

### Steps to reproduce

1. Try calling a Player reference.
2. Try getting the value of accFlipper from that Player reference.
3. OTL

### Expected Behavior

Player.accFlipper should be able to return a value telling wether it's true or false.

### Actual Behavior

An error is given due to the absence of a getter.

### Reproduction frequency

Any time it's attempted.

**Comment by Pure-Epic** [comment]
Weird. I assume something went wrong when making the Double Jump API.

**Comment by Chicken-Bones** [comment]
Nothing when wrong but it looks like we forgot to add tModPorter for this member. You need to use `player.GetJumpState<FlipperJump>().Enabled` or `.Available` depending on what you care about

**Comment by nakano15** [comment]
I see. So Flipper also counts as another jump state. I really had no idea.
Already updated my mod with the new way of checking if player have flipper acc.
I believe Enabled means that you have it and can use.

Thanks for the answer.

**Comment by absoluteAquarian** [comment]
Flippers were changed to act more like extra jumps (since that's how vanilla originally handled them).  
The Update Migration Guide's [section for the Extra Jump API](https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide#extra-jump-api) mentions that reading `accFlipper` isn't allowed and to instead use `Player.GetJumpState(ExtraJump.Flipper).Available`.

**Comment by nakano15** [comment]
It's actually quite disappointing to have to take the longer route to check if you have flipper acc, but I'm not the one who made the rules, anyways.

**Comment by JavidPack** [comment]
We are adding the getter to Player.accFlipper, seems like there was discussion about this topic earlier that fell through. It should be in stable soon.
