### ISSUE TITLE
Add a call to the shaderdata class to swap the shader ref

### ISSUE THREAD

**Issue by krazybluemonkey** [bluemagic123/tModLoader#3872]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

ShaderData has SwapProgram for switching passes at runtime. I would like something similar for swapping shader refs as well.

### What does this proposal attempt to solve or improve?

In trying to make a mod that allows dye customization, I've ran into the road block of not being able to support modded dyes easily due to needing a separate item/bind for each shader ref. With a way to swap out the shader ref as needed, I wouldn't need more items to add modded dye support. unsure whether it's useful outside of my use case though.

**Comment by JavidPack** [comment]
It certainly seems very niche. Have you implemented your code via reflection yet? Even SwapProgram is unused by Terraria, so I'm not confident there isn't code that has unknown expectations with how the shaderdata class behaves that would cause issues down the line.

I suggest doing this with reflection, but if a more widespread use-case comes up we can revisit this.
