### ISSUE TITLE
[NixOS] Game will not start, complains about libGL

### ISSUE THREAD

**Issue by enderger** [bluemagic123/tModLoader#3874]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game refuses to start on NixOS, even with the `dotnet` symlink suggested by the previous issue about the game starting. It seems as though the game cannot find libGL

### Log File

[tModLoader-logs.tar.gz](https://github.com/tModLoader/tModLoader/files/12872404/tModLoader-logs.tar.gz)

### Steps to reproduce

1. Install the game on NixOS
2. Crash

### Expected Behavior

The game should start

### Actual Behavior

The game thinks for a minute, then crashes

### Reproduction frequency

Every time

### Additional Information

OS: NixOS
GPU: Intel ARC A770

I could not get Steam Sniper working on my system.

**Comment by fishiatee** [comment]
This looks like a Mesa error to me. Normally `libGL.so.1` is provided by your system Mesa installation.
Check if your Mesa installation is up-to-date and you can run OpenGL games using the appropriate driver for your GPU.

**Comment by JavidPack** [comment]
Did the suggestion help? Going to close soon unless there is further activity.

**Comment by enderger** [comment]
Yeah, the issue is resolved.
