### ISSUE TITLE
Bosses in multiplayer are very buggy

### ISSUE THREAD

**Issue by sezaqq** [bluemagic123/tModLoader#3881]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I play with someone or even just go into multiplayer myself, the bosses start to get very buggy: they teleport here and there, their projectiles are not visible, their phases break, and so on. Has anyone encountered this and knows the solution? I play on a license ,I tried both through Steam and IP.

### Log File

[environment-server.log](https://github.com/tModLoader/tModLoader/files/12905746/environment-server.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12905747/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/12905748/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/12905749/server.log)
[client.log](https://github.com/tModLoader/tModLoader/files/12905750/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/12905751/environment-client.log)

### Steps to reproduce

1.Start a multiplayer game as host
2.Going into the world
3.Summoning any boss
4.See the weirdest bugs in history

**Comment by JavidPack** [comment]
This could very well be any number of things. I suggest first trying to confirm the issue with 0 mods enabled. If you are still experiencing the issues, it is likely an internet issue. If you aren't, your issues are likely related to mods you have enabled, either bugs, bad logic, or they are just too computer intensive to work properly on your machine. 

Remember that much of what you described happens in Terraria itself in multiplayer, so some teleporting isn't unexpected.

**Comment by sezaqq** [comment]
> This could very well be any number of things. I suggest first trying to confirm the issue with 0 mods enabled. If you are still experiencing the issues, it is likely an internet issue. If you aren't, your issues are likely related to mods you have enabled, either bugs, bad logic, or they are just too computer intensive to work properly on your machine.
> 
> Remember that much of what you described happens in Terraria itself in multiplayer, so some teleporting isn't unexpected.
 okay,i checked all mods and one imposter among they be infernum,but idk what to do because my modpack was based on him=((

**Comment by JavidPack** [comment]
You could always contact the author, they might not be aware of the specific circumstances and your report might help them fix it.

**Comment by sezaqq** [comment]
> You could always contact the author, they might not be aware of the specific circumstances and your report might help them fix it.

ok,tysm for help,you are the first one to properly explain me about the possible problems
