### ISSUE TITLE
Game run significantly worse with OpenGL than D3D11.

### ISSUE THREAD

**Issue by fishiatee** [bluemagic123/tModLoader#3884]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When running tModLoader with the rendering backend set to OpenGL, the game runs significantly worse. Frequent lag spikes (one every 5 seconds or so) generally makes the game unplayable. On the same hardware, D3D11 performs significantly better (less spikes, overall FPS was more consistent).

Additionally, some custom UI elements just looks weird on OpenGL (one example is Calamity's custom boss bar percentage font, seems to be mod-dependent).

Same list of mods and video setting by the way.

### Log File

None.

### Steps to reproduce

1. Run the game with OpenGL (add `/gldevice:OpenGL` as a parameter.)
2. Try it for yourself.

### Expected Behavior

Like most games I'd expect OpenGL to perform similarly or even better than DirectX 11.

### Actual Behavior

Lag spikes every few seconds, stuff takes longer to render, weird custom UI stuff, just generally worse than D3D11.

### Reproduction frequency

Always. I've tested on both Windows 7/11 (using dGPU) and Linux (iGPU, Ubuntu 20.04 with i965 driver and Ubuntu 22.04 with crocus driver). The results were similar.

### Additional Information

Might be a FNA issue though cannot say for sure.

**Comment by Chicken-Bones** [comment]
DirectX performing better than OpenGL is the reason it is the default

**Comment by fishiatee** [comment]
But OpenGL (and Vulkan which I doubt will improve the situation) are the only APIs that is supported on Linux. Does that mean tModLoader on Linux will remain unplayable? Or is there any plans to improve OpenGL performance?

**Comment by Chicken-Bones** [comment]
Give Vulkan a try on Linux. I can't recall if it's default there, but we definitely want to move in that direction. If you have any graphics API timing analysis tools or profilers which can get some info we might be able to look into some specifics. Please also make sure you test with and without mods so we can determine mod vs tML issues
