### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by kiaraly** [bluemagic123/tModLoader#3886]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Trying to build the docker image results in the error
```
...
#0 17.22 dotnet-install: Installed version is 6.0.0
#0 17.23 dotnet-install: Calling: combine_paths /home/tml/server/dotnet/6.0.0
#0 17.23 dotnet-install: combine_paths: root_path=/home/tml/server/dotnet/6.0.0
#0 17.23 dotnet-install: combine_paths: child_path=
#0 17.23 dotnet-install: Calling: get_absolute_path /home/tml/server/dotnet/6.0.0/
#0 17.23 dotnet-install: Adding to current process PATH: `/home/tml/server/dotnet/6.0.0`. Note: This change will be visible only when sourcing script.
#0 17.23 dotnet-install: Note that the script does not resolve dependencies during installation.
#0 17.23 dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
#0 17.23 dotnet-install: Installation finished successfully.
#0 17.23 Dotnet should be present in "/home/tml/server/dotnet/6.0.0"
#0 17.23 A tModLoader server has not been installed yet, please run the install or install-tml command before installing mods
#0 17.23 chmod: /home/tml/start-tModLoaderServer.sh: No such file or directory
------
failed to solve: process "/bin/sh -c curl -O https://raw.githubusercontent.com/tModLoader/tModLoader/1.4.4/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh  && chmod u+x manage-tModLoaderServer.sh  && ./manage-tModLoaderServer.sh install --github --skip-mods  && chmod u+x $HOME/start-tModLoaderServer.sh" did not complete successfully: exit code: 1
```

I had a look around in the container and saw that the file was present in the `server` subdirectory. Changing the line https://github.com/tModLoader/tModLoader/blob/c20ea300efcca9f2605ce4f61ac7d74cd38ef6b7/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Docker/Dockerfile#L30
to ` && chmod u+x $HOME/server/start-tModLoaderServer.sh` makes that step finish successfully however on `docker-compose up` I am greeted with

```
terraria-tml-1  | Checking for script updates
terraria-tml-1  | No script update found
terraria-tml-1  | A tModLoader server has not been installed yet, please run the install or install-tml command before installing mods
```

### Steps to reproduce

Follow https://github.com/tModLoader/tModLoader/tree/stable/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils#using-the-docker-container

### Reproduction frequency

Always

**Comment by turtletowerz** [comment]
You're using the outdated version of the script. The rewrite is not on `stable` yet but it's on `preview` and `1.4.4`. Sorry about this but it won't be on stable until the end of the month

**Comment by Lucyfurnice** [comment]
update please
why is it using alpine when it is mono, c#?
