### ISSUE TITLE
Thrown Waters display "0% critical strike chance" when they do not in vanilla

### ISSUE THREAD

**Issue by blahblahbal** [bluemagic123/tModLoader#3895]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Unholy, Holy, and Blood Water display their crit chance of 0% in their tooltips, when they should not. I have attached screenshots of vanilla and tmod. This is easy to fix within a mod, but it should act as it does in vanilla.

### Log File

Not applicable in this case.

### Steps to reproduce

1. Get yourself some thrown water (in any way you like).
2. Look at the tooltip and notice that the tooltip shows the crit chance.

### Expected Behavior

It should not show the crit chance.

### Actual Behavior

It displays the crit chance

### Reproduction frequency

Every time.

### Additional Information

Vanilla: 
![image](https://github.com/tModLoader/tModLoader/assets/1240123/6b7c4abd-6685-40cd-9ec6-9753cfe94e83)
tModLoader:
![image](https://github.com/tModLoader/tModLoader/assets/1240123/b44fa4d0-d415-4cf6-98e6-32cfc358f133)

**Comment by JavidPack** [comment]
Looking into this, I'm not sure what the best solution is....

Items with the DefaultDamageClass can still use crit chances, and the user would presumably want to see them. It appears that in vanilla this only applies to these items, but I expect many modded items might have a crit chance assigned to DefaultDamageClass items. Changing the crit behavior of DefaultDamageClass items to just not work at this point would probably not be appreciated by modders using them. 

We could technically not show the crit chance line if the final crit chance is 0, but that could lead to situations where multiple mods adjust a crit chance and it is now zero and no line is shown. This is something we standardized with mana costs, for mana costs we decided that even if the cost is zero, the mana cost shouldn't be omitted for the sake of consistency. 

...Ok, I think I'll go with just omitting the line. It's a bit of a different situation from mana cost. It doesn't seem like a "bug" if it's zero after multiple mods adjust a crit value, and it makes sense not to show it if it was never assigned anyway.
