### ISSUE TITLE
Default server timeout is too long with large mod packs

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3901]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Players

### Description

If the player has a very large modpack (100+ mods, many content mods included), if the server's serversided configs don't match the client's serversided configs, a mod reload is triggered after initiating a join. If this reload takes longer than the default timeout period (2 minutes/7200 ticks), the player is timed out before he has a chance to enter. 
Server logs reflect that 2 minute duration roughly:
```
[17:39:26.025] [TCP Listen Thread/INFO] [Terraria]: <IP HERE> is connecting...
[17:41:33.451] [Main Thread/INFO] [Network]: [1][<IP HERE> (Anonymous)] Terminating: Timeout
```

### Log File

Log files of a server and a client that gets timed out. IPs censored. <IP 2> in the server is the one that gets timed out.
Look for `Connecting to <IP SERVER>` in the client log, and `<IP 2>` in the server log.

[server(14).log](https://github.com/tModLoader/tModLoader/files/13190650/server.14.log)
[client(44).log](https://github.com/tModLoader/tModLoader/files/13190658/client.44.log)

### Steps to reproduce

It can probably be reproduced by writing a mod that is artificially loading for 2+ minutes in a loop. Simply host a server, then change a serversided config of a mod, and reload, then join

### Expected Behavior

There is no reason to trigger a timeout when the client is busy reloading mods

### Actual Behavior

No timeout

### Reproduction frequency

Haven't reproduced it myself yet

### Additional Information

There's code to prevent a timeout, `Main.stopTimeOuts`, but it's unused.

The timeout should be watchdog'd until mod loading has been completed.

**Comment by Chicken-Bones** [comment]
Can we send keep-alive packets to the server during mod loading to let them know we're still in the connection process?

**Comment by direwolf420** [comment]
Sort of duplicate of #3674?
