### ISSUE TITLE
Increase maximum supported length of chest names

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3909]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

There's a character limit on how long a chest name can be (20), which can be a problem if
1. The chest itself has a long name. This is in the realm of possibilities as one vanilla chest has a length of 19, 1 below the limit. If a mod adds a material with a corresponding chest it will say `VeryLongMaterialName Chest` but gets cut off.
2. Chat tags are used with modded items - Write `[i:2]` which displays dirt block, `[i:ModName/ItemName]` which displays ItemName. You can see immediately that the latter is almost impossible unless the mod and/or the item has a short internal name. This is useful for players that want to have a better visual feedback for item sorting purposes.

Showcase that 2. works with modded items:
[chest name is "[i:ThoriumMod/Blood]", exactly 20](https://cdn.discordapp.com/attachments/445276626352209920/1136990391539879996/Screenshot_6.png?ex=654e19d1&is=653ba4d1&hm=56524e9285310309414ea8b016ecf7fab5f67156ba3ca1c9c8f537fcba9dc199&)

The proposal is to increase the limit.

### What does this proposal attempt to solve or improve?

Make longer chest names and item tags with modded items possible.

### Which (other) solutions should be considered?

Remove the limit entirely

**Comment by Metratrj** [comment]
I would take care of that. /claim
