### ISSUE TITLE
"Please ensure Steam is logged in and running" on v2023.08.3.4 

### ISSUE THREAD

**Issue by lilfaxmachine** [bluemagic123/tModLoader#3916]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When launching tmodloader through the .bat file, i get a popup telling me to ensure that steam is logged in and running, which it is. I have a fresh install of Terraria and a fresh install of tmodloader. I've tried restarting both steam and my pc, with no luck. I suspected that maybe it was because I had the game installed on a different drive than where steam was located, but it made no difference when i tried installing it on that drive either. I have attached my log files. 

### Log File

[environment-client.log](https://github.com/tModLoader/tModLoader/files/13256680/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13256681/Launch.log)
[client.log](https://github.com/tModLoader/tModLoader/files/13256682/client.log)

### Steps to reproduce

Launch by using start-tModLoader.bat

### Expected Behavior

Game should launch

### Actual Behavior

Popup telling me to ensure steam is logged in and running

### Reproduction frequency

100%

**Comment by Solxanich** [comment]
"Usually" when this happens, it is an issue with Steam Desktop Client. 
Typical fixes include restarting the computer and restarting steam
