### ISSUE TITLE
tModLoader freezes on launch - MacOS

### ISSUE THREAD

**Issue by SnailPerson** [bluemagic123/tModLoader#3923]
### Version

Latest 1.4.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I press play on steam, game launches, window never shows up. When checking the executable via task manager, it says "...has stopped responding".
After roughly 3 minutes of inactivity, the exe closes itself with an error message on screen.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13313697/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13313699/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13313701/Natives.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13313715/environment-client.log)

### Steps to reproduce

1. Launch tmod from steam on an apple device.
2. Watch it crash 
3. Profit?

(MacOS Monterey 12.2.1)

### Expected Behavior

the game should launch and be playable

### Actual Behavior

it crashes on launch

### Reproduction frequency

every time the game is launched from steam

### Additional Information

e

**Comment by JavidPack** [comment]
Do you have a `terrariasteamclient.log` file as well? If so, please post that.

You can try launching the `start-tModLoader.sh` file directly. It is found in the [install directory](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install) (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files"). As far as I can tell so far, something is erroring when the game tries to launch the Terraria hours tracking portion of the game code. Launching manually would bypass that issue. 

You might want to come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader) for live help, it will be much more productive.

If you try the other approach, please post the new logs in a new comment, they might have some clues.

**Comment by SnailPerson** [comment]
it seems like the issue has been resolved? i can launch from steam without crashes again.
on a sidenote, the `start-tModLoader.sh` has worked when i pasted it into the computers terminal and i was able to successfully launch the game.
