### ISSUE TITLE
"please ensure steam is logged in and running" error

### ISSUE THREAD

**Issue by Shandzu** [bluemagic123/tModLoader#3925]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I can't open tmodloader because of this error (it's still present even if steam is working).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13325514/client.log)

### Steps to reproduce

open the start-tModLoader.bat file

### Expected Behavior

probably to start tmodloader?

### Actual Behavior

"please ensure steam..." error

### Reproduction frequency

100%

**Comment by Luna-Nocturna** [comment]
Might be related to https://github.com/tModLoader/tModLoader/issues/3032 which still isn't fixed.

**Comment by Shandzu** [comment]
I don't think it's related to #3032. The issue is im trying to launch start-tModLoader.bat file and gives me the error i mensioned.

**Comment by JavidPack** [comment]
Doesn't look like you followed the install instructions. <https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#steam-installation> 

Install tModLoader through steam and launch it through steam.

**Comment by daymxn** [comment]
> Doesn't look like you followed the install instructions. https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#steam-installation
> 
> Install tModLoader through steam and launch it through steam.

What about folks who want a manual installation? I was hoping to run tml under the native terraria executable so that I could properly accrue time played and track achievements, but I ran into the same error. Ironically, I *don't* run into the error if I install tModLoader on steam and manually run it *nested* in the terraria directory. But it launchs tModLoader directly instead of the intended terraria application- effectively killing my intention.

**Comment by JavidPack** [comment]
tModLoader by default already does count as Terraria playtime. We have code ensuring that that happens. Last we checked it was working, so it should still be working. 

For example, when you launch tmod from steam, you'll see that both Terraria and tModLoader are "running" once the game launches:    
![image](https://github.com/tModLoader/tModLoader/assets/4522492/f8b91e7b-faac-4c07-9d82-db78f009979c)    

Achievements are disabled in the executable itself, so nothing you do in how you launch the game will work around that. There is a mod that lets you earn Terraria achievements (https://steamcommunity.com/sharedfiles/filedetails/?id=2927542027&searchtext=achievement+enable). It looks like it is a local tracking of achievements, it will not affect what achievements are shown as unlocked on your Steam account for Terraria. I'm not aware of any mod that allows earning Terraria achievements in terms of affecting your Steam account, but you can search and see.

I believe manual installation does work even for Steam users, I just tested it locally. but it won't change how tModLoader works in regard to achievements.
