### ISSUE TITLE
cmd loads infinitely and becomes inoperable

### ISSUE THREAD

**Issue by Fuyu8X** [bluemagic123/tModLoader#3927]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

This happens when I adapt a resource pack that changes audio or SFX.
How do I adapt audio or SFX resource pack?

### Steps to reproduce

1 Subscribe to the Resource Pack in the Steam workshop

2 Open tmodloader and adapt the added resource packs

### Expected Behavior

sound and will be changed

### Actual Behavior

The screen blinks repeatedly and the cmd entries increase endlessly.

### Reproduction frequency

100％

### Additional Information

I have a lot of mods in, but I don't think there are any competing mods or resource packs.

**Comment by JavidPack** [comment]
This issue is missing the logs files. Logs are necessary for us to help troubleshoot and fix this issue.
 
Please attach the log files. You'll find the log files in the logs folder. Look for the `client.log`, `Launch.log`, `Natives.log`, and `environment-client.log` files. If the issue relates to multiplayer post the `server.log` and `environment-sever.log` files as well.
      
Logs can be found in the "tModLoader-Logs" folder in your tModLoader [install directory](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install) (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files") 
      
Attach log files by making a new comment and dragging them into the text input field. Please do not copy and paste the text from the log files, post the actual files.

**Comment by Fuyu8X** [comment]
[Natives.log](https://github.com/tModLoader/tModLoader/files/13343107/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/13343109/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/13343110/environment.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13343111/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13343112/Launch.log)

**Comment by JavidPack** [comment]
I'm not seeing any errors in your logs related to resource packs. You have a lot of mods and a lot of resource packs, it would help if you could disable all mods and identify a single resource pack that is giving you trouble. Then send the link to that resource pack. I can then test that on my computer.

**Comment by Fuyu8X** [comment]
I found that the same thing happens when I adapt all mods and resource packs with them turned off.
The resource packs in question are the following two packs
PlayStation 2 SFX
Waifu Voice Pak

**Comment by JavidPack** [comment]
K, when I tried to enable those 2 packs, I ran into this issue: https://github.com/tModLoader/tModLoader/issues/2913

Basically, some Terraria resource packs are not compatible with tModLoader at this time. The reason for this is that tModLoader does not allow multiple sound files to have the same filename. This will be fixed eventually, but you can work around it.

For example, in `Waifu Voice Pak`, which you'll find in  `D:\SteamLibrary\steamapps\workshop\content\105600\2665172132`, there are `@Female_Hit_0.wav` and `@Female_Hit_0.xnb` files. 

To fix this, copy the `2665172132` folder to the `C:\Users\fuyu\OneDrive\ドキュメント\My Games\Terraria\tModLoader\ResourcePacks\` folder. Then, go into the copied folder and delete the `\Content\Sounds\Choose your favorite` folder.

For `PlayStation 2 UI SFX`, just use the tModLoader specific version: https://steamcommunity.com/sharedfiles/filedetails/?id=3039179368&searchtext=PlayStation+2+SFX

Finally, you'll need to edit `C:\Users\fuyu\OneDrive\ドキュメント\My Games\Terraria\tModLoader\config.json` in a text editor and change `"Enabled": true`, to `"Enabled": false,` for all the resource packs. Save the file, then launch the game. Go into the Resource pack menu and enable the fixed resource packs, not the broken ones. Your local fixed copy of `Waifu Voice Pak` won't have the Steam icon, for example.

![image](https://github.com/tModLoader/tModLoader/assets/4522492/63817020-8341-4437-aae1-f75faefc358a)
