### ISSUE TITLE
tModPorter does not appear on non-Windows

### ISSUE THREAD

**Issue by Jar-M** [bluemagic123/tModLoader#3933]
### Version

Latest 1.4.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

So, I have a mod that hasn't updated since 1.4.3 and was attempting to run tModPorter, however when I followed the guide I could not find any tModPorter option. When I went to the discord to trouble shoot, I found that the ! option that was supposed to appear did not appear and was recommended to report a bug.

### Log File

<img width="1440" alt="Screenshot 2023-11-16 at 2 44 17 PM" src="https://github.com/tModLoader/tModLoader/assets/18015841/dde42ad5-9009-43a8-9d41-3f240cfebd6f">
<img width="1440" alt="Screenshot 2023-11-16 at 2 44 03 PM" src="https://github.com/tModLoader/tModLoader/assets/18015841/5adc271b-304f-443f-95d5-83d81208e8af">

### Steps to reproduce

Boot up tModLoader and attempt to run tModPorter

### Expected Behavior

tModPorter should appear

### Actual Behavior

no tModPorter option

### Reproduction frequency

Every time I boot up tModLoader

### Additional Information

#mod-programming-help thread is where I was discussing it, discussion started 16 minutes ago

**Comment by Rijam** [comment]
You could probably run tModPorter manually still. In the tModLoader install directory, open the tModPorter folder. Drag and drop your `csproj` onto the `tModPorter.sh` and it should run.
