### ISSUE TITLE
Joining via Steam fails on 13% loading tile data.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bluemagic123/tModLoader#3935]
### Version

Latest `1.4.4-stable`

### OS

> Linux

Specifically, `cpe:/o:opensuse:tumbleweed:2023`.

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I attempt to join a world, it hangs at 13% successful indefinitely.

### Log File

1. [`client.log`](https://github.com/tModLoader/tModLoader/files/13397699/client.log)
1. [`environment-client.log`](https://github.com/tModLoader/tModLoader/files/13397700/environment-client.log)
1. [`environment-server.log`](https://github.com/tModLoader/tModLoader/files/13397701/environment-server.log)
1. [`Launch.log`](https://github.com/tModLoader/tModLoader/files/13397702/Launch.log)
1. [`Natives.log`](https://github.com/tModLoader/tModLoader/files/13397703/Natives.log)
1. [`server.log`](https://github.com/tModLoader/tModLoader/files/13397704/server.log)
1. [`terrariasteamclient.log`](https://github.com/tModLoader/tModLoader/files/13397705/terrariasteamclient.log)

### Steps to reproduce

1. Launch [`steam://launch/1281930`](steam://launch/1281930).

1. > Multiplayer

1. > Join via Steam

1. > Join user

1. > Load mods

1. > Fail to load tileset

### Expected Behavior

It should load the tile data.

### Actual Behavior

It hangs at 13% tile data loaded.

### Reproduction frequency

Constant.

### Additional Information

1. [`steamcommunity.com/app/105600/discussions/0/530646080850112308`](https://steamcommunity.com/app/105600/discussions/0/530646080850112308#:~:text=2015%20@%2012:47pm-,Stuck%20on%20%22Receiving%20tile%20data%2013%25%22,-Hello!%20I%20bought)
1. [`reddit.com/r/Terraria/comments/vibcfj/comment/itvgstc`](https://www.reddit.com/r/Terraria/comments/vibcfj/comment/itvgstc/?utm_source=share&utm_medium=web2x&context=3#:~:text=insanearminpls-,Stuck%20at%20Receiving%20tile%20data:%206/13%25%20while%20joining%20online%20server,-Thats%20all%2C%20I)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tModLoader/tModLoader/issues/3935#issue-1999977153

Disabling YaST's firewall appeared to manage to get it to load to 85%. However, it ultimately still hangs.

**Comment by JavidPack** [comment]
There are quite a lot of mods loaded, I would first try 0 mods loaded on a fresh world and fresh player, make sure that works, then go from there to identify the issue. I see errors logged from ArmorReforge, WingSlotExtra, and SubworldLibrary in your log, but it could be caused by other mods or settings.

If you'd like more direct support, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). We can't really do much here on the issue tracker.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tModLoader/tModLoader/issues/3935#issuecomment-1817732680

Fixed by reinstallation of Terraria on both systems, so apologies. Thank you, @JavidPack.
