### ISSUE TITLE
CollectedEnoughItemsToCraftRecipeNew - System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by FluffyDiscord** [bluemagic123/tModLoader#3936]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Randomly, after getting some items, game freezes so that player cannot do anything, cannot open inventory or game menu. While in this state, player is receiving the item infinitely - duplicating.  The only way to workaround it is to force close the game and lose progress.

### Log File

[terrariasteamclient-1.log](https://github.com/tModLoader/tModLoader/files/13401504/terrariasteamclient-1.log)
[environment-client-1.log](https://github.com/tModLoader/tModLoader/files/13401505/environment-client-1.log)
[client-1.log](https://github.com/tModLoader/tModLoader/files/13401506/client-1.log)

### Steps to reproduce

1. start to pick up items
2. happens somehow, randomly, not sure in which items, probably multiple ones, modded especially

### Expected Behavior

Do not go out of bounds, check if index exists and noop

### Reproduction frequency

Not reliably, because it happens for many items, that I have noticed, from multiple mods.

**Comment by JavidPack** [comment]
Looking at the code, I assume some mod is doing something wrong and messing up how the game works.

You can follow [this process](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart) to identify the mod responsible, and then check the mod's steam workshop page for bug report guidance. Or just disable it.

**Comment by FluffyDiscord** [comment]
Disabled Catalyst Remix and so far it seems to be fixed.
