### ISSUE TITLE
Where is download manage-tModLoaderServer.sh?

### ISSUE THREAD

**Issue by IvesSSa** [bluemagic123/tModLoader#3938]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

**Comment by turtletowerz** [comment]
Please read through the 1.4.4 instructions [on the modded server wiki page](https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server)

**Comment by GHXX** [comment]
For anyone else looking for this, seems that it can be found in this folder: https://github.com/tModLoader/tModLoader/tree/stable/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils

Seems pretty hard to find to me, especially as it is not at all linked on this site: https://docs.tmodloader.net/docs/stable/md__github_workspace_src_t_mod_loader__terraria_release_extras__dedicated_server_utils__r_e_a_d_m_e.html
