### ISSUE TITLE
Content files are locked

### ISSUE THREAD

**Issue by Dnixcx** [bluemagic123/tModLoader#3941]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I accidentally clicked to test version 1.4.3 and the steam update says Content files are locked and I can't go back to the previous version! 
I tried to download it again,but it still like that. i also tried delete the files in steammaps/tmoder. all of that still unhelp....

### Log File

<img width="748" alt="屏幕截图 2023-11-22 135233" src="https://github.com/tModLoader/tModLoader/assets/151752213/f51247bd-a596-4150-b3e2-bc8f38114891">

**Comment by JavidPack** [comment]
Usually a computer restart will fix this. Did you end up fixing this yet?
