### ISSUE TITLE
integrate cloud flare caching to javid.ddns.net to reduce bandwidth usage

### ISSUE THREAD

**Issue by pk3zip** [bluemagic123/tModLoader#3951]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

this will require some backend work but my suggestion is to add  cloudflare caching to the backend to allow signifigantly reduced bandwidth usage. This can be done by changing the location of where mods are hosted to `Mods/{{ModName}}/{{filehash or version}}/{{ModName}}.tmod` you can tell cloudflare to cache all .tmod files for as long as possible. in the back end you can make Mods/** `noindex` so when you directly visit a mod url it with return the mod but if it is a directory it will still return 403. then in download.php you can make it redirect to the mod url so when the mod url is fetched hopfully cloudflare will have it cached and if not they should cache it but when a new version is uploaded it will have a new url so cloudflare will cache the new file and will not serve the old file allowing for instant propagation

### What does this proposal attempt to solve or improve?

large bandwidth usage

**Comment by pk3zip** [comment]
A better explanation 

### Proposal: Implement Cloudflare Caching for Bandwidth Reduction

**Objective:**
Utilize Cloudflare caching to reduce bandwidth usage while maintaining direct access to mod URLs.

**Approach:**
1. **Cloudflare Configuration:**
   - Change mod file hosting to `Mods/{{ModName}}/{{filehash or version}}/{{ModName}}.tmod`.
   - Configure Cloudflare to cache `.tmod` files for extended durations.

2. **Backend Modifications:**
   - Set `Mods/**` to disallow indexing to prevent browsing but allow direct access to mod URLs.
   - Configure direct access for mod URLs while returning a 403 error for directory requests.

3. **Download.php Redirection:**
   - Enable redirection in `download.php` to mod URLs.
   - Anticipate Cloudflare caching for efficient serving; new versions generate new URLs for instant propagation.

**Benefits:**
- Substantial bandwidth reduction through Cloudflare caching.
- Direct mod URL access while preventing indexing.

**Considerations:**
- Ensure redirections handle new uploads to prevent serving outdated versions.

**Comment by JavidPack** [comment]
The bandwidth usage of the server running javid.ddns.net is not an issue at this time. It is only used to serve 1.3 era mods, which are less and less popular as time progresses, so it doesn't use much bandwidth. I imagine integrating Cloudflare would be a significant time and money investment, so these changes would be a lot of investment for practically no gain. 

As we have limited time, we will not be working on this. Thanks for the suggestion though, it would likely have been useful to test out during the early days of tModLoader.

**Comment by pk3zip** [comment]
okay
