### ISSUE TITLE
mods issue

### ISSUE THREAD

**Issue by jsemnej** [bluemagic123/tModLoader#3952]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

i cant download ANY mods at all (i tried to switch versions too) and it only says "Cant Download. Click here for info" if i click it it says 
![obrázek_2023-11-29_141858167](https://github.com/tModLoader/tModLoader/assets/152402394/042760f2-a4a4-431a-8e10-576638381d0b)
i do not know what mod it is, i tried multiple to make sure it doesnt work on all mods. 
Theres a thing in right corner that says "see issues" if i click on it it says 
![Snímek obrazovky 2023-11-29 142018](https://github.com/tModLoader/tModLoader/assets/152402394/306b139c-50b1-4feb-83a0-82d0ea78a7a5)
![Snímek obrazovky 2023-11-29 142028](https://github.com/tModLoader/tModLoader/assets/152402394/a1f78429-d7dc-4c78-ab52-ea4a1c1d38e8)
![Snímek obrazovky 2023-11-29 142042](https://github.com/tModLoader/tModLoader/assets/152402394/033668df-9618-4c1a-a9d2-d54f885e0caf)
![Snímek obrazovky 2023-11-29 142053](https://github.com/tModLoader/tModLoader/assets/152402394/576dc745-ddae-4ab9-b670-edfc3bc41122)
![Snímek obrazovky 2023-11-29 142109](https://github.com/tModLoader/tModLoader/assets/152402394/cd38f6e0-a23f-4702-bf36-8cee0391a06b)
![Snímek obrazovky 2023-11-29 142230](https://github.com/tModLoader/tModLoader/assets/152402394/930d2836-d8b5-44dd-a315-ce992a3f2581)
All of this which i dont know what it means nor how to fix it, anyone can help? if you need more info to it just ask me

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13500983/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13500989/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13500992/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13500993/Natives.log)

### Expected Behavior

the mod should normally instal and work 

### Actual Behavior

i cant instal any mods

### Reproduction frequency

it just happened to me, first time i see this

**Comment by JavidPack** [comment]
It seems like some workshop files are in an incomplete download state. I suggest closing the game, then verifying game integrity: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#verify-game-integrity

If in-game downloading is giving you issues, you can subscribe to mods on the workshop directly, that might bypass whatever issue you are running into. https://steamcommunity.com/app/1281930/workshop/

There is also this final suggestion if it is still having issues https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#cant-redownload-mod

If you are still having issues come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader) and ask there, this issue tracker is not suited for support questions.

**Comment by Solxanich** [comment]
Should be fixed for Mod Browser issues when release the December 1st update

**Comment by jsemnej** [comment]
> It seems like some workshop files are in an incomplete download state. I suggest closing the game, then verifying game integrity: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#verify-game-integrity
> 
> If in-game downloading is giving you issues, you can subscribe to mods on the workshop directly, that might bypass whatever issue you are running into. https://steamcommunity.com/app/1281930/workshop/
> 
> There is also this final suggestion if it is still having issues https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#cant-redownload-mod
> 
> If you are still having issues come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader) and ask there, this issue tracker is not suited for support questions.

i uninstalled a mod i had downloaded and everything is fine, still thanks
