### ISSUE TITLE
crash while trying to save player or world 

### ISSUE THREAD

**Issue by roastedpotat0** [bluemagic123/tModLoader#3957]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

most of the time tmodloader crash while trying to save the world or player(sometime it only save the player sometime it don't save at all) then crash, normal terraria work just fine

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13533720/client.log)

### Steps to reproduce

start tmodloader -> load the mod -> chose character -> chose world  -> put stuff in to the character inventory and dig up dirt-> save and exit-> crash

### Expected Behavior

save world and player normally

### Actual Behavior

crashed saying that the access is denied

### Reproduction frequency

frequently, sometimes it work after a restart

### Additional Information

-) the world and player file is NOT set to readonly
-)starting the game with admin don't help 
-)i have try to fix by allowing the file in file protection and deactivate my antivirus (i don't have any antivirus other than system security)
-)the only mod i use is calamity(i don't have any other mod installed)
-)i don't use cloud save
-)this bug occur in both online and offline
-)i'm on window 11 
-)i'm in the admin account on my laptop
-)i have verify the folder intergrity
-)i have tried redownload both terraria and tmodloader

**Comment by JavidPack** [comment]
Judging by your logs, it looks like windows is preventing the game from saving files, see <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#controlled-folder-access> for information on allowing tmodloader to save files.

**Comment by roastedpotat0** [comment]
> Judging by your logs, it looks like windows is preventing the game from saving files, see https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#controlled-folder-access for information on allowing tmodloader to save files.

i have tried adding exception to the folder protection and deactivating the anti virus but it still didn't help, i saw that there's a last result by telling the tmodloader to save to the installdirectory but i don't understand the instruction(it's kind vague to me), so can you please give me a clear instruction on how to do it?. thanks for helping me with my problems

**Comment by JavidPack** [comment]
I've added a video for how to create a text file named savehere.txt to the instructions, give them a try. 

If you still need more help, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). We don't usually do support questions here since it is slow and inefficient.

**Comment by roastedpotat0** [comment]
> I've added a video for how to create a text file named savehere.txt to the instructions, give them a try.
> 
> If you still need more help, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). We don't usually do support questions here since it is slow and inefficient.

i don't know if it's just me but i couldn't watch the video, i'll close the issues now since i don't have any other problems, i have joined the discord so if i have future problems i will ask there, thanks for helping me
