### ISSUE TITLE
the game crashes in any moment

### ISSUE THREAD

**Issue by Artela22** [bluemagic123/tModLoader#3959]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Hello everyone
I'm playing with a friend and out of nowhere the game closes for both of us and shows us this image. because it is?

### Log File

![image](https://github.com/tModLoader/tModLoader/assets/132639393/4291bac8-25c2-4eba-b12e-b63e36890eca)

### Steps to reproduce

open te game
play whit normaly
crashes out of nowhere

### Actual Behavior

_yes_

### Reproduction frequency

yes

### Additional Information

_everytime show this wondow_

**Comment by fw25809** [comment]
me too

**Comment by stephsix** [comment]
Me too. I maintain a Terraria multiplayer server (10+ players) and have been experiencing constant crashes since updating to v2023.10.3.0. I hope the official team can fix this issue soon.

**Comment by ibby9902** [comment]
Same
![image](https://github.com/tModLoader/tModLoader/assets/74113881/ef8bda20-390e-4bd1-848f-dbf4a684fe25)

**Comment by jedabero** [comment]
My friend is having the same exact crash! BUT my game isn't crashing. I think it could be a corrupted update,

So, I've asked him to make back ups of his characters and worlds and then uninstall and reinstall everything. Will post again if the crash persists.

**Comment by jedabero** [comment]
It still crashes and now mine crashed too. 

Here's the log from my crash
[client.log](https://github.com/tModLoader/tModLoader/files/13537914/client.log)

**Comment by JavidPack** [comment]
We have been informed that this is a Calamity issue and that they should have it fixed next time they update Calamity. Closing.
