### ISSUE TITLE
Please ensure Steam is logged in and running  A client log file containing error information has been generated in D:\ModLoader 1.4.4\tModLoader\tModloader-Logs (You will need to share this file if asking for help)

### ISSUE THREAD

**Issue by Archit-Ud-Din-Aibak** [bluemagic123/tModLoader#3960]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

Please ensure Steam is logged in and running

A client log file containing error information has been generated in DAtModLoader 1.4.4\tModLoader\tModloader-Logs (You will need to share this file if asking for help).   I had installed Terraria from a cracked website steamunlocked
![17015936614377103614626970815196](https://github.com/tModLoader/tModLoader/assets/110294476/92e8564e-8eb9-4d12-b2c8-352c4acf9c24)

**Comment by JavidPack** [comment]
Please do not ask for support if you pirated Terraria.
