### ISSUE TITLE
Suddenly crashes while I am playing the game

### ISSUE THREAD

**Issue by iambicsfasf** [bluemagic123/tModLoader#3966]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Suddenly crashes while I am playing the gameSuddenly crashes while I am playing the game, and 
<img width="785" alt="屏幕截图 2023-12-07 113537" src="https://github.com/tModLoader/tModLoader/assets/153154434/fc8e8983-e349-4aa1-a0bf-b932181caa1a">
display the following image.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13594713/client.log)

**Comment by JavidPack** [comment]
We have been informed that this is a Calamity issue and that they should have it fixed next time they update Calamity. Closing.
