### ISSUE TITLE
Game crashes, game suddenly crashes after playing Wall of Flesh and Blood

### ISSUE THREAD

**Issue by yaooooooooop** [bluemagic123/tModLoader#3968]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

In the latest version of Calamity Mod, the game suddenly crashed after I killed the wall of flesh and blood, please help me to see if it's a conflict with that mod, thank you very much！
[client.log](https://github.com/tModLoader/tModLoader/files/13601375/client.log)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13601402/client.log)

**Comment by JavidPack** [comment]
The errors in your log suggest the `SpearToJavelin (Thrown Spears 投掷长矛)` mod is the cause of your crashes. If disabling the mod fixes your issue, make sure to report this issue to the mod author.

If you still have issues later, you can [read client.log](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#reading-clientlog) and [follow the flowchart](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart) to diagnose and fix these issues for yourself.
