### ISSUE TITLE
ModMenu Sun and Moon not working

### ISSUE THREAD

**Issue by LaBrique** [bluemagic123/tModLoader#3971]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Custom Suns and Moons in ModMenu are not taken into account and always default to Vanilla.

### Log File

[environment-client.log](https://github.com/tModLoader/tModLoader/files/13607530/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13607531/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13607532/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/13607533/client.log)

### Steps to reproduce

1. Create a Mod
2. Setup a custom Sun and/or Moon in a ModMenu
3. Launch the game and observe the Menu

Alternatively, just look at ExampleMod's Menu.

### Expected Behavior

The Menu should draw the mod's custom Sun/Moon.

### Actual Behavior

The Menu always draws Vanilla Sun/Moon regardless of mods.

### Reproduction frequency

100%

### Additional Information

I got curious and took a peek into tModLoader's code (Following the Collaborator Guide and setup), and I saw that ModMenu.SunTexture and ModMenu.MoonTexture are never used.
![image](https://github.com/tModLoader/tModLoader/assets/36274434/a66abebc-7300-4303-90fa-bef7d619771f)
![image](https://github.com/tModLoader/tModLoader/assets/36274434/8f9008cb-df10-403f-b419-444775651255)

See ExampleMod not using its _**E**_ Sun and defaulting to Vanilla.
![image](https://github.com/tModLoader/tModLoader/assets/36274434/9b9aff91-e4d2-4d33-80cd-3d9784d2e1c8)

**Comment by TacoConKvass** [comment]
I am not sure, as I can't check myself but this might work to fix this issue.
In Main.cs there is a `DrawSunAndMoon` method
In there, there is this block of code that would have to be modified like this
```diff
private void DrawSunAndMoon(SceneArea sceneArea, Microsoft.Xna.Framework.Color moonColor, Microsoft.Xna.Framework.Color sunColor, float tempMushroomInfluence)
{

-	Texture2D value = TextureAssets.Sun.Value;
+	Texture2D value = MenuLoader.currentMenu.SunTexture.Value;
	int num = moonType;
	if (!TextureAssets.Moon.IndexInRange(num))
		num = Utils.Clamp(num, 0, 8);

-	Texture2D value2 = TextureAssets.Moon[num].Value;
+	Texture2D value2 = MenuLoader.currentMenu.MoonTexture.Value;
	//Further code, should work properly
}
```
This might work, however, due to my current hardware limitations I am unable to check

**Comment by TacoConKvass** [comment]
Yay
