### ISSUE TITLE
tModloader & Vanilla Tavernkeep-Shop Disparity

### ISSUE THREAD

**Issue by Winterlevel** [bluemagic123/tModLoader#3973]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The title doesn't exactly relay the entire issue, but it _is_ part of a larger problem.
There is currently a bug regarding Defender Medals and other Modded Currency.

### Steps to reproduce

1. Have a stack of Defender Medals in your inventory
2. Have no money in your inventory (Optional)
3. Talk to a Maximum Happiness, Post-Golem Tavernkeep
4. Open the Tavernkeep's Shop
5. Buy 2 Ballista Staves in exchange for 60 Defender Medals each
6. Place them in your inventory
7. Look at their description and Sell-Value
8. Sell one of them back to the Tavernkeep (Using the Quicksell hotkey)
9. Take note of the amount of gold you were refunded
10. Close the Tavernkeep Shop Interface
11. Talk to another Maximum Happiness NPC and open the Shop Interface
12. Look at your remaining Ballista Staff's Description and Sell Value
13. Close the Shop Interface and reload the world
14. Open the Tavernkeep's shop interface again
15. Look at your remaining Ballista Staff's Description and Sell Value again

### Expected Behavior

Vanilla
At Step 7, The Sell-Value should read: "Sell price: 56 gold 25 silver"
At Step 9, You should have received 56 gold and 25 Silver
At Step 12, The Sell-Value should read: "Sell price: 20 Gold"
At Step 15, The Sell-Value should still read: "Sell price: 20 Gold"

### Actual Behavior

tModLoader
At Step 7, The Sell-Value reads: "Buy price: 60 Defender Medals"
At Step 9, You've received 60 copper
At Step 12, The Sell-Value still reads: "Buy price: 60 Defender Medals"
At Step 15, The Sell-Value reads: "Sell price: 20 Gold"

### Reproduction frequency

100% of the time without any other mod enabled

**Comment by JavidPack** [comment]
Thanks for the report.
