### ISSUE TITLE
Main Engine Crash

### ISSUE THREAD

**Issue by GuardianMMC** [bluemagic123/tModLoader#3974]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When playing with a couple other friends, we all receive the same crash at the same time that kicks us out back to the main menu.
All attached are from the play session where it started to occur

### Log File

<img width="958" alt="crash" src="https://github.com/tModLoader/tModLoader/assets/153345812/dd55d70b-0f1a-4633-98e3-a712fd5de436">
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/13622778/terrariasteamclient.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13622780/Natives.log)
[Launch.log](https://
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13622782/environment-client.log)
github.com/tModLoader/tModLoader/files/13622781/Launch.log)
[client.log](https://github.com/tModLoader/tModLoader/files/13622784/client.log)

### Steps to reproduce

Playing normally?
Never spotted anything out of the ordinary, nor did anything out of standard gameplay.

### Reproduction frequency

Often as it would happened three times after the initial crash.

**Comment by JavidPack** [comment]
We have been informed that this is a Calamity issue and that they should have it fixed next time they update Calamity. Closing.
