### ISSUE TITLE
tMod closing without Error Code on Startup

### ISSUE THREAD

**Issue by beekbirb** [bluemagic123/tModLoader#3985]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I launch the game, It opens the console, some text fills out, and then it closes. When I open vanilla Terraria, it opens just fine.

https://github.com/tModLoader/tModLoader/assets/154096379/22bb5446-eb10-4261-a56a-1af85edbe911

### Log File

[Launch.log](https://github.com/tModLoader/tModLoader/files/13697868/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13697869/Natives.log)

### Steps to reproduce

1. Launch the game

### Expected Behavior

The game should launch and I should be able to install mods and play

### Actual Behavior

The game doesn't open, only opens console, then closes

### Reproduction frequency

Every time the game is opened

### Additional Information

- Around 3 months ago, I was able to play just fine. I reinstalled it today and it doesn't launch and just closes.
- I am on a 64x computer

So far, I've tried:
- Reinstalling Terraria and tMod
- Disabling Steam Input & Cloud
- Disabling Theater mode
- Reinstalling .NET 6 and 7
- Disabling Firewall/Adding Exclusion Folder

**Comment by Chicken-Bones** [comment]
@Solxanich do you remember the solution to this one?

**Comment by Solxanich** [comment]
@beekbirb  - you've somehow set dotnet.exe to run as Adminstrator in Compatibility Options.

Remove any flags from here in the right click properties menu: 
![image](https://github.com/tModLoader/tModLoader/assets/59670736/f538d214-60f5-4101-8e59-ffd0a5cd6cc8)

**Comment by beekbirb** [comment]
@Solxanich  I'm not sure if this is the right exe, but this is what I have for dotnet.exe

![image](https://github.com/tModLoader/tModLoader/assets/154096379/50356d42-cc8f-481c-9837-4babe8702445)

**Comment by Solxanich** [comment]
EDIT: ~~interesting. can you also verify those same properties on tmodloader.dll?~~

Can you provide a fresh set of logs from attempting to launch tmodloader again?
Might be something different

**Comment by beekbirb** [comment]
Nevermind, I was looking at the wrong dotnet.exe, one that wasn't in the tMod folder. I turned administrator off, and it launches just fine. Thank you!
