### ISSUE TITLE
No audio hardware found

### ISSUE THREAD

**Issue by rahmatj0n** [bluemagic123/tModLoader#3992]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I get error on tmodloader start. No audio hardware found. Disabling all audio. But if I run terraria itself it works perfectly. How can i fix this?
![image](https://github.com/tModLoader/tModLoader/assets/64601557/32fc04a4-2ac4-4479-bbb5-a18d39f972ad)

**Comment by JavidPack** [comment]
Your log files would help.
