### ISSUE TITLE
tModLoader won't install with the GOG version on my Mac

### ISSUE THREAD

**Issue by djbchi-young** [bluemagic123/tModLoader#3998]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I have the GOG version of Terraria so I tried to do the manual installation steps but I keep getting the same error no matter what I try. Am I extracting it somewhere wrong? It always seems to find my Terraria dotnet so I don't think it matters?

### Log File

[TerminalLog.txt](https://github.com/tModLoader/tModLoader/files/13797388/TerminalLog.txt)
[client.log](https://github.com/tModLoader/tModLoader/files/13797390/client.log)

### Steps to reproduce

1. Download latest tModLoader.zip
2. Extract to Terraria.app/Contents
3. run chmod +x on all .sh files
4. run start-tModLoader.sh

**Comment by TacoConKvass** [comment]
If you followed [this guide](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players), and you tried to install TMod in the Terraria folder, try installing it [side by side](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation) because 

> DO NOT install the tModLoader files directly into the Terraria folder. This option not supported for GOG on Mac.

**Comment by JavidPack** [comment]
I believe for Mac the manual GOG install instructions expect the user places the tModLoader folder in `/Applications/` or `/Applications/Terraria/`. You have it in `/Applications/Terraria/Terraria.app/Contents/`, so you'll need to move it. 

Additionally, you'll need to try running `arch -x86_64 /bin/bash ./start-tModLoader.sh` in the terminal after deleting your dotnet folder (`/Applications/tModLoader/dotnet`). You'll need to be in a terminal navigated to the `/Applications/tModLoader` folder. 

If you are still having issues, the fastest solution is to come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). Be sure to post your logs when asking for support.

**Comment by JavidPack** [comment]
Related to #3986

**Comment by Chicken-Bones** [comment]
Fixed in #4018 and #4017
