### ISSUE TITLE
ModProjectile CooldownSlot Rewrite Leads to Incorrect Behavior

### ISSUE THREAD

**Issue by hezuo1hao** [bluemagic123/tModLoader#3999]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

After rewriting the CooldownSlot of a ModProjectile, observed behavior deviates from the original.

### Steps to reproduce

1. Create a ModProjectile and set its CooldownSlot to a non-default value (not -1).
2. Enter the game and test this Projectile.

### Expected Behavior

 After rewriting the CooldownSlot, the Projectile should not actual behavior due to invincibility frames caused by regular enemies.

### Actual Behavior

The Projectile fakes damage due to invincibility frames caused by regular enemies.

### Reproduction frequency

100%

### Additional Information

In the vanilla version, when the CooldownSlot value is not -1, damage is inflicted regardless of the player's immunity status. However, in the modded version, when the CooldownSlot value of ModProjectile is not equal to -1, it still evaluates based on the condition of CooldownSlot being equal to -1. I suspect this may be due to an issue with boolean logic, as the assignment of ModProjectile's CooldownSlot occurs after the boolean check, causing the evaluation to still consider it as -1 and thus returning directly.
I believe the code should be adjusted based on what the image shows, moving the selected code to the position indicated by the arrow.
![QQ图片20231231231629](https://github.com/tModLoader/tModLoader/assets/110245158/7f452e63-a8fd-4f5b-b3af-a464dc1d38e6)

**Comment by JavidPack** [comment]
Thanks for tracking that down, the fix is as you mentioned.
