### ISSUE TITLE
Mod browser backend vulnerability: HTTP request crafting with bogus Steam IDs

### ISSUE THREAD

**Issue by PoroCYon** [bluemagic123/tModLoader#40]
By recreating the code of [here](https://github.com/bluemagic123/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader.UI/UIManagePublished.cs#L90
) and [here](https://github.com/bluemagic123/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader.UI/UIModSourceItem.cs#L163
) and crafing HTTP requests with 'fake' steam IDs (such as [76561198141581923](https://steamcommunity.com/id/76561198141581923) or [76561198025023640](https://steamcommunity.com/id/76561198025023640)), it is possible to upload (or replace) a mod while pretending to be someone else.

Mods contain executable code, so this can be misused to inject malware (easily developped, as the CLR isn't as restrictive as, say, Lua) into the mod, and with the amount of downloads per day for all mods combined, it would make quite a high-valued botnet. The malware can take over other mods published to the backend by the user, too, to infect even more users.

**Comment by JavidPack** [comment]
K, fixed.
