### ISSUE TITLE
Delete Mod modal is bugged

### ISSUE THREAD

**Issue by ibbycs** [bluemagic123/tModLoader#4007]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Clicking the delete button on a mod will show a popup window with vertical text. Yes/No buttons are barely clickable

### Steps to reproduce

1. Have a mod downloaded
2. Click trash icon
3. Vertical text on popup window & Yes/No buttons aren't clickable apart from a small space on the left of the button

### Expected Behavior

Text should be normal and the whole Yes/No buttons should be clickable

### Actual Behavior

Clicking the delete button on a mod will show a popup window with vertical text. Yes/No buttons are not clickable

![image](https://github.com/tModLoader/tModLoader/assets/74113881/cd798a3a-9eb8-40c7-b1de-6b2b91d95e57)

### Reproduction frequency

100%

**Comment by Mirsario** [comment]
Let me know if there's anything else similar in TML GUIs, and if the issue occurs on mod GUIs - they're lacking a Recalculate() call. We've had a problem that caused excessive recalculations to occur in the backgrounds every frame, thus resulting in us over-relying on this misbehavior.

**Comment by I-am-Plague** [comment]
This is still an issue
![image_2024-01-28_004149341](https://github.com/tModLoader/tModLoader/assets/141450109/5436ffa9-6be7-44f1-bda0-65f54967ec4d)

**Comment by I-am-Plague** [comment]
to anyone who wants a quick fix before they fix it, just go into windowed mode and shrink your screen until it's fixed, but you'll need to shrink the screen every time you want to delete a mod

**Comment by Mirsario** [comment]
The fix has unfortunately not been cherrypicked to stable mid-month, await 2nd February. A better workaround is using Shift+Click on the trash icon, which skips the popup altogether.
