### ISSUE TITLE
404 error for Pastebin links in "Terraria-Specific C# Crash Course" google doc 

### ISSUE THREAD

**Issue by neitt0** [bluemagic123/tModLoader#4011]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Steps to reproduce

1. Open "Quick Terraria-specific C# crash course" Google doc
2. click on any pastebin.com links

### Expected Behavior

Expected to see the pastebins' content

### Actual Behavior

Displays "Not Found (#404)"

### Reproduction frequency

Everytime

**Comment by Rijam** [comment]
That Google doc is not affiliated with tModLoader, thus this is not the place to report that issue.

Check the tModLoader wiki and Example Mod for official tModLoader resources: https://github.com/tModLoader/tModLoader/wiki https://github.com/tModLoader/tModLoader/tree/stable/ExampleMod

**Comment by JavidPack** [comment]
I've updated the 2 links from this wiki with warnings about how the guide is now broken. I can't find any way to recover those lost pastebins. Something directly on the wiki might be useful in the future.
