### ISSUE TITLE
Add a loadout-typed system to "Manage Mods"

### ISSUE THREAD

**Issue by neitt0** [bluemagic123/tModLoader#4012]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

tModLoader code as a Contributor/Maintainer

### Description

As a recently joined modder in the TML community, I find that I every time I want to work on my mods, I would have to enable/disable each individual mods that I want active for my work. And if I want to play mods made by other people, I would have to repeat the process all over again, and it can be tedious if you have a many mods downloaded. I suggest implementing a feature where players can select which mods they want to enable and group it together into a "loadout" where players can click a button and all mods selected in the loadout will be enabled and the rest is disabled.

![image](https://github.com/tModLoader/tModLoader/assets/114895619/bec48fb6-e8a0-442d-b63d-98a4e3cece24)

### What does this proposal attempt to solve or improve?

This suggestion attempts to eliminate the tedious process that players faces when switching between different content mods making it a smoother user experience.

### Which (other) solutions should be considered?

Add an "always-enabled" button next to the "enable" button to keep that mod from being disabled when the player clicks "Disable All."

**Comment by direwolf420** [comment]
Is the Mod Packs feature in the Workshop menu not sufficient?

**Comment by neitt0** [comment]
Oh, is that what it is used for?
