### ISSUE TITLE
Attempting to publish mod not owned by user has misleading error messages

### ISSUE THREAD

**Issue by wd30x** [bluemagic123/tModLoader#4014]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Whenever I try to publish any mods, error occurs.
Error Code: k_EResultFail
Steam workshop log shows: Failed to initialize build on server (Access Denied) 
but I don't really understand what it means.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13866042/client.log)

workshop_log.txt:
[2024-01-09 04:58:22] [AppID 1281930] Subscribed to item 2831584883
[2024-01-09 05:00:33] [AppID 1281930] Starting Workshop download job (  verifying)
[2024-01-09 05:00:33] [AppID 1281930] Update canceled: Priority (Suspended)
[2024-01-09 05:00:34] [AppID 1281930] Starting Workshop download job (  verifying)
[2024-01-09 05:00:34] [AppID 1281930] Running full workshop file validation
[2024-01-09 05:00:37] [AppID 1281930] Finished Workshop download job : No Error
[2024-01-09 05:02:19] [AppID 1281930] Subscribed to item 2831584883
[2024-01-09 05:02:27] [AppID 1281930] Subscribed to item 2831584883
[2024-01-09 05:02:51] [AppID 1281930] Subscribed to item 2831584883
[2024-01-09 05:02:54] [AppID 1281930] Upload starting for workshop item 2831584883 by AppID 1281930

> [2024-01-09 05:02:54] [AppID 1281930] Upload workshop item 2831584883 failed (Failed to initialize build on server (Access Denied) )

[2024-01-09 05:02:55] [AppID 1281930] Subscribed to item 2831584883

### Steps to reproduce

1. Build and reload any mod
2. Publish

### Expected Behavior

The mod should be published in the workshop

### Actual Behavior

Failed to publish the item to steam! Error Code: k_EResultFail

### Reproduction frequency

100%

### Additional Information

This is my first time uploading item to steam workshop.

**Comment by PlazmaKG** [comment]
I can't download any mods from the workshop either, and going into the mod browser crashes the game.

I assume these are related.

**Comment by JavidPack** [comment]
So, according to the logs, it seems like you are trying to update this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2831584883, is that right? You said publish, not update, so I'm a bit confused. 

Is that your mod? If it is, it should work, but if it isn't, you might want to try naming your mod something unique, not `newmod`.

**Comment by wd30x** [comment]
> So, according to the logs, it seems like you are trying to update this mod https://steamcommunity.com/sharedfiles/filedetails/?id=2831584883, is that right? You said publish, not update, so I'm a bit confused.
> 
> Is that your mod? If it is, it should work, but if it isn't, you might want to try naming your mod something unique, not `newmod`.

I am not trying to update as I have not successfully published any mod yet.

The reason why its called **newmod** is because this is a mod I newly created for testing purpose by built-in create mod function of tmodloader, as I am new to modding.

I have no idea why it has the same id as another mod in workshop. (This is weird.)

**Comment by JavidPack** [comment]
I see, in the past this situation used to say "Error: Mod already exists on Workshop!", but for some reason that isn't showing correctly at this time. The issue is the name `newmod` is already taken by another mod on the workshop. Every mod on the workshop must have a unique name, you can't use a name someone has already made. 

Also, just so we are clear, you mentioned this is a test mod. You don't need to publish mods to test them. Publishing mods is for when you want others to use the mod.
