### ISSUE TITLE
Make menu themes persist on restart

### ISSUE THREAD

**Issue by PlazmaKG** [bluemagic123/tModLoader#4015]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Make the "Change Menu Theme:" option that users can change on the main menu persist between game restarts.

### What does this proposal attempt to solve or improve?

It aims to have a customization option persist. It's kind of a useless feature otherwise

**Comment by JavidPack** [comment]
I just tested with the ExampleMod menu and it restores itself as the selected menu once mods load. I think the feature is working as intended. (I don't think the vanilla menu options (1.3 terraria logo, 1.4 terraria logo) are intended to restore automatically since those are basically easter eggs, only modded menus.)

**Comment by PlazmaKG** [comment]
When I set the munu theme to "Journey's End" instead of tModLoader, it does not persist.

I want the vanilla logo rather than tmodloader one.

Maybe it's an easter egg but it seems like it'd be cool if it persisted rather than defaulting to a mods menu or the tmodloader one on every startup.

**Comment by steviegt6** [comment]
I believe the intended behavior has always been to not save the vanilla logos, but I'd also prefer saving the Journey's End logo at the very least (not saving the 1.3 logo is fine to preserve the easter egg). +1

**Comment by JavidPack** [comment]
@Chicken-Bones Does this seem fine? Allowing the Journeys end menu selection to persist.

**Comment by Chicken-Bones** [comment]
Yes, just have to make sure that the current behavior is maintained when a modded menu was selected. Please test reloading, as well as skip loading on startup (hold shift). I'm not sure whether the latter clears the selected menu currently.

**Comment by steviegt6** [comment]
Has work been started on this? I'd be happy to make a PR if it hasn't.

**Comment by JavidPack** [comment]
> Has work been started on this? I'd be happy to make a PR if it hasn't.

I have not seen anyone work on this, so it should be open for you to implement.

**Comment by Metratrj** [comment]
I have a solution, will open a pr now /claim
