### ISSUE TITLE
"./manage-tModLoaderServer.sh install-tml --github" command does not install the release available on Steam

### ISSUE THREAD

**Issue by vorezal** [bluemagic123/tModLoader#4023]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The documentation for the command "./manage-tModLoaderServer.sh install-tml --github" states that it will install the same version available on Steam. Running this command (as of today) installs v2023.12.2.5 instead of v2023.11.3.3, which is the current version available on Steam.

### Steps to reproduce

1. Run "./manage-tModLoaderServer.sh install-tml --github"

### Expected Behavior

The management script should install the same version of tModLoaderServer that is available on steam.

### Actual Behavior

The script installs a more recent version, not yet available on steam.

### Additional Information

It looks like this command should instead pull the latest stable release rather than the latest preview release to match the behavior in the documentation. Perhaps the present behavior can be maintained, documentation updated to describe how it actually is working, and --tml-version could be extended to support pulling latest stable or preview rather than only allowing specific versions? That would prevent any breaking changes in case some are depending on the current behavior.

**Comment by JavidPack** [comment]
Looking at the code, it seems it's just finding the first result in <https://api.github.com/repos/tModLoader/tModLoader/releases> instead of checking for the first result marked `"prerelease": false,`. 

Sounds correct to fix the behavior. I'm not sure at this time the best approach to parsing that info in a sh file, but we'll figure it out. Thanks for the report.

**Comment by Chicken-Bones** [comment]
Fixed by [3900](https://github.com/tModLoader/tModLoader/pull/3900)
