### ISSUE TITLE
delete file button bug

### ISSUE THREAD

**Issue by BrenoS93** [bluemagic123/tModLoader#4024]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

[https://www.youtube.com/watch?v=9k0V8IUiB64](url)

### Log File

log files https://drive.google.com/drive/folders/1kgOCAfv2v1qkK8Rv1VSHN3WM1NcD0tYs?usp=sharing

**Comment by Chicken-Bones** [comment]
@Mirsario

**Comment by JavidPack** [comment]
This is fixed in 2023.12 stable, which is current stable as of February.
