### ISSUE TITLE
Mod Icons Deload After Every Mod download

### ISSUE THREAD

**Issue by OverlordEclipse** [bluemagic123/tModLoader#4029]
### Version

Latest 1.4.3-legacy

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After downloading a mod from the workshop page, every single mod icon disappears until a workshop reload.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13937475/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/13937476/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13937477/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13937478/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/13937479/terrariasteamclient.log)

### Steps to reproduce

1. Boot up tModLoader 1.4.3 - Legacy beta
2. Go to Workshop
3. Go to Download Mods
4. Download any mod
5. When the workshop loads back, all mod icons have disappeared

### Expected Behavior

That the mod icons don't disappear after a mod download

### Actual Behavior

Mod icons disappear after a mod download

### Reproduction frequency

100%, literally havent had it not happened since i decided to start playing again after a while.

### Additional Information

![20240115015254_1](https://github.com/tModLoader/tModLoader/assets/109188827/a9db0691-cfa8-4f40-a08f-e398c91c7f4d)
![20240115015259_1](https://github.com/tModLoader/tModLoader/assets/109188827/6ce67e77-ba48-46ff-8ec9-b08a22727ba9)
![20240115015303_1](https://github.com/tModLoader/tModLoader/assets/109188827/37f812ef-eec3-4782-9a5d-2afa05ef0fc6)

**Comment by JavidPack** [comment]
Thanks for the report. Since this bug is purely cosmetic and since 1.4.3 tModLoader is legacy and not receiving any non-critical/compatibility updates anymore, we will not be fixing this issue. I tested in current stable tModLoader and it is working as intended, so once you make your way to stable tModLoader you won't have this issue anymore.
