### ISSUE TITLE
Running the downloaded mod page abnormally can cause a crash.

### ISSUE THREAD

**Issue by Bei-Ning** [bluemagic123/tModLoader#4034]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Running the downloaded mod page abnormally can cause a crash. I haven’t enabled any mods。and the mods I subscribed to on Steam’s workshop did not download automatically.
在我打开下载界面时他的ui出现错位并且我点击任何按钮都会发生崩溃，我没有开启任何mod，我在steam创意工坊订阅的mod也并没有自动下载。

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13996681/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13996682/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13996683/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13996684/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/13996685/terrariasteamclient.log)
![PixPin_2024-01-20_12-18-50](https://github.com/tModLoader/tModLoader/assets/120180884/b6c85f0b-d051-4438-bfce-b1e6e1ea0fb1)
![PixPin_2024-01-20_12-19-34](https://github.com/tModLoader/tModLoader/assets/120180884/072f5a88-8464-4a80-ba3f-125212603f72)

### Reproduction frequency

I can reproduce this problem every time and it still exists.

**Comment by Bei-Ning** [comment]
I have this problem when I start from Steam, but it works fine when I start from the desktop shortcut.

**Comment by JavidPack** [comment]
Thanks for the report, I haven't been able to replicate this issue yet, but we might be able to figure out some ways of preventing the error message.

[1b82137](https://github.com/tModLoader/tModLoader/commit/1b8213742dbd067ddd8d37e45ad0dd212fbdfe62) might fix this, we'll need to test preview next month to see.

**Comment by JavidPack** [comment]
The mentioned fix is live in 2024.01. I'll assume this issue is fixed, reopen if the issue persists.
