### ISSUE TITLE
Joining via IP causes reloading mods despite having the exact same mods as the server.

### ISSUE THREAD

**Issue by Itsappuru** [bluemagic123/tModLoader#4041]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder
Accidentally set it as this, but as the other selection, player not modder

### Description

Literally just the title, I can't join them as well because its stuck on this screen after reloading, however joining through steam did fine, same with an old version
![image](https://github.com/tModLoader/tModLoader/assets/106469120/d0a03f6c-a3f6-4ec3-b9aa-f4cdab5cf52b)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14024177/client.log)

### Steps to reproduce

Just join a server with a bunch of mods with the same version mods, but possibly unable to be recreated since my friend was able to join the server

### Expected Behavior

Join the server

### Actual Behavior

Unloads the mods then reloads it, after reloading, it doesn't join

### Reproduction frequency

Always

### Additional Information

not really, changed my windows username to Username instead

**Comment by JavidPack** [comment]
This is likely due to a difference in configs for the various mods. I'll look into adding more log messages so in the future it is clearer why this is happening.

(Some config changes require a mod reload if they differ from what was originally loaded)

**Comment by Jacklz** [comment]
Could this be similar to [3674](https://github.com/tModLoader/tModLoader/issues/3674)? At least your second issue of not being able to join. This mod [longer time-outs](https://steamcommunity.com/sharedfiles/filedetails/?id=3120572076) extends the default time-out length to prevent getting stuck on this screen. So if you encounter a lengthy mod reload, you can still join the server.

**Comment by JavidPack** [comment]
Just in case anyone comes here with a similar issue, we are currently beta testing a rework of the mod syncing system that will be live come April. These issues should be solved by this rework, but we do encourage users to do some testing on the beta. 

The following is the announcement that was made on steam:

**Important Feature in Preview:** This month we will be testing a major rework of how mods are loaded and synced on the `preview-v2024.02` beta branch. When joining a server, a new menu will inform the user about pending mod downloads and config changes.  

**Modders** should read the *How does this affect modders?* section of the [pull request](<https://github.com/tModLoader/tModLoader/pull/3822>). 

**Users** will be happy to know that local mods will no longer override workshop mods, reducing potential errors from loading outdated mods significantly. The new UI will greatly help users avoid lengthy mod reloads in multiplayer. See [this video](<https://github.com/tModLoader/tModLoader/pull/3822#issuecomment-1958116726>) to see the new UI in action. We hope to perfect this user experience in anticipation for next months release.

**Comment by JavidPack** [comment]
New approach should fix these issues and is in Stable already.
