### ISSUE TITLE
tmodloader crashes on trying to fullscreen

### ISSUE THREAD

**Issue by Alfredoes234** [bluemagic123/tModLoader#4051]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When I try to full screen the game it crashes and I have tried methods such as changing the resolution but yet it does not work. I have also tried setting the resolution in the config (1920x1080 which is my desktop resolution) but it said it was capped at something like 1920x1200 and then crashes. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14167692/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14167693/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14167694/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14167695/Natives.log)

### Steps to reproduce

1. Launch game 
2. Go to settings
3. Go to graphics settings 
4. Go to resolution
5. Try to full screen

### Expected Behavior

Should be able to select 1080p as a resolution and be able to full screen without crashing

### Actual Behavior

Keeps crashing when trying to change the resolution and or fullscreen

### Reproduction frequency

Happened each time I tried to Fullscreen and changing the resolution did not work

**Comment by JavidPack** [comment]
Looks like you should follow bullet 2 in this section <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#check-nativeslog>

Your client.log also mentions that some files are missing, these should fix themselves if you follow the fresh install instructions for both terraria and tModLoader. If they don't, find them in the Content folder within Terraria install folder and check if their capitalization is correct:

Images/NPC_517.xnb
Images/Gore_240.xnb
Images/Projectile_179.xnb
Images/Projectile_189.xnb
Images/Projectile_618.xnb
Images/Tiles_650.xnb
Images/Item_2648.xnb
