### ISSUE TITLE
JIT mods on background thread

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#4058]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

We could JIT all mods in parallel with the rest of the loading process, and report the results at the end of loading.

Pros:
- Mod loading takes less time overall.

Cons:
- Errors which are caught in the JIT stage may be thrown as code is naturally executed by loading mod code. 
  - Only one error at a time will show, where JIT collates errors from all methods.
- JIT Errors will come up later in the load process, making a mod seem to work until the final check.

### What does this proposal attempt to solve or improve?

Currently we load mods serially and JITting all the methods in a mod is the first part of loading for each mod. Despite running JIT on multiple parallel threads, it still takes up ~20-30% of load time, and prevents other time consuming operations like asset loading from executing.

### Which (other) solutions should be considered?

We could run the JIT in the background, but still do it on a mod-by-mod basis, and wait for the results at the start of loading each mod if they haven't been computed yet.

This would provide most of the benefit and none of the drawbacks.

**Comment by ghost** [comment]
If i didnt understand, but you could also try to load all mods parralel, and only end the loading screen when they finished, but its still faster, because multiple mods are loading at one time

EDIT: thats probably what was meant.

**Comment by steviegt6** [comment]
> If i didnt understand, but you could also try to load all mods parralel, and only end the loading screen when they finished, but its still faster, because multiple mods are loading at one time

Mod loading isn't thread-safe.

**Comment by ghost** [comment]
> > If i didnt understand, but you could also try to load all mods parralel, and only end the loading screen when they finished, but its still faster, because multiple mods are loading at one time
> 
> Mod loading isn't thread-safe.

Does that exclude the possibility of making them safe?
No.
The Issue talk about "We could JIT all mods in parallel" which is pretty clear to me.
Please hold yourself back before saying stuff like this.

**Comment by steviegt6** [comment]
> > > If i didnt understand, but you could also try to load all mods parralel, and only end the loading screen when they finished, but its still faster, because multiple mods are loading at one time
> > 
> > 
> > Mod loading isn't thread-safe.
> 
> Does that exclude the possibility of making them safe? No. The Issue talk about "We could JIT all mods in parallel" which is pretty clear to me. Please hold yourself back before saying stuff like this.

Thank you for your input! All contributions are valued!
