### ISSUE TITLE
tmod无法启动

### ISSUE THREAD

**Issue by bf321** [bluemagic123/tModLoader#4074]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

无法打开tmodLoader
![屏幕截图(18)](https://github.com/tModLoader/tModLoader/assets/161118042/8fe5acb2-1023-4a1f-a24c-b2a0c0784cf5)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14392256/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14392258/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14392261/Natives.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14392262/environment-client.log)
无server.log 和environment-sever.log

### Steps to reproduce

1启动tmod
2
![屏幕截图(18)](https://github.com/tModLoader/tModLoader/assets/161118042/768ef50b-6e4b-4813-a7bb-742790091f6d)

### Expected Behavior

打开tmod

### Actual Behavior

tmod无法打开

### Reproduction frequency

一天

### Additional Information

无

**Comment by JavidPack** [comment]
The instructions for fixing this issue are found in the FAQ: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#configjson-corrupted

Basically, you can delete the `config.json` file mentioned and it should work. If you have further issues, you should come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). We'll be able to help you directly there.

**Comment by bf321123** [comment]
我也是这个情况请问有没有解决方法我已经困扰好久了
