### ISSUE TITLE
TModLoader crashing on startup due to MonoMod not being able to detect architecture

### ISSUE THREAD

**Issue by mja00** [bluemagic123/tModLoader#4090]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

A recent update to MonoMod has caused TModLoader to no longer boot in containers. This is due to the `/proc/self/auxv` file not being accessible. This was caused by the update to MonoMod in this https://github.com/tModLoader/tModLoader/commit/d053a672f899174f3c043c0f78633ff8ab98d0d0 commit. This most likely will need to be copied upstream for them to fix (feel free to tell me to move the issue there) but I felt as if opening here might allow for people to find the issue as well. 

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/14466693/server.log)
[mmlog.txt](https://github.com/tModLoader/tModLoader/files/14466696/mmlog.txt)

### Steps to reproduce

1. Install TModLoader.
2. Create a container using the `bitnami/dotnet:6` image as non-root. 
3. Run the server using that container and image
4. Server crashes due to `/proc/self/auxv` being root-only. 

### Expected Behavior

Server is able to detect architecture and boot, or fallback to assuming an architecture. 

### Actual Behavior

Server crashes.

### Reproduction frequency

Every startup reproduces this. 

### Additional Information

We just use the raw `bitnami/dotnet:6` image. We attempted to get around it by chmoding the file but Linux unfortunately doesn't allow that.

**Comment by steviegt6** [comment]
Relevant: https://github.com/MonoMod/MonoMod/issues/166
This has already been fixed in a MonoMod release, just needs updating.

**Comment by Chicken-Bones** [comment]
Your log file says you are on tModLoader `2024.01.3.0` which does contain the update in MonoMod/MonoMod#166 and the stack trace confirms as much.

```
System.UnauthorizedAccessException: Access to the path '/proc/self/auxv' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at MonoMod.Utils.Helpers.ReadAllBytes(String path)
```

I will forward your report to the MonoMod developers

**Comment by Chicken-Bones** [comment]
For now, I can recommend using an `alpine` or `ubuntu` image which tML is known to work with. Please note that tML provides a `Dockerfile`, server management script and readme in `DedicatedServerUtils` folder in each release.

You can read more at https://github.com/tModLoader/tModLoader/tree/1.4.4/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils

**Comment by mja00** [comment]
I'll give that image a test tomorrow when I can. It looks like those scripts don't start the container as non-root which might be why you've never noticed it exhibit the same issue. This seems to be a permission issue inside the container as `/prov/self/auxv` is root read only. I'll also try creating some decent reproduction steps with docker commands for y'all.

**Comment by mja00** [comment]
Turns out it's solely limited to `bitnami/dotnet` images, which was fun to figure out. Their images don't create *any* users in the container so perms get screwed up. Appreciate you guys looking into it.

**Comment by Chicken-Bones** [comment]
@mja00 would you be able to send me a DM on Discord (Username `chickenbones`)? We have a new version of the library that should work on bitnami images, so we'd like you to test for us.

**Comment by mja00** [comment]
Sure thing.
