### ISSUE TITLE
When shooting a gun and switching directions, the position of the gun is misaligned for a split second

### ISSUE THREAD

**Issue by ilija04** [bluemagic123/tModLoader#4104]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When I change directions when shooting a gun, the gun appears misaligned for a split second. This is really noticeable when constantly switching left and right while shooting up. I tested this with no mods and I did test this in vanilla Terraria, and it does not happen there. I did check the logs and there was nothing there, so I don't think it is necessary to send them. Happens on both stable and preview.
![Capture](https://github.com/tModLoader/tModLoader/assets/69620440/57883b4e-cca8-49c5-8a1b-25892b1cfc99)

### Steps to reproduce

1. Take any kind of gun, like Minishark, and shoot it
2. Move the cursor left and right while shooting up
3. The gun will show up misaligned for a split second

### Expected Behavior

The gun should not be misaligned at all when switching directions

### Actual Behavior

The gun is misaligned for a split second

### Reproduction frequency

Always

### Additional Information

This does not happen only to guns. It also happens with magic guns and most other ranged weapons.

**Comment by JavidPack** [comment]
Thanks for the report.
