### ISSUE TITLE
ExampleMod's Example dye crashes the game upon equipping on Preview branch

### ISSUE THREAD

**Issue by CoreMod** [bluemagic123/tModLoader#4130]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player / Modders

### Description

After equipping the example dye is a visible slot, the game crashes.
After the addition of the ShaderData constructor in preview, it seemed to have broken loading example dye's shader even after its code was updated to reflect the new changes. This issue does not occur on stable.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14733815/client.log)

### Steps to reproduce

1. Load & enable ExampleMod as the only mod
2. Load a world
3. Equip example dye onto a visible armor piece/accessory

### Expected Behavior

The dye applies its shader to the equipped part as intended.

### Actual Behavior

The game crashes.

### Reproduction frequency

It occurs every time the dye is equipped to a visible slot.

**Comment by JavidPack** [comment]
Thanks for the report, fix should be live soon.
