### ISSUE TITLE
TileDefinitions fail to retrieve display name when loaded on a server-side config when starting a server

### ISSUE THREAD

**Issue by JuicyJabon** [bluemagic123/tModLoader#4132]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When adding a modded tile to a TileDefinition list inside of a server-side mod config the server will fail to get the display name of the modded tile when starting the server. This occurs even if the mod the tile is from is loaded or not. This also unloads the mod and prompts a file verification on restart of tModLoader.

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/14734358/server.log)

### Steps to reproduce

1. Enable a mod with TileDefinition usage in the config
2. Enable a mod with tiles to add to the first mod's config
3. Add the second mod's tile to the first mod's config
4. Start a multiplayer server
5. The first mod should fail to get the second mod's tile display name and unload
6. Server loads with only the second mod enabled

### Expected Behavior

Expected behavior is the server should ignore the unloaded tiles.

### Actual Behavior

Actual behavior is the server config is attempting to get display names from an unloaded tile, promptly failing.

### Reproduction frequency

100% of the time.

This issue is only reproducible when hosting a multiplayer server. This is not an issue for singleplayer and works as intended there.

### Additional Information

Requires 2 mods enabled at minimum and one of them has to have TileDefinition usage inside the configuration, and the other has to have tiles.

**Comment by JavidPack** [comment]
The error came from map entries being accessed by the TileDefinition.DisplayName. Map entries aren't loaded on servers so code was added to fallback to the normal entry.
