### ISSUE TITLE
Invisible cursor on "Download and Continue" page

### ISSUE THREAD

**Issue by Jadams505** [bluemagic123/tModLoader#4145]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When joining a multiplayer world and receiving the new download mods menu the mouse cursor will disappear if the player was holding the sun when the page opened.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14829681/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/14829692/server.log)

### Steps to reproduce

1. Join a multiplayer server with mods you do not have (to receive the menu).
2. While the "Joining [Player name] ..." text is displayed, click and hold the sun/moon.
3. When the menu appears you can release and the mouse will be invisible.

### Expected Behavior

The mouse should be visible.

### Actual Behavior

The mouse is invisible. You can still click, but the cursor is not being drawn.

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Thanks for the report.
