### ISSUE TITLE
Localization Live Updating not working

### ISSUE THREAD

**Issue by nubiaskting** [bluemagic123/tModLoader#4147]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Localization Live Updating not work...

### Log File

[environment-client.log](https://github.com/tModLoader/tModLoader/files/14835351/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14835352/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14835353/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/14835354/client.log)

### Steps to reproduce

![스크린샷 2024-04-02 193914](https://github.com/tModLoader/tModLoader/assets/116342485/bcccb624-cedc-4fe1-bbf8-9a0b23f56d9f)
![스크린샷 2024-04-02 193929](https://github.com/tModLoader/tModLoader/assets/116342485/6664a001-4a4c-4d97-86a6-1ba8f20b72e1)
![스크린샷 2024-04-02 194001](https://github.com/tModLoader/tModLoader/assets/116342485/495a607a-0c20-4acb-9a0d-75af86145171)

### Expected Behavior

localiztion..

### Additional Information

Localization

**Comment by JavidPack** [comment]
Thanks for the report.

**Comment by nubiaskting** [comment]
It still doesn't seem to be fixed...
