### ISSUE TITLE
New mods do not load on server

### ISSUE THREAD

**Issue by erzoelmatador** [bluemagic123/tModLoader#4157]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When using the server.bat file to boot up a server. The new mods do not get added. The only mods enabled on said server are from the previous update. For example, mods like Dart Guns Plus and Calamity Wrath of the Gods do not get added along with other mods such as Calamity Community Remix. It also prevents nulceus co op which sucks.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14926956/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14926958/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14926960/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/14926961/server.log)
[environment-server.log](https://github.com/tModLoader/tModLoader/files/14926969/environment-server.log)

[server2.log](https://github.com/tModLoader/tModLoader/files/14926966/server2.log)
[environment-server2.log](https://github.com/tModLoader/tModLoader/files/14926970/environment-server2.log)

### Steps to reproduce

1. Launch TModloader normally or via the bat file
2. Launch the server after all mods are downloaded via .bat file 
3. try and join server 

### Expected Behavior

Should not ask for mods to be disabled or downgraded.

### Actual Behavior

Mods are disabled, and my friend had some mods downgraded.

### Reproduction frequency

It has been going on since the April update

### Additional Information

unable to use "host & play", it gets stuck at starting server. Also Mods list for server seems to stay the same most of the time like its disconnected from steam workshop. Extra note, have reinstalled and verify files on both terraria and tmodloader

**Comment by JavidPack** [comment]
I checked Dart Guns Plus and it just isn't programmed correctly, so it won't work. This is also mentioned on their workshop page https://steamcommunity.com/sharedfiles/filedetails/?id=3204841848

![image](https://github.com/tModLoader/tModLoader/assets/4522492/2f0742c4-8876-4aa1-865b-e2d27d22e7f7)

Basically, if a mod doesn't load on the server, you'll just have to disable them, they just don't work and won't work. This is not a tModLoader issue, so I'll be closing this. If you need to learn how to diagnose issues with your mods, read this: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#reading-clientlog
