### ISSUE TITLE
Missing Dependencies On Launch Issues

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#4165]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

![image](https://github.com/tModLoader/tModLoader/assets/59670736/a28c3b73-e69b-470e-8a59-1c5e9f60ef59)

Missing some sort of flavor text as to what is the missing dependency?
Or is it bugged? 

Also seeing a lengthy black screen on startup when this happens - not clear what game is doing which would confuse someone

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14980133/client.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14980136/Natives.log)

**Comment by direwolf420** [comment]
The same thing happens on stable too
I think the issue here is that the UIs  for "recently updated mods" and "dependencies that need to be downloaded" are mixed together somehow. I just had the same window pop up with Luminance, which is a new library for Infernum Mode

**Comment by steviegt6** [comment]
It's a result due to tweaks made to my original dependency downloading stuff. I'm not sure if the faulty dependency prompting bug was always present in the PR, but somewhere along the way another contributor or developer removed the message that's supposed to show alongside it.

**Comment by JavidPack** [comment]
Should be fixed. `ModOrganizer.IdentifyMissingWorkshopDependencies()` still takes a good moment of time during the game launch, not sure if we can do anything about that while keeping the feature though.
