### ISSUE TITLE
Asset could not be found: "Terraria.ModLoader.UI.ButtonDeps

### ISSUE THREAD

**Issue by 148481** [bluemagic123/tModLoader#4166]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

[Main Thread/WARN] [tML]: 静默捕获异常: 
ReLogic.Content.AssetLoadException: Asset could not be found: "Terraria.ModLoader.UI.ButtonDeps"

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14982012/client.log)

### Steps to reproduce

![image](https://github.com/tModLoader/tModLoader/assets/167117754/07cc2740-0464-4d79-bede-759cfefccffc)
![image](https://github.com/tModLoader/tModLoader/assets/167117754/7d867e6f-28df-4a37-84b6-0f5942da0c2a)

### Reproduction frequency

The first time it happened, the game actually worked a little while ago, and then he seems to automatically update something, and then it doesn't work.

**Comment by Rijam** [comment]
Fixed in https://github.com/tModLoader/tModLoader/commit/892a5e95d83b77c57e4587fd7fa7e3a3c33822de

Reminder: You shouldn't be using Preview to play as a player. Preview can break suddenly just like this.
