### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by azlognysh** [bluemagic123/tModLoader#4179]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

cmd弹出后快速消失，但tmodloader无法打开
附上录屏
[新建压缩.zip](https://github.com/tModLoader/tModLoader/files/15104224/default.zip)

### Log File

[environment-server.log](https://github.com/tModLoader/tModLoader/files/15104248/environment-server.log)
[server.log](https://github.com/tModLoader/tModLoader/files/15104249/server.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/15104250/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/15104251/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/15104252/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/15104253/environment-client.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/15104254/terrariasteamclient.log)

**Comment by JavidPack** [comment]
According to natives.log, there seems to be an issue with audio. Try some of these suggestions <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#audio-troubleshooting>

**Comment by azlognysh** [comment]
已解决，https://github.com/tModLoader/tModLoader/issues/2863#issuecomment-1221975856有效
