### ISSUE TITLE
Detect and Warn if modder is debugging or building a mod that won't be selected to load due to version number

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#4181]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Sometimes a modder will clone a mod git and try to debug, only to be confused as their changes do not take effect. The latest report of this is a modder cloning the main branch that had 0.6 as the build, but steam had a 0.6.1.1 version published. This is either because the author had not pushed some local changes yet or the changes to build.txt were on another branch.

This also happens for modders confused about Version, for example a modders changing v0.200 to v0.3, thinking it is a higher version.

It would be useful to warn of this issue. It might be possible to to detect this when debugging directly. If not, build and reload could warn of this issue. The warning should be full page, as this is definitely a mistake and probably never intentional.

**Comment by Chicken-Bones** [comment]
`AssemblyManager` uses the following code to support debugging mods with edit and continue. We could pull the condition into `LocalMod`.

Note that if the user is the one that published the mod, and the published version was built via VS, the workshop mod may also have a pdb in the eac path.

I'm not sure there's an easy way to detect if the supplied symbols don't match in that case, but we could also use file creation date . If the local copy is debuggable, and has a newer creation date than the workshop one, and isn't selected...

```cs
					assembly = Debugger.IsAttached && File.Exists(properties.eacPath) ?
						LoadAssembly(modFile.GetModAssembly(), File.ReadAllBytes(properties.eacPath)): //load the unmodified dll and EaC pdb
						LoadAssembly(modFile.GetModAssembly(), modFile.GetModPdb());
```
