### ISSUE TITLE
If I run the game through TModLouder in Task Manager, it shows up as a blue square with the process name .NET Host . Change the image(To Terraria Image) and the process name in Task Manager to Terraria.exe

### ISSUE THREAD

**Issue by 666MisterFreeman999** [bluemagic123/tModLoader#4187]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I really don't like that when we run the game through TModLauder, the Task Manager shows not Terraria.exe, but a blue square with the process name .NET Host and not Terraria.exe, and it's annoying.
Dear TModLouder creators, could you please make it so that when you start the game through TModLouder the process name in Task Manager is displayed as Terraria.exe and there is a picture of Terraria, and I'm sure most people like me don't like it, because I'm used to closing most games through Task Manager and I don't always remember that if I start Terraria(TModLoader) it is displayed in Task Manager as Blue Square with Process Name .NET Host Please rename it to Terraria.exe.
![Terraria TModLoader 1](https://github.com/tModLoader/tModLoader/assets/168421378/e42929aa-1f22-40a9-95c9-710329391bb5)
![Terraria TModLoader 2](https://github.com/tModLoader/tModLoader/assets/168421378/318dc1ed-2541-4f29-9547-196cf61d80ed)

### What does this proposal attempt to solve or improve?

It's a small change, but most people will like it and find it convenient.

**Comment by 666MisterFreeman999** [comment]
This idea can be realized by making a separate installer patch so that people who need it could download and install it and everyone would be happy.

**Comment by JavidPack** [comment]
I've looked into this a bit today and it seems it is not possible, unfortunately. tModLoader differs from Terraria in how the game is launched. The approaches we need to use prevent us from editing the game from showing up as ".Net Host", but you can expand the window to see Terraria if you ever have multiple ".Net Host" and need to find tModLoader.

![image](https://github.com/tModLoader/tModLoader/assets/4522492/afc4bae0-09f0-462b-95e1-4d289fd3134b)

I'm not sure why you are closing programs through task manager, that is usually a last resort. You can close the game any number of the usual ways, pressing Exit on the main menu, clicking the X button button at the top right corner, right clicking on the game in the task bar and clicking "close window", or even just pressing Alt+F4. 

![image](https://github.com/tModLoader/tModLoader/assets/4522492/ced30460-14e6-4010-be65-f78981c34df9)

**Comment by 666MisterFreeman999** [comment]
Well, who likes it that way and closes games or programs It's a matter of convenience and habits.
You could just change the name of your process from .Net HOST to Terraria.exe and all problems would be solved.
But as you wish, I just created this topic with a request I understood My request was rejected

**Comment by steviegt6** [comment]
tModLoader is distributed as an assembly and uses the default .NET host (`dotnet`) rather than a dedicated app host (`tModLoader.exe`). This is done to facilitate custom start scripts and conditions, as well as to ensure consistency cross-platform. As such, it will be listed under the .NET Host process in Task Manager *because the window & process are spawned from .NET Host*. There is no "[changing] the name of [the] process."

Also, you absolutely should not be exiting tModLoader by manually killing the process (and you should prefer not exiting with the window close ('x') button, that is a degradation from the .NET 5/FNA port and is not in line with vanilla Windows behavior).
