### ISSUE TITLE
Can not launch server in dotnet_version=8.0.0

### ISSUE THREAD

**Issue by CloudChaan** [bluemagic123/tModLoader#4191]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

I have finished dotnet update, but server still can not launch on my ubuntu server and ./start-tModLoaderServer.sh exit without any Exception or error.
This is running log:
Steam>app_update 1281930 validate
 Update state (0x5) verifying install, progress: 0.44 (687364 / 155463601)
 Update state (0x5) verifying install, progress: 69.42 (107924320 / 155463601)
 Update state (0x5) verifying install, progress: 5.25 (188104136 / 3585982119)
 Update state (0x5) verifying install, progress: 15.35 (550437870 / 3585982119)
 Update state (0x5) verifying install, progress: 25.33 (908428950 / 3585982119)
 Update state (0x5) verifying install, progress: 34.24 (1227950581 / 3585982119)
 Update state (0x5) verifying install, progress: 44.14 (1582955263 / 3585982119)
 Update state (0x5) verifying install, progress: 53.43 (1916055903 / 3585982119)
 Update state (0x5) verifying install, progress: 61.43 (2202812812 / 3585982119)
 Update state (0x5) verifying install, progress: 71.20 (2553316902 / 3585982119)
 Update state (0x5) verifying install, progress: 80.54 (2887991998 / 3585982119)
 Update state (0x5) verifying install, progress: 89.84 (3221533763 / 3585982119)
 Update state (0x5) verifying install, progress: 99.55 (3569984204 / 3585982119)
Success! App '1281930' fully installed.

Steam>exit
root@VM-16-12-ubuntu: /Steam/steamapps/common/tModLoader# ./start-tModLoaderServer.sh
Use steam server (y/n): n
You are on platform: "Linux" arch: "x86_64"
Logging to /root/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Fixing Environment Issues
Success!
Verifying .NET....
This may take a few moments.
Parsing .NET version requirements from runtimeconfig.json
Success! dotnet_version=8.0.0
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/root/Steam/steamapps/common/tModLoader/dotnet"
Attempting Launch...
Launched Using Local Dotnet. Launch command: "/root/Steam/steamapps/common/tModLoader/dotnet/dotnet" tModLoader.dll "-server -config serverconfig.txt"
root@VM-16-12-ubuntu: /Steam/steamapps/common/tModLoader#

### Log File

[logs.zip](https://github.com/tModLoader/tModLoader/files/15173917/logs.zip)

**Comment by CloudChaan** [comment]
root@VM-16-12-ubuntu:~/Steam/steamapps/common/tModLoader# "/root/Steam/steamapps/common/tModLoader/dotnet/dotnet" tModLoader.dll "-server -config serverconfig.txt"
Error:
  An assembly specified in the application dependencies manifest (tModLoader.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '13.0.3'
    path: 'lib/net6.0/Newtonsoft.Json.dll'

**Comment by direwolf420** [comment]
> to those playing native on linux (for some reason), if your tModLoader does not launch when clicking "Play" after updating: browse the game's local files, delete the "Libraries" folder, and verify integrity of files. happened to me earlier where an error showed that tModLoader can't find a .NET dependency (Newtonsoft.Json).

**Comment by KennethHoff** [comment]
>for some reason

:<

**Comment by KennethHoff** [comment]
>showed that tModLoader can't find a .NET dependency (Newtonsoft.Json).

Goes to show that it should swap over to System.Text.Json ;)

**Comment by drunken-dwarf** [comment]
Same issue as in https://github.com/tModLoader/tModLoader/issues/4190
@kode54 analyzed the issue and found the underlying problem.

The quick fix suggested here and in the above tickets both work until this is resolved properly.

**Comment by JavidPack** [comment]
We've released a couple hotfixes that should resolve this issue, someone with this issue please comment if it is now fixed after testing it once more.

**Comment by KennethHoff** [comment]
I can confirm it's working. However, I did the workaround previously so.. ye.
