### ISSUE TITLE
Localization workflow live updates still don't seem to be fixed...

### ISSUE THREAD

**Issue by nubiaskting** [bluemagic123/tModLoader#4193]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Localization workflow live updates still not working

### Log File

[environment.log](https://github.com/tModLoader/tModLoader/files/15176670/environment.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/15176671/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/15176672/Launch.log)
[client.log](https://github.com/tModLoader/tModLoader/files/15176673/client.log)

### Steps to reproduce

https://github.com/tModLoader/tModLoader/assets/116342485/ca80286d-221b-4ce0-94f4-1b14590537ca

### Reproduction frequency

after the April update

**Comment by JavidPack** [comment]
This was fixed in April, which means it's in Preview for May, and will be in Stable in June. 

We usually want a month in preview to verify the fix, but the fix was pretty simple, I'll see if I can get it into Stable with the other hotfixes sometime today.

**Comment by JavidPack** [comment]
Ok, v2024.03.3.2, release just now, should have this fixed. If you don't see v2024.03.3.2 then run verify game integrity and it should download. 

Give it a test and let me know if it's working for you.

**Comment by nubiaskting** [comment]
finally!!!!! THX!!!!!!!!!!!!!!!!!!!!
![스크린샷 2024-05-02 155242](https://github.com/tModLoader/tModLoader/assets/116342485/f393746b-230f-4e98-b6fa-41c57aa47e44)
![스크린샷 2024-05-02 155236](https://github.com/tModLoader/tModLoader/assets/116342485/6fdd2e90-c142-40fd-b3cf-19e11f814ea8)
