### ISSUE TITLE
.net sdk not registering in tmodloader (still have the “install sdk” screen)

### ISSUE THREAD

**Issue by GuyFunni** [bluemagic123/tModLoader#4200]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

i installed the files, but it still says i need to install them

**Comment by JavidPack** [comment]
Well, you didn't post your logs, so I can't really help. Most likely you installed the 32 bit sdk by accident, or didn't complete the install. Come to discord if you need further help.
