### ISSUE TITLE
.NET SDK not recognised

### ISSUE THREAD

**Issue by Vicerek** [bluemagic123/tModLoader#4202]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Doesn't detect .NET 8.0 SDK even though I have it.

### Log File

[environment-client.log](https://github.com/tModLoader/tModLoader/files/15223959/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/15223960/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/15223961/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/15223962/client.log)

### Steps to reproduce

1. Launch TMod
2. Go to Workshop>Develop Mods

### Expected Behavior

Show mods to build from the mod sources folder.

### Actual Behavior

I get the text that .NET 8.0 SDK has not been detected.

### Reproduction frequency

Always

### Additional Information

I have the environment path variable for C:\Program Files\dotnet
It worked when .NET 6.0 SDK was needed but now it doesn't

**Comment by JavidPack** [comment]
Dotnet isn't in your PATH according to environment-client.log. You might just need to restart, or maybe you installed the wrong dotnet. See the suggestions at https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-developers#net-sdk to verify that it can be found. Come to discord if you have further issues for better help.

**Comment by Vicerek** [comment]
Restatrting did it for me. Thank you verry much for the help.

**Comment by TheSkyFather** [comment]
Hi my dear friend. I recorded a video about this problem. Solved

https://youtu.be/SagJ4sI45lk
