### ISSUE TITLE
Passing through the blocks

### ISSUE THREAD

**Issue by nonxedy** [bluemagic123/tModLoader#4204]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

I founde 2 bugs. First: You cant moving around marble lamp. Second: You can pass through the block up you.

https://github.com/tModLoader/tModLoader/assets/87914821/1b086cae-a8fc-4c6b-a5a6-fe6f0c500e2e

### Log File

[environment-client.log](https://github.com/tModLoader/tModLoader/files/15253866/environment-client.log)
[environment-server.log](https://github.com/tModLoader/tModLoader/files/15253867/environment-server.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/15253868/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/15253869/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/15253870/server.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/15253871/terrariasteamclient.log)
[client.log](https://github.com/tModLoader/tModLoader/files/15253872/client.log)

### Steps to reproduce

1. Place lamp, block, platforms like a photo. (Use hammer)
2. Stand around lamp. You cant moving now
3. Jump. 
![image](https://github.com/tModLoader/tModLoader/assets/87914821/5e50703e-a45c-46e1-9683-0e75664912b9)
 

### Expected Behavior

Nothing, just move, just jump.

### Actual Behavior

You cant moving and you pass through the block up you.

### Reproduction frequency

Its my first time. I was just running by, but I got stuck

**Comment by Rijam** [comment]
Congratulations! You just discovered your first Hoik! Hoiking is a vanilla thing and not necessarily related to tModLoader. With hoiks, you can travel through blocks. What is happening here is that you are getting hoiked up onto the platforms. Your head is now in the two blocks above you which is why you can't move left or right (because there are blocks to your left or right). Jumping or falling through the platforms is the only way out. The Marble Lamp has nothing to do with this.
Read more about hoiks here: https://terraria.wiki.gg/wiki/Hoik

**Comment by nonxedy** [comment]
> Congratulations! You just discovered your first Hoik! Hoiking is a vanilla thing and not necessarily related to tModLoader. With hoiks, you can travel through blocks. What is happening here is that you are getting hoiked up onto the platforms. Your head is now in the two blocks above you which is why you can't move left or right (because there are blocks to your left or right). Jumping or falling through the platforms is the only way out. The Marble Lamp has nothing to do with this. Read more about hoiks here: https://terraria.wiki.gg/wiki/Hoik

I didnt use hoiks

**Comment by Rijam** [comment]
> > Congratulations! You just discovered your first Hoik! Hoiking is a vanilla thing and not necessarily related to tModLoader. With hoiks, you can travel through blocks. What is happening here is that you are getting hoiked up onto the platforms. Your head is now in the two blocks above you which is why you can't move left or right (because there are blocks to your left or right). Jumping or falling through the platforms is the only way out. The Marble Lamp has nothing to do with this. Read more about hoiks here: https://terraria.wiki.gg/wiki/Hoik
> 
> I didnt use hoiks

The thing you showed and did is a hoik.

**Comment by nonxedy** [comment]
> > > Congratulations! You just discovered your first Hoik! Hoiking is a vanilla thing and not necessarily related to tModLoader. With hoiks, you can travel through blocks. What is happening here is that you are getting hoiked up onto the platforms. Your head is now in the two blocks above you which is why you can't move left or right (because there are blocks to your left or right). Jumping or falling through the platforms is the only way out. The Marble Lamp has nothing to do with this. Read more about hoiks here: https://terraria.wiki.gg/wiki/Hoik
> > 
> > 
> > I didnt use hoiks
> 
> The thing you showed and did is a hoik.

I accidentally used it at the last second. But you can go without it.

**Comment by JavidPack** [comment]
Yeah, this can all be replicated in normal Terraria, and isn't something they intend to fix (nor will we, it's a feature at this point). I'll be closing this.
