### ISSUE TITLE
Tmodloader Crashes when opening Develop Mods tab

### ISSUE THREAD

**Issue by Lickeningthyballs** [bluemagic123/tModLoader#4205]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

when i press the develop mods button in workshop menu, tmod dies :(

### Log File

![Screenshot 2024-05-09 180502](https://github.com/tModLoader/tModLoader/assets/100840191/6ea437ff-50df-4180-9cc6-cc4967fb3eb0)

### Steps to reproduce

step 1: Open tmodloader 
Step 2: Go to "Workshop" > "Develop Mods" 
Step 3: Crash :(

### Expected Behavior

Develop mods button actually opening. and developing mods. 

### Actual Behavior

Crash when opening develop mods. 

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
Did you recently edit build.txt? It would be helpful if you can post that file so we know what to test. I have an idea, just want to confirm it's the same issue I think it is.

**Comment by Lickeningthyballs** [comment]
> Did you recently edit build.txt? It would be helpful if you can post that file so we know what to test. I have an idea, just want to confirm it's the same issue I think it is.https://github.com/tModLoader/tModLoader/issues/4205eh

omg thank you so much it was the version text that i had to update and fix inside the build.txt.

**Comment by JavidPack** [comment]
Ok, but I'd like to fix this issue, can you tell me what you had so I can make a fix?

**Comment by Lickeningthyballs** [comment]
> Ok, but I'd like to fix this issue, can you tell me what you had so I can make a fix?

Sure. i went to the build.txt file and updated the verison for a mod im making. 
![image](https://github.com/tModLoader/tModLoader/assets/100840191/67614eda-91dd-4f76-b03d-77aafb87fba0)
Then Tmodloader crashed 100% of the time when trying to open "develop mods"
I couldn't figure out how to fix the issue up until you alerted me about the build.txt file being modified recently. 
I fixed the issue by changing the verison build (version = 0.8.3.3.1) > (version = 0.8.3.4). 
then all is good. 
anymore info you need?

**Comment by Lickeningthyballs** [comment]
Update: 
Tested it with a fresh new mod tested the crash and crash happened again when opening develop mods.

**Comment by JavidPack** [comment]
Thanks, I've added more info on correct version numbers to the wiki and added a fix to a future tmodloader version detecting this issue.

As a reminder to anyone with this issue, versions must be 2 to 4 numbers separated by `.`. https://github.com/tModLoader/tModLoader/wiki/build.txt#available-properties
