### ISSUE TITLE
Lighting Issue Caused by Overriding ModProjectile.DrawBehind

### ISSUE THREAD

**Issue by hezuo1hao** [bluemagic123/tModLoader#4211]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When I override the ModProjectile.DrawBehind function and modify the drawing layer, I notice that the lighting of the Projectile starts behaving oddly.
Specifically, in this scenario, the projectile will use the lightColor around the player instead of the lightColor around the projectile.

### Log File

![dotnet_zHNGYUqxc1](https://github.com/tModLoader/tModLoader/assets/110245158/c6798fe9-9914-4fe8-87ef-931f75014af0)

### Steps to reproduce

1. Override ModProjectile.DrawBehind and modify the drawing layer.
2. Launch projectiles in the game, ensuring a significant difference between the lightColor around the player and the lightColor around the projectile.

### Expected Behavior

The projectile should use the lightColor around itself, not the lightColor around the player.

### Actual Behavior

The projectile is using the lightColor of the player instead of the lightColor around itself.

### Reproduction frequency

100%

### Additional Information

I only override the DrawBehind function during my testing. I suspect that overriding some other drawing-related functions might cause the issue to not reproduce.

**Comment by JavidPack** [comment]
Looks like you need to set `ProjectileID.Sets.DontAttachHideToAlpha[Type] = true;` in SetStaticDefaults.

I'll look into clarifying this in the docs.

**Comment by JavidPack** [comment]
K, fixed in cf679c4994e0aa842926d8a366dd56fae458bcaf, added the docs and fixed the javelin in examplemod to use DontAttachHideToAlpha
