### ISSUE TITLE
GenVars.shimmerPosition consistently stores (0, 0)

### ISSUE THREAD

**Issue by GroguLovesCookies** [bluemagic123/tModLoader#4214]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

GOG

### This bug affects...

Mod capability as a Modder

### Description

GenVars.shimmerPosition does not store the actual position of the shimmer biome.

### Expected Behavior

shimmerPosition should store the x coordinate of the shimmer biome.

### Actual Behavior

Instead, it stores (0, 0).

**Comment by JavidPack** [comment]
Looks like it is assigned in the "Shimmer" pass. As long as your worldgen code is run after that pass, the value should be correct.

If you were trying to access `GenVars.shimmerPosition` outside of worldgen you would need to have your mod save that coordinate within your own ModSystem class in PostWorldGen, it is not saved to the world by the game. Most things in `GenVars` are not saved to the world file, they are only intended to be remembered during world gen.
