### ISSUE TITLE
Wikithis mod not opening default browser in linux

### ISSUE THREAD

**Issue by socket772** [bluemagic123/tModLoader#4223]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

The [Wikithis mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2832487441), has 2 options to where to open the wiki. The first one is in the Steam overlay browser (it works). While the option to open it in an external browser doesn't. I asked the dev on the mod page and he said it could be a bug in tModloader or it could be a missing feature, not sure which one is it.

### Steps to reproduce

1. Set the target browser to external
2. Set the keybind in the config to open the wiki
3. Hover on an item with a supported wiki (copper sword as an example)
4. press the key to open the wiki

### Expected Behavior

When pressing the key to open the wiki of an object, it opens the default browser

### Actual Behavior

Nothing happens.

### Reproduction frequency

Always.

### Additional Information

Arch Linux x86_64
Linux 6.8.9-arch1-2
KDE Plasma 6.0.4
KWin (X11)
Firefox browser from official repo

**Comment by socket772** [comment]
Note, from what i found, you could use xdg-open to have cross distro compatibility.
```bash
# Example in bash
xdg-open https://example.com
```

**Comment by steviegt6** [comment]
The mod uses `Terraria.Utils::OpenToURL`, so seems like a tModLoader bug?
The relevant block is here: https://github.com/BasicallyIAmFox/Wikithis/blob/275201865ec5afdf2a036854aec0c3c8d074e8fa/Data/WikiEntry.cs#L72-L92

**Comment by JavidPack** [comment]
That is strange, I believe we have tested these many times in the past. `Utils::OpenToURL` does use `xdg-open`, so it should work same as links in Terraria. 

Log files would help, please post them. We can't figure this out without them. Post client.log and natives.log

Also try the links in the Develop Mods menu and the links on the main menu bottom left. Let me know which or if any of those work.

**Comment by socket772** [comment]
Ok apparently now it works. I have no idea what changed. Sorry for the time loss.
