### ISSUE TITLE
Version string portion was too short or too long .Net SDK 8 on NixOS

### ISSUE THREAD

**Issue by Abdiramen** [bluemagic123/tModLoader#4231]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

tModLoader throws an error after running `dotnet --list-sdks`.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/15426702/client.log)

I believe the relevant portion of the logs:
```
[02:24:43.215] [Main Thread/DEBUG] [tML]: Found env var DOTNET_ROOT: /nix/store/bdwn4rkqlnx28xa15zk04743sl0zw2jv-user-environment/bin/dotnet
[02:24:43.216] [Main Thread/DEBUG] [tML]: Finding dotnet on PATH failed
[02:24:43.216] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "dotnet" --list-sdks
[02:24:43.308] [Main Thread/INFO] [tML]: 

[02:24:43.319] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
```

### Steps to reproduce

1. Install tModLoader via steam
2. Select Properties and set `DOTNET_ROOT=/nix/store/bdwn4rkqlnx28xa15zk04743sl0zw2jv-user-environment/bin/dotnet %command%`
2. Run tModLoader
3. Click Wrokshop > Develop Mods

### Expected Behavior

Develop Mods menu shows u

### Actual Behavior

I get the `tModLoader.MSNetSDKNotFound` message

### Reproduction frequency

Consistent

### Additional Information

related issue https://github.com/tModLoader/tModLoader/issues/4102

dotnet sdk list sdk value:
```
$ dotnet --list-sdks
8.0.104 [/nix/store/qspynapa7zcyi8mzl9s97mdday9w8q2c-dotnet-sdk-8.0.104/sdk]
```

**Comment by Abdiramen** [comment]
Changed launch options to `DOTNET_ROOT=/nix/store/qspynapa7zcyi8mzl9s97mdday9w8q2c-dotnet-sdk-8.0.104/bin %command%`. I'm still getting the same error though:

[client.log](https://github.com/tModLoader/tModLoader/files/15427168/client.log)

**Comment by Abdiramen** [comment]
Figured it out. I needed to re-install with the steam runtime rather then proton.

**Comment by TheSkyFather** [comment]
Hi my dear friend. I recorded a video about this problem. Solved

https://youtu.be/SagJ4sI45lk

**Comment by Chicken-Bones** [comment]
> Hi my dear friend. I recorded a video about this problem. Solved
> 
> https://youtu.be/SagJ4sI45lk

Please note that while this video may be helpful to some users, we have taken steps to ensure that all dotnet sdk installs on Linux work _automatically_ as much as possible, so installing to specific locations and passing `DOTNET_ROOT` environment variables should not be required.
