### ISSUE TITLE
NPC Strike packet ignores AllowVanillaClients flag

### ISSUE THREAD

**Issue by Cybermaxke** [bluemagic123/tModLoader#4232]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Looking through the tModLoader protocol modifications to the Terraria protocol, I noticed that the NPC Strike logic doesn't take AllowVanillaClients into account. This would result in incorrect packet being sent to vanilla clients when connecting to a tModLoader server.

Refs:
https://github.com/tModLoader/tModLoader/blob/1.4.4/patches/tModLoader/Terraria/NetMessage.cs.patch#L191
https://github.com/tModLoader/tModLoader/blob/1.4.4/patches/tModLoader/Terraria/MessageBuffer.cs.patch#L327

**Comment by JavidPack** [comment]
We actually have retired AllowVanillaClients, this is a good reminder to us to remove it from the code, I'll try to get to that soon.
