### ISSUE TITLE
TML SetUp occur failed-WorldGen.cs

### ISSUE THREAD

**Issue by liuyi13-cpu** [bluemagic123/tModLoader#4238]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

![image](https://github.com/tModLoader/tModLoader/assets/7510080/1c7dd7b3-aaff-43cd-b942-68cbac362a8c)
![image](https://github.com/tModLoader/tModLoader/assets/7510080/929b603c-e100-446e-88f3-bfa64a2669c1)

**Comment by JavidPack** [comment]
I just double checked this and it's working on my end. Are you sure you are on the 1.4.4 branch? Are you sure Terraria.exe hasn't been modified? I would run Verify Game integrity and then make sure to delete any Terraria_v1.4.4.9.exe and TerrariaServer_v1.4.4.9.exe files in the install directory, then try running Setup again.

If you are still having issues, we might need to chat on Discord to resolve this.

**Comment by liuyi13-cpu** [comment]
sorry， my problem ~   
I used  wrong "Terraria.exe".
