### ISSUE TITLE
Crash with attempting to search mods before mod list can load.

### ISSUE THREAD

**Issue by Upsidedowneye** [bluemagic123/tModLoader#4242]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Attempting to search mods in your mod list crashes the game if the game hasn't actually loaded the mod list.

### Log File

[2024-06-01-3.zip](https://github.com/user-attachments/files/15522034/2024-06-01-3.zip)

### Steps to reproduce

Get about 200 mods in your mod list (you don't have to enable them and it can be any mods) (this is only to make it take lots of time to load mods, if you have an alternate solution to make it take forever to load it should work however idk how to test that)
Boot up the game
Cancel mod loading and spam any letter/number on your keyboard
Results

### Expected Behavior

The game refuses to let me type into the search bar before mod list loads OR the game can successfully search mods without crashing even if the mod list isn't loaded yet.

### Actual Behavior

The game crashes

### Reproduction frequency

100% assuming I don't mess up the timing parts of the steps to reproduce.

**Comment by Lurrae** [comment]
I've been experiencing what I assume to be the same crash, though I've encountered it without having to cancel mod loading. It's also not 100% consistent for me; instead, it seems like specific mods cause a main engine crash when I try to search before the mods list is loaded with said mod enabled. So far, I've tested a few mods (with only them and any dependencies enabled) and received the following results:
* No mods = no crash
* Terratweaks (self-built) = crashes
* Block's Info Accessories = no crash
* AlchemistNPC Lite = no crash
* Snek's Misc. Vanity = no crash
* Calamity Mod = crashes
* Spirit Mod = crashes
* Vitality Mod = crashes
* Example Mod = crashes
* Remnants = crashes
* Fargo's Mutant Mod = crashes
* Extended Equipment Loadouts = no crash
* Relics Beget Slots = crashes
* Advanced World Generation = no crash
* The Shop Market = crashes
* Banner Bonanza = no crash
* Aether's Blessing = crashes
* Grappling Hook Helper (self-built) = no crash
* Ore Excavator = crashes

There doesn't seem to be much of a pattern, at least not that I've managed to pick up on. At first I thought it might be tied to mods that have a dependency, but if that were the case very few of the mods I tested would crash, as none of them have dependencies. It's clearly not an issue with self-built mods being enabled either, as most of the mods that crashed are ones I downloaded off of the Steam workshop (and Grappling Hook Helper doesn't cause the crash despite being self-built). My next idea, based on the mention of "UIModItem" and "DrawSelf" in the crash report, was that maybe modded items that override one of the drawing methods are what causes a crash? However, Snek's Misc. Vanity uses draw code for some of its custom items and doesn't crash, and Terratweaks doesn't use draw code and _does_ crash. What's weirder is that mods which don't add _any_ items (more specifically, Ore Excavator) can still crash! Adding an item doesn't guarantee a crash, though; Grappling Hook Helper doesn't cause a crash, after all.
I hope this information on what mods do/don't crash makes it easier to determine what may be going wrong! (Though given the lack of a discernible pattern, I dunno how helpful all of this will be)

**Comment by JavidPack** [comment]
K, I made a fix, if someone affected by this wants to test, there is a build at the bottom here that can be manually installed: https://github.com/tModLoader/tModLoader/actions/runs/9357316622

If we get a report that the issue is now fixed from someone who experienced the issue before, I can look into fast tracking this fix to preview or stable.

**Comment by Jadams505** [comment]
I just tested with the new build. I cannot reproduce the bug anymore. The mods list also loads significantly faster.
