### ISSUE TITLE
Main Engine Crash: Unable to Load LogitechLedEnginesWrapper.dll

### ISSUE THREAD

**Issue by AudiaUser999** [bluemagic123/tModLoader#4244]

**Comment by AudiaUser999** [comment]
I fixed the issue by removing LogitechLedEnginesWrapper.dll

**Comment by partisani** [comment]
Looks like the dll for the dynamic keyboard rgb stuff is missing, try reinstalling tModLoader/Terraria and trying again

**Comment by direwolf420** [comment]
Duplicate of #4241, see the solution linked there
