### ISSUE TITLE
Main engine crash when trying to start TMOD loader

### ISSUE THREAD

**Issue by milkycow77** [bluemagic123/tModLoader#4245]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

I was able to play tmod loader just fine up until the monthly June update and after that any time I try to play I get a message saying "Main engine crash" like in the picture i put below.

### Log File

![Screenshot 2024-06-02 091445](https://github.com/tModLoader/tModLoader/assets/171491944/3e4c21b2-d30c-4e13-af1b-d76b05412b86)
![Screenshot 2024-06-02 090632](https://github.com/tModLoader/tModLoader/assets/171491944/99606eb6-e3aa-4d3d-af3c-fb1a7f56f39e)

### Steps to reproduce

1. open tmod loader
2. wait for it to load
3. receive "main engine crash" error message 

### Expected Behavior

the game should be starting 

### Actual Behavior

game is not starting

### Reproduction frequency

This has happened every time I've opened the game since June 1st

**Comment by Solxanich** [comment]
We are currently trying to test the fix. 
Would you please download the Release Build zip file from https://github.com/tModLoader/tModLoader/actions/runs/9339492903

And perform the following: 
Extract the files in your Downloads Folder. 
In the extracted files, please run 'Start-tModLoader.bat' 
Validate that the game no longer crashes

**Comment by milkycow77** [comment]
How do I download the zip from the link you sent me?

**Comment by Solxanich** [comment]
Should be right at the bottom if you keep scrolling? 
![image](https://github.com/tModLoader/tModLoader/assets/59670736/c382e03e-fc9c-4d4a-b52e-54e1d65c1e21)

**Comment by milkycow77** [comment]
There was no download button for me. I put a screenshot of what my screen
looks like

**Comment by milkycow77** [comment]
I'm sorry I found it by opening it on another browser

**Comment by milkycow77** [comment]
I can't find the file name 'start-tmodloader.bat' Here is a screenshot of
all the files it extracted.

**Comment by Solxanich** [comment]
Just a note that the screenshot you attached doesn't make it on to github issue itself when attached on an email. 
Regardless, should look something like:
![image](https://github.com/tModLoader/tModLoader/assets/59670736/82f820f5-a23d-4ea6-ae9d-521634d58754)
If it doesn't, then Click on View -> Show -> Show File Extensions

**Comment by milkycow77** [comment]
Thank you so much, it works now

**Comment by Solxanich** [comment]
Perfect, thanks. I'll get that pushed to Steam.

**Comment by milkycow77** [comment]
There is still one problem I'm having, I can open tmod loader from the bat.
File, but I still won't open when I try to open it from the application, I
also can't find some mods when I open the game from the zip file

**Comment by Solxanich** [comment]
Yes, we are pushing an update to Steam so it should work there now
