### ISSUE TITLE
在进入存档后返回到主界面后闪退

### ISSUE THREAD

**Issue by Makesus** [bluemagic123/tModLoader#4259]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

[在进入一个存档后（无冲突任务和地图）返回主界面后闪退并弹出错误信息
![屏幕截图 2024-06-08 164244](https://github.com/tModLoader/tModLoader/assets/53037072/43199696-78e3-4d63-b6cb-be86e6875247)

### Log File

[client.log](https://github.com/user-attachments/files/15747342/client.log)

**Comment by SheepishShepherd** [comment]
Issue is related to Boss Checklist and has been resolved. Update will be posted soon.
https://github.com/JavidPack/BossChecklist/commit/8dc7d559facc8f9ccfde59767073331832fffeac
