### ISSUE TITLE
Magic Dagger Prices in Don't Dig Up World

### ISSUE THREAD

**Issue by DaisukePlays** [bluemagic123/tModLoader#4280]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

In Don't dig up worlds the Stats of the Magic Dagger don't change accordingly.
I have no mods installed and did a fresh install of tModLoader.

### Log File

![Test World](https://github.com/tModLoader/tModLoader/assets/28978719/6ba6e58b-5891-4ae7-a718-06ec6681367a)

### Steps to reproduce

1. Have a Journey mode character and Journey mode don't dig up world ready. (Unless you want to waste a couple of hours)
2. Activate 10x Enemy slider and stay in the Underground Layer for the Skeleton Merchant to spawn. I advise a Hunter potion and Lifeform analyzer
3. Check if the moon phase is in third quarter. If it isn't change the ingame timer to 24x
4. Check the Price on the Magic Dagger

### Expected Behavior

Magic Dagger should have it's nerfed stats.

### Actual Behavior

Magic Dagger has it's normal stats.

### Reproduction frequency

I reproduced it 7 times and every time it came out the same.

### Additional Information

If you spawn in the Magic Dagger from the Journey menu, it has it's adjusted stats.

**Comment by JavidPack** [comment]
Thanks for the report. I can confirm the issue.
