### ISSUE TITLE
Custom Fishing Bobbers

### ISSUE THREAD

**Issue by Raccphin** [bluemagic123/tModLoader#4284]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Make an option to make a custom fishing bobber accessory like the ones in the game. From what I could gather from the source code, if the projectile has AI 61, the fishing bobber AI, and if projectileID >= 986 and <= 993, then the bobber changes, otherwise the bobber gets killed which results in nothing being sent out.
![image_2024-07-06_215634219](https://github.com/tModLoader/tModLoader/assets/174832135/f5c33a55-a892-4125-abc6-1e2e1e598323)

### What does this proposal attempt to solve or improve?

I want to make a custom fishing bobber but currently it seems I would need to fake having a projectileID within the given range using AIType, which I have no clue how to use. It is also a very roundabout way of something that could probably be made much easier.

**Comment by Rijam** [comment]
Custom bobbers can already be made and pretty easily. For the item, set `player.overrideFishingBobber = ModContent.ProjectileType<YourBobberProjectile>()` in `UpdateAccessory()`. For the projectile Set `Projectile.aiStyle = ProjAIStyleID.Bobber`, `AIType = ProjectileID.FishingBobber`, and `Projectile.bobber = true` in `SetDefaults()`. You now have a working bobber. You can customize it more with ModPlayer's several fishing related hooks.

**Comment by Raccphin** [comment]
I see, I am not that experienced in modding yet and the only tests I have done were with the vanilla bobbers, which don't work with player.overrideFishingBobber. I am guessing the AI for modded bobbers are different from the normal bobber AI then?

**Comment by JavidPack** [comment]
We could add a new set sometime if this is more requested.
