### ISSUE TITLE
tModLoader broke multiplayer over LAN stuck at connecting screen.  It works in 2024.2.3.0 back from March 31 2024 but is broken in all stable releases after including the latest 2024.5.3.1.

### ISSUE THREAD

**Issue by deee167** [bluemagic123/tModLoader#4286]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

**Comment by deee167** [comment]
tModLoader broke multiplayer over LAN stuck at connecting screen.  It works in 2024.2.3.0 back from March 31 2024 but is 
broken in all stable releases after including the latest 2024.5.3.1.

Hosting a server either by directly executing the tModLoader server from a bat file or starting the game and going host and play does not allow another computer on the same LAN to connect.   They are stuck at the connecting screen indefinitely. Connecting using IP and port.  GOG version.  I can connect from the same computer running the server, but not from another on the same network.

In the client.log on the client computer get the following errors:

System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address) in tModLoader\Terraria\Net\Sockets\TcpSocket.cs:line 61
   at Terraria.Netplay.TcpClientLoop() in tModLoader\Terraria\Netplay.cs:line 401
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

System.Net.Sockets.SocketException: An operation was attempted on something that is not a socket.

As soon as the client hits button to connect after the port entry, the host computer gets a connection from the client on the correct port from dotnet.exe.  Allowing it doesn't allow the connection.

Again this works in the older version of tModLoder mentioned above, so the code was changed and this broke multiplayer.

Please fix this and release the fix ASAP.  Going back to this older version prevents mods from working as they need newer version.

**Comment by JavidPack** [comment]
If it stopped working for you on v2024.03 and after, then it is likely a firewall issue. That release changes the file path of the executable from `steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe` to  `steamapps\common\tModLoader\dotnet\dotnet.exe`. Update your firewall permissions to allow the new dotnet.exe path to access the network.

**Comment by deee167** [comment]
It's not my firewall, I don't use the steam version, I use GOG and dotnet.exe is in the game directory under tModLoader where it downloads it, it's not under steam.

**Comment by JavidPack** [comment]
My mistake, I was just showing an example of the path changes, you would have to adjust the path for wherever you installed tModLoader. The paths did change for GOG installs as well. 

If you checked that, I'm not sure right now what else to try, I'm not aware of any networking specific changes we've made in that release. The change from .net 6 to .net 8 was pretty big, but it shouldn't affect anything adversely unless you were on windows 7.

**Comment by deee167** [comment]
Thanks for the suggestion, but I just installed tModLoader recently, the latest version and it was working fine for connecting to the server on the same pc, and my firewall prompts me when something tries to go online so it prompted me for dotnet.exe when the client pc tried to connect.  I allowed it, but the game does not finish the connection.  There is a bug in tModLoader after the given date.

I don't know what else to tell you, I spent 2 days and many hours diagnosing and trying to fix this.  I even narrowed down for you exactly after which point tModLoder broke.  Please look at the code and commits closely as it's not working anymore.

**Comment by deee167** [comment]
it's Windows 10 server and windows 11 client.  The windows 11 client can't connect with newer version of tModLoader.  All running the same versions of terraria, tModLoader, mods etc.  This was set up a few days ago fresh.  As a final ditch effort I downloaded older version of tModLoder to narrow down for you when it broke.  It took me hours and hours to get you all this information and figure this out.  Please investigate thoroughly.  All I changed between it working and not, is delete the tModLoader directory, unzip the next version to try, run it so it downloads dotnet,exe and run the game.  Same version on both pcs.  Something changed.  Please look thoroughly.

**Comment by JavidPack** [comment]
Well, I can look, but send the logs from the connecting computer and host computer in the meantime. 

> Logs can be found in the "tModLoader-Logs" folder in your tModLoader [install directory](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install) (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files") 
>       
> Attach log files by making a new comment and dragging them into the text input field. Please do not copy and paste the text from the log files, post the actual files.

**Comment by Chicken-Bones** [comment]
As @JavidPack has said, we will need logs to investigate this issue further. However it's likely that we will need to send you test builds, or get you to run diagnostic commands on your PC. Please come to the [Discord](https://discord.gg/tmodloader), and make a post in the support forum. Feel free to ping `@jopojelly` or `@Chicken-Bones` to get our attention there

**Comment by deee167** [comment]
I have messaged Chicken-bones on discord.  I can test out builds.  Please read the messages from the general channel on discord, others have looked at the server.log and there was nothing of note in there.  No errors, no mention of the client trying to connect, nothing.  Yet my firewall detected the connection from the client and I allowed it but the server never replied to the client with the latest version of tml.

in the client.log, these were the logs at the end (ip replaced with [ip server] in the logs below):
[09:35:15.644] [TCP Client Thread/INFO] [Terraria]: Connecting to [ip server]:7779
[09:35:15.708] [TCP Client Thread/INFO] [StatusText]: Connecting to [ip server]:7779
[09:35:36.743] [TCP Client Thread/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:[ip server]]:7779
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address) in tModLoader\Terraria\Net\Sockets\TcpSocket.cs:line 61
   at Terraria.Netplay.TcpClientLoop() in tModLoader\Terraria\Netplay.cs:line 401
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

[09:37:48.077] [TCP Client Thread/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: An operation was attempted on something that is not a socket. [::ffff:[ip server]]:7779
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address) in tModLoader\Terraria\Net\Sockets\TcpSocket.cs:line 61
   at Terraria.Netplay.TcpClientLoop() in tModLoader\Terraria\Netplay.cs:line 401
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by deee167** [comment]
were you able to look at this?

**Comment by Chicken-Bones** [comment]
Resolved in Discord. The rule in windows defender on the host computer was disabled. Users experiencing similar issues should check their firewall settings for the correct path (ending in `tModLoader/dotnet/dotnet.exe`)

![image](https://github.com/tModLoader/tModLoader/assets/388233/cbb15b1c-1601-42ed-91a6-04bdf6baf490)
