### ISSUE TITLE
weird version

### ISSUE THREAD

**Issue by Mentor78** [bluemagic123/tModLoader#4299]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

![image](https://github.com/user-attachments/assets/1b3d0cc8-4762-463f-a5ca-14cb7e618f9b)

the vrsion is a little off

### Steps to reproduce

1. start tmodloader at version preview-v2024.3
2. tap cancel at loading mods
3. go to woshop and manage mods

### Expected Behavior

showing 1.4.4.9

### Actual Behavior

i have no idea thats why i am texting you

### Reproduction frequency

every time

### Additional Information

none

**Comment by JavidPack** [comment]
v2024.3 isn't the latest preview. I'll try to make this message more accurate, but you should really not be on an old preview, you should be on the default release for the greatest stability.
