### ISSUE TITLE
Getting inventory dimensions

### ISSUE THREAD

**Issue by abluescarab** [bluemagic123/tModLoader#43]
Is there a way to get the dimensions of the inventory? Position and size.

**Comment by Chicken-Bones** [comment]
Look at the code that draws them and do the same calculations

**Comment by abluescarab** [comment]
I did... it's a lot. I guess that answers my question, though. Thanks.

**Comment by Chicken-Bones** [comment]
If you have some suggestions for hooks, me might be able to do something. Especially if you were to submit a pull request.

**Comment by abluescarab** [comment]
Thanks. Unfortunately, the Terraria source code is a bit muddy for me to look through, so I've been sticking to making tModLoader mods! But if I figure out a good solution, I will be sure to test it out.
