### ISSUE TITLE
Add extra hooks in WorldGen.TileFrame() for ease of custom framing without needing to entirely copy huge chunks of vanilla code

### ISSUE THREAD

**Issue by IbanPlay** [bluemagic123/tModLoader#4305]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

- Add a **ModTile.PostTileFrame()** hook that runs after the vanilla framing code has decided on Tile.TileFrameX/TileFrameY to let modders apply simple edits (Like for example, offsetting the frame's position for larger patterns). It would need to be called both for FrameImportant tiles and non FrameImportant ones

- Add a **ModTile.ModifyFrameMerge()** that runs after the adjacent tile's merge type has been calculated, but before the frame gets calculated, exposing the adjacent tile's merge type as references so modders can modify them as needed

### What does this proposal attempt to solve or improve?

Currently the only way to have custom tile framing is by using the **ModTile.TileFrame()** hook, which is overkill in a lot of cases. It preventing the ENTIRE vanilla tile framing code means that even for simple changes, modders are forced to copy huge chunks of the vanilla tile framing code

- A common use for this would be tiles with large patterns like stone slabs. The current most common way to do this with modded tiles is to override **ModTile.AnimateIndividualTile()** to add an offset to the tile frame on the sheet which runs every single frame. This means that patterns with more complex rules can cause hits in performance due to needing to recalculate the frame offset on every draw loop
![image](https://github.com/user-attachments/assets/8cfc23eb-0884-491b-be29-624aeddb5ac7)
> Example code for a tile that uses AnimateIndividualTile to create a pattern that spans 2x2 tiles

- Another pain point is wanting to modify the connections of a tile with more control. As an example, I'd like to be able to make it so a tile only connects to another tile from the bottom, but considers it as an empty space if its on top, and have that modification happen before vanilla code that decides the frame runs. Another big thing having control over the connections would bring is the ability to easily make tiles that merge with tiles that aren't dirt by using a combination of **TileID.Sets.ChecksForMerge** and **WorldGen.TileMergeAttempt**. Currently, once again, making tiles that merge with tiles that aren't dirt is impossible unless the entire TileFrame code is copied

![placeholder](https://github.com/user-attachments/assets/9eb601b2-30da-4b43-989c-50a4a55822eb)
Here's a tile that uses both of the suggested hooks : It uses the **PostTileFrame** hook to offset the tile's frameY so every other vertical tile uses a different variant of the sheet to create a striped pattern that spans 2 vertical tiles, and it uses the **ModifyFrameMerge** hook to make it so the tile doesn't connect from the top to the other color variant, leading to a layered appearance. Despite both changes totalling 5 lines of code, without these extra hooks i would have had to copy the entire vanilla tile merging/framing code to achieve the same results with ModTile.TileFrame()

![image](https://github.com/user-attachments/assets/9b771dcf-ffde-478a-bdc2-36aaf10ad360)

Adding these hooks on the method via IL editing as a modder isn't possible because Worldgen.TileFrame is one of the large methods that leads to the detours getting randomly garbage collected (see #3878)

### Which (other) solutions should be considered?

I tried to IL edit the TileFrame method myself but because of the garbage collection bug it isn't reliable, and I don't really know if there's any way to get around that, nor can I think of any better ways to have the same control over tile framing. 
The only concern is that **PostTileFrame()** wouldn't be easily implemented for GlobalTiles, as the section that handles FrameImportant tiles is a huge messy switch statement with a lot of early returns everywhere. Implementing it as only a ModTile hook would be trivial however

**Comment by IbanPlay** [comment]
Additionally the same hooks could be given to walls? Those don't usually have much crazy framing going on, but it could still be useful to some. Additionally, walls currently don't have a AnimateIndividualTile equivalent, so walls with larger patterns are even worse to program. I had to use an IL edit to get the same functionality

EDIT: Nervermind, ModWall.WallFrame is much more useful than ModTile.TileFrame, so those hooks wouldn't be necessary. An animateindividualwall might still be nice, but not as necessary in this case

**Comment by JavidPack** [comment]
Is there anything left todo IbanPlay? If not, I'll close this issue as completed.

**Comment by IbanPlay** [comment]
The PR got merged so I think everything has been resolved!
