### ISSUE TITLE
Hopefully a 64-bit tmod version will come out 

### ISSUE THREAD

**Issue by xiaotang666** [bluemagic123/tModLoader#4307]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I hope to come out with a 64-bit tmod version 32-bit version will be very stuck when the number of mods is large, computer performance has not been fully released, of course, there are other 64-bit versions on the Internet, but sometimes the new version of the mod is not supported, thank you very much!!

### What does this proposal attempt to solve or improve?

It allows players to better play the game and bring more ways to play

**Comment by direwolf420** [comment]
tml is already 64bit, if you play on any version after 1.3 (which is 32bit, there is an unofficial 64bit version of that)

**Comment by xiaotang666** [comment]
> TML 已经是 64 位了，如果您在 1.3 之后的任何版本上玩（即 32 位，有一个非官方的 64 位版本）

这样啊  但是我在今日游玩时发现他的内存占用并不能超过4GB，请问一下是什么原因呢，感谢

**Comment by xiaotang666** [comment]
> tml is already 64bit, if you play on any version after 1.3 (which is 32bit, there is an unofficial 64bit version of that)

But I found out that his memory usage can't exceed 4GB when I played today.,What is the reason?,Thank you.

**Comment by Mirsario** [comment]
Direwolf is correct, and there are no absolutely memory usage limits in modern TML.
