### ISSUE TITLE
DrawEffects `fullBright` Parameter Ignored

### ISSUE THREAD

**Issue by steviegt6** [bluemagic123/tModLoader#4317]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

`ModPlayer::DrawEffects`' `fullBright` parameter is ignored if `r`, `g`, `b`, and `a` are all `1`. This behavior doesn't seem intended and breaks my use case. I use `DrawEffects` to fix an issue with rendering the player with `UICharacter` in-game, as doing so causes hair to render completely black (due to requesting an incorrect lighting position).

It's a very simple implementation:
```cs
	private sealed class StatPanelRendererPlayer : ModPlayer
	{
		public override void DrawEffects(PlayerDrawSet drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
		{
			base.DrawEffects(drawInfo, ref r, ref g, ref b, ref a, ref fullBright);

			// Force fullBright if rendering the player so hair draws
			// correctly.
			if (drawingPlayer)
			{
				fullBright = true;
			}
		}
	}
```

`drawingPlayer` is `true` under the correct contexts and I've confirmed it's specifically due to `fullBright` being ignored:
![image](https://github.com/user-attachments/assets/8aef0097-f6ee-4e27-872d-fdbc3dcc3c2b)
![image](https://github.com/user-attachments/assets/ede8d152-8bc8-4b23-8c68-fe2dd342ee53)

**Comment by harlowo** [comment]
Tmodloader bug speedrun any%
