### ISSUE TITLE
tmodloader wont launch dotnet 8.0.0

### ISSUE THREAD

**Issue by ZELIAM-tries** [bluemagic123/tModLoader#4330]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects...

Gameplay as a Player

### Description

SO i tried to launch tmodloader with the dotnet 8.0.0 file bc i think launching system needed that but the probleme is that it wont launch and kept deleting the 8.0.0 dotnet file in the dotnet folder to be honest idk what happening so here is the log texte 

### Log File

Logging to C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/tModLoader-Logs/Launch.log
Fixing Environment Issues
mv: can't rename 'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/Steamworks.NET': Invalid argument
'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/Steamworks.NET' -> 'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/steamworks.net/Steamworks.NET'
mv: can't rename 'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/Newtonsoft.Json': Invalid argument
'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/Newtonsoft.Json' -> 'C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/Libraries/newtonsoft.json/Newtonsoft.Json'
Windows Version 10.0
Quick Edit Disabled
Verifying installation directory...
Success!
Verifying .NET....
Parsing .NET version requirements from runtimeconfig.json
Success! dotnet_version=8.0.0
Last Run Attempt Failed to Start tModLoader. Deleting dotnet_dir and resetting
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Update Required. Checking for Windows pre-deployed x64 dotnet files
None Found. Attempting downloading win x64 portable dotnet runtime directly...
This can take up to 5 minutes
Extracting...
unzip: can't open C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/dotnet/8.0.0[.zip]
Update Required. Will now attempt downloading using official scripts.
This can take up to 5 minutes
Failed to download dotnet-install.ps1. Relying on Powershell to work
Invoke-WebRequest : La connexion sous-jacente a  t  ferm e : Une erreur inattendue s'est produite lors de l'envoi.
Au caract re Ligne:1 : 107
+ ... k]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/do ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebEx 
   ception
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Dotnet should be present in "C:/Users/MON PC/Desktop/mybe - Copie (5)/tModLoader (9)/dotnet"
[31mDownload of portable dotnet runtime seems to have failed,[0m
[31mProceeding will probably fall back to system wide installed runtime[0m
Attempting Launch...
Launched Using System Dotnet. Launch command: dotnet tModLoader.dll ""

**Comment by arsham841** [comment]
i have he same problem

**Comment by marky129** [comment]
Hi is this fixed? i have the same problem

**Comment by JavidPack** [comment]
> Hi is this fixed? i have the same problem

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). Be sure to post your logs when asking for support.
