### ISSUE TITLE
[UI] Add confirmation prompt for "Enable/Disable All" buttons

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#4357]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

The UI

### Description

Clicking "Enable All" or "Disable All" are actions which will always mess up your currently enabled mod list with no easy way to undo it. I suggest adding a confirmation prompt so when accidently pressing them you don't waste time re-enabling the mods you want again.

Such a popup exists for the "Delete Mod" button, should be easy to repurpose.

### What does this proposal attempt to solve or improve?

UX. Its common to have "confirm dangerous action" popups for things that are either irreversible or hard to revert manually.

**Comment by Metratrj** [comment]
//claim
Looks reasonable to me. Will take care of it.

**Comment by TigerChenzzz** [comment]
I think it's better to add an undo or reset function, maybe using a new button?
