### ISSUE TITLE
A change request from a DefectiveByDesign advocate

### ISSUE THREAD

**Issue by heavyutils** [bluemagic123/tModLoader#4358]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Don't do ReLogic's job in pressing a heavy DRM into Terraria. They would have done it if they wanted, but the base game doesn't even have it. This severely limits how you can play with mods for legitimate users. I will kindly request to remove the dependency of Steam credentials. [You can read why;](http://defectivebydesign.org) dig in it, and you'll likely get it.

### What does this proposal attempt to solve or improve?

This will give the player the freedom to play whenever; such as make it possible to play offline.

### Which (other) solutions should be considered?

It can be narrowed down to just requiring steam_api.txt app-id or the Steam installation without Steam running.

**Comment by Chicken-Bones** [comment]
tML can be played without internet connection by entering offline mode in Steam, the same as all other steam games.

You can also buy Terraria on Good ol Games (GoG) and follow the [Manual Installation Instructions](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation) if you want to avoid buying the game on Steam.

There is currently no way to _download_ mods without a running steam client. Since mods are hosted on the Steam workshop

**Comment by heavyutils** [comment]
> tML can be played without internet connection by entering offline mode in Steam, the same as all other steam games.
> 
> 
> 
> You can also buy Terraria on Good ol Games (GoG) and follow the [Manual Installation Instructions](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation) if you want to avoid buying the game on Steam.
> 
> 
> 
> There is currently no way to _download_ mods without a running steam client. Since mods are hosted on the Steam workshop

What if I manually download mods? Steam workshop isn't a necessity to play with mods. While I don't like internet requirement, I'm not trying to do the impossible here

**Comment by Chicken-Bones** [comment]
When tML is installed alongside a GoG version of Terraria, a running Steam client is only required to use the in-game mod browser. You can play tML and use your installed mods without the Steam client just fine. If you want to avoid installing the steam client on your PC entirely, you can probably download mods with some third party workshop downloading tool like depot downloader, and browse the mod list using your web browser.
