### ISSUE TITLE
TML pops up a black window after opening, and then it closes directly

### ISSUE THREAD

**Issue by MemThreedz** [bluemagic123/tModLoader#4362]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

TML pops up a black window after opening, and then it closes directly. My terraria can work, but tml doesn't work,I tried reinstalling tml and terraria, but that didn't work, so I came for help

### Log File

[client.log](https://github.com/user-attachments/files/16782198/client.log)
[Natives.log](https://github.com/user-attachments/files/16782201/Natives.log)
[server.log](https://github.com/user-attachments/files/16782202/server.log)
[terrariasteamclient.log](https://github.com/user-attachments/files/16782203/terrariasteamclient.log)
[environment-client.log](https://github.com/user-attachments/files/16782204/environment-client.log)
[environment-server.log](https://github.com/user-attachments/files/16782205/environment-server.log)
[Launch.log](https://github.com/user-attachments/files/16782206/Launch.log)

### Reproduction frequency

100%

**Comment by MemThreedz** [comment]
[client.log](https://github.com/user-attachments/files/16782211/client.log)

**Comment by JavidPack** [comment]
Your natives.log has the "Failed to activate audio client" error, 3rd bullet here is more info: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#check-nativeslog

**Comment by MemThreedz** [comment]
> 您的 natives.log 出现“无法激活音频客户端”错误，第 3 个项目符号是更多信息：https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#check-nativeslog

thank u sir <3 My tml has become normal, thanks again. i love u !!!!
