### ISSUE TITLE
TML Crashes when opening the mod browser

### ISSUE THREAD

**Issue by DeltaRazerNova** [bluemagic123/tModLoader#4363]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

GOG

### This bug affects...

Gameplay as a Player

### Description

TML Crashes while trying to open the mod browser

### Log File

[2024-08-31-1.zip](https://github.com/user-attachments/files/16825120/2024-08-31-1.zip)

### Steps to reproduce

1. Click Workshop
2. Click Install Mods

### Expected Behavior

Should be opening the mod browser

### Actual Behavior

TML Crashes

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Thanks for the report, and for testing GOG on Preview. We'll try to get this fixed before the Stable release.
