### ISSUE TITLE
Setting an item's shopCustomPrice allows players to sell similar items for that price

### ISSUE THREAD

**Issue by mimig298** [bluemagic123/tModLoader#4370]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Joining a stack of an item type with a stack of the same item type bought from an NPC using `shopCustomPrice` makes the custom price apply to all those items.

### Log File

[client.log](https://github.com/user-attachments/files/16910736/client.log)
[Launch.log](https://github.com/user-attachments/files/16910738/Launch.log)
[Natives.log](https://github.com/user-attachments/files/16910742/Natives.log)
[environment-client.log](https://github.com/user-attachments/files/16910743/environment-client.log)

### Steps to reproduce

1. Buy an item that is being sold for a custom price higher than the default price by an NPC
2. Drag a stack of that item type into the stack you just bought. Doing the opposite won't reproduce the issue.
3. Open any NPC shop. The value of the item stack matches the value it was being sold for.

### Expected Behavior

The item stack the player is left with after combining items bought for a custom price and items obtained normally should have the regular value rather than the modified shop value.

### Actual Behavior

The resulting item stack is worth more than it should.

### Reproduction frequency

I have been able to reproduce this every time. All of my tests were made with the same world and character, and I didn't leave the world in the middle of the execution.

**Comment by JavidPack** [comment]
Thanks for reporting, I can verify the issue and will look into a fix.
