### ISSUE TITLE
Unable to start the game normally, crashes and reports an error on the start interface

### ISSUE THREAD

**Issue by 114514-awa-qwq** [bluemagic123/tModLoader#4371]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects...

Mod capability as a Modder

### Description

Enter the game and report an error, Then pop up‘’Failed to load asset:'Images\Background_170’!‘’Ask for answers，thanks.

### Log File

[client.log](https://github.com/user-attachments/files/16924490/client.log)

### Steps to reproduce

1.Open the game 2.Waiting for the game to load 3.The game crashes during play or loading

### Expected Behavior

A lot of error reports will pop up, and the game interface will freeze, but the sound is working normally.

### Actual Behavior

Game crashes

### Reproduction frequency

Almost every time

**Comment by JavidPack** [comment]
I'm guessing the NVIDIA GeForce GTX 750 Ti you have is too weak to load the game. The error messages are similar to this error <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#texture2d-creation-failed-error-code-not-enough-memory-resources-are-available-to-complete-this-operation-0x8007000e>
