### ISSUE TITLE
Player and world corrupted after mod issue

### ISSUE THREAD

**Issue by ChocoGotLate** [bluemagic123/tModLoader#4374]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects...

Gameplay as a Player

### Description

I loaded my TModLoader today as usual (i haven't modified any folders) but when loaded it showed me an error message (something along the lines of "Terraria Ambience mod could not be loaded". I restarted TModLoader after disabling the mod (and API) to then see than my main character corrupted.
![image](https://github.com/user-attachments/assets/9e44974f-1bd2-4136-9a7e-5e7caaf0f1b4)

I have googled the issue, and some people recommended to check the recycle bin, where i found two files:
![image](https://github.com/user-attachments/assets/23a1bd5c-424b-45f5-9a1a-e7f0af27bb30)

I recovered them and tried to load TModLoader again, but the files kept getting automatically deleted.

P.S. I have now realized that the world I mainly played on is also blank. Is there a way to retrieve the world and player without losing items and mapdata?

### Log File

[client.log](https://github.com/user-attachments/files/16949426/client.log)

### Steps to reproduce

It just happened randomly lol

**Comment by JavidPack** [comment]
Well, for some reason I can't download your client.log, looks like it failed to attach correctly.

I think Terraria will delete worlds that fail to load both the normal file and the backup, but tModLoader maintains additional backups you can restore from. Follow these instructions to restore backups and see if they work https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#world-and-player-backups

The fact that it happened suddenly suggest some mod updated and has buggy code. Try the backups and if they are also deleting themselves send a new client.log file

**Comment by ChocoGotLate** [comment]
Both the player and the world loaded! Thank you so much.
