### ISSUE TITLE
Mod Map-Backgrounds Do Not Adjust Based On Sky Color

### ISSUE THREAD

**Issue by Waffles22-TMod** [bluemagic123/tModLoader#4376]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

In vanilla, the "Map Background" displayed when looking at the Full-screen map will change color depending on ColorOfTheSkies, as seen in Main.DrawMapFullscreenBackground. This only triggers under certain conditions, primarily whether or not the player is on the surface; other conditions exist, such as it not affecting the Glowing Mushroom map-background.

Mod map-backgrounds do not have this feature, however. I simply recommend that ModBackgroundStyles should be given a bool that determines whether or not their map-backgrounds should be drawn like this.
It would be extremely easy to add, only requiring a new abstract bool in ModBiome and a check in Main.DrawMapFullscreenBackground.

### What does this proposal attempt to solve or improve?

This is admittedly a very minor detail, but it does improve visuals and provide consistency with vanilla Terraria.
It helps a map-background adjust to time-of-day and details such as ModifySunLightColor.
I used an On_Main hook to roughly create this effect, as shown in the provided images.
![map back 1](https://github.com/user-attachments/assets/65f42dff-8642-4484-80cf-2840cf807e87)
![map back 2](https://github.com/user-attachments/assets/5c46939e-9087-48f5-bb14-d88d38c19fc9)
![mockup](https://github.com/user-attachments/assets/44716df2-d5d7-4409-938a-174d16506c66)

**Comment by JavidPack** [comment]
Thanks
