### ISSUE TITLE
Seemingly random multiplication in ExampleGun's Even Arc example

### ISSUE THREAD

**Issue by mimig298** [bluemagic123/tModLoader#4379]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

In line 88 of ExampleGun (https://github.com/tModLoader/tModLoader/blob/stable/ExampleMod/Content/Items/Weapons/ExampleGun.cs#L88), `perturbedVelocity` is multiplied by `.2f` for no apparent reason.

**Comment by JavidPack** [comment]
Thanks, I've clarified why that is there in the fix.
