### ISSUE TITLE
Server config file is ignored if it does not specify a world to load

### ISSUE THREAD

**Issue by Moire9** [bluemagic123/tModLoader#4382]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

If the config file does not contain a `world` attribute, then all settings inside of it are ignored. This can be seen quite obviously as the server will startup with correct port settings and such without prompting the user. It can also be noticed as the file's `atime` (access time) is not updated if the server is launched when the config file does not contain a `world` attribute.

### Log File

[server.log](https://github.com/user-attachments/files/17024079/server.log)

I'll also note, that this is a fresh install and I don't have any mods specified anywhere, so I have no idea why a bunch of mods are trying to load.

### Steps to reproduce

1. Use `serverconfig.txt` without a `world=` line.  
2. Observe.

### Expected Behavior

All config settings are used

### Actual Behavior

No config settings are used

### Reproduction frequency

Always

### Additional Information

Server managed via script, not docker.

**Comment by JavidPack** [comment]
While this is a little confusing, this behavior matches Terraria behavior, so we try not to deviate too much for consistency.

The settings are loaded, but most of them are prompted for again even if they are in the config file. I could probably add some notes to the serverconfig.txt file itself mentioning that a world or autocreate/worldname option is required. Changing the behavior of the server to not re-ask about port, number of players, and other options might be difficult to do or maintain, but I'll look.

**Comment by Moire9** [comment]
Understandable. Changing behavior isn't necessary, This should definitely be clearly noted in the config file, perhaps with something to draw attention to it.

**Comment by JavidPack** [comment]
K, I've added a note in serverconfig.txt in 6ed6552c23f697004716fde81ba11d199929667d. Changing the logic to skip already selected settings would require too many changes, so this will have to do for now.
