### ISSUE TITLE
Ненаходе steamclient.so

### ISSUE THREAD

**Issue by Kabancik166** [bluemagic123/tModLoader#4385]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Tmodloader does not find /home/kabancikk166/.steam/sdk64/steamclient.so because steam in the path /home/username/.steam/sdk64/steamclient.so holds ego.

The problem is solved manually, but please change the code so that it is not necessary to solve it manually

### Log File

Make tmodloader check steamclient not only on /home/username/.steam/sdk64/steamclient.so but also on /home/username/snap/steam/common/.steam/sdk64

Then this problem will disappear. I solved this problem with a shortcut

### Steps to reproduce

.

**Comment by JavidPack** [comment]
We don't manually look in specific locations for steamclient.so in our code, so it seems to me that this is some sort of snap configuration issue. tModLoader accesses steam the same way any other steam game would. I'm not sure how to implement your suggestion.
