### ISSUE TITLE
Low whip tag damage (2/3 of supposed value)

### ISSUE THREAD

**Issue by Lev1nSvat** [bluemagic123/tModLoader#4390]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Without mods, on different characters and in different worlds whips adds only 2/3 of tag damage that they should. Tested with snapthorn and durendal using blade staff. With base damage 7 (prefix) after getting tagged by the whip with 6 tag damage it dealt 11-13 per hit, with 13 being rare and 11-12 most common. Also tested while using mod removing damage variability and it always hit for 11 (snapthorn), 13 (durendal), 12 (spinal tap)

### Log File

[client.log](https://github.com/user-attachments/files/17178889/client.log)
[Launch.log](https://github.com/user-attachments/files/17178890/Launch.log)
[Natives.log](https://github.com/user-attachments/files/17178891/Natives.log)
[environment-client.log](https://github.com/user-attachments/files/17178892/environment-client.log)

### Steps to reproduce

1. Any character any world, no mods
2. Summon
3. whip with a tag damage

### Expected Behavior

summon should deal it's damage + whip tag damage

### Actual Behavior

summon deals it's damage + 2/3 whip damage
(spinal tap adds 5 instead of 7 so 2/3 is approximation) 

### Reproduction frequency

always

**Comment by Chicken-Bones** [comment]
Does the enemy you were testing against have any armor? Have you tested the same wewapons against the same enemy in vanilla?

**Comment by Lev1nSvat** [comment]
> Does the enemy you were testing against have any armor? Have you tested the same wewapons against the same enemy in vanilla?

Blade staff ignores up to 25 enemy defense, I used it on several enemies none of them had above 25 def, and on a modded smart dummy (robo-dummy mod) all of them behave identical. Didn't test in vanilla yet I'll do more testing when I'll have the time.

**Comment by Chicken-Bones** [comment]
According to the wiki, Blade Staff deals 25% less tag damage than other summons

**Comment by Lev1nSvat** [comment]
Yes, I somehow didn't see that when checking the wiki myself, with another summon it works as it should.
