### ISSUE TITLE
Crash error when loading or disabling one or more mods

### ISSUE THREAD

**Issue by 5s188** [bluemagic123/tModLoader#4395]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Every time I play the game, when the mod interface is reloaded, enabled, or uninstalled, I often get a mod crash error, the picture is as follows:
<img width="1220" alt="Terraria报错" src="https://github.com/user-attachments/assets/d28f954d-a185-4f84-bf55-7c8a76fe2a92">
At first I thought it was the version of the mod and the compatibility problem, and then I repeatedly disabled and enabled it back and forth to find the problem mod, when I thought I found this mod and disabled it, and this problem appeared when other mods were enabled, and then I thought it was too many mods loaded, but I specifically tested that loading a mod would also have this problem, and sometimes loading all the mods did not have a problem, and there were frequent and irregular crashes and errors.
What is the cause of this and what is the solution? this
Makes me very distressed, this is the first time I play tModloader, I have never tried it before, I have been playing the original version, and after playing 600+ hours in the original version, I was bored, so I came to try tModloader, and there was a problem when it came up, during which I checked all kinds of information and strategies, and still couldn't find a way to solve the problem.

### Log File

[client.log](https://github.com/user-attachments/files/17209771/client.log)

### Steps to reproduce

1. First I enter the game via steam or desktop shortcuts. 2. Click on the main interface of the game to enter the mod manager interface. 3. Enable or disable one or more mods. 4. Click Back to reload. 5. There was a crash during loading. 6. The crash picture is as follows:
<img width="1220" alt="Terraria报错" src="https://github.com/user-attachments/assets/0d45514a-9761-4aac-8a21-be1635c8fdaf">

### Expected Behavior

Under normal circumstances, the loading is finished and the main page of the game is successfully returned.

### Actual Behavior

In fact, a crash error occurred when loading the mod. The picture is as follows:
<img width="1220" alt="Terraria报错" src="https://github.com/user-attachments/assets/11d02fc8-42c9-4bc6-bddf-950485fccc12">

### Reproduction frequency

It basically happens every time.

**Comment by JavidPack** [comment]
We usually see this error with the TerrariaAmbience mod. Disable it and try again.

**Comment by 5s188** [comment]
> 我们通常会在 TerrariaAmbience Mod 中看到这个错误。禁用它，然后重试。

Yes, through today's test, I found that it is the problem, only to it enabled or disabled, this problem appeared, after he unsubscribed, the state resumed. Thank you very much for your answer.

**Comment by JavidPack** [comment]
I think you accidentally reopened this.
