### ISSUE TITLE
Player.breatheMax does not Reset. Add it to Player.ResetEffects()

### ISSUE THREAD

**Issue by BugraPearls** [bluemagic123/tModLoader#4396]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Player.breatheMax does not Reset its value in Player.ResetEffects(), and its coded to be 200. 

I propose adding it to Player.ResetEffects(), setting it to 0, and in Update() giving it the 200 value back.

(Out of scope of this issue but some documentation/description regarding how breath works is also good, otherwise requires decent vanilla code reading)

### What does this proposal attempt to solve or improve?

This proposal should resolve any possible conflicts, and bring convenience to the Modder, since a Modder will not have to set their own ResetEffects() code for this spesifically if they want to modify it in any way, and if there is another mod that does something with this value, they won't have to hard-lock the Reset value to be 200 inside their mod, instead, the game itself can do that and Modders can simply += the Player.breatheMax value.

**Comment by direwolf420** [comment]
Can confirm this is the case. Thorium has a few things increasing maximum breath, and it resets the cap back to 200 in ModPlayer.PostUpdateEquips manually.
This change _may_ be causing things to not work for mods expecting it to not reset, would need to be tested

**Comment by JavidPack** [comment]
Sounds good. I also agree that documenting breath and others would be good. I don't imagine resetting it in tModLoader would cause issues for mods.

Feel free to let us know if you run into any issues setting up the project. We can help here or on discord.

**Comment by BugraPearls** [comment]
I'd like to contribute regarding this, both with documenting and the Resetting of breatheMax, however, truth be told I have very little experience with GitHub and haven't done this before, so what should I do from here?

I think I have to create a Pull Request and do changes, and u guys will accept it but I am a bit confused, I really don't know what to do there.

**Comment by JavidPack** [comment]
So, since tModLoader is built on patches to the source code, things are a little different from a normal GitHub project. We have the full instructions shown in https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-contributors, give them a glance and see if you are up to it or not.

The process is a bit involved if you are not familiar with Git and Github, unfortunately. If you don't feel up to doing those steps, and since this change is fairly simple, I can make the changes for you instead and I'll mark you as the co-author if you'd like. You'll just need to type out the exact changes here and the documentation text you want added.

Either way is fine by me, but if you do want to try making the actual PR yourself, you might want to come to Discord chat for live help so we can work through any trouble with the process you might run into.

**Comment by BugraPearls** [comment]
Like you said, it does look a bit overwhelming to me so heres changes I'd say is fit:

**(in ResetEffects())
Player.breathMax = 0;
(in Update(), possibly maybe before PreUpdate()?)
Player.breathMax = 200;**

_or_

**(in ResetEffects())
Player.breathMax = 200;**

### Text for documentation:

**_Player.breathCD:_** Ticks up every frame. Is essentially the timer to manipulate the breath value, resets back to 0 once it reaches the breathCDMax value.
**_Player.breathCDMax:_** Determines how long it takes for breath value to tick down. In vanilla, defaults to 7 and is increased by factors such as Player holding a Breathing Reed, which doubles this, or having a Diving Gear, which multiplies this by 6, to make the process of losing breath value slower.
**_Player.breath:_** This is used by vanilla Terraria to determine current breath value of Player, used to draw the current bubbles and to determine if Player should take drown damage or not. This value does not tick down every frame, but rather amount determined by breathCDMax, which defaults to 7. When not in water, breathCDMax is not utilized and it will increment by 3 every frame.
**_Player.breathMax:_** This is used by vanilla Terraria to limit how much breath value can go up to, and to draw the current maximum amount of bubbles on top of Player. This value defaults to 200. How many ticks it takes for maximum breath to run out is breathMax * breathCDMax.

I think these are good enough, but while at it, I've thought breathCDMax's base value being changeable would be even better, giving extra flexibility, so kinda optional but:

_new variable in Player;_
**_Player.breathCDFrames:_** defaulting to 7, resetting back in ResetEffects() or in Update(), while being set back to 1 if its lower than 1.

 **_Text for documentation:_** Determines how much frames it needs to pass for breath value to tick down. Defaults to 7. Used by breathCDMax.

Replaces the '7' in following breathCDMax's code:
```	
public int breathCDMax
	{
		get
		{
			int num = 7; //This gets replaced so it isn't hardcoded to reduce breath every 7 frames, extra flexibility to modder
			if (this.inventory[this.selectedItem].type == 186 && this.itemAnimation == 0)
			{
				num *= 2;
			}
			if (this.accDivingHelm)
			{
				num *= 6;
			}
			return num;
		}
	}

**Comment by JavidPack** [comment]
Thanks, I've made the commit. I've held off on the new field for now because doing it right as a StatModifier would take a bit more thought.

**Comment by BugraPearls** [comment]
Both looks amazing 👍 thanks for all the work y'all are doing for the community
