### ISSUE TITLE
Projectile.OriginalArmorPenetration documentation mistake

### ISSUE THREAD

**Issue by BugraPearls** [bluemagic123/tModLoader#4401]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

OriginalArmorPenetration has wrong documentation.

### Steps to reproduce

Hover over/read documentation of OriginalArmorPenetration property of Projectile.

### Expected Behavior

	/// <summary>
	/// The armor penetration of this projectile, without any player bonuses, similar to <see cref="originalDamage"/><br/>
	/// Used by <see cref="ContinuouslyUpdateDamageStats"/> to recalculate <see cref="ArmorPenetration"/> in combination with <see cref="Player.GetTotalArmorPenetration(DamageClass)"/>
	/// </summary>
	public int OriginalArmorPenetration { get; set; }

(And maybe possibly theres something else I don't know of that should be changed?)

### Actual Behavior

	/// <summary>
	/// The crit chance of this projectile, without any player bonuses, similar to <see cref="originalDamage"/><br/>
	/// Used by <see cref="ContinuouslyUpdateDamageStats"/> to recalculate <see cref="ArmorPenetration"/> in combination with <see cref="Player.GetTotalArmorPenetration(DamageClass)"/>
	/// </summary>
	public int OriginalArmorPenetration { get; set; }

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Thanks for the report, will be fixed in a future release.
