### ISSUE TITLE
不知道什么原因打完肉山就这样了

### ISSUE THREAD

**Issue by mojun125** [bluemagic123/tModLoader#4402]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

打完肉山后就报错了之前的老档没有问题

### Log File

[client.log](https://github.com/user-attachments/files/17266544/client.log)

### Steps to reproduce

正常打完肉山就崩了

**Comment by JavidPack** [comment]
There are errors from CatalystMod in your log, I would suggest disabling it and seeing if that solves your issue.
