### ISSUE TITLE
Can't Open tModLoader

### ISSUE THREAD

**Issue by Epix62** [bluemagic123/tModLoader#4409]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects...

Gameplay as a Player

### Description

i was just trying to start tModloader and it works fine. until it gets to the FAudio part and it would just stop and tell me there were a missing module

### Log File

[client.log](https://github.com/user-attachments/files/17336950/client.log)
[environment-client.log](https://github.com/user-attachments/files/17336951/environment-client.log)
[Launch.log](https://github.com/user-attachments/files/17336952/Launch.log)
[Native
![Screenshot 2024-10-11 094141](https://github.com/user-attachments/assets/523894e3-026b-4695-bdce-c7baf5f3b4d3)
s.log](https://github.com/user-attachments/files/17336953/Natives.log)

### Steps to reproduce

1. open tModLoader
2. wait till the FAudio part comes up
3. and after a few second the bug/crash would appear

### Expected Behavior

it should open tModloader instead

### Actual Behavior

missing files ig??? idk

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
I couldn't open native.log, was that file empty?

Most of the time with FAudio issues we direct users to try some of these suggestions: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#audio-issues

**Comment by Epix62** [comment]
omg thanks you soo much i finally can open tModloader yayyycghruitgr79iwt5y39yv4ety5e9tv88tyev
