### ISSUE TITLE
Various crate drop rate discrepancies

### ISSUE THREAD

**Issue by Altixal** [bluemagic123/tModLoader#4415]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Drop rates of many items from several crates are different from vanilla.

### Log File

[environment-client.log](https://github.com/user-attachments/files/17356572/environment-client.log)
[Launch.log](https://github.com/user-attachments/files/17356573/Launch.log)
[Natives.log](https://github.com/user-attachments/files/17356574/Natives.log)
[client.log](https://github.com/user-attachments/files/17356575/client.log)

### Steps to reproduce

1. Open Titanium Crates in vanilla (most visible difference, but applies to all items that have difference in rates)
2. Open Titanium Crates in tMod

### Expected Behavior

Drop rates should roughly be equal between two versions

### Actual Behavior

Drop rates are visibly different

### Reproduction frequency

Always

### Additional Information

Applies to 3 different drop rules from comparing between sources:
- Buff potions from all Biome Crates (1/3 instead of vanilla 1/4)
- Master:Journeyman bait split ratio from all Biome Crates (1:2 ratio instead of vanilla 1:1)
- Bars from Titanium Crates (8/15 instead of vanilla 4/15)

**Comment by JavidPack** [comment]
Thanks for the report. I've made the fixes mentioned and they look correct now. Someone will have to update each of the biome crates wiki pages, they all list `1/3 (33.33%)` for bait but it's actually `1/4` for biome crates.

Biome crates:

![image](https://github.com/user-attachments/assets/80d46a28-539a-412f-9c73-f7011ca38b61)

Titanium/Gold Crate:

![image](https://github.com/user-attachments/assets/ecf2e32f-cbd8-4143-9f4f-bfcd6683d7c1)
