### ISSUE TITLE
.Net skd not detdced 

### ISSUE THREAD

**Issue by i936** [bluemagic123/tModLoader#4434]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

After clicking develop mods i see net sdk 8 required and button to instal after instal is the same i tried to reset tml rebooting my pc bur nothing works always end with same error

### Steps to reproduce

1 go to workshop page in menu
2 click develop mods

### Expected Behavior

Mod making menu 

### Actual Behavior

.net sdk error

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
Can you try these steps to verify that the correct sdk is on the PATH? https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-developers#net-sdk

**Comment by i936** [comment]
> Can you try these steps to verify that the correct sdk is on the PATH? https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-developers#net-sdk
Yes it is on program files/dotnet/sdk
