### ISSUE TITLE
为什么进不去

### ISSUE THREAD

**Issue by 1qaz6663** [bluemagic123/tModLoader#4458]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### What does this proposal attempt to solve or improve?

![屏幕截图 2024-11-28 224247](https://github.com/user-attachments/assets/f31bb6ef-7bba-4648-b564-4a52d84998dc)

**Comment by Dlinuigh** [comment]
显卡驱动正确么？或者显存炸了？我觉得你需要添加自己的硬件信息。

**Comment by jd-ouswhsnnn** [comment]
![QQ截图20241204210210](https://github.com/user-attachments/assets/ad16cb8f-ccfd-4c60-ba87-f50d980d6d8e)
/gldevice:OpenGL
