### ISSUE TITLE
Visual Studio Extension to Aid Mod Development

### ISSUE THREAD

**Issue by TechnicalityCreations** [bluemagic123/tModLoader#4469]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

An extension for Visual Studio to help add content and streamline the development process.

**Comment by JavidPack** [comment]
What exactly do you have in mind that isn't already covered?

**Comment by TechnicalityCreations** [comment]
I was thinking it would be a lot easier if there was inbuilt build.txt documentation/generator, icons to see what content is what, templates for commonly used things, such as localisation, items and more, as well as some other QOL features.

**Comment by JavidPack** [comment]
Well, build.txt is generated with the mod generator, and localization is automatically updated and generated as well, so I don't think those would necessitate a visual studio extension. I'm not sure about icons, do you mean that there would be some way of indicating if a .cs file is for a ModItem vs a ModProjectile? That could be cool, but I'm not sure how much work that would be or how useful it would be. 

I know in the past some have made and released templates for items, projectiles, etc, but in the end they aren't all that different then just a blank .cs class extending from the correct class. They never really caught on. 

We'd need something really useful to warrant integrating into tModLoader itself. I think if someone made something and the community thought it was useful and it became popular, we could then think about integrating it directly. It is a lot of work to create and distribute a visual studio extension, so we'd need to be sure that the features are desired and useful for modders before we do that.

**Comment by TechnicalityCreations** [comment]
To be honest, that is fair enough.
