### ISSUE TITLE
EchoPaint on columns does not work as expected (might be a vanilly bug)

### ISSUE THREAD

**Issue by BarzenX** [bluemagic123/tModLoader#4474]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Whenever EchoPaint is applied to a column (tested with Granite, Palladium, Marble and Sandstone) the other surrounding column tiles behave as if the painted tile got deleted. I added images of how I imagined the echo paint effect:

Painted tile with activated Spectre Goggles:
![ColumnEchoPaint1](https://github.com/user-attachments/assets/0b5b7a72-fd64-464d-a2a2-d287973b607c)

Painted tile without Spectre Goggles:
![ColumnEchoPaint2](https://github.com/user-attachments/assets/654d28d6-79af-4dda-b056-6302da14d2cf)

Painted tile without Spectre Goggles as I imagined it would be:
![ColumnEchoPaint2_Should](https://github.com/user-attachments/assets/4ebd70c0-8cc6-4805-975d-5a8b045c6eff)

Sadly I don't have the proper save to verify it in vanilla Terraria.

### Steps to reproduce

1. Place some Granite / Palladium / Marble / Sandstone Colum
2. Apply Echo Paint to a column tile

### Expected Behavior

![ColumnEchoPaint2_Should](https://github.com/user-attachments/assets/4e205d30-3ac8-47a8-90ad-4efcae48495c)

### Actual Behavior

![ColumnEchoPaint2](https://github.com/user-attachments/assets/fa335ef2-57b4-482f-bf38-043317644d02)

### Reproduction frequency

100% reproducible

### Additional Information

I'm happy to provide more screenshots / explanation if it helps :-)

**Comment by JavidPack** [comment]
Unless I'm misunderstanding something, this behavior is definitely intentional. Echo coating is supposed to make the tile appear as if it doesn't exist, not just invisible. As such, the tile "framing" as it does is expected.

https://youtu.be/Kuo_MMiHcT8?si=J5OL4GWsPcvlKKmb&t=267

I also tested vanilla and it behaves the same.  There is also hundreds of lines of code in the source code enabling this behavior.

**Comment by BarzenX** [comment]
Interesting! From, working with multi-tiled objects I've expected the single tiles just to render invisible!
Then I'm wrong and this issue can be closed, thanks for investigating and replying! :-)

**Comment by JavidPack** [comment]
Yeah, multitiles don't have any way of having the same effect, and don't frame in general, so they are untouched.
