### ISSUE TITLE
Players named "." delete all players when deleted

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#456]
Not sure if this is a tModLoader bug or a vanilla bug, but it's been reported many times.

Make a player named "."
Delete it
All player files are gone from Players folder and even recycling bin.

Needs Confirmation.

**Comment by Chicken-Bones** [comment]
Did we want to fix it in tML though?

**Comment by Jofairden** [comment]
No, as said fixed in vanilla due next update

**Comment by wooden-utensil** [comment]
Seems to be the filename, players are saved as `PLAYER_NAME.plr`, this player is `.`, so this is saved as `..plr`, `..` means parent directory, which means the parent directory with `plr` added on the end, which is: `TERRARIA_TMODLOADER_DIR\plr`
So it's deleting `TERRARIA_TMODLOADER_DIR\plr`! Problem solved!
