### ISSUE TITLE
Grappling Hooks

### ISSUE THREAD

**Issue by PythonGamer51** [bluemagic123/tModLoader#51]
O, how I have looked. I have found bits and pieces, but never any complete code that I could look at just to figure out what the heck is going on with it. I need some code to make a Custom Grappling Hook. I found projectile ID's and AI's, but never any concrete code to help me learn. Please Help

Best Wishes,

Python

**Comment by gorateron** [comment]
I don't really think this is the place for this... This  place is for issues with the tML framework.
If you need help, I suggest you use either of the following links:
(live) discord chat: http://discord.me/tmodloader
tML TCF thread: http://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/
tML TCF help thread: http://forums.terraria.org/index.php?threads/official-tmodloader-help-thread.28901/

**Comment by JavidPack** [comment]
We should leave this open though, as a grappling hook example is noticeably lacking in ExampleMod.
