### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by catmaster450** [bluemagic123/tModLoader#58]
yeah... so I compile a mod I am working on and... It gives me the error:

ErrorSo103: The name 'ItemID Does not exist.

This is the file that the error is in:
[GouhlLegs.zip](https://github.com/bluemagic123/tModLoader/files/571475/GouhlLegs.zip)

Thank you and please tell me how to fix, because I have no idea how.

**Comment by JavidPack** [comment]
This isn't a tModLoader, but rather a coding error on your part. Please keep this questions to the forum or the Discord channel.

The problem, however, is you need "using Terraria.ID;" to access ItemID variables.

**Comment by catmaster450** [comment]
thank you, I will fix this soon!
