### ISSUE TITLE
Build works only when launched from VS 

### ISSUE THREAD

**Issue by Kosti1** [bluemagic123/tModLoader#65]

**Comment by JavidPack** [comment]
More information?

**Comment by Kosti1** [comment]
It just crashes, Also I can seem to get it only work with windows debug building option

**Comment by Kosti1** [comment]
let me try to get log

**Comment by JavidPack** [comment]
Oh, ok, you are actually building tModLoader. Are you talking about the .bat file building? You might need to check that the latest msbuild is the one that your path is pointing to. If you join the discord chat we can talk it through easier, if I'm misunderstanding something.

**Comment by Kosti1** [comment]
Hi, I decided to check PATH on my PC and found out that it was pointing to old MSBUILD, corrected it and now it works like it worked before (It worked well) but I am still not getting it to run: ```
System.TypeInitializationException was unhandled
Message: An unhandled exception of type 'System.TypeInitializationException' occurred in Terraria.exe
Additional information: The type initializer for 'Terraria.Main' threw an exception.

```

**Comment by JavidPack** [comment]
I get that too. I usually build and then run it from the steam install directory (post build should copy it to there), then attach to process if I need to debug it.

It'd be nice to figure out why that error happens though.

**Comment by Murfalo** [comment]
After looking a little more closely at this bug, I think it's being caused by App.config.  Initially I was unable to even run WindowsDebug from Visual Studio, and I was able to fix it by downgrading the system.diagnostics section in my .NET machine.config.  The inner exception for trying to build in Windows Release is now:

> Unable to cast object of type 'System.Collections.Hashtable' to type 'System.Diagnostics.SystemDiagnosticsSection'.

With Stack Trace:

>     at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
>     at System.Diagnostics.DiagnosticsConfiguration.Initialize()
>     at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
>     at System.Diagnostics.TraceSource.Initialize()
>     at System.Net.Logging.InitializeLogging()
>     at System.Net.Logging.get_On()
>     at System.Net.Sockets.TcpClient..ctor(AddressFamily family)
>     at System.Net.Sockets.TcpClient..ctor()
>     at Terraria.Net.Sockets.TcpSocket..ctor() in tModLoader\src\tModLoader\Terraria.Net.Sockets\TcpSocket.cs:line 32
>     at Terraria.RemoteServer..ctor() in tModLoader\src\tModLoader\Terraria\RemoteServer.cs:line 10
>     at Terraria.Netplay..cctor() in tModLoader\src\tModLoader\Terraria\Netplay.cs:line 35

I don't really think this is a high priority issue since there are plenty of easy workarounds, just thought I'd document what I've found in case I or others find time to get back around to this later!

**Comment by Chicken-Bones** [comment]
Try steps 1-4 of the Debugging section in https://github.com/bluemagic123/tModLoader/wiki/Developing-with-Visual-Studio
