### ISSUE TITLE
Dye and Balloons odd behavior.

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#72]
"Hello, I have a weird glitch using tmodloader.
When I put any dye in the head slot, it pushes balloon sprite down."

![01](https://cloud.githubusercontent.com/assets/4522492/21217018/3a919fe6-c267-11e6-8a52-8c129aa7347b.jpg)
![02](https://cloud.githubusercontent.com/assets/4522492/21217015/388b9616-c267-11e6-8861-9ecb4596eaf1.jpg)

**Comment by Chicken-Bones** [comment]
I too have experienced this bug, very useful info to know it's dye in head slot related, I'll look into it

**Comment by Chicken-Bones** [comment]
Using cheat sheet, it appears the height offset increases with increasing dye id

**Comment by Chicken-Bones** [comment]
Fixed https://github.com/bluemagic123/tModLoader/commit/eb4cba90a9db757f8070abbd42cb6d0830c385ce
