### ISSUE TITLE
Tmodloader SteamID

### ISSUE THREAD

**Issue by rayman89** [bluemagic123/tModLoader#73]
The GoG version of tmodloader doesnt ask the user on the GUI to put their steamID like it asks for the passphrase It also does not tell the user that they can manually input it in the config.json file on the error that pop ups later.

If you follow the GUI's instructions after inputting the passphrase and pressing publish you get this error

Validate Credentials Query failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and passphrase = '(not at all my passphrase actually is way longer)'= at line 1 

It would be nice if the GUI asked you for the stemid as it does for the passphrase and the error for not having it (properly) specified would be nice if it was easier to understand to most users and provided aid in how to fix the issue.

Thank you.

**Comment by JavidPack** [comment]
Noted. We can add another prompt for this data, hopefully next release

**Comment by JavidPack** [comment]
Implemented in 42ddad036aabea99b43a211b1dd0f6764ff498a2
