### ISSUE TITLE
Building .tmod using C# 6.0 doesn't seem to work

### ISSUE THREAD

**Issue by Murfalo** [bluemagic123/tModLoader#75]
For example, expression-bodied members and the new null conditional operator are causing my mod to fail to compile (syntax errors) through the build option under Mod Sources in-game.

For example:
`private static int GoldChestRareItem => GoldChestRareItems[R.Next(GoldChestRareItems.Length)];`
Results In:
> error CS1002: ; expected

Is there an option for me to take the resources compiled by Visual Studio and run them through a .tmod creator of sorts?  I couldn't find one and looking through the source code that generates .tmod files, it seems like it would take a bit of work for me to make this an option and honestly it would be a pretty hacky way of solving the problem.

**Comment by JavidPack** [comment]
Did you set "languageVersion" in build.txt?

**Comment by Murfalo** [comment]
Nope! I feel silly now.  Please don't hate me D:
