### ISSUE TITLE
Format Code Invalid Cast Exception

### ISSUE THREAD

**Issue by Murfalo** [bluemagic123/tModLoader#78]
Setup.exe's Format Code option causes an invalid cast exception.  I'm currently testing it on a different computer but I have to set everything up all over again and compiling is taking a while... I'll edit this description with the results once it has finished!

For reference, [here is the log file](https://github.com/bluemagic123/tModLoader/files/671836/error.log.txt)

Also, after some testing I've determined that the error is not isolated to a single .cs file or even files that I have edited.

**Comment by Chicken-Bones** [comment]
Format code is regretfully broken at this point in time, I should probably hide it

**Comment by Murfalo** [comment]
I would also suggest removing it from README.md so that people like me who are interested in contributing don't get confused and waste time trying to debug.  Thanks for the quick response!

**Comment by Chicken-Bones** [comment]
https://github.com/bluemagic123/tModLoader/commit/dbefd62132cce8ca9d6d901c342f7c326174c7a8
