### ISSUE TITLE
Issues with Tile Entities

### ISSUE THREAD

**Issue by Itorius** [bluemagic123/tModLoader#81]
Hey,
I've found 2 bugs with TE when playing with them.
1) They don't seem to kill themselves when you destroy the tile it originated from (I can confirm that this isn't my bad code)
2) They don't seem to reactivate themselves after you re-enter the world (possibly they get killed when you leave?)

Have a nice day
-Itorius

**Comment by gorateron** [comment]
1. Will investigate
2. What do you  mean by reactivate?

**Comment by JavidPack** [comment]
This is likely an incorrect placement of the tile entity in relation to the tile's origin. I fixed this for someone else, so we probably just need to document the magic numbers in the example mod tile entity.

**Comment by Itorius** [comment]
For some weird reason it's not happening anymore and I'm not aware of any changes to the code.

**Comment by JavidPack** [comment]
K, added some comments: 7083bd46e45ee1c7860d3d7129f108a99628c382
