### ISSUE TITLE
Buying back sold items removes mod data (ItemInfo is discarded)

### ISSUE THREAD

**Issue by hamstar0** [bluemagic123/tModLoader#83]
https://forums.terraria.org/index.php?threads/durability.52036/page-2#post-1165422

**Comment by gorateron** [comment]
Will investigate...

**Comment by gorateron** [comment]
This does not seem like a bug to me, you need to properly clone your ItemInfo. Falling back to the [Clone hook](https://github.com/bluemagic123/tModLoader/wiki/EntityInfo#public-virtual-iteminfo-clone) here.

Here's an example:
```
class KirbyInfo : ItemInfo
{
	public bool cool = false;

	public override ItemInfo Clone()
	{
		KirbyInfo info = new KirbyInfo();
		info.cool = cool;
		return info;
	}
}
```
