### ISSUE TITLE
Added TileInfo and OnLeaveWorld

### ISSUE THREAD

**Issue by Itorius** [bluemagic123/tModLoader#86]
Could we have TileInfo and a OnLeaveWorld hook?

**Comment by Chicken-Bones** [comment]
Give us examples of how you'd use them. Also feel free to pull request

**Comment by Itorius** [comment]
OnLeaveWorld - close all custom UI's, some final cleanup
TileInfo 
1) I have a tile ownership system in mind -> only you and player's you share with could access/break the given tile
2) Something like JEI for Minecraft

**Comment by Chicken-Bones** [comment]
OnLeaveWorld - yeah why not
TileInfo
I think you just need to use some arrays in WorldInfo. There's no instantiating per tile data unless you use Tile Entities, but I'll leave someone else to comment on their stability of now.

**Comment by gorateron** [comment]
Strangely I remember doing OnLeaveWorld , I wonder why I didn't make it in.

**Comment by JavidPack** [comment]
@gorateron When you do, can you do some testing with those similar commands and make a note in the documentation on if those are called on client, server, or sp?

**Comment by gorateron** [comment]
Actually I was wrong, I was thinking about the disconnect hook. According to Skiphs, there isn't anything equivalent to a leave world we can hook into.

**Comment by JavidPack** [comment]
I added a PreSaveAndQuit hook for SP/Clients leaving the game. Should function as a suitable hook for the OnLeaveWorld hook you wanted.

TileInfo, is something you'll have to build yourself in a clever data structure within your own mod, as any real TileInfo class would cause Memory usage to explode beyond the 4GB limits.
