### ISSUE TITLE
Issues with hook functions for Wings

### ISSUE THREAD

**Issue by Berserk-Knight** [bluemagic123/tModLoader#87]
Unlike most other hooks, HorizontalWingSpeeds and VerticalWingSpeeds do not pass the player variable, which requires you to save the variable to the ModItem from some other function if you want to make something that isn't just a "wing" like hoverboards and jetpacks.
All the non-standard wing functions such as "extra vertical boost (jetpacks)", "hover", "extra horizontal speed during hover" and the like require access to the control variables in the player class.

The WingUpdate function has...quite a few problems in its current form.

First, the location of that hook (in its current state) is absolutely wrong. There's an "else" block down at 22630 that activates no matter what, and it basically overrides any changes WingUpdate can make on the wing's animations. (Unless WingUpdate just changed a bunch of variables on the ModItem or the ModPlayer that was to be catched by some other hook later on.)

Then there's another "if" block at line 22692 that plays a flapping sound for all custom wings with custom sprites. (Only checks if a wing isn't of a few specific types.)
This one is slightly less of a problem because it can be prevented by setting player.flapSound to true on every frame. (Which is stupid.)

Then there's yet another "else if" block at line 22874 that activates when the wings aren't "in use".
It has a chain of "else if" blocks that are effectively just "else" blocks (they only check for what something isn't) and ends with setting player.wingframe to 2 at line 23202.

It's not too big of a fix to make, I suppose. We're definitely going to need another local variable in player.Update(int i), WingUpdate needs to return something to that variable so it can be used to stay out of those blocks, and of course, those blocks need to have one more variable check.

**Comment by Chicken-Bones** [comment]
Pull request?

**Comment by Berserk-Knight** [comment]
Sorry, new to GitHub (to the point where I created an account just a few minutes prior to posting) so it may take a while until I figure out how to use GitHub properly.
I'll try and...fork a branch? and push changes into it? then put up a pull request? Is that how it goes?

**Comment by Chicken-Bones** [comment]
Yep, you fork this repo to make your own copy of it. 
Then you pull/clone it to your computer. 
Make your changes and commit.
Push the commit to your fork.
Submit a pull request to have your changes added here.

I see you have a good grasp of what needs to be done, so it'll be much easier to review the changes in code form.

Good luck

**Comment by Berserk-Knight** [comment]
Alright.

Just one question.
Should I consider backward compatibility?
What I'm proposing basically changes 3 hooks, adding an extra parameter to 2 of them and adding a return value to 1 that didn't return anything.
The one with the added return value...well, that one can't be helped, but for the ones that I added variables, I can just make them overloaded functions that people can choose to upgrade to in the meantime. (They are used in the example mod, btw.)
You know, give people an early warning, call it deprecated and then phase out the old ones after a few iterations.

**Comment by Chicken-Bones** [comment]
Ah yes, we try and avoid breaking changes until there's a Terraria update. Add a New prefix to the one with the return value change, and [Deprecated] attributes to all the old ones.

**Comment by gorateron** [comment]
I actually was supposed to look into wings but totally forgot about them, glad someone else noticed it. lol

**Comment by Berserk-Knight** [comment]
After countless tries, TML Dev Setup is failing to create the player.cs.patch when I do the "diff tModLoader" thing.

**Comment by Chicken-Bones** [comment]
You'd have to give us the error for future use. Also I recommend contacting us at http://discord.me/tmodloader and feel free to send us a PM for faster response time

**Comment by Chicken-Bones** [comment]
@Berserk-Knight  In the off chance you're still subscribed to this thread, I'm just looking to get in touch for your approval on our license change, Can you drop on Discord or have a look at #705 

Thanks
