### ISSUE TITLE
Mod Browser duplicates mods when spamming "Reload List" button

### ISSUE THREAD

**Issue by goldenapple3** [bluemagic123/tModLoader#89]
If you click on the "Reload List" button multiple times while it's loading, it lists every single mod multiple times.

As you can see here, every mod gets listed twice:
![Example](http://i.imgur.com/LaoxU5y.png?1)

**Comment by gorateron** [comment]
Is this guaranteed to happen when clicking the 'Reload List' button, or does it randomly happen?

**Comment by goldenapple3** [comment]
It is almost guaranteed to happen if you click it fast enough.
From what I understand, the list reload is performed in a separate thread, which (with my Internet connection) takes a second or two. If you click 'Reload List' again during that time, it will load all Mod Browser mods again, but it won't clear the existing list. So you end up with duplicates.

**Comment by gorateron** [comment]
I've replicated this, we're looking into it. 
https://i.imgur.com/YYz8Dtu.png

**Comment by JavidPack** [comment]
Should be fixed with https://github.com/bluemagic123/tModLoader/commit/854632d785f0fed19f40eb209e04a7c1b587163a
