### ISSUE TITLE
Built-in ModLoader mod doesn't have proper DisplayName

### ISSUE THREAD

**Issue by goldenapple3** [bluemagic123/tModLoader#90]
I made a small mod called WMITF (Which Mod Is This From?). It adds a tooltip for modded items that displays the mod's name, using the DisplayName property. 
![Self-advertisement example](http://i.imgur.com/oLvvTnJ.png?1) 
However, it seems like the default ModLoader mod's DisplayName is an empty string:
![Starting Bag example](http://i.imgur.com/MRJKkUy.png?1)
It's a really minor issue, but it would be nice if it's DisplayName was "tModLoader" or something like that.

**Comment by Chicken-Bones** [comment]
Fixed https://github.com/bluemagic123/tModLoader/commit/1468b71272ea4add331bc05f91b3154b64ddf1dd
