### ISSUE TITLE
Game Runs in Slow Motion and Moving Creatures Teleport

### ISSUE THREAD

**Issue by DonWaun** [bluemagic123/tModLoader#91]
My friend and I are playing together through Steam Multiplayer and whenever we move, it is always like we are in slow motion. We're not lagging or losing FPS, our movement speed and nothing else is slowed. Creatures and the Guide will also randomly teleport to and from us. We are using the Thorium Mod, Simple Auto Chests, Prefixes for Enemies, The Ethereal Mod, Calamity Mod, PowerMod, CakeMod, Shorter Respawn Time, Tremor Mod Remastered, Terra's Prehardmode Wings Mod, RPG Classes, and Wireless. Please help us with this issue, we love tModLoader, but the slowness and teleporting takes all the fun out of it, thanks,
DonWaun

**Comment by JavidPack** [comment]
This isn't a tmodloader bug, but rather a bug with one of the mods you are using. I'd suggest disabling half until you figure out which mod is the problem.

**Comment by DonWaun** [comment]
Ok, thanks
