### ISSUE TITLE
Slow Motion and Teleporting Still Happening- Follow Up

### ISSUE THREAD

**Issue by DonWaun** [bluemagic123/tModLoader#92]
#91 
I posted the above issue earlier today and @JavidPack told me that it wasn't a tModLoader problem and to just disable some mods. I tried disabling some of the mods that I was using and the same problem kept happening to the point where all mods were disabled and the game was still in slow motion and teleporting, but my friend's game is running fine, please help with this issue, thanks.

**Comment by gorateron** [comment]
I still doubt this is a tModLoader issue as I'm not experiencing any 'slow motion and teleporting' issues myself with or without enabled mods. So you've disabled all mods on the server, your friend's game is running fine but yours isn't? Are you the host of the server?

**Comment by DonWaun** [comment]
No, he's hosting

**Comment by Chicken-Bones** [comment]
The typical reason for slow motion is that your game/graphics card can't keep up with the framerate. This will also cause teleporting because the server moves things faster than you do. In my case, I've had to set the tModLoader executables to run on my graphics card because they were autoselecting integrated graphics.

**Comment by gorateron** [comment]
Are issues still present, can this be closed @DonWaun ?

**Comment by DonWaun** [comment]
No I had to turn Frame Skip on in the options, thanks

**Comment by Rashaln** [comment]
I'm actually having a problem like this, but have found no fix for it, and I can only seem to trace it to tModLoader itself. For starters, I am running a tModLoader server on a Ubuntu 16.04 Live Linux box on my home network, connecting from a Windows 10 client. No matter how far I turn down Terraria settings; tiny window, everything off(except frame skip) or turned down, I lose 10-20 FPS (With frequent stuttering from frame skip) when connecting to my server. I've done a clean install of Terraria, and tested multiple configurations; vanilla Terraria runs fine in single- and multi-player at high graphical settings, tModLoader runs fine in single-player with and without mods, at the same graphical settings, but tModLoader multiplayer, with or without mods, has significant performance problems. My server doesn't appear to be the direct cause, as it stays under 50% of either core while tModLoader is running.

Some system info:
Client:
Terraria 1.3.4.4, TML 0.9.1
Windows 10 Pro 64bit build 14393
AMD Athlon 64 X2 4600+ 2.4ghz
4GB RAM
Nvidia GeForce 9600GT

Server:
Terraria Linux server 1.3.4.4, TML Linux 0.9.1
Ubuntu 16.04 LTS 64-bit (Running off USB with persistence)
Intel Core 2 Duo E8500 3.16ghz
4GB RAM
Onboard graphics

Likely I'm just missing something, (I've had bad luck with troubleshooting lately) but hopefully someone can help. I will provide more detailed information if necessary.
