### ISSUE TITLE
ForceItemPickup and DisableItemPickup hook request

### ISSUE THREAD

**Issue by JPANv2** [bluemagic123/tModLoader#93]
While making one of my mods where items are picked up directly into a bag equipped on the accessory slot, I ran into a problem: picking up the items (that will be destroyed by the OnPickup method) only works when there is at least one slot empty, or another of the item's type in the bag.
The desired function would be to pick up the item to be destroyed regardless of inventory space.

In order to make my mod work as inteneded, I propose (and code) two hooks that allow for item pickup manipulation

- "ForceItemPickup" allows for an item to be picked up regardless of inventory space. This is the hook I would use for my mod. This would also allow for mods to increase inventory space by moving the items to another inventory (such as the piggy bank) automatically, or to other custom-made slots, to pickup items into custom item stacks and to create buff/recovery items.

- "DisableItemPickup" allows for the reverse: the item not being picked up. This could be used for preventing a player from picking up certain items (such as mana crystals and hearts) when they do not need them, amongst other uses.

All the needed changes should be included below. I submit this on this format because I could not decompile terraria using the provided method in order to create patches. It should be a case of copy-paste either way.

[ForceItemPickup and DisableItemPickup.txt](https://github.com/bluemagic123/tModLoader/files/690560/ForceItemPickup.and.DisableItemPickup.txt)

Edit: created a safer version

**Comment by gorateron** [comment]
Forwarded for discussion..

**Comment by gorateron** [comment]
From jopo
>I guess the real problem is what should take priority, a mod preventing picking up items, or a mod saying yes, this item can be picked up even though there is no room
Probably preventing, since that would be a debuff or something

Also you can use the [OnPickup hook](https://github.com/bluemagic123/tModLoader/wiki/ModItem#public-virtual-bool-onpickupplayer-player) to do similar stuff as well
To us, this seemed a little heavy for what you're trying to achieve.

**Comment by JPANv2** [comment]
Maybe ForcePickup was not the best way to name it. What it should do is, if an item could not normally picked up (due to lack of inventory space), it will still allow OnPickup to be run on that item, and let OnPickup handle the decison of either the item will be picked up or not. As it is right now, OnPickup only runs on items that had their grab animations played, which does not happen when the inventory is full. The only alternative I can think of is to set item entry in the NebulaPickup array on GrabRange, Override GrabStyle so it is not grabbed like a nebula pickup and then use  OnPickup to clear the NebulaPickup entry for that item, which is most definitly unsafe and could conflict with other mods (and I'm not even sure it would work).

The DisableItemPickup takes precedence, allowing disabling of grabbing that item even if a ForcePickup for that item exists. That is DisableItemPickup would have higher priority than ForcePickup. This hook really could be replaced by  turning the item grab range to 0 and then using OnPickup to disable the item pickup and spawn a new item in its place, but this is also very inefficient.

**Comment by gorateron** [comment]
How about a bool forcePickup or something? You could use OnPickup to do whatever you want.

**Comment by JPANv2** [comment]
In my particular case, I created a bag that, when used in the accessory slot, gathers some items you pickup (such as ores or dirt and stone) into a Tag in the bag item, which can gather up to a certain limit (currently Int64.MaxValue, but customizeable). I would need a ForcePickup hook to allow picking up the vanilla items and other items into the bag, if enough room is available.
That requires custom logic to determine, at runtime, if the current item can or not be grabbed regardless of inventory space.

Could a bool offer that functionality?

**Comment by Chicken-Bones** [comment]
Yeah, I understand the use cases for some decent hook organisation here. I'll handle this one

**Comment by Chicken-Bones** [comment]
Done https://github.com/bluemagic123/tModLoader/commit/394aaa6c17e69021769d18c381d876db027b757a
